### ISSUE TITLE
Question: Change trace-id header

### ISSUE THREAD

**Issue by otheriault** [spring-cloud/spring-cloud-sleuth#1006]
The Spring Cloud Sleuth 2.0 Migration Guide mentions:

> If you want to change the headers that define span / trace id, etc. it's enough to set a custom version of the Propagation.Factory. 

Can you please provide an example of how to do this? Also, my custom trace id header will be a UUID instead of a pure hex string. Will this be an issue?

**Comment by adriancole** [comment]
if you have uuid format it can be parsed by stripping hyphens.

**Comment by marcingrzejszczak** [comment]
Here https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java you have an example of how we define a bean of factory type. You'd have to do sth similar

**Comment by adriancole** [comment]
here's an example alternative propagation thing:
https://github.com/openzipkin/zipkin-gcp/tree/master/propagation-stackdriver

**Comment by otheriault** [comment]
This was exactly what I was looking for. Thanks.
