### ISSUE TITLE
TracingFeignClient creates redundant span when FeignClient does not have a url variable

### ISSUE THREAD

**Issue by yshauly** [spring-cloud/spring-cloud-sleuth#1007]
I'm using version 2.0.0.RC2 of spring-cloud-starter-sleuth.

I've created a Feign Client for ServiceA which call ServiceB using Eureka (i.e. the `@FeignClient` annotation does not has a url variable but only name="ServiceB")

When executing the call and later inspecting it via Zipkin i've noticed that the span trace is ->
ServiceA->ServiceB->ServiceA

(from my check look like it is due to 2 executions of TracingFeignClient.execute())

Is it the correct outcome? if yes, please advise why.

**Comment by marcingrzejszczak** [comment]
Can you check the latest snapshots? If that doesn't help can you create a sample that replicates the issue?

**Comment by yshauly** [comment]
Issue is replicated for the latest snapshot version.
Attached zip files for both services (maven projects), print screen from Zipkin and the json.

[com-serviceA.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2099189/com-serviceA.zip)
[com-serviceB.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2099190/com-serviceB.zip)
![feign-sleuth](https://user-images.githubusercontent.com/40236682/41367667-5c653b16-6f48-11e8-8c1c-d3594a253675.jpg)

[span-trace.txt](https://github.com/spring-cloud/spring-cloud-sleuth/files/2099212/span-trace.txt)
