### ISSUE TITLE
updating to RC2 triggers a dependency cycle

### ISSUE THREAD

**Issue by jorgheymans** [spring-cloud/spring-cloud-sleuth#1011]
I just updated my app to RC2, without changing anything else, and now during startup i get this:

```
   servletEndpointRegistrar defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration.class]
      ↓
   healthEndpoint defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]
      ↓
   org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration
┌─────┐
|  dataSource
↑     ↓
|  scopedTarget.dataSource defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]
↑     ↓
|  org.springframework.boot.autoconfigure.jdbc.DataSourceInitializerInvoker
└─────┘
```

Is this really related to Sleuth or has something changed in sleuth that would reorder the configuration instantiation hence revealing this cycle ?

Reverting to RC1 makes the cycle go away, weird !

**Comment by marcingrzejszczak** [comment]
Are you using Spring Boot 2.0.3 ? Can you upload a sample somewhere?

**Comment by jorgheymans** [comment]
i was still on 2.0.1, upgrading to 2.0.3 makes the problem go away, thanks for FTL support :+1:

**Comment by marcingrzejszczak** [comment]
OMG I was terridied that there's a bug and we're on the verge of doing a GA release :P

**Comment by jorgheymans** [comment]
:-D no worries all good have a nice weekend !
