### ISSUE TITLE
Trace and Span ID consistency across services

### ISSUE THREAD

**Issue by kabennett** [spring-cloud/spring-cloud-sleuth#102]
According to @spencergibb the road map for Spring Cloud Sleuth includes passing the trace and span IDs across multiple services invoked via Feign (see https://github.com/spring-cloud-samples/tests/issues/3).

Any idea when this feature might make its way in to Spring Cloud Sleuth?  Prior to running across Spring Cloud Sleuth, I was using ThreadLocal/MDC to achieve a similar result, and I have developed a logging feature in our microservice architecture where all services send log data through Redis pub/sub channels while a separate logging service pulls the log data from Redis and logs them either to Elasticsearch or logback files depending on the channel the data is sent across.  It would be fantastic if we could correlate all of the traces/spans across the services, making our efforts to debug and analyze log data so much easier.

Keep up the fantastic work with Spring Cloud!  Believe me, it's improving enterprise capabilities by leaps and bounds!

**Comment by marcingrzejszczak** [comment]
Check the snapshot versions cause we already support Feign. I think that even latest Milestone has already supported that

**Comment by marcingrzejszczak** [comment]
Can we close this?

**Comment by kabennett** [comment]
Thanks, it works great when I switched to the snapshot.
