### ISSUE TITLE
Is there a pdf document file of Spring Cloud ？

### ISSUE THREAD

**Issue by stdupanda** [spring-cloud/spring-cloud-sleuth#1021]
It is very helpful for us to use the online help :  [Finchley.RELEASE](http://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/)， but I remember that there once was an pdf download link, I'd really like  to use the pdf document. WHERE can I find the spring cloud reference pdf :question:

**Comment by marcingrzejszczak** [comment]
We don't publish our documentation in a pdf format
