### ISSUE TITLE
Question: how to get tag values from Span in brave

### ISSUE THREAD

**Issue by sabtharishi** [spring-cloud/spring-cloud-sleuth#1024]
We are currently using Spring-cloud-sleuth 1.x. We are using Span tags to store data and then later just before closing the span we get all the tags from the span using Span.tags().
We are trying to migrate from 1.x to 2.x where I could see **brave.Span** class has method to add tag to it. But I do not know how to retrieve the tags from the span. 
Can you please explain how to retrieve the tags from the current span?

Note: We are not using zipkin as all logs (including Span details such as span name, duration and all tags) will be processed by Splunk.

**Comment by marcingrzejszczak** [comment]
You can only access it upon span reporting. `zipkin2.Span` contains the `tags` map that contains all the tags and you can use it regardless of the fact whether you're using Zipkin or not.

**Comment by fkrauthan** [comment]
@marcingrzejszczak is there no other way? We have a similar usecase where we extract span information in case of exceptions to report it to pager duty which will not longer work with Brave by the looks of it.

**Comment by marcingrzejszczak** [comment]
With Brave there's no other way. 

> We have a similar usecase where we extract span information in case of exceptions to report it to pager duty which will not longer work with Brave by the looks of it.

Why? Upon span reporting you can handle the fact that there's an exception or not. You can decide to ignore it, not send it to zipkin, report it to pager duty, etc.

**Comment by fkrauthan** [comment]
Well the big issue is that an exception does not necessarily wait until a span is reported. I think currently we just can't migrate to spring boot 2 as this is a full blocker. We also use the baggage items in spans to transmit information like exceptions to not report during test runs etc.

**Comment by marcingrzejszczak** [comment]
Let me see if i understand correctly. You've been using span tags to control the flow of your application? That sounds wrong (or i misunderstood sth).

Can you show an example of this situation that you mentioned?

**Comment by fkrauthan** [comment]
We have some error testing that triggers exceptions. A lot of that exceptions triggers a PagerDuty incident for us to investigate. But for CI testing we are expecting this exceptions so we use a span baggage item to pass down the list of expected exceptions for this particular api call across all services involved. I hope that makes it a bit more clear.

**Comment by adriancole** [comment]
sounds like you have two things you are looking for:
* propagating a list of exceptions (something the extra fields thing can do)
* reading back exceptions as they occur from arbitrary code in the request path

Can you share your implementation so we can consider all the options available? I imagine most exceptions occur in a way that downwards propagation might not work. A sample project that has the gist of what you are doing could help.

**Comment by adriancole** [comment]
PS distilled I think you are asking for the ability to readback in-flight data, but if specific to errors, that might be easier as there's `brave.ErrorParser` which you can customize and is invoked prior to reporting. If http-specific, there are parsers there as well, though in this case it might be even more helpful as you can access the raw request. That said, if you need to access the request, maybe you have a filter, and can already intercept the error regardless of brave :P

**Comment by adriancole** [comment]
another note is that all this stuff only applies when requests are sampled. NoopSpan are created when a thing is not sampled, which makes readback impossible as it was never read in the first place.

**Comment by fkrauthan** [comment]
Your first point "propagating a list of exceptions" is correct. We use that in our custom exception handler to determent if we need to send an exception that happen in the current micro services needs to be reported to pagerduty or not.

The second point is very similar to the first. In this custom exception handler (that is microservice specific) we read a lot information out of the span (like span name etc) to report that as meta information to PagerDuty for faster tracing and bug fixing.

I will post some more information about what we extract from a span tomorrow when I am back at work.

**Comment by aleskovets** [comment]
We have similar issue with migrating from sleuth 1 to sleuth 2. In our case we have old home-grown transaction id implementation (pre-zipkin era) that we use to pass-through between service calls pretty much like trace id. So "new" services have an ability to work in backward-compatible mode by accepting transactionId (SpanExtractor), storing it at Span level and then passing it with subsequent calls (SpanInjector) and logging (SpanLogger extension).

**Comment by aleskovets** [comment]
@devinsba, thank you for the hint! It looks very promising - I will have a look.
