### ISSUE TITLE
Improve support for reactor : Record span start at subscription phase, end after termination rather then invocation phase

### ISSUE THREAD

**Issue by kptfh** [spring-cloud/spring-cloud-sleuth#1027]
Currently, if I annotate method that returns Mono or Flux with NewSpan annotation,
span started and finished before actual subscription happened.
But I'd like to track span start on subscription and span finish on termination.

**Comment by kptfh** [comment]
Actually I can introduce tests that are broken and fix that eliminates this issue :)

**Comment by marcingrzejszczak** [comment]
Awesome, be our guest!

**Comment by kptfh** [comment]
[https://github.com/spring-cloud/spring-cloud-sleuth/pull/1028](https://github.com/spring-cloud/spring-cloud-sleuth/pull/1028)

**Comment by kptfh** [comment]
BTW, noticed that there is [TraceReactorConfiguration ](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/TraceReactorAutoConfiguration.java) related to reactor support, that register reactor hooks.
Can you explain briefly or give a link to doc how it expected to work and why there are to strategies: ConditionalOnNotWebApplication and ConditionalOnWebApplication

**Comment by robotmrv** [comment]
@kptfh, what about the case:
I want to log method invocation and it's input arguments and do it by aspect or manually inside a method body or just log smth inside it. 
If you start span only on subscribe then my Logger would get MDC from parent Span and I lose context.
And it is not desired result

**Comment by kptfh** [comment]
Agree. Seems we need 2 spans to be created: sync and reactive. One will work on invocation phase and one on subscribe/completion. What about: 
1) append "_reactor" to reactive span or 
2) just add "reactive" tag to reactive span

**Comment by marcingrzejszczak** [comment]
Hi! We haven't yet taken a look into this PR with @adriancole . Reactor instrumentation is very non trivial and before we add any new tags / features to it we need to very carefully analyze all changes.

**Comment by kptfh** [comment]
@marcingrzejszczak  To finish with reactor stuff we need to consider @robotmrv comment. 
Currently I use one span for to not intersecting periods: 
- method invocation (construction phase) (span not started yet but set in scope)
- subscription-completion
It will be correct to have 2 different spans for this.

**Comment by marcingrzejszczak** [comment]
Wdyt @adriancole?
