### ISSUE TITLE
@NewSpan does not generate a new span Id for methods using Mono.subscriberContext

### ISSUE THREAD

**Issue by nnanda2016** [spring-cloud/spring-cloud-sleuth#1030]
I am using:
- `Finchley.RELEASE` release train
- Spring boot `2.0.3`

If I use `Mono.subscriberContext()` in a method and annotate the method with `@NewSpan(name="myMethod")`, no new span ID is generated for that method.

Reference Repo: https://github.com/nnanda2016/springboot-sleuth-issue 

The method `com.demo.springboot.sleuth.UserApiHandler#getById2` is the buggy one I am talking about. No new span Id is generated if I invoke this method (URL to invoke this: `curl -v http://localhost:5002/users/ids/U1`).

If I remove `Mono.subscriberContext()`, everything is working fine as expected. Example method in this sample app is `com.demo.springboot.sleuth.UserApiHandler#getById` (URL to invoke this: `curl -v http://localhost:5002/users/U1`).

**Comment by kptfh** [comment]
@marcingrzejszczak  Investigating this issue found that there is a bug in my recent pull request (didn't set new span in trace context). Will add tests and fix soon.

**Comment by kptfh** [comment]
@nnanda2016 Don't use Tracing.current().currentTraceContext().get().spanId() in your app.  You should tracer.currentSpan().context().spanId() instead.
[https://github.com/spring-cloud/spring-cloud-sleuth/pull/1056#issuecomment-412571580](https://github.com/spring-cloud/spring-cloud-sleuth/pull/1056#issuecomment-412571580)

**Comment by nnanda2016** [comment]
@kptfh I checked the review comments on #1056 and I will change the code as per your suggestion; however, does this usage cause this issue?

**Comment by marcingrzejszczak** [comment]
For sure it doesn't help ;) @kptfh has done some improvements in the way reactor stuff is handled so that should help

**Comment by nnanda2016** [comment]
oh okay...where can i see those details? I want to make code change n verify.

**Comment by marcingrzejszczak** [comment]
The whole discussion is happening in the PR (https://github.com/spring-cloud/spring-cloud-sleuth/pull/1056). The previous changes were done here https://github.com/spring-cloud/spring-cloud-sleuth/pull/1028

**Comment by nnanda2016** [comment]
So, looks like I have to upgrade the version to `2.0.1`

**Comment by marcingrzejszczak** [comment]
Try with the latest `2.1.0` snapshots
