### ISSUE TITLE
HeaderBasedMessagingInjector(1.3.2 RELEASE) support in Spring sleuth core 2.0.0

### ISSUE THREAD

**Issue by sbogadhi** [spring-cloud/spring-cloud-sleuth#1032]
I was using the sleuth core 1.3.2 HeaderBasedMessagingInjector and override inject method to update the span baggage item but couldn't find a way to do the same in sleuth 2.0.0 RELEASE. Is there any support for the same in new version of sleuth 2.0.0.RELEASE or any other alternative way to achieve the same.

Existing code : 

```java
@Override
public void inject(Span span, SpanTextMap carrier) {
   super.inject(span, carrier);
   span.setBaggageItem("custom-field", "******");
}
```

Please suggest.

**Comment by marcingrzejszczak** [comment]
Hmm indeed for messaging we haven't provided an easy hook. We'll consider adding that of course. 

For now what you should do is to copy the `TracingChannelInterceptor` and modify the copy to suit your needs. You have to provide your own versions of:

```
final TraceContext.Injector<MessageHeaderAccessor> injector;
final TraceContext.Extractor<MessageHeaderAccessor> extractor;
```
