### ISSUE TITLE
Add a filter that allows to drop spans

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#1033]
Right now we allow to mutate a Zipkin Span before we send it to Zipkin. Sometimes, however, it could be useful to filter out certain spans.

Adding a filter (`SpanFilter`?) before the `SpanAdjuster`  would allow to filter out undesired spans.

**IMPORTANT** ONE MUST NOT DROP SPANS THAT HAVE CHILDREN!

**Comment by adriancole** [comment]
used with care this can be helpful until there's another way to do the same.

**Comment by adriancole** [comment]
technically someone can do this now by wrapping the reporter.

**Comment by adriancole** [comment]
See also https://github.com/openzipkin/zipkin/pull/2072 which is server-side

**Comment by adriancole** [comment]
See https://github.com/spring-cloud/spring-cloud-sleuth/pull/1096

**Comment by marcingrzejszczak** [comment]
Closing in favour of https://github.com/spring-cloud/spring-cloud-sleuth/pull/1096
