### ISSUE TITLE
Amazon SQS - exceeded maximum number of message attributes

### ISSUE THREAD

**Issue by milczarek** [spring-cloud/spring-cloud-sleuth#1036]
This is what I'm trying to send (I'm using spring-integration-aws):

```
GenericMessage [
        payload=myTestMessageBody, 
	headers={
		spanId=011932c59170cefa, 
		spanParentSpanId=d262bbbb05636814,  
		spanTraceId=08bc7db2456b5cef, 
		spanSampled=0, 
		X-B3-SpanId=011932c59170cefa, 
		X-B3-ParentSpanId=d262bbbb05636814, 
		X-B3-TraceId=08bc7db2456b5cef, 
		X-B3-Sampled=0, 
		id=0b2d53e6-73f5-09a6-7738-9f70a09022ef, 
		aws_queue=MY_TEST_QUEUE, 
		timestamp=1532437887059,
		nativeHeaders={
			spanTraceId=[08bc7db2456b5cef], 
			spanId=[4e92b45630c7fec6], 
			spanParentSpanId=[011932c59170cefa], 
			spanSampled=[0], 
			X-B3-TraceId=[08bc7db2456b5cef], 
			X-B3-SpanId=[4e92b45630c7fec6], 
			X-B3-ParentSpanId=[011932c59170cefa], 
			X-B3-Sampled=[0]}
	}]
```
	
Message has 12 attributes and 11 of them will be sent to AWS (attribute `nativeHeaders` will be omitted). 
Almost all headers are generated by sleuth, only `aws_queue` is custom and is being used by spring-integration-aws. Sleuth consumes all possible attributes (SQS message can have up to 10 attributes) leaving no place for user defined headers.

Is this desired behaviour?

**Comment by marcingrzejszczak** [comment]
Yes it is desired. If you don't want to do that you can copy the https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptor.java , modify the `MessageHeaderAccessor` to set only the camel case headers and register the `TracingChannelInterceptor` as a bean. That's the way to go until we allow easier hooking to change message headers.

**Comment by marcingrzejszczak** [comment]
Related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/1032

**Comment by milczarek** [comment]
I registered additional interceptor for getting rid of unwanted headers.
Thanks for your help.
