### ISSUE TITLE
Bug report. Span not close when ClientAbortException: java.io.IOException: Broken pipe

### ISSUE THREAD

**Issue by mm23504570** [spring-cloud/spring-cloud-sleuth#1038]
For some reason  throw the org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe(ex. client timeout).  The TraceFilter not close the span.
I have a sample application to test it. The /normal-request return a normal content and httpstatus is 200. 
The ClientAbortException throw from AbstractJackson2HttpMessageConverter.writeInternal. Then exception propagate to TraceFilter. After that, In detachOrCloseSpans 
```
TraceFilter:
if (httpStatusSuccessful(response) && tracer().isTracing()) {
				if (log.isDebugEnabled()) {
					log.debug("Closing the span " + span + " since the response was successful");
				}
				if (exception == null || !hasErrorController()) {
					tracer().close(span);
					clearTraceAttribute(request);
				}
			}
```
The status is 200 and exception is not null, cause span not close.  So the exception propagate to StandardHostValve.invoke

```
StandardHostValve: 

protected void throwable(Request request, Response response,
                             Throwable throwable) {
        ......
        // If this is an aborted request from a client just log it and return
        if (realError instanceof ClientAbortException ) {
            if (log.isDebugEnabled()) {
                log.debug
                    (sm.getString("standardHost.clientAbort",
                        realError.getCause().getMessage()));
            }
            return;
        }
        ....
```
Tomcat ignore the ClientAbortException. So that request not forward to the /error.
After all, Span have no chance to close.

### Version
spring-boot-starter-parent 1.5.14.RELEASE
spring-cloud.version Edgware.SR4

### My Workaround 
use HandlerExceptionResolver to handle this. Then return normal ModelAndView. But this bug mabye need fix.

**Comment by mm23504570** [comment]
[test-duplicate-trace-id.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2227577/test-duplicate-trace-id.zip)

**Comment by marcingrzejszczak** [comment]
Care for a PR ?

**Comment by mm23504570** [comment]
Ok. I'm trying to fix it.

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-sleuth/commit/707f3714d60bf280133b43bbfbc2ef84e1a2455f

**Comment by addozhang** [comment]
@mm23504570 I add an override the method`#getStatus()` and make it always return 200 to fall into below line.  Or it won't trigger this branch. 

https://github.com/spring-cloud/spring-cloud-sleuth/blob/707f3714d60bf280133b43bbfbc2ef84e1a2455f/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java#L244

**Comment by kartheektrilochan** [comment]
@marcingrzejszczak which version of spring-sleuth-core has this fix?
We are using spring-sleuth-core 2.2.0.Release and still having ClientAbortException issues.

Also the classes  from PR are not found in 2.2.0.Release Jar.
