### ISSUE TITLE
Proposition: split instrumentation package in sleuth core to modules

### ISSUE THREAD

**Issue by tdanylchuk** [spring-cloud/spring-cloud-sleuth#1042]
Spring Cloud Sleuth Code module has instrumentation package with all integration functionality inside it:
![image](https://user-images.githubusercontent.com/3741358/43311856-4c1c8868-9194-11e8-820d-278b44423193.png)
My proposition is to split integrations from core and make it more plug-n-playable as an example we can take a look on https://github.com/openzipkin/brave/tree/master/instrumentation or https://github.com/apache/camel/tree/master/components.

Benefits with this approach: 
1. logic separation
2. easier to contribute new instrumentation (since shared code is not touched) + easier development - you can focus only for you instrument and don't mess with other instruments tests
3. maybe someone are not okay with jar size (which could be pretty huge in case of additional instrumentations - see camel ;D ) so they would have a change to chose only needed ones

Of course there are drawbacks - but IMHO there would be more benefits from it.

**Comment by adriancole** [comment]
one of the reasons why sleuth is the way it is... is to facilitate
instrumentation which isn't in a shared library state.

For example, tracking reactor was a laborious activity and probably it
isn't in shape to be used generally. If it were, it would be in brave or a
different repo anyway. I think of sleuth instrumentation as package
private. I don't think we should keep adding heft to the main repo either,
only strategic things.

**Comment by tdanylchuk** [comment]
what if I need to add new instrumentation, I need to add it to brave repo with spring autoconfiguration?
for example for now I'm willing to have camel and spring data instruments to be added, where should I go with this?

**Comment by adriancole** [comment]
summary is to start with private repo, probably split
brave-instrumentation-X and brave-autoconfiguration-X as that's likely the
modularity that would end up best avoiding version conflicts of boot etc,
yet still allow core instrumentation to have minimal dependencies
