### ISSUE TITLE
Does Sleuth 2.0 work with Spring Boot 1.5.*

### ISSUE THREAD

**Issue by qcloop** [spring-cloud/spring-cloud-sleuth#1050]
Hi there,

I have an Spring Boot 1.5.13 app that uses RestTemplate as well as 3rd party lib that uses AsynHttp from https://github.com/AsyncHttpClient/async-http-client. As far as I know Spring Sleuth does not auto configure tracing for AsynHttp. In order to support tracing I probably need Brave dependencies, however it may clash with the way Sleuth leverages Brave pre Sleuth 2.0. Any suggestions?

**Comment by marcingrzejszczak** [comment]
Sleuth 2.x doesn't work with Boot 1.5
