### ISSUE TITLE
Duplicate trace-ids are generated in edgeware.sr3 and org.springframework.cloud:spring-cloud-sleuth-core 1.3.3.RELEASE

### ISSUE THREAD

**Issue by harinathbk** [spring-cloud/spring-cloud-sleuth#1051]
Hi All,

I have noticed duplicate trace-ids generated with edgeware.sr3 and org.springframework.cloud:spring-cloud-sleuth-core 1.3.3.RELEASE. May i know is there any bug in sleuth 1.3.3.RELEASE code? 

Harinath.

**Comment by marcingrzejszczak** [comment]
Please do not cross post

**Comment by harinathbk** [comment]
Apologize.
