### ISSUE TITLE
Spring Sleuth trace/span IDs not available in HttpTraceRepository only if Mono response has body

### ISSUE THREAD

**Issue by adammichalik** [spring-cloud/spring-cloud-sleuth#1054]
_This is a copy/follow-up of https://stackoverflow.com/q/51769056/466738_

Versions: Spring Boot 2.0.4.RELEASE/2.1.0.BUILD-SNAPSHOT, Spring Cloud Finchley.SR1

I have logging in an Actuator HttpTraceRepository bean which is invoked after a Mono response has been written. If the response has no body (only status) then I get the trace/span IDs in the log message. If however the response has a body, the log messages do not have the trace/span IDs **unless** they are handled by the same NIO thread that handled a "no body" request previously.

Here is a sample application that exposes the issue.

```java
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Bean
    public WebClient webClient() {
        return WebClient.create();
    }
}

@Component
class AccessLoggingHttpTraceRepository implements HttpTraceRepository {

    @Override
    public List<HttpTrace> findAll() {
        return null;
    }

    @Override
    public void add(HttpTrace trace) {
        LogFactory.getLog("netty.Access").info("ACCESS");
    }
}

@RestController
@RequestMapping("/test")
class PublicationFamilyEndpoint {

    @Autowired
    private WebClient webClient;

    @GetMapping("/body")
    public Mono<String> testWithBody() {
        return callWebClient();
    }

    @GetMapping("/nobody")
    public Mono<ResponseEntity<Object>> testWithoutBody() {
        return callWebClient().map(s -> ResponseEntity.ok().build());
    }

    private Mono<String> callWebClient() { // doesn't matter what happens here - this is just an example of a reactive call
        return webClient.get().uri("http://example.com").retrieve().bodyToMono(String.class);
    }
}
```

Dependencies: spring-boot-starter-actuator, spring-boot-starter-webflux, spring-cloud-starter-sleuth

When I call

```
curl -sS 'http://localhost:8080/test/nobody'
```

I get logs

```
[-,ff016a7a5a9aadbb,ff016a7a5a9aadbb,false] 5741 --- [ctor-http-nio-4] netty.Access: ACCESS
```

When I call

```
curl -sS 'http://localhost:8080/test/body'
```

I get logs

```
[-,,,] 5741 --- [ctor-http-nio-1] netty.Access: ACCESS
```

See however this series of request logs. The first two are to the `/nobody` endpoint and the rest are to the `/body` endpoint. If the `/body` request is handled by the same thread as a `/nobody` request previously, the trace/span IDs are present.

```
[-,78bbe5342dbcd517,78bbe5342dbcd517,false] 7091 --- [ctor-http-nio-3] netty.Access: ACCESS
[-,941cc2e3afc9bbc4,941cc2e3afc9bbc4,false] 7091 --- [ctor-http-nio-3] netty.Access: ACCESS
[-,,,] 7091 --- [ctor-http-nio-1] netty.Access: ACCESS
[-,,,] 7091 --- [ctor-http-nio-2] netty.Access: ACCESS
[-,5728dcc1559f64ae,5728dcc1559f64ae,false] 7091 --- [ctor-http-nio-3] netty.Access: ACCESS
[-,,,] 7091 --- [ctor-http-nio-4] netty.Access: ACCESS
[-,,,] 7091 --- [ctor-http-nio-1] netty.Access: ACCESS
[-,,,] 7091 --- [ctor-http-nio-2] netty.Access: ACCESS
[-,00241261eb9931bd,00241261eb9931bd,false] 7091 --- [ctor-http-nio-3] netty.Access: ACCESS
[-,,,] 7091 --- [ctor-http-nio-4] netty.Access: ACCESS
```

**Comment by kptfh** [comment]
@adammichalik I've added AccessLoggingHttpTraceRepository  into this test [https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/SleuthSpanCreatorAspectWebFluxTests.java](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/SleuthSpanCreatorAspectWebFluxTests.java) and get all "netty.Access" logs with trace/span IDs. Can you double check it in this test?

**Comment by adammichalik** [comment]
@kptfh I'm sorry, can you point me more specifically? I don't see any mention of `HttpTraceRepository` anywhere in `SleuthSpanCreatorAspectWebFluxTests` or anywhere in the whole PR #1056.

**Comment by kptfh** [comment]
I've just added it locally to the code to check your issue. You can checkout project and do the same. In this test there is already WebFlux app returning responses with body so you just need to add `AccessLoggingHttpTraceRepository` to this class to verify issue.

**Comment by marcingrzejszczak** [comment]
Remember to test against 2.1 sleuth

**Comment by adammichalik** [comment]
The `SleuthSpanCreatorAspectWebFluxTests` starts with a SERVLET web application type and then the trace/span ID is present. Changing it to REACTIVE causes the log message to have an empty trace/span ID. My app is running as a reactive app on Netty while the test was running as a servlet app on Tomcat.

See this gist with an updated test: https://gist.github.com/adammichalik/2ace93e031dff79d1d992c4d3b1aa812

What I did is:
* added `properties = {"spring.main.web-application-type=reactive"}` to `@SpringBootTest`
* removed `@EnableAutoConfiguration` from the test class (duplicated in `TestConfiguration`) and added `exclude = {org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration.class, ReactiveUserDetailsServiceAutoConfiguration.class}` on `TestConfiguration` to disable Spring Security
* added `AccessLoggingHttpTraceRepository` and configured it as a bean

Now the logs look like this

```
2018-08-15 12:06:23.914  INFO [-,,,] 43689 --- [o-auto-1-exec-1] netty.Access                             : ACCESS
```

**Comment by marcingrzejszczak** [comment]
Meh, I haven't had time to look into it, yet. Can you take a look at the order of the `TraceFilterFunction` being applied vs. the `TraceRepository`? Meaning, that most likely the `TraceRepository` is applied at a wrong time.

**Comment by adammichalik** [comment]
@marcingrzejszczak I don't think anything pops up at me... One thing I noticed though is that the `HttpTraceRepository` is invoked during `onComplete()` of the subscription. In Sleuth's `ScopePassingSpanSubscriber` `onComplete()` (and `onError()`) does not surround the subscriber invocation with `try (Tracer.SpanInScope inScope = this.tracer.withSpanInScope(this.span))`, contrary to invocations of other `Subscription`/`Subscriber` methods.

Changing to 

```java
	@Override public void onComplete() {
		try (Tracer.SpanInScope inScope = this.tracer.withSpanInScope(this.span)) {
			this.subscriber.onComplete();
		}
	}
```

causes the span/trace IDs be printed in the logs in the `HttpTraceRepository`.

**Comment by kptfh** [comment]
Don't anybody has arguments against wrapping `onComplete()` (and `onError()`) in `ScopePassingSpanSubscriber ` with `try (Tracer.SpanInScope inScope = this.tracer.withSpanInScope(this.span))`  ?
