### ISSUE TITLE
why Sampler doesn't support request params

### ISSUE THREAD

**Issue by lly835** [spring-cloud/spring-cloud-sleuth#1055]
i want all request
```
if (request.getHeader("uid").equals("123")) {
    send to zipkin
}else {
    use PercentageBasedSampler
}
```

Sampler should According to the user's request.

**Comment by marcingrzejszczak** [comment]
You can. Just create sth similar to https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/SleuthHttpSampler.java#L30

**Comment by lly835** [comment]
@marcingrzejszczak 
version 2.0+ feture?

**Comment by marcingrzejszczak** [comment]
Yes. Please read the documentation before submitting questions - https://cloud.spring.io/spring-cloud-static/Finchley.SR1/single/spring-cloud.html#_customizations

**Comment by lly835** [comment]
i use  Edgware.SR1 and spring-cloud-sleuth 1.3.1.RELEASE, Do you have any suggestions?

**Comment by marcingrzejszczak** [comment]
I suggest you upgrade to `FInchley.SR1`. If that's not possible, I suggest that you upgrade to `Edgware.SR4` and try to work this around by applying a filter before the `TraceFilter` that registers what's there in the request, puts the request contents to `ThreadLocal`, then create your own `Sampler` that will retrieve that value, and basing on its contents perform sampling.

We migrated to Brave for a reason so my suggestion is to upgrade to `Finchley`.
