### ISSUE TITLE
traceid not retained when using Netty4ClientHttpRequestFactory and AsyncRestTemplate

### ISSUE THREAD

**Issue by JasonNorth** [spring-cloud/spring-cloud-sleuth#1057]
spring boot version: 4.0.4.RELEASE
spring cloud sleuth version:  4.0.1.RELEASE

When using ```AsyncClientHttpRequestInterceptor``` with the default ```AsyncClientHttpRequestFactory``` the traceids reported by the interceptor are as expected, i.e. the same as other log statements for the request.  This always works.

However, when using ```Netty4ClientHttpRequestFactory``` for some time the traceid start to be different between the logs in the interceptor and other parts of the request.  It does not happen immediately but always happens eventually.

The migration guide contains this statement:

```
It seems that we have overengineered the async trace context passing. It seems that with the async template's interceptor with a wrapper around the ListenableFutureCallback we don't need to wrap the connection factories anymore.

TODO: Please provide feedback if that's the case. Current tests prove that it's good enough.
```

https://github.com/spring-cloud/spring-cloud-sleuth/wiki/Spring-Cloud-Sleuth-2.0-Migration-Guide

I strongly suspect this is just the way I have set things up but please can someone help?  For example, what is meant by a ```wrapper around the ListenableFutureCallback```?  Is that referring to ```TracingAsyncClientHttpRequestInterceptor``` or do I have to do something explicit?

Below is some example code:

```java
@Configuration
@EnableAutoConfiguration
public class AsyncRestTemplateConfiguration {
    @Autowired
    private AsyncClientHttpRequestFactory asyncClientHttpRequestFactory;

    @Autowired
    private MyInterceptor myInterceptor;


    @Bean
    public AsyncRestTemplate myAsyncRestTemplate() {
        // this does not give the correct traceid in interceptor
        AsyncRestTemplate asyncRestTemplate = problem();

        // if above is swapped for below then this does give the correct traceid in interceptor
//        AsyncRestTemplate asyncRestTemplate = working();

        asyncRestTemplate.getInterceptors().add(myInterceptor);
        return asyncRestTemplate;
    }

    private AsyncRestTemplate problem() {
        return new AsyncRestTemplate(asyncClientHttpRequestFactory);
    }

    private AsyncRestTemplate working() {
        return new AsyncRestTemplate();
    }
}

@Configuration
@EnableAutoConfiguration
public class AsyncClientHttpRequestFactoryConfiguration {
    @Bean
    public AsyncClientHttpRequestFactory clientHttpRequestFactory() throws SSLException {
        return new Netty4ClientHttpRequestFactory();
    }
}
```

Thanks.

**Comment by marcingrzejszczak** [comment]
>  It does not happen immediately but always happens eventually.

Can you elaborate more on this?

**Comment by JasonNorth** [comment]
@marcingrzejszczak for example, I just tested it and after restarting the spring boot application the first 8 requests did not show the problem but then every request did.

**Comment by marcingrzejszczak** [comment]
can you create a sample application that replicates the problem?

**Comment by JasonNorth** [comment]
Sample application that replicates the problem:
https://github.com/JasonNorth/netty-sleuth-problem

**Comment by JasonNorth** [comment]
if it helps if I put org.springframework Loggers to TRACE level the first time the traceid is wrong is the first time any response is handled, e.g.:

```
Thrd=nioEventLoopGroup-2-2|Lggr=o.s.c.s.l.Slf4jCurrentTraceContext|Msg=Starting scope for span: ab39fca8d9b5f76c\/3fa8e3a1d419327b|
```

**Comment by michael-barker** [comment]
Due to the non-blocking nature of Netty a single thread handles many requests.  Sleuth sets the trace ID in MDC but by the time your log statement is executed there's no guarantee that another request isn't also being handled on the same thread and updated trace ID value in MDC to a different value.  I think this blog post gives a good description of what's happening, [Contextual Logging with Reactor Context and MDC](https://simonbasle.github.io/2018/02/contextual-logging-with-reactor-context-and-mdc/).

Until there's a reactive logging framework I think the only option is to create utilities to make it easier to temporarily set the trace ID in MDC.

**Comment by JasonNorth** [comment]
thanks for the feedback.

If I use the default ```org.springframework.web.reactive.function.client.WebClient``` class for client calls rather than ```AsyncRestTemplate``` and netty then it all seems to work, i.e. sleuth seems to retain the correct traceids.  As WebClient appears to use the ```reactor.ipc.netty``` classes by default I would like to know if you think this is really working or perhaps I am just getting lucky as you suggest I need a reactive logging framework?

**Comment by marcingrzejszczak** [comment]
BTW if you're using directly the Reactor Netty's `httpClient` and Sleuth in latest `2.1` snapshots, then things are currently broken and the instrumentation doesn't work.

**Comment by JasonNorth** [comment]
@marcingrzejszczak thanks - good to know but I am not using snapshots.

**Comment by marcingrzejszczak** [comment]
Hey @JasonNorth, starting from Spring 5 we deprecated both `AsyncRestTemplate` and `Netty4ClientHttpRequestFactory` so we're not planning to improve support for those classes. Please migrate to `WebClient` and `Netty4ClientHttpRequestFactory`.
