### ISSUE TITLE
Change the IDs from UUIDs to random 64bit

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#106]
The `IdGenerator` should no longer have `UUID` but a `long`

```
public interface IdGenerator {

    /**
     * Generate a new identifier.
     * @return the generated identifier
     */
    long generateId();

}
```

The default implementation of the IdGenerator should have a `Random` injected that can be overiden (via a setter for example).

**Comment by adriancole** [comment]
I don't agree with us exposing an interface for this. Sleuth will be less complicated an easier to support if features such as id customization came after diverse need was established. Just use Random.

**Comment by adriancole** [comment]
For example, designing an interface to control ids isn't likely to be as simple as just making a Func0. Ex. in Brave, the PR on this topic was more experienced *and also abandoned*. If we eagerly design a span id generator, we now have a legacy which might mean breaking it later.

If we want sleuth to be a clean and maintainable project, we need to consider aspects such as the [rule of three](http://blog.codinghorror.com/rule-of-three/) when choosing whether or when to create something.

```java
/**
 * Allows you to control how ids are generated. For example, implementations
 * can encode where in the call tree the span originates from, or use alternate
 * random number generators.
 */
// Intentionally single-method to be implementable with a lambda
public interface SpanIdGenerator {

    /** Returns the next trace id, or span id if parent is null. */
    SpanId nextSpanId(@Nullable SpanId parent);

    final class Default implements SpanIdGenerator {
        private final Random random = new Random();

        @Override
        public SpanId nextSpanId(@Nullable SpanId parent) {
            long nextLong = random.nextLong();
            if (parent == null) {
                return SpanId.create(nextLong, nextLong, null);
            }
            return SpanId.create(parent.getTraceId(), nextLong, parent.getSpanId());
        }
    }
}
```

**Comment by marcingrzejszczak** [comment]
This

> Ex. in Brave, the PR on this topic was more experienced and also abandoned. 

Convinces me. So in every place where ATM were using the interface we would call

```
new Random().nextLong()
```

?

**Comment by marcingrzejszczak** [comment]
Done in https://github.com/spring-cloud/spring-cloud-sleuth/commit/82ed9f78a16ef34db48979762e7bec606d20ff9c
