### ISSUE TITLE
Allow customization of span names for Spring Messaging

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-sleuth#1062]
https://github.com/spring-cloud/spring-cloud-gcp/issues/953

Spring Cloud Sleuth automatically instruments Spring Cloud Stream and Spring Integration when sending/processing messages.  When sending a message, the generated span name is always "send". This is not customizable like the HTTP span names.

Introduce a mechanism to allow easy span customization.

**Comment by meltsufin** [comment]
@marcingrzejszczak When will this land in snapshots?

**Comment by marcingrzejszczak** [comment]
Once we do it in Brave

**Comment by marcingrzejszczak** [comment]
Also, @meltsufin, if you don't want to wait, you can copy what we've done in Sleuth, register your own version of `TraceChannelInterceptor` and inject a bean to allow customization of names.

**Comment by meltsufin** [comment]
I can wait. :smile: Thanks!

**Comment by adriancole** [comment]
we have limited horsepower. If someone wants to try to help with this, they can. It would need to be portable over jms, kafka, rabbit at least. Otherwise, tell people to use interceptors

**Comment by marcingrzejszczak** [comment]
So with the new Sleuth & Stream approach this should be easier since you'll be able to access the span in your function or leverage the `MessagingSleuthOperator` utility class. I can help you apply either of those if you're interested @meltsufin @saturnism

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
