### ISSUE TITLE
Support building current trace context with scope decorators

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#1063]
Right now, we allow people to override CurrentTraceContext, which is cool. we can do things like switch propagation etc. Would be neat if things like SLF4J could be made additive to whatever the primary context backend choice is. This would prevent people from knowing too much and/or excessive wrapping.

For example, we can provide a bean of type `CurrentTraceContext.Builder` which has a list builder method for `ScopeDecorator`. These scope decorators can implement SLF4J, logging or even things like census integration.

For example, we could list injection to create the final `CurrentTraceContext`:

ex
```java
@Bean CurrentTraceContext currentTraceContext(CurrentTraceContext.Builder builder, List<ScopeDecorator> scopeDecorators) {
  for (ScopeDecorator scopeDecorator : scopeDecorators) {
    builder.addScopeDecorator(scopeDecorator);
  }
  return builder.build();
}
```

cc @bogdandrutu @anuraaga @trustin @kojilin
See https://github.com/bogdandrutu/oc-spring-boot
See https://github.com/openzipkin/brave/pull/683
See https://github.com/line/armeria/pull/1322

**Comment by devinsba** [comment]
I fully agree here, one of the things that has kept me from implementing baggage in our system is the need for a custom implementation to handle the MDC/Propagation case
