### ISSUE TITLE
Sleuth (1.3.x) with Kafka Binder Replaces User ...headers Config

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-sleuth#1064]
https://gitter.im/spring-cloud/spring-cloud-stream?at=5b7b8ecfc53ee54c187df141

The `TraceStreamEnvironmentPostProcessor` adds a new property source containing the sleuth headers to embed (for older Kafkas). It attempts to find the starting index at which to add the headers; however, at that time, the `application.properties` `PropertySource` is not yet in the environment so the first 6 user headers are overridden.

```java
@SpringBootApplication
@EnableBinding(Processor.class)
public class Gitter3813xApplication {

	public static void main(String[] args) {
		SpringApplication.run(Gitter3813xApplication.class, args);
	}

	@Bean
	public ApplicationRunner runner(MessageChannel output, Environment environment) {
		return args -> output.send(MessageBuilder.withPayload("foo").setHeader("foo", "bar").build());
	}

	@StreamListener(Processor.INPUT)
	public void listen(Message<?> in) {
		System.out.println(in);
	}

}
```

```properties
spring.cloud.stream.kafka.binder.headers=foo
spring.cloud.stream.bindings.input.destination=gitter38
spring.cloud.stream.bindings.input.group=gitter38
spring.cloud.stream.bindings.output.destination=gitter38
```
**Result (no `foo` header)**
>GenericMessage [payload=foo, headers={spanId=a002f4490b3700b7, spanTraceId=a002f4490b3700b7, kafka_offset=5, messageSent=true, id=1948a26f-9c18-b2b2-d168-d095ef2cff93, spanSampled=0, kafka_receivedPartitionId=0, contentType=text/plain, kafka_receivedTopic=gitter38}]

**application.properties `PropertySource`**
![screen shot 2018-08-21 at 11 07 22 am](https://user-images.githubusercontent.com/483832/44411269-1ee4e580-a534-11e8-8948-ac70bf2d04fd.png)

**Sleuth**
![screen shot 2018-08-21 at 11 07 44 am](https://user-images.githubusercontent.com/483832/44411361-4d62c080-a534-11e8-816e-a6467c7d9740.png)

**Code trying to find index**
![screen shot 2018-08-21 at 11 13 15 am](https://user-images.githubusercontent.com/483832/44411409-71be9d00-a534-11e8-9990-648afb2d0853.png)

**Environment at that time (hence `null` property)**
![screen shot 2018-08-21 at 11 15 39 am](https://user-images.githubusercontent.com/483832/44411473-931f8900-a534-11e8-8f04-3c52686f6c7f.png)

**Comment by garyrussell** [comment]
This is a bit of a hack, but it works around the problem...

```properties
spring.cloud.stream.kafka.binder.headers=x,x,x,x,x,x,foo
```

**Comment by garyrussell** [comment]
The binder environment post processor runs after the `TraceStreamEnvironmentPostProcessor`.

![screen shot 2018-08-21 at 12 27 12 pm](https://user-images.githubusercontent.com/483832/44415200-d29ea300-a53d-11e8-97a3-dee2b3bc82a1.png)

I think we need to implement `Orderable` in both places and coordinate the order, to ensure that the Kafka PP runs first.

/cc @olegz @sobychacko @sabbyanandan

**Comment by garyrussell** [comment]
On second thought, no; that's not related; it's the `application.properties` `PropertySource` that's missing.

**Comment by marcingrzejszczak** [comment]
> I think we need to implement Orderable in both places and coordinate the order, to ensure that the Kafka PP runs first.

So I guess I should update the Sleuth ones after you update yours?

> however, at that time, the application.properties PropertySource is not yet in the environment so the first 6 user headers are overridden.

Wouldn't updating the insertion algorithm be enough? I mean we shouldn't override any headers that the user has already provided.

**Comment by garyrussell** [comment]
>So I guess I should update the Sleuth ones after you update yours?

No, as I mentioned in my follow-up, that order is not important since the required properties are not set up by the Stream property source.

>Wouldn't updating the insertion algorithm be enough? I mean we shouldn't override any headers that the user has already provided.

To be honest, I am not entirely sure what's going on; I need to get back to it, but it seems the environment objects are different.

**Comment by marcingrzejszczak** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-sleuth/commit/d1dba3008641d048860067ce789ea1060dd2b95f
