### ISSUE TITLE
Wrong span name when request failing with a 401

### ISSUE THREAD

**Issue by madgnome** [spring-cloud/spring-cloud-sleuth#1065]
We're using spring cloud sleuth 2.01 with webflux and spring security. 
It all works fine except in case of authorization error, in this case the span name is `get` instead of `get /api/{cloudid}/etc` as expected.

**Possible cause:**
- `TraceWebFilter` uses `HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE` to generate the span nam
- `HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE` is set by `RequestMappingInfoHandlerMapping#handleMatch`
- unfortunately this is not called in case of authentication error because the request will be rejected by Spring Security filter.

spring-cloud-sleuth version: 2.0.1

**Comment by marcingrzejszczak** [comment]
@wilkinsona @jkschneider - have you seen a similar problem with the `BEST_MATCHING_PATTERN_ATTRIBUTE`?

**Comment by madgnome** [comment]
@jkschneider `MetricsWebFilter` has the same problem, on 401 the `uri` tag is `UNKNOWN`

**Comment by jkschneider** [comment]
@madgnome This is intentional in Micrometer. Doing anything else would effectively expose your monitoring system to an attack vector that allows a malicious party to hit knowingly false URIs, trusting that spring-security would block access with 401.

You're of course welcome to override the default tagging strategy if you'd like.

**Comment by madgnome** [comment]
Ah yeah makes sense! 🤦‍♂️

**Comment by jkschneider** [comment]
> 🤦‍♂️ 

Don't feel bad. We entirely missed this in the initial implementation!

**Comment by marcingrzejszczak** [comment]
@madgnome I see you started working on a PR. How is it going?

**Comment by madgnome** [comment]
Oops, forgot about that PR, I'll fix the conflicts ASAP

**Comment by marcingrzejszczak** [comment]
@madgnome how is it going? :)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
