### ISSUE TITLE
webFlux+seluth Performance decline

### ISSUE THREAD

**Issue by zhl1987** [spring-cloud/spring-cloud-sleuth#1067]
when I use seluth on webFlux Pattern,the performance decreased significantly.

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem or shows some benchmarks? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by zhl1987** [comment]
Sorry, I can't upload code because of privacy restrictions.I will briefly describe my question.
My project is based spring-boot 2.0.2.RELEASE and spring-cloud Finchley.RELEASE ,
1、pom.xml dependencies  as follows, and in application.properties set spring.sleuth.sampler.probability=1.0.
_<dependencies>
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter</artifactId>
</dependency>
<dependency>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
</dependency>
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-webflux</artifactId>
</dependency>
</dependencies>_

Under 200 user concurrent, TPS is 27423.9 and average response time is 7ms.
2、when I add sleuth dependency to pom.xml dependencies ,and other conditions are the same.Under 200 user concurrent, TPS is 6452 and average response time is 30ms.

_<dependency>
<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-sleuth</artifactId>
</dependency>_

**Comment by marcingrzejszczak** [comment]
WIthout the project it will be impossible to help you, sorry.

**Comment by zhl1987** [comment]
[IdeaProjects.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2386726/IdeaProjects.zip)
run the project eureka-server,trace-1,trace-2 one by one ,then use jmeter
test http://localhost:9901/trace-1,the performance decreased significantly.

**Comment by zhl1987** [comment]
> WIthout the project it will be impossible to help you, sorry.

hello，I upload my project already, can you give me a hand,thank you a lot.

**Comment by bradbowd** [comment]
ya we've been seeing the same performance issues here too, sleuth while valuable has some really terrible user support and documentation

**Comment by marcingrzejszczak** [comment]
@bradbowd what exactly is missing with the documentation and the user support?

**Comment by marcingrzejszczak** [comment]
@bradbowd I don't understand your reaction. Can you elaborate please?
