### ISSUE TITLE
Add configuration to put baggage automatically to MDC

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#1071]
with this change you can set a property to pass the values from baggage automatically to MDC

**Comment by tdanylchuk** [comment]
along with this, baggage could be propagated to span tags, so they can be collected by zipkin to enable trace filtering by baggage.

**Comment by adriancole** [comment]
>
> along with this, baggage could be propagated to span tags, so they can be
> collected by zipkin to enable trace filtering by baggage.
>
please be careful with this as it will dramatically reduce cost
effectiveness of storage. Usually you do not need to copy a field to every
span (except the trace ID). IOTW, if such a feature happens, please make it
very very very very optional or parsimoniously handled.

Right now, anyone can do this themselves by setting up a custom parser.

>
