### ISSUE TITLE
<2.0 only: implement "b3 single" header format

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#1077]
The following is about backporting support for "b3 single" format for Sleuth versions that don't use Brave.

---
As discussed on https://github.com/openzipkin/b3-propagation/issues/21 and first implemented here: https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/propagation/B3SingleFormat.java https://github.com/openzipkin/brave/blob/master/brave/src/test/java/brave/propagation/B3SingleFormatTest.java

Let's support at least reading "b3" header from a single string, most commonly traceid-spanid-1
It would also be nice to support optionally writing this, especially in message providers or others with constrained environments.

Brave currently has a property like this, but its name could change with feedback:
```java
    /**
     * When true, only writes a single {@link B3SingleFormat b3 header} for outbound propagation.
     *
     * <p>Use this to reduce overhead. Note: normal {@link Tracing#propagation()} is used to parse
     * incoming headers. The implementation must be able to read "b3" headers.
     */
    public Builder b3SingleFormat(boolean b3SingleFormat) {
      this.b3SingleFormat = b3SingleFormat;
      return this;
}
```

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-sleuth/commit/b7302a61f6ed068afe9e64b03c2873ddd68260ea

**Comment by marcingrzejszczak** [comment]
@shakuzen:
> I think sampled could also be the only field, for instance when just sending an unsampled decision 0. It's one of the examples here: openzipkin/b3-propagation#21 (comment)
Also, it could be d in the third position when the debug flag is set, which this method will parse but the caller doesn't seem to handle it currently.
> Another thing is the case when a parentId is sent doesn't seem to be handled (there will be 4 --separated fields, not 3). It can be omitted for the messaging extractor/injector, I guess, but the HTTP implementation seems like it should handle it.

**Comment by adriancole** [comment]
thx

**Comment by marcingrzejszczak** [comment]
fixed via https://github.com/spring-cloud/spring-cloud-sleuth/commit/bef30d698bc5f7de5d821b5288955ef6e509480c

**Comment by alonbl** [comment]
Hi,
I see this is for <2.0 and I wounder what happens in >2.0, is there a reason why not support the single b3 header format? I am just wondering.
Thanks!

**Comment by shakuzen** [comment]
> I wounder what happens in >2.0

Sleuth >2.0 uses Zipkin's official Java tracer [Brave](https://github.com/openzipkin/brave/) which has support for b3 single header. This issue was about making b3 single header also possible in <2.0 which did not use the Brave library.

**Comment by alonbl** [comment]
> > I wounder what happens in >2.0
> 
> Sleuth >2.0 uses Zipkin's official Java tracer [Brave](https://github.com/openzipkin/brave/) which has support for b3 single header. This issue was about making b3 single header also possible in <2.0 which did not use the Brave library.

Thanks! I cannot see anywhere in sleuth document how do I configure what outgoing format to use.
