### ISSUE TITLE
Extra propagation-keys are (also) removed from messages, and henceforth unavailable

### ISSUE THREAD

**Issue by timtebeek** [spring-cloud/spring-cloud-sleuth#1083]
Hi! Using `Finchley.SR1` I'd like to take advantage of `spring.sleuth.propagation-keys` to propagate a few internal headers with my Kafka mesages, which we currently do manually. However, when I add the property to our configuration, the extra headers are stripped before they reach my `@KafkaListener`, which then raises a `MessageHandlingException: Missing header 'corporate_trace_id' for method parameter type [class java.lang.String]`.

This commit introduces the problem to a demo project of mine:
https://github.com/timtebeek/sleuth-kafkalistener/commit/eb68995605abdb1d9051b15cc5415e80f6b37cc4#diff-9588a0ac6aee0ef700ab1dc6a13d0e04R71

I'm not sure if this is a Brave or Sleuth issue; reading `ExtraFieldPropagation.get` it seems I should be able to extract the value that way. Should I update my code to do that? Or is this something that should work out of the box? I was surprised to see a sleuth property break my listener, hence the question here.

**Comment by marcingrzejszczak** [comment]
@timtebeek have you checked this on 2 separate applications? Sometimes the tests might be misleading (I'm not saying that sth is not wrong here)

**Comment by timtebeek** [comment]
Yes it's in two projects, one at work, and the replication project linked
above. It's actually caused by this line:
https://github.com/openzipkin/brave/blob/release-5.2.0/instrumentation/kafka-clients/src/main/java/brave/kafka/clients/TracingConsumer.java#L89
But looking at the current master branch for brave that has since been
changed/moved. I realized after I posted here it's in brave instead, sorry
about that.

**Comment by marcingrzejszczak** [comment]
No problem. I'll close this one then.
