### ISSUE TITLE
Extra field propagation not having x- format

### ISSUE THREAD

**Issue by iRohitBajaj** [spring-cloud/spring-cloud-sleuth#1085]
Question - 

I am facing an issue while trying to add a baggage key that represents correlationid that comes from a calling client to a server where sleuth (2.0.0.RELEASE) and zipkin start trace and first span and cummunication goes through a series of applications all of which are configured to use sleuth and zipkin. Per documentation it says that any baggage key gets sent across as x-baggage-{key_name} header, but what I am observing is it comes as baggage-{key-name} and it is loosing x- part; am I missing something?

**Comment by marcingrzejszczak** [comment]
Fixed missing `x-` in the method
