### ISSUE TITLE
Default trace sampler for Zipkin should depend on the existence of a RefreshScope bean not class

### ISSUE THREAD

**Issue by asibross** [spring-cloud/spring-cloud-sleuth#1086]
If refresh scope is explicitly disabled (i.e. by excluding `org.springframework.cloud.autoconfigure.RefreshAutoConfiguration`), the Sampler bean should not be set to the refresh scope.

A possible solution is to add `@ConditionalOnBean(RefreshScope.class)` instead of `@ConditionalOnClass(RefreshScope.class)`.

**Comment by brenuart** [comment]
My two cents: why not relying on `@ConditionalOnRefreshScope` defined at https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java#L328-L351

With a little refactoring these two @Conditional conditions could be made public and reusable elsewhere.

**Comment by asibross** [comment]
Makes sense to me.
In the mean time, if we want to avoid the extra work, I explicitly changed the affected beans.

**Comment by marcingrzejszczak** [comment]
@brenuart can you file an issue in Commons to add such an annotation?

**Comment by marcingrzejszczak** [comment]
fixed by https://github.com/spring-cloud/spring-cloud-sleuth/pull/1087
