### ISSUE TITLE
spring-cloud-sleuth-dependencies should remove spring-cloud-sleuth-stream in 2.0.1.RELEASE

### ISSUE THREAD

**Issue by Alvison** [spring-cloud/spring-cloud-sleuth#1091]
spring-cloud-sleuth-dependencies should remove spring-cloud-sleuth-stream in 2.0.1.RELEASE
because  spring-cloud-sleuth-stream is remove

**Comment by marcingrzejszczak** [comment]
What are you talking about exactly? We instrument Spring Cloud Stream as a messaging tool. We've removed `spring-cloud-zipkin-stream` module already.
