### ISSUE TITLE
Support Kinesis

### ISSUE THREAD

**Issue by holledauer** [spring-cloud/spring-cloud-sleuth#1094]
Is it possible to support AWS Kinesis?
AWS Kinesis is now part of Spring Integration. See https://github.com/spring-projects/spring-integration-aws#amazon-kinesis

**Comment by marcingrzejszczak** [comment]
If AWS is part of Spring Integration, and Sleuth supports Spring Integration, then it should work out of the box. Can you try it out?

**Comment by holledauer** [comment]
Ah, that is great :) I will try it out next week

**Comment by holledauer** [comment]
it works!

**Comment by marcingrzejszczak** [comment]
Can you describe what you did exactly?

**Comment by mattmadhavan** [comment]
Hi [holledauer](/holledauer) Can I have a sample please?
