### ISSUE TITLE
Custom Fields Within a Service & Logging to Splunk

### ISSUE THREAD

**Issue by bkookoopuffs** [spring-cloud/spring-cloud-sleuth#1097]
**Scenario**
Using Spring aspects, monitor every directory package (rest layer, application layer, dto, etc). _(FYI, this is already done and not related to Sleuth.)_ When __Service A__ receives a request, spring aspect notices rest layer has been called and will log a custom classification field such as "classification:rest-layer".  Then rest layer calls the application layer, spring aspect notices this, and updates the custom classification field to be "classification:app-layer". __This is all within the context of Service A.__
Ultimately, by logging that custom field, we want it to show up on Splunk. However, I do not want the custom field in the actual log message body but instead have it as a separate key-value pair that shows up on the logs. 

**Current solution**
For each aspect, we are using MDC in log4j to manually put information into the headers. Logback works with MDC by default so the custom key-value pair we put into MDC, automatically shows up in Splunk. It's extremely simple. However, this is a problem because it does not handle thread pooling by default (https://logging.apache.org/log4j/2.x/manual/thread-context.html) so when we make service calls asynchronously to other services, it might leak some information.

**Question**
I am trying to understand if Sleuth can handle this scenario. 
- Is this a good scenario for Sleuth? 
- How do I create a custom trace/field/baggage/span or whatever to handle this scenario? 
- Since Sf4jlCurrentTraceContext.java is using MDC, I'm assuming you guys are handling the thread pooling? I've seen other posts where some of you have mentioned copying Sf4jlCurrentTraceContext.java and making a custom version of it. If I do that, does Sleuth handle the thread pooling scenarios or is it no different than MDC in log4j2?  
- Could someone provide an example of making a custom version of claSf4jlCurrentTraceContext.java?
- If I use baggage, I don't think it will work because the baggage gets picks up only when we create a call from Service A to service B. Is this correct? Or if I set a baggage key in one aspect, will I be able to update that baggage key in another aspect while within Service A? 
- Baggage keys follow a trace but what is the point of propagation keys? 

Sorry for the many questions. I have looked into the documentation and not sure where to go from here.

**Comment by adriancole** [comment]
sleuth attempts to configure things such that the trace context is "scoped" when user code is invoked. For example, before a callback runs, a trace  context is applied to it. Similarly the case with executors. The primary use of this is getting the right parentage in place for tracing. A side-effect is MDC synchronization. So, sleuth (often via brave) always attempt to get a trace context in place when user code runs. This is imperfect as not all frameworks expose hooks, but we try our best.

arbitrary field synchronization is [not yet supported](https://github.com/openzipkin/brave/pull/577) in brave, though sleuth has some hooks for example, to populate MDC which is not done by default. Baggage.. in brave it is called extra fields... is not currently done by default, but it can be done as it is a part of the trace context. This would be a custom "ScopeDecorator" which is a functionality available in sleuth 2.1 for auto-configuration.
