### ISSUE TITLE
Sleuth reactor instrumentation could wrap only operators that use schedulers

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#1098]

**Comment by simonbasle** [comment]
In the hook, use `Scannable.from(subscriber).scan(Attr.RUN_ON) != null` condition to wrap the subscriber, should avoid instances where it is not necessary to wrap (because that operator doesn't hop threads)

**Comment by adriancole** [comment]
suppose motivation on this is performance?

**Comment by marcingrzejszczak** [comment]
It won't be as easy as we thought it would. Not a single time did we manage to trigger a `Scannable.from(subscriber).scan(Attr.RUN_ON) != null` condition for any of Sleuth's tests.

**Comment by marcingrzejszczak** [comment]
@smaldini is working on massive improvement of Sleuth with Reactor performance. You can check the progress here https://github.com/spring-cloud/spring-cloud-sleuth/tree/stephane_help
