### ISSUE TITLE
Does spring-cloud-sleuth library support protobuf?

### ISSUE THREAD

**Issue by OleksandrSankin** [spring-cloud/spring-cloud-sleuth#1099]
Question

As I can conclude from documentation your library can track HTTP/HTTPS requests. But does it support protobuf protocol?

**Comment by adriancole** [comment]
which protobuf library are you using for rpc?

**Comment by OleksandrSankin** [comment]
This one https://github.com/protocolbuffers/protobuf

**Comment by adriancole** [comment]
It doesn't currently support that, but you can raise an issue on Brave. If
a few others are interested, we can make something. Meanwhile it might be
similar in nature to other RPC frameworks. Let's carry the discussion here
https://github.com/openzipkin/brave/issues

**Comment by marcingrzejszczak** [comment]
I'll close the issue then
