### ISSUE TITLE
Implement proposed tracing common data model

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-sleuth#11]
https://docs.google.com/document/d/1pxZ5NQHftJzhlCIT4vMfOT6QT_StikaoDc_NCdfesoA/edit?usp=sharing

Eg `/http/request/uri "/my/uri"` as an annotation.

**Comment by spencergibb** [comment]
![screen shot http annotations](https://cloud.githubusercontent.com/assets/594085/9069244/5fd3b92e-3aa5-11e5-867d-8e85f2432689.png)

@mstine @b @adriancole

**Comment by adriancole** [comment]
neat! @jpinner thoughts on this?

**Comment by b** [comment]
i'm in love.

**Comment by spencergibb** [comment]
@b now that the infrastructure is in place, adding those http annotations was fairly straightforward.

**Comment by adriancole** [comment]
PS question: is this illustrative? Ex we expect to sink all
dimensions/annotations in the namespace? Or would usage more often be
sparse? Feel free to punt this.

Regardless, I like seeing how it looks.

**Comment by b** [comment]
i'd like to see everything namespaced in this way

**Comment by jpinner** [comment]
only comment would be to take a look at how the request / response first
lines are folded into the header namespace in HTTP/2 -- might make it more
forward-compatible do have things like:

/http/request/method
/http/request/scheme
/http/request/authority
/http/request/path
/http/request/headers/host

**Comment by b** [comment]
i think i noted this in the doc: http/2 is sufficiently different from 1.x that i believe it should be in its own namespace (/http2)

**Comment by spencergibb** [comment]
@adriancole should we keep this issue open or create new issues for different sections as the need arises?

**Comment by adriancole** [comment]
This would be implemented per component, so if we left this issue open, it
might be open for years. I'd close it as I think the value is understood,
and progress can be logged per component (and likely many PRs per component
till we get it right!)
