### ISSUE TITLE
Authorization header is visible in the log files

### ISSUE THREAD

**Issue by pfournea** [spring-cloud/spring-cloud-sleuth#110]
The TraceFilter registers all http headers as annotations (see method addRequestAnnotations). The Slf4jSpanListener prints the current span showing all http headers even with basic authentication information.

eg:

/http/request/headers/authorization=Basic dXNlcjpwc3dk, /http/request/headers/accept=application/json, 
...

**Comment by adriancole** [comment]
Closed via #115

no headers, sensitive or otherwise, are logged by default anymore
