### ISSUE TITLE
Feature: support tracing for request scoped resttemplates?

### ISSUE THREAD

**Issue by karel1980** [spring-cloud/spring-cloud-sleuth#1114]
Type: enhancement (?) Not 100% sure. Feel free to correct me (Hopefully I did not miss any trivial configuration)

We're using request scoped rest templates in our project (because the rootUri for our rest template depends on a property of the incoming request) - Ribbon does something similar for load balancing purposes, but solves this on a lower level.
This works fine, but it breaks when we add the sleuth starter (with no additional configuration)

Here is a minimal self contained example:
https://github.com/karel1980/sleuthproblem

Spring/Sleuth is trying to intercept the restTemplate at startup, but that doesn't work because there is not request scope at startup.

Here's the main error message:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'testResource' defined in file [/Users/kareve/Downloads/demo/demo/target/classes/com/example/demo/TestResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'restTemplate': Post-processing of FactoryBean's singleton object failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.restTemplate': Scope 'request' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
```

**Comment by karel1980** [comment]
I've found a way to solve our problem without a request scoped rest template. Instead we're setting the rootUri to http://placeholder, and then replace the placeholder via a UriTemplateHandler.

That being said, I'm leaving this open in case you guys think there's real value in the feature.

**Comment by marcingrzejszczak** [comment]
I'll close this issue for now. If there are more interested people we'll reopen it.
