### ISSUE TITLE
Improve spring cloud gateway instrumentation

### ISSUE THREAD

**Issue by fitzoh** [spring-cloud/spring-cloud-sleuth#1120]
Currently requests proxied through spring-cloud-gateway only have a span name of `get` (or `post` or `delete` or `whatever`).

It would be nice if by default the route id was tagged and or used in the span name.

This is a `GlobalFilter` that we're using on our gateway app to name the span appropriately.

```
public class RouteIdTaggingGlobalFilter implements GlobalFilter {


    /**
     * This is protected in {@link org.springframework.cloud.sleuth.instrument.web.TraceWebFilter} :(
     */
    protected static final String TRACE_REQUEST_ATTR = TraceWebFilter.class.getName()
            + ".TRACE";

    private static final Logger log = LoggerFactory.getLogger(RouteIdTaggingGlobalFilter.class);

    @Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        Object spanObj = exchange.getAttributes().get(TRACE_REQUEST_ATTR);
        if (!(spanObj instanceof Span)) {
            log.info("expected span in exchange attributes, got {}", spanObj);
            return chain.filter(exchange);
        }
        Span span = (Span) spanObj;

        Object routeObj = exchange.getAttributes().get(GATEWAY_ROUTE_ATTR);
        if (!(routeObj instanceof Route)) {
            log.info("expected route in exchange attributes, got {}", routeObj);
            return chain.filter(exchange);
        }
        Route route = (Route) routeObj;


        span.name(exchange.getRequest().getMethod() + " " + route.getId());
        span.tag("gateway.route-id", route.getId());
        return chain.filter(exchange);
    }
}
```

Writing this filter was what led me to writing #1117 as there wasn't a good way to get access to the span.

**Comment by adriancole** [comment]
there is built in support for something called "http.route" I would use
that instead.

here is a hint
https://github.com/openzipkin/brave/blob/master/instrumentation/spring-webmvc/src/main/java/brave/spring/webmvc/SpanCustomizingHandlerInterceptor.java

**Comment by fitzoh** [comment]
Aren't those sort of distinct types of values @adriancole?

The `http.route` from that interceptor is the `BEST_MATCHING_PATTERN_ATTRIBUTE` which matches the shape of the URL, while the route-id just a name.

At some point we could theoretically add a route predicate in gateway that populates the webflux `MATCHING_PATTERN_ATTRIBUTE` and use that to populate `http.route instead

related:
https://github.com/spring-projects/spring-boot/issues/12757

**Comment by adriancole** [comment]
Can you give some concrete examples perhaps? If it is different than something else isn't populating the 'http.route' else you wouldn't be getting just a "get" span name. I think the tag would be 'gateway.route_id' not 'gateway.route-id' as we don't tend to use dashes conventionally. Anyway, let's get a feature in.. seems like a decorator in nature.

**Comment by fitzoh** [comment]
Somewhat more concrete example:

Gateway route
```
    return Routes.locator()
      .route("person-service")
          .uri("http://my-person-service.com:80")
          .predicate(path("/person/**"))
      .build()
```

Downstream Controller in a person service
```
  @GetMapping("/person/{id}")
```


If someone does a `GET` to `http://gateway/person/12345`, the gateway service would record an `http.route` of `/person/{id}`.
I don't think it makes sense for that same request to have an `http.route` of `person-service` on the gateway side.  It could potentially be `/person/**`, but I don't believe anything is currently tracking the best matching route/predicate on the gateway side.

Instead, it probably makes sense to store the route id (`person-service`) in a separate property.

Does that make sense?

**Comment by adriancole** [comment]
this makes sense though still doesn't explain why there was no route in the
first place. for example I thought your initial request was about not
having 'get'. since we automatically name when route info is present I am
worried about maybe a bug somewhere?

also your code example helps a lot.. makes me wonder if the gateway
shouldn't be a span (even if this is a future change). right now double
instrumentation is tricky..

**Comment by fitzoh** [comment]
> thought your initial request was about not having 'get'

My apologies if that wasn't clear,  my complaint was about **only** having `get`.

`get person-service` is a lot more useful at a glance in the UI than `get` (IMO).

**Comment by marcingrzejszczak** [comment]
I guess we should close this since we can't do more than what we get from the attribute.
