### ISSUE TITLE
Spans opened by reactive WebClient .retry() are not nested correctly 

### ISSUE THREAD

**Issue by archie-swif** [spring-cloud/spring-cloud-sleuth#1121]
**Preface**
I have two Spring WebFlux apps with configured Sleuth and Jaeger server.
One app has an */error* functional endpoint that returns 500 error. 
Other has a */test* functional endpoint that sends a request to the */error*.
I'm using a Spring reactive WebClient to send a http request. With a *.retry(...)* added to the web client mono chain. 

**Description**
App ONE sends a request to app TWO */error* endpoint, gets a 500 error, and makes 3 more retry requests.

The **problem** is that TWO's spans opened by retry are not nested under corresponding ONE's web-client individual request spans. By the timeline you can see which TWO belongs to which ONE span.

<img width="732" alt="jeager" src="https://user-images.githubusercontent.com/2158707/47885712-9f0cae80-ddf3-11e8-8211-7383a4e963d6.png">

**Resources**
Code: https://github.com/archie-swif/sleuth-webclient-retry
Run two instances of the application, one with 'one' spring profile, another with 'two'. 

ONE's log: https://gist.github.com/archie-swif/2dfbf28c0837830cd75ad68c069079d8
TWO's log: https://gist.github.com/archie-swif/c0103c6e695c01d8c6786a6940335ea5

Trace JSON from Jaeger: https://gist.github.com/archie-swif/d2453c556272371fd5961a4bc243cccb

**Comment by archie-swif** [comment]
@adriancole Sure, no problem.

Trace JSON: https://gist.github.com/archie-swif/81ea16a55ae9dccf3f2505257f2beac4
Logs: https://gist.github.com/archie-swif/2e98e07fb667ff391ed36e5b2402a211

That's how it looks in Zipkin. There is only a single TWO span for some reason, for the exact scenario.
<img width="1177" alt="screen shot 2018-11-01 at 7 14 02 pm" src="https://user-images.githubusercontent.com/2158707/47890059-5f04f600-de0a-11e8-8467-ba5e9c65d200.png">

**Comment by archie-swif** [comment]
In the JSON I see that there are 4 get records for app TWO, with the **same** Span Id ddc5003cea7888a7
```
  {
    "traceId": "bbf04ad17fce973c",
    "parentId": "bbf04ad17fce973c",
    "id": "ddc5003cea7888a7",
    "kind": "SERVER",
    "name": "get",
    "timestamp": 1541124521469143,
    "duration": 3361,
    "localEndpoint": {
      "serviceName": "two",
      "ipv4": "172.31.99.80"
    },
    "tags": {
      "error": "500",
      "http.method": "GET",
      "http.path": "/error",
      "http.status_code": "500"
    },
    "shared": true
  },
```

For the app ONE, there is one get record with the same Span Id ddc5003cea7888a7
And three more get records with unique Span Ids.

<img width="604" alt="screen shot 2018-11-01 at 9 51 03 pm" src="https://user-images.githubusercontent.com/2158707/47894532-a5654f80-de20-11e8-9336-b705b7d29f9d.png">

**Comment by marcingrzejszczak** [comment]
Can you try with latest 2.1.0 snapshots?

**Comment by archie-swif** [comment]
It works correctly in 2.1.0.BUILD-SNAPSHOT spring-boot-starter-parent. Retry spans have unique ids.

Trace JSON: https://gist.github.com/archie-swif/513bcf9cc97a87938f2491bca0d950c8
Logs: https://gist.github.com/archie-swif/10282e2039c232b9b2889028e06ffd5f

<img width="1078" alt="screen shot 2018-11-06 at 10 58 58 am" src="https://user-images.githubusercontent.com/2158707/48087342-e14b3c80-e1b3-11e8-9e39-9884e08629b6.png">

**Comment by archie-swif** [comment]
So, 2.1.0 snapshots did not help with for this issue

**Comment by archie-swif** [comment]
However I see that IDs in TWO's logs are now unique
Let me take a closer look

**Comment by archie-swif** [comment]
With 2.1.0 Snapshot, ID assignment has changed. 
Now each WebClient GET call on app ONE opens a span with unique id. 
And app TWO code is executed in the span with the same id.

Still, I would expect a new span opened when app TWO code is executed. And this span be nested under app ONE's WebClient GET span. Please correct me if I'm wrong with this. Thank you!

<img width="623" alt="screen shot 2018-11-06 at 1 45 26 pm" src="https://user-images.githubusercontent.com/2158707/48096005-ff706700-e1ca-11e8-914e-fab8aa52068f.png">

**Comment by marcingrzejszczak** [comment]
Maybe I don't understand sth but when I look at the graph right now, that seems to be ok. Each call to `two` has a unique ID

![image](https://user-images.githubusercontent.com/3297437/50738596-f7867080-11d5-11e9-8225-2680a3eb2c57.png)

Can you sketch how it should look like in your opinion?

**Comment by archie-swif** [comment]
There was an expected picture bit earlier, with two “get” bars under each “async”.
https://github.com/spring-cloud/spring-cloud-sleuth/issues/1121#issuecomment-435275230

Now Id is unique for each call, but is duplicated for “get” in scope of each individual request. This way one of the “get” block is lost on the chart.

**Comment by marcingrzejszczak** [comment]
Hey @archie-swif can you check if the latest versions work fine for that matter?

**Comment by archie-swif** [comment]
Hi @marcingrzejszczak , thanks for checking up!

I have tried it with Spring Boot 2.3.2.RELEASE, 2.4.0-SNAPSHOT, and latest zipkin image 2.21.5. 
Here is how it looks by default:
<img width="742" alt="Screen Shot 2020-08-05 at 16 17 10" src="https://user-images.githubusercontent.com/2158707/89473655-4ab90000-d738-11ea-86a5-a7211d4dc610.png">

I see that more spans of the service ONE are present in json, but they are not visible in zipkin UI.
It looks like the issue is in non unique "id" values in span objects. Zipkins takes the one span with an unique id and ignores others with the same id.

If exported trace json is updated so that all ids are unique:
[https://github.com/archie-swif/sleuth-webclient-retry/commit/853173bae76492ae74fbbd8aaba4d4cc2741617a](https://github.com/archie-swif/sleuth-webclient-retry/commit/853173bae76492ae74fbbd8aaba4d4cc2741617a?branch=853173bae76492ae74fbbd8aaba4d4cc2741617a&diff=split)

Then it looks this way, no spans are lost:
<img width="730" alt="zipkin-expected" src="https://user-images.githubusercontent.com/2158707/89475181-60302900-d73c-11ea-85a0-80ca4120c767.png">

Thank you!

**Comment by marcingrzejszczak** [comment]
I've bumped boot to `2.4.0` and Cloud to `2020.0.0-SNAPSHOT` and I got the following trace

![image](https://user-images.githubusercontent.com/3297437/89532128-967bb000-d7f1-11ea-8470-9d4ed5fce3bb.png)

I guess it looks fine?

**Comment by archie-swif** [comment]
In 2.4.0, additional "async" span is being tracked, but ONE's "get" span is still ignored, even if it's present in json. After id fix it looks this way:
<img width="1221" alt="Screen Shot 2020-08-06 at 11 09 57" src="https://user-images.githubusercontent.com/2158707/89567223-290e5600-d7d6-11ea-88b9-332806dd34ea.png">

**Comment by marcingrzejszczak** [comment]
Please upgrade to [Micrometer Tracing](https://docs.micrometer.io/tracing/reference/). Spring Cloud Sleuth is feature complete and out of OSS support.
