### ISSUE TITLE
How to customize traceid in spring-cloud-sleuth-zipikin v1.1.4.RELEASE

### ISSUE THREAD

**Issue by sureshp1980** [spring-cloud/spring-cloud-sleuth#1127]
Hi Team,
 We are building a microservices application using Spring Boot.
For logging, we have used spring-cloud-sleuth-zipkin (version: 1.1.4.Release), by using @EnableZipkinStreamServer and @EnableZipkinServer annotations.

Currently, the auto-generated TraceId is been logged for all log messages.
Instead of this system generated traceId, we need to customize the TraceId  (in format  "UID (8)+'_'+RandomNumber(55)" in TraceId field of 64 bit) and use it in all our log statements.

Can you provide the steps to make this change in TraceId.
If this is not possible, as an alternate solution can we add an extra field (say 'x-custom-request-id') in all the log statements. Can you share the steps for this configuring this extra field?

Thanks and Regards
Sam

**Comment by marcingrzejszczak** [comment]
Hi!

> @EnableZipkinStreamServer

That's deprecated. Please don't use it anymore.

> Currently, the auto-generated TraceId is been logged for all log messages.
Instead of this system generated traceId, we need to customize the TraceId (in format "UID (8)+'_'+RandomNumber(55)" in TraceId field of 64 bit) and use it in all our log statements.

don't change that. Instead use baggage (ExtraPropagation) to set a new field that will be propagated within your system. You can also tag it so that you'll be able to search for it in Zipkin.

> If this is not possible, as an alternate solution can we add an extra field (say 'x-custom-request-id') in all the log statements.

With the newest version of Sleuth you'll be able to automatically (via property) add that field to MDC. Then, it's easy to just change the logging format. If you can't wait for Greenwich then in Finchley you'll have to copy the existing Slf4j implementation and add your own fields there to MDC.

**Comment by sureshp1980** [comment]
Hi Marcin,

1. If @EnableZipkinStreamServer is deprecated, what is the alternate for this?
2. Is "ExtraPropagation" feature available in version 1.1.4.RELEASE?

I have used below code, and got compilation error in span.setBaggageItem() call. Is this method available for use in this version?
```
import org.springframework.cloud.sleuth.Span;
@Autowired
@Lazy
 private  Tracer tracer1;
 Span currentSpan = tracer1.getCurrentSpan(); 
  String newUniqueId= getNewTraceId(userId);
  String baggageKey = "CustomTraceId";
  String baggageValue = newUniqueId;
 currentSpan.setBaggageItem(baggageKey, baggageValue);   _=> This throws compilation error -The method setBaggageItem(String, String) is undefined for the type Span_
 tracer1.addTag(baggageKey, baggageValue);
```

Thanks

**Comment by marcingrzejszczak** [comment]
Please upgrade to latest version and read the documentation. Everything is there.

**Comment by sureshp1980** [comment]
hi Marcin,

I have used latest version (2.0.2.RELEASE) and have gone through the [documentation ](https://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/2.0.2.RELEASE/single/spring-cloud-sleuth.html#_sending_spans_to_zipkin)as well.

But still Im getting error for the "span.setBaggageItem()" method call.
 I have used Gradle for build dependencies. 'springBootVersion; is '1.5.3.RELEASE'.


```
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:Camden.SR7"
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2.0.2.RELEASE"       
    }
}

dependencies {

    compile group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: springBootVersion   
	compile ('org.springframework.cloud:spring-cloud-starter-sleuth')
	compile ('org.springframework.cloud:spring-cloud-starter-zipkin')
	compile ('org.springframework.amqp:spring-rabbit:2.0.2.RELEASE')
}
```

**Comment by OlgaMaciaszek** [comment]
Hello @sureshp1980 . This setup will not work. You should only have one bom for dependencyManagement, with the newest release version for the chosen release train, for example, Edgware.SR5. You can read more about setting sleuth with dependency management plugin here: https://cloud.spring.io/spring-cloud-sleuth/single/spring-cloud-sleuth.html#sleuth-adding-project . This is not a bug in Sleuth. Closing issue. If you have more usage questions, as opposed to bug reports, please use StackOverflow or Sleuth gitter for that.
