### ISSUE TITLE
ExecutorBeanPostProcessor Makes Guava's ListeningExecutorService Beans Unusable

### ISSUE THREAD

**Issue by jwcarman** [spring-cloud/spring-cloud-sleuth#1130]
We recently upgraded to Spring Boot 2.1.0 (with spring-cloud-sleuth-core 2.0.2.RELEASE) and for our apps that use a Guava ListeningExecutorService, exposed as a bean, they have started getting the following exception:

`
org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'batchExecutorService' is expected to be of type 'com.google.common.util.concurrent.ListeningExecutorService' but was actually of type 'org.springframework.cloud.sleuth.instrument.async.TraceableExecutorService'
`

**Comment by marcingrzejszczak** [comment]
Can you create a sample that replicates this problem?

**Comment by jwcarman** [comment]
You want it attached or just upload it to GH in my account?

**Comment by marcingrzejszczak** [comment]
Gh account is good

**Comment by jwcarman** [comment]
Okay, I finally figured it out.  Since we don't have a Greenwich release in central, we're still using Finchley.SR2.  Since that's likely a no-no with Spring Boot 2.1.x, I downgraded Spring Boot to 2.0.6.RELEASE.  The key appears to be the devtools, though (which would be gone at runtime normally).  If you try to start this project from within your IDE (I use IDEA), it will fail.  If you comment out the devtools dependency, it'll run.  

https://github.com/jwcarman/spring-cloud-sleuth-guava

Hope this helps.  Thanks, @marcingrzejszczak !

**Comment by marcingrzejszczak** [comment]
The exception is related to 

```
org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class com.google.common.util.concurrent.MoreExecutors$ListeningDecorator: Common causes of this problem include using a final class or a non-visible class; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
```

the concrete reason for that (coming from the `LoadingCache` from Spring's CGLIB module) is

```
class com.google.common.util.concurrent.MoreExecutors$ListeningDecorator$$EnhancerBySpringCGLIB$$152e166c cannot access its superclass com.google.common.util.concurrent.MoreExecutors$ListeningDecorator
```

that's due to the fact that `ListeningDecorator` is a `private static` one, and we can't instrument it. I have no idea why it works in the first place ;)

please help :D @aclement @philwebb

**Comment by marcingrzejszczak** [comment]
Is this still a problem? I can't replicate this when running the sample locally with latest versions (maybe I'm doing sth wrong)

**Comment by jwcarman** [comment]
Oh my gosh, I totally forgot to provide a sample to you all. So sorry. This has been a while, but let me see what I can whip up. It may have very well already been addressed.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
