### ISSUE TITLE
Way of specifying custom source for application name

### ISSUE THREAD

**Issue by chintanb** [spring-cloud/spring-cloud-sleuth#1132]
# Bug report

Version: 2.0.1.RELEASE
I am using custom `spring-logback.xml` and specifying app name as specified in the docs.
```	<springProperty scope="context" name="springAppName"source="spring.application.name"/>```
Is there a way to specify source other than spring.application.name ? 

I am running clusters of spring microservices along with Zuul proxy. When I see logs, I would like to know its instance id along with its name to be sure where the log is coming from. I could easily do that by adding following property to bootstrap.yml, however that breaks the Zuul functionality as my routes/service ids are hardcoded for that.
```
spring.application.name=router-${spring.application.instance_id}
```
What I want to do rather, is define a custom slueth specific bootstrap property that I can use instead of application.name for property springAppName in my logback.xml
So is it doable ? If not, can it be added as a functionality ? I am sure anyone who's running same setup as me, must be having difficulty specifying unique id for each service to see sleuth traces.

**Comment by marcingrzejszczak** [comment]
I don't understand the question. You can put as as the application name whatever you want, in whatever way you want. Just change the logging format.

If you want to use our logging format we search for the name of the app like this:

`${spring.zipkin.service.name:${spring.application.name:-}}`

so you can also set the name via `spring.zipkin.service.name`

**Comment by marcingrzejszczak** [comment]
Sorry, I don't understand the problem.

Can you create a sample that reproduces the issue?

`<property name="spring.zipkin.service.name" value="router-123"/>` - this will not work, cause you need to pass the property value to Spring context. Please read this section of the Boot's documentation - https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html it should be helpful

**Comment by chintanb** [comment]
@marcingrzejszczak Sure I will give it a read. Forget about zipkin service name. This is what my logback.xml file looked like before, and if I understand passing property to spring context correctly, I think I had it by defining it a Spring property.

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
     <include resource="org/springframework/boot/logging/logback/defaults.xml" />

	<springProperty scope="context" name="springAppName" source="application.instance.name"/>

     <property name="CONSOLE_LOG_PATTERN" value="%date{ISO8601} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } [%15.15t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"/>
     <include resource="com/some/path/logging/console-appender.xml"/>
     <root level="INFO">
	  <appender-ref ref="CONSOLE" />
     </root>
</configuration>
```
And following in my bootstrap.properties file
```application.instance.name=router-154ae9beeac659fb```

This configuration gave me no application name in logs.
```
[-,753e321600a9a023,753e321600a9a023,false]
```

Do you understand the problem now ? I can certainly give you a reproducer but it will be just a simple spring app with aforementioned logback.xml.

**Comment by chintanb** [comment]
@marcingrzejszczak Following up on this, please let me know if you had a chance to go through my previous response and have any update for me. thanks.

**Comment by marcingrzejszczak** [comment]
here you have an example of a good setup - https://github.com/spring-cloud-samples/sleuth-documentation-apps/blob/master/service1/src/main/resources/logback-spring.xml if that doesn't help, please create a project that reproduces the issue
