### ISSUE TITLE
The logback log always outputs four variables to the log by default.

### ISSUE THREAD

**Issue by tofdragon** [spring-cloud/spring-cloud-sleuth#1136]
spring boot 1.5 + spring clund sleuth 1.3.6 

Not using spring clound other features

I don't want to use sleuth to add to the four variable log formats in the logback. No matter how it is configured, the four variables will be added to the log.

It is also useless to configure the console pattern in logback-spring.xml, or there will be four variables by default.

[sinogear,5bee636f0addecfec1199dd15e0bddae,c1199dd15e0bddae,false]

use yml config

**Comment by marcingrzejszczak** [comment]
Just set `spring.sleuth.enabled=false` to disable setting any entries to MDC. Configure the logging pattern as you wish to disable the default logging setup.
