### ISSUE TITLE
Sleuth Integration Performance degradation

### ISSUE THREAD

**Issue by tony-clarke-amdocs** [spring-cloud/spring-cloud-sleuth#1137]
If we add spring cloud sleuth starter to the 2.0.x stream performance degrades to such an extent that it is almost unusable. Request Processing times is about 6 times slower.  This issue has already been [identified](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1105) and at least partially addressed in Spring Cloud 2.1.x SNAPSHOT.  The fixes are here: 
https://github.com/spring-cloud/spring-cloud-sleuth/pull/1111
https://github.com/spring-cloud/spring-cloud-sleuth/pull/1122

Will we need to wait for a 2.1.x release to get these fixes or will they be ported into the 2.0.3?

**Comment by marcingrzejszczak** [comment]
AFAIR there were some big changes there so we encourage to upgrade to the latest Boot and Greenwich.

**Comment by marcingrzejszczak** [comment]
Can you confirm that with the latest versions the performance is not degraded?

**Comment by tony-clarke-amdocs** [comment]
Running with Finchley and adding sleuth request processing is about 6 times slower.  Using Greenwich SNAPSHOT is a lot better...only 2 times slower with sleuth. 
@spencergibb This would imply no sleuth in practice for Spring Cloud Gateway 2.0.x

**Comment by marcingrzejszczak** [comment]
So it's not about Spring Cloud Stream but Gateway, correct?

OTOH you're the first person to complain about it so I'm surprised the performance is so bad for you. I'm not surprised that it's deteriorated though. Anyways, I'm closing the issue.

**Comment by marcingrzejszczak** [comment]
Oh and cc @smaldini

**Comment by tony-clarke-amdocs** [comment]
The issue raised here is: will the fixes be merged into Finchley....I didn't see that raised as an issue anywhere else? I think you are saying the answer is "no". What is the duplicate of?

**Comment by marcingrzejszczak** [comment]
The title is `Sleuth Integration Performance degradation`. So it's a duplicate. 

BTW in the title you have `Integration`. Then you write about `Stream`. Then it turns out that it's not `Stream` but `Gateway`. Actually it's really about `Reactor`. 

Currently I'm saying `no` to merging it to Finchley.
