### ISSUE TITLE
TraceWebClient should report trace in case of cancellation

### ISSUE THREAD

**Issue by madgnome** [spring-cloud/spring-cloud-sleuth#1138]
When using Sleuth with WebFlux we get traces for webclient calls on success and error but we don't get any trace on cancellation. The most common case of cancellation on a stream originating from a webClient would be timeout.

```
webClient.post()
                 .uri("http://example.com")
                 .retrieve()
                .bodyToMono(String.class)
                .timeout(Duration.ofSeconds(1))
```

It would be perfect if `TraceWebClientBeanPostProcessor` could be changed to handle cancellation and report them as a special type of error maybe?

I'm happy to raise a PR if you think it's a good idea.

**Comment by marcingrzejszczak** [comment]
Makes perfect sense. Be my guest
