### ISSUE TITLE
Should we ever export a span missing a trace id or a span id?

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#114]
In issue #111, we carry-over a "default id" of 1125899906842597L

It doesn't make sense to me why we would report a constant id. ex, if this were actually used, any spans that are missing ids would become attached to trace 1125899906842597L. That data wouldn't be reclassifyable. If it could be displayed, it would appear in the trace list as an odd trace that has dead spans from N endpoints attached.

I think this is an example of where we are allowing null in a place that should never be. Is there any valid reason for a span without an identifier to be reported?

**Comment by marcingrzejszczak** [comment]
ATM (https://github.com/spring-cloud/spring-cloud-sleuth/issues/111) it's no longer possible to have a span without trace and span id.
