### ISSUE TITLE
Trace Ids not sent in the response for Spring 1.5.17 and Spring Cloud Edgware.SR5

### ISSUE THREAD

**Issue by vikrantk365** [spring-cloud/spring-cloud-sleuth#1144]
I've recently migrated my application from Spring Boot `1.4.3.RELEASE` to Spring Boot `1.5.17.RELEASE`
and Spring Cloud from `Brixton.SR4` to `Edgware.SR5`.
After migration, trace and span ids are not being sent in the API response
(`X-B3-Traceid` and `X-B3-Spanid`)
I can see that they are generated in the logs.

**Comment by marcingrzejszczak** [comment]
Yes, that feature was removed in the meantime. You have to add those values yourself. One of the corresponding issues is https://github.com/spring-cloud/spring-cloud-sleuth/issues/633
