### ISSUE TITLE
How to comprehend to the "localEndpoint" and "tags" field?

### ISSUE THREAD

**Issue by JackGzj** [spring-cloud/spring-cloud-sleuth#1151]
I am new to tracing technology and I used to have a zipkin span with annotation of 'cs' 'sr' 'ss' 'cr'，but when I am using a benchmark equipped with sleuth (version 1.2.2.RELEASE), I got some span like:
`{
    "traceId": "d4f03cba9aa0b0cb",
    "parentId": "ee80dcdcf21180f8",
    "id": "0f6069681c606c39",
    "kind": "CLIENT",
    "name": "http:/basic/queryfortravel",
    "timestamp": 1543799898269000,
    "duration": 72000,
    "localEndpoint": {
      "serviceName": "ts-ticketinfo-service",
      "ipv4": "172.20.1.46",
      "port": 15681
    },
    "tags": {
      "http.host": "ts-basic-service",
      "http.method": "POST",
      "http.path": "/basic/queryForTravel",
      "http.url": "http://ts-basic-service:15680/basic/queryForTravel",
      "spring.instance_id": "ts-ticketinfo-service-849689c758-5lfhp:ts-ticketinfo-service:15681"
    }
  },
  {
    "traceId": "d4f03cba9aa0b0cb",
    "parentId": "d4f03cba9aa0b0cb",
    "id": "ee80dcdcf21180f8",
    "kind": "SERVER",
    "name": "http:/ticketinfo/queryfortravel",
    "timestamp": 1543799898267000,
    "duration": 75000,
    "localEndpoint": {
      "serviceName": "ts-ticketinfo-service",
      "ipv4": "172.20.1.46",
      "port": 15681
    },
    "tags": {
      "mvc.controller.class": "TicketInfoController",
      "mvc.controller.method": "queryForTravel",
      "spring.instance_id": "ts-ticketinfo-service-849689c758-5lfhp:ts-ticketinfo-service:15681"
    },
    "shared": true
  }`
but I can't figure out if the "localEndpoint" field represents the parent service and the tags field represents the child service in a "CLIENT" span. If I understand the span data like this way, it can't make sense because some dependency I got from the raw span data doesn't appear in the dependency graph drawn by the Zipkin-UI, as it;s presented below.
![image](https://user-images.githubusercontent.com/24668339/49452676-9822f280-f81c-11e8-85ed-fc61b13f69a2.png)
![image](https://user-images.githubusercontent.com/24668339/49452715-a6710e80-f81c-11e8-8b6a-78a8a59be989.png)
As we can see, the "ts-basic-service" didn't call the "ts-station-service".
I want to know what do these fields actually mean, and if I can change the span record to the 'cs' 'sr' 'ss' 'cr' style. Thank you!

**Comment by marcingrzejszczak** [comment]
I think you should ask this question at Zipkin gitter / github cause it's not related to Sleuth. Also please use the latest version of Sleuth
