### ISSUE TITLE
why there are 3 spans in zipkin after send a message by Spring cloud Stream?

### ISSUE THREAD

**Issue by FunnyYish** [spring-cloud/spring-cloud-sleuth#1155]
I use sleuth and zipkin to track messaging.

I  make  a REST call to send a message by Spring cloud stream and there is no consumer for this message,but then there are  4 spans in zipkin.The first span is for the Rest call,the second span is for message publishing,but what for the third and fourth span?

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

You haven't provided any meaningful information that can help answer your question. You have basically ignored all the suggestions we've provided for you when you create a new issue

**Comment by FunnyYish** [comment]
Sorry for that...
This is my sample project:
[sample.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2655637/sample.zip)
This is the zipkin track json:
[670a320d60522403.txt](https://github.com/spring-cloud/spring-cloud-sleuth/files/2655650/670a320d60522403.txt)

**Comment by marcingrzejszczak** [comment]
* The first one is for the REST controller
* Your channel is assumed to be a `DirectChannel` so
** we create the second span for `send` to broker
** then we create the third span for consuming the message from the broker (since it's a direct channel it takes almost no time)
** and finally we have the `handle` span

Having such an interface

```java
public interface MySender {

	@Output("my-output")
	MessageChannel send();

}
```

and such a controller

```java
@RestController
public class TestController {
	
	@Autowired
	MySender sender;
	
	@GetMapping("sendMsg")
	public boolean sendMsg() {
		return sender.send().send(MessageBuilder.withPayload("ssss").build());
	}
}

```

and such a main app 

```java
@EnableBinding(MySender.class)
@SpringBootApplication
public class SampleApplication {

	public static void main(String[] args) {
		SpringApplication.run(SampleApplication.class, args);
	}
}
```

why is the channel assumed to be `DirectChannel` ? @artembilan @garyrussell

**Comment by garyrussell** [comment]
```java
public interface MySender {

	@Output("my-output")
	MessageChannel send();

}
```

Spring Cloud Stream creates a `DirectChannel` for that binding (and binds it to the output destination).

**Comment by marcingrzejszczak** [comment]
So that's a standard behaviour? Since `DirectChannel` can also be used by Spring Integration for sending messages inside the same JVM, how can we know that this `DirectChannel` is actually only a bridge for sending a message out to the broker?

**Comment by olegz** [comment]
@marcingrzejszczak if you're using the latest SCSt you can actually look for `DirectWithAttributesChannel`which were added as part of https://github.com/spring-cloud/spring-cloud-stream/commit/28990fe995575bdccb31eee527114ab147ae8962. So regular SI channels aren't going to be that.

**Comment by olegz** [comment]
Basically the `@Input/@Output` channels that are on the edges of SCSt app are `DirectWithAttributesChannel`.
