### ISSUE TITLE
Allow configuring RateLimitingSampler via properties

### ISSUE THREAD

**Issue by shakuzen** [spring-cloud/spring-cloud-sleuth#1162]
[Brave 5.6 introduced](https://github.com/openzipkin/brave/releases/tag/5.6.0) a `RateLimitingSampler` which I would like to use with Sleuth. Currently, I would have to provide my own `Sampler` bean to do this, which is not difficult, but it would be nice if it had the same level of support as the `ProbabilityBasedSampler`, allowing it to be configured via properties alone. Some restructuring of the properties to support different Sampler implementations may be needed, but I think it would be a nice feature people would use.

Maybe a selector property like `spring.sleuth.sampler.type` that is an enum for choosing the sampler implementation, paired with specific properties like `spring.sleuth.sampler.ratelimiting.rate`.

/cc @adriancole

**Comment by adriancole** [comment]
or even sleuth.sampler.ratelimit

**Comment by marcingrzejszczak** [comment]
@shakuzen show me the PR :D
