### ISSUE TITLE
Missing Tracer#currentSpan() in tests alongside spring security

### ISSUE THREAD

**Issue by beltram** [spring-cloud/spring-cloud-sleuth#1168]
Bug report
Hi, I recently upgraded to Greenwich RC1 and stumbled upon a weird issue (which did not happen with Finchley).
In a Controller test (WebTestClient) I have 2 tests doing the exact same thing (getting current span back). First test to be executed works fine but second fails because brave.Tracer#currentSpan() is null. This only happens if I bring spring-security-test in the mix. 
My first naive guess is that it might come from ReactorContextTestExecutionListener but haven't had time to investigate further.
Reproducer is [here](https://github.com/beltram/sleuth-greenwich-reproducer)
Thanks

**Comment by marcingrzejszczak** [comment]
The workaround is to use `DirtiesContext`

```
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
```

Other than that I guess we'll need help from @smaldini or @bsideup :|

**Comment by bsideup** [comment]
or @simonbasle :)

**Comment by beltram** [comment]
@bsideup  I'm using Spring Security 5.1.2.RELEASE

**Comment by beltram** [comment]
I confirm it works back with spring-security-test:5.1.3-BUILD-SNAPSHOT
Thanks a lot @bsideup

**Comment by marcingrzejszczak** [comment]
Cool! I'm closing the issue. Thanks @bsideup, you're the best!
