### ISSUE TITLE
Deadlock in obtaining Redis connection

### ISSUE THREAD

**Issue by yarodinD** [spring-cloud/spring-cloud-sleuth#1177]
Hello.
I'm using the following combination:
Spring Boot 2.1.1,  spring-cloud-dependencies Greenwich.RC2, spring-boot-starter-data-redis 2.1.1, spring-session-data-redis 2.1.2, spring-cloud-starter-sleuth. Java 11

The Redis is accessed by using sentinel in front of it.

This fails because the main thread blocks while trying to get a Redis connection from lettuce.

Any other combination works: Going to redis directly instead of going through sentinel makes it work, switching to Jedis instead works, using lettuce 5.0 instead of 5.1 works also.
When I either leave sleuth or spring-session-data-redis out, the service starts again.

Thread dump is attached.

[thread_dump_greenwich_rc2.txt](https://github.com/spring-cloud/spring-cloud-sleuth/files/2732772/thread_dump_greenwich_rc2.txt)

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by yarodinD** [comment]
@marcingrzejszczak Here it is. 
Created directly with spring boot initiliazr, just added the redis settings in application.properties.
I tested it against a redis/sentinel running on docker, Redis 3.2.5 (I could reproduce the same behavior with 5.0.3)

[sleuth-bug-demo.tar.gz](https://github.com/spring-cloud/spring-cloud-sleuth/files/2733161/sleuth-bug-demo.tar.gz)
