### ISSUE TITLE
how can I put the propagation-keys value into log4j2.yaml

### ISSUE THREAD

**Issue by shl1988012** [spring-cloud/spring-cloud-sleuth#1178]
[https://github.com/spring-cloud/spring-cloud-sleuth/issues/1176](url)
according to issues/1176. I  use the spring.sleuth.propagation-keys: propagation_id  and it can work fine. thanks a lot .

now, I have another question: how can I put the propagation-keys value into log4j2.yaml . 
 the logging.pattern.level set to %5p [${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},**%X{propagation_id:-}**]
and it can not work

**Comment by marcingrzejszczak** [comment]
For SLF4J we do that for you - we add all the ids to MDC. For Log4j you would have to do it yourself. You can check https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jScopeDecorator.java#L105-L108 for inspiration
