### ISSUE TITLE
Support multiple tracing systems

### ISSUE THREAD

**Issue by TYsewyn** [spring-cloud/spring-cloud-sleuth#1180]
Currently one of the requirements I have is to support multiple tracing systems (GCP Stackdriver Trace & Zipkin). Unfortunately it is not possible to use the auto-configuration which comes with the 2 dependencies (`spring-cloud-gcp-starter-trace ` and `spring-cloud-starter-sleuth-zipkin`).
Supporting both systems also requires to duplicate almost all of the auto-configuration.

It'd be interesting if `spring-cloud-sleuth-core` comes shipped with an `@Primary` bean which is a composite of all the configured `SpanReporter`s, or something that is a brave based `FinishedSpanHandler ` (which will be more efficient) like @adriancole said on gitter.

**Comment by adriancole** [comment]
yep and to clarify.. right now, no reporter is based on `FinishedSpanHandler` but anyway the overall design you mention seems to apply regardless

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-sleuth/pull/1181
