### ISSUE TITLE
Base Url property in documentation is old version

### ISSUE THREAD

**Issue by devinsba** [spring-cloud/spring-cloud-sleuth#1185]
While creating a demo we discovered that the latest documentation has the wrong base url property. It has the old property still. I'm reporting from my phone otherwise I would fix it

**Comment by marcingrzejszczak** [comment]
I don't know what you refer to so I'll wait for the PR ;)

**Comment by marcingrzejszczak** [comment]
@devinsba can you file a PR please?

**Comment by devinsba** [comment]
Looks like I may have had an old version of the docs open somehow, maybe my phone cached it, the property in question looks good everywhere I looked
