### ISSUE TITLE
Consistent gRPC version in transitive dependencies

### ISSUE THREAD

**Issue by suztomo** [spring-cloud/spring-cloud-sleuth#1186]
Type: Enhancement

# Problem

[`org.springframework.cloud:spring-cloud-sleuth-core:2.1.0.RC3`][1] depends on following two Maven artifacts.

- [`io.github.lognet:grpc-spring-boot-starter:3.0.0`][2]
  This depends on `io.grpc:grpc-netty:jar:1.15.1`
- [`io.zipkin.brave:brave-instrumentation-grpc:5.6.0`][3]
  This depends on `io.grpc:grpc-all:1.16.1`

They, however, do not have same version of transitive gRPC dependency (1.**15**.1 vs. 1.**16**.1). Such inconsistencies carries a risk of raising a run-time exception (Example: https://github.com/spring-cloud/spring-cloud-gcp/issues/1373).

# Solution

In order to mitigate the risk, it would be great if spring-cloud-sleuth has consistent gRPC version in its transitive dependencies.

Note that as of this issue creation, the latest grpc-spring-boot-starter ([3.0.1-SNAPSHOT][4]) has only 1.15.1.

[1]: http://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-sleuth-core/2.1.0.RC3/spring-cloud-sleuth-core-2.1.0.RC3.pom
[2]: https://search.maven.org/artifact/io.github.lognet/grpc-spring-boot-starter/3.0.0/jar
[3]: https://search.maven.org/artifact/io.zipkin.brave/brave-instrumentation-grpc/5.6.0/jar
[4]: https://search.maven.org/artifact/io.github.lognet/grpc-spring-boot-starter/3.0.1-SNAPHSOT/jar

**Comment by marcingrzejszczak** [comment]
Care for a PR to fix this?

**Comment by suztomo** [comment]
Sure. To start with, I've created an issue in grpc-spring-boot-starter repository, "Release with gRPC 1.16.1".

**Comment by suztomo** [comment]
`grpc-spring-boot-starter:3.0.1` has been released with gRPC 1.16.1.

**Comment by suztomo** [comment]
@marcingrzejszczak PR is created (1190). Would you check this?
