### ISSUE TITLE
NPE in a custom reactive web filter

### ISSUE THREAD

**Issue by SirWayne** [spring-cloud/spring-cloud-sleuth#1188]
Hello,

with the current master, i get a NPE when im using a custom reactive web filter. In the tracer the current span is always null.
I try to add a custom key to the response. Here is the example:
https://github.com/SirWayne/reproduce-sleuth-issue with test case

**Comment by marcingrzejszczak** [comment]
Can you please upload all of this code as a sample project at github?

**Comment by SirWayne** [comment]
Here we go:
https://github.com/SirWayne/reproduce-sleuth-issue

**Comment by marcingrzejszczak** [comment]
I think it's related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/1143

**Comment by marcingrzejszczak** [comment]
Yeah it's related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/1143
