### ISSUE TITLE
Possible incompatibility with grpc-spring-boot-starter

### ISSUE THREAD

**Issue by ST-DDT** [spring-cloud/spring-cloud-sleuth#1209]
I'm referring to [yidongnan/grpc-spring-boot-starter](https://github.com/yidongnan/grpc-spring-boot-starter) not [LogNet/grpc-spring-boot-starter](https://github.com/LogNet/grpc-spring-boot-starter).

### The issue

`KafkaProperties` aren't loaded at the time spring tries to initialize the `KafkaSender` causing the application to fail to start.

### The Story

Recently a user from spring-cloud-sleuth and [grpc-spring-boot-starter](https://github.com/yidongnan/grpc-spring-boot-starter/) reported an [issue](https://github.com/yidongnan/grpc-spring-boot-starter/issues/167) to us, that if he uses your library in combination with ours, he cannot use the kafka binder anymore. After a short investigation I discovered that the sender setup runs before the kafka setup and thus is unaware of its presence.

### The Workaround

From the user's perspective this issue is hard to find, but easy to fix (Simply add `@EnableConfigurationProperties(KafkaProperties.class)` to their `@Configuration` classes).

### The Details

Somehow we need to make sure that the sleuth sender setup runs after the kafka setup.

Without our library it seems to work fine, so I assume that I'm doing something wrong here, but I cannot image what, because I don't use/reference kafka at all.

Maybe you can add something like `@AutoConfigureAfter(KafkaAutoConfiguration.class)` to [`ZipkinKafkaSenderConfiguration`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/sender/ZipkinKafkaSenderConfiguration.java#L43). That should fix the ordering issues, but I haven't tested that yet.

You can find the auto configuration classes [here](https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure).

The following graph shows how the different configs dependent on each other.
![autoconfigurationorder](https://user-images.githubusercontent.com/1579362/52479145-e8fdf100-2ba7-11e9-962a-cc2d04f16573.png)

The referenced issue contains some sample projects that demonstrate this behavior.

Do you have any idea, what could cause this behavior?

----------------------------

Original issue: https://github.com/yidongnan/grpc-spring-boot-starter/issues/167

Disclaimer: I'm one of the library's main contributors.

**Comment by marcingrzejszczak** [comment]
Hi @ST-DDT ! Nice to meet you :) From my perspective that's not a problem to add it (I guess). Is this the URL https://github.com/bob04619/sleuth-grpc-framework-testing/tree/kafka-with-grpc-framework of the repo that replicates the problem?

**Comment by ST-DDT** [comment]
Yes. That's the one.
I just tested it and the issue is still reproducible using that branch and also the workaround works.

**Comment by marcingrzejszczak** [comment]
I'm sorry for sure I'm doing sth wrong. I've checked out the `kafka-with-grpc-framework` and ran `./gradlew clean build`. The build fails. I commented out `spring-cloud-starter-zipkin` and the build also fails for the same reason. Can you tell me how I can actually make the build pass?

**Comment by ST-DDT** [comment]
1. Checkout the branch
2. Edit [`src/main/java/test/TestSpringApp.java`](https://github.com/bob04619/sleuth-grpc-framework-testing/blob/kafka-with-grpc-framework/src/main/java/test/TestSpringApp.java)
   * Add `@EnableConfigurationProperties(KafkaProperties.class)`
3. Run the project with `./gradlew clean bootRun -x test`
   The tests needs to be skipped if you don't have a running kafka (configured).

**Comment by marcingrzejszczak** [comment]
I did what you said and I got this with Zipkin excluded :|

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
```

**Comment by ST-DDT** [comment]
Why did you exclude zipkin? Well, I assume that the `requestMappingHandlerMapping` has an annotation with a class that is not on the CP, thus the `TypeNotPresentExceptionProxy` is thrown. Unfortunately I don't know which class that actually is. My knowledge about spring-cloud + zipkin is very limited so I cannot help much there.

I have a working setup with zipkin, but without the problematic kafka-sender:
https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/examples#cloud-mode
There is also an "automated" test for that setup which might help you to run it
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/testExamples.sh#L48

**Comment by marcingrzejszczak** [comment]
I excluded Zipkin cause you said that there's an incompatibility with Sleuth. `starter-zipkin` includes sleuth. I excluded zipkin so as not to include Sleuth. Regardless of whether I have sleuth on the classpath or not, the project doesn't work. I'm curious why do you think that Sleuth is to blame for the exceptions since I can't start the project even without it.

**Comment by ST-DDT** [comment]
I'll try what you did and report back in a few hours.

**Comment by marcingrzejszczak** [comment]
There's a high chance that I messed sth up, but in order for me to try to replicate the issue I need to be able to run the project ;)

**Comment by marcingrzejszczak** [comment]
Ok I've managed to replicate it. I've bumped Boot and Spring Cloud versions.
