### ISSUE TITLE
Sleuth breaks Spring's strategy of looking for an Executor for @Async processing

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-sleuth#1212]
When no `AsyncConfigurer` is present in the context, Sleuth autoconfigures one which initialize the Spring `@Async` framework with a `SimpleAsyncTaskExecutor`, *even if* an explicit `TaskExecutor`  has been provided by the application.

Just to remember, Spring follows the following step when looking for an executor:
1. use the `AsyncConfigurer` found in the context if any
2. search for a single (or annotated @Primary) `TaskExecutor`bean
3. search for a bean of type `Executor` named `taskExecutor`
If nothing is found, Spring falls back to using a SimpleAsyncTaskExecutor after logging some warning messages in the logs.

Because Sleuth creates an AsyncConfigurer itself, steps 2 and 3 are not applicable anymore. Consequence is people cannot rely on Spring's default behaviour.

**Comment by marcingrzejszczak** [comment]
Which version of Sleuth are you using? Do you have a sample project that replicates this behaviour?

**Comment by marcingrzejszczak** [comment]
Ok I think I know what you're referring... Is my comment correct?

```java
/**
	 * Wrapper for the async executor.
	 */
	@Configuration
	@ConditionalOnMissingBean(AsyncConfigurer.class)
	@ConditionalOnProperty(value = "spring.sleuth.async.configurer.enabled", matchIfMissing = true)
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	static class DefaultAsyncConfigurerSupport extends AsyncConfigurerSupport {

		@Autowired
		private BeanFactory beanFactory;

		@Override
		public Executor getAsyncExecutor() {
			// you're saying that this default shouldn't be here...
			return new LazyTraceExecutor(this.beanFactory, new SimpleAsyncTaskExecutor());
		}

	}
```

**Comment by brenuart** [comment]
That's the culprit indeed.
The condition `@ConditionalOnMissingBean(AsyncConfigurer.class)` is not enough - it doesn't take into account the fact that Spring will also consider the TaskExecutor or Executor it may find in the context (see original description).

As a temporary workaround, we disabled Sleuth's default async configurer by setting `spring.sleuth.async.configurer.enabled` to false. Then we added the following configuration in our code:

```
@Configuration
@AutoConfigureBefore(AsyncCustomAutoConfiguration.class)
public class SchedulingAutoConfiguration {
	
	@Bean
	@Lazy
	@Conditional(OnNoAsyncExecutorFound.class)
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	public AsyncConfigurer defaultAsyncConfigurer() {
		Logger logger = LoggerFactory.getLogger(SchedulingAutoConfiguration.class);
		logger.warn(
				"Using an unbounded SimpleAsyncTaskExecutor that fires up a new thread for each task for @Async processing. " +
				"To use another strategy, register an AsyncConfigurer, a single or primary TaskExecutor or an Executor named 'taskExecutor' in the context.");
		
		return new AsyncConfigurerSupport() {
			@Override
			public Executor getAsyncExecutor() {
				return new SimpleAsyncTaskExecutor();
			}
		};
	}
	

	private static class OnNoAsyncExecutorFound extends NoneNestedConditions {
		OnNoAsyncExecutorFound() {
	        super(ConfigurationPhase.REGISTER_BEAN);
	    }

	    @ConditionalOnBean(AsyncConfigurer.class)
	    static class OnAsyncConfigurer {
	    }
	    
	    @ConditionalOnSingleCandidate(TaskExecutor.class)
	    static class OnTaskExecutor {
	    }
	    
	    @Conditional(OnDefaultTaskExecutor.class)
	    static class OnDefaultExecutor {
	    }
	}
	 
	
	/**
	 * Condition matching when a bean of type {@link Executor} and named {@link AsyncExecutionAspectSupport#DEFAULT_TASK_EXECUTOR_BEAN_NAME}
	 * is found in the context.
	 * <p>
	 * Similar to {@link ConditionalOnMissingBean @ConditionalOnMissingBean} except that both the type and 
	 * the name must match.
	 */
	private static class OnDefaultTaskExecutor extends SpringBootCondition {
		@Override
		public ConditionOutcome getMatchOutcome(ConditionContext context, AnnotatedTypeMetadata metadata) {
			String[] beanNames = BeanFactoryUtils.beanNamesForTypeIncludingAncestors(context.getBeanFactory(), Executor.class, true, false);
			for(String beanName: beanNames) {
				if (AsyncExecutionAspectSupport.DEFAULT_TASK_EXECUTOR_BEAN_NAME.contentEquals(beanName)) {
					return ConditionOutcome
							.match("Found Executor with name "+AsyncExecutionAspectSupport.DEFAULT_TASK_EXECUTOR_BEAN_NAME);
				}
			}

			return ConditionOutcome
					.noMatch("Did not find Executor with name "+AsyncExecutionAspectSupport.DEFAULT_TASK_EXECUTOR_BEAN_NAME);
		}
	}
}
```

**Comment by marcingrzejszczak** [comment]
Nice! Do you happen to have a sample that is broken? I could use it as a test that would break ATM.

**Comment by brenuart** [comment]
I'm trying to build a sample... shouldn't be too hard.

There is another potential issue I'm thinking of atm... What would happen if my `AsyncConfigurer` gets the executor from the application context? My first impression is it will be instrumented *twice*: once because Sleuth found the executor bean in the context (by means of its post processor), and a second time because of its instrumentation of the configurer. Is that a problem? Wouldn't it cause duplicate spans?

**Comment by marcingrzejszczak** [comment]
> My first impression is it will be instrumented _twice_: once because Sleuth found the executor bean in the context (by means of its post processor), and a second time because of its instrumentation of the configurer. Is that a problem? Wouldn't it cause duplicate spans?

If you have you own `AsyncConfigurer` then we don't wrap yours since the configuration has `	@ConditionalOnMissingBean(AsyncConfigurer.class)`.

**Comment by brenuart** [comment]
What about what happens in `AsyncCustomAutoConfiguration` then ?

**Comment by marcingrzejszczak** [comment]
It's a bean post processor that wraps all of your customizers in such a way that whatever `Executor` you've defined, will be wrapped in a `LazyTraceExecutor` wrapper.

**Comment by brenuart** [comment]
Here is a simple JUnit test case to illustrate the case.
[GH1212Tests.java.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2856843/GH1212Tests.java.zip)

**Comment by marcingrzejszczak** [comment]
@brenuart thanks for the test - it helped to debug the issue. Now the logic is such that it will try to pick the proper executor and fallback to the default if necessary. Can you double check that it works as expected now?

**Comment by brenuart** [comment]
Sounds good.
You replicated the logic found in `AsyncExecutionAspectSupport` instead of relying on conditions as in my proposal. It has the added benefit of logging the same warning messages as the aspect would do.

However, we should be aware that those warnings will be printed *even* if the async framework doesn't use the default executor. This happens if you explicitly name an executor in your `@Async` annotations. This may be confusing for some people...

**Comment by marcingrzejszczak** [comment]
> However, we should be aware that those warnings will be printed _even_ if the async framework doesn't use the default executor. This happens if you explicitly name an executor in your `@Async` annotations. This may be confusing for some people...

I have modified one of the tests to replicate that behavior and I don't see such logs.

**Comment by marcingrzejszczak** [comment]
You can check https://github.com/spring-cloud/spring-cloud-sleuth/commit/c225cadb2dfb94a91b17385b7fd6437e07c9ea1c for more details (maybe I've done sth wrong though).
