### ISSUE TITLE
Add support for SQS

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#1217]

**Comment by devinsba** [comment]
@marcingrzejszczak can you elaborate a bit on this? Have you looked at: https://github.com/SmartThingsOSS/smartthings-brave/tree/master/brave-sqs if you are considering the propagation. Or are you thinking more along the lines of native integration with `spring-cloud-aws-messaging`. I've been working through this exact thing the last couple weeks so I'm interested in the approach and how I can make our apps less custom

**Comment by marcingrzejszczak** [comment]
> Have you looked at: https://github.com/SmartThingsOSS/smartthings-brave/tree/master/brave-sqs if you are considering the propagation

I haven't. Thanks for pointing it out!

> Or are you thinking more along the lines of native integration with `spring-cloud-aws-messaging`.

I was also thinking about it. I wanted to make sure that it's actually working. `spring-cloud-aws-messaging` is using Spring messaging under the hood, so I wanted to double check if it maybe works out of the box right now (by any chance).

>  I've been working through this exact thing the last couple weeks so I'm interested in the approach and how I can make our apps less custom.

I'd love to join forces then. Whatever works, we can autoconfigure it in Sleuth.

**Comment by devinsba** [comment]
@marcingrzejszczak I spiked an attempt in #1218

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-sleuth/pull/1218
