### ISSUE TITLE
How to use spring cloud sleuth for RabbitListener and RabbitTemplate

### ISSUE THREAD

**Issue by alihasanzaade** [spring-cloud/spring-cloud-sleuth#1219]
I want to send RabbitMQ messages tracking event to Zipkin with using spring cloud sleuth, After many research I found some configuration added recently to spring in order to manage it you can find in [here](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceMessagingAutoConfiguration.java), But unfortunately there is not any  documentation that explains how can we configure it, I tried many ways but I couldn't send tracking events to Zipkin.

Please advice

**Comment by spencergibb** [comment]
Please don't cross post. Closing in favor of https://stackoverflow.com/questions/54845174/how-to-use-spring-cloud-sleuth-for-rabbitlistener-and-rabbittemplate
