### ISSUE TITLE
If Zipkin server is down them app goes OOM

### ISSUE THREAD

**Issue by Sutty100** [spring-cloud/spring-cloud-sleuth#1228]
If the Zipkin server can not be reached then our application rapidly consumes heap space with 
zipkin2.reporter.InMemoryReporterMetrics steadily occupying more and more heap until our application goes OOM. 
![Screenshot 2019-03-11 at 14 19 45](https://user-images.githubusercontent.com/8058978/54130781-f1e11d00-4408-11e9-8438-12b034a675dd.png)

We are using version 2.0.0.RELEASE version of Sleuth.

Seems like there should be some sort of limit here to prevent this growing out of control?

**Comment by devinsba** [comment]
@Sutty100 this was fixed in `2.0.1` please update your sleuth version. In the future it is always advisable to try updating first before reporting an issue

**Comment by shakuzen** [comment]
I guess it was this fix in Zipkin's Java Reporter that fixed the issue: https://github.com/openzipkin/zipkin-reporter-java/pull/119

**Comment by Sutty100** [comment]
Thanks, will close the issue
