### ISSUE TITLE
Need Fully Custom URL for collector

### ISSUE THREAD

**Issue by msennett9** [spring-cloud/spring-cloud-sleuth#1229]
We are experimenting with sending Zipkin spans to a Splunk Http event collector instead of a regular Zipkin collector.  The RestTemplateSender for the Zipkin2 integration always appends "api/v2/spans" to the baseURL, which is not a valid URL in our Splunk setup.  It would be helpful if we could specify the complete URL in this case without having "api/v2/spans" appended to it.  From the documentation, I can see that we could completely replace the Sender class and change this, but we'd prefer not to do this if adding a simple property would work instead.

**Comment by devinsba** [comment]
There are 2 ways you can customize the `RestTemplate` that is used: https://cloud.spring.io/spring-cloud-sleuth/single/spring-cloud-sleuth.html#_sending_spans_to_zipkin

If the `ZipkinRestTemplateCustomizer` does not provide what you need then you will need to create a custom instance of `Sender`.

**Comment by msennett9** [comment]
> If the `ZipkinRestTemplateCustomizer` does not provide what you need then you will need to create a custom instance of `Sender`.

Yes - I did see that doc ... The customizer doesn't allow customizing the URL since this it is part of the sender, not the template.  And I didn't want to create the custom instance of `Sender` just to change the way it is appending `api/v2/spans` to the baseUrl.  It seems reasonable to allow the full Url to be controlled by a property if that is what the developer wants, without duplicating the rest of the code in `RestTemplateSender`.

**Comment by marcingrzejszczak** [comment]
We never considered parametrizing the URL. You're the first user to ask for this feature. Once there are more people interested in this change we can consider adding the feature. Until then you need to create the custom `Sender` instance.

**Comment by msennett9** [comment]
We experimented with implementing our own `Sender` and noticed that events were being sent twice - once from `RestTemplateSender` and once from our sender.  I will try to recreate in a small example - we were probably doing something wrong.

**Comment by devinsba** [comment]
A recent feature was added where multiple senders can be created, to not have that happen your sender needs to have a name of `ZipkinAutoConfiguration.SENDER_BEAN_NAME`

**Comment by msennett9** [comment]
The feature to _not_ have multiple senders is only in the 2.2 release, correct?  So, as I understand it, unless we go with the 2.2 snapshot build, using our own RestTemplateSender will result in multiple events.

**Comment by marcingrzejszczak** [comment]
If you create your own sender with name `ZipkinAutoConfiguration.SENDER_BEAN_NAME` then the whole configuration will not be applied and there will be only one sender - yours.That's the suggested way to go.
