### ISSUE TITLE
Convert to/from hex when interacting with headers

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#125]
Some headers are hexed and some are not right now (e.g. https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/integration/AbstractTraceChannelInterceptor.java#L53). So we need to be consistent and the suggestion is to always use hex because that matches the zipkin API (even though, confusingly, Zipkin stores longs in its SpanStore).

**Comment by adriancole** [comment]
Longs are a side effect of the original payload form (thrift), also I
suspect they are better indexed than strings or raw byte arrays
(conjecture).

Hex encoding was originally there to prevent ppl from missing the minus
sign when copy and pasting a trace id.

Also makes sense in json as large json numbers otherwise need to be quoted
iirc.

**Comment by dsyer** [comment]
Yeah, I get all that. It makes me wonder if we are coupling too tightly with Zipkin though. If we went back to String for ids we could make them hexed longs by default, and everything would look the same to users, but we wouldn't have to remember (and risk not doing so) to pack and unpack them every time we cross a boundary.

**Comment by adriancole** [comment]
I feel you, but I'd hesitate.

Stringifying could reintroduce the temptation to toy with id naming
conventions etc. which.. happened ;) There is some value to a fixed
boundary, and it is easier to do that with longs vs a regex+length
constraint on a string.

We are coupled to zipkin but that's more about the UI etc, but I think wrt
id it is more about dapper variants. Ex dapper variants zipkin, htrace,
Google cloud trace all have fixed length opaque ids encoded as numbers.

If I understand correctly gRPC will treat ids as opaque bytes ;) Ex tag
sets (which hold ids) have a printable flag, which ids will not have set.

I don't know if they will actually map ids individually as HTTP headers
either.. I'm noticing some propagate context with just a blob that includes
all sorts of things. Ex "Context-Tracing: base64blob"

Ex id, sampling flags etc are all in that bag together, so no need to hex
them.

We can choose whatever of course, just not a big fan of ids as strings in
raw span structs, at least of primary motivation is how they look if
individually mapped as propagation headers.
