### ISSUE TITLE
Each Flux/Mono.subscribeOn() Flux/Mono.publishOn() produces async Span

### ISSUE THREAD

**Issue by robotmrv** [spring-cloud/spring-cloud-sleuth#1260]
```java
@GetMapping
Mono<String> test() {
	return Mono.just("ok")
			.subscribeOn(Schedulers.single())
			.publishOn(Schedulers.parallel())
			.publishOn(Schedulers.elastic())
			.publishOn(Schedulers.parallel());
}
```
Due to Sleuth instrumentation of Reactor Schedulers this code (every Mono.subscribeOn(), Mono.publishOn() switch) produces async Span.
From my point of view this spans are not very useful as they just "pollute" whole tracing picture.
And it is not clear what is the function of this instrumentation as Span is propagated by Reactor Context
https://github.com/spring-cloud/spring-cloud-sleuth/blob/c5b3b38b09182c6435f3949e56124dbe1a7f49ac/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/TraceReactorAutoConfiguration.java#L117:L120

Is it possible to make Schedulers instrumentation optional by property?
https://github.com/spring-cloud/spring-cloud-sleuth/blob/c5b3b38b09182c6435f3949e56124dbe1a7f49ac/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/TraceReactorAutoConfiguration.java#L121:L125

example https://github.com/robotmrv/async-span-on-each-scheduler-change
#### Test Case:
0. start zipkin
1. start application
2. curl http://localhost:8080/
#### Expected Result:
Only one span was created
#### Actual Result
Five spans were created. One for the web request and one for each Mono.subscribeOn(), Mono.publishOn() (there are 4)

Zipkin output
![image](https://user-images.githubusercontent.com/7793957/54495763-8eb32700-48ef-11e9-97e1-5a0e71091220.png)

```json
[
  {
    "traceId": "47f9e42180743ba8",
    "parentId": "47f9e42180743ba8",
    "id": "000d90be78278f4c",
    "name": "async",
    "timestamp": 1552842670048458,
    "duration": 10632,
    "localEndpoint": {
      "serviceName": "async-span",
      "ipv4": "10.238.10.120"
    }
  },
  {
    "traceId": "47f9e42180743ba8",
    "parentId": "47f9e42180743ba8",
    "id": "e1cd31561a3578dd",
    "name": "async",
    "timestamp": 1552842670059121,
    "duration": 10631,
    "localEndpoint": {
      "serviceName": "async-span",
      "ipv4": "10.238.10.120"
    }
  },
  {
    "traceId": "47f9e42180743ba8",
    "parentId": "47f9e42180743ba8",
    "id": "aca3caf889fd694a",
    "name": "async",
    "timestamp": 1552842670069966,
    "duration": 11159,
    "localEndpoint": {
      "serviceName": "async-span",
      "ipv4": "10.238.10.120"
    }
  },
  {
    "traceId": "47f9e42180743ba8",
    "parentId": "47f9e42180743ba8",
    "id": "c7b4941f6264297b",
    "name": "async",
    "timestamp": 1552842670080822,
    "duration": 12677,
    "localEndpoint": {
      "serviceName": "async-span",
      "ipv4": "10.238.10.120"
    }
  },
  {
    "traceId": "47f9e42180743ba8",
    "id": "47f9e42180743ba8",
    "kind": "SERVER",
    "name": "get /",
    "timestamp": 1552842670001342,
    "duration": 99940,
    "localEndpoint": {
      "serviceName": "async-span",
      "ipv4": "10.238.10.120"
    },
    "tags": {
      "http.method": "GET",
      "http.path": "/",
      "mvc.controller.class": "Endpoint",
      "mvc.controller.method": "test"
    }
  }
]
```

**Comment by marcingrzejszczak** [comment]
Correct, we needed to add it back since we were losing the thread context propagation. As a side effect we have this beautiful `async-span`. 

As a workaround, you could, theoretically, drop those spans by creating a `FinishedSpanHandler` and dropping all `async-spans` with no `tags` ?

**Comment by robotmrv** [comment]
Thanks @marcingrzejszczak, WA works.

**Comment by marcingrzejszczak** [comment]
Closing since there's a workaround in case someone wants to remove those
