### ISSUE TITLE
[1.3] microseconds in span duration is lost when changing span to Builder 

### ISSUE THREAD

**Issue by chang-chao** [spring-cloud/spring-cloud-sleuth#1263]
When a span is created and stopped,  `duration` field contains microseconds.
But when the span is converted to a builder and after some customizations, the microseconds in  `duration`  will be lost in the cloned span.

Because of this issue, when a span finished in one millisecond, Brave client will treat duration of the final span as 0 microsecond and will not send `duration` to zipkin, whereas the field should and could be sent.

The following code can reproduce the issue.

    @Test
    public void test() {
        Span span = Span.builder().name("name").build();
        span.stop();

        // say we want to adjust the span in SpanAdjuster
        Span adjustedSpan = span.toBuilder().name("service::" + span.getName()).build();

        // assert that the total amount of time is equal between the two spans.
        Assert.assertEquals(span.getAccumulatedMicros(), adjustedSpan.getAccumulatedMicros());
    }

This issue applies to version 1.3.x.

**Comment by marcingrzejszczak** [comment]
I think you should file this issue in Brave, since SLeuth is reusing Brave.

**Comment by devinsba** [comment]
Well, the user also mentions Sleuth 1.3, which does not use brave, though they mention that as well. Seems more information would be needed to reopen the issue

**Comment by chang-chao** [comment]
@marcingrzejszczak 
> ...SLeuth is reusing Brave.

No, not before 2.0. the `Span` class in my test case is [org.springframework.cloud.sleuth.Span](https://github.com/spring-cloud/spring-cloud-sleuth/blob/1.3.x/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java).

**Comment by marcingrzejszczak** [comment]
Oops, I haven't noticed that. Note that `1.3` is old and we're not planning to patch it with anything other than critical fixes.

**Comment by chang-chao** [comment]
> Oops, I haven't noticed that. Note that `1.3` is old and we're not planning to patch it with anything other than critical fixes.

Well, this issue is a just minor one, so it is ok to be closed.
