### ISSUE TITLE
Spring Cloud Sleuth GCP netty-tcnative unavailable

### ISSUE THREAD

**Issue by rajivml** [spring-cloud/spring-cloud-sleuth#1265]
HI, I am trying to integrate spring cloud sleuth gcp module into my spring boot project but am running into some issues and couldn't figure out how to resolve the same. 

In the Non Docker environment i.e through intellij app is running fine, but through docker or when it's deployed onto GKE am running into the below issue.

Spring Boot version:  2.1.1.RELEASE
Spring Cloud Dependencies Version: Greenwich.SR1

Other Dependencies which am using to setup sleuth:

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-rabbit</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-test-support</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-gcp-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-gcp-starter-trace</artifactId>
        </dependency>

I tried adding below libraries, following this dependency matrix https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty, but no luck, 

        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty-shaded</artifactId>
            <version>1.16.1</version>
        </dependency>
        
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>4.1.30.Final</version>
        </dependency>
        
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.17.Final</version>
        </dependency>

application.properties:
#https://stackoverflow.com/questions/53765439/error-creating-bean-with-name-rabbitlistenercontainerfactory
spring.cloud.gcp.trace.enabled=true
spring.sleuth.sampler.probability=1
spring.sleuth.web.skipPattern=(^cleanup.*|.+favicon.*)
spring.application.name=model-management
spring.rabbitmq.listener.direct.retry.enabled=true
spring.rabbitmq.listener.simple.retry.enabled=true

Stack Trace:
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative] at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:104) ~[grpc-netty-shaded-1.16.1.jar!/:1.16.1] at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:440) ~[grpc-netty-shaded-1.16.1.jar!/:1.16.1] at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:97) ~[grpc-netty-shaded-1.16.1.jar!/:1.16.1] at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:244) [grpc-netty-shaded-1.16.1.jar!/:1.16.1] at 

Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_646625172353831907268.so: Error loading shared library libcrypt.so.1: No such file or directory (needed by /tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_646625172353831907268.so) at java.lang.ClassLoader$NativeLibrary.load(Native Method) at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) at

Complete Stack Trace: https://pastebin.com/HTWqaybN

Plz let me know in case of any other info needed.

Thanks!!

**Comment by rajivml** [comment]
BTW, Am using Alpine Linux to Dockerize the Spring Boot App

# Alpine Linux with OpenJDK JRE
FROM docker.io/openjdk:8-jre-alpine

**Comment by rajivml** [comment]
I have tried dockerizing with distroless java8 image instead of Alpine, that image is running fine and traces are getting generated fine without adding any additional libraries like netty, but still there is one more issue where traces aren't visible through their UI. Will debug it further

FROM gcr.io/distroless/java:8

**Comment by adriancole** [comment]
in regular alpine I think you need to use jetty alpn or otherwise. I dont
think this issue is strictly related to sleuth as it is more about the
requirements of grpc

**Comment by rajivml** [comment]
Thanks for the reply @adriancole . You can close the issue
