### ISSUE TITLE
Message producer not starting new span

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#128]
This is a new feature and I think it's a bug. Let's say you receive an http request that means you have to send a message. The result should be a new span. If we count the spans in the brewery, I bet they have changed since last week.

**Comment by marcingrzejszczak** [comment]
Assuming that we take the set up into account we should have the following flow:

We should have 6 spans:
- first HTTP incoming message with its parent (2 spans)
- then there is the message sent and received (2 spans)
- then I'm calling rest template to myself with the HTTP message (1 span)
- then I'm receiving that HTTP message (2 spans  but one is the same as the one in the first step)

2 + 2 + 1 + 1 = 6 spans. ATM we're missing this part: 

> then there is the message sent and received
