### ISSUE TITLE
Error creating bean with name 'traceWebFilter'

### ISSUE THREAD

**Issue by wdudek13** [spring-cloud/spring-cloud-sleuth#1282]
When using Artemis broker and enabling sleuth tracing for JMS: 
`sleuth.messaging.jms.enabled=true`
the exception is thrown and the application fails:
`### Caused by: java.lang.IllegalStateException: Unable to create indicator class org.springframework.boot.actuate.jms.JmsHealthIndicator for source interface javax.jms.ConnectionFactory`
See attached stacktrace.

**Possible solution:**
Artemis client implements both XAConnectionFactory & ConnectionFactory but  TracingConnectionFactoryBeanPostProcessor creates LazyXAConnectionFactory only implementing first one and JmsAutoConfiguration works incorrectly as it depends on:
`@ConditionalOnBean({ConnectionFactory.class})`
TracingConnectionFactoryBeanPostProcessor should probably create factory implementing both interfaces i.e.. XAConnectionFactory & ConnectionFactory

**Recreated using:**  
sleuthVersion= cloud version or '2.1.1.RELEASE'
springCloudVersion = 'Greenwich.SR1' or 'Greenwich.RELEASE'
artemisVersion = '2.6.4'   
[exception.log](https://github.com/spring-cloud/spring-cloud-sleuth/files/2996115/exception.log)

**Comment by marcingrzejszczak** [comment]
Can you create a PR with the suggested solution? :)

**Comment by marcingrzejszczak** [comment]
Remember to do it towards `2.1.x` branch

**Comment by marcingrzejszczak** [comment]
That's been already fixed via https://github.com/spring-cloud/spring-cloud-sleuth/commit/1b493e602a837536c6bccfa84c96ddf6ed169ca4
