### ISSUE TITLE
traceId transfer in threadpool

### ISSUE THREAD

**Issue by shuliu8** [spring-cloud/spring-cloud-sleuth#1283]
hello, I am using sleuth to track the requests across microservices. One of my service is running jobs using a thread pool. How do I transfer the traceId values to the threads? is there a sleuth wrapped thread pool/executor available?

**Comment by NearteamABE** [comment]
Hello,
Sleuth intercepts ThreadExecutor calls and TraceId is inherited by child threads. Just pay attention to bind your ThreadExecutor as a Spring bean. (If not Sleuth can't know it).
Example with Spring-batch : 
`    @Bean
    public JobLauncher jobLauncher(@Named(BATCH_EXECUTOR) TaskExecutor taskExecutor) throws Exception {
        SimpleJobLauncher jobLauncher = new SimpleJobLauncher();
        jobLauncher.setJobRepository(jobRepository);
        jobLauncher.setTaskExecutor(taskExecutor);
        jobLauncher.afterPropertiesSet();
        return jobLauncher;
    }

    @Bean(BATCH_EXECUTOR)
    public TaskExecutor taskExecutor() {
        return new SimpleAsyncTaskExecutor();
    }`

**Comment by marcingrzejszczak** [comment]
@NearteamABE is right. I'll close the issue.
