### ISSUE TITLE
Change RestTemplate in ZipkinRestTemplateSenderConfiguration

### ISSUE THREAD

**Issue by natrem** [spring-cloud/spring-cloud-sleuth#1327]
I'm trying to send spans to a zipkin server secured via OAuth2.
For this purpose the provided extension `ZipkinRestTemplateCustomizer` does not fit.
Is it possible to declare the used `ZipkinRestTemplateWrapper` as a Bean with `ConditionalOnMissingBean` annotation?
I think that this would be the minimum update allowing me to override it simply.

I don't have any solution to merge quite simply the Oauth2 feature with the existing specific `ZipkinRestTemplateWrapper` so I think this support might wait (I don't use the URI resolution so I'm fine without it).

If you're ok with that proposition I'm willing to try it. Apart from the tests I did not look at it's a quite straightforward update in `ZipkinRestTemplateSenderConfiguration`.

**Comment by marcingrzejszczak** [comment]
What exactly is missing currently in the `ZipkinRestTemplateCustomizer` ?

**Comment by natrem** [comment]
With `ZipkinRestTemplateCustomizer` you can update the provided RestTemplate but ni my case I'd like to use an `OAuth2RestTemplate`. I don't think it's easy to plug-in with this extension mechanism.

**Comment by natrem** [comment]
#1446 will allow this customization.
