### ISSUE TITLE
Vulnerable dependency needs to be updated. 

### ISSUE THREAD

**Issue by ghsatpute** [spring-cloud/spring-cloud-sleuth#1328]
I am using `org.springframework.cloud:spring-cloud-starter-sleuth:jar:2.1.1.RELEASE`. We are using BlackDuck product and it revealed that one of the indirect dependency has security issues. 
![image](https://user-images.githubusercontent.com/3480767/55555443-eb417f00-5702-11e9-8956-1e954a7eebd2.png)

This is dependency tree. 
```
[INFO] +- org.springframework.cloud:spring-cloud-starter-sleuth:jar:2.1.1.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter:jar:2.0.0.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-context:jar:2.0.0.RELEASE:compile
[INFO] |  |  |  \- org.springframework.security:spring-security-crypto:jar:5.0.6.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-commons:jar:2.0.0.RELEASE:compile
[INFO] |  |  \- org.springframework.security:spring-security-rsa:jar:1.0.5.RELEASE:compile
[INFO] |  |     \- org.bouncycastle:bcpkix-jdk15on:jar:1.56:compile
[INFO] |  |        \- org.bouncycastle:bcprov-jdk15on:jar:1.56:compile
```

The version `1.60` of `bcpkix-jdk15on` was suggested to be used.

**Comment by devinsba** [comment]
I'm not sure exactly your dependency tree has those specific deps in it. In order to use sleuth 2.1.x you should also have spring-cloud 2.1.x, which has the updated versions in it that you are looking for

**Comment by ghsatpute** [comment]
Hi @devinsba . 
As shown in the dependency tree, the dependencies are coming as below. 
```[INFO] +- org.springframework.cloud:spring-cloud-starter-sleuth:jar:2.1.1.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter:jar:2.0.0.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-context:jar:2.0.0.RELEASE:compile
[INFO] |  |  |  \- org.springframework.security:spring-security-crypto:jar:5.0.6.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-commons:jar:2.0.0.RELEASE:compile
[INFO] |  |  \- org.springframework.security:spring-security-rsa:jar:1.0.5.RELEASE:compile
[INFO] |  |     \- org.bouncycastle:bcpkix-jdk15on:jar:1.56:compile
[INFO] |  |        \- org.bouncycastle:bcprov-jdk15on:jar:1.56:compile```

**Comment by devinsba** [comment]
`org.springframework.cloud:spring-cloud-starter-sleuth:jar:2.1.1.RELEASE:compile`

AND

`org.springframework.cloud:spring-cloud-starter:jar:2.0.0.RELEASE:compile`

are not versions from the same cloud release, please align the versions. Spring-cloud-commons 2.1.x already has the version updated: https://github.com/spring-cloud/spring-cloud-commons/blob/v2.1.1.RELEASE/spring-cloud-commons-dependencies/pom.xml#L18, also that is the project this issue belongs on

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by Usha3012** [comment]
Hi, I am also facing similar type of issue as mention by @ghsatpute while using PACT as CDC

**Comment by marcingrzejszczak** [comment]
We will bump the deps, don't worry
