### ISSUE TITLE
Problems with feign and Oauth2RestTemplate

### ISSUE THREAD

**Issue by zhangxiaozhou** [spring-cloud/spring-cloud-sleuth#1330]
When the default RestTemplate send request is used, zipkin can track my request link. However, when using Oauth2RestTemplate to send a request to an Oauth2 protected service, zipkin cannot track it. And when using Feign, it is also impossible to track.

**Comment by spencergibb** [comment]
Can you tell us what versions you are using? How is the `OAuth2RestTemplate` created? We need more details.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
