### ISSUE TITLE
Enhancement: Include Path Template  in Client Span Names

### ISSUE THREAD

**Issue by msmsimondean** [spring-cloud/spring-cloud-sleuth#1331]
I have Sleuth set up in a Spring Boot app.  Sleuth is including the `path template` in the parent span's name which is great.  An example parent span name would be `get /example/{exampleId}`.  For child spans that represent RestTemplate calls, those span names just the HTTP verb and not the `path template`.  Is there a way that Slueth could include the `path template` in spans for RestTemplate?  Thanks

**Comment by msmsimondean** [comment]
Here's an example screenshot showing the parent span with `HTTP Method + path template` and the RestTemplate spans including only `path template`: 

<img width="428" alt="image" src="https://user-images.githubusercontent.com/5443142/55730302-c6555080-5a0f-11e9-9af3-4cd03fe86db6.png">

**Comment by shakuzen** [comment]
This would require a change in Spring Framework to make the templated URI available (if used) to the interceptor which is making the span (see Brave's `TracingClientHttpRequestInterceptor`). Currently, that information is lost when RestTemplate expands the URI.

**Comment by marcingrzejszczak** [comment]
Until Spring provides this information we won't be able to do much. I'll close this issue until a change in Spring appears and allows us to consider adding this feature.

**Comment by shakuzen** [comment]
I thought there was a framework issue already, but I can't find it. @msmsimondean perhaps you can try searching the Spring framework issues also and if you don't find anything open an issue requesting the original request uri template be made available to the request interceptor for this purpose.

**Comment by msmsimondean** [comment]
Thanks @shakuzen I've searched through the issues on Spring Framework and not found an issue.  I've raised a new issue https://github.com/spring-projects/spring-framework/issues/22852
