### ISSUE TITLE
Spring-Integration blocks trace headers downstream

### ISSUE THREAD

**Issue by dschulten** [spring-cloud/spring-cloud-sleuth#1333]
**Bug report**

Affected: Greenwich.RELEASE, resolves to spring-cloud-sleuth-core 2.1.0-RELEASE

The TraceSpringIntegrationAutoConfiguration successfully registers a global channel interceptor, but outgoing calls, e.g. via Http outbound components, do not propagate the X-B3-* headers.
This is caused by Spring-Integrations header mapping feature, which ensures that internal headers will not be sent downstream.

The effect is that downstream Sleuth-enabled services create fresh trace ids because they receive no X-B3-* headers.

Ideally, the outbound X-B3-* headers should automatically pass through when Sleuth is on the classpath. At least it would be helpful to mention this in the reference manual, where Spring-Integration is discussed.

Workaround:

I helps to register a custom DefaultHttpHeaderMapper manually on every inbound and outbound Http endpoint:

    // as part of a Spring Integration DSL flow:
    .handle(Http.outboundChannelAdapter(downstreamServiceUrl)
                    .httpMethod(HttpMethod.POST)
                    .headerMapper(headerMapper())

    @Bean
    public DefaultHttpHeaderMapper headerMapper() {
        DefaultHttpHeaderMapper ret = new DefaultHttpHeaderMapper();
        ret.setInboundHeaderNames(new String[]{"*"}); 
        ret.setOutboundHeaderNames(new String[]{"HTTP_REQUEST_HEADERS", "X-B3-*"});
        ret.setUserDefinedHeaderPrefix("");
        return ret;
    }

**Comment by ryanjbaxter** [comment]
cc @artembilan

**Comment by marcingrzejszczak** [comment]
@artembilan do you think we can handle it somehow in the global channel interceptor?

**Comment by artembilan** [comment]
No, this is not what we can do by the `ChannelInterceptor` at all.
The feature belongs to the mentioned `DefaultHttpHeaderMapper` which really has only this set of headers to map to the outbound HTTP request:
```
	private static final String[] HTTP_REQUEST_HEADER_NAMES = new String[] {
			HttpHeaders.ACCEPT,
			HttpHeaders.ACCEPT_CHARSET,
			HttpHeaders.ACCEPT_ENCODING,
			HttpHeaders.ACCEPT_LANGUAGE,
			HttpHeaders.ACCEPT_RANGES,
			HttpHeaders.AUTHORIZATION,
			HttpHeaders.CACHE_CONTROL,
			HttpHeaders.CONNECTION,
			HttpHeaders.CONTENT_LENGTH,
			HttpHeaders.CONTENT_TYPE,
			HttpHeaders.COOKIE,
			HttpHeaders.DATE,
			HttpHeaders.EXPECT,
			HttpHeaders.FROM,
			HttpHeaders.HOST,
			HttpHeaders.IF_MATCH,
			HttpHeaders.IF_MODIFIED_SINCE,
			HttpHeaders.IF_NONE_MATCH,
			HttpHeaders.IF_RANGE,
			HttpHeaders.IF_UNMODIFIED_SINCE,
			HttpHeaders.MAX_FORWARDS,
			HttpHeaders.PRAGMA,
			HttpHeaders.PROXY_AUTHORIZATION,
			HttpHeaders.RANGE,
			HttpHeaders.REFERER,
			HttpHeaders.TE,
			HttpHeaders.UPGRADE,
			HttpHeaders.USER_AGENT,
			HttpHeaders.VIA,
			HttpHeaders.WARNING
	};
```

Of course we can adjust that component in Spring Integration to apply that `X-B3-*` pattern by default as well, however before jumping into the potential solution I would like to know how tracing headers are propagated in case of raw `RestTemplate` usage.
Do we still need to do something in the target application to have such a propagation or do you have in Sleuth some smart reconfiguration for end-user components?

**Comment by marcingrzejszczak** [comment]
We have an interceptor that should handle insertion of headers. I'm starting to guess that the resttemplate  used in this flow is not a bean and that's why the context is not propagated.

**Comment by artembilan** [comment]
OK, thanks, @marcingrzejszczak .

Can you share the code with me to understand better what is going on?

**Comment by artembilan** [comment]
@dschulten ,

You can inject an auto-configured `RestTemplate` into that `Http.outboundChannelAdapter()`.
According SC Sleuth post-processing there is a `LazyTracingClientHttpRequestInterceptor` injection into the `RestTemplate` bean.
So, that should work for you without any header mapping manipulations.

**Comment by marcingrzejszczak** [comment]
In other words, when the `RestTemplate` is a bean and gets injected to your flow, and you have a Sleuth on the classpath, things should work out of the box

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
