### ISSUE TITLE
 NullPointer on error message being sent to errorChannel

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#1335]
Originally posted here https://github.com/spring-projects/spring-integration/issues/2897

**Comment by artembilan** [comment]
Thanks, Marcin!

Let us know if you need a review for the fix when it is issued.

**Comment by marcingrzejszczak** [comment]
Ooops, I haven't noticed your suggestion @artembilan . This is how I think I fixed it - https://github.com/spring-cloud/spring-cloud-sleuth/commit/c287fd8ea525cff474e116f14c1d89e07c5a0e75

**Comment by artembilan** [comment]
LGTM! 😄
