### ISSUE TITLE
spring.zipkin.baseUrl not visible in "kubernetes" profile

### ISSUE THREAD

**Issue by adzubla** [spring-cloud/spring-cloud-sleuth#1339]
I'm using spring-cloud-starter-kubernetes-config and spring-cloud-starter-zipkin (Greenwich.SR1, boot 2.1.4.RELEASE) running on Kubernetes.

The property "spring.zipkin.baseUrl" works fine when used in "application.properties" but is not available when moved to "application-kubernetes.properties" and the localhost default is used instead.

**Comment by marcingrzejszczak** [comment]
Have you tried setting it in `bootstrap.properties` ?

**Comment by adzubla** [comment]
It works in "bootstrap.properties" but not in "bootstrap-kubernetes.properties"

I want to use a local configuration (localhost) and the spring-cloud "kubernetes" profile to use another server inside de kubernetes cluster.

All other properties (like datasources) can be in -kubernetes.properties but not "spring.zipkin.baseUrl".
I tried to inject it using @Value("${spring.zipkin.baseUrl"}) and spring boot gave me an error.

**Comment by spencergibb** [comment]
There is a known issue around bootstrap and profiles in spring cloud commons in the manner your describe. We can close this and I'll find the issue to post here later.

**Comment by ammarsohail1** [comment]
Hey @spencergibb , is there an update about the issue? I am also facing the same, my K8s instance is calling localhost instead of the provided collector URL.
