### ISSUE TITLE
Add ability to include / exclude Redis command args from span tags

### ISSUE THREAD

**Issue by datagitlies** [spring-cloud/spring-cloud-sleuth#1344]
Since Redis tracing is now enabled by default - _see_ #1267 it would be a good idea to allow users to [include / exclude Redis command args from span tags](https://github.com/lettuce-io/lettuce-core/pull/920) since including them by default can be problematic for a few reasons...

**Note**: the ability to include/exclude Redis command args was added to `lettuce-core` but that code has not yet been released as of 4-30-2019. See their `5.2.0` milestone [here](https://github.com/lettuce-io/lettuce-core/milestone/51?closed=1).

**Comment by datagitlies** [comment]
@chang-chao @marcingrzejszczak @shakuzen @ryanjbaxter the `5.2.0` version of `lettuce-core` is available now. I have confirmed that I can exclude command args from span tags manually via the below code snippet. In my humble opinion, this should be the default as it prevents accidental exposure of data. Would you like me to change that via PR or should users be provided a way to toggle the behavior (include / exclude) via some sort of config property?

```java
@Bean(destroyMethod = "shutdown")
public ClientResources lettuceClientResources(Tracing tracing) {
	final BraveTracing braveTracing = BraveTracing.builder().tracing(tracing).excludeCommandArgsFromSpanTags().build();
	return DefaultClientResources.builder().tracing(braveTracing).build();
}
```

**Comment by chadlwilson** [comment]
Thanks for looking at this! Would be great to get a `2.2.1.RELEASE` with this change in it :-)
