### ISSUE TITLE
The "nativeHeaders" Map modification in MessageHeaderPropagation can cause ConcurrentModificationException

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#1345]
Thanks to @artembilan :

> So, my point is to create a new map and then add a new entry as a copy of an existing one. Something like what is done in the `NativeMessageHeaderAccessor`":

```java
@SuppressWarnings("unchecked")
    @Nullable
    protected Map<String, List<String>> getNativeHeaders() {
        return (Map<String, List<String>>) getHeader(NATIVE_HEADERS);
    }

    /**
     * Return a copy of the native header values or an empty map.
     */
    public Map<String, List<String>> toNativeHeaderMap() {
        Map<String, List<String>> map = getNativeHeaders();
        return (map != null ? new LinkedMultiValueMap<>(map) : Collections.emptyMap());
    }
```

> So, we would never abuse an existing map for modification which can be shared between different messages in different threads

**Comment by artembilan** [comment]
The code we talk about is in the `MessageHeaderPropagation` and looks like:
```
private void doPut(MessageHeaderAccessor accessor, String key, String value) {
		accessor.setHeader(key, value);
		if (accessor instanceof NativeMessageHeaderAccessor) {
			NativeMessageHeaderAccessor nativeAccessor = (NativeMessageHeaderAccessor) accessor;
			ensureNativeHeadersAreMutable(nativeAccessor).setNativeHeader(key, value);
		}
		else {
			Object nativeHeaders = accessor
					.getHeader(NativeMessageHeaderAccessor.NATIVE_HEADERS);
			if (nativeHeaders == null) {
				nativeHeaders = new LinkedMultiValueMap<>();
				accessor.setHeader(NativeMessageHeaderAccessor.NATIVE_HEADERS,
						nativeHeaders);
			}
			if (nativeHeaders instanceof Map<?, ?>) {
				((Map) nativeHeaders).put(key, Collections.singletonList(value));
			}
		}
	}
```

We obtain a `nativeHeaders` `Map` from headers and modify it.

**Comment by adriancole** [comment]
by abuse we assume it is usual for messages to be written by multiple threads and have eachother clobber eachother's map object :) Not saying it is wrong, just putting it another way.

**Comment by artembilan** [comment]
> have each other clobber each other's map object 

Yes, this is really real behavior and it's OK to have it like that from the end-user perspective. We really can't control such a behavior from our side, when everything sits in the user code.
Here, on the other hand, we have an issue in the Framework, but not in the end-user code and since we can't provide a workaround for him (unless exclude tracing at all 😉 ), it would be better to make our code as thread-safe. At least from our side we can claim that our headers are immutable when we "clobber" them in the Framework.
