### ISSUE TITLE
ExceptionLoggingFilter should be disabled by default

### ISSUE THREAD

**Issue by T3rm1** [spring-cloud/spring-cloud-sleuth#1347]
I think `ExceptionLoggingFilter`should be disabled by default. You usually have your own ExceptionHandler and then need to manually disable this one. Why is it enabled by default?

**Comment by ryanjbaxter** [comment]
Can't you set the logging level to `NONE` on `ExceptionLoggingFilter`?

**Comment by T3rm1** [comment]
Yes, I can. The result is the same. My point is that you usually don't want this to be enabled and have to disable it manually through one or the other method.

**Comment by marcingrzejszczak** [comment]
You're the first person to complain about this. If there are more we will consider doing anything about this. Till then we'll close the issue.

**Comment by keithstrydom** [comment]
I'd like to second that it should be disabled by default or removed.

**Comment by MrHurniak** [comment]
Guys, I agree with keithstrydom. Image my situation: I look through logs and see the message `"Uncaught exception thrown"` with error level. When you wonder `"where this log from?"`  - you see it is that filter that just logs an exception and does any other activity. 
IMHO it is redundant.

**Comment by adriancole** [comment]
I agree with waiting for three people before adding or removing features. This feature is quite troublesome and I will happily help disable it.

**Comment by adriancole** [comment]
I'll disable in 2.2.x and remove in 3.x there's no value add whatsoever in us doing this.

**Comment by adriancole** [comment]
https://github.com/spring-cloud/spring-cloud-sleuth/pull/1633

**Comment by riching** [comment]
> I'd like to second that it should be disabled by default or removed.

I'd like to third！
