### ISSUE TITLE
Cannot log traceid and spanid

### ISSUE THREAD

**Issue by nischayreddy** [spring-cloud/spring-cloud-sleuth#1353]

**Comment by nischayreddy** [comment]
here is my POM
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.3.RELEASE</version>
		<relativePath /> 
	</parent>
	<groupId>com.adp.automationhub</groupId>
	<artifactId>solaria-api</artifactId>
	<version>19.05.20.00</version>
	<name>solaria-api</name>
	<description>Solaria Repository API implemented in spring-boot</description>

	<properties>
		<java.version>11</java.version>
		<bitbucketProject>RCF</bitbucketProject>
		<dockerImage>bpmadmin/solaria-api</dockerImage>
		<spring-cloud.version>Greenwich.RELEASE</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb</artifactId>
		</dependency>
		<dependency>
			<groupId>org.mongodb</groupId>
			<artifactId>mongo-java-driver</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>com.github.ulisesbocchio</groupId>
			<artifactId>jasypt-spring-boot-starter</artifactId>
			<version>1.18</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.retry</groupId>
			<artifactId>spring-retry</artifactId>

		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aspects</artifactId>

		</dependency>
		<dependency>
			<groupId>org.modelmapper</groupId>
			<artifactId>modelmapper</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
		</dependency>
		<dependency>
			<groupId>com.adp.automationhub</groupId>
			<artifactId>automationhub-shared-objects</artifactId>
			<version>0.0.14</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjweaver</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleauth</artifactId>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

**Comment by nischayreddy** [comment]
> here is my POM
> 
> 
> 4.0.0
> 
> org.springframework.boot
> spring-boot-starter-parent
> 2.1.3.RELEASE
> 
> 
> com.adp.automationhub
> solaria-api
> 19.05.20.00
> solaria-api
> Solaria Repository API implemented in spring-boot
> 
> ```
> <properties>
> 	<java.version>11</java.version>
> 	<bitbucketProject>RCF</bitbucketProject>
> 	<dockerImage>bpmadmin/solaria-api</dockerImage>
> 	<spring-cloud.version>Greenwich.RELEASE</spring-cloud.version>
> </properties>
> 
> <dependencies>
> 	<dependency>
> 		<groupId>org.springframework.boot</groupId>
> 		<artifactId>spring-boot-starter-actuator</artifactId>
> 	</dependency>
> 	<dependency>
> 		<groupId>org.springframework.boot</groupId>
> 		<artifactId>spring-boot-starter-data-mongodb</artifactId>
> 	</dependency>
> 	<dependency>
> 		<groupId>org.mongodb</groupId>
> 		<artifactId>mongo-java-driver</artifactId>
> 	</dependency>
> 	<dependency>
> 		<groupId>org.springframework.boot</groupId>
> 		<artifactId>spring-boot-starter-web</artifactId>
> 	</dependency>
> 
> 	<dependency>
> 		<groupId>org.springframework.boot</groupId>
> 		<artifactId>spring-boot-starter-test</artifactId>
> 		<scope>test</scope>
> 	</dependency>
> 	<dependency>
> 		<groupId>io.springfox</groupId>
> 		<artifactId>springfox-swagger2</artifactId>
> 		<version>2.9.2</version>
> 	</dependency>
> 	<dependency>
> 		<groupId>io.springfox</groupId>
> 		<artifactId>springfox-swagger-ui</artifactId>
> 		<version>2.9.2</version>
> 	</dependency>
> 	<dependency>
> 		<groupId>com.github.ulisesbocchio</groupId>
> 		<artifactId>jasypt-spring-boot-starter</artifactId>
> 		<version>1.18</version>
> 	</dependency>
> 	<dependency>
> 		<groupId>org.springframework.retry</groupId>
> 		<artifactId>spring-retry</artifactId>
> 
> 	</dependency>
> 	<dependency>
> 		<groupId>org.springframework</groupId>
> 		<artifactId>spring-aspects</artifactId>
> 
> 	</dependency>
> 	<dependency>
> 		<groupId>org.modelmapper</groupId>
> 		<artifactId>modelmapper</artifactId>
> 		<version>2.3.0</version>
> 	</dependency>
> 	<dependency>
> 		<groupId>com.fasterxml.jackson.core</groupId>
> 		<artifactId>jackson-databind</artifactId>
> 	</dependency>
> 	<dependency>
> 		<groupId>org.springframework.boot</groupId>
> 		<artifactId>spring-boot-starter-security</artifactId>
> 	</dependency>
> 	<dependency>
> 		<groupId>commons-codec</groupId>
> 		<artifactId>commons-codec</artifactId>
> 	</dependency>
> 	<dependency>
> 		<groupId>com.adp.automationhub</groupId>
> 		<artifactId>automationhub-shared-objects</artifactId>
> 		<version>0.0.14</version>
> 	</dependency>
> 	<dependency>
> 		<groupId>org.springframework</groupId>
> 		<artifactId>spring-aop</artifactId>
> 	</dependency>
> 	<dependency>
> 		<groupId>org.aspectj</groupId>
> 		<artifactId>aspectjweaver</artifactId>
> 	</dependency>
> 	<dependency>
> 		<groupId>org.springframework.boot</groupId>
> 		<artifactId>spring-boot-starter-aop</artifactId>
> 	</dependency>
> 	<dependency>
> 		<groupId>org.springframework.cloud</groupId>
> 		<artifactId>spring-cloud-starter-config</artifactId>
> 	</dependency>
> 	<dependency>
> 		<groupId>org.springframework.cloud</groupId>
> 		<artifactId>spring-cloud-starter-sleauth</artifactId>
> 	</dependency>
> </dependencies>
> <dependencyManagement>
> 	<dependencies>
> 		<dependency>
> 			<groupId>org.springframework.cloud</groupId>
> 			<artifactId>spring-cloud-dependencies</artifactId>
> 			<version>${spring-cloud.version}</version>
> 			<type>pom</type>
> 			<scope>import</scope>
> 		</dependency>
> 	</dependencies>
> </dependencyManagement>
> <build>
> 	<plugins>
> 		<plugin>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-maven-plugin</artifactId>
> 		</plugin>
> 	</plugins>
> </build>
> ```

![image](https://user-images.githubusercontent.com/35205065/57791975-f9c08480-770b-11e9-9aae-9ada2f911f10.png)

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by marcingrzejszczak** [comment]
Please learn how to [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by nischayreddy** [comment]
Okay thanks.
So here is my problem I added sleuth dependency in my POM and I also have cloud config which is sitting in the same POM file. 

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
		</dependency>
```

Sleuth and config dependency management.
```
<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-sleuth</artifactId>
				<version>${sleuth.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```
Versions for spring-cloud and sleuth.
```
<spring-cloud.version>Greenwich.RELEASE</spring-cloud.version>
<sleuth.version>2.1.0.RELEASE</sleuth.version>

```

My spring boot version is 
```
<version>2.1.3.RELEASE</version>
```

When I run locally and made a request to get some data after adding sleuth I was expecting to see traceId and SpanId, but the behaviour is not as expected I don't see any log.

**Comment by spencergibb** [comment]
> Can you provide a complete, minimal, verifiable sample that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.
