### ISSUE TITLE
Why Spring Cloud Sleuth Do Not Trace Spring Cloud Stream Consumer Endpoint

### ISSUE THREAD

**Issue by glmapper** [spring-cloud/spring-cloud-sleuth#1355]
Spring cloud stream is tracked using spring cloud sleuth and the data is reported to zipkin. As you can see from the zipkin dependency graph, there is no consumer.

![image](https://user-images.githubusercontent.com/35319286/57918909-4baf0900-78ca-11e9-9896-85845f2ec534.png)

The Json Span : 

```java
[
  {
    "traceId": "e2d09ac09f8ddec1",
    "parentId": "4039c7f9066909b3",
    "id": "67ef75a55a9c6663",
    "kind": "PRODUCER",
    "name": "send",
    "timestamp": 1558082376657153,
    "duration": 255,
    "localEndpoint": {
      "serviceName": "default",
      "ipv4": "10.15.232.132"
    },
    "remoteEndpoint": {
      "serviceName": "broker"
    },
    "tags": {
      "channel": "testInPut"
    }
  },
  {
    "traceId": "e2d09ac09f8ddec1",
    "parentId": "e2d09ac09f8ddec1",
    "id": "4039c7f9066909b3",
    "kind": "PRODUCER",
    "name": "send",
    "timestamp": 1558076935671302,
    "duration": 5441142379,
    "localEndpoint": {
      "serviceName": "default",
      "ipv4": "10.15.232.132"
    },
    "remoteEndpoint": {
      "serviceName": "broker"
    },
    "tags": {
      "channel": "testOutPut"
    }
  },
  {
    "traceId": "e2d09ac09f8ddec1",
    "id": "e2d09ac09f8ddec1",
    "kind": "SERVER",
    "name": "get /testmq",
    "timestamp": 1558076935670151,
    "duration": 5441149204,
    "localEndpoint": {
      "serviceName": "default",
      "ipv4": "10.15.232.132"
    },
    "remoteEndpoint": {
      "ipv6": "::1",
      "port": 65147
    },
    "tags": {
      "http.method": "GET",
      "http.path": "/testMq",
      "mvc.controller.class": "Controller",
      "mvc.controller.method": "testMq"
    }
  }
]
```

By analyzing the TracingChannelInterceptor, it is found that the Channel used in the Spring Cloud Stream is a SubscribableChannel, and the preReceptive(), postReceive() and afterReceiveCompletion() methods of the ChannelInterceptor will only be intercepted when the Channel is a PollableChannel.

**Comment by marcingrzejszczak** [comment]
Which version of sleuth are you using

**Comment by glmapper** [comment]
> Which version of sleuth are you using

* SpringBoot 2.1.5.RELEASE
* spring-cloud Greenwich.SR1
* spring-cloud-sleuth 2.1.1.RELEASE

**Comment by marcingrzejszczak** [comment]
Can you please create a small sample that replicates the problem?

**Comment by glmapper** [comment]
> Can you please create a small sample that replicates the problem?

[glmapper-spring-cloud-samples](https://github.com/glmapper/glmapper-spring-cloud-samples)

**Comment by glmapper** [comment]
You need to replace the server addresses inside, such as Kafka and Zipkin

**Comment by glmapper** [comment]
@marcingrzejszczak Hi, do you have a conclusion about this question?

**Comment by marcingrzejszczak** [comment]
I don't. I didn't have time to debug this.

**Comment by marcingrzejszczak** [comment]
Is this still an issue with the latest version?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
