### ISSUE TITLE
Use custom request header to be used as Trace-Id

### ISSUE THREAD

**Issue by samyakmehta** [spring-cloud/spring-cloud-sleuth#1357]
I am using sleuth version 2.0.1

Does it have a provision which can help me convert a custom request header, say 'x-correlation-id' to 'X-B3-SpanId'. I am able to log 'X-B3-SpanId' headers but I want the callers of my REST API to be able to send me trace-id as 'x-correlation-id'?

I tried to achieve this by injecting a filter as a bean which reads "x-correlation-id" and populates "X-B3-TraceId" in the request context. I have set the filter order to "TraceWebServletAutoConfiguration.TRACING_FILTER_ORDER - 1" assuming that Sleuth will pick up the "X-B3-TraceId" post it.

But it does not seem to work. Am I missing something?

**Comment by marcingrzejszczak** [comment]
Much better idea will be to just leave setting of ids to Brave in the way it's done ATM and use the `propagation-keys` to move propagate your ID 

```yaml
spring:
  sleuth:
    propagation-keys: x-correlation-id
```

That way you'll have the ID propagated in your system. The only thing you need to change is essentially add a property instead of changing any code.

**Comment by samyakmehta** [comment]
Thanks for the response! Does this solution support logging the custom header out of the box?
I implemented your suggestion and updated the logback-spring,xml to contain correlation id by adding **CorrelationId: %X{x-correlation-id:-}]** to the pattern.

This does not seem to work if I pass "x-correlation-id" header to the Rest API.

**Comment by marcingrzejszczak** [comment]
Please read the docs https://cloud.spring.io/spring-cloud-static/Greenwich.SR1/single/spring-cloud.html#prefixed-fields
