### ISSUE TITLE
The request headers order has changed

### ISSUE THREAD

**Issue by verichenn** [spring-cloud/spring-cloud-sleuth#1359]
`SERVICE-A` and `SERVICE-B` two applications, through `postman` to initiate a `Content-Type: text/plain` request to `SERVICE-A`, `SERVICE-B` through `FeignClient` request to `SERVICE-B`, `SERVICE-B` Consumption`Content-Type : application/json` request, when not added to the `Sleuth` dependency, the processing succeeds, and when adding the `Sleuth` dependency, throw `HttpMediaTypeNotSupportedException` exception.

---
`SERVICE-A`

```java
@PostMapping("/a/feign")
public Map feign(@RequestHeader("Content-Type") String contentType) {
    Map<String, Object> map = new HashMap<>();
    map.put("original-content-type", contentType);
    return feignClient.helloWorld(map);
}
```

```java
@FeignClient("sleuth-feign-demo")
public interface MyFeignClient {

    @PostMapping("/b/feign")
    Map helloWorld(@RequestBody Map<String, Object> map);
}
```

`SERVICE-B`

```java
@PostMapping("/b/feign")
public Map hello(@RequestBody Map<String,Object> map){
    Map<String, Object> result = new HashMap<>(map);
    result.put("service","Service-B");
    return result;
}
```
---
By breakpoint finds the `org.springframework.cloud.sleuth.instrument.web.client.feign.TracingFeignClient#execute` method to saved the request header in the `HashMap` (originally saved in the `LinkedHashMap`) when adding the trace header.Caused the header order to be disrupted.For example, the original `Content-Type` is in front of `content-type`, but finally becomes `Content-Type` behind `content-type`.So,Perhaps this should be changed to `LindedHashMap`.

```java
@Override public Response execute(Request request, Request.Options options)
			throws IOException {
   Map<String, Collection<String>> headers = new HashMap<>(request.headers());
   ...
}
```
---
You can also read [this article](https://github.com/verichenn/my_notes/blob/master/others/sleuth-issue.md), but it is written in Chinese.

**Comment by marcingrzejszczak** [comment]
Why does the header order matter to you?

**Comment by verichenn** [comment]
Because in the above example, the headers of the original request was passed by `RequestInterceptor`, but the `content-type` was not filtered, causing `text/palin` and `application/json` to be the value of the request header `content-type`. I wanted to get `application/json`, but after the order changed, I got `text/palin`.

**Comment by marcingrzejszczak** [comment]
I see. Care for a PR?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
