### ISSUE TITLE
sleuth trace not working with Kstream

### ISSUE THREAD

**Issue by t0il3ts0ap** [spring-cloud/spring-cloud-sleuth#1363]
I have a stream processor written using `spring-cloud-stream-binder-kafka-streams`
```
@Slf4j
@EnableBinding(KafkaStreamsProcessor.class)
@RequiredArgsConstructor
@Component
public class SomeWorker extends BaseStream<SomePojo> {

    @StreamListener(Sink.INPUT)
    @SendTo(Source.OUTPUT)
    public KStream<?, SomePojo> process(KStream<?, SomePojo> pojoObj) {
                     //stream processing
}
```

pom.xml 
` <spring-cloud.version>Greenwich.SR1</spring-cloud.version>`
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka-streams</artifactId>
        </dependency>
```

properties
```
#kafka stream properties
spring.cloud.stream.kafka.binder.brokers=localhost
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=1000
spring.cloud.stream.kafka.streams.binder.configuration.default.key.serde=org.springframework.kafka.support.serializer.JsonSerde
spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde=org.springframework.kafka.support.serializer.JsonSerde
spring.cloud.stream.bindings.input.contentType=application/json
spring.cloud.stream.bindings.output.contentType=application/json
spring.cloud.stream.kafka.streams.bindings.input.consumer.application-id=dedup-metric-worker
spring.cloud.stream.bindings.input.destination=split-metrics3
spring.cloud.stream.bindings.output.destination=cleaned-metrics9

```

Sleuth trace keys in MDC(`X-B3-TraceId, X-B3-SpanId`) are missing when logging. 
Is Kstream supported by sleuth? (the main feature of kafka streams)

**Comment by adriancole** [comment]
not sure the tie-in with spring-cloud-stream, but work at the kstreams layer of abstraction exists cc @jeqo https://github.com/apache/incubator-zipkin-brave/tree/master/instrumentation/kafka-streams

**Comment by jeqo** [comment]
Yes, we had a similar issue solved with spring-kafka-streams, which once released will offer `TracingKafkaClientSupplier` to enable tracing on Kafka Streams: https://github.com/apache/incubator-zipkin-brave/issues/886
Not sure if in `spring-cloud-stream-binder-kafka-streams` KafkaClientSupplier can be injected similarly.

**Comment by t0il3ts0ap** [comment]
Ohh I see, there is one more kafka stream implementation with spring, provided by [spring-kafka ](https://github.com/spring-projects/spring-kafka/blob/master/src/reference/asciidoc/streams.adoc) directly. Since, I am working on a new project I can migrate to it.
I wonder why stream implementation is supported by both spring-kafka and spring-cloud-stream.

**Comment by marcingrzejszczak** [comment]
Becaue those are different abstractions. Via instrumenting Spring Integration we will have plenty of SI components working out of the box. Spring Cloud Stream uses Spring Integration so we got that for free so to speak. Spring Kafka directly has nothing to do with Spring Integration.

**Comment by garyrussell** [comment]
Yes, I think it would need hooks in the spring-cloud-stream Kafka Streams binder.

The binder builds the "start" and "end" of the KStream, with the app dev providing the "middle" of the stream topology.

The binder would need to provide a hook to allow the insertion of the processor/transformer at the appropriate points.

/cc: @sobychacko @sabbyanandan

**Comment by timtebeek** [comment]
@t0il3ts0ap for the spring-kafka instrumentation of Kafka Streams there's a start in https://github.com/spring-cloud/spring-cloud-sleuth/pull/1365
At present that also lacks the log correlation, so migrating to that got your project would not help you much yet I suppose. But perhaps support can be expanded either way, as neither option right now seems to have to correlation.

**Comment by timtebeek** [comment]
@t0il3ts0ap not sure how to interpret the :confused: reaction on my above comment; You asked about log correlation with Kafka Streams; at present there's two implementation for Spring + Kafka:
1. `spring-cloud-stream-binder-kafka-streams`, which you're using in your examples
2. `spring-kafka`, which uses `@EnableKafkaStreams` to bootstrap & support the StreamsBuilder DSL

As you've found, approach 1 above, currently does not output your Span correlation IDs on any logged messages. Gary Russel above has suggested some hooks to work around that, and that might be a valuable route to pursue.

Above [you mentioned possibly migrating to spring-kafka](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1363#issuecomment-499815324) (approach 2 above). That at present currently also lacks log correlation out of the box. Now Jorge Otoya has done some work recently to enable Trace forwarding and log correlation with an explicit `KafkaStreamsTracing` wrapper in `brave-instrumentation-kafka-streams`.

For my part; I'm taking the wrapper created by Jorge, and adding auto configuration for that in Sleuth https://github.com/spring-cloud/spring-cloud-sleuth/pull/1365. Add that configuration class on your classpath, and invoke the wrapper with something like:
```java
kstream.transform(kafkaStreamsTracing.peek("my-named-span", (k, v) -> LOGGER.info("This message will have log correlation IDs; key: {}, value: {}", k, v)));
```
That will give your logged message Sleuth Trace/Span correlation IDs in the log output!

There's more operations you can wrap, and an ongoing discussion to follow on whether this should be part of Sleuth, but this should at least get you going. Hope it helps!

**Comment by t0il3ts0ap** [comment]
@timtebeek I looked at your pr, and implemented same changes in mine as the given milestone will take time to release. But still did not see any span headers coming in for streams.
```
  <dependency>
        <groupId>io.zipkin.brave</groupId>
        <artifactId>brave-instrumentation-kafka-streams</artifactId>
        <version>5.6.5</version>
  </dependency>
```
```
@Configuration
public class DedupMetricWorkerStreamConfig {

    @Bean
    public KafkaStreamsTracing kafkaStreamsTracer(@Autowired Tracing tracing) {
        return KafkaStreamsTracing.create(tracing);
    }

    @Bean
    public StreamsBuilderFactoryBean privateStreamBuilder(
        @Autowired KafkaProperties kafkaProperties,
        @Autowired KafkaStreamsTracing kafkaStreamsTracing) {

        KafkaStreamsConfiguration streamsConfiguration = configureStream(kafkaProperties.buildStreamsProperties());
        StreamsBuilderFactoryBean streamsBuilderFactoryBean = new StreamsBuilderFactoryBean(streamsConfiguration);
        streamsBuilderFactoryBean.setClientSupplier(kafkaStreamsTracing.kafkaClientSupplier());
        return  streamsBuilderFactoryBean;
    }
}
```

Then I use above StreamsBuilderFactoryBean. Normal processing is working fine, just request headers are not visible in stream logs, but they are visible everywhere else.
```
    @Autowired
    public KStream<?, ?> process(StreamsBuilder privateStreamBuilder) {
        //stream processing
    }
```

**Comment by timtebeek** [comment]
Can you tell me if you're using anything like `kstream.transform(kafkaStreamsTracing.peek("my-named-span", (k, v) -> LOGGER.info("This message will have log correlation IDs; key: {}, value: {}", k, v)));` in your `public KStream<?, ?> process(StreamsBuilder privateStreamBuilder) { ... }` method? I provided a hint in my previous message, that you'll need that for the correlation IDs to show up in the logs. It's not ideal, but at least you (already) get propagation, new spans, and the option to get correlation IDs in the logs when using that method chain.

If you are already using that `transform/peek` combination, I'd need a bit more details on what operations you're doing in your `process` function. If you look into the `KafkaStreamsTracing` sources, you'll find some operations need additional wrappers that are not yet instrumented out of the box.

**Comment by t0il3ts0ap** [comment]
Ohh my bad, I did not use `transform` with it. But then I have to use transform with all `map/peek/filter`. 
I was under impression, `brave's kafkaClientSupplier` would take care of it.

**Comment by timtebeek** [comment]
That's the unfortunate reality until more extensive instrumentation for Kafka Streams itself is implemented, or the new hooks in spring-cloud-stream mentioned above. If/Once I find time to apply this at work I'll actively be looking into contributing more extensive instrumentation out of the box.

**Comment by timtebeek** [comment]
This issue has been closed; presumably because @t0il3ts0ap has found a way around his issues with spring-cloud-stream Kafka binders by switching to spring-kafka + Kafka Streams.

Should a tracking issue be created / prioritized with regards to the binder hooks that allow for the insertion of the processor/transformer in spring-cloud-stream, as suggested by @garyrussell ?

Future developers stumbling upon this thread might incorrectly assume it's resolved if this issue has been closed.

**Comment by marcingrzejszczak** [comment]
I think once the hooks are there we can reopen this one. BTW with Brave you can work with Kafka Streams already - https://github.com/openzipkin/brave/blob/master/instrumentation/kafka-streams/README.md. Of course once the hooks are there we can automate the instrumentation setup.

**Comment by t0il3ts0ap** [comment]
I closed the issue as stream instrumentation is possible using spring-kafka though not fully automated yet. Please reopen if necessary.

**Concluding the summary of issue**: 
If you are using 
A) _**kafka streams via spring-cloud-stream**_
Instrumentation is not possible until binders hooks that allow insertion of processor/transformer are supported.

B)_**kafka streams via spring-kafka**_
Polling instrumentation will start happening automatically ( visible on zipkin dashboard ) once [milestone 2.2.0.M1](https://github.com/spring-cloud/spring-cloud-sleuth/milestone/57)  is released. 
Yet the logs wont have tracer id unless `transform/peek or other fns` combination ( as described above) is used manually.

**Comment by garyrussell** [comment]
I opened an issue against the binder; link above.

**Comment by timtebeek** [comment]
@sobychacko Thanks for chiming in here as well! Haven't used spring cloud stream myself yet, although the new functional approach you've linked seems promising. I'll reconsider adding it for my next project/service.

Good to head spring-cloud/spring-cloud-sleuth#1365 also benefits Spring Cloud Stream. Although it would be nice if spring-cloud/spring-cloud-stream-binder-kafka#699 would provide some hooks to make the instrumentation more implicit, as ideally users would not need to call `kafkaStreamsTracing.transformer` themselves, with sufficiently advanced auto configured instrumentation.

**Comment by sobychacko** [comment]
@timtebeek Thanks for the feedback. I guess for the time being we will leave the binder with the explicit options mentioned above for instrumentation. I know it is not ideal, but the more implicit strategy requires a bit more effort and I am afraid it may not fit with our current timeline for Spring Cloud Stream `Horsham` release. Therefore, I leave the [issue in the binder ](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/699) open and moved to the backlog. Contributions there are welcomed though:-)

**Comment by jankosecki** [comment]
> B)_**kafka streams via spring-kafka**_
> Polling instrumentation will start happening automatically ( visible on zipkin dashboard ) once [milestone 2.2.0.M1](https://github.com/spring-cloud/spring-cloud-sleuth/milestone/57) is released.
> Yet the logs wont have tracer id unless `transform/peek or other fns` combination ( as described above) is used manually.

@timtebeek 
Hi, has anything changed in regard to trace id in method processing spring kafka stream?
I managed to display trace id in logs using `KafkaStreamsTracing#peek` method, however my stream ends to `toTopic` method, which also outputs some data to the logs. Is it possible to provide traceId in the context of `toTopic` method?

**Comment by timtebeek** [comment]
Hi @jankosecki What are you referring to with `toTopic`? Have not used that before.. My most recent example is located here: https://github.com/timtebeek/kafka-streams-log-correlation , which I've documented here: https://blog.jdriven.com/2019/10/distributed-tracing-with-kafka-streams/
Does any of that help? I'm also using `peek` to have the trace/span show up in the logs. Propagation is already handled by Sleuth.

**Comment by jankosecki** [comment]
Hi @timtebeek sorry, I got a bit distracted while writing the question and wrote wrong name of the method, I meant `KStream#to`.
To be exact, my method that initializes the KStream looks following:
```
   KafkaStreamsTracing streamsTracing = KafkaStreamsTracing.create(tracing);

   streamsBuilder.<String, Message>stream(topics)
        .transformValues(streamsTracing.peek("peek",
            (key, value) -> LOGGER.info("Received new kafka message [{}] {}", key, value)))
        .filter((key, value) -> SUPPORTED_MESSAGE_TYPES.contains(value.getMessageType()))
        .mapValues(message -> (FooMessage) message)
        ...
        .map(eventMapper::map)
        .transformValues(NotificationIdValueTransformer::new)
        .to(KafkaNotificationsStream::toTopic, Produced.valueSerde(new MessageSerde()));
```
Earlier before, I was using simply `peek` method but never observed trace in logs - the same applies to logging that happens inside `KafkaNotificationsStream::toTopic` method.

I'm gonna have a look tomorrow at your example and doc - thank you for providing them. 

I assume that I did something wrong in my configuration and hence traces are not propagated in my  methods.

**Comment by timtebeek** [comment]
No problem at all! At first glance what strikes me as odd is that you seem
to be creating your own instance of KafkaStreamsTracing. You should be able
to just Autowire the instance that sleuth auto configuration with spring
boot creates for you.

**Comment by jankosecki** [comment]
Hi @timtebeek 
I've read your post on https://blog.jdriven.com/2019/10/distributed-tracing-with-kafka-streams/ and there you also confirm that:
> Finally, we want to demonstrate that the trace context information is only available when using the explicit instrumentation. For that, we add a third log statement to the odd numbers stream that uses a regular old KStream#peek.

Does it mean there is no way to propagate trace MDS to a log crated inside `KStream#to` method? The topic in this method is calculated dynamically based on the content of the message hence the logging inside `TopicExctractor` method - it would be great if there was any way to provide trace there, right now the log line is 
```
2019-12-20 09:35:43.227 DEBUG [notification-service,,,] 60970 --- [-StreamThread-1] i.i.n.c.kafka.KafkaStreamsConfig         : Writing [test_callback]BaseMessage{}
```

**Comment by timtebeek** [comment]
@jankosecki Had not seen that `TopicNameExtractor` used before; at first glance it does indeed seem as though there's no support for that operation in `KafkaStreamsTracing` yet. You might want to ask @jeqo about that over in https://github.com/openzipkin/brave, since the class originates there.

In similar cases I had up to now been using `KafkaStreamBrancher` to switch messages between topics, given that I had fairly modest needs. You can then peek on any KStream that you produce, so it might be worth considering for your needs.

However, it does seem like we're slowly moving away from what this issue was about; Perhaps it's best to continue any further questions on a forum like Stackoverflow. As much as I like to help any way I can, there's no need to loop in everyone else on this thread.
