### ISSUE TITLE
How to switch off the new span creation in TracingProducer

### ISSUE THREAD

**Issue by ternovoy** [spring-cloud/spring-cloud-sleuth#1364]
Question:
Details: 'spring-cloud-starter-sleuth', version: '2.1.1.RELEASE'

Our application sends records to and then consumes them from Kafka.

The issue we face is how to correlate a sent record with a consumed record,
since their correnspoing spandId and parentId do not match.

Our short investigation shows that both TracingProducer and TracingConsumer create new spans,
but because we don't see the records in transit, we are missing the link between last oberseved
spanId on the producing side and the spanId on the consuming side.

The question is how to switch off the new span creation in TracingProducer?

**Comment by marcingrzejszczak** [comment]
Set `spring.sleuth.messaging.kafka.enabled` to `false`

**Comment by ternovoy** [comment]
Sorry @marcingrzejszczak, I think you misunderstood my question.
If I set `spring.sleuth.messaging.kafka.enabled` to `false` then neither TraceId nor SpanId will be added to incoming Kafka messages. But my question was about configuring Sleuth to save the original SpanId.

**Comment by marcingrzejszczak** [comment]
`TracingProducer` always creates a new span because it's sending a span to the broker. There's no way to toggle it off. You can of course disable the Kafka tracing as I mentioned and introduce your own way of instrumenting Kafka producer.

**Comment by ternovoy** [comment]
Thank you for the answer.
