### ISSUE TITLE
Enhancement: jaeger UDP support

### ISSUE THREAD

**Issue by pstitt** [spring-cloud/spring-cloud-sleuth#1366]
I have a spring sleuth app running locally that sends traces to jaeger using the zipkin http collector. However, we are running our apps in kubernetes with jaeger-agent sidecars. As far as I can tell, the jaeger agent does not support the http zipkin collector so there seems to be no way to use sleuth to send traces to jaeger agents. 

We can use spring-jaeger-cloud-starter to achieve this but then we lose the trace ids in our logs. 

I propose a new spring-cloud-sleuth-jaeger adapter that supports the UDP protocol. Unless there is another option I have overlooked. 

Thanks.

**Comment by adriancole** [comment]
things like this end up in different repos. Closest to what you are asking for is the X-Ray UDP reporter

https://github.com/openzipkin/zipkin-aws/tree/master/reporter-xray-udp

There are at least 6 other non-stock reporters in various repos, for different backends or transports.

**Comment by adriancole** [comment]
PS if someone is feeling advanced, they could also implement this as a
Brave FinishedSpanHandler, too.

Just the zipkin.reporter option is a bit more understood, and can be used
in different libraries vs Brave.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
