### ISSUE TITLE
Switch to slf4j instead of commons-logging

### ISSUE THREAD

**Issue by balamaci** [spring-cloud/spring-cloud-sleuth#1367]
Enhancement

Remove dependency on commons-logging and use slf4j instead. We have a spring boot application that now outputs uncaught exceptions to console, because the ExceptionLoggingFilter https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/ExceptionLoggingFilter.java is logging uncaught exceptions to a commons-logging Log.
We can circumvent commons-logging, but why use it in the first place?

**Comment by spencergibb** [comment]
Spring Framework standardized on commons logging a long time ago

**Comment by balamaci** [comment]
Hi, you are right but I think we only have a problem with ExceptionLoggingFilter.java because the actual Log class in provided by another jar spring-jcl https://github.com/spring-projects/spring-framework/tree/master/spring-jcl/src/main/java/org/apache/commons/logging which delegates to SLF4J while Sleuth is actually using the "true" apache commons https://github.com/spring-cloud/spring-cloud-sleuth/blob/4fcd0d59504640a94b405c7b7720794b5aed94ff/pom.xml#L219

**Comment by marcingrzejszczak** [comment]
I don't understand the problem. What would you like us do for that matter?

**Comment by balamaci** [comment]
Hi, I let it open as to me it makes sense to rather reference spring-jcl instead of commons-logging in the pom.xml. 
Since projects using spring cloud already have spring modules, bringing commons-logging as a transient dependency besides spring-jcl might cause not so evident problems.
If you don't think it's worth it, the issue can be closed from my perspective.
Thanks!
