### ISSUE TITLE
spring.zipkin.base-url/hostname with underscore

### ISSUE THREAD

**Issue by aromansmc** [spring-cloud/spring-cloud-sleuth#1372]
Bug report

Using spring cloud v2.1.1. If the hostname in the base-url contains an underscore, the hostname gets stripped out at some point during the configuration process.

With trace turned on org.springframework.cloud.sleuth, io.zipkin

application.yml:
  zipkin:
    enabled: true
    base-url: http://jhipster_zipkin:9411/

produces:

[AsyncReporter{org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender@23336187}] o.s.c.s.z.s.ZipkinRestTemplateWrapper    : HTTP POST http:/api/v2/spans

application.yml:
  zipkin:
    enabled: true
    base-url: http://jhipster-zipkin:9411/

produces:

[AsyncReporter{org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender@3277e499}] o.s.c.s.z.s.ZipkinRestTemplateWrapper    : HTTP POST http://jhipster-zipkin:9411/api/v2/spans

**Comment by devinsba** [comment]
I'm guessing that is because `_` is an illegal character in the hostname portion of a URL and that there is some validation happening somewhere in the `RestTemplate`/client layer

**Comment by aromansmc** [comment]
I would suggest that an exception be thrown when trying to submit to the zipkin server and failing. That was the behavior in previous versions of spring cloud. It seems that the hostname/_ issue is controversial internet topic because DNS allows it but its frowned upon to use. In this case I was using docker, which was just converting container names to DNS names.

**Comment by marcingrzejszczak** [comment]
You can't use underscores in the hostnames. We're reusing current load balancing tools and they don't support it.
