### ISSUE TITLE
Spring Cloud Sleuth GCP: every time spans are sent, they are sent to localhost as well

### ISSUE THREAD

**Issue by bbzg** [spring-cloud/spring-cloud-sleuth#1377]
There should be a way to turn off the default ZipkinRestTemplateSenderConfiguration when using Spring Cloud GCP. I would prefer if it was turned off by default.

Currently, every time spans are being sent, a completely unnecessary call to `http://localhost:9411/api/v2/spans`, and it fails 100% of the time because there is nothing there to answer.

The only reason I saw it was because I used `logging.level.org.springframework.cloud=TRACE`.

I tried to fix it by setting `spring.zipkin.enabled=false` but it crashes on startup because of `ZipkinBackwardsCompatibilityAutoConfiguration`.

If there already is a way to turn this off I would be very happy. Anyway my opinion is it should be off by default because I have already chosen `spring.cloud.gcp.trace.enabled=true`.

Thanks.

**Comment by marcingrzejszczak** [comment]
Shouldn't it get fixed in Spring Cloud GCP?

**Comment by bbzg** [comment]
Sorry, it probably should... I will post it there instead
