### ISSUE TITLE
Sampler should accept a Span a a method parameter

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#138]
The implementation of `PercentageBasedSampler` shows us the flaw: you need a `Span` to compute the sample rate, but the sampler is needed to create a `DefaultTracer`, and you can't start a span without a `Tracer`.

**Comment by marcingrzejszczak** [comment]
This particular implementation needs a `Span`. Maybe some other samplers would profit from other approaches and wouldn't necessary need a `Span` ?

**Comment by dsyer** [comment]
There is always in principle a `Span` available when you ask a `Sampler` for a decision. I see no harm in adding it to the parameters.

**Comment by marcingrzejszczak** [comment]
Me neither - just saying...

**Comment by dsyer** [comment]
Whereas it is actively harmful not to add it (because then there is no way to create a `DefaultTracer` with a `PercentageBasedSampler`).

**Comment by marcingrzejszczak** [comment]
That's a very good argument for doing that ;)
