### ISSUE TITLE
WebClientTracerSubscriber.terminateSpan() throws IllegalArgumentException for non-standard status code

### ISSUE THREAD

**Issue by blake-bauman** [spring-cloud/spring-cloud-sleuth#1382]
When using Spring Cloud Sleuth with a WebClient call, and the downstream service responds with a non-standard HTTP code (say 499), then WebClientTracerSubscriber.terminateSpan() throws an IllegalArgumentException because the status code cannot be mapped to one of the HttpStatus enum values.

The offending code is here:

```java
    void terminateSpan(@Nullable ClientResponse clientResponse,
                       @Nullable Throwable throwable) {
        if (clientResponse == null || clientResponse.statusCode() == null) {
```

From the Javadoc, ClientResponse.statusCode() will never return null, but will instead throw an IllegalArgumentException.  As suggested by https://github.com/spring-projects/spring-framework/issues/21289 clientResponse.getRawStatusCode() should be used if there's a possibility of a non-standard response code.  Our app will call something like:

```java
        webClient.get()
                 .uri(...)
                 .exchange()
                 .flatMap(response -> {
                     if (response.getRawStatusCode() == ...)
                         ...
                 })
```

However, this response handler never gets control because of the exception thrown when `terminateSpan()` calls `clientResponse.statusCode()`.  When we remove spring-cloud-sleuth, it works fine, but since we would like the OpenTracing support, we still want to use sleuth.

**Comment by blake-bauman** [comment]
We are using the Greenwich.SR1 release train.

**Comment by marcingrzejszczak** [comment]
Hi @blake-bauman ! Are you interested in filing a PR with a failing test and the impl that fixes it?

**Comment by blake-bauman** [comment]
I wish, but at the moment, the Legal department at my company hasn't approved me for public open source code contributions.  I'm going through the vetting process, but that can take months.  I'm working on a simple project that demonstrates this.

Browsing through the code, however, it does appear that the problem is localized to this null check, the `error` validation, and the reason phrase in the exception.  walking through handleReceive(), that part appears to be ok.

**Comment by adriancole** [comment]
ok so the fix for who can do this would be to try/catch and coerce IAE to
null here, with a mock test with some invalid status from the server.. who
knows, maybe 0?

https://github.com/spring-cloud/spring-cloud-sleuth/blob/65ea711671b00dff591477f881bddbec3b13a287/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientBeanPostProcessor.java#L400-L402

**Comment by marcingrzejszczak** [comment]
Maybe they should be a part of Brave's API? Like statusCodeOrZero()?

**Comment by adriancole** [comment]
yeah this current code overrides statusCode, but better to override statusCodeAsInt instead. in any case catch the exception :P

**Comment by adriancole** [comment]
actually it can also throw IOE heh https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/client/ClientHttpResponse.java#L46-L55

so something like 

```java
  @Override public int statusCodeAsInt(ClientHttpResponse response) {
    try {
      return response.getRawStatusCode();
    } catch (IOException | IllegalArgumentException dontCare) {
      return 0;
    }
  }
```

**Comment by blake-bauman** [comment]
I don't think this is going to solve the reported problem.  It may solve *some* problem, but not the reported one.  Unless terminateSpan() stops calling ClientResponse.getStatusCode(), the original problem will persist.

Btw, getRawStatusCode() won't throw an exception.  It's getStatusCode() that'll throw it.

**Comment by marcingrzejszczak** [comment]
Now it should be better with https://github.com/spring-cloud/spring-cloud-sleuth/commit/39d5e00e2db4ecd7c26f43c7463a8fcf25ce47ab

**Comment by blake-bauman** [comment]
Which snapshot will this be?  2.2.0.BUILD-SNAPSHOT?

**Comment by blake-bauman** [comment]
Using 2.2.0-BUILD-SNAPSHOT, issue seems to have moved to a different location.  Should I open a new Issue to continue discussion?  I have a sample project that demonstrates the issue.

**Comment by marcingrzejszczak** [comment]
Please do.
