### ISSUE TITLE
Add brave bom file to spring-cloud-sleuth-dependencies 

### ISSUE THREAD

**Issue by kurtharriger** [spring-cloud/spring-cloud-sleuth#1384]
We have a transitive dependency on org.springframework.cloud:spring-cloud-sleuth-dependencies via org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR2 which imports the [spring-cloud-sleuth-dependencies](https://github.com/spring-cloud/spring-cloud-release/blob/master/spring-cloud-dependencies/pom.xml#L97)

We also use io.zipkin.reporter2:zipkin-sender-urlconnection and the version brave expects is listed in the [brave bom](https://github.com/openzipkin/brave/blob/master/brave-bom/pom.xml#L33)

However, spring sleuth imports brave bom file via the [root pom](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/pom.xml#L181) not via [spring-cloud-sleuth-dependencies](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-dependencies/pom.xml) and thus the brave bom file is not transitively included in our project forcing us to specify the desired version of the dependency and/or reimport the brave bom file into our our pom file. 

This caused issues for us during the last upgrade as brave expected version 2.8.4 but our pom file was using version 2.7.10.

It would be great if the [brave bom import](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/pom.xml#L181) could be moved to [spring-cloud-sleuth-dependencies](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-dependencies/pom.xml)  so that we can remove the version number from our own project to more easily keep things in sync.

**Comment by marcingrzejszczak** [comment]
@dsyer do you see any issues with this?

**Comment by spencergibb** [comment]
In other spring cloud projects, versions of things uniquely provided by the project go in dependencies bom: in Netflix, eureka, hystrix and zuul for example. Things that are provided somewhere else in the framework go in the parent like spring cloud modules and other libraries provided by Framework or boot. Seems like brave should go in the dependency bom to me.

**Comment by dsyer** [comment]
Problems then arise if the foreign bom also has dependencies which clash with Spring Boot (cf AWS). So we need to check the brave  to make sure it doesn’t have stuff that is managed elsewhere.

**Comment by devinsba** [comment]
The brave BOM only manages things within `io.zipkin*` groups so we should be safe there. Maybe there is a way for us to add that to CI so we don't accidentally introduce something bad.

**Comment by adriancole** [comment]
yeah brave only sets versions of itself and its instrumentation uses
provided scope. It does import zipkin-reporter's bom iirc, which if you use
one of the senders, like amqp, then I suppose it is possible for that to
affect versions as senders use compile scope. OTOH, sleuth already controls
the senders likely to be chosen including the amqp one :)

The brave BOM only manages things within io.zipkin* groups so we should be
> safe there. Maybe there is a way for us to add that to CI so we don't
> accidentally introduce something bad.
>
that'd be interesting.. a bom test.
