### ISSUE TITLE
Spring Cloud Gateway is truncating TraceID coming from other application

### ISSUE THREAD

**Issue by guptaamit** [spring-cloud/spring-cloud-sleuth#1391]

**Comment by adriancole** [comment]
I really hope parent spanid is not literally '-'

**Comment by guptaamit** [comment]
From the first application it will always be "-", the from App 2, Parent Span id will be App 1 Span id

**Comment by adriancole** [comment]
@guptaamit that is a bug

**Comment by adriancole** [comment]
`-` has never been a valid parent ID https://github.com/openzipkin/b3-propagation 

There was a bug a couple years ago in the cloudfoundry gorouter that added that, but it was resolved

**Comment by guptaamit** [comment]
Here the main issue is that in App3 which is spring cloud gateway is creating new trace Id and not printing 123

**Comment by adriancole** [comment]
you should probably start by mentioning which version of sleuth and brave are being used by your app 3 doing this type of troubleshooting on gitter is more efficient and less spammy to those watching the repo https://gitter.im/spring-cloud/spring-cloud-sleuth

**Comment by guptaamit** [comment]
Strange thing is I am not explicitly including sleuth in my grade file..

**Comment by adriancole** [comment]
I don't think spring-cloud-gateway implicitly includes sleuth. you would need to add the sleuth dependency if you want traces to continue.

**Comment by guptaamit** [comment]
I didn't add sleuth because the app3 is already printing new trace id.. 
I will check the behavior again after adding sleuth

**Comment by marcingrzejszczak** [comment]
Without sleuth tracing will not work in gateway.
