### ISSUE TITLE
Instrumentation for spring integration

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-sleuth#14]
Email thread as first thoughts.

----
Date: Tue, 4 Aug 2015 16:26:46 -0600
Subject: Tracing messages and spring integration
From: Spencer Gibb
To: Artem Bilan, Gary Russell

Artem and Gary,

I'm looking to add support to [spring-cloud-sleuth](https://github.com/spring-cloud/spring-cloud-sleuth) for tracing (start/end timings, etc...) spring integration messages, especially those that cross thread boundaries.

Dave pointed me at the following:

https://jira.spring.io/browse/INT-2166
https://github.com/spring-projects/spring-integration/pull/1493

Especially [SecurityContextPropagationChannelInterceptor.java]
(https://github.com/artembilan/spring-integration/blob/4e3f36c8ab6767cd141e9ee29b5efce924b1700b/spring-integration-security/src/main/java/org/springframework/integration/security/channel/SecurityContextPropagationChannelInterceptor.java) because it is similar to how the tracing context is held (ie a ThreadLocal).

Is this a good model to follow?  If not, any other ideas?

----
Date: Tue, 4 Aug 2015 20:20:13 -0400
Subject: Re: Tracing messages and spring integration
From: Gary Russell
To: Spencer Gibb
Cc: Artem Bilan

Yes, we made it a subclass of for ThreadStatePropagationChannelInterceptor exactly that reason (propagating other thread-based state).

However, we don't currently have a solution for propagating across the network (which is a bit more tricky for security, we don't want to simply convey an Authentication - the sender might not be trusted).

If you need to propagate it across loosely coupled integration-based apps (e.g. via rabbitmq etc), it might be better to carry the trace information in a message header, similar to MessageHistory (when enabled in SI).

We added something similar to XD to convey XD module transits by adding to the header as the message transits each module in an XD stream.

Hope that helps.

Gary

----
Subject: Re: Tracing messages and spring integration
Date: Wed, 5 Aug 2015 09:22:58 +0100
To: Spencer Gibb

Yeah message headers sound like the best place to put the correlation ids. But the injection point (and how to automate it/ optimize it) might be similar. We just need a way to catch the incoming requests mainly.

**Comment by dsyer** [comment]
The security context interceptor is a good building block: it keeps the thread context up to date when Spring Integration hands off between threads. Missing are:

* Creating the span on an incoming message (question: how to identify incoming messages, as opposed to any old message that is in flight and not being sampled?)

* Ensuring that the span headers are propagated through all external middleware. Problem here is that they are all different, e.g. JMS has headers and by default copies all headers, AMQP has headers and doesn't, Redis and Kafka do not have headers.

* How to signal to a downstream service that the message is not being sampled (and that the decision was already made)?

**Comment by dsyer** [comment]
This one is closeable (all problems addressed in some way). The "common data model" is an ongoing effort so additional issues can be raised against that as necessary.
