### ISSUE TITLE
Sleuth with webflux

### ISSUE THREAD

**Issue by dlsrb6342** [spring-cloud/spring-cloud-sleuth#1402]
I tested sleuth with webflux and mvc. But webflux with sleuth doesn't work properly.
You can see [my test example](https://github.com/dlsrb6342/sleuth-example).

fcaller, fclient are made with webflux. fcaller send request to fclient. 
And mcaller, mclient are made with mvc. mcaller send request to mclient.

I used zipkin server with docker. 
```shell
docker run -d -p 9411:9411 openzipkin/zipkin
```

### with mvc
I send request to mcaller. and mcaller request to mclient
**ME -> mcaller -> mclient**

<img width="1326" alt="스크린샷 2019-07-21 오후 9 51 47" src="https://user-images.githubusercontent.com/19386038/61591436-e2b57b80-ac01-11e9-8050-15d9d9fb3f23.png">

It works well as I expected.

### with webflux
same scenario with mvc. 
**ME -> fcaller -> fclient**

<img width="1330" alt="스크린샷 2019-07-21 오후 9 53 17" src="https://user-images.githubusercontent.com/19386038/61591466-23ad9000-ac02-11e9-8f73-18faff9dfccc.png">

but It doesn't record "Server Start - Server Finished" span. 

<br/>

In debugging mode, `WebFilterTraceSubscriber.onComplete()` never called. So "Server span" isn't reported.

https://github.com/spring-cloud/spring-cloud-sleuth/blob/06ccdd60abf6f47626d4c9fe568a2440233eca67/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java#L252-L256

<br/>

Is there any problem in my usage with webflux? Or is it works well as as you intended?

**Comment by adriancole** [comment]
can you make a fork of https://github.com/openzipkin/sleuth-webmvc-example and make minimal changes for webflux? then easier for shared troubleshooting. Also we can use this later

**Comment by dlsrb6342** [comment]
@adriancole 
https://github.com/dlsrb6342/sleuth-webmvc-example/tree/with-webflux
Please check this repo. 

There is only one change that from spring-boot-starter-web to spring-boot-starter-webflux in pom.xml
Because webflux support `@RestController` or `@RequestMapping`, it doesn't need any other changes.

![image](https://user-images.githubusercontent.com/19386038/61607336-3e771780-ac89-11e9-92c5-b11a998bbe7e.png)
I send request to "http://localhost:8081/" and got response "Mon Jul 22 13:50:29 KST 2019%".
And, the zipkin tracing result is same as [my example](https://github.com/dlsrb6342/sleuth-example). 
![image](https://user-images.githubusercontent.com/19386038/61607270-eb04c980-ac88-11e9-864d-098b96508bce.png)
You can see `Parent ID: d60a8b29b7d83af0` in image. But there is no span with that name. 
I think the Parent Span was a "Server Start - Server Finish" span.

As I said in above comment, `WebFilterTraceSubscriber.onComplete()` is never called. Please test with above repo.

**Comment by adriancole** [comment]
flying all day so excuse delays. thx for raising this

**Comment by marcingrzejszczak** [comment]
Your controllers need to return a flux or mono.

**Comment by dlsrb6342** [comment]
@marcingrzejszczak 
I replaced with Mono and tested again. https://github.com/dlsrb6342/sleuth-webmvc-example/tree/return-publisher
But result is same as upper test.

![image](https://user-images.githubusercontent.com/19386038/61611203-2e196980-ac96-11e9-8b30-8494e325b2ce.png)
![image](https://user-images.githubusercontent.com/19386038/61611183-22c63e00-ac96-11e9-8298-b8701760f395.png)

**Comment by dlsrb6342** [comment]
Additionally I made example with `RouterFunctions`.

And this test also got same result.
![image](https://user-images.githubusercontent.com/19386038/61611904-05926f00-ac98-11e9-8aef-dffc93609c47.png)
![image](https://user-images.githubusercontent.com/19386038/61611878-f7445300-ac97-11e9-92c0-eafe8da5b295.png)

**Comment by dlsrb6342** [comment]
@adriancole  Did you check about this issue?

**Comment by adriancole** [comment]
looking now. thx for the ping as was snowed under

**Comment by adriancole** [comment]
ok I do not know why this is the case, but anyway..

This does not result in a server span
```java
  public Mono<ServerResponse> printDate(ServerRequest request) {
    String dateString = new Date().toString();
    return ServerResponse.ok().body(BodyInserters.fromObject(dateString));
  }
```

This does
```java
  public Mono<ServerResponse> printDate(ServerRequest request) {
    return ServerResponse.ok().body(BodyInserters.empty());
  }
```

hope the hint helps

**Comment by dlsrb6342** [comment]
Yes. Your case works well. But that's so weird...  I think it would have to be fixed .

**Comment by adriancole** [comment]
agree I think there's some problem. not sure if it has already been fixed or not. can you change your example to use snapshot? I'm going to be offline a bit

**Comment by dlsrb6342** [comment]
https://github.com/dlsrb6342/sleuth-webmvc-example/tree/with-snapshot
![image](https://user-images.githubusercontent.com/19386038/62376479-aed04380-b57b-11e9-8e3d-cae7cc989b42.png)

It has already been fixed! With snapshot, it works well!! Thanks for helping.

**Comment by marcingrzejszczak** [comment]
Cool, thanks!
