### ISSUE TITLE
[REGRESSION] DelegatingSecurityContextExecutor NPE when using Spring cloud sleuth Greenwich.SR2

### ISSUE THREAD

**Issue by orenw1** [spring-cloud/spring-cloud-sleuth#1403]
Bug report

Working in: Finchley.SR3
Regression in: Greenwich.SR2

Using DelegatingSecurityContextSchedulingTaskExecutor for `@Async` handling
causing NPE, as the method `createAsyncTaskExecutorProxy` of
`org.springframework.cloud.sleuth.instrument.async.ExecutorBeanPostProcessor`
return proxied object that is missing the delegate Executor field of
`DelegatingSecurityContextExecutor`.

See [ExecutorBeanPostProcessor line 198](https://github.com/spring-cloud/spring-cloud-sleuth/blob/v2.1.2.RELEASE/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/ExecutorBeanPostProcessor.java#L198)

This is similar to #1212

i have created a [sample project](https://github.com/orenw1/sleuth-delegate-executor-issue)
with a test where you can change the spring cloud version in the pom.xml to
see the change in behavior from Finchley.SR3

**Comment by marcingrzejszczak** [comment]
If you upgrade your project to `Greenwich.BUILD-SNAPSHOT` the problem is already solved
