### ISSUE TITLE
Ability to provide a custom name for redis spans

### ISSUE THREAD

**Issue by worldtiki** [spring-cloud/spring-cloud-sleuth#1406]
https://github.com/lettuce-io/lettuce-core/pull/866 adds an enhancement where we can override the service name for calls to Redis (default is "redis").

An example of where we may want to do this is on setups where there are multiple installations of Redis. Using the default name would mean that in a service graph visualization, different services interacting with separate Redis would appear as if they are interacting with the same one.

**Comment by marcingrzejszczak** [comment]
What do you think about this @adriancole ?

**Comment by adriancole** [comment]
remoteServiceName is a method on span. some instrumentation add a default and have an override, ex mysql has one for the database. ex makes mysql-db. so yeah things like this are common enough to change and there's a method to do that.

cc also @jeqo who had some similar thoughts on message brokers/topics

**Comment by marcingrzejszczak** [comment]
Currently we apply tracing to redis via `org.springframework.cloud.sleuth.instrument.redis.TraceLettuceClientResourcesBeanPostProcessor`. I wonder how we can differentiate between installation names from there. 

How exactly would you like to provide different names @worldtiki ?

**Comment by worldtiki** [comment]
Hi @marcingrzejszczak 👋

I think something like allowing users to override a `spring.sleuth.redis.service-name` would be enough.
I understand that it doesn't cover the cases where a single Spring app connects to multiple Redis installations, but I would consider that an edge case.
I don't have data to prove this but my guess is that when there are multiple Redis installations they are typically used by different apps.

If there's no rush I can open a pr with a proposal early next week.

**Comment by adriancole** [comment]
@worldtiki if this is one redis than why wouldn't a finishedspanhandler work?

**Comment by worldtiki** [comment]
Yes, but imo that's not not a great experience.

My thoughts on this is that since Redis is a first level citizen in Sleuth (`spring.sleuth.redis`) it would simplify the developer experience if there was an easy way to tweak the name.

**Comment by adriancole** [comment]
I'm sure you get that if we add a property by default it will have to stick
around. I wanted to give you an option meanwhile.

it doesnt seem like many people are asking for this feature and rushing to
a property is usually not a good things under these conditions. I think you
also mentioned this would only work for one instance of redis whereas the
finished span handler would work for any number of them. it is helpful to
know options even if what I suggested isnt of interest to you.

can you find another person you dont work with who is an end user and would
be served by the property?

usually you can find someone by looking at past change on a feature and who
has been involved.

**Comment by adriancole** [comment]
if trying to develop something like this it is also helpful to use real values. For example I mentioned a while back that mysql varies by default on db name and something similar could be considered here. when discussing options please put ideas of how you would use this property and assign it. like how a user would get the value of the property set to avoid the issue you mentioned.

**Comment by worldtiki** [comment]
I'm not ignoring you Adrian/Marcin.
I just don't know that many folks who are using Redis with Sleuth :)

The name would always have to be set manually. As far as I know the individual nodes have a name but the cluster itself does not.
In my case we append the name of the service, eg: redis-foo or redis-bar and this is how we identify them in our monitoring tools.
I don't know if this is a common practice, and I agree it would be useful to hear other voices.

ps: Redis also has a concept of namespaces but I think that's a different abstraction: the cluster is still the same as well as the client used.

**Comment by adriancole** [comment]
yay I get a chance to help :) I used to work in telemarketing so I really believe in numbers. Meaning by tagging several people usually at least one or two will respond.

here's what I do.. I search repos for people using redis.

for example here with the term redis https://github.com/spring-cloud/spring-cloud-sleuth/search?q=redis&type=Issues

and lettuce with the term sleuth
https://github.com/lettuce-io/lettuce-core/search?q=sleuth&type=Issues

Personally I know that LINE uses lettuce also (@kojilin), but by aggregating the people who collaborated in the above issues with a comment here with a question, the chances are higher at getting an answer vs just those watching this repo.

So, for example, your straw-man is that there is one remote service name for lettuce. I'd present that as a hypothesis, cc'ing (nagging) all the people.. asking if this would help them or if they are doing something different. Make sense?

**Comment by adriancole** [comment]
PS I found a way out of this.. Precedent! While we (surprisingly) have no people commenting on this except us, we do have precedent I didn't notice before.

Ex looky looky
```
|spring.sleuth.messaging.jms.remote-service-name | jms | 
|spring.sleuth.messaging.kafka.remote-service-name | kafka | 
|spring.sleuth.messaging.rabbit.remote-service-name | rabbitmq | 
```

So, instead of popularity, let's try precedent based on the above prior art, which is consistent.

copying folks I scraped from the above issues in case they hate the idea. Otherwise, let's merge in a couple days. @worldtiki I presume you are cool raising the PR?

@datagitlies @kktn-FW @chang-chao @mp911de @yarodinD  @dyc87112 So, the idea is to default the redis service name from a property like so

```
|spring.sleuth.messaging.redis.remote-service-name | redis | 
```

If any of you can give literal real examples of what your redis service name would be, it would be instructive

**Comment by datagitlies** [comment]
I've been fine so far having the default service name "redis" appear in spans but can see how this might be helpful for @worldtiki in his situation. I don't have multiple redis installations but since I like the data driven approach of @adriancole I'll comment here with my service name: `redis-cups`

**Comment by worldtiki** [comment]
I'm using a similar format: redis _dash_ tla of the app that uses that redis.

I opened a draft with how I think this could look like: #1475
