### ISSUE TITLE
how to add tags in logs - logback pattern 

### ISSUE THREAD

**Issue by Marek00Malik** [spring-cloud/spring-cloud-sleuth#1407]
I'm trying to add a tag to a new Span that I start manually. 
IT seems to work properly, but I cannot get the correct configuration to have it print out in logs.

This is how I use my new Span:
```
val newSpan: Span = tracer
            .nextSpan()
            .name("mq-communication")
            .tag("correlationId", requestMessage.messageId)

        tracer.withSpanInScope(newSpan.start()).use {
            log.info("Sending request to XX queue ${requestQueue.name}")
            ///---- some work
            log.info("Receiving reply from queue ${responseQueue.name}")
            return responseMessage
        }
```
I already tried pattern as such:
"%X{correlationId:-}"
"%X{tag-correlationId:-}"
"%X{tags-correlationId:-}"
"%X{X-B3-Tag-correlationId:-}",
"%X{X-B3-Tags-correlationId:-}",

**Comment by Marek00Malik** [comment]
Ehm... I figured out that the span that is created is always a NoopSpan, which has an empty tag method implemented ;/
Can someone point me to how should the Tracer be initialized that the Tracing class does not create any noop Spans ?

**Comment by marcingrzejszczak** [comment]
Please read the docs about sampling https://cloud.spring.io/spring-cloud-static/Greenwich.SR2/single/spring-cloud.html#_sampling

**Comment by Marek00Malik** [comment]
Thx @marcingrzejszczak for the hint, but still. The first question -> how tags should be retrieved throw a logging pattern ?

**Comment by marcingrzejszczak** [comment]
You won't do it via tags. Please try extra field propagation. Please read this section of the documentation https://cloud.spring.io/spring-cloud-static/Greenwich.SR2/single/spring-cloud.html#_propagating_extra_fields

**Comment by Marek00Malik** [comment]
Thx @marcingrzejszczak for the hint !:) 
But still, there is the first part, how should I retrieved that tag in the logging patterns ?
