### ISSUE TITLE
Should RateLimitingSampler be public?

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-sleuth#1409]
I am trying to replicate* changes from [`SamplerAutoConfiguration`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/e13f7f80489da35fbac1840451acd4252219e652/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/sampler/SamplerAutoConfiguration.java#L39) autoconfiguration logic into [spring-cloud-gcp](https://github.com/spring-cloud/spring-cloud-gcp/blob/4059007bd5fbe7f7c7c00d8472b00230a52465fb/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/trace/StackdriverTraceAutoConfiguration.java#L199-L224), but [`RateLimitingSampler`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/e13f7f80489da35fbac1840451acd4252219e652/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/sampler/RateLimitingSampler.java#L30) is package-private. Was it meant to be only package private, or is it okay to relax its visibility to `public`? `ProbabilityBasedSampler`, which is in the same package and is used similarly, is public already.

\* I'd rather not replicate them at all and just rely on `SamplerAutoConfiguration`, but whenever `TraceAutoConfiguration` and `SamplerAutoConfiguration` are both present, `TraceAutoConfiguration`'s [NEVER_SAMPLE](https://github.com/spring-cloud/spring-cloud-sleuth/blob/a5c4f05c2d6c15fe06b7e6ec3325162bc4b58796/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java#L122) sampler gets instantiated due to Spring Boot ordering (`TraceAutoConfiguration` has an order and `SamplerAutoConfiguration` does not, so `SamplerAutoConfiguration` is processed at the end). From the docs, NEVER_SAMPLE [seems like intended behavior](https://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/2.0.4.RELEASE/multi/multi__sampling.html#_sampling_in_spring_cloud_sleuth).

**Comment by TYsewyn** [comment]
AFAIC that's actually a bug. `SamplerAutoConfiguration` should have `@AutoConfigureBefore(TraceAutoConfiguration.class)` and a way to enable/disable sampling with a property. Because `spring-cloud-gcp` is depending on `spring-cloud-sleuth-core` you'd have those samplers too.

I don't see the reason of replicating those changes into `spring-cloud-gcp` though.
What would be the added benefit of doing that?

**Comment by elefeint** [comment]
No added benefit whatsoever! `@AutoConfigureBefore(TraceAutoConfiguration.class)` in `SamplerAutoConfiguration` will be the perfect solution to our problem; then I can remove the custom sampler beans from [StackdriverTraceAutoConfiguration](https://github.com/spring-cloud/spring-cloud-gcp/blob/72d746486fedd19b16ead3cdbbcfb48c3e90c3a9/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/trace/StackdriverTraceAutoConfiguration.java#L80) for good.

**Comment by TYsewyn** [comment]
I've added it to my pile of todo items, will try to get it fixed in core.
In the meantime a simple `@Import({ SamplerAutoConfiguration.class })` on `StackdriverTraceAutoConfiguration` should be able to do the trick.

**Comment by elefeint** [comment]
Thank you!
I tried the import route before, but because `TraceAutoConfiguration` is also brought in (through `spring.factories` in real world scenarios, and directly in tests), its NEVER_SAMPLE bean still took precedence.

**Comment by elefeint** [comment]
Thank you @TYsewyn and @marcingrzejszczak for removing the unnecessary configuration from spring-cloud-gcp. 

I wonder, though, if #1410 should still be considered. Both `SamplerAutoConfiguration` and `TraceAutoConfiguration` get imported through [`spring.factories`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/fe997283d1b20c685f743e528328bbe99519549e/spring-cloud-sleuth-core/src/main/resources/META-INF/spring.factories#L4), so if a project depends on `spring-cloud-sleuth-core` and configures `spring.sleuth.sampler.enabled=true`, it would not be obvious why tracing is off. Perhaps a warning message would be useful if the  `sleuthTraceSampler()` ends up being configured while `spring.sleuth.sampler.enabled` is on?

**Comment by marcingrzejszczak** [comment]
There's no such property to disable a sampler. It doesn't make much sense to have one.
