### ISSUE TITLE
JmsListener stops working if sleuth on the classpath

### ISSUE THREAD

**Issue by dome313** [spring-cloud/spring-cloud-sleuth#1414]
I have a simple rest controller which uses JmsTemplate to send a message
```
    @ResponseStatus(HttpStatus.OK)
    @GetMapping("/test")
    public void sendMessage() {
        System.out.println("Sending a test message");
        Map<String, String> map = new HashMap<>();
        map.put("hello", "world");
        jmsTemplate.convertAndSend("DEV.QUEUE.1", map);
    }
```
and then that message is consumed by JmsListener
```
    @JmsListener(destination = "DEV.QUEUE.1")
    public void receiveMessage(HashMap map) {
        System.out.println("Test message received...");
        System.out.println("Content received" + map);
    }
```
This code was tested with ActiveMQ and IBM MQ and it works fine.
The things go wrong once I add **spring-cloud-starter-sleuth** to the classpath, after that JmsListner is not receiving the message anymore.

I created this mini project to demonstrate this
https://github.com/dome313/jms-sleuth

Also, [here](https://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_spring_jms) it's state that sleuth supports Jms

Versions used:
Spring boot: 2.1.6.RELEASE
Spring cloud dependencies: Greenwich.RELEASE

**Comment by marcingrzejszczak** [comment]
Hi we already have greenwich.sr2 release can you please check if it works fine with that version? Thanks!

**Comment by dome313** [comment]
Hi, it works fine with Greenwich.SR2. Thanks for your help.
The way it is sorted on mvnrepository is to blame 😄 
![Screenshot_8](https://user-images.githubusercontent.com/11508086/62126610-034b9880-b2c8-11e9-9d46-9dcda891c703.png)

**Comment by marcingrzejszczak** [comment]
Great to hear that. BTW you can check https://spring.io/projects/spring-cloud#learn for the latest versions.
