### ISSUE TITLE
Add redaction support to extra fields config

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#1421]
Some people want to add "extra fields" but at process scope, and not propagated downstream. Currently, the approach to implementing this is to add them as "redacted" https://github.com/openzipkin/brave/tree/master/brave#redacting-fields

This serves use cases like log context synchronization for totally trusted applications. What I mean by trusted is that applications should be as careful about what to put in extra fields as they are about MDC, as anything in the classpath can read them.

Incidentally, this was added for sleuth, requested by @alonbl but I don't think we hooked it together, yet. hence the issue.

https://github.com/openzipkin/brave/tree/master/brave#redacting-fields
https://github.com/openzipkin/brave/pull/931

**Comment by adriancole** [comment]
You can now use the `spring.sleuth.local-keys` property to pass a list keys that will be propagated locally but will not be propagated over the wire.

**Comment by alonbl** [comment]
Thank you all! Much appreciated.
