### ISSUE TITLE
SpanId changes on WebClient request

### ISSUE THREAD

**Issue by gabriel-cardenete-movile** [spring-cloud/spring-cloud-sleuth#1423]
I am doing a simple HTTP request with WebClient, and the spanId is changing.
I noticed that this doesn't happen in `Finchley.RELEASE`, but is happening on `Greenwich.SR2`

I have the following code:
```kotlin
restTemplate.getForObject(
        "https://github.com",
        String::class.java
)

logger.info("no spanId changes")

webClient.get()
        .uri("https://github.com")
        .retrieve()
        .bodyToMono(String::class.java)
        .block()

logger.info("spanId changed!")
```
Example output:
```
[c177ebd3831cc307-c177ebd3831cc307] no spanId changes
[c177ebd3831cc307-bcdfe282f4b59a0c] spanId changed!
```
Full project: https://github.com/gabriel-cardenete-movile/sleuth-webclient-problem

Am I doing something wrong here?

Thanks in advance!

**Comment by marcingrzejszczak** [comment]
Could you please always first verify an issue against the latest stable release before filing it? Greenwich.sr2 is the latest one

**Comment by gabriel-cardenete-movile** [comment]
Sorry, I checked with `Greenwich.SR2` and the problem still happens.

**Comment by marcingrzejszczak** [comment]
We have working code with webflux. You can check the samples here https://github.com/spring-cloud-samples/sleuth-documentation-apps

I wonder why do you have both resttemplate and webclient together. You should pick only one either webmvc or webflux

**Comment by gabriel-cardenete-movile** [comment]
I was testing both, to see if normally the request should change the current spanId. If I don't use RestTemplate, the problem still occurs. 

Sleuth doesn't work correctly with webmvc and webflux at the same time?

**Comment by marcingrzejszczak** [comment]
You shouldn't have webmvc and webflux at the same time in your application. It's not a matter of sleuth but boot.

**Comment by marcingrzejszczak** [comment]
You shouldn't have webmvc and webflux at the same time in your application. It's not a matter of sleuth but boot.

**Comment by gabriel-cardenete-movile** [comment]
I removed webmvc dependencies, and it still changes spanId after webClient request. Again, I tried with `Finchley.RELEASE` and it works fine.

**Comment by marcingrzejszczak** [comment]
Please check out the samples and write your code in the same way. If you're using  webflux please make all the controllers return flux or mono.

**Comment by gabriel-cardenete-movile** [comment]
I ran the samples project with zipkin (start_with_zipkin_server.sh), and the output of service1 was the following:
```
 INFO [service1,ebb620aa0f57a20b,ebb620aa0f57a20b,true] i.s.c.s.docs.service1.Service2Client     : Hello from service1. Setting baggage foo=>bar
 INFO [service1,ebb620aa0f57a20b,ebb620aa0f57a20b,true] i.s.c.s.docs.service1.Service2Client     : Super secret baggage item for key [baggage] is [null]
 INFO [service1,ebb620aa0f57a20b,ebb620aa0f57a20b,true] i.s.c.s.docs.service1.Service2Client     : Hello from service1. Calling service2
DEBUG [service1,ebb620aa0f57a20b,ebb620aa0f57a20b,true] .s.c.s.i.w.c.TraceExchangeFilterFunction : Instrumenting WebClient call
DEBUG [service1,ebb620aa0f57a20b,ebb620aa0f57a20b,true] .s.c.s.i.w.c.TraceExchangeFilterFunction : Handled send of RealSpan(ebb620aa0f57a20b/fc1f575e0c12ff06)
 INFO [service1,ebb620aa0f57a20b,fc1f575e0c12ff06,true] i.s.c.s.docs.service1.Service2Client     : Got response from service2 [Hello from service2, response from service3 [Hello from service3] and from service4 [Hello from service4]]
 INFO [service1,ebb620aa0f57a20b,fc1f575e0c12ff06,true] i.s.c.s.docs.service1.Service2Client     : Service1: Baggage for [key] is [foo]
```
Again, the spanId changed after a WebClient request.

**Comment by marcingrzejszczak** [comment]
I'll investigate it once I have some spare time.

**Comment by marcingrzejszczak** [comment]
Should be fixed via https://github.com/spring-cloud/spring-cloud-sleuth/issues/1516
