### ISSUE TITLE
No Spring Cloud Sleuth traces for Servlet Filter

### ISSUE THREAD

**Issue by damvinod** [spring-cloud/spring-cloud-sleuth#1425]
I am using a custom Filter for validating the http request before forwarding the request to RestController.

Sleuth is attaching the Trace Id and Span Id only from controller layer and not for the logs in Filter.

I have seen from spring sleuth documentation as below

"Instruments common ingress and egress points from Spring applications (servlet filter, async endpoints, rest template, scheduled actions, message channels, Zuul filters, and Feign client)."

It says that the span supports for 'servlet filter' but its not working for me.

**Below is the code and let me know if any configuration is required to apply traces to Filter**

**application.properties**
spring.zipkin.base-url=loclhost:9411
spring.zipkin.sender.type=web
spring.sleuth.propagation-keys=x-request-id
spring.sleuth.log.slf4j.whitelisted-mdc-keys=x-request-id
spring.sleuth.async.enabled=false
spring.sleuth.web.additionalSkipPattern=/admin/*

**FilterConfig.class**
@Configuration
public class FilterConfig {

    private CustomFilter customFilter;

    FilterConfig(CustomFilter customFilter) {
        this.customFilter = customFilter;
    }

    @Bean
    public FilterRegistrationBean<CustomFilter> filterRegistrationBean() {

        FilterRegistrationBean<CustomFilter> registrationBean = new FilterRegistrationBean<>();

        registrationBean.setFilter(customFilter);
        registrationBean.setOrder(Ordered.HIGHEST_PRECEDENCE);
        return registrationBean;
    }
}

**CustomFilter.class**
@Slf4j
@Component
public class CustomFilter implements Filter {

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
        throws IOException, ServletException {
.....
}
}

**Comment by marcingrzejszczak** [comment]
You've set your filter with the highest precedence. So your filter comes in first before the trace filter. Your filter needs to be after the trace filter.

**Comment by marcingrzejszczak** [comment]
You can use this order value when registering your own filter https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebServletAutoConfiguration.java#L67

**Comment by damvinod** [comment]
> You can use this order value when registering your own filter https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebServletAutoConfiguration.java#L67

Modified as below but still the same traces are applied to the filter layer

**registrationBean.setOrder(Ordered.HIGHEST_PRECEDENCE + 5);**

**Comment by marcingrzejszczak** [comment]
Please set

`registrationBean.setOrder(TraceWebServletAutoConfiguration.TRACING_FILTER_ORDER + 5);`

**Comment by damvinod** [comment]
> Please set
> 
> `registrationBean.setOrder(TraceWebServletAutoConfiguration.TRACING_FILTER_ORDER + 5);`

Yes it worker Thanks
