### ISSUE TITLE
context integration for spring-jms

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#1427]
@Liodene mentions he's using sleuth, but the message listener isn't continuing the trace. I don't see anything in his stack that would suggest it would. Wondering if something is not integrating property here.

```
lambda$configure$0:32, SomeRoute (consumption)
process:-1, 582025508 (SomeRoute$$Lambda$566)
process:63, DelegateSyncProcessor (org.apache.camel.processor)
process:548, RedeliveryErrorHandler (org.apache.camel.processor)
process:201, CamelInternalProcessor (org.apache.camel.processor)
process:138, Pipeline (org.apache.camel.processor)
process:101, Pipeline (org.apache.camel.processor)
process:201, CamelInternalProcessor (org.apache.camel.processor)
process:97, DelegateAsyncProcessor (org.apache.camel.processor)
onMessage:113, EndpointMessageListener (org.apache.camel.component.jms)
doInvokeListener:736, AbstractMessageListenerContainer (org.springframework.jms.listener)
invokeListener:696, AbstractMessageListenerContainer (org.springframework.jms.listener)
doExecuteListener:674, AbstractMessageListenerContainer (org.springframework.jms.listener)
doReceiveAndExecute:318, AbstractPollingMessageListenerContainer (org.springframework.jms.listener)
receiveAndExecute:257, AbstractPollingMessageListenerContainer (org.springframework.jms.listener)
invokeListener:1189, DefaultMessageListenerContainer$AsyncMessageListenerInvoker (org.springframework.jms.listener)
executeOngoingLoop:1179, DefaultMessageListenerContainer$AsyncMessageListenerInvoker (org.springframework.jms.listener)
run:1076, DefaultMessageListenerContainer$AsyncMessageListenerInvoker (org.springframework.jms.listener)
runWorker:1142, ThreadPoolExecutor (java.util.concurrent)
run:617, ThreadPoolExecutor$Worker (java.util.concurrent)
run:745, Thread (java.lang)
```

**Comment by marcingrzejszczak** [comment]
Without a sample project it will be close to impossible to help.

**Comment by adriancole** [comment]
I'll merge an example about normal spring JMS. we can ask @Liodene  to what degree if anything the relationship to camel is, or if that can be switched out to not use camel an instead normal spring jms.. one min

**Comment by Liodene** [comment]
I can create a sample project Camel/SB/Sleuth/JMS and add it here. I can't say if Camel is a part of the equation or not.

**Comment by marcingrzejszczak** [comment]
I don't think we instrument Camel at all so no wonder it's not working fine.

**Comment by Liodene** [comment]
True, but Camel is using Spring component.

HTTP is fully working  with Camel for example (span sent to zipkin, SLF4J MDC and so on).
On JMS, the tracing is working (span is sent to Zipkin), but the SLF4J decorator is never triggered for some reasons.

**Comment by adriancole** [comment]
here's normal jms, maybe you can use this to show what else might need to happen https://github.com/openzipkin/sleuth-webmvc-example/compare/add-jms-tracing

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
