### ISSUE TITLE
Different modes for the HystrixConcurrencyStrategy

### ISSUE THREAD

**Issue by worldtiki** [spring-cloud/spring-cloud-sleuth#1431]
Context: I'm using Hystrix to wrap a number of http clients. Each of these clients is instrumented and generates tracing information.

Problem: For each network call there are 2 spans, one generated by the SleuthHystrixConcurrencyStrategy and another by the instrumented http client.
This leads to a duplication of spans and unnecessary nesting when visualising the traces.

Proposal: Include an option to configure SleuthHystrixConcurrencyStrategy so that users can decide if they want to create spans for each Hystrix command execution or just have the SleuthHystrixConcurrencyStrategy to propagate the trace context between threads.

I'm happy to open a pr if there is interest in this.

**Comment by adriancole** [comment]
interesting. pass-through basically. between disabled and enabled

**Comment by worldtiki** [comment]
Exactly.

I think my story is similar to many others, specially for monolith apps. Assuming all network clients are wrapped with Hystrix, it's easy to start capturing spans with the HystrixConcurrencyStrategy.
However at some point the many network clients will be instrumented which means that the Hystrix spans stop providing useful info and become mostly noise.
