### ISSUE TITLE
Sleuth's transparent use of RabbitMQ to deliver traces when it's added as a dependency can be confusing

### ISSUE THREAD

**Issue by GrahamLea** [spring-cloud/spring-cloud-sleuth#1432]
I had a Spring Boot app handling web requests and logging tracing to Zipkin using spring-cloud-starter-zipkin.

I added RabbitMQ messaging to the app using spring-boot-starter-amqp. Noticed later that I was no longer getting tracing reported from this app to Zipkin.

It was surprising to me that adding spring-rabbit to the dependencies automatically switched Sleuth's functionality. Though it is relatively well documented, I had long since forgotten that part of the Sleuth docs when I added Rabbit messaging to the app.

It's possible that I'm an outlier. Maybe the vast majority of developers using Rabbit for app communications also want to use it to deliver tracing telemetry. My assumption was that most developers would be delivering data to Zipkin using HTTP, and so adding RabbitMQ dependencies to my app wouldn't change how Sleuth works unless I explicitly asked Sleuth to use Rabbit instead.

Perhaps, if there's no obvious default to pick when Rabbit or Kafka are in the classpath, Sleuth should fail the container startup with a message requesting an explicit choice to be made?

**Comment by GrahamLea** [comment]
Related Twitter conversation:
https://twitter.com/evolvable/status/1165885545362288640

**Comment by adriancole** [comment]
one option is to require opt-in for rabbit such as we do with kafka https://github.com/spring-cloud/spring-cloud-sleuth/pull/1013

**Comment by marcingrzejszczak** [comment]
The opt in makes a lot of sense. I'd go with that one for hoxton
