### ISSUE TITLE
WebFlux long async call breaks trace/span generation

### ISSUE THREAD

**Issue by BondarenkoIlya** [spring-cloud/spring-cloud-sleuth#1438]
Hello! 

During adding Sleuth to WebFlux project run in to problem that async call which takes a lot of time breaks trace and span id generation - stops to add it to logs. 

It can be reproduced like:
```
Mono.fromFuture(
                CompletableFuture.supplyAsync(()-> {
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        log.error("problem",e);
                    }
                    return "test_message";
                })
        )
                .doOnSuccess(s -> log.info("log message receive result - {}", s)) 
```
In case timeout is 100ms then log record is NOT marked with trace and span.
In case timeout is 10 ms then record marked normally.
For real, I need this Mono.fromFuture because of AWS SDK usage which make async request to S3 bucket.
Am I miss some essential information about Sleuth works with WebFlux or it's could be a bug? 

 Thank you in advanced!

**Comment by marcingrzejszczak** [comment]
I think you're using supply async in such a way that you're not providing the traced executor service like you should https://cloud.spring.io/spring-cloud-sleuth/reference/html/#executor-executorservice-and-scheduledexecutorservice

**Comment by BondarenkoIlya** [comment]
@marcingrzejszczak Thank you for answer.
1. In that case, why it depends on time of async method execution? It works properly with fast execution. 
2. Actually, this is just example. For real I'm not using supply async method, I'm using S3AsyncClient putObject method which return CompletableFuture without any ExecutorService override opportunity. Should I override executor service on TraceableExecutorService for whole application to allow all async call writing trace and span in logs?

**Comment by marcingrzejszczak** [comment]
> In that case, why it depends on time of async method execution? It works properly with fast execution.

Can you post the whole code please?

> Actually, this is just example. For real I'm not using supply async method, I'm using S3AsyncClient putObject method which return CompletableFuture without any ExecutorService override opportunity. Should I override executor service on TraceableExecutorService for whole application to allow all async call writing trace and span in logs?

We wrap it already in sleuth for you.

**Comment by BondarenkoIlya** [comment]
So the real code example is: 
```
public Mono<String> storeData(String data) {
        log.info("S3SinkAdapter test in storeData method");
        return Mono.fromFuture(
                    asyncClient().putObject(PutObjectRequest.builder()
                        .bucket(s3Sink.getS3BucketName())
                        .key(getKey(s3Sink.getFolderPath(), id))
                        .build(), AsyncRequestBody.fromString(dataStr)
                    )
        )
                .onErrorMap(throwable -> new SinkIngestionException("S3 ingestion error", throwable))
                .doOnSuccess(s -> log.info("S3SinkAdapter test in doOnSuccess - {}", s))
                .map(putObjectResponse -> id);
    }

    private S3AsyncClient asyncClient() {
        log.info("S3SinkAdapter test in asyncClient method");
        if (s3AsyncClient == null) {
            S3AsyncClientBuilder builder = S3AsyncClient.builder().region(getRegion());
            if (isNotBlank(s3Sink.getEndpointUrl())) {
                builder.endpointOverride(URI.create(s3Sink.getEndpointUrl()));
            }
            s3AsyncClient = builder.build();
        }
        return s3AsyncClient;
    }
```
Output of that code 
`
08-09-2019 21:02:26.229 trace=9ea5e0e6e29bf02d span=9ea5e0e6e29bf02d [reactor-http-epoll-10] INFO  c.h.i.S3SinkAdapter.storeData - S3SinkAdapter test in storeData method
glix-ingress-traffic            | 08-09-2019 21:02:26.229 trace=9ea5e0e6e29bf02d span=9ea5e0e6e29bf02d [reactor-http-epoll-10] INFO  c.h.i.S3SinkAdapter.asyncClient - S3SinkAdapter test in asyncClient method
glix-ingress-traffic            | 08-09-2019 21:02:26.325 trace= span= [sdk-async-response-0-1] INFO  c.h.i.S3SinkAdapter.lambda$storeData$1 - S3SinkAdapter test in doOnSuccess - PutObjectResponse(ETag="c62895f8a4c1ff890dab02bdf05b7798")
`
in the method beginning log trace and span are present, but right after async call to s3 trace and span are missed

**Comment by marcingrzejszczak** [comment]
I don't know much about S3 clients, but can you check if `S3AsyncClientBuilder` or any other S3 element can have a custom `ExecutorService` or sth like that passed to it?

**Comment by BondarenkoIlya** [comment]
You right. After default executor override, trace and span appeared but they are not the same with previous trace from the same request. Now it looks like
```
08-09-2019 21:02:26.229 trace=e7c2bcb1912345d6 span=e7c2bcb1912345d6 [reactor-http-epoll-10] INFO  c.h.i.S3SinkAdapter.storeData - S3SinkAdapter test in storeData method
08-09-2019 21:02:26.229 trace=e7c2bcb1912345d6 span=e7c2bcb1912345d6 [reactor-http-epoll-10] INFO  c.h.i.S3SinkAdapter.asyncClient - S3SinkAdapter test in asyncClient method
08-09-2019 21:02:26.325 trace=997c7522032dc902  span=997c7522032dc902  [sdk-async-response-0-1] INFO  c.h.i.S3SinkAdapter.lambda$storeData$1 - S3SinkAdapter test in doOnSuccess - PutObjectResponse(ETag="c62895f8a4c1ff890dab02bdf05b7798")
```
Could it be related with some other configurations ?

**Comment by marcingrzejszczak** [comment]
Maybe, I have no idea what you did so I don't know how to help you.

**Comment by BondarenkoIlya** [comment]
Actually, as I find out, looks like trace and span creation breaks right after new reactive publisher appears in chain. Span information stored in Publisher's context are still valid but current span from tracer is new. I workaround that problem by overriding Tracer's span on old one from context by `tracer.withSpanInScope(span.start())` but anyway it's just temporary untidy solution. And it's looks like Sleuth cannot handle situation where new Mono appears in chain

**Comment by marcingrzejszczak** [comment]
Can you show us exactly what you did?

**Comment by BondarenkoIlya** [comment]
```
public Mono<String> storeData(JsonNode data) {
        String dataStr = getDataString(data);
        String id = DigestUtils.md5DigestAsHex(dataStr.getBytes(StandardCharsets.UTF_8));
        log.info("S3SinkAdapter start data storing"); // trace=65eaa269850538b2 
        return Mono.fromFuture(
                asyncClient().putObject(PutObjectRequest.builder()
                        .bucket(s3Sink.getS3BucketName())
                        .key(getKey(s3Sink.getFolderPath(), id))
                        .build(), AsyncRequestBody.fromString(dataStr)
                )
        )
                .materialize()
                .doOnNext(signal -> {
                    log.info("before trace rewrite"); // trace=d15162eea3a013de (new trace) 
                    Span span = signal.getContext().get(Span.class); // old trace inside context 
                    tracer.withSpanInScope(span.start());
                })
                .<PutObjectResponse>dematerialize()

                .onErrorMap(throwable -> new SinkIngestionException("S3 ingestion error", throwable))
                .doOnSuccess(s -> log.info("S3SinkAdapter stored data successfully")) // old right trace trace=65eaa269850538b2
                .map(putObjectResponse -> id);
    }

    private S3AsyncClient asyncClient() {
        log.info("s3 async client configuration start");
        if (s3AsyncClient == null) {
            S3AsyncClientBuilder builder = S3AsyncClient.builder()
                    .asyncConfiguration(b -> b.advancedOption(SdkAdvancedAsyncClientOption.FUTURE_COMPLETION_EXECUTOR,
                            traceableExecutorService).build()
                    )
                    .region(getRegion());
            if (isNotBlank(s3Sink.getEndpointUrl())) {
                builder.endpointOverride(URI.create(s3Sink.getEndpointUrl()));
            }
            s3AsyncClient = builder.build();
        }
        return s3AsyncClient;
    }
```

This how my workaround looks like

**Comment by marcingrzejszczak** [comment]
@bsideup why 

```
.doOnNext(signal -> {
                    log.info("before trace rewrite"); // trace=d15162eea3a013de (new trace) 
                    Span span = signal.getContext().get(Span.class); // old trace inside context 
                    tracer.withSpanInScope(span.start());
                })
```

is not wrapped with our instrumentation in this case? Is it because the `AsyncClient` is not a bean?

**Comment by BondarenkoIlya** [comment]
What you expect to be wrapped ? `asyncClient().putObject`which return CompletableFuture? If yes - I made AsyncClient use traceableExecutorService (it's mentioned in code above).

**Comment by marcingrzejszczak** [comment]
I expected

```.doOnNext(signal -> {  ... }) ```

to already have a span in scope.

**Comment by BondarenkoIlya** [comment]
I also expected :) But whole that issue is about wrong span there. 
I wrote comments near logging (in the code above) with traces which is produced for them and you can see there that without propagation span into trace manually, it got new trace instead of using existing in signal context.

**Comment by devinsba** [comment]
I don't know that this would solve the problem but to remove the possibility of the S3 client causing this is it possible for you to try using: https://github.com/openzipkin/zipkin-aws/tree/master/brave-instrumentation/aws-java-sdk-v2-core to instrument the client. We've implemented it to attach the context to the underlying request.

**Comment by marcingrzejszczak** [comment]
Ok I get it. So you're saying that inside the ThreadLocal we have the new trace (which is wrong) but in the context we have the proper span?

**Comment by BondarenkoIlya** [comment]
@devinsba Unfortunately it's not works for me, it still starts to create new span instead of using one from context.

**Comment by BondarenkoIlya** [comment]
@marcingrzejszczak Yes, `tracer.currentSpan` shows just generated span, `signal.getContext().get(Span.class)` right old span.

**Comment by marcingrzejszczak** [comment]
Is this actually a problem with the latest Sleuth releases?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
