### ISSUE TITLE
Create custom Spring scopes for Span (and Trace if possible)

### ISSUE THREAD

**Issue by rLitto** [spring-cloud/spring-cloud-sleuth#144]
Working on a similar problem I encountered the need to set and have access to some variables that should live only for the Span of an operation. 
Eg: storing some header information that arrives from a jms message, without having access to a Session or Request scope.

I resolved to use a (Named)InheritableThreadLocal element inside a component, but this could be solved by adding a custom scope, that if a request comes from http overlaps the Request scope, but is available even if a request comes from a jms (or other) calls:

[Custom scope for JMS](http://stackoverflow.com/questions/15415688/spring-bean-custom-scope-jms)

**Comment by marcingrzejszczak** [comment]
After #711 , I think that this will now be solved via `ExtraFieldPropagation.set` and `ExtraFieldPropagation.get`. If the fields are not set in the whitelist of headers then they will not be propagated. WDYT @adriancole ?

**Comment by adriancole** [comment]
Depends.. if these variables are to be propagated out of process to the
next hop, yes. Tomorrow, I will update the description of
https://github.com/openzipkin/brave/pull/577 mentioning local propagation
as some have asked for things like span name for correlation purposes. What
is different is that this could be correlated data but not data necessary
or helpful to send to the next node (as it is not trace scoped)

**Comment by adriancole** [comment]
huge redo of the https://github.com/openzipkin/brave/issues/577 description complete

**Comment by marcingrzejszczak** [comment]
Anyways, I guess this problem will be moved to Brave. I'll close this one in favour of https://github.com/openzipkin/brave/pull/577
