### ISSUE TITLE
Create a RestTemplateSender with a custom RestTemplate

### ISSUE THREAD

**Issue by markmaxey** [spring-cloud/spring-cloud-sleuth#1440]
I need to be able to send spans to Zipkin over HTTPS.  This requires me to construct my own RestTemplate with certificates and custom HostnameVerifier.  I then need to inject this into a Sender.  I'd like to create my own Sender reusing RestTemplateSender with my own RestTemplate, e.g.,

```java
	@Bean public Sender httpsRestTemplateSender(
                        final ZipkinProperties zipkin,
                        final RestTemplate httpsRestTemplate) {
		return new RestTemplateSender(
                        httpsRestTemplate,
                        zipkin.getBaseUrl(),
                        zipkin.getEncoder());
	}
```

The problem is that the RestTemplateSender class and constructor are both package private. 
 :disappointed:

Is there another way of accomplishing the same goal?  The ZipkinRestTemplateCustomizer only allows me to modify an existing RestTemplate - not create my own.

Is the solution I'd like to take risky or unreasonable?

**Comment by marcingrzejszczak** [comment]
Why not use `ZipkinRestTemplateCustomizer` to customize it?

**Comment by markmaxey** [comment]
> Why not use `ZipkinRestTemplateCustomizer` to customize it?

Sorry - I updated my original question to address this at the same time you added your comment.

The ZipkinRestTemplateCustomizer only allows me to modify an existing RestTemplate - not create my own.  I need to create my own RestTemplate to support HTTPS.  The stuff I do during creation of the RestTemplate is not possible to tweak after it is created.

**Comment by marcingrzejszczak** [comment]
Hey @adriancole . What if `ZipkinRestTemplateCustomizer` could return a `RestTemplate` instead of customizing it? That way one could create their own `RestTemplate` or wrap the one that we've created in their own delegate. WDYT?

**Comment by markmaxey** [comment]
Thanks @marcingrzejszczak and @adriancole (in advance).  I'm good with any solution, but out of curiosity, what is the interest in keeping ZipkinRestTemplateCustomizer package private?

**Comment by marcingrzejszczak** [comment]
The interest is such that we don't want people to use all of the internals that we're building. Once we make sth public we can't modify it, extend it or remove it. That's a terrible support burden for us.

**Comment by markmaxey** [comment]
Thanks @marcingrzejszczak - it is something I should probably consider when writing my own APIs.

**Comment by marcingrzejszczak** [comment]
Oh definitely. You should always start with package private classes and make them public only if it is absolutely necessary.

**Comment by markmaxey** [comment]
Thanks @marcingrzejszczak!  I reviewed the changeset and it looks good.  Do you think anything in the documentation needs to be updated?
