### ISSUE TITLE
Qualified string for the Zipkin localServiceName

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#1441]
Right now, sleuth injects this to configure the tracer. There could be components that need access to this value before the tracer is built, and this is a little awkward:

```java
@Value("${spring.zipkin.service.name:${spring.application.name:default}}") String serviceName
```

Maybe an qualifier like `@LocalServiceName String` could be easier? wdyt?

The use case is setting up secondary sampling for Netflix, which needs access in a tracing customizer.

**Comment by marcingrzejszczak** [comment]
Absolutely, makes perfect sense
