### ISSUE TITLE
Does someone implement Jaeger with Spring Cloud Gateway?

### ISSUE THREAD

**Issue by nicorbes** [spring-cloud/spring-cloud-sleuth#1445]
We are re-building our software platform using a microservice architecture approach.

Most of it using **Spring Boot** libraries, and for our entry points we are using **Spring Cloud Gateway** which can be easily integrated with **Jaeger** to have tracing in the platform.

We do that using the following Maven dependency:
```
<dependency>
    <groupId>io.opentracing.contrib</groupId>
    <artifactId>opentracing-spring-jaeger-cloud-starter</artifactId>
    <version>2.0.3</version>
</dependency>
```
And it is working pretty well, we can see the trace on the **Jaeger UI** web console.

The problem now is how to send the tracking information to the next inner service in the platform to have every service correlated.

Any ideas?

We have tried to inject the tracking information as HTML Headers using a `GlobalFilter` but it is using the incoming request and we need to put them on the downstream request... any clue on how to override the `HTTPClient` used underneath?

Thanks in advance!

**Comment by devinsba** [comment]
I'm pretty sure this issue belongs on the `opentracing-spring-jaeger-cloud-starter` repo. This isn't a sleuth issue
