### ISSUE TITLE
[Question] Why does ReactorSleuth scan all beans for each call?

### ISSUE THREAD

**Issue by martinvisser** [spring-cloud/spring-cloud-sleuth#1449]
I've been running some CPU profiling on our application and I noticed that during those runs ~3% of CPU self time goes to `org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType ()`. Searching for the Forward Calls I end up with this:
![reactor-sleuth](https://user-images.githubusercontent.com/3170236/65229729-09dadd00-dacd-11e9-919f-c94a1b528803.png)

It doesn't look like much in the complete perspective of the profiling, but I'm wondering why this is done in this way.

I would expect that in `org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth#scopePassingSpanOperator` `beanFactory.getBean(Tracing.class)` could be done once for example. In `org.springframework.cloud.sleuth.instrument.reactor.SpanSubscriptionProvider` the `Tracing` bean is only loaded once.

Running Spring Boot 2.1.8.RELEASE, with Spring Cloud Sleuth 2.1.3.RELEASE.

**Comment by marcingrzejszczak** [comment]
Thanks for the pointer, now we're caching that instance.
