### ISSUE TITLE
ExtraFieldCustomizer is ignored unless either propagation-keys or baggage-keys property is set

### ISSUE THREAD

**Issue by oiavorskyi** [spring-cloud/spring-cloud-sleuth#1454]
In the context of a standalone application the `spring.sleuth.propagation-keys` and `spring.sleuth.baggage-keys` properties are most likely enough to configure extra fields propagation. When creating a Spring Boot autoconfiguration library, however, it is useful to be able to add extra fields without overriding the properties above. Support for `brave.propagation.ExtraFieldCustomizer` added in Greenwich.SR3 release makes it possible to do so. Unfortunately, the customization is skipped unless at least one of the propagation properties has a value. The code in `TraceAutoConfiguration.sleuthPropagation()` is clear about it:
```java
if (sleuthProperties.getBaggageKeys().isEmpty()
	           && sleuthProperties.getPropagationKeys().isEmpty()) {
	return B3Propagation.FACTORY;
}
```
The workaround for a library developer is to add a bogus value for `spring.sleuth.propagation-keys` if it is not set by the host application.

The [sample application](https://github.com/spring-cloud/spring-cloud-sleuth/files/3663909/extra-field-propagation-customization.zip) reproduces the issue with the tests.

**Comment by adriancole** [comment]
I think probably adding to the if `!extraFieldCustomizers.isEmpty()` should do it. feel free to raise a PR, just make sure there's a unit test.
