### ISSUE TITLE
Unable to use spring-cloud-sleuth with weblogic jms

### ISSUE THREAD

**Issue by martin-mucha** [spring-cloud/spring-cloud-sleuth#1458]
Weblogic jms ConnectionFactory impements both XAConnectionFactory and ConnectionFactory. In the latest release of sleuth this wont work properly, and while we want to use just ConnectionFactory, we will get LazyXAConnectionFactory autowired, because sources does not cover this combination.

You have already fix for this in master from march, commit: e099b6d9f40e7ac5afab58f77ccdf7773b1116a8

could this be cherry-picked into release branch? This blocks us from updating to newest spring/sleuth. If it's not possible, could you offer some workaround?

**Comment by marcingrzejszczak** [comment]
Please upgrade to `2.2.0.RC2`. `2.2.0.RELEASE` is right around the corner.

**Comment by alfonz19** [comment]
thanks.
