### ISSUE TITLE
Kafka ProducerListener doesn't contain trace information

### ISSUE THREAD

**Issue by vaclavnemec** [spring-cloud/spring-cloud-sleuth#1459]
I have a simple app here https://github.com/vaclavnemec/kafka-sleuth-problem

I am registering a bean of type ProducerListener and every time I send a message to Kafka I log it. There is no trace information in the log. The trace information is correctly propagated to the headers in Kafka.

I have raised a StackOverflow question, but so far no answers
https://stackoverflow.com/questions/58226540/why-isnt-kafka-producerlistener-logging-trace-id-and-span-id

Is this a bug?

**Comment by marcingrzejszczak** [comment]
No, you haven't turned on sampling. Please set `spring.sleuth.probability=1.0` as described in the documentation and the readme.

**Comment by vaclavnemec** [comment]
I set the property 'spring.sleuth.sampler.probability' to 1.0 and the messages are still not being logged. I tried to add 'spring.sleuth.probability' also but it looks that you meant the other one. I updated the sample project. Am I doing anything wrong?

**Comment by marcingrzejszczak** [comment]
Can you show your logs after setting this?

**Comment by vaclavnemec** [comment]
The debug log is here https://github.com/vaclavnemec/kafka-sleuth-problem/blob/master/test

I noticed that there is a sampler @Bean in TraceAutoConfiguration: Sampler.NEVER_SAMPLE and another sampler @Bean in SamplerAutoConfiguration that uses the property which you mentioned. The problem is that the one from TraceAutoConfiguration is created, thus it never samples.

I created a branch 'workaround'  in my little project and I explicitly create a sampler bean Sampler.ALWAYS_SAMPLE and the tracing started to work.

https://github.com/vaclavnemec/kafka-sleuth-problem/tree/workaround

**Comment by marcingrzejszczak** [comment]
So the thing is that you have the sleuth starter only (without zipkin), that's why I'm general you don't need to sample anything cause you're not sending the spans anywhere. Creation of the sampler bean is a good practice since you have some custom logic that requires you to sample even though you're not sending the span anywhere

**Comment by vaclavnemec** [comment]
We are actually planning to use some sort of visualization of tracing and we are not sure if Zipkin will be the one.

How is sampling related to the fact that the trace id is missing in logs? Here it clearly says that the traces appear in logs and spans are by default non-exportable:
https://cloud.spring.io/spring-cloud-sleuth/reference/html/#sampling-in-spring-cloud-sleuth

With all respect, defining a sampler bean looks like a workaround. If I export the spans, I would like to set the sampling based on my needs and not to ALWAYS_SAMPLE all the time.

Are you sure this one is not a bug or a limitation?

**Comment by adriancole** [comment]
data (like kafka info) is only recorded when sampled. recent release of sleuth now reads the sampling property even if the zipkin dep is not on the classpath. please re-open if you are using latest sleuth 2.2.3 and there's still question.
