### ISSUE TITLE
Improve span naming

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#146]
We had a chat about span naming and we agreed that for async the naming is completely useless e.g. `MvcAsync`.

We'll migrate towards the following pattern:

`protocol:address#fragment`

where `protocol` might be `http` , `messages`, `async`, `hystrix` etc.
`address` is sth like `/some/address`, `/events` or hystrix command key, async method name
`fragment` may contain additional labels

The naming has to be fixed for entries such as:
- MvcAsync (Async Controllers)
- SimpleAsyncTaskExecutors (@Async methods)
- @Scheduled methods
- pool-X-thread-Y (Hystrix?)

**Comment by adriancole** [comment]
I like the description in general. It seems to be missing some detail about how we got from here to there. For example, you could like a "before and after" of a couple span names and/or the motivation for doing this (guessing to make the bars on the ui look nicer?)

Motivation is important, as it helps understand if this is just to avoid looking up things in javascript, or something more fundamental. For example, we are introducing a type: `SpanName` vs a function to name a span. I suspect there's a reason for this.

**Comment by marcingrzejszczak** [comment]
The main motivation was to improve the naming in the UI. Until this change the names were really not self-explanatory. Especially for the async processing. Instead having any meaningful information they contained the thread name.

Old approach:
![old_zipkin_naming](https://cloud.githubusercontent.com/assets/3297437/12943851/4758da12-cfe4-11e5-8a84-7663ae61dc3c.png)

New approach:
![new_zipkin_naming](https://cloud.githubusercontent.com/assets/3297437/12943854/4cdf678a-cfe4-11e5-98fb-9705556fe919.png)

**Comment by adriancole** [comment]
Thanks for the rationale. I think the operation name is a bit overloaded
now, as we are encoding a lot into it. Particularly, the HTTP prefix looks
oddly like a uri, but it's not. The trailing tags look like odd, too. In
general, encoding things into names is a bit of a smell.. Maybe there's
another way?

Have you pinged others in distributed-tracing (or any other project) to see
how they handle this issue?

I suspect some change javascript to read tags. I recall appneta have a type
named layer or something that indicates http vs something. Pinpoint has an
async attribute in the span, which I assume is for reasons including UI. I
have noticed some "light" name encoding, too, ex uber's DBI prefixes the
name of the bound db driver (ex mysql) to the operation name. Long story
short is that we've a lot of folks who have been here before, worth asking
before inventing a new encoding format, yeah?

**Comment by marcingrzejszczak** [comment]
Wrote on the Google Group as you suggested - http://groups.google.com/group/distributed-tracing/t/b0fa6134deb9206?utm_source=digest&utm_medium=email
