### ISSUE TITLE
consider adding a bean name tag to async spans

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#1465]
When eventually coming up with https://github.com/spring-cloud/spring-cloud-sleuth/pull/1464, we found it very hard to figure out which executor was causing "async" spans. Since the controls are based on bean name, it seems a decent idea to have a bean name tag. Ex `spring.bean=fooExecutor`

**Comment by marcingrzejszczak** [comment]
That can be problematic cause the `async` span comes from a `TraceRunnable` or `TraceCallable`. Those are not beans really. I would have to extend the constructors to pass the creating object's name. However passing the bean name is also not easy. What I could do though is pass the class name of the object creating the runnable / callable. WDYT?

**Comment by adriancole** [comment]
I tried to look up what the original context was.. I think it was about the
name of the executor bean, that being something helpful to pinpoint what's
going on when there is no other info.

this continued more recently here
https://github.com/spring-cloud/spring-cloud-gcp/pull/2158

**Comment by marcingrzejszczak** [comment]
Getting the bean name can be tricky, doing the class name would be trivial

**Comment by marcingrzejszczak** [comment]
Ok, so one way of solving this is explicitly creating executor services with a provided name. Example below:

```java

	@Bean
	ExecutorService billingExecutor(BeanFactory beanFactory) {
		return new TraceableExecutorService(beanFactory, Executors.newFixedThreadPool(10), "Billing");
	}

	@Bean
	ExecutorService pointsExecutor(BeanFactory beanFactory) {
		return new TraceableExecutorService(beanFactory, Executors.newFixedThreadPool(10), "Points");
	}

	@Bean
	ExecutorService playerExecutor(BeanFactory beanFactory) {
		return new TraceableExecutorService(beanFactory, Executors.newFixedThreadPool(10), "Player");
	}

	@Bean
	ExecutorService inventoryExecutor(BeanFactory beanFactory) {
		return new TraceableExecutorService(beanFactory, Executors.newFixedThreadPool(10), "Inventory");
	}
```

another option is that e.g. someone uses a `AsyncTaskExecutor` implementation, e.g. `MyAsyncTaskExecutor`, I can by default not call the span `async` but `my-async-task-executor`. 

WDYT @adriancole @saturnism ?

**Comment by saturnism** [comment]
/cc @meltsufin @elefeint as well

iirc, for spring cloud gcp, the issue was more on hiding some executor pools from being instrumented/traced.

w/ `TraceableExecutorService`, is the idea that only`TraceableExecutorService` will be instrumented? and a regular executor no longer get instrumented automatically? (i do like this primarily because it's easily/explicit to differentiate which ones will have trace applied automatically).

**Comment by marcingrzejszczak** [comment]
All of the executor services still would be instrumented unless you set `spring.sleuth.scheduled.enabled=false` (the property is wrong - we'll fix it). If a service is already a `Traceable...` one then it won't get instrumented again.

The idea is such that if you explicitly create executor services, then you can provide proper names for the spans.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by saturnism** [comment]
Got it. I think it’s helpful and we can see where the async spans are coming from.

**Comment by elefeint** [comment]
In [`ExecutorBeanPostProcessor.postProcessAfterInitialization()`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/ed68a109c6f9874d57c71024cb7621a7a06afcd3/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/ExecutorBeanPostProcessor.java#L73), the bean name is known. So it should be doable, although a bit annoying, to propagate the bean name through helper methods into `TraceableExecutorService` and `TraceableScheduledExecutorService`.

**Comment by marcingrzejszczak** [comment]
That's a good idea. I'll check it out today
