### ISSUE TITLE
Update auto-configuration to use `@Configuration(proxyBeanMethods=false)`

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-sleuth#1473]
This is a performance enhancement.

See https://github.com/spring-projects/spring-boot/issues/9068

**Comment by adriancole** [comment]
thanks. I totally forgot what the "proxy thing" optimization was!

**Comment by marcingrzejszczak** [comment]
fixed via https://github.com/spring-cloud/spring-cloud-sleuth/commit/34f61908fde002ce8415c3fbefb2a70567746cd4
