### ISSUE TITLE
sleuth with spring-cloud-contract

### ISSUE THREAD

**Issue by HoffiMuc** [spring-cloud/spring-cloud-sleuth#1476]
I am a) trying out sleuth 2.2.0.BUILD-SNAPSHOT and b) spring-cloud-contract 2.2.0.M3
with messaging via rabbitMQ

When I have a contract that puts baggage in the header, e.g.:

```
def contractDsl = Contract.make {
        name "contractSourceName"
	label "contractSourceLabel"

	input {
		triggeredBy('methodFromContract()')
	}
	outputMessage {
		sentTo("minimal-SourceTo1")
		body('''{ "seq" : "42", "message" : "per contract fromSource", "modifications" : "" }''')
		headers {
			header('baggage_ddd', 'testBPDomain')
			header('baggage_bp', 'testBProcess')
			header('baggage_bpids', '43,44')
			messagingContentType(applicationJson())
		}
	}
}
```

The generated **Producer Verifier test fail**, as the received message does not have these put into the baggage, therefore missing in the header.

Is there a way to "intercept" the message and put things in?

Or should sleuth "somehow" investigate the header and put accordingly prefixed stuff into baggage "automagically" ?

Thanx for infos

**Comment by marcingrzejszczak** [comment]
Can you show your base class?

**Comment by HoffiMuc** [comment]
ha!

right hint ... I just forgot to put the sleuth headers in!

```
package com.hoffi.minimal.microservices.microservice.contractbaseclasses;

<snip>

@ActiveProfiles({"source", "unscheduled"})
@SpringBootTest(properties = {"--spring.autoconfigure.exclude="})
@AutoConfigureCache
@AutoConfigureMessageVerifier
public abstract class SourceBaseClass {
	@Autowired
	@Qualifier(SourceChannels.OUTPUT)
	MessageChannel sourceOutputMessageChannel;

	@Autowired
	SourceChannels sourceChannels;

	@Inject
	MessageVerifier messaging;

	@Autowired(required = false)
	Source source;

	@Before
	public void setup() {
		this.messaging.receive("minimal-SourceTo1", 100, TimeUnit.MILLISECONDS);
	}

	protected void methodFromContract() {
		MessageDTO referenceMessageDTO = DTOTestHelper.getPlainMessageDTO();

		referenceMessageDTO.seq = "42";
		referenceMessageDTO.message = "per contract fromSource";
		referenceMessageDTO.modifications = "";

		sourceChannels.sourceOutput()
				.send(MessageBuilder.withPayload(referenceMessageDTO)
                                                  // these lines I forgot to put in here
						.setHeaderIfAbsent("baggage_ddd", "testBPDomain")
						.setHeaderIfAbsent("baggage_bp", "testBProcess")
						.setHeaderIfAbsent("baggage_bpids", "43,44").build());
	}
}
```

thanx for the "hint"

(and I also want to send big big kudos ... it's impressive how fast and experienced you help us "half-intelligence-given" coders on issues, on stackoverflow et. al.
 Really! Often I ask myself how you and you colleagues get the work done you're supposed to do, with all the distracting and foolish things (like my issue here) that keep you from doin' your work. Impressive! Thanx again, and I apologize for the inconveniences...)

**Comment by marcingrzejszczak** [comment]
Wow, thanks for the kind words :)
