### ISSUE TITLE
Sleuth does not trace KStream Polling

### ISSUE THREAD

**Issue by msmsimondean** [spring-cloud/spring-cloud-sleuth#1480]
## Bug Description
Sleuth does not trace the polling operations performed by a KStream's Consumer.  Consequently, KStream Consumer's don't show up in Zipkin's Dependencies view.  

## Steps to Reproduce
1. Run the Producer and Consumer in the https://github.com/msmsimondean/kafka-tracing example codebase. 
2. Look at the Dependencies in the Zipkin UI.  Expected dependencies would be `kakfa-producer` -> `broker` -> `kafka-streams-consumer` but actual dependencies is this, with `kafka-streams-consumer` missing: ![image](https://user-images.githubusercontent.com/5443142/67762308-0c6e1200-fa3d-11e9-8a19-0f839e12cc3e.png)

## Expected Behaviour
The `kafka-streams-consumer` to show up in the Dependencies view.  

## Possible Root Cause
Brave provides an implementation of Kafka's [KafkaClientSupplier interface](https://github.com/axbaretto/kafka/blob/master/streams/src/main/java/org/apache/kafka/streams/KafkaClientSupplier.java) in the [TracingKafkaClientSupplier class](https://github.com/openzipkin/brave/blob/master/instrumentation/kafka-streams/src/main/java/brave/kafka/streams/TracingKafkaClientSupplier.java).  However Sleuth doesn't use TracingKafkaClientSupplier and instead uses Kafka's [DefaultKafkaClientSupplier implementation](https://github.com/axbaretto/kafka/blob/master/streams/src/main/java/org/apache/kafka/streams/processor/internals/DefaultKafkaClientSupplier.java).  This means that Sleuth doesn't trace the operation's performed by a Kakfa Stream's consumer(s) or producer(s), including consumer polling.  

NB Brave's 
[KafkaStreamsTracing.kafkaClientSupplier method](https://github.com/openzipkin/brave/blob/master/instrumentation/kafka-streams/src/main/java/brave/kafka/streams/KafkaStreamsTracing.java#L67) provides a way to create a new instance of TracingKafkaClientSupplier

**Comment by msmsimondean** [comment]
The following code is a work around for the issue: 

``` java
package example;

import brave.kafka.streams.KafkaStreamsTracing;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.kafka.config.StreamsBuilderFactoryBean;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
public class KafkaStreamsTracingBeanPostProcessor implements BeanPostProcessor {

    private final KafkaStreamsTracing kafkaStreamsTracing;

    @Override
    public final Object postProcessAfterInitialization(Object bean, final String beanName) {
        if (bean instanceof StreamsBuilderFactoryBean) {
            ((StreamsBuilderFactoryBean) bean).setClientSupplier(kafkaStreamsTracing.kafkaClientSupplier());
        }

        return bean;
    }

}
```

**Comment by marcingrzejszczak** [comment]
Care for a PR to fix it?

**Comment by marcingrzejszczak** [comment]
BTW looking at https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/SleuthKafkaStreamsConfiguration.java#L104 it seems that we do use the traced `KafkaClientSupplier` since 

```
public KafkaClientSupplier kafkaClientSupplier() {
    return new TracingKafkaClientSupplier(kafkaTracing);
  }
```

maybe this issue is obsolete?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by msmsimondean** [comment]
@marcingrzejszczak looks like you're correct, the issue is obsolete. The KafkaStreamsBuilderFactoryBeanPostProcessor class didn't exist in the version of Spring Cloud Sleuth I was using.  I've upgraded to `Hoxton.RELEASE` and now the class does exist and is working as intended.  Thanks
