### ISSUE TITLE
Conflicting remoteServiceNames for Kafka

### ISSUE THREAD

**Issue by msmsimondean** [spring-cloud/spring-cloud-sleuth#1481]
Sleuth's [TracingChannelInterceptor](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptor.java#L91) uses a remoteServiceName of `broker` whereas other parts of Sleuth's Kafka integration use a remoteServiceName of `kafka`, which is inherited from Brave's [KafkaTracing](https://github.com/openzipkin/brave/blob/master/instrumentation/kafka-clients/src/main/java/brave/kafka/clients/KafkaTracing.java#L51).  This leads to split Dependency views in Zipkin like this: 

![image](https://user-images.githubusercontent.com/5443142/67847255-6f71ae80-fafa-11e9-9f20-0f5b3a7d35dc.png)

**Comment by adriancole** [comment]
we should probably put some notes in here about how 415c809 works.. For example, this changes the service name from "broker" to "kafka" when you use a prefixed header. For example, if you use @Header(KafkaHeaders.MESSAGE_KEY)`, it will set it to that constant. However, if you don't use a message key, it will remain "broker"

cc @LtTempletonPeck @jeqo

**Comment by adriancole** [comment]
related to #1670 which I just opened about the larger concern
