### ISSUE TITLE
How to make spring-cloud-sleuth work with rxjava2?

### ISSUE THREAD

**Issue by wunaidage** [spring-cloud/spring-cloud-sleuth#1482]
I'm trying to integrate sleuth into this RxJava2 application. No luck at all. traceid is only logged in controller level. 
I checked the source code and found that this `sleuthRxJavaSchedulersHook` bean in class `RxJavaAutoConfiguration` is not initialized at all. and it seems because of the mismatch of `@ConditionalOnClass({RxJavaSchedulersHook.class})`
I cannot find this `RxJavaSchedulersHook.class` anywhere in the class path. RxJava2 marked it as deprecated in their document https://github.com/ReactiveX/RxJava/wiki/Plugins#rxjavaschedulershook
and the class is not even in the jar.
I saw some closed issues that people actually make spring-cloud-sleuth works with rxjava2. how?

**Comment by wunaidage** [comment]
seems `RxJavaSchedulersHook` only exists on rxjava 1.x https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/plugins/RxJavaSchedulersHook.java

**Comment by marcingrzejszczak** [comment]
You'll have to check Brave's RXjava2 integration (https://github.com/openzipkin/brave/tree/master/context/rxjava2) and act accordingly.
