### ISSUE TITLE
Lost spans & traces getting combined

### ISSUE THREAD

**Issue by Pojahn-Netent** [spring-cloud/spring-cloud-sleuth#1484]
Using Spring Cloud version Greenwich.RELEASE and Spring Boot version 2.2.1.RELEASE with Zipkin to test tracing in an asynchronous environment and I noticed two strange behaviours.

Steps to reproduce:

Run Zipkin. Perhaps with docker: 
`docker run -d -p 9411:9411 openzipkin/zipkin`

Download this sample project:
https://drive.google.com/file/d/1joVwG4-HU9UJaOP5dAOjPWvGB8e8tUoD/view

Run the main method of classes `ZipkinService1Application`, `ZipkinService2Application`, `ZipkinService3Application` and `ZipkinService4Application`.

Open a browser and call `http://localhost:8081/zipkin`. You should see _**one**_ new trace that looks something like this:
https://drive.google.com/file/d/13P4opLTEaCI8nXj5Bf-eWzVF9Rqzdtqp/view
This is correct and as expected. 

Call `http://localhost:8081/zipkin/async`. _You should now have two new traces. The expected result is **one** new trace_. The first trace doesn't contain the spans of `zipkin-server3`, because those spans got their own trace. 

There is an other bug: Call the two URLs above in quick succession. You should see some new traces now, one with _**11**_ spans. That's because the some of the spans created by the two requests somehow got combined. This in unexpected and I feel like this shouldn't happen.

Implementation of `/zipkin/`:
```java
webClient.get().uri("http://localhost:8082/zipkin2").exchange().block();
webClient.get().uri("http://localhost:8083/zipkin3").exchange().block();
webClient.get().uri("http://localhost:8084/zipkin4").exchange().block();
```
Implementation of `/zipkin/async/`:
```java
webClient.get().uri("http://localhost:8082/zipkin2").exchange()
    .flatMap(clientResponse -> webClient.get().uri("http://localhost:8083/zipkin3").exchange())
    .flatMap(clientResponse -> webClient.get().uri("http://localhost:8084/zipkin4").exchange())
    .block();
```

Are these bugs or is there something I don't understand?

**Comment by marcingrzejszczak** [comment]
Boot 2.2.1 is incompatible with Greenwich. You have to use Hoxton i.e. Sleuth 2.2.0

**Comment by Pojahn-Netent** [comment]
Tested with Hoxton.RC1. Works perfect!
