### ISSUE TITLE
LazyTraceThreadPoolTaskScheduler.getScheduledThreadPoolExecutor() cause associated ScheduledThreadPoolExecutor shutdown

### ISSUE THREAD

**Issue by evilnull** [spring-cloud/spring-cloud-sleuth#1485]
Last day I found that some `@Scheduled` method not run in my application. After looking up the problem, I found out that the thread pool was closed. Finally I find this is caused by Spring Cloud Sleuth 2.2.0.M3.  

`LazyTraceThreadPoolTaskScheduler.LazyTraceThreadPoolTaskScheduler()` method return a new `LazyTraceScheduledThreadPoolExecutor` instance when `executor` is not a `ScheduledThreadPoolExecutor` instance as below show:
```java
@Override
public ScheduledThreadPoolExecutor getScheduledThreadPoolExecutor()
		throws IllegalStateException {
	ScheduledThreadPoolExecutor executor = this.delegate
			.getScheduledThreadPoolExecutor();
	if (executor instanceof LazyTraceScheduledThreadPoolExecutor) {
		return executor;
	}
	return new LazyTraceScheduledThreadPoolExecutor(executor.getCorePoolSize(),
			executor.getThreadFactory(), executor.getRejectedExecutionHandler(),
			this.beanFactory, executor);
}
```
Be careful the new `LazyTraceScheduledThreadPoolExecutor` instance hold a reference of the `executor` object (`'delegate'` in `LazyTraceScheduledThreadPoolExecutor` class).

`LazyTraceScheduledThreadPoolExecutor` class override `finalize()` method to invoke delegate's `finalize()` method. 
```java
@Override
@Deprecated
public void finalize() {
	ReflectionUtils.invokeMethod(this.finalize, this.delegate);
}
```

When `LazyTraceScheduledThreadPoolExecutor` instance is no longer to use, `finalize()` method will be invoked and then the `delegate`'s  `finalize()` method also be invoked. But `delegate` is a shared object and still in use. 

So this problem occurs when the `LazyTraceThreadPoolTaskScheduler.LazyTraceThreadPoolTaskScheduler()` is called. Unfortunately this happens when use spring-websocket 5.2.0.

**Comment by marcingrzejszczak** [comment]
> LazyTraceThreadPoolTaskScheduler.LazyTraceThreadPoolTaskScheduler() method return a new LazyTraceScheduledThreadPoolExecutor instance when executor is not a ScheduledThreadPoolExecutor instance as below show:

That's actually not true, cause the executor is of `ScheduledThreadPoolExecutor` type.

`ScheduledThreadPoolExecutor executor = this.delegate.getScheduledThreadPoolExecutor();`

Nonetheless this:

> When LazyTraceScheduledThreadPoolExecutor instance is no longer to use, finalize() method will be invoked and then the delegate's finalize() method also be invoked. But delegate is a shared object and still in use.

is still true. Since it's a shared object we should not finalize it. I'll remove wrapping of that method.

**Comment by evilnull** [comment]
I'm sorry. It's a type error.

> `LazyTraceThreadPoolTaskScheduler.LazyTraceThreadPoolTaskScheduler()` method return a new `LazyTraceScheduledThreadPoolExecutor` instance when `executor` is not a `ScheduledThreadPoolExecutor` instance as below show:

`ScheduledThreadPoolExecutor` should be `LazyTraceScheduledThreadPoolExecutor`. I just want to describe the method details.

**Comment by evilnull** [comment]
I checked your fix code and found that the bug still exists.

LazyTraceScheduledThreadPoolExecutor.finalize() after fix:
```java
@Override
@Deprecated
public void finalize() {
	super.finalize();
}
```
`super.finalize()` actually `java.util.concurrent.ThreadPoolExecutor.finalize()` method that calls the `shutdown()` method next.
```java
protected void finalize() {
    SecurityManager sm = System.getSecurityManager();
    if (sm == null || acc == null) {
        shutdown();
    } else {
        PrivilegedAction<Void> pa = () -> { shutdown(); return null; };
        AccessController.doPrivileged(pa, acc);
    }
}
```
Because `LazyTraceScheduledThreadPoolExecutor` class override `shutdown()` method
```java
@Override
public void shutdown() {
    this.delegate.shutdown();
}
```
So, the call chain is: `LazyTraceScheduledThreadPoolExecutor.finalize()` -> `ThreadPoolExecutor.finalize()` -> `LazyTraceScheduledThreadPoolExecutor.shutdown()`.
Finally `ScheduledThreadPoolExecutor` instance still shutdown.

**Comment by marcingrzejszczak** [comment]
Ah true, good point!

**Comment by marcingrzejszczak** [comment]
Can you file the pr against branch 2.1.x?

**Comment by evilnull** [comment]
Of course, it's done.

**Comment by marcingrzejszczak** [comment]
You've got to sign the cla

**Comment by evilnull** [comment]
done
