### ISSUE TITLE
Subsequence requests sharing previous traceId after request with invalid url

### ISSUE THREAD

**Issue by addozhang** [spring-cloud/spring-cloud-sleuth#1492]
**Describe the bug**

1.3.6.RELEASE

There is a request with invalid url like `https://zuul:9999/serviceA]]>><`, the framework throws exception "Caused by: java.lang.IllegalArgumentException: Illegal character in path xxxx".

Subsequence requests handled by **same worker thread** are sharing same traceId.

**Sample**

Reproducing: 
1. start a zuul with config `server.tomcat.max-threads=1`
2. fire request with url `https://localhost:9999/serviceA]]>><`. 
3. send normal requests with url `https://localhost:9999/serviceA/info`

Then, you will find the subsequence requests sharing trace id as bad one.

**Cause**
In line https://github.com/spring-cloud/spring-cloud-sleuth/blob/1.3.x/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/zuul/TracePreZuulFilter.java#L88, it throws exception when invoking `URI#create()` and does not close new opened span.

**Comment by marcingrzejszczak** [comment]
We don't support that version of Sleuth anymore, please upgrade.
