### ISSUE TITLE
additional-skip-pattern is invalid

### ISSUE THREAD

**Issue by book-yao** [spring-cloud/spring-cloud-sleuth#1494]
add additional-skip-pattern is invalid，even if i create a bean as ClientSampler.NAME, but not run into this class's method 'trySample'

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? Can you also provide any meaningful information about the used versions? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by book-yao** [comment]
1.versin is _2.0.0.RELEASE_
2.**example**  ：
`public class MySleuthClientSampler extends HttpSampler {
  private final Pattern pattern;

  MySleuthClientSampler(SkipPatternProvider provider) {
    this.pattern = provider.skipPattern();
  }

  @Override
  public <Req> Boolean trySample(HttpAdapter<Req, ?> httpAdapter, Req req) {
    String url = httpAdapter.path(req);
    boolean shouldSkip = this.pattern.matcher(url).matches();
    if (shouldSkip) {
      return false;
    }
    return null;
  }
}`

**bean code**：
`@Bean(name = ClientSampler.NAME)
	@Primary
	@Order(Ordered.HIGHEST_PRECEDENCE + 1)
	public HttpSampler mySleuthClientSampler(SkipPatternProvider provider){
		return new MySleuthClientSampler(provider);
	}`

**setting**:
`  sleuth:
    sampler:
      probability: 1.0
    web:
      additional-skip-pattern: "/hi2"`
3.**describe**
I debug at method _trySample_, but restTemplete(bean) as client to invoke http method never debug into line.
I did not want to report client that contain "/hi2", and _additional-skip-pattern_ is invalid.
4. **run program**
sample is _spring-cloud-sleuth-sample-zipkin_
![image](https://user-images.githubusercontent.com/18388508/69594901-b5a62900-1038-11ea-95b5-5e8c8aa9bba3.png)

5.env is spring boot 2.0.3.RELEASE integrate spring cloud sleuth, so match sleuth's version is 2.0.0.RELEASE

**Comment by book-yao** [comment]
and if create a bean as **ServerSampler.NAME**, and i invoke  http（GET）that controller give ，will debug into method **trySample**,so  as server is normal ，just as client is invalid .
if  not create a bean as client by myself, just set **additional-skip-pattern: "/hi2"**,also is invalid.

**Comment by marcingrzejszczak** [comment]
Please use the latest stable release begin. Sleuth 2.0.0 is old
