### ISSUE TITLE
Don't check local keys in if

### ISSUE THREAD

**Issue by ByJacob** [spring-cloud/spring-cloud-sleuth#1498]
**Describe the bug**
When bean Propagation.Factory is created don't check if have sleuthProperties.getLocalKeys() in properties

**Sample**
- use the version 2.2.0.RELEASE in spring sleuth
- in application properties set `spring.sleuth.local-keys=tmp_key`
- set variable for span - `ExtraFieldPropagation.set("tmp_key", "something");`
- try read variable - `ExtraFieldPropagation.get(tmp_key)`
-- read value is null

[Bug in code](https://github.com/spring-cloud/spring-cloud-sleuth/blob/f80d5b00d7b4806bea5ff9dc2d85a5c9dc01f717/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java#L153)

**Comment by marcingrzejszczak** [comment]
Hello, when you created the issue via the issue template you had the following template generated

```
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.
```

Can you please read it again and update your issue description?

**Comment by ByJacob** [comment]
Update issue

**Comment by marcingrzejszczak** [comment]
Ok, are you willing to create a pull request with a test that shows that the current implementation is broken and write a fix for this issue?

**Comment by ByJacob** [comment]
Yes, i can create it

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-sleuth/pull/1499
