### ISSUE TITLE
Integration with GCP PubSub

### ISSUE THREAD

**Issue by mauraborean** [spring-cloud/spring-cloud-sleuth#1500]
Hi!

I'm using Spring Sleuth in a Spring Boot project and I'd like to include received PubSub events in my metrics. I've read that is it possible to trace RabbitMQ, Kaftka, JMS messages, but I'm having some trouble finding some integration for PubSub.

**Describe the solution you'd like**
I'd like to have some guidance on how to trace this events =) or know if there's an integration possible or in the way.

**Describe alternatives you've considered**
I tried to intercept the method that is executed when the events are received using AspectJ, but it was not possible (at least for me)

**Comment by marcingrzejszczak** [comment]
Why won't you file this issue in Spring Cloud GCP so that they instrument it there?
