### ISSUE TITLE
skipPattern property doesn't consider a potential contextPath

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [spring-cloud/spring-cloud-sleuth#1504]
Using Spring Boot 2.1.7 using https://github.com/openzipkin/sleuth-webmvc-example sample but packaged as a war, call on /actuator/ generate traces which are not skipped by default pattern org.springframework.cloud.sleuth.instrument.web.SleuthWebProperties.DEFAULT_SKIP_PATTERN

In addition org.springframework.cloud.sleuth.instrument.web.TraceWebAutoConfiguration.ActuatorSkipPatternProviderConfig should also consider contextPath.

**Sample**
https://github.com/openzipkin/sleuth-webmvc-example but changed to works deployed as war.

**Comment by marcingrzejszczak** [comment]
Is the problem still there with the latest version of sleuth and boot? 2.2.0 and 2.2.1

**Comment by EstebanDugueperoux2** [comment]
Indeed, it is fixed with last release.
