### ISSUE TITLE
Tag HTTP requests with http.url, remote hostname, IP and port

### ISSUE THREAD

**Issue by csabakos** [spring-cloud/spring-cloud-sleuth#1514]
**Is your feature request related to a problem? Please describe.**
I noticed that HTTP requests (for instance those made through `WebClient`) are not tagged with `http.url` and the remote address by default. This makes it hard to understand what peer the service is communicating with (especially if the peer is not instrumented). Similarly, WebFlux requests are not tagged with the remote address unless the `X-Forwarded-For` header is present.

**Describe the solution you'd like**
HTTP requests should be tagged with `http.url` and the remote address (hostname, IP, port) by default.

**Describe alternatives you've considered**
If there are concerns around the data size associated with spans and/or the cardinality of these tags, then perhaps we could make this opt-in by setting `spring.sleuth.web.extra-tags=true` or something similar, rather than enabling by default.

**Additional context**
I would be happy to put in a pull request, but wanted to get some opinions first. Should this be done by default, or in an opt-in manner, or not at all? If by default, then should the new tags be added by `brave-instrumentation-http` by default (so that it applies to everything that uses brave), or just by the Sleuth `Http{Client/Server}Parser`?

**Comment by marcingrzejszczak** [comment]
Can you show a sample that replicates this issue? If you set the `spring.sleuth.http.legacy.enabled` to `true` then you get all the tags. Example from `org.springframework.cloud.sleuth.instrument.web.client.integration.WebClientTests`


```java
@TestPropertySource(properties = { "spring.sleuth.http.legacy.enabled=true",
		"spring.application.name=fooservice", "feign.hystrix.enabled=false",
		"spring.sleuth.web.client.skip-pattern=/skip.*" })
```

the first test reports a span with the following characteristics

```
"http.host" -> "localhost"
"http.method" -> "GET"
"http.path" -> "/notrace"
"http.url" -> "http://localhost:45635/notrace"
```

**Comment by csabakos** [comment]
@marcingrzejszczak The `legacy` keyword in `spring.sleuth.http.legacy.enabled` deterred me from using it. It seems like something that will get killed off eventually.

If this is not the case, then setting `spring.sleuth.http.legacy.enabled=true` solves my problem, however if `spring.sleuth.http.legacy.enabled` is truly a legacy feature that will be eliminated at some point, then I think we should add `http.url` tagging to the "non-legacy" code path as well.

**Comment by marcingrzejszczak** [comment]
Legacy means the pre brave time. If you want this to be turned on by default convince the Brave team in their project

**Comment by csabakos** [comment]
It looks like this was discussed in https://github.com/openzipkin/brave/pull/828 and the outcome was that it should not be enabled by default.

**Comment by merusso** [comment]
These properties have been de-supported in Spring Cloud 2020 (#1564). What's the recommended way to set these tags now?

**Comment by marcingrzejszczak** [comment]
You can use the `HttpRequestParser` and `HttpResponseParser` beans where you can set arbitrary tags

**Comment by merusso** [comment]
Thanks! After your tip, I found the relevant documentation here:

- https://docs.spring.io/spring-cloud-sleuth/docs/3.0.1/reference/htmlsingle/#how-to-cutomize-http-client-spans
- https://docs.spring.io/spring-cloud-sleuth/docs/3.0.1/reference/htmlsingle/#how-to-cutomize-http-server-spans
