### ISSUE TITLE
sleuth "traceid" and "spanid" is not generating in the logs of Spring batch multithreaded step.

### ISSUE THREAD

**Issue by R-Kishore** [spring-cloud/spring-cloud-sleuth#1518]
**Describe the bug**
In our spring batch application we are using multiThreaded Step by using ThreadPoolTaskExecutor.
  for logging we are using spring cloud sleuth component.
  The logs generated  by the multithreaded step does not have "traceid" and "spanid".

how can we customise  and set the ThreadPoolTaskExecutor in step builder factory to generate "traceid" and "spanid" in the logs. 

**Sample**
     ThreadPoolTaskExecutor taskExecutor = new ThreadPoolTaskExecutor();
     taskExecutor.setCorePoolSize(7);
     taskExecutor.setMaxPoolSize(10);
     taskExecutor.afterPropertiesSet();

     Step readAndProcessStep = stepBuilderFactory.get(CSV_FILE_PROCESS_STEP)
         .<InputDto, OutputDto>chunk(100)
         .reader(itemReader)
         .processor(readAndExecuteProcessor)
         .writer(batchDbWriter)
         .faultTolerant()
         .skip(FlatFileParseException.class)
         .skipLimit(performanceProps.getSkipLimit())
         .listener(itemReaderListener)
         .listener(customStepListener())
         .listener(executionContextPromotionListener())
         .taskExecutor(taskExecutor)
         .throttleLimit(6)
         .build();

**Comment by marcingrzejszczak** [comment]
If `ThreadPoolTaskExecutor` is a bean you should not need to do anything. If it's not a bean, you can wrap it in a `LazyThreadPoolTaskExecutor`.

**Comment by zahidMed** [comment]
@marcingrzejszczak 
This is late, but I think this project can help you propagate the traceId and spanId through spring-batch
https://github.com/zahidMed/spring-batch-context
