### ISSUE TITLE
How to trace hbase requests?

### ISSUE THREAD

**Issue by duwanqiebi** [spring-cloud/spring-cloud-sleuth#1520]
I want to trace hbase request in one web request.

How can I  to trace hbase request in application  by using spring-cloud-starter-zipkin?

**Comment by marcingrzejszczak** [comment]
You would have to write your own implementation of a tracer for hbase. We don't support it out of the box. Please read the documentation of the OpenZipkin Brave project first and then you can consider adding the tracing mechanism in your project. I'll close this issue for now and if there are more people interested we can think of reopening it one day
