### ISSUE TITLE
Failed to process import candidates for configuration class

### ISSUE THREAD

**Issue by vivekthangathurai** [spring-cloud/spring-cloud-sleuth#1521]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 
I have added the following dependency into my pom in one of the maven modules
```
<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-sleuth-zipkin</artifactId>
                         <version>1.2.6.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-feign</artifactId>
                         <version>1.2.6.RELEASE</version>
			<exclusions>
			<exclusion>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-starter</artifactId>
			</exclusion>
			</exclusions>
		</dependency>
```

tests in another module using this module as dependency is failing when it uses @EnableAutoConfiguration

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by marcingrzejszczak** [comment]
Please 
* do not add versions by yourself, reuse the release train
* your Sleuth version is ancient, please upgrade to the latest one

Please go to start.spring.io and generate a fresh project from scratch including the zipkin dependencies to see how it should properly look like.
