### ISSUE TITLE
Spring Cloud Sleuth Propagation SupportsJoin Issue

### ISSUE THREAD

**Issue by huangydyn** [spring-cloud/spring-cloud-sleuth#1523]
**Describe**
Spring Cloud version Greenwich.SR4

**Sample**
use feign and sleuth, and config spring.sleuth.supports-join=false, parent spanid not correct during propagation.

Invoker 
traceId spanId parentSpanId 
eacdf1fa6276a833, eacdf1fa6276a833,null

Receiver
Get Http Header
x-b3-spanid, Value: 0ee7e9f326298f95
x-b3-parentspanid, Value: eacdf1fa6276a833
x-b3-traceid, Value: eacdf1fa6276a833

traceId spanId parentSpanId 
eacdf1fa6276a833, a3f53beaf4bcb48d, 0ee7e9f326298f95

The receiver parent spanid is not correct, it should be eacdf1fa6276a833 not 0ee7e9f326298f95, and x-b3-parentspanid has been ignored.

**Comment by marcingrzejszczak** [comment]
Please upgrade to the latest version and try again. `spring.sleuth.supports-join` is set to `true` by default. I have no idea how you send a request and what you're really doing. We had no issues reported for Feign for that matter.

**Comment by huangydyn** [comment]
sorry, I make a mistake in writing:  spring.sleuth.supports-join is set to false

**Comment by marcingrzejszczak** [comment]
Can you please create a sample that replicates this issue?

**Comment by huangydyn** [comment]
I just create a repo in github,  https://github.com/huangydyn/sleuth-demo     
refer to REAMME to start

**Comment by huangydyn** [comment]
I'll create in Brave. Thanks a lot
