### ISSUE TITLE
Add R2DBC support

### ISSUE THREAD

**Issue by deblockt** [spring-cloud/spring-cloud-sleuth#1524]
the purpose of this feature is to allow to postpone the execution time of the query in zipkin.

R2DBC provide a ProxyConnectionFactory, this proxy can be used to provide a zipkin (Open Tracing) support using a listener.

it can be fine to provide a spring-boot-r2dbc-zipkin-autoconfiguration jar to have an autoconfiguration around zipkin and r2dbc.

https://github.com/spring-projects-experimental/spring-boot-r2dbc/issues/71

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-sleuth/commit/181c789020063ac9e6fdf53d6ebab2ffb398d13c
