### ISSUE TITLE
ScheduledExecutorService is wrapped into TraceableExecutorService instead of TraceableScheduledExecutorService

### ISSUE THREAD

**Issue by u3r** [spring-cloud/spring-cloud-sleuth#1536]
When using spring to autowire a `ScheduledExecutorService` it gets wrapped (by the `ExecutorBeanPostProcessor` ) into a `TraceableExecutorService` when it **should** be wrapped into a `TraceableScheduledExecutorService` - it seems it is missing an extra `if (bean instanceof....` block to handle this case.

```java
// bean definition: 
@Bean()
   public ScheduledExecutorService createExecutorService(  ) {
      return Executors.newSingleThreadScheduledExecutor();
   }

//[...]
// usage:
 @Autowired
 private ScheduledExecutorService executor;
```
Result:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'SomeName': Unsatisfied dependency expressed through field 'executor'; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'createRegistrationExecutorService' is expected to be of type 'java.util.concurrent.ScheduledExecutorService' but was actually of type 'org.springframework.cloud.sleuth.instrument.async.TraceableExecutorService'
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'createRegistrationExecutorService' is expected to be of type 'java.util.concurrent.ScheduledExecutorService' but was actually of type 'org.springframework.cloud.sleuth.instrument.async.TraceableExecutorService'
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1297)
```

Whether this error actually occurs is dependent on the spring- and spring-cloud-starter-sleuth version:
* spring-boot 2.2.1 + Spring-cloud-sleuth 2.1.3 => problem occurs
* spring-boot 2.2.3 + Spring-cloud-sleuth 2.2.1 => problem is suppressed (but not solved) because `ExecutorBeanPostProcessor` does not proxy anything due to (probably) spring dynamic proxies

**Comment by marcingrzejszczak** [comment]
Meh, are you willing to add a pull request with a test to the 2.2.x branch?

**Comment by u3r** [comment]
@marcingrzejszczak I've tried for an hour to get the 2.2.x branch to build behind our company proxy but had no success. For someone with a buildable workspace it should be reproducible with the code quoted above and one or two breakpoints in `ExecutorBeanPostProcessor`

**Comment by marcingrzejszczak** [comment]
No problem, I'll check it out.
