### ISSUE TITLE
How to log custom propagated field with SLF4J?

### ISSUE THREAD

**Issue by boonware** [spring-cloud/spring-cloud-sleuth#1539]
I've been trying to figure out how to propagate a custom field alongside the standard trace and span IDs and have this custom field also logged by SLF4J in a Spring Boot application. Logging is performed via Lombok's `@Slf4j` annotation. It appears that many people have hit a similar problem and there does not seem to be a single, clearly documented procedure for implementing this capability. Indeed, the [documentation](https://cloud.spring.io/spring-cloud-sleuth/reference/html/#propagating-extra-fields) does not seem to align with some of the suggested approaches in various threads: [this](https://github.com/spring-cloud/spring-cloud-sleuth/issues/864) for example.

My attempt to implement this is as follows:
1. Custom configuration:
```
    @Bean
    Propagation.Factory propagationFactory() {
        return ExtraFieldPropagation.newFactory(B3Propagation.FACTORY, "my-custom-key");
    }
```
2. Properties:
```
spring.sleuth.log.slf4j.whitelisted-mdc-keys = my-custom-key
```
3. When handling a HTTP request or Kafka message where I want to log the trace/span context together with the new field:
```
ExtraFieldPropagation.set("my-custom-key",  "my-custom-value");
```

The above is my understanding from the docs, however I'm clearly doing something wrong here as the log statements do not include my custom field. Any guidance on how to get this right would be great. If I can get it working I'll deliver a PR to update the docs with a concise example.

**Comment by marcingrzejszczak** [comment]
Instead of 

```java
    @Bean
    Propagation.Factory propagationFactory() {
        return ExtraFieldPropagation.newFactory(B3Propagation.FACTORY, "my-custom-key");
    }
```

Please try

```yaml
spring.sleuth:
  log.slf4j.whitelisted-mdc-keys: 
    - my-custom-key
  propagation-keys:
    - my-custom-value
```

When you created your own propagation factory you're overriding this auto configuration

```java
@Bean
	@ConditionalOnMissingBean
	Propagation.Factory sleuthPropagation(SleuthProperties sleuthProperties) {
		if (sleuthProperties.getBaggageKeys().isEmpty()
				&& sleuthProperties.getPropagationKeys().isEmpty()
				&& extraFieldCustomizers.isEmpty()
				&& this.extraFieldPropagationFactoryBuilder == null
				&& sleuthProperties.getLocalKeys().isEmpty()) {
			return B3Propagation.FACTORY;
		}
		ExtraFieldPropagation.FactoryBuilder factoryBuilder;
		if (this.extraFieldPropagationFactoryBuilder != null) {
			factoryBuilder = this.extraFieldPropagationFactoryBuilder;
		}
		else {
			factoryBuilder = ExtraFieldPropagation
					.newFactoryBuilder(B3Propagation.FACTORY);
		}
		if (!sleuthProperties.getBaggageKeys().isEmpty()) {
			factoryBuilder = factoryBuilder
					// for HTTP
					.addPrefixedFields("baggage-", sleuthProperties.getBaggageKeys())
					// for messaging
					.addPrefixedFields("baggage_", sleuthProperties.getBaggageKeys());
		}
		if (!sleuthProperties.getPropagationKeys().isEmpty()) {
			for (String key : sleuthProperties.getPropagationKeys()) {
				factoryBuilder = factoryBuilder.addField(key);
			}
		}
		if (!sleuthProperties.getLocalKeys().isEmpty()) {
			for (String key : sleuthProperties.getLocalKeys()) {
				factoryBuilder = factoryBuilder.addRedactedField(key);
			}
		}
		for (ExtraFieldCustomizer customizer : this.extraFieldCustomizers) {
			customizer.customize(factoryBuilder);
		}
		return factoryBuilder.build();
```

**Comment by boonware** [comment]
```
spring.sleuth:
  log.slf4j.whitelisted-mdc-keys: 
    - my-custom-key
  propagation-keys:
    - my-custom-value
```
Is `my-custom-value` a typo?

**Comment by boonware** [comment]
I'm still not seeing the custom field logged to the console after I set its value with `ExtraFieldPropagation.set`. Do I also need to change the formatter for Slf4j?

**Comment by marcingrzejszczak** [comment]
Yeah it is, sorry. It should be the key name there

**Comment by marcingrzejszczak** [comment]
Did the provided solution help?

**Comment by boonware** [comment]
This worked nicely. I realized I also had to add a custom `src/main/resources/logback-spring.xml` to add my new fields to the log template. Thanks for the help. I have hit a separate issue now which I've tracked here: https://github.com/spring-cloud/spring-cloud-sleuth/issues/1543
