### ISSUE TITLE
Suggest W3C Trace Context compatibility

### ISSUE THREAD

**Issue by gerasimovv88** [spring-cloud/spring-cloud-sleuth#1540]
Hi!

I would like to use Spring Boot Sleuth Project to set up distributed tracing. 
But Sleuth use Brave library with B3Propagation, which includes headers like X-B3* and separated headers with SpanId, ParentSpanId, TraceId. 

And I would like to use Sleuth Project to perform distributed tracing by specification [W3C Trace Context](https://www.w3.org/TR/trace-context-1/) with fully included **traceparent** header, which is currently not supported as I see...
Exporters such as Zipkin are not used, headers only send to microservices.

Is this planned to be supported? 
Could you give me an advice to implement this correctly? 
I think, I should implement my own implementation of Brave interface **Propagation** with **Propagation.Factory**, **Injector** and **Extractor**

Thank you very much!

**Comment by adriancole** [comment]
It looks like late last year w3c has promoted the trace context thing to "Proposed Recommendation" which is almost a standard. There's a rough draft here which was awaiting stability in the spec as last year they were still changing things. In sleuth, you would use a Propagation component that swaps out B3, possibly with some sort of fallback as so few things are compatible with w3c traceparent. https://github.com/openzipkin/brave/pull/693

**Comment by gerasimovv88** [comment]
So, what have I to do to get W3C Trace Context integration? 
On my opinion, it’s about replacing B3Propagation with my own Propagation implementation, isn’t it?

**Comment by adriancole** [comment]
Concrete first step is to mention on that https://github.com/openzipkin/brave/pull/693 your use-case (ex exactly what you are doing that requires w3c headers as little if any software uses it right now). For example, w3c claims to support different vendors tracestate. Which are you working with?

Also, thumbsup the PR it as currently no one else is asking for this. A sense of demand helps justify the effort not just to build, but also maintain it.

Finally, if you are up to helping, you can make pull requests to that branch. This isn't required, but it would make it move faster as again, no one else is asking for this and doing work here displaces other work.

There's no action to take in this repo. Not even B3 is implemented here, so again, let's please move it to the correct issue.

**Comment by gerasimovv88** [comment]
Oh.. I saw, that you are already contributed this feature to openzipkin/brave. 
I understood, that implementation of W3C TraceContext propagation is not a Spring-Cloud-Sleuth responsibility, but openzipkin/brave. Let's hope they accept this soon.
Thank you!

**Comment by adriancole** [comment]
openzipkin/brave#693 is in progress. once finished, we'll add it here

**Comment by fzyzcjy** [comment]
Hi is there any updates - is this available now? Thanks!

**Comment by marcingrzejszczak** [comment]
Yes it is https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/project-features.html#features-context-propagation
