### ISSUE TITLE
Wrong contextual value in logs with Spring Cloud Stream

### ISSUE THREAD

**Issue by boonware** [spring-cloud/spring-cloud-sleuth#1543]
I have set up propagation and logging for a custom field as outlined in https://github.com/spring-cloud/spring-cloud-sleuth/issues/1539. When using this with Spring Cloud Stream and the Kafka binder, however, I encounter a problem.

```
@StreamListener("my-input-channel")
public void handleMessage(Message message) {
    ExtraFieldPropagation.set("my-key", message.getValue());
    log.info("Test");
    // Do stuff ...
}
```
With the above, I see a log message with the following context info:

> INFO [my-app, my-value] Test

That's great, it works. However, consider what happens when another message arrives with a new value. I expect the log to contain the new value for the context field, i.e. `my-value-2`, however, the log still contains `my-value` from before. Only when an exception is thrown by Spring later on in my code do I see the correct context value in the log:

> ERROR [my-app, my-value-2] 73 --- [[Ljava.lang.String;@7865899f.container-0-C-1]  o.s.i.h.LoggingHandler:182 : org.springframework.messaging.MessagingException ...

Any ideas what's going on here? I was under the impression that once I set the value for a log context field using `ExtraFieldPropagation` that this would be reflected immediately in the logs, given that the log message is produced from a new log context (new invocation of the @StreamListener method).

**Comment by boonware** [comment]
I've tested this against a HTTP controller and I see the same issue. The output of a few log statements that are called _after_ I have set the values for the extra propagation fields are **missing the fields**. At some point, say four or five log statements latter, the output starts to include the extra propagation fields. If I make a second request to the controller the first few log statements include the extra propagations values _from the previous_ request for again a few log statements. Is there a race condition here?

**Comment by marcingrzejszczak** [comment]
I haven't noticed such issues. Can you create a sample that replicates this?

**Comment by boonware** [comment]
@marcingrzejszczak I've pushed a simple Sleuth app here: https://github.com/boonware/sleuth-1543. Make a GET request to `localhost:8080/{propagationValue}` where `propagationValue` should be the value to be printed in the log context (and propagated). Weirdly enough, I can only get this to work if I send the extra propagation key as a HTTP header. Just using `ExtraFieldPropagation.set` in the controller method does not work. Any idea what I did wrong in the case?

**Comment by marcingrzejszczak** [comment]
Can you try setting the probability sampling to 1.0 ?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by boonware** [comment]
@marcingrzejszczak Setting the sampling rate to 1.0 did not fix the simple example I have here: https://github.com/boonware/sleuth-1543

**Comment by Babajide** [comment]
@marcingrzejszczak do you perhaps have a working example of logging extra/custom field in SLF4J?
I have a requirement where I need to include an HTTP header value as part of logging info.
example:

[x-service,5e4cb494c41c51df7bccbff915c21f71,7bccbff915c21f71,**FOO**,false]
I have not been able to get this to work for about 3 days, I have:

- Used logback settings as[logback-spring.xml](https://github.com/spring-cloud-samples/sleuth-documentation-apps/blob/master/service1/src/main/resources/logback-spring.xml)

-  set spring.sleuth.log.slf4j.whitelisted-mdc-keys
- set baggage-keys
- set ExtraFieldPropagation.set("x-b3-Request-ID", "Foo");

But no extra /custom field is logged.

Will appreciate your response.

**Comment by marcingrzejszczak** [comment]
There you go 

* commit modifying the logging https://github.com/spring-cloud-samples/sleuth-documentation-apps/commit/9c55edb3596e96e776dc35a052267f20b8483bcc 
* e.g. where the baggage is set https://github.com/spring-cloud-samples/sleuth-documentation-apps/blob/2.2.x/service1/src/main/java/io/spring/cloud/sleuth/docs/service1/Service2Client.java#L52

**Comment by marcingrzejszczak** [comment]
@boonware  I took your example and modified it a bit

.App
```java
package com.sleuth.test;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.client.RestTemplate;

@SpringBootApplication
public class App {

    public static void main(final String[] args) { // NOSONAR
        SpringApplication.run(App.class, args);
    }

    @Bean
    RestTemplate restTemplate() {
        return new RestTemplate();
    }
}
```

.Controller
```java
package com.sleuth.test;

import brave.Tracer;
import brave.propagation.ExtraFieldPropagation;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.context.request.async.DeferredResult;

@RestController
public class Controller {

	private static final Logger log = LoggerFactory.getLogger(Controller.class);

	private final Tracer tracer;
	private final RestTemplate restTemplate;

    public Controller(Tracer tracer, RestTemplate restTemplate) {
        this.tracer = tracer;
        this.restTemplate = restTemplate;
    }

    @RequestMapping(value = "/{propagationValue}", method = RequestMethod.GET)
	public DeferredResult<ResponseEntity> sleuthTest(@PathVariable(value = "propagationValue") String propagationValue) {
		DeferredResult<ResponseEntity> result = new DeferredResult<>();
		log.info("Hello [{}]", tracer.currentSpan().context().traceIdString());
		log.info("GET request for propagation value: {}", ExtraFieldPropagation.get("x-b3-foo"));
		for (int i = 0; i < 10; i++) {
			log.info(String.valueOf(i));
		}
        log.info("Response from httpbin [{}]", restTemplate.getForObject("https://httpbin.org/headers", String.class));
		result.setResult(new ResponseEntity<>("Sleuth test complete", HttpStatus.OK));
		return result;
	}

}
```

After running the app and sending a request, I got such response 

```
➜  1543 git:(master) ✗ http :8080/asd x-b3-foo:bar
HTTP/1.1 200 
Connection: keep-alive
Content-Length: 20
Content-Type: text/plain;charset=UTF-8
Date: Thu, 20 Feb 2020 08:35:38 GMT
Keep-Alive: timeout=60

Sleuth test complete
```

and in the logs I got

```
2020-02-20 09:35:38.094  INFO [sleuth-test,bar] 25886 --- [http-nio-8080-exec-2]  c.s.test.Controller:38 : Response from httpbin [{
  "headers": {
    "Accept": "text/plain, application/json, application/*+json, */*", 
    "Host": "httpbin.org", 
    "User-Agent": "Java/11.0.4", 
    "X-Amzn-Trace-Id": "Root=1-5e4e44d9-cf80425dff6304afe5fc55df", 
    "X-B3-Foo": "bar", 
    "X-B3-Parentspanid": "6affed90ea138d19", 
    "X-B3-Sampled": "0", 
    "X-B3-Spanid": "09a6abf83b917a55", 
    "X-B3-Traceid": "6affed90ea138d19"
  }
}
]
```

You can see that the field is there in the logs and in the headers that got sent to httpbin.
