### ISSUE TITLE
Zipkin RabbitMQ Sender fails to reconnect with RabbitMQ broker

### ISSUE THREAD

**Issue by sufiannazim** [spring-cloud/spring-cloud-sleuth#1547]
**Describe the bug**
RabbitMQ fails to reconnect with RabbitMQ broker on connection reset. RabbitConnectionFactoryBean in Spring AMQP, which is used in RabbitAutoConfiguration to configure ConnectionFactory for RabbitMQ, disables automatic connection recovery functionality provided by rabbit mq client library. Since, Spring AMQP has its own recovery mechanism, it disables connection recovery functionality provided by the client library. Issue was found in Spring Cloud Version: 2.x.

```
Dropped 18 spans due to AlreadyClosedException(connection is already closed due to connection error; cause: java.net.SocketException: Connection reset) com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; cause: java.net.SocketException: Connection reset? at 
com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:253) ~[amqp-client-5.4.3.jar!/:5.4.3]? at 
com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:422) ~[amqp-client-5.4.3.jar!/:5.4.3]? at 
com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:704) ~[amqp-client-5.4.3.jar!/:5.4.3]? at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:679) ~[amqp-client-5.4.3.jar!/:5.4.3]? at 
com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:669) ~[amqp-client-5.4.3.jar!/:5.4.3]? at zipkin2.reporter.amqp.RabbitMQSender$RabbitMQCall.publish(RabbitMQSender.java:260) ~[zipkin-sender-amqp-client-2.7.3.jar!/:na]? at 
zipkin2.reporter.amqp.RabbitMQSender$RabbitMQCall.doExecute(RabbitMQSender.java:255) ~[zipkin-sender-amqp-client-2.7.3.jar!/:na]? at 
zipkin2.reporter.amqp.RabbitMQSender$RabbitMQCall.doExecute(RabbitMQSender.java:247) ~[zipkin-sender-amqp-client-2.7.3.jar!/:na]? at 
zipkin2.Call$Base.execute(Call.java:379) ~[zipkin-2.9.3.jar!/:na]? at 
zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:286) ~[zipkin-reporter-2.7.3.jar!/:na]? at 
zipkin2.reporter.AsyncReporter$Builder$1.run(AsyncReporter.java:190) [zipkin-reporter-2.7.3.jar!/:na]?
```

**Comment by marcingrzejszczak** [comment]
Can you please read the issue template again

```
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.
```

and update your issue description with all the necessary data? Thank you.

**Comment by sufiannazim** [comment]
@marcingrzejszczak I have updated the issue description.

**Comment by marcingrzejszczak** [comment]
Why do you think that it disables anything?

```java
@Bean(ZipkinAutoConfiguration.SENDER_BEAN_NAME)
	Sender rabbitSender(CachingConnectionFactory connectionFactory,
			RabbitProperties config) {
		String addresses = StringUtils.hasText(this.addresses) ? this.addresses
				: config.determineAddresses();
		return RabbitMQSender.newBuilder()
				.connectionFactory(connectionFactory.getRabbitConnectionFactory())
				.queue(this.queue).addresses(addresses).build();
	}
```

We're reusing the existing connection factory. So we're not disabling anything really.

**Comment by sufiannazim** [comment]
RabbitAutoConfiguration creates that existing connection factory through RabbitConnectionFactoryBean class. As shown in the screenshot below, RabbitConnectionFactoryBean disables automatic connection recovery that Rabbit MQ client library provides out of the box. 

![image](https://user-images.githubusercontent.com/12127670/73804818-fafe7980-4792-11ea-8bae-29a4f12ae1d7.png)

**Comment by marcingrzejszczak** [comment]
You can create your own `ConnectionFactory`  bean and define whatever you want there. I don't see why we should assume that it's a Sleuth issue.

**Comment by sufiannazim** [comment]
Yes, user can create a custom ConnectionFactory for Zipkin sender. But, Spring Cloud Sleuth default configuration for Zipkin should ensure that the connection factory used for RabbitMQ have connection recovery support enabled.

**Comment by tomekstankowski** [comment]
I've experienced this issue in Spring Cloud 2021.0.4 and Spring Boot 2.7.4. I agree with @sufiannazim that it's an issue of Spring Sleuth. Most developers will use RabbitMQ Zipkin sender in conjunction with Spring AMQP autoconfiguration and won't be aware of the issue until it hits them. I think this should be documented at least.
