### ISSUE TITLE
SqsQueueMessageHandlerFactory.createQueueMessageHandler overrides super class method causing Jackson message converter not registered

### ISSUE THREAD

**Issue by jason2h** [spring-cloud/spring-cloud-sleuth#1566]
Hi there

I am trying to use Spring Cloud AWS to consumer SQS message, but found that Jackson  String to Object message converter was not registered by default.

It looked weird to me because `QueueMessageHandlerFactory.createQueueMessageHandler()` should register Jackson message converter by default. After some debugging, I found that actually `SqsQueueMessageHandlerFactory.createQueueMessageHandler()` overrides the behaviour of its superclass, which caused a bunch of logic not running (such as setting default message converter, argument resolvers, etc.)

Is there particular reason why `SqsQueueMessageHandlerFactory` is doing that? Or it's a bug?

**Comment by marcingrzejszczak** [comment]
Can you describe in more depth what exactly is problematic and how do you think it should be fixed?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by jason2h** [comment]
Spring SQS integration allows using `SqsListener` annotation to receive message, for example:
```
@SqsListener("order-queue")
public void receiveMessage(OrderPlaced order) {
    // ...
}
```
By default, Spring SQS integrates with Jackson to deserialise the String message to object like `OrderPlaced`. However, it does not work if Spring Sleuth is present.

When Spring Sleuth is in classpath, `TraceMessagingAutoConfiguration` is loaded and its `SqsQueueMessageHandlerFactory` kicks in and replaces the default factory. There's problem with `SqsQueueMessageHandlerFactory` implementation, because it overrides its superclass `createQueueMessageHandler()` method, which causes Jackson message converter not registered.

I hope I explained the problem well. Regarding the fix, I would consider calling `super.createQueueMessageHandler()` in Sleuth's `SqsQueueMessageHandlerFactory`.

**Comment by marcingrzejszczak** [comment]
Can you point me in Sleuth's Github code to the class that does this? Also, can you please tell me which version of Sleuth are you using?

**Comment by jason2h** [comment]
We are using Spring Sleuth 2.2.1. See:
https://github.com/spring-cloud/spring-cloud-sleuth/blob/c71d6ff0e2af4f57b58a27c626c94eb07257a456/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceMessagingAutoConfiguration.java#L491

**Comment by marcingrzejszczak** [comment]
Hey @jason2h, sorry for the delay. Are you willing to file a PR with a failing test / a fix? 

> I hope I explained the problem well. Regarding the fix, I would consider calling super.createQueueMessageHandler() in Sleuth's SqsQueueMessageHandlerFactory.

Where would you call the `super.createQueueMessageHandler()` ?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by jason2h** [comment]
@marcingrzejszczak sorry for the late response. Actually I have no idea about how to fix this. I suppose Sleuth `SqsQueueMessageHandlerFactory.createQueueMessageHandler()` needs to call `super.createQueueMessageHandler()` and then use decorator pattern to wrap the handler returned from super class. But I could be wrong because I am not familiar with the library.
Unfortunately I don't have plan to create a PR for the fix.

**Comment by tyagiarpit** [comment]
We are facing the same issue. And I agree with @jason2h. Or even better, if a bean of type `QueueMessageHandlerFactory` exists, use the bean to create an instance of `QueueMessageHandler` and wrap the instance of QueueMessageHandler using a decorator

**Comment by vachillo** [comment]
I am facing the same problem using `spring-cloud-openfeign`. With `spring-cloud-starter-sleuth` on the classpath, the feign client silently fails JSON unmarshalling and a null is returned. without it, feign client works as expected.

**Comment by marcingrzejszczak** [comment]
SQS support got dropped and should be continued in Spring Cloud AWS
