### ISSUE TITLE
Executor Bean with a final method might cause application to crash

### ISSUE THREAD

**Issue by plilja** [spring-cloud/spring-cloud-sleuth#1569]
**Description**
If I have an Executor bean with a final method on it. That bean will be wrapped in the class ExecutorBeanPostProcessor with a CGLIB proxy. Later calls to the final method might cause the application to crash. 

It looks like you check for final methods in ExecutorBeanPostProcessor#anyFinalMethods. But it only checks the Executor interface. Maybe it's as simple as changing to bean.getClass() in the call to that method?

**Sample**
Here is a sample project that triggers the problem. It registers a QueuedThreadPool Bean with a JettyServletWebServerFactory. When the Jetty startup process attempts to call QueuedThreadPool#start the application crashes.

https://github.com/plilja/sleuth-jetty-startup-bug

Version of spring-cloud-sleuth used : 2.2.0.RELEASE

**Comment by marcingrzejszczak** [comment]
Hi, thanks for filing the issue. Are you willing to create a breaking test and then update the production code to fix it? If that's the case, can you do it against the 2.2.x branch?

**Comment by plilja** [comment]
> Hi, thanks for filing the issue. Are you willing to create a breaking test and then update the production code to fix it? If that's the case, can you do it against the 2.2.x branch?

I can give it a shot in the upcoming week.

**Comment by plilja** [comment]
> Hi, thanks for filing the issue. Are you willing to create a breaking test and then update the production code to fix it? If that's the case, can you do it against the 2.2.x branch?

I have looked in to this now and I wont be making a pull request, however I will post my findings here. 

This commit solves my problem:
https://github.com/plilja/spring-cloud-sleuth/commit/7e0b18fac880a062384ee6c25998708d03fdf206

However as you can see I also had to change the class "Issue410Tests" in a way that worries me. Apparently the type of the bean changes which might break startup when people upgrade.
