### ISSUE TITLE
The SpanName could be simplified

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#158]
According to the discussion that takes place here: https://groups.google.com/forum/#!topic/distributed-tracing/Cw-mE03rkgY

**Comment by dsyer** [comment]
`SpanName` (as a class) can probably go back to the cutting floor as well, right? Span names are unstructured in their simpler form, so there's no need for a value class.

**Comment by marcingrzejszczak** [comment]
It gets deleted here - https://github.com/spring-cloud/spring-cloud-sleuth/pull/164
