### ISSUE TITLE
Trace IDs are not sent on messaging brokers that do not support headers.

### ISSUE THREAD

**Issue by jmaister** [spring-cloud/spring-cloud-sleuth#1584]
**Describe the bug**
Trace IDs are not transferred when using a messaging broker that does not support message headers, like NATS (https://nats.io/).

**Sample**
I have a messaging project configured with a Kafka broker and spring-cloud-sleuth logging works correctly. Switching it to a NATS broker breaks the trace logging IDs as new trace and span are created.

**Comment by marcingrzejszczak** [comment]
It's not even a bug in Sleuth. We just don't support nats as such. If spring cloud stream worked fine with this tool then Sleuth would work out of the box. We have to somehow pass the tracing context though, so if headers are not supported then some custom instrumentation would have to take place.

**Comment by jmaister** [comment]
Thanks for the answer.

Would it be a way to read the tracing context from the payload instead of the headers?
Previously, the sender should put that context in the payload of the message.

**Comment by marcingrzejszczak** [comment]
You can check out https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/MessageHeaderPropagation.java where we're retrieving tracing information from messages. You could create sth similar but parse the body accordingly.

**Comment by marcingrzejszczak** [comment]
I'll close this issue for now since there's not much interested in altering Sleuth to support this. If it changes in time we can come back to it.
