### ISSUE TITLE
Springboot custom filters not logging the trace id

### ISSUE THREAD

**Issue by explorer-fullstack** [spring-cloud/spring-cloud-sleuth#1589]
**Describe the bug**
I have few custom filters in my Springboot Webflux API. This project has been activated with Spring Sleuth. However, these filters are not logging the trace id/ span id in the log messages. I have made sure that the order has been set properly for these filters. Can someone please provide your insights on this?

**Sample**
Log message  without trace id: 2020-03-23 12:53:18.895 -2020-03-23 12:53:18.895 INFO [my-spring-boot,,,] 9569 --- [ctor-http-nio-3] c.d.a.f.test.myTestEnvWebFilter : **_Reading data from header_**

Code:
```
@Component
@Profile("multienv")
@Order(value = TEST_WEB_FILTER)
@Slf4j
public class myTestEnvWebFilter implements WebFilter {

    public TestWebFilter() {
        log.info("**_Reading data from header_**");
    }

}
```
**filter Orders defined:**
```
public class FilterOrder {
    private FilterOrder() {}

    // Web filters
    public static final int SAMPLE_FILTER = Ordered.HIGHEST_PRECEDENCE + 100;
    public static final int TEST_WEB_FILTER = SAMPLE_FILTER + 1;

}
```

**Comment by marcingrzejszczak** [comment]
Please learn how to [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

You're cross-posting with StackOverflow (https://stackoverflow.com/questions/60821225/how-to-log-the-trace-id-using-springboot-custom-filters), please don't do this.

Also you'll not see any logging in the constructor. Why should you? There is no tracing going on when Spring context is setup.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
