### ISSUE TITLE
Empty ClientResponse.logPrefix on WebClient response when using Sleuth

### ISSUE THREAD

**Issue by fabiojb** [spring-cloud/spring-cloud-sleuth#1591]
**Describe the bug**
For some reason, making a WebClient call having Sleuth configured on your project, result on a empty `ClientResponse.logPrefix`.

Ex:
```java
webClient.post().uri("/status/400")
        .retrieve()
        .onStatus(httpStatus -> true,
                c -> logger.info("logPrefix:{}", c.logPrefix())) // "logPrefix:"
        .toBodilessEntity();
```
Removing sleuth from classpath solves the problem, and the logPrefix starts to have a value again:
```java
webClient.post().uri("/status/400")
        .retrieve()
        .onStatus(httpStatus -> true,
                c -> logger.info("logPrefix:{}", c.logPrefix())) // "logPrefix: [6fef75c6]"
        .toBodilessEntity();
```

**Sample**
I created a github repo with tests that execute WebClient calls with and without Sleuth to simulate the problem: https://github.com/fabiojb/sleuth-log-prefix-bug

**Comment by fabiojb** [comment]
Apparently the issue is fixed on this commit: https://github.com/spring-projects/spring-framework/commit/d7a29bbcef7d278a3ca9fd66ceb70c60fb283cc0

I'll wait the 5.2.7 release to come out and check if the issue is still reproducible

**Comment by marcingrzejszczak** [comment]
Thanks! I'll close this until then
