### ISSUE TITLE
Zookeeper + Feign + Sleuth does not work

### ISSUE THREAD

**Issue by askindaras** [spring-cloud/spring-cloud-sleuth#1609]
**Bug description**
After adding Sleuth to Zookeeper + Feign project, calls to the external system via load-balanced Feign are throwing _NullPointerException_. If Sleuth is disabled by passing _spring.sleuth.feign.enabled=false_ - everything works fine.

**Sample**
Demo project: https://github.com/askindaras/sleuth-bug
Please try executing _com.example.demo.ExternalServiceIntegrationTest_ with _spring.sleuth.feign.enabled=true_ and later with _spring.sleuth.feign.enabled=false_

**Comment by marcingrzejszczak** [comment]
I've bumped the version to latest build-snapshot and it's working fine. Will be fixed in Hoxton.SR5 then.
