### ISSUE TITLE
assymetry in requests from load-balanced feign vs load-balanced `RestTemplate`

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-sleuth#161]
i've got two endpoints on node A calling the same endpoint on node B:

```java

@FeignClient(serviceId = MessageClient.ZIPKIN_CLIENT_B)
interface MessageServiceClient {

	@RequestMapping(method = RequestMethod.GET, value = "/",
			consumes = MediaType.APPLICATION_JSON_VALUE)
	Map<String, String> readMessage();
}

@RestController
@RequestMapping("/message")
class MessageClientRestController {

	@Autowired
	private RestTemplate restTemplate;

	@Autowired
	private MessageServiceClient messageClient;

	@RequestMapping("/template")
	ResponseEntity<Map<String, String>> template() {

		String url = "http://" + MessageClient.ZIPKIN_CLIENT_B;

		ParameterizedTypeReference<Map<String, String>> ptr =
				new ParameterizedTypeReference<Map<String, String>>() {};

		ResponseEntity<Map<String, String>> responseEntity =
				this.restTemplate.exchange(url, HttpMethod.GET, null, ptr);

		return ResponseEntity
				.ok()
				.contentType(responseEntity.getHeaders().getContentType())
				.body(responseEntity.getBody());
	}

	@RequestMapping("/feign")
	Map<String, String> feign() {
		return this.messageClient.readMessage();
	}
}

``` 

when i run both paths i get more `span`s in the `RestTemplate` call than in the Feign call, which seem to me otherwise identical. Both are load-balanced.

<img width="936" alt="screen shot 2016-02-13 at 5 37 58 pm" src="https://cloud.githubusercontent.com/assets/54473/13028746/c19a05c6-d278-11e5-8809-391cfcee8eb7.png">
<img width="944" alt="screen shot 2016-02-13 at 5 39 18 pm" src="https://cloud.githubusercontent.com/assets/54473/13028747/c19a8faa-d278-11e5-9455-799eb6612560.png">

**Comment by dsyer** [comment]
The feign client is not setting the "ClientSend/Receive" tags. I don't see any difference in the number of spans though. Is that what you meant?
