### ISSUE TITLE
resilience4j with sleuth joint use will be get a NullPointerException

### ISSUE THREAD

**Issue by LightError** [spring-cloud/spring-cloud-sleuth#1613]
**Describe the bug**
I user resilience4j starter and sleuth starter, but i found it all get a  NullPointerException;

position code is :
1. Resilience4JAutoConfiguration
```
	@Bean
	@ConditionalOnMissingBean(CircuitBreakerFactory.class)
	public Resilience4JCircuitBreakerFactory resilience4jCircuitBreakerFactory() {
		Resilience4JCircuitBreakerFactory factory = new Resilience4JCircuitBreakerFactory();
		customizers.forEach(customizer -> customizer.customize(factory));
		return factory;
	}
```
sleuth will user AnnotationAwareAspectJAutoProxyCreator to create Resilience4JCircuitBreakerFactory proxy. it use cglib
2. Resilience4JAutoConfiguration
```
		@PostConstruct
		public void init() {
			if (factory != null) {
				TaggedCircuitBreakerMetrics
						.ofCircuitBreakerRegistry(factory.getCircuitBreakerRegistry())
						.bindTo(meterRegistry);
			}
		}
```
factory is proxy by cglib, and ```factory.getCircuitBreakerRegistry()``` will be null

**Sample**
[demo project](https://github.com/LightError/demo)

**Comment by adriancole** [comment]
@LightError do you have time to fix the bug?

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-circuitbreaker/issues/68
