### ISSUE TITLE
Disabling @Scheduled instrumentation doesn't work unless @Async instrumentation is disabled

### ISSUE THREAD

**Issue by Shrulik** [spring-cloud/spring-cloud-sleuth#1615]
This of course also applies to the skip-pattern. 

Versions: 2.1.7.RELEASE of sleuth-core and spring boot 2.1.3

This happens tobecause @Scheduled operations are run from the "taskScheduler" bean initialized by Spring, and this bean/executor is processed by the org.springframework.cloud.sleuth.instrument.async.ExecutorBeanPostProcessor.

I think this is a bug, at the very least at the documentation level. 
To solve this, probably disabling tracing for the taskScheduler bean is required when @Scheduled tracing is turned off. I'm not sure if Spring uses the taskScheduler bean for other operations, hopefully not.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Shrulik** [comment]
At least for now, I no longer work for the client on whose code base I discovered this issue.

**Comment by marcingrzejszczak** [comment]
If someone gets this issue again please reopen it with a link to code that will help us replicate this problem.
