### ISSUE TITLE
How to naming the server when use spring-cloud-starter-openfeign + spring-cloud-starter-zipkin invoke cloud service

### ISSUE THREAD

**Issue by chentging** [spring-cloud/spring-cloud-sleuth#1616]
Versions:
- spring-boot-starter-parent:2.2.6.RELEASE
- spring-cloud-dependencies:Hoxton.SR3

I use spring-cloud-starter-openfeign + spring-cloud-starter-zipkin to collect trace and send to zipkin-server, all work well,zipkin-server show right tracing.

but I want to naming the remote service name so that it shows up in Zipkin's service dependency graph

![image](https://user-images.githubusercontent.com/29357333/79488604-91c99b00-804c-11ea-88af-6e1ff0c1da5b.png)

I only find a little doc in https://github.com/openzipkin/brave/pull/242#issue-86643842,
but I don't know how to do in spring cloud sleuth when I use feign.

@adriancole 
> ### Naming the server
> When calling an service that isn't traced with Zipkin, such as a cloud
> service. You'll want to assign a server name so that it shows up in
> Zipkin's service dependency graph. You can set this via
> `BraveTracingInterceptor.Builder.serverName()`
> 
> ```java
> tracingInterceptor = BraveTracingInterceptor.builder(brave)
>   ...
>   .serverName("github").build();
> 
> request = new Request.Builder()
>     .url("https://api.github.com/repos/square/okhttp/issues")
>     ...
> ```

sample-zipkin-sleuth-client
```java
@FeignClient(name = "${sample.zs.server.name}", url = "${sample.zs.server.url}")
public interface SimpleService {
	@GetMapping(value = "/server", headers = {"signature=server"})
	public String simpServ();
}
```
sample-zipkin-sleuth-server
```java
@GetMapping("/server")
public String getService() {
        return "OK";
}
```

please give me some help☺️☺️

**Comment by adriancole** [comment]
When I originally made feign, the "target name" was made for metrics for the remote name.

I'm trying to understand if `name = "${sample.zs.server.name}"` isn't showing up as the remote service name, or if it is and you'd like that changed

cc also @worldtiki who likes remote names :D

**Comment by adriancole** [comment]
the usual workaround to whatever isn't working is creating a FinishedSpanHandler bean and changing whatever, assuming you can identify the span based on what's in the name or tags.

**Comment by chentging** [comment]
> the usual workaround to whatever isn't working is creating a FinishedSpanHandler bean and changing whatever, assuming you can identify the span based on what's in the name or tags.

yea,I solve it via creating a FinishedSpanHandler bean(I shoud more see FinishedSpanHandler 😋)
It seems very simple🥳
thank you,adriancole 
```java
	@Bean
	FinishedSpanHandler finishedSpanHandler(
			@Value("${sample.zs.server.name}") String remoteServiceName,
			@Value("${sample.zs.server.ip}") String remoteServiceIp,
			@Value("${sample.zs.server.port}") Integer remoteServicePort) {
		return new FinishedSpanHandler() {
			@Override
			public boolean handle(TraceContext traceContext, MutableSpan span) {
				span.remoteServiceName(remoteServiceName);
				span.remoteIpAndPort(remoteServiceIp, remoteServicePort);
				return true; // keep this span
			}
		};
	}
```
zipkin-server call relationship:
![image](https://user-images.githubusercontent.com/29357333/79530873-3bd41200-80a3-11ea-992e-07f39b56d222.png)
