### ISSUE TITLE
Allow span name customization in Quartz instrumentation

### ISSUE THREAD

**Issue by jbruinink** [spring-cloud/spring-cloud-sleuth#1617]
Looking at our traces in Zipkin, I noticed that all spans of Quartz jobs have a unique name. Since span names are expected to be low cardinality, this causes problems in the ui. Looking at the code, I noticed that the quartz job key is used to name the spans. In our application, jobs are scheduled by Axon Framework which uses a unique identifier as the job name which ends up in the job key.

I would like to be able to customize the names of the spans. For instance by registering a bean that maps a `JobExecutionContext` to a span name.

Alternatively I could disable the autowiring for quartz and subclass the `TracingJobListener`. I'm not sure how common this problem is.

I would be happy to submit a PR for this, but I don't know if this is something you would want Sleuth to support.

**Comment by adriancole** [comment]
is there a good way to detect that uuid names are in use? it could be the case we shouldn't use the job name as default..

how would you derive the span name?

for now you can use FinishedSpanHandler as a workaround.

**Comment by marcingrzejszczak** [comment]
@jbruinink what do you think of @adriancole 's answer?

**Comment by jbruinink** [comment]
I can't think of a reliable way to detect this in general. 

In our specific case we would use the job group name as the span name. Maybe this should be the default. The name of that property suggests it is lower cardinality.

For now we will use the FinishedSpanHandler to set the span name to something like "quartz"

**Comment by marcingrzejszczak** [comment]
Let's close this for now and if we figure this out in the future we'll reopen it.
