### ISSUE TITLE
Slueth trace id mismatch between services

### ISSUE THREAD

**Issue by anandfmr** [spring-cloud/spring-cloud-sleuth#1625]
Hi,

I am trying to use spring cloud slueth with spring webflux and seeing that the trace id in caller and called service are not matching. Any idea, what could be the reason and please let me know if there is a workaround.
Caller Service:
[d25525f4ca3f6128/fc16d633d82ea1ac]
Called Service:
[17dcc5ab6eaf3659/17dcc5ab6eaf3659]

Thanks

**Comment by spencergibb** [comment]
None. Besides the two traceid's you given us no other information that was asked for 

> Describe the bug Please provide details of the problem, including the version of Spring Cloud that you are using.

> Sample If possible, please provide a test case or sample application that reproduces the problem. This makes it much easier for us to diagnose the problem and to verify that we have fixed it.

**Comment by anandfmr** [comment]
Please find below the details:
```
return webClient.post()
                .contentType(MediaType.APPLICATION_JSON)
                .body(Mono.just(billOfLading),BillOfLading.class)
                .retrieve()
                .bodyToMono(BillOfLading.class)
```
If you see the post request Log:
2020-05-07 08:46:03.181 [274932741fc3beeb/0a6bc13b57ff067b]  INFO 9200 [container-0-C-1] n.a.c.g.m.r.c.BillOfLadingCallerImpl     : Request: POST
And when I see the called service log 
2020-05-07 08:46:04.117 [9720ec00a972ae48/9720ec00a972ae48] DEBUG 21392 [ctor-http-nio-3] o.s.d.m.c.ReactiveMongoTemplate          : Saving Document containing

Now, Do I have to pass the trace id in the header and set it manually at receiver side in MDC.put or shouldn't it be taken care automatically by slueth.

Cloud Version:
<spring-cloud.version>Hoxton.SR1</spring-cloud.version>

Thanks,
Anand

**Comment by spencergibb** [comment]
How is the web client created?

**Comment by anandfmr** [comment]
In postconstruct block:
```
WebClient webClient;

    @PostConstruct
    public void initialize() {
        webClient = WebClient.builder()
                .baseUrl(baseURI)
                .filter(logRequest())
                .build();
    }
```

**Comment by spencergibb** [comment]
Your web client is not instrumented because it is not a bean

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
