### ISSUE TITLE
Sleuth not reporting client spans with Feign builder

### ISSUE THREAD

**Issue by natrem** [spring-cloud/spring-cloud-sleuth#1626]
First if you think this issue would have been better in StackOverflow or other then forgive me and tell it so I'll know for next time.

**Describe the bug**
When using Feign.builder() to create a BuilderFeign build with ribbon client LoadBalancerFeignClient I notice that the client spans are not sent to zipkin.

I noted the documentation saying ['nothing created manually will work'](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1125#issuecomment-451754405) yet I see some instrumentation.

`TraceFeignObjectWrapper.wrap` handles `LoadBalancerFeignClient` and - from my understanding - `TraceLoadBalancerFeignClient` creates a span - that should be sent downstream - and abandon it at the end. On the other hand, for other feign clients, `TracingFeignClient` performs the receive.

Given the specific code I suppose there is a rational behind this choice but I do not understand it.
Could you explain it?

I managed to have my client reporting client spans by creating a class that extends `TraceLoadBalancerFeignClient` and mimic the content of `TracingFeignClient` but I'm surprised that this is needed.

**Sample**
A sample app with these classes reproduces the behavior:
```java
public interface BuilderFeign {
    @RequestLine("GET /")
    String pingGithub();
}
```

```java
@Configuration
public class BuilderFeignConfig {

    @Bean
    static BuilderFeign blotterFeignClient(ObjectFactory<HttpMessageConverters> messageConverters,
                                           Client loadBalancerFeignClient){
        Request.Options options = new Request.Options(30000, 30000);

        return Feign.builder()
                .encoder(new SpringEncoder(messageConverters))
                .decoder(new SpringDecoder(messageConverters))
                .decode404()
                .retryer(NEVER_RETRY)
                .options(options)
                .client(loadBalancerFeignClient)
                .target(BuilderFeign.class, "https://api.github.com");
    }

    @Bean
    public Client loadBalancerFeignClient(CachingSpringLoadBalancerFactory cachingFactory,
                                               SpringClientFactory clientFactory, BeanFactory beanFactory,
                                               HttpTracing httpTracing) {
        PoolingHttpClientConnectionManager cm = new PoolingHttpClientConnectionManager();
        cm.setMaxTotal(200);
        cm.setDefaultMaxPerRoute(20);
        return new LoadBalancerFeignClient(new Client.Default(null, NoopHostnameVerifier.INSTANCE), cachingFactory, clientFactory);
// client spans are reported with this implementation
//        return new CustomTraceLoadBalancerFeignClient(httpTracing, new Client.Default(null, NoopHostnameVerifier.INSTANCE), cachingFactory, clientFactory, beanFactory);
    }
}
```

```java
    @GetMapping("/builderFeign")
    public ResponseEntity<?> getFromBuilderFeign() {
        return new ResponseEntity<>(this.builderFeign.pingSgithub(), HttpStatus.OK);
    }
```

My class `CustomTraceLoadBalancerFeignClient` is a copy of `TracingFeignClient` + other needed copies (due to closed visibility) except the call to `this.delegate.execute(modifiedRequest(request, headers), options)` is replaced by `super.execute(modifiedRequest(request, headers), options)`

**Comment by marcingrzejszczak** [comment]
Which version of Sleuth are you using?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by natrem** [comment]
sorry for the missing part.
this version was made with spring boot 2.2.5.RELEASE and spring cloud Hoxton.SR2

**Comment by marcingrzejszczak** [comment]
Can you please check if the problem still persists with the latest 2.2.x and 2.3.x ?

**Comment by natrem** [comment]
I checked and still reproduce the issue with
-  boot 2.3.2.RELEASE and cloud Hoxton.SR6 
- boot 2.2.9.RELEASE and cloud Hoxton.SR6

The workaround is still valid too. Thus I'm puzzled by the current implementation of `TraceFeignObjectWrapper.wrap`

**Comment by marcingrzejszczak** [comment]
AFAIR that's because we wrap the delegate and we don't want to wrap twice - the `LoadBalancerFeignClient` and its delegate.

**Comment by marcingrzejszczak** [comment]
Can you create a sample with your code?

**Comment by natrem** [comment]
My bad. While creating the sample free of corporate stuff I found out I did not test properly earlier.
The client spans are now reported correctly with latest versions.
Thanks.
