### ISSUE TITLE
Create a SleuthMongoConfiguration class to tag Mongodb as a remote service

### ISSUE THREAD

**Issue by davidmelia** [spring-cloud/spring-cloud-sleuth#1627]
Hi,

Now that brave-instrumentation-mongodb has been released 
```
<dependency>
     		<groupId>io.zipkin.brave</groupId>
    		<artifactId>brave-instrumentation-mongodb</artifactId>
        	<version>5.12.3</version>
</dependency>  
```
See https://github.com/openzipkin/brave/tree/master/instrumentation/mongodb

Can we add SleuthMongoConfiguration  (Similar to SleuthKafkaConfiguration and TraceRedisAutoConfiguration ) so we can tag MongoDB as a remote service?

Thanks

**Comment by spencergibb** [comment]
seems reasonable to me.

**Comment by marcingrzejszczak** [comment]
Sure, @davidmelia  are you willing to give it a try in a PR? :)

**Comment by marcingrzejszczak** [comment]
Hey @davidmelia are you willing to take the 3.0.0-SNAPSHOT for a spin with your Mongo installation?

**Comment by davidmelia** [comment]
@marcingrzejszczak  having a bit of a nightmare with dependencies

`Could not resolve dependencies for project com.example:demo:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.springframework.cloud:spring-cloud-starter-sleuth:jar:3.0.0-SNAPSHOT: Failed to read artifact descriptor for org.springframework.cloud:spring-cloud-starter-sleuth:jar:3.0.0-SNAPSHOT: Failure to find io.projectreactor:reactor-bom:pom:2020.0.0-M1`

will try again tomorrow.

**Comment by davidmelia** [comment]
@marcingrzejszczak  works great - thanks for this :-) 

<img width="991" alt="Screenshot 2020-07-01 at 08 41 26" src="https://user-images.githubusercontent.com/8583712/86217075-dad2bb00-bb76-11ea-8d31-4dd6e7880bf0.png">
