### ISSUE TITLE
Incomptability between Sleuth and Eureka

### ISSUE THREAD

**Issue by houdini68** [spring-cloud/spring-cloud-sleuth#163]
Hi,

In the LoadBalancerAutoConfiguration, a loadBalancedRestTemplate bean is created and later is Autowired into the class TraceWebClientAutoConfiguration. 

The TraceInterceptorConfiguration does the following:
```
@Autowired(required = false)
private Collection<RestTemplate> restTemplates>
```
and
```
@Autowired
private TraceRestTemplateInterceptor traceRestTemplateInterceptor;
```
Then in a loop we add the interceptor to the array of restTemplates.
The following line will return a ClassCastException:
```
for (RestTemplate restTemplate : this.restTemplates) {
```
More specifically:
```
09:49:00.692 [main] ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.sleuth.instrument.web.client.TraceWebClientAutoConfiguration$Trace
InterceptorConfiguration': Invocation of init method failed; nested exception is java.lang.ClassCastException: com.sun.proxy.$Proxy96 cannot be cast to org.springframework.web.client.RestTemplate
```
Any idea why the TraceInterceptorConfiguration  cannot assign the RestTemplate that was created by LoadBalancerAutoConfiguration ?

Thanks a lot in advance,

Rudy

**Comment by marcingrzejszczak** [comment]
It seems you're missing `@EnableAspectJAutoProxy(proxyTargetClass = true)`

**Comment by houdini68** [comment]
Thanks a lot for the answer. It solved the problem!
