### ISSUE TITLE
baggage set is not correct 

### ISSUE THREAD

**Issue by bloodstars** [spring-cloud/spring-cloud-sleuth#1631]
**Describe the bug**
ServiceA -> ServiceB -> ServiceC 

in ServiceA ,i initialize a baggage 'pid'  to call ServiceB , and it pass two header "baggage-pid" and "baggage_pid" to ServiceB, and in ServiceB i set baggage 'pid' a new value by using 
`ExtraFieldPropagation.set(key, value);`  ， it only change header "baggage-pid" not both header , and when ServiceB call ServiceC , it pass 'baggage-pid'=newvalue and 'baggage_pid'=oldvalue to ServiceC, and SerivceC only get the oldvalue........

in spring-cloud-sleuth-core-2.2.2

**Comment by adriancole** [comment]
thanks for describing the problem. I'll check this out before our 2.2.3 release which is less than a week away

**Comment by adriancole** [comment]
I think it is ok.. not sure how it could even be incorrect. Anyway 2.2.3 will be out soon so you can try again.

Here's the test I used on 2.2.3

```java
	@Test
	public void testBaggage() {
		new ApplicationContextRunner()
				.withConfiguration(AutoConfigurations.of(TraceBaggageConfiguration.class))
				.withPropertyValues("spring.sleuth.baggage-keys=pid")
				.run((context) -> {
					final Propagation.Factory propagationFactory = context
							.getBean(Propagation.Factory.class);
					TraceContext ctx = propagationFactory.decorate(
							TraceContext.newBuilder().traceId(1L).spanId(2L).build());

					// old api
					ExtraFieldPropagation.set(ctx, "pid", "1");

					// new api
					assertThat(BaggageField.create("pid").getValue(ctx)).isEqualTo("1");

					// propagation
					Map<String, String> map = new LinkedHashMap<>();
					propagationFactory.get().<Map<String, String>>injector(Map::put).inject(ctx, map);
					assertThat(map)
							.containsEntry("baggage-pid", "1")
							.containsEntry("baggage_pid", "1");
				});
	}
```

**Comment by bloodstars** [comment]
yes, set and get in one springboot process works fine, but when use feign to call other app, does not.maybe something wrong in feignaspect? ........i wiill try 2.2.3 to see if it works. thanks.

**Comment by bloodstars** [comment]
maybe here?  

.addPrefixedFields("baggage-", sleuthProperties.getBaggageKeys())
.addPrefixedFields("baggage_", sleuthProperties.getBaggageKeys());

@Bean
	@ConditionalOnMissingBean
	Propagation.Factory sleuthPropagation(SleuthProperties sleuthProperties) {
		if (sleuthProperties.getBaggageKeys().isEmpty()
				&& sleuthProperties.getPropagationKeys().isEmpty()
				&& extraFieldCustomizers.isEmpty()
				&& this.extraFieldPropagationFactoryBuilder == null
				&& sleuthProperties.getLocalKeys().isEmpty()) {
			return B3Propagation.FACTORY;
		}
		ExtraFieldPropagation.FactoryBuilder factoryBuilder;
		if (this.extraFieldPropagationFactoryBuilder != null) {
			factoryBuilder = this.extraFieldPropagationFactoryBuilder;
		}
		else {
			factoryBuilder = ExtraFieldPropagation
					.newFactoryBuilder(B3Propagation.FACTORY);
		}
		if (!sleuthProperties.getBaggageKeys().isEmpty()) {
			factoryBuilder = factoryBuilder
					// for HTTP
					.addPrefixedFields("baggage-", sleuthProperties.getBaggageKeys())
					// for messaging
					.addPrefixedFields("baggage_", sleuthProperties.getBaggageKeys());
		}
		if (!sleuthProperties.getPropagationKeys().isEmpty()) {
			for (String key : sleuthProperties.getPropagationKeys()) {
				factoryBuilder = factoryBuilder.addField(key);
			}
		}
		if (!sleuthProperties.getLocalKeys().isEmpty()) {
			for (String key : sleuthProperties.getLocalKeys()) {
				factoryBuilder = factoryBuilder.addRedactedField(key);
			}
		}
		for (ExtraFieldCustomizer customizer : this.extraFieldCustomizers) {
			customizer.customize(factoryBuilder);
		}
		return factoryBuilder.build();
	}

**Comment by marcingrzejszczak** [comment]
Please learn how to [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
