### ISSUE TITLE
Allow continuing of spans via messaging

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#165]
ATM we're always creating new spans check: `TraceChannelInterceptor`

**Comment by efenderbosch** [comment]
Will this allow the propagation of span IDs across messaging systems, such as Kafka?

Currently, I'm reading the span ID out of the MDC, adding it to a header in an envelope that contains the real message body, then serializing and sending the envelope. In the deserializer, I'm reading the header value and putting it back directly in the MDC before returning the message body to the consumer.

Will this strategy work, or is there a way I should register the span ID during deserialization?

**Comment by marcingrzejszczak** [comment]
It does already work for messaging and for kafka if you're using Spring
Cloud Stream. This issue is about continuing spans instead of creating them
each time.

Let's say that this task is about improving the way spans are treated in
messaging not about adding tracing support for messaging. Cause this has
already been done since 1.0.0.RELEASE

**Comment by marcingrzejszczak** [comment]
Closing this in favour of https://github.com/openzipkin/brave/pull/572
