### ISSUE TITLE
Not clear from the doc how to use parent trace id from new thread

### ISSUE THREAD

**Issue by Sergey80** [spring-cloud/spring-cloud-sleuth#1650]
**Describe the bug**
Initially posted: [here](https://stackoverflow.com/questions/61659898/make-spring-sleuth-not-to-create-a-new-trace-id-span-for-new-thread)

There is provided answer (mainly taken from the doc), there is no up vote for some time. apparently because it is not useful.. It did not answer the question. At least I could not apply any of it and get desired result. 

**Sample**
Re-iterating here:

Here is http interceptor that is set on Spring HttpTemplate to intercept request / responses.
Http calls are blocking, so they are performing in separate threads. Separate from main thread on spring boot web app.  

The interceptor:

`public class ClientHttpRequestInterceptorImpl implements ClientHttpRequestInterceptor {`

   `log.info(JacksonUtil.toJsonString(logRequest));`

the log always prints in new trace id. instead of using main trace id. 

Because of that, it is impossible to trace the requests from the beginning to the end. Since the trance is "broken" (splitted).

Is there clear working explanation how **not** to let sleuth create new trace id? How to be in main trace id?

**Comment by adriancole** [comment]
I can understand you want to escalate the stackoverflow, but probably still using gitter to nag is nicer than pasting SO here. I'll look at your SO, but please try gitter next time if you feel you need to escalate https://gitter.im/spring-cloud/spring-cloud-sleuth
