### ISSUE TITLE
spring-cloud-sleuth and reactor

### ISSUE THREAD

**Issue by dchack** [spring-cloud/spring-cloud-sleuth#1653]
**Describe the bug**
spring-cloud-sleuth version is 2.1.1.REALEASE
reactor-core version is 3.2.11.REALEASE
this codes :
```java
Mono
                .fromRunnable(task)
                .publishOn(scheduler)
                .subscribe();
```
there is no new thread to execute task，because Mono is MonoLift。

reactor.core.publisher.Mono#publishOn：
```java
	public final Mono<T> publishOn(Scheduler scheduler) {
		if(this instanceof Callable) {
			if (this instanceof Fuseable.ScalarCallable) {
				try {
					T value = block();
					return onAssembly(new MonoSubscribeOnValue<>(value, scheduler));
				}
				catch (Throwable t) {
					//leave MonoSubscribeOnCallable defer error
				}
			}
			@SuppressWarnings("unchecked")
			Callable<T> c = (Callable<T>)this;
			return onAssembly(new MonoSubscribeOnCallable<>(c, scheduler));
		}
		return onAssembly(new MonoPublishOn<>(this, scheduler));
	}
```
MonoLift is not instanceof Callable,so cant use scheduler.

And I use main method to execute codes there is no problem.
When I use `spring.sleuth.reactor.enabled=false`,there is no problem.
Why Mono change to MonoLift,because `TraceReactorAutoConfiguration`.

**Comment by spencergibb** [comment]
Can you retry with the latest supported sleuth Hoxton.SR4 (2.2.2) and boot 2.2.7?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
