### ISSUE TITLE
Project page refers to the wrong bom

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-sleuth#1658]
The project page at https://spring.io/projects/spring-cloud-sleuth refers to `spring-cloud-sleuth` as the bom to use to get started. Unfortunately, that does not match the setup [in the reference guide](https://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/2.2.2.RELEASE/reference/html/#sleuth-adding-project) and it looks like it should be at the very least `spring-cloud-sleuth-dependencies`. 

The one documented brings dependencies that are internal to the build, which can lead conflicts when mixed with a valid project using the Spring Boot bom, see https://github.com/spring-projects/spring-boot/issues/21586#issuecomment-634981613

**Comment by spencergibb** [comment]
yeah, I think all of the spring cloud core projects suffer similarly. They should refer to spring-cloud-dependencies.
