### ISSUE TITLE
Formalize internal or experimental code

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#166]
If experimental or otherwise internal code was noted as such, review could be easier as it would be obvious that this isn't public api changing.

This is particularly important with "Spike PRs" which routinely raise underdocumented and experimental code.

The issue comes in two major areas.

First there's chicken-egg problem. For example "Spike PRs" usually has code inside which folks aren't sure about. Ex. others might want to play with it before committing to an idea. We don't have experimental builds, so placing the code in master helps alleviate the chicken-egg problem.

Secondly, there's an implicit public api problem. Right now, it isn't clear which types are internal or not based on package structure or anything else. There's a running assumption that certain existing types are the api. This makes review a bit burdensome as it isn't always obvious if "spike types" are experimental or intentionally affecting public api, or intentionally not yet affecting public api.

Projects like guava solve this with a `@Beta` annotation, but that indicates it is part of an emerging public api.. ex users should proceed with caution. Many projects have an internal package, which indicate code that isn't intended for public consumption (at least yet)

I'd really love for us to have a means for people like me to be able to review new change without having to wonder why "junk types" are added, or if lack of documentation is ok (bc it is internal)

Thoughts?

**Comment by marcingrzejszczak** [comment]
I like the idea of the annotation. Makes perfect sense.

**Comment by dsyer** [comment]
I think it's overthinking the problem. It's not a convention used anywhere else in Spring either, so I'd prefer just to keep it informal.

**Comment by adriancole** [comment]
Fair enough.. When in Rome etc.

**Comment by marcingrzejszczak** [comment]
So do we close it?
