### ISSUE TITLE
Upgrade to Hoxton.SR5 creates ClassNotFoundException in a test using stubrunner

### ISSUE THREAD

**Issue by martinvisser** [spring-cloud/spring-cloud-sleuth#1661]
After the upgrade from Hoxton.SR4 to Hoxton.SR5 nothing seemed wrong initially, because our Spring Boot app still started without any issues. However, running unittests (a `@SpringBootTest`) it fails with `java.lang.ClassNotFoundException: org.springframework.cloud.loadbalancer.config.LoadBalancerAutoConfiguration`.
Using the exact same configuration for starting the application and running the unittest this happened.
I did a comparison between the auto configuration loading. I debugged the code with `debug: true`
[sr4.txt](https://github.com/spring-cloud/spring-cloud-commons/files/4716236/sr4.txt)
[sr5.txt](https://github.com/spring-cloud/spring-cloud-commons/files/4716237/sr5.txt)

I also added the maven dependency trees.
[sr4-tree.txt](https://github.com/spring-cloud/spring-cloud-commons/files/4716251/sr4-tree.txt)
[sr5-tree.txt](https://github.com/spring-cloud/spring-cloud-commons/files/4716252/sr5-tree.txt)

**Comment by marcingrzejszczak** [comment]
It's been already fixed in spring cloud contract https://github.com/spring-cloud/spring-cloud-contract/issues/1419
