### ISSUE TITLE
Provide sleuth tracing on all factory methods of KafkaListenerContainerFactory

### ISSUE THREAD

**Issue by fromlabs** [spring-cloud/spring-cloud-sleuth#1664]
Version: `spring-cloud-sleuth-core-2.2.2.RELEASE.jar`

Actually `MessageListenerContainer` creation is intercepted thanks to a pointcut defined in `SleuthKafkaAspect` on method `KafkaListenerContainerFactory.createListenerContainer`:

```
@Pointcut("execution(public * org.springframework.kafka.config.KafkaListenerContainerFactory.createListenerContainer(..))")
private void anyCreateListenerContainer() {
}
```

but from the reference documentation ([link](https://docs.spring.io/spring-kafka/docs/2.5.1.RELEASE/reference/html/#container-factory)):

> Starting with version 2.2, you can use the same factory to create any ConcurrentMessageListenerContainer

`KafkaListenerContainerFactory` exposes other factory methods:

```
// intercepted
C createListenerContainer(KafkaListenerEndpoint endpoint);

// not intercepted
C createContainer(TopicPartitionOffset... topicPartitions);
C createContainer(String... topics);
C createContainer(Pattern topicPattern);
```

Can you add pointcuts also on `createContainer(..)` methods with the same tracing logic?

**Comment by marcingrzejszczak** [comment]
Thanks for the pointer! Maybe you're interested in filing a pull request (against branch 2.2.x)with those changes? :)

**Comment by adriancole** [comment]
related to #1670

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-sleuth/pull/1665/files
