### ISSUE TITLE
[Feature] Out of box support for RSocket in sleuth similar to WebFlux

### ISSUE THREAD

**Issue by kprasad99** [spring-cloud/spring-cloud-sleuth#1677]
With RSocket being added into spring boot core similar to WebFlux and RSocket is being projected for inter micro services communication tracing becomes more important in RSocket environment.  Thus case for out of box support for RSocket becomes more important.

**Comment by vitorvezani** [comment]
Any update on this task? Is it planned or have already some code/branch that I could have a look into? thanks!

**Comment by marcingrzejszczak** [comment]
Nope, not yet. We have it on our radar though.

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-sleuth/commit/216d681b04a2fc228ca5628e4f5c4593d9b33171

**Comment by marcingrzejszczak** [comment]
It's available in Release Train `2021.0.0-SNAPSHOT` or Sleuth version `3.1.0-SNAPSHOT`
