### ISSUE TITLE
Sleuth should be disabled by default when we add its dependency

### ISSUE THREAD

**Issue by asuri3** [spring-cloud/spring-cloud-sleuth#1681]
**Is your feature request related to a problem? Please describe.**
We have some microservice applications, which are dependent on one common module, I added sleuth dependency in that common module which now enabled sleuth in all modules, is there any way to disable sleuth by default for all applications and in case if someone wants to enable it, they can enable it through the property?

Right now, to disable it I have to add "sleuth.enabled: false" in all child applications which I don't want, As this common module, is shared among a lot of applications. 

**Describe the solution you'd like**
Sleuth should be disabled by default or there should be a way through code to disable it. So when required, we can enable it through the property.

**Comment by marcingrzejszczak** [comment]
I disagree. If you add a dependency then you want to have sth working. If you don't want sleuth either remove the dependency or set the property. You can set the property coś the config server globally then you'll only do it once.

**Comment by asuri3** [comment]
My suggestion is to keep Auto configuration in 1 file, which if someone wants, can disable it by using @EnableAutoConfiguration(exclude = { ClassName.class})

**Comment by robotmrv** [comment]
@asuri3  you can add to your module  EnvironmentPostProcessor that will set the property to false if it was not set or to play with your own PropertySourceLocator which will do the same with the lowest priority
