### ISSUE TITLE
spring-cloud-sleuth-stream dependency with version 2.2.1.RELEASE is not present in the maven repo

### ISSUE THREAD

**Issue by raika-jagdish** [spring-cloud/spring-cloud-sleuth#1697]
I am facing some issues while building one of the applications where **spring-cloud-sleuth-stream** is coming transitively in the <dependencyManagement> from **spring-cloud-sleuth** version **2.2.1.RELEASE**. 

I am getting a warning in the maven build as below and build is failing due to this:-

_

> Downloading from public: https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-sleuth-stream/2.2.1.RELEASE/spring-cloud-sleuth-stream-2.2.1.RELEASE.pom
> [WARNING] The POM for org.springframework.cloud:spring-cloud-sleuth-stream:jar:2.2.1.RELEASE is missing, no dependency information available.

_

My question is simple, why the dependency has been added in the <dependencyManagement> section of **spring-cloud-sleuth version** **2.2.1.RELEASE** when actually doesn't exist in the [maven](https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-sleuth-stream/).

https://github.com/spring-cloud/spring-cloud-sleuth/blob/c71d6ff0e2af4f57b58a27c626c94eb07257a456/spring-cloud-sleuth-dependencies/pom.xml#L57

**Comment by marcingrzejszczak** [comment]
Please use the latest sleuth version and try again

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
