### ISSUE TITLE
App crashes on startup if zipkin collector is not running

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#17]
(This is particularly annoying if all you wanted to do was log the spans.)

**Comment by spencergibb** [comment]
running with `--sleuth.sample.logging.collector.enabled=true` or `--spring.sleuth.zipkin.enabled=false` works for me

**Comment by dsyer** [comment]
I changed the property name to `sample.zipkin.enabled=false`. It works, thanks.
