### ISSUE TITLE
W3C tracecontext propagation

### ISSUE THREAD

**Issue by suman-aella** [spring-cloud/spring-cloud-sleuth#1700]
Hi

   This is a follow up to the feature request and also closed PR
 https://github.com/spring-cloud/spring-cloud-sleuth/issues/1540
  https://github.com/openzipkin/brave/pull/693

  We would like to use the W3C trace context propagation for spring boot projects using sleuth. With included support of the w3c specified traceheaders.
  Currently I see the development happening in the new repo
  https://github.com/openzipkin-contrib/brave-propagation-w3c

  I see that currently the above propagation repo uses brave 5.12.3 versions and not compatible with latest Sleuth which uses brave 5.9.
  Is the Sleuth update to be done once this feature is released. Could you advice me on its usage for my Spring sleuth projects. Should I go with my own implementation if not.

Thanks

**Comment by marcingrzejszczak** [comment]
All of our latest releases are using latest Brave version (e.g. https://github.com/spring-cloud/spring-cloud-sleuth/blob/v2.2.3.RELEASE/spring-cloud-sleuth-dependencies/pom.xml#L34)

**Comment by suman-aella** [comment]
Ok. I see that my Springcloud version has affected the zipkin brave dependency version.
Once I updated the SpringCloudVersion from 'Hoxton.SR1' to ''Hoxton.SR5'' the latest brave version 5.12.3 got reflected in the dependencies under the "spring-cloud-starter-zipkin" artifatct.

**Comment by marcingrzejszczak** [comment]
Cool, can we close this then?

**Comment by suman-aella** [comment]
> Cool, can we close this then?

yes we can. thanks
