### ISSUE TITLE
How to override traceId in runtime.

### ISSUE THREAD

**Issue by Anakinud** [spring-cloud/spring-cloud-sleuth#1709]
I have jobs which state is stored in db if some requirements are met those jobs become retrieved from db and started once again. This system is using RxJava with spring.

What I would like to achieve is: when such job is started again I want to have traceId with same value when this job was saved in db. Example:

1. Job is started with **traceId A**
2. Job is saved with **traceId A** and waits for some required data/events
3. Other process is started with **traceId B**
Process with **traceId B** unlock job with **traceId A** to be processed again

In that case when I will be processing job it will be with **traceId B**. My current naive implementation was to insert it to MDC, but it works only in scope of Single.map and is not propagated to inside Completables or Singles. I assume it might require some hacking because I couldn't find any similar use case in brave documentation and spring-sleuth. Moreover, if it will make it easier I don't care about spanId, the only important thing for me is traceId.

**Comment by marcingrzejszczak** [comment]
Just use Brave's API

```java
Span span = tracer.nextSpan(TraceContextOrSamplingFlags.create(TraceContext.newBuilder().traceId(xxx).build()));
```

your span object will continue the previous trace (of course you need to pass all the relevant information in the trace context builder). On the other hand you might have a messed up UI in Zipkin if the gap between stopping the trace and continuing it later on will be to large.

**Comment by Anakinud** [comment]
I tried what you suggested and it didn't work out. Maybe I'm missing some value. My code which I tried:
```
    void someMethod() {
       Span span = tracer.nextSpan(TraceContextOrSamplingFlags.create(createTraceContext(checkpoint)));
        try {
            span.start();
            log.info("Restored transaction");
            action.run();
        } finally {
            span.finish();
        }
    }

    private TraceContext createTraceContext(Checkpoint checkpoint) {
        return TraceContext.newBuilder()
                .traceIdHigh(checkpoint.traceIdHigh())
                .traceId(checkpoint.traceId())
                .spanId(getRandomBytes(8)))
                .build();
    }
```

In given try block my logs are logged with previous transaction id.

**Comment by marcingrzejszczak** [comment]
Try this

```java
    void someMethod() {
       Span span = tracer.nextSpan(TraceContextOrSamplingFlags.create(createTraceContext(checkpoint)));
        try (SpanInScope ws = tracer.withSpanInScope(span.start())) {
            log.info("Restored transaction");
            action.run();
        } finally {
            span.finish();
        }
    }

    private TraceContext createTraceContext(Checkpoint checkpoint) {
        return TraceContext.newBuilder()
                .traceIdHigh(checkpoint.traceIdHigh())
                .traceId(checkpoint.traceId())
                .spanId(getRandomBytes(8)))
                .build();
    }
```
