### ISSUE TITLE
Make HTTP response status available in WebClient trace

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-sleuth#1714]
**Is your feature request related to a problem? Please describe.**
```
{"traceId":"9a95a6e86b4d828f","id":"9a95a6e86b4d828f","kind":"CLIENT","name":"post","timestamp":1597353880756953,"duration":197036,"localEndpoint":{"serviceName":"my-svc"},"tags":{"http.method":"POST","http.path":"/v2/authorize"}}
```
The HTTP response status isn't available.

**Describe the solution you'd like**
Make the HTTP response status available as a tag, presumably `http.status`.

**Describe alternatives you've considered**
None, not sure what I can do.

**Additional context**
Using Sleuth `2.2.3.RELEASE`.

**Comment by marcingrzejszczak** [comment]
We've been discussing this years ago. We're not setting the response status on the server side because we set it on the client side. We don't want to set it twice in order to reduce overhead in the span collector (e.g. Zipkin).

If you need to do it please create a bean of type `HttpResponseParser` and annotate it with `@HttpServerResponseParser`. There you can define the response status. E.g.

```java
class SleuthHttpServerParser implements HttpResponseParser {

	private static final String STATUS_CODE_KEY = "http.status";
	@Override
	public void parse(HttpResponse response, TraceContext context, SpanCustomizer span) {
		int httpStatus = response.statusCode();
		if (httpStatus == 0) {
			return; // already parsed the error
		}

		if (httpStatus == HttpServletResponse.SC_OK && response.error() != null) {
			// Filter chain threw exception but the response status may not have been set
			// yet, so we have to guess.
			span.tag(STATUS_CODE_KEY,
					String.valueOf(HttpServletResponse.SC_INTERNAL_SERVER_ERROR));
		}
		// only tag valid http statuses
		else if (httpStatus >= 100 && (httpStatus < 200) || (httpStatus > 399)) {
			span.tag(STATUS_CODE_KEY, String.valueOf(httpStatus));
		}
	}

}
```

**Comment by asarkar** [comment]
@marcingrzejszczak But client and server sides could be managed by very different teams and people, who don’t share their logs and/or metrics. Having the response status available on the client side may not help the server team at all. Using your suggestion, code can be written to capture the status, but it seems like a basic ask for any HTTP metric that should be there OOTB.

**Comment by marcingrzejszczak** [comment]
We're not planning to add this. We've migrated away from it and gave people option as presented above to add it back if necessary.
