### ISSUE TITLE
HTTP client integration docs does not mention WebClient.Builder beans

### ISSUE THREAD

**Issue by ciscoo** [spring-cloud/spring-cloud-sleuth#1716]
[Section 13.6.3](https://docs.spring.io/spring-cloud-sleuth/docs/current-SNAPSHOT/reference/html/#webclient) for `WebClient` has a callout for `WebClient` beans only.

This is somewhat misleading as it conveys that only `WebClient` beans are supported.

Examining the source of `TraceWebClientBeanPostProcessor` reveals that a [`WebClient.Builder` beans are also supported](https://github.com/spring-cloud/spring-cloud-sleuth/blob/391059f824e200953634048aee0b55bfc8c82bab/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientBeanPostProcessor.java#L80).

**Comment by marcingrzejszczak** [comment]
Indeed. Do you want to find a pull request with a fix to the docs at the 2.2.x branch?

**Comment by ciscoo** [comment]
Yes, I can submit a PR sometime today.

**Comment by marcingrzejszczak** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-sleuth/pull/1718
