### ISSUE TITLE
Provide a simple way to disable WebClient instrumentation

### ISSUE THREAD

**Issue by asibross** [spring-cloud/spring-cloud-sleuth#1717]
I am looking to disable the `TraceWebClientBeanPostProcessor` since I have my own simple brave instrumentation for WebClient.

I cannot just exclude it because it is being created in a nested configuration in [TraceWebClientAutoConfiguration](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientAutoConfiguration.java#L136) and the TraceWebClientAutoConfiguration is also in charge of providing other instrumentations (RestTemplate) that I don't want to exclude.

I had to implement a `BeanDefinitionRegistryPostProcessor` to remove it, but would have preferred to set a property, or add the AutoConfiguration to the exclude list.

I think adding a @ConditionalOnProperty on the nested configuration will suffice.

**Comment by marcingrzejszczak** [comment]
Are you willing to add a pull request to the master branch? We can make it `@ConditionalOnProperty` indeed.

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-sleuth/pull/1723
