### ISSUE TITLE
Provide ways to customize spans in reactor

### ISSUE THREAD

**Issue by voipp** [spring-cloud/spring-cloud-sleuth#1719]
I have the spring reactor app, and would like to customize spans, generated automatically.
I enabled sleuth:

```
spring.sleuth.enabled: true
spring.sleuth.reactor.enabled: true
```

and my code like the following:

```
@EventListener(classes = ApplicationReadyEvent.class)
    public void executeSendingNotificationToServer() { 

   return Mono.fromRunnable(() -> {
     tracer.currentSpan().tag("sample-key", "sample-value");
     tracer.currentSpanCustomizer().tag("sample-key", "sample-value2");
   })
   .then(<other business logic>)...
```

I can observer traces in jaeger , but they don't contain 'sample-key' tags at all. 

How to properly customize span in spring reactor?

**Comment by marcingrzejszczak** [comment]
Are you sure that the span is sampled?

**Comment by voipp** [comment]
> 
> 
> Are you sure that the span is sampled?

Yes. I have jaeger server running, and in jaeger UI i can see only 2 default tags, please take a look:

![Снимок](https://user-images.githubusercontent.com/5221372/90370782-9d6ab400-e076-11ea-9485-9add660bb1bc.PNG)

**Comment by marcingrzejszczak** [comment]
Can you log out the span from the runnable code?

**Comment by voipp** [comment]
I added some debug logging to my method:
`@EventListener(classes = ApplicationReadyEvent.class)
    public void executeSendingNotificationToServer() { 

   return Mono.fromRunnable(() -> {
     Span span = tracer.currentSpan();
            if (span != null)
                log.debug((span.toString() + " span with id: " + span.hashCode()));
     tracer.currentSpan().tag("sample-key", "sample-value");
     tracer.currentSpanCustomizer().tag("sample-key", "sample-value2");
   })
   .then(<other business logic>)...`
Portion of logs:
`
2020-08-17 10:50:33.138 DEBUG [notifications-gw,0a2544a5dbc01d8d,0a2544a5dbc01d8d,true] 11344 --- [     parallel-2] r.s.s.n.i.s.NotificationServiceExecutor  : LazySpan(0a2544a5dbc01d8d/0a2544a5dbc01d8d) span with id: 604568545
2020-08-17 10:50:33.196 DEBUG [notifications-gw,,,] 11344 --- [ender@6c9074e4}] .s.ZipkinRestTemplateSenderConfiguration : The port in Zipkin's URL [http://localhost:9411] is provided - that means that load balancing will not take place
2020-08-17 10:50:33.196 DEBUG [notifications-gw,,,] 11344 --- [ender@6c9074e4}] o.s.c.s.z.s.ZipkinRestTemplateWrapper    : HTTP POST http://localhost:9411/api/v2/spans
2020-08-17 10:50:33.196 DEBUG [notifications-gw,,,] 11344 --- [ender@6c9074e4}] o.s.c.s.z.s.ZipkinRestTemplateWrapper    : Accept=[text/plain, application/json, application/*+json, */*]
2020-08-17 10:50:33.196 DEBUG [notifications-gw,,,] 11344 --- [ender@6c9074e4}] o.s.c.s.z.s.ZipkinRestTemplateWrapper    : Writing [[B@1cd9dedc] as "application/json"
2020-08-17 10:50:33.198 DEBUG [notifications-gw,,,] 11344 --- [ender@6c9074e4}] o.s.c.s.z.s.ZipkinRestTemplateWrapper    : Response 202 ACCEPTED
`

**Comment by marcingrzejszczak** [comment]
Most likely it's the reactor instrumentation issue. 

In Sleuth 3.0.0 we'll give the user much more freedom to operate on reactor via https://docs.spring.io/spring-cloud-sleuth/docs/3.0.0-SNAPSHOT/reference/html/#webflux-support or https://docs.spring.io/spring-cloud-sleuth/docs/3.0.0-SNAPSHOT/reference/html/#spring-cloud-function-and-spring-cloud-stream

You can try turning off the `decorate-on-each` feature until you migrate https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/#project-reactor

**Comment by voipp** [comment]
I'm going to turn off sleuth on reactor:
`
spring.sleuth.reactor.enabled: false
`
And manually create spans and finish them in flux.

Do you find it correct way of tracing reactor?

**Comment by marcingrzejszczak** [comment]
The default instrumentation should work fine most of the time. Without a sample it's hard for me to reason about what's going on exactly. For sure if you take care of the tracing manually it should work better cause you pass on the tracing stuff in an explicit manner.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by voipp** [comment]
@marcingrzejszczak  Hello
can you please look at https://github.com/spring-cloud/spring-cloud-sleuth/issues/1741

**Comment by marcingrzejszczak** [comment]
Please do not cross post. I'm looking into the issues as soon as possible.
