### ISSUE TITLE
Trace information is missing when exception is thrown from Scheduled methods

### ISSUE THREAD

**Issue by sting2804** [spring-cloud/spring-cloud-sleuth#1729]
When an exception is thrown from a method annotated with @Scheduled all trace information is lost when it reaches the any implementation of error handler. 

Spring boot 2.3.3,  Sleuth connected via dependencyManagement - spring-cloud-dependencies Hoxton.SR8

[link for demo project](https://github.com/sting2804/traceId-bug-demo)

I think same problem as in [1663](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1663) and  [1660](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1660)

**Comment by marcingrzejszczak** [comment]
Can you please write this application in Java so that we're able to isolate the issue? I want to be sure that it's not related to Kotlin.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by jonatan-ivanov** [comment]
I'm reopening this: I created a Java example where I was able to repro the issue: https://github.com/jonatan-ivanov/sleuth-gh-1729.  It seems this has the same cause as the ones in the description, the error handling happens after the Span is closed.

This is where the tracing instrumentation happens: [TraceSchedulingAspect.java#L69-L74](https://github.com/spring-cloud/spring-cloud-sleuth/blob/ca2e15fc769ef4ce9988ac4c1142d4aa44b28f0f/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/scheduling/TraceSchedulingAspect.java#L69-L74)
And this is where the error handling takes place: [TaskUtils.java#L93-L97](https://github.com/spring-projects/spring-framework/blob/885f6dbab94712fa76545276058a62216e17881e/spring-context/src/main/java/org/springframework/scheduling/support/TaskUtils.java#L93-L97) through [/DelegatingErrorHandlingRunnable.java#L56-L61](https://github.com/spring-projects/spring-framework/blob/885f6dbab94712fa76545276058a62216e17881e/spring-context/src/main/java/org/springframework/scheduling/support/DelegatingErrorHandlingRunnable.java#L56-L61)

**Comment by jonatan-ivanov** [comment]
I'm closing this in favor of https://github.com/spring-projects/spring-framework/issues/26533
