### ISSUE TITLE
Sleuth + Webflux + gRPC unexpected behavior

### ISSUE THREAD

**Issue by oburgosm** [spring-cloud/spring-cloud-sleuth#1735]
I have a Webflux application that call a grpc server using a reactive grpc client. When I invoke the controller, I expect that there are three spans in the same trace. This expected behavior (considered OK) occurs with Hoxton.SR2 but beginning with Hoxton.SR3 and every version up to Hoxton.SR8 (included) we see that there are  two traces, one for http server and another for grpc spans. The unexpected behavior only occurs if I have a subscribeOn on my reactive controller. I'm not sure if it is a sleuth reactor integration problem or brave grpc instrumentation.

I have an application to reproduce it at https://github.com/oburgosm/sleuth-grpc-test

**Comment by marcingrzejszczak** [comment]
I've just checked in a change in Sleuth (https://github.com/spring-cloud/spring-cloud-sleuth/commit/0242859cc692baf2e1357497636b07210d4c7a69), turned on the `spring.sleuth.reactor.decorate-queues: true` option and I got the following result:

![image](https://user-images.githubusercontent.com/3297437/115257866-c75a0600-a130-11eb-989b-e05f5b2299c2.png)
