### ISSUE TITLE
Sleuth does not work in Coroutines context

### ISSUE THREAD

**Issue by ninja-inc** [spring-cloud/spring-cloud-sleuth#1737]
**Describe the bug**
traceId, spanId and exportable are not printed in Coroutines context.

Versions
Spring Boot: 2.3.3.RELEASE
Spring Cloud: Hoxton.SR8

**Sample**
You can see full code by [sleuth-coroutines](https://github.com/ninja-inc/sleuth-coroutines).

```
	@GetMapping("/hello")
	suspend fun hello(): Map<String, String> {
		log.info("in main context")

		GlobalScope.launch {
			log.info("in Coroutines context (launch)")
		}

		GlobalScope.async {
			log.info("in Coroutines context (async)")
		}.await()

		return mapOf(
			"msg" to "hello"
		)
	}
```

Printed log messages
```
2020-09-12 21:03:15.306  INFO [sleuth-coroutines,42883585174b8ae0,42883585174b8ae0,true] 22621 --- [ctor-http-nio-2] c.e.sleuthcoroutines.WebController       : in main context
2020-09-12 21:03:15.312  INFO [sleuth-coroutines,,,] 22621 --- [atcher-worker-2] c.e.sleuthcoroutines.WebController       : in Coroutines context (async)
2020-09-12 21:03:15.312  INFO [sleuth-coroutines,,,] 22621 --- [atcher-worker-1] c.e.sleuthcoroutines.WebController       : in Coroutines context (launch)
```

**Comment by buehlerjochen** [comment]
This issue is somewhat mitigated by coroutine's slf4j support, that carries the MDC context into the coroutine:
```
GlobalScope.launch(MDCContext()) {
    // your code goes here
}
```

However, it does not work with the automatic instrumentation of RestTemplates when calling another service. The tracing headers seem not to be set on RestTemplates used within coroutines. Only solution I know of so far uses a special Callable class and is described here: https://stackoverflow.com/questions/47026664/spring-sleuth-zipkin-spans-not-nesting-in-kotlin-coroutine

**Comment by marcingrzejszczak** [comment]
Done via #1977

**Comment by tmdgusya** [comment]
is supported kotlin corotine? 
i think only supported reactor-coroutine..

**Comment by marcingrzejszczak** [comment]
Yes, we support Kotlin Coroutines as you can see in https://github.com/spring-cloud/spring-cloud-sleuth/pull/1977

**Comment by tmdgusya** [comment]
i'm migration my code that using spring async to coroutine code (see below code). but sleuth not working

```kotlin
   @Async(CUSTOM)
    fun asyncExecute(
        lockName: String,
        lockConfig: LockConfig,
        executingFunction: () -> Unit,
    )  {
        execute(lockName, lockConfig, executingFunction)
    }
```
sleuth working well
to

```kotlin
    fun asyncExecute(
        lockName: String,
        lockConfig: LockConfig,
        executingFunction: () -> Unit,
    ) = GlobalScope.launch(context = MDCContext() + customTaskExecutor, start = CoroutineStart.DEFAULT) {
        execute(lockName, lockConfig, executingFunction)
    }
```

sleuth not working

**Comment by marcingrzejszczak** [comment]
I'm not an expert in Kotlin - this is how we're using Sleuth & Kotlin Coroutines and how things seem to be working https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-instrumentation/src/test/kotlin/org/springframework/cloud/sleuth/instrument/kotlin/AsContextElementKtTests.kt

**Comment by tmdgusya** [comment]
i use 2.2.8 RELEASE but i can't find simpletracer

<img width="529" alt="image" src="https://user-images.githubusercontent.com/57784077/171589162-48886531-16b3-445b-9eae-59807e565909.png">

**Comment by marcingrzejszczak** [comment]
Maybe that's because you're using 2.2.8? Please upgrade to the latest version.

If you check the `SimpleTracer` code you'll see `@since 3.0.4`. 

Kotlin code got added in 3.1.0.

**Comment by tmdgusya** [comment]
okey thank you i'll upgrade version!

**Comment by AndreVelde** [comment]
I am using spring boot version 2.7.17 with cloud version 2021.0.8 but cant find this SimpleTracer dependency. Even though with `./gradlew dependencyInsight --dependency spring-cloud-starter-sleuth` it is saying that I am using version: 3.1.9 which is higher than 3.1.0. So what am I missing?
