### ISSUE TITLE
Existing Span is modified for @Async annotated methods

### ISSUE THREAD

**Issue by notizklotz** [spring-cloud/spring-cloud-sleuth#1738]
**Describe the bug**

Spring Cloud Hoxton SR8
Spring Cloud Sleuth 2.2.5

According to https://docs.spring.io/spring-cloud-sleuth/docs/2.2.5.RELEASE/reference/html/#async-annotated-methods Sleuth should create a new Span for `@Async` annotated methods.
However, in my MVC based application I observe that the information of the already existing Span created by Sleuth's HTTP Filter is modified. The name of the existing Span ist overwritten so instead of the the originating URL I see the name of my async method on the top span.

Having a look at `org.springframework.cloud.sleuth.instrument.async.TraceAsyncAspect` I can see that it actually only starts a new Span if there is no current Span:

```
	public Object traceBackgroundThread(final ProceedingJoinPoint pjp) throws Throwable {
		String spanName = name(pjp);
		Span span = this.tracer.currentSpan();
		if (span == null) {
			span = this.tracer.nextSpan();
		}
		span = span.name(spanName);
		try (Tracer.SpanInScope ws = this.tracer.withSpanInScope(span.start())) {
			span.tag(CLASS_KEY, pjp.getTarget().getClass().getSimpleName());
			span.tag(METHOD_KEY, pjp.getSignature().getName());
			return pjp.proceed();
		}
		finally {
			span.finish();
		}
	}
```

**Comment by marcingrzejszczak** [comment]
Can you show us what your code looks like?

**Comment by notizklotz** [comment]
I created a small demo app to showcase the problem at https://github.com/notizklotz/sleuth-demo

There are three cases implemented:

1. Sync case
2. Async case using `supplyAsync()`
3. Async case using `@Async` 

I included a screenshot of Zipkin with the results: https://github.com/notizklotz/sleuth-demo/blob/master/resulting-spans.png

Case 1 and 2 work as expected with case 2 producing a Trace with a child Span.
Case 3 produces one Span with the name being overwritten. According to the documentation I would expect this to produce a Trace named "get /ping-async-annotated" with a child Span named "async-annotated".

**Comment by marcingrzejszczak** [comment]
OK I checked this issue and now I remember what the problem is. We are typically overriding the `async` span that was created by wrapping an executor service and that we don't have really that much of a control over.

I will update the docs to change that statement + I'll mention that it's worth annotating a `@Async` based method with a `@NewSpan` annotation so that the newly created span will get modified and not the one from e.g. the controller.

**Comment by notizklotz** [comment]
Thank you for the clarification!
