### ISSUE TITLE
tracing doesn't work with spring cloud stream StreamBridge

### ISSUE THREAD

**Issue by erohana** [spring-cloud/spring-cloud-sleuth#1739]
when using spring cloud stream for RabbitMQ and producing messages with [`StreamBridge`](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/StreamBridge.java), tracing propagation/baggage doesn't work

I tried to debug the code of `StreamBridge` and sleuth, seems to be no instrumuntation for StreamBridge.

i tried to use spring cloud stream MessageChannel to send message, and my code works - i see the tracing and my custom propogation headers added to rabbitMQ

according to [spring cloud sleuth docs for spring cloud stream](https://docs.spring.io/spring-cloud-sleuth/docs/2.2.5.RELEASE/reference/html/#spring-integration-and-spring-cloud-stream) 
```
Propagation.Setter<MessageHeaderAccessor, String> 
Propagation.Getter<MessageHeaderAccessor, String>
```

should be called to insert the headers, but from code debbuging i see neither the Getter or Setter are called

spring boot version: 2.2.5.RELEASE
spring cloud version: Hoxton.SR5 

**Sample**
just produce a simple message using StreamBridge

is there any workaround/suggestion i can do until it is solved ?

**Comment by marcingrzejszczak** [comment]
It's added for 3.0.0 - https://github.com/spring-cloud/spring-cloud-sleuth/commit/bd149ce4a7c2154fe8526394d14b6ab89addd62e . Spring Cloud Stream & Function brought additional classes in to allow instrumentation but it's only available in the recent release of stream & function.

**Comment by erohana** [comment]
i see the latest version of spring cloud is Hoxton.SR8 which includes sleuth 2.2.5.RELEASE
so i understand 3.0.0 is not released yet ?

**Comment by marcingrzejszczak** [comment]
Nope, not yet. It will be part of the 2020.0.0 release train.
