### ISSUE TITLE
Don't make tracing start eagerly around Callable/Runnable

### ISSUE THREAD

**Issue by ryan-ju** [spring-cloud/spring-cloud-sleuth#174]
Finalge works this way: before a Function runs on a thread, the current thread context is stored, then the Function's context (the context in which the Function is defined, which could be in a different thread) is restored, then the Function is executed, and finally the stored context is restored.

This allows 2 things:
1. execution context is preserved across threads.
2. a Function may create new Functions, and they will use the same context.

Currently _DefaultTracer_ only provides wrap() methods, which starts a span "eagerly" around Runnable/Callable.  There should an option to allow the storing-restoring-restoring of SpanContext like that in Finalge.

**Comment by adriancole** [comment]
Thanks for the explanation! Do you feel comfortable implementing this, if
others agree with this path?

**Comment by marcingrzejszczak** [comment]
> Currently *DefaultTracer* only provides wrap() methods, which starts a
span "eagerly" around Runnable/Callable. There should an option to allow
the storing-restoring-restoring of SpanContext like that in Finalge.

Maybe I misunderstood sth but we don't start a span at that point. The span
is started when the wrapped object is executed. When we're wrapping we just
pass the "context".

**Comment by ryan-ju** [comment]
> The span
is started when the wrapped object is executed.
Sorry I didn't explain it clearly.  What I meant is that the span shouldn't be started when the object is executed, but rather the code inside the object to start the span.  

An example:

```
Runnable run = () -> {
    Span span1 = tracer.startTrace(...);
    // Some code
    span1.close();
    Span span2 = tracer.startTrace(...);
    // Some code
    span2.close();
}

class DefaultTracer {
// Other code

public Runnable wrapContext(Runnable runnable) {
    Span stored = tracer.getCurrentSpan();
    return () -> {
        Span previous = tracer.getCurrentSpan();
        SpanContextHolder.push(stored, false);
        runnable.run();
        SpanContextHolder.push(previous false);
    }
}
```

This lets runnable run in the same SpanContext it was wrapped, but not actually dictates that a Span should be started when the runnable starts.  This gives runnable the freedom to create spans when it wants to.

**Comment by marcingrzejszczak** [comment]
so ATM we have the same scenario but we're wrapping it all in one more span. You still can create spans inside the runnable - that's perfectly legit

**Comment by ryan-ju** [comment]
@marcingrzejszczak That's correct.  But this one extra layer of span may be cumbersome for tracing, as it adds unnecessary noise to the span tree.  It would be nice to have a way to stop it.
