### ISSUE TITLE
required JmsPoolConnectionFactory ,but LazyTopicConnectionFactory

### ISSUE THREAD

**Issue by kewkew1026** [spring-cloud/spring-cloud-sleuth#1740]
**Describe the bug**
when i use sleuth ,and my project hava used activemq. i can not run application.
error info:
 Bean named 'jmsConnectionFactory' is expected to be of type 'org.messaginghub.pooled.jms.JmsPoolConnectionFactory' but was actually of type 'org.springframework.cloud.sleuth.instrument.messaging.LazyTopicConnectionFactory'

**Comment by kewkew1026** [comment]
i have solved .as i close  sleuth jms check.
spring.sleuth.messaging. jms.enabled: false.
but when i want open, how i can solve this problem ?

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
