### ISSUE TITLE
How to set Process-level tags for span?

### ISSUE THREAD

**Issue by voipp** [spring-cloud/spring-cloud-sleuth#1741]
Im using brave 5.9.0 library in my spring reactor project for tracing.
Traces are sent to Jaeger server, example of my trace: 
![Снимок](https://user-images.githubusercontent.com/5221372/94487465-b7f18a80-01e9-11eb-82e6-653c58ef47af.PNG)

two questions:
1)What is the purpose of **Process** section?
2)How can i add properties to this section with my brave Tracer ?

**Comment by marcingrzejszczak** [comment]
I have no idea what Process is, it seems to be Jaeger specific. Please ask them in their repo and ask them how that section can be populated when sending zipkin compatible spans.

**Comment by jpkrohling** [comment]
Tags in the `process` part are tags that are added by a Jaeger component (client/tracer, agent, collector) to all spans it sees. To add such tags, you do need to use either a Jaeger client, the Jaeger agent (`--agent.tags`) or the Jaeger collector (`--collector.tags`), or the OpenTelemetry equivalents (where it's called `Resource`).

**Comment by marcingrzejszczak** [comment]
We don't support that at this point.
