### ISSUE TITLE
DirectRabbitListenerContainerFactory not instrumented for tracing, whereas SimpleRabbitListenerContainerFactory is

### ISSUE THREAD

**Issue by abadelt** [spring-cloud/spring-cloud-sleuth#1751]
Hi, 
I've noticed that some of our services aren't logging Sleuth trace ids. When making a comparison I found that those just annotating listener methods with
  `@RabbitListener(queues = "...") `
are working as expected, whereas those using 
  `@RabbitListener(queues = "...", containerFactory = "someContainerFactory")`
where `someContainerFactory` returns an instance of `DirectRabbitListenerContainerFactory`
are _not_ adding trace ids when logging from invocations of those listener methods.

Investigating further, I saw that `org.springframework.cloud.sleuth.instrument.messagingTraceMessagingAutoConfiguration`  is decorating `org.springframework.amqp.rabbit.config.SimpleRabbitListenerContainerFactory` (which I believe is the default), but not the newer `DirectRabbitListenerContainerFactory` in the same package.

Is it deliberately not decorated, or has the sleuth project just not caught up with the rabbit support yet?

**Comment by marcingrzejszczak** [comment]
> Is it deliberately not decorated, or has the sleuth project just not caught up with the rabbit support yet?

I guess we haven't caught up. Are you interested in filing a PR to fix this? You can file it against the 2.2.x branch and I'll then apply it to master.

**Comment by marcingrzejszczak** [comment]
Actually this first needs to be fixed in Brave. Can you please file an issue there? The `brave.spring.rabbit.SpringRabbitTracing` class can only instrument `SimpleRabbitListenerContainerFactory`.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
