### ISSUE TITLE
Support for java.net.http.HttpClient

### ISSUE THREAD

**Issue by abrudin** [spring-cloud/spring-cloud-sleuth#1753]
**Is your feature request related to a problem? Please describe.**
We are using Java 11:s HttpClient (java.net.http.HttpClient) in some of our projects but there is no mentioning of that client in the documentation for sleuth. It seems reasonable to include that seeing that it is a very natural choice of HttpClient for modern Java applications.

**Describe the solution you'd like**
I would like to be able to expose my java.net.http.HttpClients as beans and get them picked up by Sleuth.

**Comment by marcingrzejszczak** [comment]
Are you interested in providing instrumentation for that?

**Comment by abrudin** [comment]
I'm not 100% sure what that would entail, but I would be happy to help out in any way I can.

**Comment by marcingrzejszczak** [comment]
The thing is that we are unable to provide instrumentations for every single project. So if there's one person that wants the `HttpClient` instrumentation then we don't have the capacity to implement and then support this.

**Comment by dimi-nk** [comment]
I might be wrong, but when I investigated the same issue I realised `java.net.http.HttpClient` doesn't support a mechanism to intercept incoming or outgoing calls. Therefore, you'd need to introduce a wrapper around the library which allows for interception like https://github.com/raphw/interceptable-http-client

**Comment by marcingrzejszczak** [comment]
Let's close this issue for the time being. If there are more people interested in it we'll revive it :)

**Comment by aowss** [comment]
if by jdk http client support we mean the trace id is passed automatically as is the case for a rest template, then i am interested and i imagine a lot of people are since as mentioned above that's a natural choice

**Comment by bademux** [comment]
+1

**Comment by jansoren** [comment]
+1

**Comment by jansoren** [comment]
If you do not have the opportunity to remove HttpClient you can add these headers:

```
    @Autowired
    private final Tracer tracer;
    
    private Map<String, String> createHeaders() {
        Map<String, String> headers = new HashMap<>();
        headers.put("x-b3-traceid", tracer.currentSpan().context().traceIdString());
        headers.put("x-b3-spanid", tracer.currentSpan().context().spanIdString());
        headers.put("x-b3-parentspanid", tracer.currentSpan().context().parentIdString());
        headers.put("x-b3-sampled", tracer.currentSpan().context().sampled().toString());
        return headers;
    }
```

**Comment by marcingrzejszczak** [comment]
I'd suggest using the `Propagator` bean instead of setting the headers manually.

It would be sth like this

```java

@Autowired Propagator propagator;
@Autowired Tracer tracer;

propagator.inject(tracer.currentSpan().context(), headers, carrier, key, value -> header.put(key, value));
```

that way regardless of the chosen propagation mechanism this will work
