### ISSUE TITLE
Sleuth + WebMVC + log4j2 can't log traceId and spanId

### ISSUE THREAD

**Issue by zhanglei-1987** [spring-cloud/spring-cloud-sleuth#1764]
Sleuth + WebMVC + log4j2 can't log traceId and spanId

log4j2 version:  2.11.0
spring-boot version: 2.3.2.RELEASE

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
