### ISSUE TITLE
need a way to show method names of the classes instead of send and handle spans

### ISSUE THREAD

**Issue by muhammadnkhan** [spring-cloud/spring-cloud-sleuth#1772]
For spans ingested via Wavefront spring boot starter with sleuth, with following configuration;
<img width="1092" alt="xml" src="https://user-images.githubusercontent.com/34246923/99101270-faa4d180-25a1-11eb-9561-51384ec7a532.png">

In the Wavefront tracing UI, we are seeing a lot of “send” and “handle” methods instead of method names, of the classes, which are called.
If you see the screenshot below, it is showing on the left side uComCustomerSvcs send. Is it possible to see name of channel directly here which is evReadCustomerChannel. Currently, it shows as channel tag on right hand side of UI.  

![send](https://user-images.githubusercontent.com/34246923/99105157-a43a9180-25a7-11eb-8840-9f6d38fc004e.png)
 
Similarly for handle (see screenshot below), they cannot see the real called class / method name at all. It would be good to see EnrollVaultAdapterClient#readCustomer (see XML config above). Is it possible?
If this is not feasible then can it show serviceActivator (enrollVaultReadCustomerService) instead?.

<img width="1868" alt="handle" src="https://user-images.githubusercontent.com/34246923/99105185-ae5c9000-25a7-11eb-968e-0f05bf485a47.png">

**Comment by marcingrzejszczak** [comment]
> In the Wavefront tracing UI, we are seeing a lot of “send” and “handle” methods instead of method names, of the classes, which are called.

Yes cause conceptually you `send` and `handle` messages - that makes perfect sense. It's the same for HTTP - you see `http post` or `http get`. The problem we might see is that we can see a lot of `handle` and `send` within the same application. Are you referring to that example?

> Similarly for handle (see screenshot below), they cannot see the real called class / method name at all. It would be good to see EnrollVaultAdapterClient#readCustomer (see XML config above). Is it possible?

Do you have a sample that replicates this issue?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by muhammadnkhan** [comment]
we would like the span name to be channel= name which is currently a span tag
right now the span names i.e. method names are too generic -i.e.  "send" and "handle"
and the customer was complaining that they want more concrete values for the span names, preferably the channel name
