### ISSUE TITLE
add span tag in sleuth

### ISSUE THREAD

**Issue by muhammadnkhan** [spring-cloud/spring-cloud-sleuth#1773]
For spans ingested via Wavefront spring boot starter with sleuth, there is a span tag http.path but not for URL which was called. Can we add it as a tag in sleuth? See screenshot.

<img width="1234" alt="image006" src="https://user-images.githubusercontent.com/34246923/99105237-c59b7d80-25a7-11eb-9e3e-abdea2536103.png">

**Comment by marcingrzejszczak** [comment]
What do you mean by "but not for the URL which was called", what would be the expected tag value in your opinion then?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by muhammadnkhan** [comment]
Customer is requesting if the remote url that was called can be made visible as tag value.

**Comment by marcingrzejszczak** [comment]
that's already possible via the https://docs.spring.io/spring-cloud-sleuth/docs/2.2.6.RELEASE/reference/html/#data-policy

```
@Configuration
class Config {
  @Bean(name = { HttpClientRequestParser.NAME, HttpServerRequestParser.NAME })
  HttpRequestParser sleuthHttpServerRequestParser() {
      return (req, context, span) -> {
          HttpRequestParser.DEFAULT.parse(req, context, span);
          String url = req.url();
          if (url != null) {
              span.tag("http.url", url);
          }
      };
  }
}
```
