### ISSUE TITLE
Upstream header propagation

### ISSUE THREAD

**Issue by maxxedev** [spring-cloud/spring-cloud-sleuth#1776]
**Is your feature request related to a problem? Please describe.**
Add support for propagating baggage field headers upstream.

For example, given a series of service requests: WEB -> A -> B -> ... -> X, it should be possible for a service M to set an extra baggage field such that not only is the field propagated downstream to N, O, etc. but also the field is propagated upstream to M, L, etc.

**Describe the solution you'd like**
If a baggage field meant for upstream propagation is set in current trace context, then server should include additional headers in the response.
Clients should parse the response headers and subsume the extra bagge field into its current trace context.

**Describe alternatives you've considered**
Custom interceptors to implement above behavior

**Comment by marcingrzejszczak** [comment]
I think that this can lead to problems related to merging baggage entries. I have not heard of any tracer actually allowing this. If you have a custom interceptor you can paste it here as a comment on how you fixed this problem, however I don't think it's actually a good idea to do it like this. I'm closing this issue for now.
