### ISSUE TITLE
Support `tags` attribute in `@NewSpan` annotation

### ISSUE THREAD

**Issue by making** [spring-cloud/spring-cloud-sleuth#1780]
**Is your feature request related to a problem? Please describe.**
There are cases where specific tags are required.
For example: Visualizing external services in Wavefront https://docs.wavefront.com/tracing_external_services.html

Currently, `@NewSpan` + `@SpanTag` support only dynamic tags through arguments.
In order to meet the above requirements, it is necessary to programmatically add tags via `Span#tag` API.

It would be very convenient if static tags can be put into a `@NewSpan` annotation.

**Describe the solution you'd like**

Add `tag` attribute in `@NewSpan`. The usage looks like bellow:

```java
@NewSpan(tags = {"component=java-jdbc", "db.type=postgresql", "db.instance=stylingDB"})
```

**Describe alternatives you've considered**

Introducing a new annotation such as`@StaticSpanTag` annotation instead of String key-values is type-safer but might be too verbose.

```java
@NewSpan(tags = {@StaticSpanTag(key = "component", value = "java-jdbc"), 
                 @StaticSpanTag(key = "db.type", value = "postgresql"), 
                 @StaticSpanTag(key = "db.instance", value = "stylingDB")})
```

**Comment by making** [comment]
Another suggestion that is similar to Micrometer's [`@Timed`](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/annotation/Timed.java#L38)
```java
@NewSpan(extraTags = { "component", "java-jdbc", "db.type", "postgresql", "db.instance", "stylingDB"})
```

**Comment by marcingrzejszczak** [comment]
We are not planning to add any new features to Sleuth
