### ISSUE TITLE
Cannot disable baggage propagation for brave

### ISSUE THREAD

**Issue by maxxedev** [spring-cloud/spring-cloud-sleuth#1781]
**Describe the bug**
When propagation type is set to W3C, each extra bagge field is sent twice. once in "baggage" header and once on its own.
```
baggage: country-code1=A,country-code2=B
country-code1: A
country-code2: B
```

With otel, setting `spring.sleuth.otel.propagation.sleuth-baggage.enabled=false` ensures that only "baggage" header is sent. 
Setting equivalent headers for brave has no effect:
```
spring.sleuth.brave.propagation.sleuth-baggage.enabled=false
```

Please fix so that it's possible to avoid sending duplicate baggage headers in W3C propagation with brave

spring cloud sleuth version: 3.0.0-M5

**Comment by marcingrzejszczak** [comment]
Can you describe exactly how you passed the propagation type? Did you set `B3` and `W3C` or `W3C` only?

**Comment by maxxedev** [comment]
W3C only

**Comment by maxxedev** [comment]
maven pom:
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-dependencies</artifactId>
	<version>2020.0.0-M5</version>
	<type>pom</type>
	<scope>import</scope>
</dependency>

<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-sleuth</artifactId>
</dependency>
```

application.properties:
```
spring.sleuth.brave.propagation.sleuth-baggage.enabled=false
spring.sleuth.baggage.remote-fields=my-header,my-header2
spring.sleuth.baggage.correlation-fields=my-header,my-header2
spring.sleuth.baggage.correlation-enabled=true
spring.sleuth.propagation.type=W3C
```

code:
```
tracer.createBaggage("my-header").set("new-value");
tracer.createBaggage("my-header2").set("new-value2");
tracer.createBaggage("my-header3").set("new-value3");
```

**Comment by marcingrzejszczak** [comment]
@maxxedev you can try against latest snapshots. You should not need to do anything really.

**Comment by maxxedev** [comment]
thanks. seems to work fine. had to fiddle a bit because of package renames

**Comment by marcingrzejszczak** [comment]
Cool! You can check out this doc https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#300-m6 to see the release notes with breaking changes
