### ISSUE TITLE
As part of the 3.0.0-M5 release, org.springframework.cloud:spring-cloud-starter-zipkin:3.0.0-M5 dependency not found

### ISSUE THREAD

**Issue by chrismathews** [spring-cloud/spring-cloud-sleuth#1782]
I am moving from Spring Cloud 2020.0.0-M4 which updates Spring Cloud Sleuth from 3.0.0-M4 to 3.0.0-M5. During this update I was unable to resolve org.springframework.cloud:spring-cloud-starter-zipkin:3.0.0-M5.

Looking at the Spring Milestone Repo I can see previous releases:
- 3.0.0-M1: https://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-starter-zipkin/3.0.0.M1/
- 3.0.0-M2: https://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-starter-zipkin/3.0.0.M2/
- 3.0.0-M3: https://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-starter-zipkin/3.0.0.M3/
- 3.0.0-M4: https://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-starter-zipkin/3.0.0.M4/
- No 3.0.0-M5

Is this expected or some issue during the release process? I looked at the closed issues for 3.0.0-M5 (https://github.com/spring-cloud/spring-cloud-sleuth/issues?q=is%3Aclosed+milestone%3A3.0.0-M5) and nothing jumped out at me that this would be expected.

**Comment by marcingrzejszczak** [comment]
Yes this is expected. You have to use the spring cloud starter sleuth and a spring cloud sleuth zipkin dependencies. You can read more about it here https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#spring-cloud-sleuth

**Comment by chrismathews** [comment]
Thanks @marcingrzejszczak! I will attempt to read better next time. ;)
