### ISSUE TITLE
Illegal embedded sign character - spring cloud sleuth + configserver in Brixton M5

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-sleuth#179]
see https://github.com/spring-cloud/spring-cloud-netflix/issues/837

**Comment by dsyer** [comment]
How are you connecting to the app (browser, curl, etc)? Steps to reproduce (and maybe a sample project) would be very helpful.

**Comment by cforce** [comment]
i feared you will say that ..its some work to do extract the code from the one i am not allowed to pass out. 

I guess the request is issues by the spring boot admin server ( https://github.com/codecentric/spring-boot-admin ). The admin asks all microservices for the info's. 
Why do you think the cause is on client side? .. I would expect the tracing is done on server side and therefore the issue shall be searched there.

**Comment by cforce** [comment]
I tracked down the cause.
This is my request:

`HttpServerExchange{ GET /management/configprops request {Accept=[application/json, text/plain, */*], Accept-Language=[de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4], Accept-Encoding=[gzip], X-Span-Name=[http/admin/ui/api/applications/f2367ee1/configprops], User-Agent=[Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36], X-Trace-Id=[77198da9-a88f-4017-ad3f-7598420fa58a], Connection=[Keep-Alive], X-Span-Id=[77198da9-a88f-4017-ad3f-7598420fa58a], x-forwarded-proto=[http], Cookie=[JSESSIONID=92F6474BAB06B8187C96F0390FF52392], Referer=[http://localhost:8602/admin/ui/], x-forwarded-host=[localhost:8602], x-forwarded-prefix=[/admin/ui/api/applications/f2367ee1/configprops], Host=[localhost:8624]} response {}}`
The exception throws because the Span.fromHex(String hexString) tries con convert
"77198da9-a88f-4017-ad3f-7598420fa58a" (X-Trace-Id) to an BigInteger. That fails cause of the "-" signs.

**Comment by marcingrzejszczak** [comment]
We've migrated from UUID IDs to long based IDs. ATM the ID is in fact a random Long so you have to change the way you're generating ids
