### ISSUE TITLE
TraceWebServletAutoConfiguration should back of if spring-webmvc is not on the classpath

### ISSUE THREAD

**Issue by nioertel** [spring-cloud/spring-cloud-sleuth#1790]
Problem description
===============
We're using spring-cloud-sleuth for tracing instrumentation of Jersey-based REST endpoints, Spring's RestTemplate and others.
As we don't want to unnecessarily pollute the classpath, we exclude certain transitive dependencies which we don't need. E.g.:
```xml
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-sleuth</artifactId>
  <exclusions>
    <exclusion>
      <groupId>io.zipkin.brave</groupId>
      <artifactId>brave-instrumentation-jms</artifactId>
    </exclusion>
    <exclusion>
      <groupId>io.zipkin.brave</groupId>
      <artifactId>brave-instrumentation-messaging</artifactId>
    </exclusion>
    <!-- ... -->
  </exclusions>
</dependency>
```

Generally this is working fine as e.g. in case of `TraceMessagingAutoConfiguration` there is a `@ConditionalOnClass(MessagingTracing.class)` present that ensures the auto configuration backs off.

However in case of spring-webmvc this is not the case. The `TraceWebServletAutoConfiguration` always tries to initialise itself and imports `SpanCustomizingAsyncHandlerInterceptor` which can't resolve `HandlerInterceptorAdapter` as it's not on the classpath.

Envionment
=========
spring-boot-2.3.4.RELEASE with spring-cloud-sleuth-core-2.2.5.RELEASE
I didn't check if the refactoring in 3.0.0 fixes the issue but on the first look it doesn't seem to.

Potential solution
=============
Current workaround is `@EnableAutoConfiguration(exclude = { TraceWebServletAutoConfiguration.class })` but that won't work for long anymore because `TraceWebServletAutoConfiguration` has already been marked as `@Deprecated`.
Simple solution would probably be adding `@ConditionalOnClass(HandlerInterceptorAdapter.class)`.

If you confirm this approach I'm happy to prepare a pull request.

**Comment by marcingrzejszczak** [comment]
Yeah absolutely be my guest and go with the `@ConditionalOnClass(HandlerInterceptorAdapter.class)`  Please prepare a PR against the 2.2.x branch. A test would be more than welcome :)
