### ISSUE TITLE
Missing Correlation in Logs

### ISSUE THREAD

**Issue by gmiano** [spring-cloud/spring-cloud-sleuth#1792]
Hi,
I am facing a problem integrating sleuth with my spring boot component. I am developing a Spring Boot application using latest version (2.4.0) and I use slf4j (1.7.30) to log messages.

I configured logging library using the logback-spring.xml:
```
<configuration>
  <springProperty scope="context" name="springAppName" source="spring.application.name"/>
  <property name="LOG_DATEFORMAT_PATTERN" value="yyyy-MM-dd'T'HH:mm:ss.SSSSSXXX, UTC"/>
  <property name="LOG_LEVEL_PATTERN" value="%-5level"/>
  <property name="PID" value="[${springAppName:- },%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}]"/>
  <property name="STDOUT_THRESHOLD_LEVEL" value="${e:-INFO}"/>

  <include resource="org/springframework/boot/logging/logback/base.xml"/>

  <logger name="com.doxee" level="${STDOUT_THRESHOLD_LEVEL}"/>
  <logger name="org.springframework" level="${STDOUT_THRESHOLD_LEVEL}"/>

  <root level="WARN"/>
</configuration>

```

and added the library dependency in my pom:

```
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-sleuth</artifactId>
        <version>3.0.0-M5</version>
      </dependency>

```

Considering this configuration I would have expected a log like this:

> 2020-11-28T12:52:00.00372Z INFO  [lea-outbound-connector,7a208bddafd5a1a0,2499eb6bc6915d7c] --- [ntainer#0-0-C-1] c.d.l.o.core.ProcessRunner               : Process ended correctly, returning 195.

But I rather obtain this:

> 2020-12-01T17:43:43.00603Z DEBUG [alalalaextraction-service,,] --- [ntainer#0-0-C-1] c.d.r.e.service.core.ReportEventManager  : Event management started

Library seems to work properly as in the integration with a Kafka broker I see that message contains the header b3 with span-trace-execution.

![image](https://user-images.githubusercontent.com/11851632/100778378-3d223700-3407-11eb-8186-26277d6069ba.png)

Best regards,
Giuseppe.

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by marcingrzejszczak** [comment]
Also instead of `  <property name="PID" value="[${springAppName:- },%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}]"/>` 
try `  <property name="PID" value="[${springAppName:- },%X{traceId:-},%X{spanId:-}]"/>`. 

Check this doc https://github.com/spring-cloud/spring-cloud-sleuth/wiki/Spring-Cloud-Sleuth-3.0-Migration-Guide#x-b3--mdc-fields-names-are-no-longer-set

**Comment by gmiano** [comment]
@marcingrzejszczak it was simply logback configuration as you suggested. My fault not to check if MDC fields format changed in the new major version.

Thank you,
Giuseppe.

**Comment by marcingrzejszczak** [comment]
No problem.
