### ISSUE TITLE
Missing ParentSpanId in Messages Header

### ISSUE THREAD

**Issue by gmiano** [spring-cloud/spring-cloud-sleuth#1793]
Hello,
I am using spring-cloud-sleuth in a SpringBoot application that receives HTTP requests and produces messages to a Kafka broker. I recently updated libraries version and I moved to spring-boot 2.4.0 and spring-cloud-sleuth 3.0.0-M5  from spring-boot 2.1.4 and spring-cloud-sleuth 2.1.1.RELEASE.

In this shift I noticed a difference between the two implementations. Previously, messages contained the following headers
![image](https://user-images.githubusercontent.com/11851632/100847950-c0cc3a00-3480-11eb-9a39-952d6aaffa7c.png)
while now I see:
![image](https://user-images.githubusercontent.com/11851632/100847999-cf1a5600-3480-11eb-8c9c-80cc9eb08067.png)

I understand the reason of this shift (be compliant with headers naming and efficiently use Kafka) but I was wondering wether you removed ParentSpanId from b3 header, which may be helpful to identify the producer thread.
It could be sufficient to use SpanId, but I noticed that the value injected for SpanId is not the Id of message producer but a brand new one.

Thank you,
Giuseppe.

**Comment by marcingrzejszczak** [comment]
What if you set the following bean?

```
@Bean
PropagationFactorySupplier myPropagationFactorySupplier() {
  return () -> B3Propagation.newFactoryBuilder().injectFormat(B3Propagation.Format.SINGLE).build();
}
```

**Comment by gmiano** [comment]
Hi Marcin,
thank you for your feedback. I will check asap your solution.

G.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
