### ISSUE TITLE
Expose isSampled() in TraceContext

### ISSUE THREAD

**Issue by phxql** [spring-cloud/spring-cloud-sleuth#1799]
**Is your feature request related to a problem? Please describe.**
I'm trying to log a JSON field `"sampled": true` when the current trace is sampled.

**Describe the solution you'd like**
It would be great if `org.springframework.cloud.sleuth.TraceContext` could expose the `isSampled()` Method found in `BraveTraceContext`.

**Describe alternatives you've considered**
Im 3.0.0-M5 i casted the `TraceContext` to `BraveTraceContext` but this is no longer possible, as `BraveTraceContext` is now package protected.

**Comment by marcingrzejszczak** [comment]
Makes perfect sense!

**Comment by phxql** [comment]
Just a quick note: in your commit d547386cb51cabdf114d6179fa7844402018b455 you used a `boolean`, the `isSampled()` from Brave returns a `Boolean` (nullable) - this could lead to a NPE.

**Comment by marcingrzejszczak** [comment]
Oh, great catch! Let me fix this

**Comment by marcingrzejszczak** [comment]
There you go https://github.com/spring-cloud/spring-cloud-sleuth/commit/7fee2670c73cc7f5f196917573cd8b584cd4e675

**Comment by marcingrzejszczak** [comment]
I've renamed the method to `sampled` from `isSampled` to be consistent with lack of `get` / `set` / `is`

**Comment by phxql** [comment]
Perfect, many thanks!
