### ISSUE TITLE
Support Spring @Cacheable

### ISSUE THREAD

**Issue by Nankh** [spring-cloud/spring-cloud-sleuth#1800]
Hi Team, 
First, thank you for the incredible work you've done on this amazing project.

**Describe the bug**
When using Spring `@Cacheable` annotation within a redis implementation, I can't see any span reported to zipkin.
Spring Cloud : 2.2.6.RELEASE
Spring-Boot : 2.3.5.RELEASE

**Sample**
Here a sample and simple code for Cacheable usage
The main controller...
```
 @RequestMapping(value = "/user/v1/{idUser}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
public ResponseEntity<String> getUser(Integer idUser) {
        Optional<String> userInformation = myService.getUserName(idUser);
        return userInformation.isEmpty() ? ResponseEntity.noContent().build() : ResponseEntity.ok(userInformation.get());
    }
```

The service...
```
 @Cacheable(value = "myCacheNameInRedis")
    public Optional<String> getUserName(Integer idUser) {
        //call repository with idUser;
    }
```

Dependencies used :
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zipkin</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
```
Thank you

**Comment by marcingrzejszczak** [comment]
Hi! Thank you for the nice words. Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by Nankh** [comment]
Hi @marcingrzejszczak Done ! (sorry)

**Comment by marcingrzejszczak** [comment]
Thanks, can you upload this as a sample? It will be difficult to debug this without one.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Nankh** [comment]
Hi team,

just some words to tell you that, this error is due to a custom LettuceFactory and we did not add BraveTracing when creating it.

Have nice day folks
