### ISSUE TITLE
Build error for Spring 2.4.1 with spring-cloud-starter-vault-config 2.2.4.RELEASE

### ISSUE THREAD

**Issue by pxb280** [spring-cloud/spring-cloud-sleuth#1811]
I have upgraded spring boot dependencies from 2.3.5.RELEASE to 2.4.1. I have spring-cloud-starter-vault-config version  at 2.2.4.RELEASE. I tried to upgrade it to 2.2.6.RELEASE. In both the cases I am getting below error.

java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configurationPropertiesBeans' defined in class path resource [org/springframework/cloud/autoconfigure/ConfigurationPropertiesRebinderAutoConfiguration.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.context.properties.ConfigurationPropertiesBeans] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@2aae9190]
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.context.properties.ConfigurationPropertiesBeans] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@2aae9190]
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/ConfigurationBeanFactoryMetadata
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.properties.ConfigurationBeanFactoryMetadata

What would be the compatible version of spring-cloud-starter-vault-config

**Comment by marcingrzejszczak** [comment]
These are incompatible versions. You just can't upgrade to boot 2.4

**Comment by pxb280** [comment]
I have tried with spring-cloud-starter-vault-config 3.0.0-M2 version and spring-boot 2.4.1. It does remove compilation error. But during runtime it throws 

"java.lang.NoSuchMethodError: 'void org.springframework.core.codec.Hints.touchDataBuffer(org.springframework.core.io.buffer.DataBuffer, java.util.Map, org.apache.commons.logging.Log)'\n\tat
org.springframework.http.codec.EncoderHttpMessageWriter.lambda$write$1(EncoderHttpMessageWriter.java:131)\n\tat reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)\n\tat reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73)\n\tat reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784)\n\tat reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:178)\n\tat reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)\n\tat reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:102)\n\tat reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)\n\tat reactor.core.publisher.MonoSingle$SingleSubscriber.request(MonoSingle.java:101)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2154)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2028)\n\tat reactor.core.publisher.MonoSingle$SingleSubscriber.onSubscribe(MonoSingle.java:121)\n\tat reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)\n\tat reactor.core.publisher.FluxJust.subscribe(FluxJust.java:70)\n\tat reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)\n\tat reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)\n\tat reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:379)\n\tat
reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:612)\n\tat reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onStateChange(DefaultPooledConnectionProvider.java:194)\n\tat reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onStateChange(DefaultPooledConnectionProvider.java:465)\n\tat reactor.netty.channel.ChannelOperationsHandler.channelActive(ChannelOperationsHandler.java:63)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)\n\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelActive(CombinedChannelDuplexHandler.java:412)\n\tat io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelActive(CombinedChannelDuplexHandler.java:211)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)\n\tat reactor.netty.tcp.SslProvider$SslReadHandler.userEventTriggered(SslProvider.java:750)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)\n\tat io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1813)\n\tat io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1467)\n\tat io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1294)\n\tat io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1331)\n\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)\n\tat io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)\n\tat
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\tat io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)\n\tat io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)\n\tat io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n","msg":"An exception 'java.lang.NoSuchMethodError: 'void org.springframework.core.codec.Hints.touchDataBuffer(org.springframework.core.io.buffer.DataBuffer, java.util.Map, org.apache.commons.logging.Log)'' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:"}

**Comment by jonatan-ivanov** [comment]
@pxb280 Could you please use GH's pretty nice formatting features in your comments, it increases the readability of your stacktraces a lot: https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks

Could you please try the spring-cloud BOM? https://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-dependencies/ 
Right now `2020.0.0-RC1` is the latest so first, I would go with that, `Hoxton.x` is not compatible with `spring-boot 2.4.x`.

Also, are you sure that this issue should be here (`spring-cloud-sleuth`)? To me it rather seems that you have an issue with `spring-cloud-config` or `spring-cloud-vault`.

**Comment by pxb280** [comment]
issue is not related to sleuth. raised an issue in spring-cloud-vault
