### ISSUE TITLE
Application is not starting when zipkin is disabled by environment variable - spring cloud version 2020.0.0

### ISSUE THREAD

**Issue by kubav182** [spring-cloud/spring-cloud-sleuth#1813]
I have dependency org.springframework.cloud:spring-cloud-sleuth-zipkin from spring cloud version 2020.0.0
There was not this problem in previous version Hoxton.SRX.

In application properties:
spring.zipkin.enabled=false
spring.zipkin.base-url=http://zipkin:9411
spring.sleuth.sampler.probability=1.0

Sometimes I want to turn on zipkin so I have environment variable in k8s deployment
SPRING_ZIPKIN_ENABLED='false' // I switch to true if needed

When I start application with false value in env var I get this error, but when I remove this env var completely it starts fine:

APPLICATION FAILED TO START

Description:

Parameter 3 of method traceFunctionAroundWrapper in org.springframework.cloud.sleuth.autoconfig.instrument.messaging.TraceFunctionAutoConfiguration required a bean of type 'org.springframework.cloud.sleuth.propagation.Propagator$Setter' that could not be found.

The injection point has the following annotations:
- @org.springframework.beans.factory.annotation.Autowired(required=false)

Action:

Consider defining a bean of type 'org.springframework.cloud.sleuth.propagation.Propagator$Setter' in your configuration.

**Comment by jonatan-ivanov** [comment]
@kubav182 Could you please create a sample project that reproduces the issue?

**Comment by kubav182** [comment]
yes, I will try it with simple project to see if there can be problem in different dependency

**Comment by kubav182** [comment]
@jonatan-ivanov I could not make not working example, so i tried different use cases with my app and this is what I discovered:
The problem is not variable SPRING_ZIPKIN_ENABLED, but variable SPRING_SLEUTH_MESSAGING_ENABLED=false
This property is now spring.sleuth.messaging.messaging.enabled instead of spring.sleuth.messaging.enabled in previous version. When I change it to SPRING_SLEUTH_MESSAGING_MESSAGING_ENABLED it works fine.

But what is quite strange this error occurs only when I run app in kubernetes, when I run it via docker-compose or as jar it starts fine with that old variable.

I would recommend improvement - this class:
```
@ConfigurationProperties("spring.sleuth.messaging")
public class SleuthMessagingProperties
```
should not contain inner class `public static class Messaging`
and fields inside this static class should be just fields of SleuthMessagingProperties to prevent doubling .messaging

**Comment by marcingrzejszczak** [comment]
That's a bug. Do you want to file a PR to fix this?

**Comment by kubav182** [comment]
Yes I can handle it
