### ISSUE TITLE
Customizing Message Spans sample code in Spring Cloud Sleuth Reference Documentation is incorrect

### ISSUE THREAD

**Issue by wabrit** [spring-cloud/spring-cloud-sleuth#1818]
**Describe the bug**
The sample [code snippet](https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/htmlsingle/#customizing-messaging-spans) for use of `MessageSpanCustomizer` is incorrect in that the return type and first parameter of each overriden method should be `SpanCustomizer`.

_Current docs_:

```
@Component
  class MyMessageSpanCustomizer extends DefaultMessageSpanCustomizer {
      @Override
      public Span customizeHandle(Span spanCustomizer,
              Message<?> message, MessageChannel messageChannel) {
          return super.customizeHandle(spanCustomizer, message, messageChannel)
                  .name("changedHandle")
                  .tag("handleKey", "handleValue")
                  .tag("channelName", channelName(messageChannel));
      }

      @Override
      public Span.Builder customizeSend(Span.Builder builder,
              Message<?> message, MessageChannel messageChannel) {
          return super.customizeSend(builder, message, messageChannel)
                  .name("changedSend")
                  .tag("sendKey", "sendValue")
                  .tag("channelName", channelName(messageChannel));
      }
  }

```

_Suggested fix_:

```
@Component
  class MyMessageSpanCustomizer extends DefaultMessageSpanCustomizer {
      @Override
      public SpanCustomizer customizeHandle(SpanCustomizer spanCustomizer,
              Message<?> message, MessageChannel messageChannel) {
          return super.customizeHandle(spanCustomizer, message, messageChannel)
                  .name("changedHandle")
                  .tag("handleKey", "handleValue")
                  .tag("channelName", channelName(messageChannel));
      }

      @Override
      public SpanCustomizer customizeSend(SpanCustomizer spanCustomizer,
              Message<?> message, MessageChannel messageChannel) {
          return super.customizeSend(spanCustomizer, message, messageChannel)
                  .name("changedSend")
                  .tag("sendKey", "sendValue")
                  .tag("channelName", channelName(messageChannel));
      }
  }

```

**Comment by marcingrzejszczak** [comment]
Do you want to suggest a PR?

**Comment by wabrit** [comment]
I'm not familiar with the Sleuth codebase but if you can point me at the right source file / package I will do my best :-)

**Comment by marcingrzejszczak** [comment]
The code is taken from here https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptorTest.java#L427-L449 and we reference it here https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/docs/src/main/asciidoc/integrations.adoc (search for `TracingChannelInterceptorTest` inclusion). The return type is correct (it does compile ;) ) but of course we can make it better!

**Comment by wabrit** [comment]
I think I must have pulled down a JAR built from slightly different (later?) source (spring-cloud-sleuth-core-2.2.7.BUILD-20210107.095756-74.jar) because e.g. the signature of MessageSpanCustomizer.customizeSend I have is:

```
SpanCustomizer customizeSend(SpanCustomizer spanCustomizer, Message<?> message,
			@Nullable MessageChannel messageChannel);
```

whereas the source in master is

`Span.Builder customizeSend(Span.Builder builder, Message<?> message, @Nullable MessageChannel messageChannel);`

**Comment by marcingrzejszczak** [comment]
So 2.2.7 would be https://github.com/spring-cloud/spring-cloud-sleuth/blob/2.2.x/spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptorTest.java#L459-L481

**Comment by wabrit** [comment]
OK then I think I was just looking at the wrong docs for the sleuth jars I have, so feel free to close.
