### ISSUE TITLE
Library aspect for tracing

### ISSUE THREAD

**Issue by Koizumi85** [spring-cloud/spring-cloud-sleuth#182]
I am experimenting with Sleuth at the moment and am a little bit wondering about what's the best way to create Spans at points not catched by the automatic instrumentation.
For myself i created an annotation ("SleuthInstrumented") and an AOP Advice which matches this is on a method or a class. The advice then creates a new Span either with a name defined in the annoation or simply "CLASSNAME/METHODNAME" as name. Additionally you can name method parameters in the annotation which should be added as tags to span.

Do you think this is a good way to handle this?
If it is: Do you think it would be something i should contribute?
If it is not: What would you do?

PS:  Very nice work you are making here! Works really good :)

**Comment by dsyer** [comment]
Sleuth is about distributed tracing, meaning it cares primarily about process boundaries, and normally spans only need to be created when you cross those boundaries. There is a codicil about "local" spans and particularly processing that is not "on the critical path" (for latency), so, for example, async, fire-and-forget work can be done in a new span. We are only just starting to articulate this in the core team so it's not laid out anywhere formally. You can pick up the discussion in gitter.

That said, I think we're generally open to the idea of a library aspect. I'm not sure what its features should be though, since (as described above) we want to discourage creation of new spans. If you want to make a contribution I would assume that it should start with continuing the existing span, and maybe we could add optional features later to start a new one.

**Comment by dsyer** [comment]
Another point that is relevant: if we are going to insist (at least initially) on not creating a new span, what would the aspect actually do? It could only log events and add tags to the existing span, so what would the values of those events and tags be?

**Comment by Koizumi85** [comment]
Hello. Thanks for your Feedback. My intendation where i would have used this, was to track database access and similar stuff, where you possibly won't track every call (for example a "findOne" would be really boring), but some more complex queries would be interesting. And for me, some declarative approach with the annotation to create this "local span" is nicer, than to repeat the same stuff in every of these methods just for adding other tags or something like this.
I am with you, that just a continued span with some more tags or something, would really have no values, why I have choosen to create new Spans for my own implementation.

The gitter discussion is in the spring-boot room, right?

**Comment by dsyer** [comment]
https://gitter.im/spring-cloud/spring-cloud-sleuth

**Comment by marcingrzejszczak** [comment]
Hey @Koizumi85 can you point here in a comment or issue description where your code is?

**Comment by Koizumi85** [comment]
@marcingrzejszczak 
sorry for the late answer. My code is here in this branch of my repo:

https://github.com/Koizumi85/spring-cloud-sleuth-annotation/tree/advisor

**Comment by marcingrzejszczak** [comment]
Hi @Koizumi85! Pinging @dsyer and @adriancole on this as well.

I've been playing around with this and I think I fully agree with what Dave has written before. In 1.2.0 I'll try to change the way the spans are created to continue as often as possible. Needing a new span should be rare.

To some extent I think that if we create an aspect out of this then it should work more or less like the Hystrix Javanica aspect. So basically it would create a span and close it upon method exit.

 So if we assume that this aspect would create new spans then I have a couple of ideas / thoughts  on what you did:

- Don't you think that `@CreateSleuthSpan()` on a class is an overkill? I'd prefer to have it on methods only.
- I'd rename `@CreateSleuthSpan()` to `@NewSpan()`
- I don't know if it makes sense to add the `@SpanTag` thing. Tags should be created from code most often (you pass some parameter or sth). So If you create a span you can take `tracer.addTag(someKey, someValue)`. That's not a gigantic thing to do right?

**Comment by adriancole** [comment]
here are some notes..

first, I agree that method scope is important, although one can argue for type-level. In the latter case, easy to add later.

on naming, yeah hinting that this will be a new span is important, and can be done in docs. Here are some similar annotations
* [Kill Bill's TimedResource](https://github.com/killbill/killbill-commons/blob/67947b2e23d386381d179687a0f18bdd46375b7b/metrics/src/main/java/org/killbill/commons/metrics/TimedResource.java)
* [New Relic's Trace](https://docs.newrelic.com/docs/agents/java-agent/custom-instrumentation/java-instrumentation-annotation)
  * note this one calls out if a new trace is to be created or not

on tags, statically configured ones seem to cover rare circumstances as the values are usually dynamic (except possibly component name etc). Dynamic tags are probably better as a callback. This is how Brave does it, as well DataDog. For example, in DataDog, you can express in yaml some tags to apply to everything (which is reporter-scope), then you can add a callback or so to supply more [DynamicTagsCallback)(https://github.com/coursera/metrics-datadog/blob/master/metrics-datadog/src/main/java/org/coursera/metrics/datadog/DynamicTagsCallback.java). Personally, I've been working on something a bit more involved, as the concern tends to be how to parse dynamic tags from an object (ex. the HttpRequest).

**Comment by Koizumi85** [comment]
Hello @marcingrzejszczak 

thanks for your feedback. On the "create new spans or continue old"-discussion, I am not sure because I don't have enought knowledge of how everything works in sleuth and zipkin. I thought something like "I want to track something like a database request. This goes out from my application, so a new span is right". If it is not right we can continue as well.

To your ideas/thoughts:
- I made `@CreateSleuthSpan()` on type level possible mainly for things like SpringData-Repositories or something like this, where you don't want to override every method of the parent interface, just to add the annotation to it.
- I am really not good in naming things, so we can name this like whatever you want :D 
- Also this is not so easy If you have code which is executed from another framework - like spring data. If I start the span on method entry and close it when I am leaving the method, I don't have a chance to add those tags programmatically.

I hope I was able to make my thoughts clear. My english is not the best, so it is not easy for me :)

**Comment by gavlyukovskiy** [comment]
Hi, I would like to have single annotation with a type of tracing - create new span or just add events to existing one (see https://github.com/spring-cloud/spring-cloud-sleuth/issues/471). 
Here is my suggestion:
```
public @interface Traceable {
    String name();
    TraceType type() default TraceType.LOG_EVENT;

    enum TraceType {
        CREATE_SPAN,
        LOG_EVENT
    }
}
```
```
@Aspect
public class TraceableAspect {

    private final Tracer tracer;
    private final String prefix;

    public TraceableAspect(Tracer tracer, String prefix) {
        this.tracer = tracer;
        this.prefix = prefix;
    }

    @Around("execution(* *(..)) && @annotation(traceable)")
    public Object withTracing(ProceedingJoinPoint joinPoint, Traceable traceable) throws Throwable {
        String signature = joinPoint.getTarget().getClass().getSimpleName() + "." + joinPoint.getSignature().getName();
        String spanName = traceable.name();
        Span span;
        if (traceable.type() == TraceType.CREATE_SPAN) {
            span = tracer.createSpan(spanName);
            span.logEvent(Span.CLIENT_SEND);
        }
        else {
            span = tracer.getCurrentSpan();
            span.logEvent(prefix + signature + ".start");
        }
        try {
            return joinPoint.proceed();
        }
        catch (Exception e) {
            span.tag(prefix + signature + ".error", e.getMessage());
            throw e;
        }
        finally {
            if (traceable.type() == TraceType.CREATE_SPAN) {
                span.logEvent(Span.CLIENT_RECV);
                tracer.close(span);
            }
            else {
                span.logEvent(prefix + signature + ".end");
            }
        }
    }
}
```

**Comment by marcingrzejszczak** [comment]
@gavlyukovskiy thanks for the proposal. I think that it's too simple, there are more complex cases (like the ones that @Koizumi85 has mentioned). I'll have to give it a thought and give it another go (but first I have to focus on fixing bugs ;) )

**Comment by Koizumi85** [comment]
@marcingrzejszczak Hey. Cool, that my work was a good starting point for your PR. Just looked at it and it looks really good. Sorry, that I didn't have the time to make the PR myself.

**Comment by marcingrzejszczak** [comment]
Actually I took all of your code, polished it and added some javadocs and docs. So I did nothing in comparison to your work. Great work @Koizumi85 :)

**Comment by Koizumi85** [comment]
Hm. Seems I did not see my own code for a looong time. Did not recognize all of it :joy: 
Thanks :)
