### ISSUE TITLE
Too much LazyTracing wrapping that produces a StackOverflowError when extending the LoadBalancerFeignClient

### ISSUE THREAD

**Issue by albertominetti** [spring-cloud/spring-cloud-sleuth#1824]
**Describe the bug**
A `StackOverflowError` is thrown after a massive usage of wrap/decorator of `LazyTracingFeignClient` delegate in the custom `LoadBalancerFeignClient`. This happens because the wrap method of `TraceFeignObjectWrapper` **modifies** the **custom** bean `LoadBalancerFeignClient`, changing its delegate with a wrap (`LazyTracingFeignClient`) of the previous delegate. Since the bean is a **singleton** and its runtime class is not `LoadBalancerFeignClient` (we extended it), the wrap method keep to wrap/decorate with a new `LazyTracingFeignClient` for each new _TracingContext_. It actually runs every new _TracingContext_ because of the aspect `TracingFeignAspect`.

![image](https://user-images.githubusercontent.com/15971462/104730360-32fb9400-573a-11eb-8ad0-5e24f211ebcf.png)

Spring sleuth 2.2.6.RELEASE
Spring cloud Hoxton.SR9

**Sample screenshot**
In the screenshot the `XenonLoadBalancerFeignClient` is instance of `LoadBalancerFeignClient`, but of course the `AopUtils.getTargetClass` is not equal to `LoadBalancerFeignClient`. This behavior produces a _stack leak_ (do not know how to define it) that ends with a `StackOverflowError` during the execution.

![image](https://user-images.githubusercontent.com/15971462/104730406-49095480-573a-11eb-97ca-0a23d9176eca.png)

**Comment by jonatan-ivanov** [comment]
Could you please provide a minimal sample app that reproduces the issue?

**Comment by albertominetti** [comment]
Here a minimal project with a few tests to reproduce the issue:
https://github.com/albertominetti/sleuth-stackoverflow/blob/master/src/test/java/com/example/demo/DemoApplicationTests.java

**Comment by jonatan-ivanov** [comment]
Thank you very much investigating and finding the issue.
The fix seems to be pretty simple but I need to write some tests and propagate this fix to 2.1.x, 2.2.x and 3.x. I'm going to open PRs and include you.

**Comment by jonatan-ivanov** [comment]
@albertominetti You can find the release artifacts in the snapshot repo, e.g.: [spring-cloud-sleuth-core-2.2.7.BUILD-20210130.045509-97.jar](https://repo.spring.io/libs-snapshot-local/org/springframework/cloud/spring-cloud-sleuth-core/2.2.7.BUILD-SNAPSHOT/spring-cloud-sleuth-core-2.2.7.BUILD-20210130.045509-97.jar)
