### ISSUE TITLE
sleuth with flowable not working

### ISSUE THREAD

**Issue by DekateSainath** [spring-cloud/spring-cloud-sleuth#1833]
I have tried to integrate the sleuth with flowable but its not working.
As observer the trace details are not available in api request called using flowable.

**Comment by jonatan-ivanov** [comment]
@DekateSainath Could you please provide a minimal sample project that reproduces the issue?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
