### ISSUE TITLE
First span for received http request now gets new span id (since sleuth 3.0.0) - Is this by purpose?

### ISSUE THREAD

**Issue by larsduelfer** [spring-cloud/spring-cloud-sleuth#1841]
While updating a few spring boot services to 2.4.2 including Sleuth 3.0.0 we saw that the first span for a received http request (that is in our case reported to zipkin / jaeger) gets a new span id and the parent id is set to the received value of x-b3-spanid http header.

With the previous major version of sleuth (2.x.x) the first span created for a received http request contained the value of the x-b3-spanid http header as the span id, so basically, the span was continued. 

Was this an intended change? And if so, why was this done? I tried to understand the B3 specification to see, what the desired behaviour should be but without much success. From what I read in the sleuth documentation here https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/htmlsingle/#getting-started-terminology I would have expected that the first span for the received http request gets the span id contained in the incoming http request.

I got aware of that because we have one node.js service participating in the trace and the traces now were broken because of that changed behaviour. The node application created the first span with a span id set to the value of the x-b3-spanid of the received http request (the same as sleuth did with version 2.x.x.). 

UPDATE: The more I investigate this, the more I think this is a bug. Previously, a sending (requesting) spring boot application was sending a span of type "client", and the span id of this span was also sent in the http headers. The receiving spring boot application (and also our node js application) was creating a span of type "server" with the same span id (the one from the incoming http request). This for me seems to be the desired behaviour. 

Can you please comment on this? Much appreciated! Thanks a lot!

**Comment by marcingrzejszczak** [comment]
`x-b3-spanid` is no longer supported. Can you elaborate exactly on what happens in which service?

**Comment by larsduelfer** [comment]
I found this explanation (https://github.com/openzipkin/b3-propagation)

Some propagation formats look similar to B3, but don't propagate a field named parent. Instead, they propagate a span ID field which serves the same purpose as ParentSpanId. **Unlike B3, these systems use a different span ID for the client and server side of an RPC.** When a server reads headers like this, it is expected to provision a new span ID for itself, and use the one it extracted as its parent.

Here's an example of an alternate library composing a trace context with incoming http request headers and an ID generator:

< picture not copied >

In both B3 and the above example, incoming headers contain the parent's span ID, and three IDs (trace, parent, span) end up in the trace context. **The difference is that B3 uses the same span ID for the client and server side of an RPC, where the latter does not.**

—-

I have a feeling that sleuth since version 3.0.0 now behaves as mentioned above in the second example and not like the B3 specification anymore. That is at least what we see.

**Comment by marcingrzejszczak** [comment]
Sure, but can you write exactly what kind of apps do you have, what they are doing, what is put in the headers, what do you see that happens and what do you think that should happen. Creating samples that replicate this issue would be best of course.

**Comment by larsduelfer** [comment]
HI @marcingrzejszczak would you be available for a remote call today in order to discuss this? That would be faster than just writing back and forth. I am happy to provide some examples, would even prefer to do this in a remote call.

**Comment by marcingrzejszczak** [comment]
It can be tricky ATM cause I'm a little bit overwhelmed with work. How about you try to create the samples that replicate this? It will be much easier to reason about the issue.

**Comment by larsduelfer** [comment]
Hi @marcingrzejszczak  I have found a way now to get our solution working even with the changed behaviour on the most recent sleuth version. So I would not like to spent more time with it. I tested another tracer / instrumentation (the one from the jaeger ecosystem) and saw this one does exactly the same as sleuth 3.0.0 so that client and server side of an RPC call (in this case the HTTP request) have different span ID's. Therefore, from my perspective we can close this isssue here.

If you have a chance, I would much appreciate if you could rather have a look into #1840 since this seems to really be a bug that now produces garbage in the trace collector (zipkin or jaeger). Thanks a lot!
