### ISSUE TITLE
Using Feign builder requests doesn't send trace-id, span-id to child clients but using rest template is showing all headers on child clients

### ISSUE THREAD

**Issue by oguzhanonder91** [spring-cloud/spring-cloud-sleuth#1848]
****
Actually I'm not sure it's related to spring-cloud-sleuth. If I'm looking in the wrong place I would be glad if you could help me.
I'm making a sequential request using Feign Builder. There are no x-b3-traceid,x-b3-spanid .. in the title of the request. That's why the log my last client appears on the zipkin.

I use spring boot 2.4.2 , spring cloud 2020.0.0 , feign-core 10.10.1 , feign-okhttp 10.10.1. I have tried spring-cloud-openfeign and i achieved wanted result. But i don't want to use this lib. There are requests when using Feign Builder and Rest Template in here. I dont' see same log at zipkin.

****
[All code is here. ]https://stackoverflow.com/questions/66167917/using-feign-builder-requests-doesnt-send-trace-id-span-id-to-child-clients-but

**Comment by marcingrzejszczak** [comment]
Please do not cross post. Let's leave the stackoverflow question open and close this issue.
