### ISSUE TITLE
Customized WebClient implementation stops working after adding Sleuth dependency 

### ISSUE THREAD

**Issue by djarza** [spring-cloud/spring-cloud-sleuth#1853]
**Describe the bug**

In the project I use both WebClient and a custom class that implements WebClient. There are beans for each implementation.
Everything works fine, but after adding the Sleuth dependency, I get the following error:

> 2021-02-21 13:18:44.081 ERROR [,,] 27429 --- [           main] o.s.boot.SpringApplication               : Application run failed
>
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'someService': Unsatisfied dependency expressed through field 'customWebClient'; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'customWebClient' is expected to be of type 'com.example.demo.CustomWebClient' but was actually of type 'org.springframework.web.reactive.function.client.DefaultWebClient'

Spring Boot 2.4.2
Spring Cloud 2020.0.1

**Sample**

[Sample code available here](https://github.com/djarza/spring-sleuth-custom-web-client-reproducer)
Run the application and you will get the error as above.
After removing spring-cloud-starter-sleuth dependency from POM, application starts correctly.

**Comment by marcingrzejszczak** [comment]
Why do you need to use the `CustomWebClient` version? Why is it important to inject a concrete class really?

**Comment by djarza** [comment]
I need to extend `WebClient` with an additional method, which in certain situations causes additional logging on the server. At the same time, I want `CustomWebClient` to be used only by microservices that really need that logging. All others should use `WebClient`. I also want to be able to switch easily between both implementations hence the inheritance.

**Comment by marcingrzejszczak** [comment]
We don't support such an option out of the box. If you want to achieve what you want you need to do the following.

- Disable the default `WebClient` wrapping via `spring.sleuth.web.webclient.enabled=false`
- Create your own implementation of the `WebClient` that will call a delegate
- Wrap the delegate manually via the `TraceWebClientBeanPostProcessor`

Example:

.My custom WebClient
```java
public static class MyWebClient implements WebClient {
		private final WebClient webClient;

		boolean wasCalled = false;

		public MyWebClient(WebClient webClient) {
			this.webClient = webClient;
		}

		@Override
		public RequestHeadersUriSpec<?> get() {
			return webClient.get();
		}

		@Override
		public RequestHeadersUriSpec<?> head() {
			return webClient.head();
		}

		@Override
		public RequestBodyUriSpec post() {
			return webClient.post();
		}

		@Override
		public RequestBodyUriSpec put() {
			return webClient.put();
		}

		@Override
		public RequestBodyUriSpec patch() {
			return webClient.patch();
		}

		@Override
		public RequestHeadersUriSpec<?> delete() {
			return webClient.delete();
		}

		@Override
		public RequestHeadersUriSpec<?> options() {
			return webClient.options();
		}

		@Override
		public RequestBodyUriSpec method(HttpMethod httpMethod) {
			return webClient.method(httpMethod);
		}

		@Override
		public Builder mutate() {
			return webClient.mutate();
		}

		public void call() {
			this.wasCalled = true;
		}
	}
```

and my custom bean registration

```java

@Bean
WebClient myWebClient(ConfigurableApplicationContext springContext, WebClient.Builder builder) {
  return new MyWebClient((WebClient) new TraceWebClientBeanPostProcessor(springContext).postProcessAfterInitialization(builder.build()));
}
```

Now you can inject your own `MyWebClient` web client that is traced. Remember about setting  `spring.sleuth.web.webclient.enabled=false`. If you don't need this to be traced just set  `spring.sleuth.web.webclient.enabled=false` and don't create any of the tracing beans.

**Comment by djarza** [comment]
Thank you for your answer. This is technically ok. But in this case, adding sleuth causes dependency injection to work inconsistently. Shouldn't there be an assumption that Sleuth is transparent to the application?

**Comment by marcingrzejszczak** [comment]
It should but you're the first person that is actually using a custom implementation of WebClient and requires that type to be autowired. If there are more people interested then we can come back to the topic.
