### ISSUE TITLE
WebFluxSleuthOperators should use ContextView instead of Context as parameter

### ISSUE THREAD

**Issue by blake-bauman** [spring-cloud/spring-cloud-sleuth#1860]
Some of the method variants of `WebFluxSleuthOperators.withSpanInScope()` take `reactor.util.context.Context` as an arg.  Now that `Mono.subscriberContext()` is deprecated and is targeted for removal, apps are being pushed to use `Mono.deferContextual()` instead, which provides a `reactor.util.context.ContextView` instead of a `Context`.

Since `Context` extends `ContextView`, it should hopefully be a small change to `WebFluxSleuthOperators` in order to support this.

**Comment by marcingrzejszczak** [comment]
Hey @blake-bauman ! Are you willing to give it a try and file a PR?

**Comment by blake-bauman** [comment]
I'm looking into setting up my IDE for this, but yes, I can give it a shot.  Looks like a small enough fix.  Would I open the PR against `master`?

**Comment by marcingrzejszczak** [comment]
Correct!
