### ISSUE TITLE
Not creating new traceid inside a spring scheduler 

### ISSUE THREAD

**Issue by alagesann** [spring-cloud/spring-cloud-sleuth#1862]
I am scheduling the spring scheduler with SchedulingConfigurer as follows. However, new traceid is not getting created every time the "ProcessJob" method is getting called. 

Even following method always logs with the same traceid.

              log.info("Performing task");

What is the issue here? and how do i ensure new traceid everytime this job is triggered. 

I have even tried wrapping "processJob" method call inside newSpan as follows: but no luck.

**Fix i tried:**

  private void setSchedule() {
    future =
        taskScheduler.schedule(
            () -> {

                Span newSpan = tracer.nextSpan().name("newSpan").start();
               try (SpanInScope ws = tracer.withSpanInScope(newSpan.start())) {
                            log.info("Performing task");
                            taskManager.processJob(); 
                  } finally {
                      newSpan.finish();
                  }
            },
            dynamicTrigger);
  }

Original class that needs fix:

```
public class SchedulerConfig
    implements SchedulingConfigurer, ApplicationListener<RefreshScopeRefreshedEvent> {

  private final DynamicTrigger dynamicTrigger;

  private final TaskManager taskManager;

  private TaskScheduler taskScheduler;
  private ScheduledFuture<?> future;

  @Bean(destroyMethod = "shutdown")
  public ExecutorService taskExecutor() {
    return Executors.newScheduledThreadPool(1);
  }

  @Override
  public void configureTasks(ScheduledTaskRegistrar taskRegistrar) {
    taskRegistrar.setScheduler(taskExecutor());
    taskScheduler = taskRegistrar.getScheduler();
    setSchedule();
  }

  private void setSchedule() {
    future =
        taskScheduler.schedule(
            () -> {z
              log.info("Performing task");
              taskManager.processJob(); 
            },
            dynamicTrigger);
  }

  @Override
  public void onApplicationEvent(RefreshScopeRefreshedEvent event) {

    log.info("Rescheduling due to change in cron expression");
    future.cancel(false);
    setSchedule();
  }
```

**Comment by jonatan-ivanov** [comment]
Please do't cross-post. I answered your question on SO, I'm closing this issue in favor of it: https://stackoverflow.com/questions/66383403/spring-sleuth-not-creating-new-traceid-inside-a-spring-scheduler
