### ISSUE TITLE
Wrong MongoDB instrumentation configuration leads to memory leaks

### ISSUE THREAD

**Issue by ppressives** [spring-cloud/spring-cloud-sleuth#1864]
Now, brave mongo instrumentation uses thread-local variables to keep stacks of spans, so [it can't be used](https://github.com/openzipkin/brave/blob/0a5666d4a918b2a359cefff84e276bc9bbffa5a4/instrumentation/mongodb/src/main/java/brave/mongodb/MongoDBTracing.java#L26) in an asynchronous environment.

Brave mongo client instrumentation [is enabled](https://github.com/spring-cloud/spring-cloud-sleuth/blob/899410a2b03f6d275f17a5330483e3f599b48072/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/brave/instrument/mongodb/BraveMongoDbAutoConfiguration.java#L48) when `mongodb-driver-core` is on the classpath, which is also used as a part of the asynchronous mongodb driver `mongodb-driver-reactivestreams`.

**Comment by jonatan-ivanov** [comment]
@ppressives Based on the readme of [brave-instrumentation-mongodb](https://github.com/openzipkin/brave/tree/master/instrumentation/mongodb), it seems that 
>Support for asynchronous clients is **unimplemented**. To request support for this, add your thumbs up to https://github.com/openzipkin/brave/issues/1113

What is the goal of this issue?
- Adding support for async mongo client?
  You need to request it from Brave, see the connected issue above
- Not being able to turn the Sleuth auto-config off:
  Just set `spring.sleuth.mongodb.enabled=false`
- Do you think the Sleuth autoconfig could be smarter and it should not be enabled is only the async client is present?
  Do you have any idea in mind for this?

**Comment by ppressives** [comment]
@jonatan-ivanov I think that instrumentation for reactive mongo client should be disabled by default in the future `Sleuth` releases until there's a version that does support the reactive client.
To achieve that, we could check that [MongoClient](http://mongodb.github.io/mongo-java-driver-reactivestreams/1.9/javadoc/com/mongodb/reactivestreams/client/MongoClient.html) is not on the classpath.

If it doesn't seem possible, we could at least log a warning at application startup.

**Comment by jonatan-ivanov** [comment]
@ppressives Seems straightforward, `@ConditionalOnMissingClass` (or `@ConditionalOnMissingBean`) can do the trick.
Do you want to put a PR together?

**Comment by beatfreaker** [comment]
@jonatan-ivanov created pull request to add `@ConditionalOnMissingClass("com.mongodb.reactivestreams.client.MongoClient"
)`

wanted to know how to write a test case for this change ?
as to assert that bean of `TraceMongoClientSettingsBuilderCustomizer` class should not be created we need `mongodb-driver-reactivestreams` is in classpath, which we don't have.

**Comment by jonatan-ivanov** [comment]
@beatfreaker Let's discuss this on the PR (see my comment there).

**Comment by marcingrzejszczak** [comment]
With Mongodb version 4.2 the internals are rewritten to use Reactor. Since we're already instrumenting project reactor things just work out of the box. We could leverage the builder customizer again regardless of whether it's reactive or not. WDYT @jonatan-ivanov , @beatfreaker , @ppressives ?
