### ISSUE TITLE
Spring Webflux 2.4.2 + Ilford - Intermittent traces not found

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-sleuth#1867]
Hello Spring Cloud Sleuth Team,

I would like to report an issue where some of my traces get lost.
Currently, I am using a SpringBoot Webflux 2.4.2 app, with Ilford 2020.0.0.

I am also using the Zipkin and Sleuth dependecy as follow.
```
 <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-zipkin</artifactId>
        </dependency>
```

Moreover, I have those in my properties.
```
  "spring.sleuth.sampler.probability": "1.0",
  "spring.zipkin.base-url": "http://my-zipkin.com:9411",
  "spring.zipkin.enabled": true,
  "spring.zipkin.sender.type": "web",
```
As a result, I do see some traces in my Zipkin server, the trace are there, searchable, very happy.
However, I am not able to find all the traces, on many occasions, I input a trace ID, and it is not there.

Actually, there are more traces I cannot find, than traces I can find.
Yet, it seems there is no pattern or correlations, it is not like I can only see the traces that happen every N minutes, etc.

And especially with ```"spring.sleuth.sampler.probability": "1.0"```, I was expected I would send 100% of the traces to Zipkin.

May I ask if this is an issue please?
Thank you

**Comment by marcingrzejszczak** [comment]
Can you create a sample that replicates the problem?

**Comment by patpatpat123** [comment]
Or course, will do.

But there is nothing special in my sample, just one webflux web server, in the handler, it creates a web client that will trigger another call.

I even added 

```
spring.sleuth.sampler.rate=100
spring.sleuth.sampler.probability=1.0
```

Still reproducible.

Are they some kind of hidden rule, that will make sleuth-zipkin not to send the trace?
Or is it possible to see in the log if a trace was failed to be sent?

Thank you

**Comment by jonatan-ivanov** [comment]
There are no hidden rules as far as I know, that's why we need a sample project to repro the issue.
The zipkin `Reporter` reports the spans, you can check the `zipkin2.reporter` package and you can a lower log level to get more details. There is also `LogSpanHandler` that logs out your spans and the `Reporter` also records metrics.

**Comment by patpatpat123** [comment]
Apologies with the follow up questions.
But I am really trying to understand the root cause of this issue.
We monitored for a week already, and cannot find any pattern why some traces are in, some traces are not.
It's not like every 5, 12, N requests, I see the traces, and not for the others.
It's not like every 6, or 9  or N minutes, I see traces, and not for the others.
It's not like for traces that are a certain size, certain elapsed time, I see those, and not the others.

I even enabled debug log for ```org.springframework.cloud.sleuth.autoconfig.zipkin2 and org.springframework.cloud.sleuth.zipkin2``` and even seeing 


I am just building crazy theories in my head now. 😛

- May I ask if it can be related to the id being the same?
For instance, for some of the trace that are like ```[myservice,f016e22385460ca7,f016e22385460ca7]``` I can see the traces.
But when the two IDs are not equal, mostly I do not see the traces. Can this be related? When or why sometimes they are same, sometimes different?
```[myservice,1bf6ce8439eb15b8,833adedffddf6495]```

Finally, is it possible there is a secret invisible "false"? I am only seeing three elements 
```[myservice,1bf6ce8439eb15b8,833adedffddf6495]```
But maybe it would be ```[myservice,1bf6ce8439eb15b8,833adedffddf6495,false]```, or do I enable the last bit please?

**Comment by marcingrzejszczak** [comment]
You can change the logging format and search for `sampled` entry. It should come from `MDCScopeDecorator` class from Brave.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by patpatpat123** [comment]
Hello @marcingrzejszczak,

I tried putting MDCScopeDecorator log to DEBUG, not seeing anything helpful.
Maybe I am looking at the wrong place.

Would it be possible to have a debug line, from the web app, that simply says
"trace successfully sent to Zipkin server"
"trace not sent to Zipkin server"

Or something similar? That would help in the troubleshooting of such issues.
Thank you

**Comment by jonatan-ivanov** [comment]
I guess what Marcin was referring to is changing the `logging.pattern.level` property. See the [docs](https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/htmlsingle/#features-log-integration) or [this SO answer](https://stackoverflow.com/a/65851232/971735).

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
