### ISSUE TITLE
honor managment custom context path in sleuth ressource trace filter

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-sleuth#187]
Although its configurable its bad support in sense of convention over configuration that changes in spring cloud managment path won't be reflected automaticatlly in the ressource skip filter for sleuth. 

`sleuth.instrument.web.skipPattern: /api-docs.*|/autoconfig|/management|/management/configprops|/configprops|/dump|/management/info|/info|/metrics.*|/mappings|/trace|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream`

**Comment by marcingrzejszczak** [comment]
I'm sorry can you elaborate more on this topic because I don't understand the issue

**Comment by spencergibb** [comment]
I'm thinking that he means if you set `management.context-path` to include that automatically in `skipPattern`.

**Comment by marcingrzejszczak** [comment]
ah ok - that would make sense actually cause why would you like to trace those endpoints?

**Comment by cforce** [comment]
@spencergibb   tx, that was my point

**Comment by marcingrzejszczak** [comment]
@cforce could you please build Sleuth from that branch and check if it's working as you would expect? https://github.com/spring-cloud/spring-cloud-sleuth/pull/204

**Comment by cforce** [comment]
Tx a lot for your contribution!
