### ISSUE TITLE
Question: Are skip-pattern properties only for sampling?

### ISSUE THREAD

**Issue by Saljack** [spring-cloud/spring-cloud-sleuth#1877]
I read whole documentation and try to find it in code but I just need to cofirm from someone my question. What does it mean `should be skipped in tracing.` in properties documentation for `skip-pattern` properties {for example: `spring.sleuth.web.additional-skip-pattern`)? Does it mean that these urls names are skipped only for sampling or does it mean that there are no a trace id and spans? I think that it connected only with sampling. I think that it should be better described in Sleuth documentation. 

For clarification what I want to achieve: I have some paths which I do not want to be sampled anymore but I still want to send trace ids for these paths because I can easy find these requests in logs but I do not need them in Zipkin.

**Comment by marcingrzejszczak** [comment]
> Does it mean that these urls names are skipped only for sampling or does it mean that there are no a trace id and spans? 

If will be skipped in terms of sampling. 

> I think that it should be better described in Sleuth documentation.

Please feel free to file a pull request with a suggestion on how to make the documentation better.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
