### ISSUE TITLE
Question: About ThreadLocal memory leak

### ISSUE THREAD

**Issue by cincat** [spring-cloud/spring-cloud-sleuth#1878]
In this issue:
https://github.com/spring-cloud/spring-cloud-sleuth/issues/27?spm=ata.13261165.0.0.30bf4985CXnIg1 @rwinch  report a bug which may cause memory leak, but the reference to this is a weak reference which kept in thread, so call ThreadLocal.set(null) or ThreadLocal.remove() has no matter. What may cause memory leak is that the thread local is a customed  class (e.g NamedThreadLocal) and an outlasts thread instance has its reference, so cause WebAppClassLoader leak.

**Comment by marcingrzejszczak** [comment]
Sleuth is not storing any tracing information directly. We do it either via Brave or OpenTelemetry libraries. If you see memory leaks please file issues in the corresponding libraries.

**Comment by cincat** [comment]
https://github.com/spring-cloud/spring-cloud-sleuth/issues/27 is pasted in Sleuth.
Memory leaks may not caused by the bug mentioned on the paste, so I wanna to know why the code has changed.
