### ISSUE TITLE
Wrong span duration

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#188]
Depending on the order of sent spans to zipkin we have different span lenghts.

Wrong length of `/foo` span:
![wrong_foo_length](https://cloud.githubusercontent.com/assets/3297437/13353132/797503bc-dc92-11e5-9b23-8620a7d240eb.png)

Good length of `foo` span:
![better_foo](https://cloud.githubusercontent.com/assets/3297437/13353133/79816814-dc92-11e5-920b-ebe1f32198e2.png)

Jsons from apps and query server:
[too_short_foo_span.txt](https://github.com/spring-cloud/spring-cloud-sleuth/files/148227/too_short_foo_span.txt)

**Comment by adriancole** [comment]
nit: if you name the file ending in json, some tools might have a better chance formatting it.

**Comment by adriancole** [comment]
great work, capturing the failure case!

Both the client and the server are assuming they know what the timestamp and duration of the same span is. Who should win? The client, right, as that defines the critical path. There's some devil in the details, mostly around a race condition between these sides of the same span. I'll open an upstream issue on this.

**Comment by adriancole** [comment]
actually, there's no race condition upstream. I think the smoking gun was a different value for "cs".timestamp and span.timestamp
