### ISSUE TITLE
Unresolved: Incorrect 200 status code on WebFlux spans

### ISSUE THREAD

**Issue by flavium31** [spring-cloud/spring-cloud-sleuth#1888]
This issue is related to: https://github.com/spring-cloud/spring-cloud-sleuth/issues/1851

**Describe the bug**
In some cases the status code set on the webflux server traces is incorrect. For instance, when trying to call an endpoint that throws an exception (e.g. `RuntimeException`), the caller gets back a 500, however the corresponding trace has status code 200.
There was an issue previously raised for this (see link above), but the fix implemented only seems to work for `ResponseStatusException`.

**Sample**
A small sample that reproduces it: https://github.com/flavium31/sleuth-otel-status-code-issue/tree/status-code-runtime-exception

When the endpoint is called, the caller receives a 500 status code, however the printed span has a status code of 200:
```
'GET' : 6157be29641f578e81413063aac84df9 f333dbc20ddf3188 SERVER [tracer: org.springframework.cloud.sleuth:0.17.0] AttributesMap{data={net.peer.ip=localhost, net.peer.port=8080, http.method=GET, http.user_agent=PostmanRuntime/7.26.10, http.url=http://localhost:8080/test, http.path=/test, http.flavor=http, http.client_ip=localhost, mvc.controller.method=test, mvc.controller.class=Controller, http.status_code=200}, capacity=128, totalAddedValues=11}
```

**Comment by marcingrzejszczak** [comment]
fixed via https://github.com/spring-cloud/spring-cloud-sleuth/pull/1889
