### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-cloud/spring-cloud-sleuth#1895]
This issue is about renaming the default branch (`master`) to `main` in the Sleuth-related repos:
- https://github.com/spring-cloud/spring-cloud-sleuth
- https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel
- https://github.com/spring-cloud-samples/sleuth-issues
- https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples
- https://github.com/spring-cloud-samples/sleuth-documentation-apps
- https://github.com/spring-cloud-samples/sleuth-webmvc-example
- Brewery?

GitHub supports this, see their [guide](https://github.com/github/renaming).

Things need to be done after the rename:
- [ ] Build config fix
- [ ] Documentation update
- [ ] Updating the guides (wiki, `.md` files, etc.)
- [ ] Communicating it (Gitter)

**Comment by spencergibb** [comment]
We're going to wait until after our April release

**Comment by marcingrzejszczak** [comment]
Done
