### ISSUE TITLE
InaccessibleObjectException when calling getScheduledThreadPoolExecutor

### ISSUE THREAD

**Issue by rogelio-o** [spring-cloud/spring-cloud-sleuth#1897]
**Describe the bug**
When calling the method `LazyTraceThreadPoolTaskScheduler.getScheduledThreadPoolExecutor()`, a new 
`LazyTraceScheduledThreadPoolExecutor` is created. The constructor of the pool executor is using `ReflectionUtils` to make accessible the method `decorateTask`.

Making this method accessible produces:
- A warning in Java 11: 
```
WARNING: An illegal reflective access operation has occurred
```
- An exception in Java 16: 
```
java.lang.reflect.InaccessibleObjectException: Unable to make protected java.util.concurrent.RunnableScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.decorateTask(java.lang.Runnable,java.util.concurrent.RunnableScheduledFuture) accessible: module java.base does not "opens java.util.concurrent" to unnamed module @d723c8a
```

Because `LazyTraceThreadPoolTaskScheduler` is wrapping all the created `ThreadPoolTaskScheduler`, method `getScheduledThreadPoolExecutor()` cannot be used in any `ThreadPoolTaskScheduler` bean when Sleuth is enabled.

**Comment by marcingrzejszczak** [comment]
Yes, we know about this. Thanks for filing the issue though! Really appreciate it.

**Comment by marcingrzejszczak** [comment]
Should be fixed via https://github.com/spring-cloud/spring-cloud-sleuth/commit/39617c6cf61e76947a4cdeb164b7d71c355e0beb
