### ISSUE TITLE
Sleuth not tracing WebAsyncTask's onCompletion callback

### ISSUE THREAD

**Issue by nkvaratskhelia** [spring-cloud/spring-cloud-sleuth#1898]
Spring boot 2.4.4
Spring cloud 2020.0.2
Using spring-boot-starter-web & spring-cloud-starter-sleuth

I have a spring mvc controller method that returns WebAsyncTask. This seems to be supported by Sleuth https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/integrations.html#sleuth-http-server-async-integration and indeed everything works fine. However, if I add an onCompletion callback to WebAsyncTask, Sleuth doesn't seem to trace logs in that callback:

![image](https://user-images.githubusercontent.com/16168235/114181231-ea730180-9949-11eb-9291-26bfe192a238.png)

Here's a minimal reproducer:  https://github.com/nkvaratskhelia/sleuth-demo

**Comment by marcingrzejszczak** [comment]
Please wrap the callable lambda in the `TraceCallable` and it will work just fine.

**Comment by nkvaratskhelia** [comment]
Thanks for the tip.
