### ISSUE TITLE
Why spanID missed some part

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [spring-cloud/spring-cloud-sleuth#1899]
**Using dependency**
```
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-sleuth</artifactId>
                <version>2.2.7.RELEASE</version>
            </dependency>
```

**Describe the bug**
I have some applications:

Gateway(A)
Security(B)
Web-system(C)
Message-center(D)

I have a request chain like this :
user-->Gateway-->(Async)Message-Center-->Web-system-->Gateway's controller-->Security-->(Async)Message-center

The first incomming call from user will be route by gateway to Web-system and there is an async thread to call Message-center.
Then Web-system will find uri from eureka then call the controller in Gateway though http request.
This controller was surrounded by an AOP to print log, and also it will invoke an async thread to call Message-center.
I cannot change the logistics of calling gateway's controller because it may leads to too many modifying works.
Then Gateway's controller will call a controller in Security through feign client.
All the async calls was based on feign client.
After that the request is done.

And here is the traceId I checked out from log in the order of time:
```
(correct)
[app:web-gateway,traceId:b498e0e156bdb6ef,spanId:b498e0e156bdb6ef,parentId:]

(parent span id missed)
[app:web-message-center,traceId:b498e0e156bdb6ef,spanId:ae3fabca7042ed29,parentId:18fae7bbd06421b2]

(correct)
[app:web-system,traceId:b498e0e156bdb6ef,spanId:3c5910aa70459fac,parentId:b498e0e156bdb6ef]

(correct)
[app:web-gateway,traceId:b498e0e156bdb6ef,spanId:e545bc0d7fce74fd,parentId:3c5910aa70459fac]

(parent span id missed)
[app:web-security,traceId:b498e0e156bdb6ef,spanId:312310dcac67a640,parentId:925e2465955b25a2]

(parent span id missed)
[app:web-message-center,traceId:b498e0e156bdb6ef,spanId:bc7e0751f3b4daf2,parentId:d5b47b04b0a4f47c]
```

I don't know why the log in Message-center will have an unexisting parent span id, and also security log have an unexisting parent span id too!
Before and after calling Security, the log is all ok, but security will not get a correct parent span id (it should be e545bc0d7fce74fd).
And also, parent span id in Message-center should be b498e0e156bdb6ef and e545bc0d7fce74fd but it failed!

the async threads were executed in customized thread pool like this:
```
@Configuration
public class MyExecutors {
    @Bean
    public Executor customExecutor() {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(5);
        executor.setMaxPoolSize(20);
        executor.setQueueCapacity(50);
        executor.setKeepAliveSeconds(60);
        executor.setThreadNamePrefix("CustomExecutor-");

        // rejection-policy：当pool已经达到max size的时候，如何处理新任务
        // CALLER_RUNS：不在新线程中执行任务，而是有调用者所在的线程来执行
        executor.setRejectedExecutionHandler(new ThreadPoolExecutor.CallerRunsPolicy());
        executor.initialize();
        return executor;
    }

    @Bean
    public Executor globalExecutor() {
        ThreadPoolExecutor executor = new ThreadPoolExecutor(5, 20, 60, TimeUnit.SECONDS, new ArrayBlockingQueue<Runnable>(60));
        executor.setThreadFactory(new CustomizableThreadFactory("CustomExecutor-"));
        executor.setRejectedExecutionHandler(new ThreadPoolExecutor.CallerRunsPolicy());
        return executor;
    }
}
```

```
@Service
@Slf4j
public class AccessCountFilter extends ZuulFilter {
    @Autowired
    private ResourceCenterApi resourceApi;
    @Autowired
    private MessageProducerApi messageProducerApi;
    @Autowired
    private MyExecutors executor;

    @Override
    public String filterType() {
        return "post";
    }

    @Override
    public int filterOrder() {
        return 2;
    }

    @Override
    public boolean shouldFilter() {
        return true;
    }

    @Override
    public Object run() throws ZuulException {
        RequestContext ctx = RequestContext.getCurrentContext();
        HttpServletRequest request = ctx.getRequest();
        GatewayUrlCountProcessor processor = new GatewayUrlCountProcessor(request, messageProducerApi);
        executor.customExecutor().execute(processor);
        return null;
    }
}
```

And in GatewayUrlCountProcessor there is a simple call using feign client messageProducerApi with parameters in request.
The constructor of GatewayUrlCountProcessor using deepcopy to clone inneeded parameters.
```
public GatewayUrlCountProcessor(HttpServletRequest request, MessageProducerApi statisticsApi) {
        this.statisticsApi=statisticsApi;
        HashMap<String, String> attributeMap = new HashMap<>();
        Enumeration<String> attributeNames = request.getAttributeNames();
        while (attributeNames.hasMoreElements()) {
            String attributeName = attributeNames.nextElement();
            Object attribute = request.getAttribute(attributeName);
            if (!attributeMap.containsKey(attributeName)) {
                attributeMap.put(attributeName, attribute.toString());
            }
        }
        //异步子线程运行时，request的对象会被销毁从而引发NPE，此处进行深拷贝，线程内部调用message
        this.attributes = SerializationUtils.clone(attributeMap);
        this.parameterMap = SerializationUtils.clone((HashMap) request.getParameterMap());
        this.requestUrl = SerializationUtils.clone(request.getRequestURI());
        this.method = SerializationUtils.clone(request.getMethod());
        this.remoteAddr = SerializationUtils.clone(request.getRemoteAddr());
        this.remotePort = SerializationUtils.clone(request.getRemotePort());
    }
```

I don't know why it happens.

**Comment by WilliamChen-luckbob** [comment]
I have noticed that when I print the debug log.
There is a combine operation like this:
`2021-04-12 11:44:47.729 [app:web-gateway,traceId:0dcefb33704eae4a,spanId:a119cc280198c15b,parentId:0dcefb33704eae4a] [CustomExecutor-2] DEBUG | TracingFeignClient.java:76 |o.s.c.s.i.w.c.f.TracingFeignClient |Handled send of RealSpan(0dcefb33704eae4a/a72463a5b6587b9b)`
my real span id is 0dcefb33704eae4a, but it was chaged to a72463a5b6587b9b when I using threadpool to execute threads.

**Comment by marcingrzejszczak** [comment]
can you check the latest Sleuth `3.0.3-SNAPSHOT` and see if that fixes the problem?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
