### ISSUE TITLE
Add Spring Cloud Task support

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#1903]
Root span would start and be reported at the point of the `TaskExecutorListener`. The name of the span would be `spring.application.name`.

Each of the `CommanLineRunner` or `ApplicationRunner` executions would be a span. The name of the span would be the bean name.

cc @mminella

**Comment by cppwfs** [comment]
We can add this as a feature in 2.4.     Thoughts @mminella .

**Comment by marcingrzejszczak** [comment]
We can add it in Sleuth that's not a problem (I think we even have to do it cause otherwise we could have a release cycle Task depending on Sleuth that depends on a lot of other things). Or we would have to push Task after Sleuth if Task is not used by any other projects.

I've created this issue after talking to @mminella and we're gathering all feedback here.

**Comment by cppwfs** [comment]
That makes sense

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-sleuth/commit/2fca60a112e360b6913ed7b2b9d12c768ce751ad

**Comment by abccbaandy** [comment]
ok, so `ApplicationRunner or CommandLineRunner` will support in `spring cloud 2021.0.0`, and `spring boot 2.6.X` will support `spring cloud 2021.0.0`, right?

**Comment by marcingrzejszczak** [comment]
that's the plan.
