### ISSUE TITLE
Support gradual rollout via spring-cloud-sleuth-autoconfigure

### ISSUE THREAD

**Issue by jimshowalter** [spring-cloud/spring-cloud-sleuth#1907]
We are integrating opentelemetry with a fleet of microservices, and don't want to roll it out all at once, and only want to roll it out initially to a preprod environment, not to all environments.

We have a logging library we developed and that our microservices use. We have added spring-cloud-starter-sleuth and spring-cloud-sleuth-autoconfigure dependencies to our library.

When a microservice upgrades to the latest version of our library, it starts logging traces right away, and in all environments.

Services that don't want to log traces could add

`spring:
	sleuth:
		enabled: false`
 
to application.yaml, but they could forget to do that.

We want to default it to disabled, and then selectively enable it.

And even for services that want to log traces, initially it should be limited to preprod.

We don't see a way to do that with the current code in autoconfigure. Is there a way to do it, perhaps by overriding one or more of the components?

**Comment by jonatan-ivanov** [comment]
I suppose you use [Spring Cloud Sleuth OTel](https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel) with OpenTelemetry. Let me insert a little sidenote about this: neither Spring Cloud Sleuth OTel nor OpenTelemetry are production-ready. As you can see, Sleuth-OTel is an incubator project, while [opentelemetry-java-instrumentation](https://search.maven.org/search?q=g:io.opentelemetry.instrumentation) is in alpha.

I'm not sure if there is a simple way to redefine default behavior of flags in auto-configuration but there are a few things you can do to override the default behavior for everyone:
1. You can utilize [Spring Cloud Config](https://docs.spring.io/spring-cloud-config/docs/current/reference/html/) to override properties. Your property source can be a lot of things but this could be a bigger change for all apps if they are not using it already (also, you need to enforce the usage of this).
2. You can override property files with other [external config sources](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1907), e.g.: Java System properties or OS environment variables. You can do this in your deployment solution so should be fairly easy to do this for all services. I would try to do this in the first place.
3. You can make the services fail at startup if they forget it, [here's a slightly similar example](https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/blob/master/spring-cloud-sleuth-otel-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/otel/MultipleTracerAutoConfigurationsDetector.java) (you need to enforce the usage of this).

**Comment by jimshowalter** [comment]
Yes, we are using these two dependencies:
    implementation("org.springframework.cloud:spring-cloud-starter-sleuth:${sleuthVersion}")
    implementation("org.springframework.cloud:spring-cloud-sleuth-autoconfigure:${sleuthVersion}")
where sleuthVersion=3.0.2.

If these aren't production-ready, is there something else we should be using?

**Comment by jonatan-ivanov** [comment]
*Spring Cloud Sleuth* is stable and prod ready, *Spring Cloud Sleuth OTel* is not (please notice the extra OTel word, also clicking through the links above give more info).

What I would suggest is using *Spring Cloud Sleuth* with Zipkin and not OTel.
