### ISSUE TITLE
Zipkin metrics for prometheus

### ISSUE THREAD

**Issue by lex-em** [spring-cloud/spring-cloud-sleuth#1909]
hello, I have a strange behavior with zipkin metrics: if `spring.zipkin.enabled: false` - metrics are exposed (with zeros), otherwise if `spring.zipkin.enabled: true` - no metrics in endpoint `/actuator/prometheus`, also `/actuator/metrics` does not contain zipkin metrics

Library version - spring-cloud-starter-sleuth:2.2.1

**Comment by marcingrzejszczak** [comment]
Can you create a sample that replicates this issue?

**Comment by lex-em** [comment]
@marcingrzejszczak https://github.com/lex-em/zipkin-metrics-demo

**Comment by marcingrzejszczak** [comment]
Wait a second, what are `zipkin metrics` actually? Also please use the latest versions of the release train and Boot

**Comment by lex-em** [comment]
>Wait a second, what are zipkin metrics actually?
when zipkin turned off in `/actuator/prometheus`:
```
# HELP zipkin_reporter_messages_total Messages reported (or attempted to be reported)
# TYPE zipkin_reporter_messages_total counter
zipkin_reporter_messages_total 0.0
# HELP zipkin_reporter_spans_bytes_total Total bytes of encoded spans reported
# TYPE zipkin_reporter_spans_bytes_total counter
zipkin_reporter_spans_bytes_total 0.0
# HELP zipkin_reporter_spans_dropped_total Spans dropped (failed to report)
# TYPE zipkin_reporter_spans_dropped_total counter
zipkin_reporter_spans_dropped_total 0.0
# HELP zipkin_reporter_queue_spans Spans queued for reporting
# TYPE zipkin_reporter_queue_spans gauge
zipkin_reporter_queue_spans 0.0
# HELP zipkin_reporter_spans_total Spans reported
# TYPE zipkin_reporter_spans_total counter
zipkin_reporter_spans_total 0.0
# HELP zipkin_reporter_messages_bytes_total Total bytes of messages reported
# TYPE zipkin_reporter_messages_bytes_total counter
zipkin_reporter_messages_bytes_total 0.0
# HELP zipkin_reporter_queue_bytes Total size of all encoded spans queued for reporting
# TYPE zipkin_reporter_queue_bytes gauge
zipkin_reporter_queue_bytes 0.0
```

> Also please use the latest versions of the release train and Boot
Unfortunately we can not upgrade globally our large project right now

**Comment by marcingrzejszczak** [comment]
We can't really help you unless you upgrade and see if the problem is not already fixed.

**Comment by lex-em** [comment]
spring cloud version 2020.0.0 and boot 2.4.5 works fine. can you give me some workaround for my versions?

**Comment by marcingrzejszczak** [comment]
Can you also check the latest hoxton version? Cause if the latest hoxton version works fine you need to upgrade.

**Comment by lex-em** [comment]
okay, boot 2.2.13 and Hoxton.SR10 is fine, I'll try to find solution, tnx a lot

**Comment by marcingrzejszczak** [comment]
No problem
