### ISSUE TITLE
No Trace in spring-cloud-stream Kafka Binder

### ISSUE THREAD

**Issue by ruiczhu-sh** [spring-cloud/spring-cloud-sleuth#1918]
Our system has two ways to reach the audit, one is through http api request, and the other is through kafka message input. Our target is to get the unique trace id for both of them.
The dependency we use for spring cloud stream kafka is:
`<dependency>`
     ` <groupId>org.springframework.cloud</groupId>`
     ` <artifactId>spring-cloud-starter-stream-kafka</artifactId>`
`</dependency>`

Our sleuth is rely on gcp starter trace:
`<dependency>`
   ` <groupId>com.google.cloud</groupId>`
   ` <artifactId>spring-cloud-gcp-starter-trace</artifactId>`
`</dependency>`

When an http api request is sent, I could successfully get the trace id because coroutineContext[ReactorContext] is not empty and trace id is included in the first key-value pair of its context.
However, when I try to get trace id from kafka message input, the  coroutineContext[ReactorContext] is empty and there is no trace id included.

`fun consumeMessage(): Function<Flux<String>, Mono<Void>> {`
   ` return java.util.function.Function { flux: Flux<String> ->`
       ` flux.asFlow().map {it}.asFlux().then() }`
`}`
When I print out the “it” in the above function, reactorContext id not included.

It seems that I could only get trace id from reactorContext, but how can I also get the trace id for kafka message input?

For debugging comparison, the type of coroutineContext for http api request is: combinedContext “[kotlinx.coroutines.reactor.ReactorContext]” There are many key-value pairs inside context, and the first one is the traceContext where the trace id is included; the type of that for kafka message is: combinedContext “[StandaloneCoroutine{Active}]”.

![Screen Shot ](https://user-images.githubusercontent.com/77034857/115378379-13757b00-a203-11eb-8691-fad86a3233b9.png)

**Comment by marcingrzejszczak** [comment]
If you're using `Flux` in Spring Cloud Stream then you have to either propagate the context manually (https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/integrations.html#sleuth-messaging-spring-cloud-function-integration) or set `spring.sleuth.integration.enabled=true` (that way you disable the native Spring Cloud Stream / Function support).

**Comment by ruiczhu-sh** [comment]
I added `spring: sleuth: integration: enabled: true` in the yaml document, but the result remains the same. Is there any other solution besides adding the context manually?

**Comment by marcingrzejszczak** [comment]
Hmm that should work - we have even benchmark tests for that - https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/benchmarks/src/test/java/org/springframework/cloud/sleuth/benchmarks/jmh/stream/MicroBenchmarkStreamTests.java#L166-L167 . Can you create a Java, Maven based sample that replicates the issue?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by ruiczhu-sh** [comment]
Sure. Let me try to create a sample and see if there is any other problem. Thanks.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
