### ISSUE TITLE
Kafka Instrumentation Issues

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-sleuth#1921]
Spring for Apache Kafka has a bug whereby the results of calling the Producer/Consumer post processors are discarded

https://github.com/spring-projects/spring-kafka/issues/1778

```
this.postProcessors.forEach(pp -> pp.apply(kafkaProducer));
```

This means that the `TraceProducerPostProcessor` is a no-op.

However, Sleuth still works because the factory is also wrapped in a proxy and the producer created by the factory is wrapped in a `TracingProducer`.

Final wrapping:

- `TracingProducer`
- - `CloseSafeProducer`
- - - `KafkaProducer`

When we fix the spring-kafka bug, we'll end up with 

- `TracingProducer`
- - `CloseSafeProducer`
- - - `TracingProducer`
- - - - `KafkaProducer`

More context:

https://stackoverflow.com/questions/67194702/sleuth-tracing-is-not-working-for-transactional-kafka-producers/67196367#67196367

**Comment by garyrussell** [comment]
With spring-kafka bug fixed

![image](https://user-images.githubusercontent.com/483832/115573859-1c139300-a28f-11eb-906c-638ea1448296.png)
![image](https://user-images.githubusercontent.com/483832/115573889-22097400-a28f-11eb-9cf1-cdcfbb052cd2.png)

**Comment by marcingrzejszczak** [comment]
@garyrussell would this fix the problem? https://github.com/spring-cloud/spring-cloud-sleuth/pull/1923

**Comment by garyrussell** [comment]
It would fix the `Consumer` case but, yes, with the producer case we already wrap the raw producer.

[so67194702.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/6352841/so67194702.zip)

To get the double wrapping, you would need to change the pom to use spring-kafka 2.7.1-SNAPSHOT (commented out) and wait for [this build](https://build.spring.io/browse/SK-MAS-1384) to complete.

**Comment by garyrussell** [comment]
Actually, in some cases, even with the consumer, we sometimes wrap it in a proxy.
