### ISSUE TITLE
Spring Cloud support OpenTelemetry

### ISSUE THREAD

**Issue by HaojunRen** [spring-cloud/spring-cloud-sleuth#1926]
OpenTelemetry has released stable version for 1.1.0, will Spring Cloud continue to integrate with it? Thanks a lot

**Comment by marcingrzejszczak** [comment]
Check the spring cloud sleuth otel project where we integrate with OTel. The problem is that otel java instrumentation is not ga. Once it's not alpha we will consider our next steps

**Comment by HaojunRen** [comment]
This feature only supports 2020, or include Hoxton?

**Comment by spencergibb** [comment]
It will not support Hoxton. In fact it won't support 2020.0, only 2021.0.

**Comment by HaojunRen** [comment]
Additional question:
spring cloud sleuth otel project only supports Zikpin? Will support Uber Jaeger or more?

**Comment by marcingrzejszczak** [comment]
Please read the docs - https://spring-cloud-incubator.github.io/spring-cloud-sleuth-otel/docs/current/reference/html/project-features.html#features-otel-exporters

**Comment by orange-buffalo** [comment]
Sorry for bringing this up again, just wanted to clarify OpenTelemetry support status. 

Spring Cloud Sleuth OpenTelemetry has [just released](https://spring.io/blog/2022/09/16/spring-cloud-sleuth-opentelemetry-otel-1-1-0-has-been-released) their first GA version. But they still are hosted in `spring-projects-experimental` namespace. Are there any plans to integrate Otel support into `spring-cloud-sleuth` project directly or should we expect `spring-cloud-sleuth-otel` to be a separate (experimental) project for a long time yet?

**Comment by marcingrzejszczak** [comment]
We still depend on OpenTelemetry's alpha non ga versions. Also Sleuth 3.1.x is the last release minor for sleuth so we're not planning to add any new features there
