### ISSUE TITLE
Allow ZipkinRestTemplateWrapper configuration

### ISSUE THREAD

**Issue by dimi-nk** [spring-cloud/spring-cloud-sleuth#1932]
**Is your feature request related to a problem? Please describe.**
There's currently no way to tune the internal `ClientHttpRequestFactory` created in `ZipkinRestTemplateWrapper`, e.g. configure the acceptable request timeout.

**Describe the solution you'd like**
- Programmatic configuration of the internal `ClientHttpRequestFactory`
- Declarative configuration via props
- Provide the internal `ClientHttpRequestFactory` via an overridable `@Bean`

**Describe alternatives you've considered**
You can provide a new `Sender` `@Bean` but you need to duplicate most of the code used, e.g. `ZipkinUrlExtractor` and `ZipkinLoadBalancer` are package-private and cannot be re-used.

```java
@Bean
Sender customZipkinSender(
    RestTemplateBuilder builder,
    ZipkinProperties zipkin,
    ZipkinRestTemplateCustomizer zipkinRestTemplateCustomizer) {
  var restTemplate =
      builder
          .setConnectTimeout(Duration.ofMillis(1000))
          .setReadTimeout(Duration.ofMillis(1000))
          .build();

  zipkinRestTemplateCustomizer.customizeTemplate(restTemplate);
  return new RestTemplateSender(restTemplate, zipkin.getBaseUrl(), zipkin.getEncoder());
}
```

**Additional context**
N/A

**Comment by marcingrzejszczak** [comment]
Hmm `ZipkinUrlExtractor` and `ZipkinLoadBalancer` are public in `3.0.x`. I will add an option to just provide the `RestTemplate` though for Zipkin sending - that makes sense.

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-sleuth/commit/4fef057e96d950729a48d7dad319824c577efaf9

**Comment by dimi-nk** [comment]
Thanks @marcingrzejszczak 🙏🏼
