### ISSUE TITLE
Sleuth not picking traceId from the header x-b3-traceid

### ISSUE THREAD

**Issue by rastogirishabh** [spring-cloud/spring-cloud-sleuth#1935]
Hi, 
I'm using javax.servlet.Filter and javax.servlet.http.HttpServletRequestWrapper to set **x-b3-traceid** and **x-b3-spanid** once the request has been received. I'm following the contract of 32 bit lower hex encoded into 16 characters while setting these two values. However, sleuth does not picks values from these headers and it generates a new trace Id which ideally it shouldn't do if these two headers contains value.
```
@Component
public class CorrelationIdFilter implements Filter {

  @Override
  public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse,
      FilterChain filterChain) throws IOException, ServletException {

    HttpServletRequest wrapperRequest = new CorrelationHeaderManipulator((HttpServletRequest) servletRequest);
    String traceId = wrapperRequest.getHeader("x-b3-traceid");
    String spanId = wrapperRequest.getHeader("x-b3-spanid");

    filterChain.doFilter(wrapperRequest, servletResponse);
  }
}
```
```
@Component
public class CorrelationHeaderManipulator extends HttpServletRequestWrapper {

  public CorrelationHeaderManipulator(HttpServletRequest request) {
    super(request);
  }

  @Override
  public String getHeader(String name) {
    return "004a6f0eac534d44";
  }
}
```

Ideally it sleuth should not generate the traceId and should return **004a6f0eac534d44**.

**Comment by marcingrzejszczak** [comment]
It does work fine, please check the samples here https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples/ (e.g. pick resttemplate and mvc) and you will see that things are working fine.

**Comment by rastogirishabh** [comment]
@marcingrzejszczak - I'm using Spring WebFlux and WebClient to call the downstream services. What am I missing here?

**Comment by marcingrzejszczak** [comment]
I don't know - please check the samples. You have a webflux and a webclient sample there too. What you're doing is absolutely the most basic Sleuth functionality that we have thoroughly tested. You're saying that you're using WebFlux and you're using a standard servlet filter. That will not work.
