### ISSUE TITLE
Unsatisfied dependency while using sleuth otel

### ISSUE THREAD

**Issue by SunithaRajan** [spring-cloud/spring-cloud-sleuth#1938]
**I want to implement distributed tracing using sleuth-otel** 
Our apps are hosted in GKE, Currently we implemented that using `spring-cloud-sleuth-core-2.2.7.RELEASE` and `spring-cloud-gcp-starter-trace
-1.2.7.RELEASE` It is working fine and we are getting traceId exported to `GCP Trace API`. But we want to upgrade this feature using sleuth-otel.

My question is, is it possible to export traceId to GCP trace API using sleuth-otel ?
If yes, can you tell me what did i miss. These are my changes,
`      
      <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-sleuth-brave</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-otel-autoconfigure</artifactId>
            <version>1.0.0-M7</version>
     </dependency>
     <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2020.0.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-sleuth-otel-dependencies</artifactId>
                <version>1.0.0-M7</version>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>
`
also i added the below in application.properties
`spring.application.name=app-name
spring.sleuth.otel.log.exporter.enabled=true
spring.sleuth.otel.log.slf4j.enabled=true`

Build gets succeed but while running the app i got error like this,
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'httpClientBeanPostProcessor', defined in class path resource [org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientAutoConfiguration$NettyConfiguration.class], could not be registered.
 A bean with that name has already been defined in class path resource [org/springframework/cloud/sleuth/autoconfig/instrument/web/client/TraceWebClientAutoConfiguration$NettyConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

And this is my mvn dependency:tree 

[INFO] +- org.springframework.cloud:spring-cloud-starter-sleuth:jar:2.2.7.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter:jar:2.2.7.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-context:jar:2.2.7.RELEASE:compile
[INFO] |  |  |  \- org.springframework.security:spring-security-crypto:jar:5.3.6.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-commons:jar:2.2.7.RELEASE:compile
[INFO] |  |  \- org.springframework.security:spring-security-rsa:jar:1.0.9.RELEASE:compile
[INFO] |  |     \- org.bouncycastle:bcpkix-jdk15on:jar:1.64:compile
[INFO] |  |        \- org.bouncycastle:bcprov-jdk15on:jar:1.64:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-aop:jar:2.3.7.RELEASE:compile
[INFO] |  |  \- org.aspectj:aspectjweaver:jar:1.9.6:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-sleuth-core:jar:2.2.7.RELEASE:compile
[INFO] |     +- org.aspectj:aspectjrt:jar:1.9.6:compile
[INFO] |     +- io.zipkin.brave:brave:jar:5.12.7:compile
[INFO] |     |  \- io.zipkin.reporter2:zipkin-reporter-brave:jar:2.15.2:compile
[INFO] |     +- io.zipkin.brave:brave-context-slf4j:jar:5.12.7:compile
[INFO] |     +- io.zipkin.brave:brave-instrumentation-messaging:jar:5.12.7:compile
[INFO] |     +- io.zipkin.brave:brave-instrumentation-rpc:jar:5.12.7:compile
[INFO] |     +- io.zipkin.brave:brave-instrumentation-spring-web:jar:5.12.7:compile
[INFO] |     |  \- io.zipkin.brave:brave-instrumentation-http:jar:5.12.7:compile	----
[INFO] |     +- io.zipkin.brave:brave-instrumentation-spring-rabbit:jar:5.12.7:compile
[INFO] |     +- io.zipkin.brave:brave-instrumentation-kafka-clients:jar:5.12.7:compile
[INFO] |     +- io.zipkin.brave:brave-instrumentation-kafka-streams:jar:5.12.7:compile
[INFO] |     +- io.zipkin.brave:brave-instrumentation-httpclient:jar:5.12.7:compile		----
[INFO] |     +- io.zipkin.brave:brave-instrumentation-httpasyncclient:jar:5.12.7:compile
[INFO] |     +- io.zipkin.brave:brave-instrumentation-spring-webmvc:jar:5.12.7:compile
[INFO] |     |  \- io.zipkin.brave:brave-instrumentation-servlet:jar:5.12.7:compile
[INFO] |     +- io.zipkin.brave:brave-instrumentation-jms:jar:5.12.7:compile
[INFO] |     \- io.zipkin.reporter2:zipkin-reporter-metrics-micrometer:jar:2.15.2:compile
[INFO] |        +- io.zipkin.reporter2:zipkin-reporter:jar:2.15.2:compile
[INFO] |        \- io.zipkin.zipkin2:zipkin:jar:2.21.7:compile					
[INFO] |  +- org.springframework.cloud:spring-cloud-sleuth-otel-autoconfigure:jar:1.0.0-M7:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-sleuth-autoconfigure:jar:3.0.3-SNAPSHOT:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-sleuth-instrumentation:jar:3.0.3-SNAPSHOT:compile
[INFO] |  |  \- org.springframework.cloud:spring-cloud-sleuth-api:jar:3.0.3-SNAPSHOT:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-sleuth-otel:jar:1.0.0-M7:compile
[INFO] |  |  \- io.opentelemetry:opentelemetry-extension-aws:jar:1.0.0:compile
[INFO] |  +- io.opentelemetry:opentelemetry-api:jar:1.0.0:compile
[INFO] |  |  \- io.opentelemetry:opentelemetry-context:jar:1.0.0:compile
[INFO] |  +- io.opentelemetry:opentelemetry-semconv:jar:1.0.1-alpha:compile
[INFO] |  +- io.opentelemetry:opentelemetry-sdk-common:jar:1.0.0:compile
[INFO] |  +- io.opentelemetry:opentelemetry-sdk-trace:jar:1.0.0:compile
[INFO] |  +- io.opentelemetry:opentelemetry-sdk:jar:1.0.0:compile
[INFO] |  +- io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:jar:1.0.1-alpha:compile
[INFO] |  +- io.opentelemetry.instrumentation:opentelemetry-instrumentation-api:jar:1.0.1-alpha:compile
[INFO] |  \- io.opentelemetry:opentelemetry-extension-trace-propagators:jar:1.0.0:compile
[INFO] +- org.springframework.boot:spring-boot:jar:2.3.7.RELEASE:compile

I observed one thing, `spring-cloud-starter-sleuth` also uses `spring-cloud-sleuth-core` internally. Do we really need this ?
  If i exclude the 'spring-cloud-sleuth-core` 
 that error has gone and i got the traceID in logs as follows

`INFO[app-name,608ff343d205770232bd9a6e50779e6c,608fbb6aeca362ce3120ba18f3b874a3]`
which doesn't have exporter flag.
Also in this case that traceId gets propogated along the apps and i saw same same traceID in the entire flow same as above(without exporter flag).
So that traces are not getting exported to GCP. Can you tell me did i miss anything in the above scenario or do i need to add any other dependencies along with the above one to make it export to GCP. Otherwise, do i need to create any beans for exporting.

Thanks in Advance :)

**Comment by spencergibb** [comment]
I don't believe it's compatible with sleuth 2.x and gcp 1.x.

**Comment by marcingrzejszczak** [comment]
Yes, it's not compatible

**Comment by SunithaRajan** [comment]
Oh is it. Then cannot we export traces to GCP using sleuth otel ? or Which versions of otel supports GCP

**Comment by spencergibb** [comment]
GCP is no longer part of the release train. You'll need to go watch here https://github.com/GoogleCloudPlatform/spring-cloud-gcp
