### ISSUE TITLE
Support intrumentation for  LogNet grpc-client-spring-boot-starter

### ISSUE THREAD

**Issue by oburgosm** [spring-cloud/spring-cloud-sleuth#1949]
Currently gRPC  instrumentation is supported for Lognet grpc-spring-boot-starter, but not for a gRPC client that use Lognet grpc-**client**-spring-boot-starter,

In this case BraveGrpcAutoConfiguration is not loaded because class 'org.lognet.springboot.grpc.GRpcGlobalInterceptor' is not in classpath

I think will be fine that BraveGrpcAutoConfiguration take this into account, with a solution similar to  this other: https://github.com/yidongnan/grpc-spring-boot-starter/issues/194

**Comment by marcingrzejszczak** [comment]
We are not planning on adding any new features for Sleuth
