### ISSUE TITLE
Add Spring Data, Hibernate and SQL showing support for instrumentation

### ISSUE THREAD

**Issue by bmistry13** [spring-cloud/spring-cloud-sleuth#1951]
**Is your feature request related to a problem? Please describe.**
We need the ability to track, Spring Data, Hibernate, and SQL calls are taking for Application with Spring Sleuth.  Open telemetry Java Instrumentation provides auto instrumentation of Spring Data, Hibernate, and SQL calls are taking in the distributive trace, but I do not see this ability with Spring sleuth.

Please see following for more discussion: 
https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/issues/53 

Please refer to the following image which shows the full Open telemetry Java Agent report which is not possible with Spring sleuth:
https://user-images.githubusercontent.com/9261969/117698681-d274e480-b178-11eb-93e7-ba790ef150a0.png 

**Describe the solution you'd like**
I had to add Open Telemetry Java Agent ( it used to work with Spring-sleuth-otel but no logger works).

**Describe alternatives you've considered**

There is not alternative.

**Additional context**

**Comment by marcingrzejszczak** [comment]
dulicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/1930
