### ISSUE TITLE
Baggage remote fields propagation is case sensitive for spring cloud Hoxton.SR11

### ISSUE THREAD

**Issue by lanmingle** [spring-cloud/spring-cloud-sleuth#1955]
There are plans to fix it in Hoxton.SR12 #1874

**Comment by marcingrzejszczak** [comment]
Are you interested in cherry-picking the change?

**Comment by lanmingle** [comment]
@marcingrzejszczak 

Hello! Thank you for your approval. At present, I can only use sleuth. I don't know the internal details. Thank you!

**Comment by lanmingle** [comment]
o(╥﹏╥)o

**Comment by marcingrzejszczak** [comment]
I'll close this issue for now and if there are more people interested in this we'll think of coming back to it.
