### ISSUE TITLE
awspring compatibility

### ISSUE THREAD

**Issue by nekperu15739** [spring-cloud/spring-cloud-sleuth#1956]
Since we do the upgrade to use spring cloud 2020.0.2 and in favor of continue using aws we add [io.awspring.cloud ](https://spring.io/blog/2021/03/17/spring-cloud-aws-2-3-is-now-available) dependency, however, we loose sleuth functionalities on SQS, checking deeper we saw that TraceMessagingAutoConfiguration is still using older dependencies

Hoxton
`org.springframework.cloud.aws.messaging.config.QueueMessageHandlerFactory;`
`org.springframework.cloud.aws.messaging.listener.QueueMessageHandler;`

io.awspring.cloud 
`io.awspring.cloud.messaging.config.QueueMessageHandlerFactory`
`io.awspring.cloud.messaging.listener.QueueMessageHandler`

is there any work around to solve the issue?

Kind regards

**Comment by marcingrzejszczak** [comment]
We don't have the `TraceMessagingAutoConfiguration` class in 3.0.x version of Sleuth. 

We don't plan to support this ATM. You can ask at the Spring Cloud AWS project for adding this feature.
