### ISSUE TITLE
Relative time of spans retried by hystrix is wrong

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#196]
The spans are shifted to the left.

**Comment by adriancole** [comment]
let's start by capturing the essence of what a hystrix retry looks like. Ex. in finagle a retry is simply an annotation/log named finagle.retry (it isn't a new span). In this case, there's no risk of shifting. What is the shape of a retry? I'm assuming it is a span? Is it repeating RPC annotations (as opposed to using wire send ("ws"))?

**Comment by marcingrzejszczak** [comment]
I would assume that each time a new span is created but I have no proof yet. Will try to check it once I finish the first iteration of the docs.

**Comment by marcingrzejszczak** [comment]
I can't replicate it and I found a bug in Brewery (unclosed span on exception). I've reran the tests and now the spans seem to be ok:

![spans_with_retry](https://cloud.githubusercontent.com/assets/3297437/13571104/f16835b4-e472-11e5-8643-bc1280148917.png)
