### ISSUE TITLE
TraceableExecutorService lose Trace Info

### ISSUE THREAD

**Issue by CrackerGit** [spring-cloud/spring-cloud-sleuth#1966]
when i use spring cloud stream ,  it create binder in LIfeStyle.start but this time Context is not refreshed，so wo use TraceableExecutorService.execute will miss trace info.

**Comment by marcingrzejszczak** [comment]
Can you provide any meaningful information? A sample, version numbers etc.

**Comment by CrackerGit** [comment]
spring-cloud-sleuth 2.1.7.RELEASE
![image](https://user-images.githubusercontent.com/44165444/120599350-f7a7fa80-c479-11eb-9b84-f70f7264e67d.png)
spring-cloud-stream 2.1.4.RELEASE
![image](https://user-images.githubusercontent.com/44165444/120599077-a566d980-c479-11eb-9e6a-16cc27bf11bb.png)

**Comment by marcingrzejszczak** [comment]
You're using very old versions of sleuth. Please upgrade

**Comment by CrackerGit** [comment]
I looked at the Sleuth code in version 2.2.4 and the issue hasn't changed
![image](https://user-images.githubusercontent.com/44165444/120609142-83268900-c484-11eb-8a67-ff8f1b801ab5.png)
ApplicationContext needs to publish a ContextFreshedEvent
![image](https://user-images.githubusercontent.com/44165444/120609250-95a0c280-c484-11eb-8afc-2f81e674dac1.png)

**Comment by marcingrzejszczak** [comment]
Please don't paste screen shots of your code. Prepare a simple java maven sample that replicates the problem or a failing issue inside sleuth code.
