### ISSUE TITLE
how to send the trace span to istio / kubernetes?

### ISSUE THREAD

**Issue by nikita111100** [spring-cloud/spring-cloud-sleuth#1968]
If I add your dependency my metrics don't go up to istio/kubernetes

If I am not using your library, my metrics go down to istio.

I am submitting metrics using: 

       <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-spring-jaeger-cloud-starter</artifactId>
            <version>3.3.1</version>
        </dependency>

**Comment by marcingrzejszczak** [comment]
We're not maintaining that project. Please file an issue in their repo.
