### ISSUE TITLE
how to send gRPC  trace span to istio / kubernetes?

### ISSUE THREAD

**Issue by nikita111100** [spring-cloud/spring-cloud-sleuth#1970]
**I try to send trace span to k8s/istio.** 

I set this properties but it doesn't works for me 

spring.sleuth.propagation.type = b3
spring.sleuth.grpc.enabled= true
spring.sleuth.baggage.remote-fields= x-request-id, x-b3-traceid.....

**The application's environment** 

- Spring boot  : 2.3.1
- Spring-cloud-starter-sleuth : 2.2.8 
- grpc-client-spring-boot-autoconfigure : 2.12.0

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by nikita111100** [comment]
I have an external request to the aggregator, from which there is a request to the gRPC server. I only get metrics from ingress-gateway to aggregator. and from the aggregator to the grpc service. It turns out that I do not build a complete query dependency tree, but only two parts of it. How can I get the complete dependency tree?

I have no calls connected. I cannot propagate headers.

`@Service
public class GrpcService {

    @GrpcClient("square")
    private SquareRpcGrpc.SquareRpcBlockingStub blockingStub;

    @GrpcClient("square")
    private SquareRpcGrpc.SquareRpcStub asyncStub ;

    public Object getSquareResponseUnary(int number){
        return IntStream.rangeClosed(1, number)
                .mapToObj(i -> Input.newBuilder().setNumber(i).build())
                .map(this.blockingStub::findSquareUnary)
                .collect(Collectors.toMap(
                        Output::getNumber,
                        Output::getResult
                ));
    }

    public Object getSquareResponseStream(int number){
        CompletableFuture<Map<Integer, Integer>> completableFuture = new CompletableFuture<>();
        OutputStreamingResponse outputStreamingResponse = new OutputStreamingResponse(
                new HashMap<>(),
                completableFuture
        );
        StreamObserver<Input> squareBiStream = this.asyncStub.findSquareBiStream(outputStreamingResponse);
        IntStream.rangeClosed(1, number)
                .mapToObj(i -> Input.newBuilder().setNumber(i).build())
                .forEach(squareBiStream::onNext);
        squareBiStream.onCompleted();
        return completableFuture;
    }`
