### ISSUE TITLE
how to send gRPC trace span to istio / kubernetes?

### ISSUE THREAD

**Issue by nikita111100** [spring-cloud/spring-cloud-sleuth#1972]
**Describe the bug**

I am trying to get tracing span in istio / kubernetes. I am using a spring boot 2.2.8 RELEASE.
After add dependency, I don't get the metric in the istio dashboard jaeger. I think propagate headers does not work for me.
Сould you tell me how to set up the endpoint correctly or create a bean.
I am using gRPC and REST protocols.

**Sample**
```
@GrpcClient("square")
private SquareRpcGrpc.SquareRpcBlockingStub blockingStub;

@GrpcClient("square")
private SquareRpcGrpc.SquareRpcStub asyncStub ;

public Object getSquareResponseUnary(int number){
    return IntStream.rangeClosed(1, number)
            .mapToObj(i -> Input.newBuilder().setNumber(i).build())
            .map(this.blockingStub::findSquareUnary)
            .collect(Collectors.toMap(
                    Output::getNumber,
                    Output::getResult
            ));
}

public Object getSquareResponseStream(int number){
    CompletableFuture<Map<Integer, Integer>> completableFuture = new CompletableFuture<>();
    OutputStreamingResponse outputStreamingResponse = new OutputStreamingResponse(
            new HashMap<>(),
            completableFuture
    );
    StreamObserver<Input> squareBiStream = this.asyncStub.findSquareBiStream(outputStreamingResponse);
    IntStream.rangeClosed(1, number)
            .mapToObj(i -> Input.newBuilder().setNumber(i).build())
            .forEach(squareBiStream::onNext);
    squareBiStream.onCompleted();
    return completableFuture;
}

```
my code [https://github.com/nikita111100/gRPC-vs-REST/tree/main/aggregator-service](url)

I set this properties but it doesn't works for me

spring.sleuth.propagation.type = b3
spring.sleuth.grpc.enabled= true
spring.sleuth.baggage.remote-fields= x-request-id, x-b3-traceid.....

The application's environment

Spring boot : 2.3.1
Spring-cloud-starter-sleuth : 2.2.8 RELEASE.
grpc-client-spring-boot-autoconfigure : 2.12.0

**Comment by marcingrzejszczak** [comment]
You're using Sleuth 2.x. To have the propagation type supported you have to use Sleuth 3.x. That implies using Boot 2.4 or 2.5 and 2020.0.3 cloud.

**Comment by nikita111100** [comment]
Now i am using Sleuth 3.0.3 and SpringBoot 2.5.0

Distribution headers don't work for me

Does Sleuth have a documentation how to use istio / kubernetes?  :)

**Comment by marcingrzejszczak** [comment]
Propagation works fine in any environment including kubernetes because it's platform agnostic.

**Comment by nikita111100** [comment]
If I configured my application properties 

spring.sleuth.propagation.type=b3
spring.sleuth.grpc.enabled=true
spring.sleuth.baggage.remote-fields=x-b3-traceid, x-b3-traceid ,x-b3-spanid,x-b3-parentspanid,x-b3-sampled,x-b3-flags,x-ot-span-context

I see

2021-06-09 11:08:03.799  INFO [grpc-service,,] 8 --- [ool-1-thread-12] c.vinsguru.square.service.MyGrpcService  : call findSquareUnary
2021-06-09 11:08:03.806  INFO [grpc-service,,] 8 --- [ool-1-thread-15] c.vinsguru.square.service.MyGrpcService  : call findSquareUnary
2021-06-09 11:08:03.814  INFO [grpc-service,,] 8 --- [ool-1-thread-19] c.vinsguru.square.service.MyGrpcService  : call findSquareUnary
2021-06-09 11:08:03.824  INFO [grpc-service,,] 8 --- [pool-1-thread-3] c.vinsguru.square.service.MyGrpcService  : call findSquareUnary
2021-06-09 11:08:03.832  INFO [grpc-service,,] 8 --- [pool-1-thread-6] c.vinsguru.square.service.MyGrpcService  : call findSquareUnary
2021-06-09 11:08:03.841  INFO [grpc-service,,] 8 --- [pool-1-thread-9] c.vinsguru.square.service.MyGrpcService  : call findSquareUnary

**Comment by marcingrzejszczak** [comment]
Are you following the required GRPC instrumentation setup https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/integrations.html#sleuth-rpc-grpc-integration ?

**Comment by nikita111100** [comment]
Yes :) , I chose variant 2. i use grpc-spring-boot-starter.

**In documentation  said:**
Grpc Spring Boot Starter automatically detects the presence of Spring Cloud Sleuth and Brave’s instrumentation for gRPC and registers the necessary client and/or server tooling.

but it doesn't work for me. :(

**Comment by nikita111100** [comment]
i solve this problem. i create a bean @GrpcGlobalClientInterceptor
