### ISSUE TITLE
datasource-proxy log level is always DEBUG, despite setting property to INFO

### ISSUE THREAD

**Issue by ctsag** [spring-cloud/spring-cloud-sleuth#1973]
I'm using 2021.0.0-SNAPSHOT to get datasource-proxy functionality.

I'm setting the property spring.sleuth.jdbc.datasource-proxy.query.log-level to INFO and I get nothing in my log.

Added a breakpoint here DataSourceProxyBuilderCustomizer#customize(ProxyDataSourceBuilder proxyDataSourceBuilder

and it seems that the result of this.datasourceProxy.getQuery().getLogLevel() is always DEBUG , regardless of what you set it the the property to.

Tried the same datasource-proxy scenario via datasource-proxy-spring-boot-starter 1.7.1 and it works fine.

Please let me know if I can provide any further information

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-sleuth/commit/f7eb39891720675e0fa25d0fea5d773839b59cc3
