### ISSUE TITLE
With latest AbstractTraceHttpRequestInterceptor, spans cannot be closed when exceptions occur while sending HTTP request

### ISSUE THREAD

**Issue by dnathanson** [spring-cloud/spring-cloud-sleuth#198]
In `TraceRestTemplateInterceptor`, `publishStartEvent()` is called before sending the HTTP request.  `publishStartEvent()` now creates a child span and sets it as current span on thread.  The child span is expected to be closed when `TraceHttpResponse.close()` is called.  But if an exception happens in `ClientHttpRequestExecution.execute()`, a response object is not returned and so the span is never closed.
This causes an error when `Tracer` tried to close or detach the current span (in my case invoked from `SleuthHystrixConcurrencyStrategy`.

```
o.s.cloud.sleuth.util.ExceptionUtils    : Tried to detach trace span but it is not the current span: [Trace: 14dd71dd28e39053, Span: 14dd71dd28e39053, exportable=true]. You may have forgotten to close or detach [Trace: 14dd71dd28e39053, Span: e7d1934fd517e593, exportable=true]
```

**Comment by marcingrzejszczak** [comment]
Do you have a sample project you could share?

**Comment by marcingrzejszczak** [comment]
You can check this branch and see if it's working fine now - https://github.com/spring-cloud/spring-cloud-sleuth/compare/issues_%23198_rest_templ_interceptor

**Comment by dnathanson** [comment]
That fixes the issue. Thanks!

One thing...  Since you are rethrowing the exception, there is no need to include the exception/stack trace in your log message.  I'm using Spring's `@Retryable` annotation and I end up with three of your stack traces, followed by my own stack trace in the logs.

**Comment by marcingrzejszczak** [comment]
True, good point!
