### ISSUE TITLE
Cannot Find Tracing Kafka Producer Factory

### ISSUE THREAD

**Issue by PedroEsnaola** [spring-cloud/spring-cloud-sleuth#1988]
**Describe the bug**
Even in the most recent version of spring cloud (2020.0.3) the package org.springframework.cloud.sleuth.instrument.kafka its not present

**Comment by jonatan-ivanov** [comment]
I'm not sure what you are looking for but the Kafka-related instrumentation classes are under [`org.springframework.cloud.sleuth.brave.instrument.messaging`](https://github.com/spring-cloud/spring-cloud-sleuth/tree/main/spring-cloud-sleuth-brave/src/main/java/org/springframework/cloud/sleuth/brave/instrument/messaging) and [`org.springframework.cloud.sleuth.instrument.messaging`](https://github.com/spring-cloud/spring-cloud-sleuth/tree/main/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/messaging)
