### ISSUE TITLE
No X-Trace-Id and X-Span-Id in response when zuul is used

### ISSUE THREAD

**Issue by ishchenko** [spring-cloud/spring-cloud-sleuth#199]
In Brixton.M5 powered zuul proxy, and want to get `X-Trace-Id` and `X-Span-Id` headers in response to proxy.

But when `org.springframework.cloud.sleuth.instrument.web.TraceFilter` tries to write `X-Trace-Id` and `X-Span-Id` headers to `HttpServletResponse`, it gets ignored because reponse has already been commited in `org.springframework.cloud.netflix.zuul.filters.post.SendResponseFilter`. `SendResponseFilter` performed flush earlier.

I could work around this issue using my own ZuulFilter and performing
```
Span spanFromRequest = (Span) request.getAttribute(TraceFilter.class.getName() + ".TRACE");
if (spanFromRequest != null) {
    context.addZuulResponseHeader(Span.TRACE_ID_NAME,  Span.toHex(spanFromRequest.getTraceId()));
}
````
sleuth should probably call `com.netflix.zuul.context.RequestContext#addZuulResponseHeader` when instrumenting zuul requests

**Comment by marcingrzejszczak** [comment]
In the brewery tests there is a Zuul app and it passes trace and span id without any issues. Can you post a sample project?

**Comment by marcingrzejszczak** [comment]
The service with name "zuul" is in fact, well, Zuul :P

![zuul](https://cloud.githubusercontent.com/assets/3297437/13497153/37e90dc8-e154-11e5-92fd-ca4538028b0f.png)

**Comment by ishchenko** [comment]
In my case zuul-powered service is the first one to handle the request. Maybe that matters. I will try to provide sample project

**Comment by marcingrzejszczak** [comment]
Ah ok have you defined the property to sample all requests? `spring.sleuth.sampler.percentage=1.0` ?

**Comment by ishchenko** [comment]
I use AlwaysSampler. It samples well, I have all my traces in logs.

**Comment by marcingrzejszczak** [comment]
Interesting... so I'm waiting for the sample project

**Comment by ishchenko** [comment]
See demo project attached https://yadi.sk/d/9_xFPL-LptfKq
Unzip and mvnw test

**Comment by dsyer** [comment]
I can confirm that the proxy is not sending traceids back in the responses. It's probably not intentional, but arguably it's not a bad thing that Zuul is not adding response headers for Sleuth. Wouldn't you want the backend to supply the traceid (if anyone did)?

**Comment by dsyer** [comment]
Actually it's quite interesting. The HTTP response comes back from the proxy before the `TraceFilter` has finished processing it. The response is sent by Zuul pre-emptively, which might be an indication of a problem in Zuul, not Sleuth.

**Comment by ishchenko** [comment]
That's right, and zuul commits it before Sleuth can write it's own headers. And when no actual proxying happend, say 302, then X-Trace-Id are present. 

I think, sleuth should use addZuulResponseHeader to add its headers to zuul-managed response. They can be set before zuul starts to handle the request.

**Comment by dsyer** [comment]
I think maybe Zuul should just add the headers before any other processing is done. I suppose you can't opt in to have the back end set it then. Or maybe you get 2 headers. I'll have to check.
