### ISSUE TITLE
Resolution exception when using dependency on spring-cloud-starter-sleuth in a modular Java app

### ISSUE THREAD

**Issue by rhollander73** [spring-cloud/spring-cloud-sleuth#1991]
When using a dependency on "spring-cloud-starter-sleuth" in a Java moduler app, a module resolution exception will occur during the initialization of the boot layer. This is because the package "org.springframework.cloud.sleuth.autoconfig" exists within two modules which causes a package split. These are the modules within this repo which both contain this package:
- spring-cloud-sleuth-api
- spring-cloud-sleuth-autoconfigure

The solution to this is to move the interface SingleSkipPattern in the "spring-cloud-sleuth-api" to another package (it's the only class in this package). This interface is only used by two classes in "spring-cloud-sleuth-autoconfigure" (SkipPatternConfiguration and SkipPatternConfigurationTest) in which the import of the SingleSkipPattern will change.

A workaround for this bug is to make a fat jar with the Maven shade plugin which only contains the above mentioned two modules to prevent the split package. I managed to have a working solution for this workaround, but I'd rather use the dependency on this repo without the fat jar.

**Comment by marcingrzejszczak** [comment]
:grimacing: it's sth we can tackle in 3.1.0 as a necessary breaking change (we'll need to move the class around). Until then you have to do the workaround as you mentioned.

**Comment by hollander-cegeka** [comment]
Thanks, that's great! For the time being we are able to manage it with the workaround solution.
