### ISSUE TITLE
@NewSpan not wok in reactive project

### ISSUE THREAD

**Issue by desertTown** [spring-cloud/spring-cloud-sleuth#1995]
**Describe the bug**
@NewSpan did not create a new Span if I register a bean  SpanHandler in my project

like this in my Configuration
```
    @Bean
    SpanHandler handleWebClientCustomizeTag() {
        return new SpanHandler() {
            @Override
            public boolean end(TraceContext traceContext, MutableSpan span, Cause cause) {
                if ("CLIENT".equalsIgnoreCase(span.kind().name())) {
                    span.tag("name", "evan");
                }
                return true; // keep this span
            }
        };
    }
```

can anyone help to fix this issue?  
or this SpanHandler does not allow to exits in the reactive projects? thanks

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.


Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by desertTown** [comment]
> Can you please answer all the required questions described in the issue template? For your convenience let me paste it here
> 
> > **Describe the bug**
> > Please provide details of the problem, including the version of Spring Cloud that you
> > are using.
> > **Sample**
> > If possible, please provide a test case or sample application that reproduces
> > the problem. This makes it much easier for us to diagnose the problem and to verify that
> > we have fixed it.
> 
> Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

sorry， it causes by my project logic, as @NewSpan will not contain Kind value
but from here
    @Bean
    SpanHandler handleWebClientCustomizeTag() {
        return new SpanHandler() {
            @Override
            public boolean end(TraceContext traceContext, MutableSpan span, Cause cause) {
                if ("CLIENT".equalsIgnoreCase(v)) {
                    xxx
                }
                return true; // keep this span
            }
        };
    }
    
        @Bean
    SpanHandler handleWebClientCustomizeTag() {
        return new SpanHandler() {
            @Override
            public boolean end(TraceContext traceContext, MutableSpan span, Cause cause) {
                if ("CLIENT".equalsIgnoreCase(span.kind().name())) {
                    span.tag("name", "evan");
                }
                span.tag("name", "gg");
                return true; // keep this span
            }
        };
    }
    span.kind().name() will got Nullpointer Exception, and make new span fail
    will close this issue. thx
