### ISSUE TITLE
/traces actuator endpoint should return valid JSON response when Accept = */* is passed in request header

### ISSUE THREAD

**Issue by beatfreaker** [spring-cloud/spring-cloud-sleuth#1996]
**Is your feature request related to a problem? Please describe.**
when calling `/traces` actuator endpoint without passing `Accept` in `Request Header`
`The format [application/x-protobuf ] is not supported` is returned in response

I think it would be good by default [CONTENT_TYPE_OPENZIPKIN_JSON_V2](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/actuate/TextOutputFormat.java#L34) should be used and a valid `JSON` response is returned

**Describe the solution you'd like**
This is happening because as per  [Producible.java](https://github.com/spring-projects/spring-boot/blob/8540bc0d121e1af98fb1d42749fe53f51e548df5/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/Producible.java#L32-L42) documentation in `spring-boot-actuator` the enum values are matched using `Enum#ordinal()` in highest to the lowest fashion.

and as ordinal value of [CONTENT_TYPE_OTLP_PROTOBUF](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/actuate/TextOutputFormat.java#L39) is highest it is matched first.

I tested in local if we change the order of `enum` declaration in `TextOutputFormat` and call endpoint withought passing `Accept` by default `CONTENT_TYPE_OPENZIPKIN_JSON_V2` will be picked and result will be returned as `JSON`

If this is a valid enhancement, I can submit a PR for the required changes.

**Comment by marcingrzejszczak** [comment]
Definitely, great catch. Be my guest!

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-sleuth/commit/f0af136af821deca1dbf960185b6a0cce1a9912e
