### ISSUE TITLE
Sleuth tracing context does not propagate to Spring Data Redis Reactive

### ISSUE THREAD

**Issue by festinalente91** [spring-cloud/spring-cloud-sleuth#2000]
**Describe the bug**

I'm trying to trace the Redis operation but the first operation has no parent span context.

For example

```
@RestController
@RequestMapping
class PingPongController (
    private val reactiveStringRedisTemplate: ReactiveStringRedisTemplate
) {
    @GetMapping("/ping")
    suspend fun ping(): String? {
        reactiveStringRedisTemplate.opsForValue().setAndAwait("ping", "pong")
        reactiveStringRedisTemplate.opsForValue().getAndAwait("ping")
        return reactiveStringRedisTemplate.opsForValue().getAndAwait("ping")
    }
}
````

In this case, the `set` operation does not have a parent span, while the rest `get` operations do.

![image](https://user-images.githubusercontent.com/8946248/127124579-071069fe-d113-463c-8744-4446415b0c45.png)

**Sample**

I made [a simple SpringBoot application ](https://github.com/festinalente91/sleuth-lettuce-propagation-test)to reproduce this issue.

**Environment**

- Spring Cloud Version: 2020.0.3
- Spring Boot Version: 2.5.3
- Java 1.8.0_201, Kotlin

**Comment by marcingrzejszczak** [comment]
Try with the latest 3.1.0 snapshot and 2021.0.0 snapshot release train

**Comment by festinalente91** [comment]
@marcingrzejszczak I tried but still doesn't work. 😓
