### ISSUE TITLE
Enable to take Feign.Builder parameter when initialize SleuthFeignBuilder

### ISSUE THREAD

**Issue by LarryJung** [spring-cloud/spring-cloud-sleuth#2003]
**Is your feature request related to a problem? Please describe.**
I am using Feign which is decorated with circuitBreaker, fallbackFactory.(from Resilience4jFeign)

when using a sleuth, it required a `Feign.Builder` type bean with sleuth feature added. 

in TraceFeignClientAutoConfiguration.java
```java
@Bean
@ConditionalOnMissingBean
@Scope("prototype")
Feign.Builder feignBuilder(BeanFactory beanFactory) {
    return SleuthFeignBuilder.builder(beanFactory);
}
```

in SleuthFeignBuilder.java
```java
public static Feign.Builder builder(BeanFactory beanFactory) {
    return Feign.builder().retryer(Retryer.NEVER_RETRY).client(client(beanFactory));
}
```
in the SleuthFeignBuilder, because it initializes pure builder 'Feign.builder()', 
it seems no way to make with my decorated feign builder.

```kotlin
val decorators: FeignDecorators = FeignDecorators.builder()
            .withCircuitBreaker(moneyCircuitBreaker)
            .withFallbackFactory(
                { MoneyAdapterFallback(it) },
                { it is CallNotPermittedException }
            ).build()
val builder: Feign.Builder = Resilience4jFeign.builder(decorators)
```

**Describe the solution you'd like**
take Feign.Builder parameter when build sleuth feign builder.
```java
public static Feign.Builder builder(BeanFactory beanFactory) {
		return Feign.builder().retryer(Retryer.NEVER_RETRY).client(client(beanFactory));
	}

// i want this
public static Feign.Builder builder(Feign.Builder feignBuilder, BeanFactory beanFactory) {
		return feignBuilder.retryer(Retryer.NEVER_RETRY).client(client(beanFactory));
	}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by marcingrzejszczak** [comment]
We are not planning on adding any new features for Sleuth
