### ISSUE TITLE
Span is not terminated properly in Spring Cloud Gateway

### ISSUE THREAD

**Issue by HashZhang** [spring-cloud/spring-cloud-sleuth#2004]
This issue is also submitted in Spring Cloud Gateway. [https://github.com/spring-cloud/spring-cloud-gateway/issues/2320](https://github.com/spring-cloud/spring-cloud-gateway/issues/2320)

There are two example for this phenomenon.

First is to enable `AdaptCachedBodyGlobalFilter` for a route, then the span will be terminated after the `AdaptCachedBodyGlobalFilter`  in request chain. For example:

```
//other filter...
LogFilter1
AdaptCachedBodyGlobalFilter (cache is enabled for this route)
LogFilter2
```

You would find the log context possess spanId and traceId in LogFilter1 **but does not possess in LogFilter2**.

The other example is while use RetryGatewayFilterFactory. You can enable RetryGatewayFilterFactory trace log and you would find the log context possess spanId and traceId only before the first request sent out, and **there is no spanId or traceId in the log context for the possible subsequent retry**.

Maybe we should subscribe some specific filter in Spring Cloud Gateway to solve it. The only subscribe in `TraceWebFilter` is not enough.

**Comment by marcingrzejszczak** [comment]
Which version of sleuth are you using?

**Comment by HashZhang** [comment]
> Which version of sleuth are you using?

3.0.3

**Comment by marcingrzejszczak** [comment]
Can you please create a sample that replicates this issue?

**Comment by HashZhang** [comment]
> Can you please create a sample that replicates this issue?

please refer to https://github.com/HashZhang/spring-cloud-gateway-sleuth-test

**Comment by marcingrzejszczak** [comment]
Is this still an issue?
