### ISSUE TITLE
log4j2 integration doesn't work, "logging.pattern.level" syntax incorrect in TraceEnvironmentPostProcessor

### ISSUE THREAD

**Issue by farnetto** [spring-cloud/spring-cloud-sleuth#2008]
**Description**

traceId and spanId don't appear in log when using log4j2, e.g.:

`2021-08-12 12:54:14.737  INFO [hello-app,,] 106004 --- [nio-8080-exec-1] c.e.d.FooController                      : hello`

**Reproduce**

1. exclude `org.springframework.boot:spring-boot-starter-logging`
2. include `org.springframework.boot:spring-boot-starter-log4j2`, `org.springframework.cloud:spring-cloud-starter-sleuth` and `io.zipkin.brave:brave-context-log4j2`
3. define bean of type `ScopeDecorator` with `ThreadContextScopeDecorator.get()`

**Cause**

The value for `logging.pattern.level` in `TraceEnvironmentPostProcessor` uses e.g. `%X{traceId:-}` but the syntax for an empty default value isn't supported by log4j2. See [Pattern Layout](https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternLayout)

**Workaround**

Override the property with e.g.:

`logging.pattern.level=%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId},%X{spanId}]`

i.e. no `:-`

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by farnetto** [comment]
I certainly did.

**Comment by farnetto** [comment]
spring-boot-starter-parent 2.5.3 and spring-cloud.version 2020.0.3

**Comment by marcingrzejszczak** [comment]
Since manual work is required to add such support with Brave maybe it's enough to document that the pattern must be changed? WDYT?

**Comment by farnetto** [comment]
Yes, that's a good idea. Is the pattern that way for slf4j? I expected that spring-cloud-sleuth + log4j2 would work "out of the box", but there are a couple steps you have to go through on top of the issue with the pattern. I'm sure more documentation would be appreciated. Thanks.

**Comment by farnetto** [comment]
On the other hand, I think the pattern might only be an issue if you use the default log4j2 configuration in org/springframework/boot/logging/log4j2/log4j2.xml or the property LOG_LEVEL_PATTERN.

**Comment by marcingrzejszczak** [comment]
Are you willing to add such an entry to the docs?

**Comment by farnetto** [comment]
Yes, I'll give it a shot.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by ByeBug** [comment]
Still happened in **Sleuth 3.1.4**，can we detect log4j2 on classpath and adjust the `logging.pattern.level` added by `TraceEnvironmentPostProcessor` ?

**Comment by marcingrzejszczak** [comment]
We're not planning to add any new features to Spring Cloud Sleuth. Sleuth is feature complete.

**Comment by ByeBug** [comment]
Well...But I think it's maybe a issue? Because when users get `INFO [hello-app,,]`, there is no doc to tell them why and how to fix it.
