### ISSUE TITLE
Unable to find 3.1.0-* jar version of spring-cloud-starter-sleuth in spring.io official site but could see the corresponding version documentation being available 

### ISSUE THREAD

**Issue by GayatriKola** [spring-cloud/spring-cloud-sleuth#2009]
I was trying for the spring-sleuth integration with the spring batch and this feature is included from 3.1.0.* version of the spring-cloud-sleuth and happy to hear this  :) 

But I was unable to see this version jar available in spring official page and also in the repo .But at the same time in the official page of spring ,documentation related to this version -3.1.0.* is being present .

Related Links : 

- https://spring.io/projects/spring-cloud-sleuth  --> Should the latest version as 3.0.3
![image](https://user-images.githubusercontent.com/87513890/129363546-94bba108-308b-46fe-8892-c55d8644a5bb.png)

- https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-starter-sleuth/  --> Could see only latest version as 3.0.3 not much higher than this in this page
- But documentation is available for 3.1.0.* version (For eg:- https://docs.spring.io/spring-cloud-sleuth/docs/3.1.0-M1/reference/htmlsingle/spring-cloud-sleuth.html)

Can you please help on this asap . Thanks in advance :)

**Comment by marcingrzejszczak** [comment]
I've updated the page to have 3.1.0-M1. You need to add the milestone repo to use it.

	<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-releases</id>
			<name>Spring Releases</name>
			<url>https://repo.spring.io/release</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>spring-plugin-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>spring-plugin-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/release</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

**Comment by GayatriKola** [comment]
Thanks for the quick response .

I am still not able to see the version in maven Central repo .
 ( https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-starter-sleuth/ )  

Can you please do needful asap on this .

**Comment by marcingrzejszczak** [comment]
It's not in Central. It's in the milestone repo https://repo.spring.io/milestone
