### ISSUE TITLE
Span did not share between Span type "Client" and "Server" while using SpringBoot 2.4.5 and SpringCloud 2020.0.2

### ISSUE THREAD

**Issue by desertTown** [spring-cloud/spring-cloud-sleuth#2028]
**Describe the bug**
SpanId did not share between Span type "Client" and "Server" if you use SpringBoot 2.4.5 and SpringCloud 2020.0.2

![image](https://user-images.githubusercontent.com/17807898/134643144-98376b67-b18d-4186-9db0-67f817bdb93c.png)

**Sample**
[zipKin-sleuth-demo.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/7224219/zipKin-sleuth-demo.zip)

Step to reproduce

1. start local Zipkin (localhost:9411)  
2. unzip file and startup ProducerApplication and ReceiverApplication
3. do a REST call :   GET http://localhost:8081/command/bookings/

**Comment by marcingrzejszczak** [comment]
I think the bug was fixed here https://github.com/spring-cloud/spring-cloud-sleuth/compare/v3.0.2...v3.0.4#diff-04c741cfd783e626261a2b57167e27ee1410710ff2165ab216b5678a3df63b6fR68 so you need to upgrade to 2020.0.4. Or you can introduce your own propagation factory manually but I'd definitely suggest upgrading.

**Comment by desertTown** [comment]
> I think the bug was fixed here [v3.0.2...v3.0.4diff-04c741cfd783e626261a2b57167e27ee1410710ff2165ab216b5678a3df63b6fR68](https://github.com/spring-cloud/spring-cloud-sleuth/compare/v3.0.2...v3.0.4diff-04c741cfd783e626261a2b57167e27ee1410710ff2165ab216b5678a3df63b6fR68) so you need to upgrade to 2020.0.4. Or you can introduce your own propagation factory manually but I'd definitely suggest upgrading.

I see, thanks for your suggestion
