### ISSUE TITLE
spring-cloud-sleuth-instrumentation:3.0.4 is incompatible with reactor-core:3.4.5

### ISSUE THREAD

**Issue by MitchelLabonte** [spring-cloud/spring-cloud-sleuth#2029]
**Describe the bug**
spring-cloud-sleuth-instrumentation:3.0.4 uses `Scannable.Attr.LIFTER` in `ReactorHooksHelper`:
https://github.com/spring-cloud/spring-cloud-sleuth/blob/602749a8d148c281e9f519a1ef362744eeff1f44/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorHooksHelper.java#L171

This doesn't exist in reactor-core:3.4.5 (Spring Boot 2.4.x) and throws an exception when running.

**Sample**
Create a new Maven project with spring-cloud-starter-parent as the parent:
```
<parent>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-parent</artifactId>
    <version>2020.0.4</version>
</parent>
```

**Comment by marcingrzejszczak** [comment]
How is this possible? We're using build 3.0.x that uses boot 2.4.x. We're not setting reactor version explicitly so we're getting a reactor version from boot.

**Comment by MitchelLabonte** [comment]
My bad, I had an additional dependency in the pom.xml that I didn't notice that brought in an older version of reactor-core

**Comment by ifsmsd** [comment]
> How is this possible? We're using build 3.0.x that uses boot 2.4.x. We're not setting reactor version explicitly so we're getting a reactor version from boot.

Sorry if I am missing something but this is the issue I believe.

spring-cloud-sleuth-instrumentation:3.0.4 needs a version post this commit

https://github.com/reactor/reactor-core/commit/ab16d1c7fdd4d7c7aa18531a3f9b7ee06ad27edb#diff-b75ea62daae61a2e6aab3e2c5a565c6a91d6918b84187c6357ea789a432e55d9

**Comment by luizpmonteiro8** [comment]
> > How is this possible? We're using build 3.0.x that uses boot 2.4.x. We're not setting reactor version explicitly so we're getting a reactor version from boot.
> 
> Sorry if I am missing something but this is the issue I believe.
> 
> spring-cloud-sleuth-instrumentation:3.0.4 needs a version post this commit (3.4.6)
> 
> [reactor/reactor-core@ab16d1c#diff-b75ea62daae61a2e6aab3e2c5a565c6a91d6918b84187c6357ea789a432e55d9](https://github.com/reactor/reactor-core/commit/ab16d1c7fdd4d7c7aa18531a3f9b7ee06ad27edb#diff-b75ea62daae61a2e6aab3e2c5a565c6a91d6918b84187c6357ea789a432e55d9)

thank you, 2 days with this problem, i solved it thanks to your help
