### ISSUE TITLE
MDC context not passed when using custom ForkJoinPool

### ISSUE THREAD

**Issue by tejaswibm** [spring-cloud/spring-cloud-sleuth#2031]
**Describe the bug**

I have a spring boot application in which I have created a custom fork join pool as given below -

```
@Bean(ThreadPoolConstants.FORK_JOIN_POOL)
@Lazy
public Executor getCustomForkJoinPool() {
    final ForkJoinPool.ForkJoinWorkerThreadFactory factory = pool -> {
        final ForkJoinWorkerThread worker = ForkJoinPool.defaultForkJoinWorkerThreadFactory.newThread(pool);
        worker.setName(ThreadPoolConstants.FORK_JOIN_POOL + worker.getPoolIndex());
        return worker;
    }; 

    return new LazyTraceExecutor(beanFactory,
            new ForkJoinPool(Runtime.getRuntime().availableProcessors(), factory, null, true));
}

```

The reason for doing this is to increase the thread pool count which I will do by providing min and max pool size (since they were not available in JDK8)

Using this custom pool, am doing a parallelStream() operation on a Map as shown below -

```
ThreadPoolFactory.getInstance(ThreadPoolType.FORK_JOIN_POOL)
        .execute(() -> myMap.values().parallelStream().forEach(handler -> {
            log.debug("HANDLER :: {}", handler);
            handler.handleEvent(event);
        })
);
```

Above parallelStream() operation is done in a service method implementation which has `@Async()` annotation as shown below -

```
@Async(ThreadPoolConstants.EVENT_HANDLER)
@Override
public void handleEvent(@NonNull final String event) {
}
```

Now `@Async(ThreadPoolConstants.EVENT_HANDLER)` is also a custom thread pool created like below -

```
@Bean(ThreadPoolConstants.EVENT_HANDLER)
@Lazy
public Executor getEventHandlerExecutor() {
    ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
    executor.setCorePoolSize(threadPoolConfig.getHandlerCorePoolSize());
    executor.setMaxPoolSize(threadPoolConfig.getHandlerMaxPoolSize());
    executor.setQueueCapacity(threadPoolConfig.getHandlerQueueCapacity());
    executor.setWaitForTasksToCompleteOnShutdown(true);
    executor.setAllowCoreThreadTimeOut(true);
    executor.setAwaitTerminationMillis(threadPoolConfig.getAwaitTerminationMillis());
    executor.setThreadNamePrefix(ThreadPoolConstants.EVENT_HANDLER);
    executor.initialize();

    return new LazyTraceExecutor(beanFactory, executor);
}
```

When using this, and printing logs, the MDC key is getting changed across the `EVENT_HANDLER` and `FORK_JOIN_POOL` thread pools. I was expecting that the MDC key would remain same across pools when using `LazyTraceExecutor`.

**Expected Behaviour -**
MDC keys passed, should not be reset across pools.

**Version -**
```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-dependencies</artifactId>
  <version>2020.0.4</version>
  <type>pom</type>
  <scope>import</scope>
</dependency>

<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-sleuth</artifactId>
</dependency>

```
Using `adoptOpenJDK11` for docker base image and local IDE environment.

**Comment by marcingrzejszczak** [comment]
Do you have a small sample that replicates this problem that we could check out?

**Comment by tejaswibm** [comment]
Unfortunately, I do not have a sample application created. This is observed in my production grade application and the code snippets given above are trimmed down version of it.. 
If insisted, I can create an application to demonstrate it !

**Comment by marcingrzejszczak** [comment]
That would be extremely helpful!

**Comment by tejaswibm** [comment]
[demo.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/7268223/demo.zip)

I have created a demo application to illustrate MDC not being passed to FJ Pool. Hope it suffices. 

I have 2 more questions -
* When Sleuth is NOT used, the `@Async` annotation creates a proxy object, but when Sleuth is used it creates the actual implementation class bean.
* `ThreadPoolTaskExecutor.setWaitForTasksToCompleteOnShutdown(true);` is not honoured when Sleuth is used VS when its not used. Is this behaviour expected ? If so, how do we tear down the executor after finishing all its submitted tasks gracefully ?

**Comment by marcingrzejszczak** [comment]
I have a couple of questions:

* What's the point in putting `@Async` on the `Controller`? If you want the Servlet3 async support just make the controller method return `Callable`.
* What's the idea behind `MyServiceImpl#init` method?

Can you please remove Lombok and simplify this example?

**Comment by tejaswibm** [comment]
> * What's the point in putting `@Async` on the `Controller`? If you want the Servlet3 async support just make the controller method return `Callable`.

-- This API is more of a fire-and-forget type which does not return anything except response code since it performs heavy I/O operation. Hence, @Async would be a better alternative to Callable.

> * What's the idea behind `MyServiceImpl#init` method?

-- This is to identify different `HandlerImpl` based on the custom annotation - `MsgHandlerType`.

Apologies for having a little complex application. But I wanted to bring out all the nuances in it for better analysis(since any of the parts of code might have contributed to this behaviour).

I can simplify it a bit though by nuking a couple of classes and removing lombok style autowiring of dependencies.

Will this help ??

**Comment by marcingrzejszczak** [comment]
> This API is more of a fire-and-forget type which does not return anything except response code since it performs heavy I/O operation. Hence, @async would be a better alternative to Callable.

No it wouldn't. It's the first time ever I hear of anyone put `@Async` on a controller. You can have even a simple `void` controller that delegates work to an `@Async` service. 

> Apologies for having a little complex application. But I wanted to bring out all the nuances in it for better analysis(since any of the parts of code might have contributed to this behaviour).
> I can simplify it a bit though by nuking a couple of classes and removing lombok style autowiring of dependencies.

Yes, please. Let's start with simple cases and then we'll move to nuances.

**Comment by tejaswibm** [comment]
> No it wouldn't. It's the first time ever I hear of anyone put `@Async` on a controller. You can have even a simple `void` controller that delegates work to an `@Async` service.

-- My understanding of `Async` was wrong I suppose. For the `void` return type, I could have just called the async service alone. I had read about this from this [spring blog](https://spring.io/blog/2012/05/07/spring-mvc-3-2-preview-introducing-servlet-3-async-support)

Specifically -
> *In some cases you can return to the client immediately while a background job completes processing. For example sending an email, kicking off a database job, and others represent fire-and-forget scenarios that can be handled with Spring's @Async support or by posting an event to a Spring Integration channel and then returning a confirmation id the client can use to query for the results.*


I have removed parts of the demo app. Hope this helps
[demo.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/7279003/demo.zip)

**Comment by marcingrzejszczak** [comment]
OK I saw the updated example. So the thing is that the fork join pool is properly instrumented. The only problem is that the stream uses the `parallel()` method that converts the stream to a parallel one. I have no knowledge of how we can instrument the underlying executor service within that parallel stream. The closest similar thing you can do is to use CompleteableFutures like presented here https://github.com/spring-cloud-samples/brewery/blob/4ccee91ac7a4b7ac7a5b84002c5f3b25e72ffd2d/brewing/src/main/java/io/spring/cloud/samples/brewery/aggregating/IngredientsAggregator.java#L48-L56 or use executor services to schedule the tasks manually. In general I don't see any value of using parallel streams directly and we weren't planning to support those in the near future.

**Comment by tejaswibm** [comment]
Thanks for looking through the issue and providing a workaround.

> * `ThreadPoolTaskExecutor.setWaitForTasksToCompleteOnShutdown(true);` is not honoured when Sleuth is used VS when its not used. Is this behaviour expected ? If so, how do we tear down the executor after finishing all its submitted tasks gracefully ?

@marcingrzejszczak - Any explanation for this ??

**Comment by marcingrzejszczak** [comment]
> ThreadPoolTaskExecutor.setWaitForTasksToCompleteOnShutdown(true); is not honoured when Sleuth is used VS when its not used. Is this behaviour expected ? If so, how do we tear down the executor after finishing all its submitted tasks gracefully ?

what do you mean it's not supported? We do support it https://github.com/spring-cloud/spring-cloud-sleuth/blob/main/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceThreadPoolTaskExecutor.java#L147
