### ISSUE TITLE
Manually start a trace

### ISSUE THREAD

**Issue by sooty1892** [spring-cloud/spring-cloud-sleuth#2032]
I have a in-house built DB scheduler and I would like to get Sleuth working with it, so when a job starts, trade-ids are logged. Currently the application is working with Sleuth for http requests and logging correctly for those.

Is it possible to manually start a trace? 

I can only find documentation around starting spans and copying traces over to new threads.

**Comment by marcingrzejszczak** [comment]
I don't understand the problem. Are you saying that there already is a trace but you would like to start a new one? If you really need to do it like this you can call Sleuth's `tracer.withSpan(null)` that should clear anything currently there in scope. Then when you start a new span `tracer.nextSpan(...)` you will start a new trace.
