### ISSUE TITLE
Spring cloud sleuth problems with tracing in camunda

### ISSUE THREAD

**Issue by jakubt4** [spring-cloud/spring-cloud-sleuth#2041]
Question

We are trying to trace operations with spring cloud sleuth (version 2.2.2.RELEASE). Here we are using the camunda boot (version 3.4.3) and we are expecting to have the same trace id for one operation in a flow. However, the traceId is changed in each delegate what we tried. These delegates are used in the parallel gateway. So after this ‘operation’, trace id is changed. It’s like camunda is handling concurrency internally, so we can’t fix it in our code.
We tried to use property ‘spring.sleuth.async.enabled’ with both, true and false, then upgrade/downgrade sleuth versions, introduce LazyTraceExecutor also with @Async annotation, use brave.Tracer bean from spring sleuth to push values into the trace context manually - everything without success.

**Comment by marcingrzejszczak** [comment]
I have no idea what `camunda boot` is. I don't know what exactly you're doing and how you're doing it. Please provide some code and more details.
