### ISSUE TITLE
traceid and spanid is not printing in log

### ISSUE THREAD

**Issue by Ajaya1997** [spring-cloud/spring-cloud-sleuth#2047]
Hi Team,

After overriding the default Feign.Builder with Resilience4j we are getting traceid and spanid as empty. Can someone help us to resolve this. Below is the code which we have written. When comment this line of code it's start printing the traceID and spanID.

@Bean
    @Scope("prototype")
    public Feign.Builder feignBuilder() {
        CircuitBreaker circuitBreaker = registry.circuitBreaker(CollectionClient.SERVICE_NAME);
        FeignDecorators decorators = FeignDecorators.builder()
                .withCircuitBreaker(circuitBreaker)
                .withFallback(collectionClientFallbackFactory)
                .build();
        return Resilience4jFeign.builder(decorators).client(client);
    }

**Comment by marcingrzejszczak** [comment]
Please learn how to [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by Ajaya1997** [comment]
Hi @marcingrzejszczak 

We are using the Spring Cloud version Greenwich.SR2.

Description :
Whenever we hit the API suppose(/items) it creates the both trace and span Id. When it calls to downstream services(for example Product) the traceId and spanId becomes empty.
We are overriding the Feign.Builder because of that this issue we are facing.

**Comment by marcingrzejszczak** [comment]
Greenwich is no longer maintained. Please upgrade to the latest release train. Check this page for more information https://spring.io/projects/spring-cloud
