### ISSUE TITLE
Add possibility to add principal name in log message

### ISSUE THREAD

**Issue by alxxyz** [spring-cloud/spring-cloud-sleuth#2058]
It will be very useful to be able to add in config a possibility to add in log message also principal name.

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by alxxyz** [comment]
It is not a bug, it is a feature request.

**Comment by marcingrzejszczak** [comment]
Your description didn't provide any useful information. Are you referring to spring security? Where should be the prinicpal name be added. Are you talking about a span tag? Do you want to add it to mdc? Please provide thorough information about what you want to achieve and why do you think it's not possible to achieve it now

**Comment by alxxyz** [comment]
I want to configure Sleuth to print into logs also principal name from security, besides Application name, TraceId, SpanId, Export, as it is by default.

**Comment by marcingrzejszczak** [comment]
So you can use the existing solutions such as setting a baggage entry of a principal and configure Sleuth to automatically put it to MDC. You can read more about this here https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/project-features.html#features-baggage
