### ISSUE TITLE
Integration with Spring Cloud AWS SQS 

### ISSUE THREAD

**Issue by patrickbray** [spring-cloud/spring-cloud-sleuth#206]
Hi, 

I was just wondering if there is currently any planned integration between Spring Cloud Sleuth and Spring Cloud AWS SQS. 

We have what I think would be a fairly common use case to publish a message onto an SQS queue and would like for the Trace information to propagate across this hop.

We are currently solving this by implementing the following on each queue publisher / consumer but was thinking that this sounds like a great enhancement for the platform. 

```
  ...
	queueMessagingTemplate.convertAndSend(url, payload, createTraceHeaders(spanAccessor.getCurrentSpan()));
	...

    private Map<String, Object> createTraceHeaders(Span span) {
        Map<String, Object> map = Maps.newHashMap();
        map.put(Span.SPAN_ID_NAME, span.getSpanId());
        map.put(Span.TRACE_ID_NAME, span.getTraceId());
        map.put(Span.SPAN_NAME_NAME, span.getName());
        if (span.getParents().size() != 0) {
            map.put(Span.PARENT_ID_NAME, span.getParents().get(0));
        }
        return map;
    }
```

Consumer: 

```
  @SqsListener(value = "${SQS." + Queues.QUEUE_NAME + ".QUEUE.URL}", deletionPolicy = NEVER)
  public void receiveMessage(Request request, 
  				   @Header("Acknowledgment") Acknowledgment acknowledgment,
                         @Header("message_id") String id, 
                         @Header(Span.TRACE_ID_NAME) long traceId, 
                         @Header(Span.SPAN_ID_NAME) long spanId) {

    Span span = Span.builder()
            .spanId(spanId)
            .traceId(traceId)
            .build();

    tracer.joinTrace(span.getName(), span);
    ...
```

I would be happy to help to get a PR raised if this sounds like a worthwhile feature. 

Thanks

**Comment by marcingrzejszczak** [comment]
This seams really interesting but actually if you used Spring Cloud Integration - https://github.com/spring-projects/spring-integration-aws#spring-integrations-extensions-to-aws to integrate with AWS SQS then this should work out of the box: http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_messaging

**Comment by marcingrzejszczak** [comment]
Can we close this @patrickbray ?

**Comment by patrickbray** [comment]
Yes happy to close this we will take a look at spring integration for our SQS interactions. Thanks for the quick feedback

**Comment by patrickbray** [comment]
@marcingrzejszczak taking a closer look at the link you posted I can't see any recent releases of spring-integration-aws in [maven central](http://search.maven.org/#artifactdetails%7Corg.springframework.integration%7Cspring-integration-aws%7C0.5.0.RELEASE%7Cjar). Last one seems to date back to 2014 am I missing something?

**Comment by marcingrzejszczak** [comment]
@patrickbray - you'll have to go the https://github.com/spring-projects/spring-integration-aws and file an issue there. The guys there are awesome and more than willing to answer any of your questions :)

**Comment by jorgetovar** [comment]
How to make the Span builder with spring sleuth and brave?

**Comment by marcingrzejszczak** [comment]
I don't understand your question nor  what it has to do with this issue
