### ISSUE TITLE
OAuth2 Sleuth WebClient on PostConstruct - blocked, stuck, hangs

### ISSUE THREAD

**Issue by kirill1722** [spring-cloud/spring-cloud-sleuth#2062]
**Describe the bug**
I would like to fetch some data with OAuth2 WebClient on PostConstuct but the application just hangs.
When I remove Sleuth from Maven or OAuth2 ".filter" or "spring.sleuth.web.webclient.enabled: false" then everything works fine.

Is this a bug or by design?

**Sample**
`
<version>2.6.0</version>
<spring-cloud.version>2021.0.0-RC1</spring-cloud.version>

spring-boot-starter-oauth2-client
spring-boot-starter-webflux
spring-cloud-starter-sleuth

@Configuration
public class MyWebClientConfig {

    @Bean
    WebClient webClient(ReactiveClientRegistrationRepository clientRegistrations) {
        ServerOAuth2AuthorizedClientExchangeFilterFunction oauth =
                new ServerOAuth2AuthorizedClientExchangeFilterFunction(
                        clientRegistrations,
                        new UnAuthenticatedServerOAuth2AuthorizedClientRepository());
        oauth.setDefaultClientRegistrationId("myclient");
        return WebClient.builder()
                .baseUrl("https://myBaseUrl")
                .filter(oauth)
                .build();
    }

}

@Component
public class Start {

    @Autowired
    private WebClient webClient;

    @PostConstruct
    public void init() {
        System.out.println("start");
        String result = webClient.get()
                .uri(uriBuilder -> uriBuilder
                        .path("/v1/fahrten/{zugnummer}")
                        .queryParam("betriebstag", LocalDate.now())
                        .build(719))
                .retrieve()
                .bodyToMono(String.class)
                .block();
        System.out.println("end");
    }

}

`

**Comment by marcingrzejszczak** [comment]
It seems like a similar problem as we had with lettuce and early bean resolution. Can you try the following and see if it helps?

```java
@configuration
public class MyWebClientConfig {

@Bean
WebClient webClient(ReactiveClientRegistrationRepository clientRegistrations, Sampler sampler) {

   sampler.isSampled(0L); // add this line - it should resolve a proxy around the sampler eagerly

    ServerOAuth2AuthorizedClientExchangeFilterFunction oauth =
            new ServerOAuth2AuthorizedClientExchangeFilterFunction(
                    clientRegistrations,
                    new UnAuthenticatedServerOAuth2AuthorizedClientRepository());
    oauth.setDefaultClientRegistrationId("myclient");
    return WebClient.builder()
            .baseUrl("https://myBaseUrl")
            .filter(oauth)
            .build();
}

}
```

**Comment by kirill1722** [comment]
sampler.isSampled(0L); didnt't fixed it.
It's injecting a NeverSample Sampler

`
package brave.sampler;

public abstract class Sampler {
    public static final Sampler ALWAYS_SAMPLE = new Sampler() {
        public boolean isSampled(long traceId) {
            return true;
        }

        public String toString() {
            return "AlwaysSample";
        }
    };
    public static final Sampler NEVER_SAMPLE = new Sampler() {
        public boolean isSampled(long traceId) {
            return false;
        }

        public String toString() {
            return "NeverSample";
        }
    };
`

**Comment by marcingrzejszczak** [comment]
Can you create a simple sample that replicates this problem?

**Comment by kirill1722** [comment]
https://github.com/kirill1722/webclient-playground

you need to fill a valid OAuth2 tokenUri, clientId, clientSecret to reproduce

**Comment by kirill1722** [comment]
do you need more information?

or do https://github.com/kirill1722/webclient-playground sample works for you?

**Comment by marcingrzejszczak** [comment]
Sorry I can't set it up to work properly. Can you set it up against e.g. Spring Authentication Server that I can run locally?

**Comment by kirill1722** [comment]
@marcingrzejszczak 
I have updated webclient-playground, you should pull from main branch.
https://github.com/kirill1722/webclient-playground 

Here is the local sever
https://github.com/kirill1722/oauth2-server

You can start the oauth2-server and then webclient-playground. You dont need any additional configuration.
