### ISSUE TITLE
TraceId spreading between containers thread pools 

### ISSUE THREAD

**Issue by CyberpunkPerson** [spring-cloud/spring-cloud-sleuth#2064]
Hi Spring Team! 
We found a bug with traceId spreading in `TracingChannelInterceptor ` the issue starts in [here](https://github.com/spring-projects/spring-integration/issues/3649), the essence of the bug [here](https://github.com/spring-projects/spring-integration/issues/3649#issuecomment-977036096).

Best regards,
Andrew

**Comment by maecval** [comment]
@marcingrzejszczak 
Hi Marcin,
Thanks for the fix.
Can you tell us what we can do to get this fix asap?
The bug causes major issues in our productive environment.
Is there a hotfix release available?
Cheers!
Valentin

**Comment by marcingrzejszczak** [comment]
You can either disable that integration via the `spring.sleuth.messaging.enabled=false` property, or wait until 17.02 when we do the release or use tools such as jitpack.io to point to a concrete commit in this repository and use a snapshot version.

**Comment by maecval** [comment]
Thanks for the quick response.
We have already disabled it for transactions (`spring.sleuth.tx.enabled=false`) and need to check what it means if we disable it for messaging.

**Comment by marcingrzejszczak** [comment]
This issue is about `TracingChannelInterceptor` which is a messaging component. If you disable messaging support in Sleuth then you won't have issues with `TracingChannelInterceptor`

**Comment by maecval** [comment]
As far as we understand we will loose the population of traceId / spanId if we do so we so.
BTW: it is certainly closely related to [issues 2082](https://github.com/spring-cloud/spring-cloud-sleuth/issues/2082) which is also one of the issues our apps suffer.

**Comment by marcingrzejszczak** [comment]
Yes, you will lose that functionality

**Comment by gigermocas** [comment]
Hi, can we expect this fix on a 3.0.x release?

**Comment by marcingrzejszczak** [comment]
3.0.x is outside of OSS support. Please check this website for more information https://spring.io/projects/spring-cloud-sleuth#support

**Comment by pankajchugh7** [comment]
as per the doc 3.0.x, end of support date is 2022-05-19. Can you pls check once.
We need this fix in 3.0.x.

can you pls highlight any compatibility breaks between 3.1.x and 3.0.x.
