### ISSUE TITLE
asynchronous thread missing origin traceId throw feign request

### ISSUE THREAD

**Issue by sunset535** [spring-cloud/spring-cloud-sleuth#2070]
my question detail: 
The request first go to gateway, gateway service route the request to serviceA, at the same time gateway create a trace bind to the request,  serviceA doing business and create a message send to mq, mq consumer method throw a asynchronous custom thread consume it. when process entry consumer method, the traceId is correct. but the mq consumer method have a feign request to ServiceB, when i saw the serviceB log, i found serviceB have a new traceId, so the log chain is break.
i found when i use @RabbitListener annotation to consume the mq message, the chain is correct, when i use my custom annotation to consume the mq message, the chain will be break in feign request to serviceB.

entry asynchronous thread (mq consume thread) log:
![clipboard](https://user-images.githubusercontent.com/3860179/144788228-19e26c3f-8dc8-43a2-b546-7c5341d7fd4b.png)

serviceB log:
![image](https://user-images.githubusercontent.com/3860179/144788546-4d523f8d-6048-4629-b2f8-77ddc326fda6.png)

is sleuth design not support custom asynchronous thread?

**Comment by marcingrzejszczak** [comment]
You're using Hystrix. We don't support Hystrix

**Comment by sunset535** [comment]
??

**Comment by sunset535** [comment]
> You're using Hystrix. We don't support Hystrix

sleuth don't support hystrix? so, what's the function of SleuthHystrixAutoConfiguration?

**Comment by marcingrzejszczak** [comment]
We've dropped that support in Sleuth 3.0.0. If you're using an old version of Sleuth please migrate to the latest version. Hystrix is a deprecated project.

**Comment by sunset535** [comment]
> We've dropped that support in Sleuth 3.0.0. If you're using an old version of Sleuth please migrate to the latest version. Hystrix is a deprecated project.

actually, my version is 2.2.5-RELEASE, i want to know why my sleuth not working in this version. my project upgrade to 3.0.0 is a very difficult project.

**Comment by marcingrzejszczak** [comment]
According to the support page here https://spring.io/projects/spring-cloud-sleuth support for that version finished s year ago. I'm closing this issue.
