### ISSUE TITLE
NewSpan throw-catch log spam on protected methods

### ISSUE THREAD

**Issue by fisco-unimatic** [spring-cloud/spring-cloud-sleuth#2072]
At least, I think that's what's happening.
At debug level, we get the log statement, 'Exception occurred while tyring to find the annotation', with the signature of a protected method.
I can fix it by changing [line 82 of SleuthAnnotationUtils](https://github.com/spring-cloud/spring-cloud-sleuth/blob/main/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/annotation/SleuthAnnotationUtils.java#L82) to

    method.getDeclaringClass().getDeclaredMethod(...

instead of

    method.getDeclaringClass().getMethod(...

Also note that the logged message should say 'trying' instead of 'tyring'.
I'll try to submit a pull request when I get some free time.

**Comment by marcingrzejszczak** [comment]
Pull requests are more than welcome!

**Comment by fisco-unimatic** [comment]
I've uploaded a minimal project to illustrate the problem - https://github.com/fisco-unimatic/spring-cloud-sleuth-2072

I now think that it will always find contained spans, but will log a NoSuchMethodException with its stack trace whenever it examines an advised non-public method that is not annotated with both NewSpan and ContinueSpan.

It can be fixed, as I initially said, by calling getDeclaredMethod instead of getMethod, but on close inspection, I think we can just delete  the second attempt to find the annotation. 

I think 

    method.getDeclaringClass().getMethod(method.getName(), method.getParameterTypes())

will always just return `method`, but I may have misunderstood something, so I'd like a second opinion. Obviously, whoever wrote the method expected that it could sometimes return a different result.

I propose that 

	static <T extends Annotation> T findAnnotation(Method method, Class<T> clazz) {
		T annotation = AnnotationUtils.findAnnotation(method, clazz);
		if (annotation == null) {
			try {
				annotation = AnnotationUtils.findAnnotation(
						method.getDeclaringClass().getMethod(method.getName(), method.getParameterTypes()), clazz);
			}
			catch (NoSuchMethodException | SecurityException ex) {
				if (log.isDebugEnabled()) {
					log.debug("Exception occurred while tyring to find the annotation", ex);
				}
			}
		}
		return annotation;
	}

can just be 

	static <T extends Annotation> T findAnnotation(Method method, Class<T> clazz) {
		return  AnnotationUtils.findAnnotation(method, clazz);
	}

**Comment by marcingrzejszczak** [comment]
If you change it like this do the test pass?

**Comment by marcingrzejszczak** [comment]
ping @fisco-unimatic ?
