### ISSUE TITLE
Change default for sql parameter values

### ISSUE THREAD

**Issue by anderius** [spring-cloud/spring-cloud-sleuth#2073]
To improve the security (and possibly the usability) of the default configuration, I suggest changing the default of `spring.sleuth.jdbc.p6spy.tracing.include-parameter-values` from `true` to `false`.

**Comment by marcingrzejszczak** [comment]
cc @jonatan-ivanov @gavlyukovskiy WDYT ?

**Comment by gavlyukovskiy** [comment]
It makes sense to me to disable that by default. Unfortunately there is no way to know if individual values need to be sanitized or not.

**Comment by jonatan-ivanov** [comment]
Agree, disabling by default makes sense.
