### ISSUE TITLE
traceId / spanId generated are changed post WebClient call

### ISSUE THREAD

**Issue by syedyusufh** [spring-cloud/spring-cloud-sleuth#2075]
We are using ReactorNettyHttpTracing with our Spring Web + Spring WebFlux + Spring Cloud Sleuth application. The traceId / spanId generated are getting changed post the WebClient call.

`Spring Boot v2.6.1 and Spring Cloud v3.1.0`

How do we retain the same traceId and spanId for the entire Spring Web request?

```
    @Bean
    public ReactorNettyHttpTracing reactorNettyHttpTracing(HttpTracing httpTracing) {
        return ReactorNettyHttpTracing.create(httpTracing);
    }

    WebClient.builder()
            .clientConnector(new ReactorClientHttpConnector(tracing.decorateHttpClient(httpClient)))
            .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
            .filters(exchangeFilters -> { 
                exchangeFilters.add(exchangeFilter.logRequest());
                exchangeFilters.add(exchangeFilter.logResponse());
            }).build();
```

**Comment by marcingrzejszczak** [comment]
Have you created the WebClient as a bean?

**Comment by syedyusufh** [comment]
Yes, it is created as a bean.

To be more precise with the behavior, since my application is Spring Web + Spring WebFlux, we do have a ControllerAdvices that are called to log the request payload, then the service layer makes the WebClient call and responds back a Mono from the Controller class. On the way back, there is another ControllerAdvice to log the response.

Tried checking the traceId / spanId on the Mono using doOn***** side effects and they match the one initially found as part of the Spring Web ControllerAdvice. The new traceId / spanId is just after the call returns back from WebFlux to Web (ControllerAdvice)

**Comment by marcingrzejszczak** [comment]
Can you create a small sample that replicates this problem?

**Comment by syedyusufh** [comment]
Sure thing, please allow a day or two to get back without the actual application (functional) code.

Thanks

**Comment by syedyusufh** [comment]
Please try the below, you should be able to see the traceId / spanId changed post the WebClient call

https://github.com/syedyusufh/sleuth-web-webflux.git

**Comment by syedyusufh** [comment]
Hi @marcingrzejszczak 

Kindly check and help

Thanks

**Comment by marcingrzejszczak** [comment]
Once I check I'll update this issue

**Comment by MohithMarisetti** [comment]
I'm having an almost similar issue with Spring cloud sleuth 3.x.x. I recently upgraded to Spring boot 2.6.6 and Sleuth 3.x.x. After the upgrade I see my **HandlerInterceptor** class is giving a different traceId in the **afterCompletion()** method. More info available [here](https://stackoverflow.com/questions/72107520/spring-interceptor-has-different-traceid-for-aftercompletion-method-with-spring) 

@marcingrzejszczak @syedyusufh Any solution for this problem?

**Comment by Prithvi1994** [comment]
@marcingrzejszczak @syedyusufh We are facing the same issue when trying to upgrade spring boot to 2.6.6. 

Any solution for this?

**Comment by syedyusufh** [comment]
@marcingrzejszczak  can you please help check this issue? We still don't have a solution. As a temporary workaround, we are preserving the traceId through a request scoped bean in Spring Web.

**Comment by MohithMarisetti** [comment]
@syedyusufh Can you please let me know your contact so that I can reach out to you to discuss this issue and your solution

**Comment by marcingrzejszczak** [comment]
I haven't had the time to look into this yet

**Comment by MohithMarisetti** [comment]
@marcingrzejszczak Can you please check on this issue. Also, just to confirm even if we are using spring-webflux (reactive stack) sleuth is going to generate the traceId and log the same traceId for all log-statements for a particular request right? Want to check if thread switching will change the traceIds in sleuth 3.x.x or not

**Comment by marcingrzejszczak** [comment]
I will check it out once it is possible. Yes, the trace should be propagated when thread switching takes place. The only problem is that the current instrumentation is not perfect because there are always edge cases of reactor instrumentation that we can't cover. We will work on better support for this in spring framework 6.

**Comment by MohithMarisetti** [comment]
Okay. With sleuth 2.x.x we never faced any issues but with sleuth 3.x.x the traceIds are getting changed at Interceptor's **afterCompletition()**

**Comment by marcingrzejszczak** [comment]
From what I see  in this sample https://github.com/syedyusufh/sleuth-web-webflux.git it has nothing to do with `WebClient`. It's more with the fact that the `TraceValve` didn't properly support async dispatch. That means calling `TraceValve` twice with an span attribute already set once would not reuse span but create the new one.
