### ISSUE TITLE
Application fails to start with Spring Cloud Stream + Kafka Streams binder on classpath

### ISSUE THREAD

**Issue by TYsewyn** [spring-cloud/spring-cloud-sleuth#2078]
There's a bug in brave which causes a Spring Cloud Stream application not to start when the Kafka Streams binder is being used.
This requires a new release of Brave, and an update of the dependency version in Spring Cloud Sleuth.
Found this while using the 2021.0.0 release, although I expect this to be an issue in older releases too.

See https://github.com/openzipkin/brave/pull/1312 for more info.

**Comment by yannickdeturck** [comment]
Also interested in this!

**Comment by pfconrey** [comment]
This appears to still be an issue. Any idea what the status is?

**Comment by marcingrzejszczak** [comment]
Can you elaborate on this? Do you have any information on what the Sleuth, Boot and Cloud release trains are?

**Comment by pfconrey** [comment]
I apologize. I discovered that it was a compatibility issue between the version of Sleuth I was trying to use (3.1.3) and the version of Spring Boot (2.2.13). I reverted to Sleuth 2.2.8 and it now works.

**Comment by jonatan-ivanov** [comment]
fyi: those versions are not supported anymore.
