### ISSUE TITLE
Application fails to start with Spring Cloud Stream + multiple output bindings for function

### ISSUE THREAD

**Issue by TYsewyn** [spring-cloud/spring-cloud-sleuth#2080]
A Spring Cloud Stream function with multiple output bindings uses following signature:
`Function<Flux<Integer>, Tuple2<Flux<String>, Flux<String>>>`.

When Sleuth is on the classpath & enabled, the `TraceFunctionAroundWrapper` throws a `ClassCastException` because it tries to cast the `Tuple2` result to `Flux`, more specifically on [this line](https://github.com/spring-cloud/spring-cloud-sleuth/blob/938a30af7ea3dfdeeca32f14c85dbb284c60b481/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceFunctionAroundWrapper.java#L203).

Release train: 2021.0.0
Sleuth 3.1.0

**Sample**
See https://github.com/TYsewyn/sleuth-multiple-output-streams-fails

**Comment by marcingrzejszczak** [comment]
Can you check the latest snapshots?

**Comment by TYsewyn** [comment]
Wait, this is a flux to double-flux function. According to [the docs](https://docs.spring.io/spring-cloud-stream/docs/3.2.1/reference/html/spring-cloud-stream.html#_functions_with_multiple_input_and_output_arguments) this should work, which I just verified without Sleuth on the classpath.

@marcingrzejszczak Tried this with the snapshot, no luck though.

**Comment by olegz** [comment]
Tim, you're right. . . ;) All I saw is `Function<Integer...>` where it is actually `Function<Flux<Integer>>...`
My bad, so yes, the above function should work fine, single input, multiple outputs, but I have no idea how it can work with tracing. . . 
@marcingrzejszczak i think right now if you see any kind of Tuple (1, 2, 3, 4) in the signature, just exit as in no tracing

**Comment by TYsewyn** [comment]
Quick & dirty solution: couldn't we create a new Tuple of n and wrap each individual `Flux`? 🤔

**Comment by olegz** [comment]
I am not following. . We use Tuple (2 thru 8) from reactor API specifically to signal how many inputs/outputs function has and only support multiple in/out for reactive API, so what do you mean create new one?

**Comment by TYsewyn** [comment]
The problem is with this line of code in `TraceFunctionAroundWrapper`:
`final Flux<Message> function = ((Flux<Message>) targetFunction.apply(flux));`

So instead of immediately casting the result of `targetFunction.apply(flux))` to `Flux<Message>` we could check the instance type of the result: `Flux`, `Tuple` or `Iterable` (Tuple2..8 are implementing this interface).
In case it is a `Tuple` we could get all `Flux` from the tuple as an array, wrap each of them, and return a new `Tuple` based on the size of the array.

**Comment by marcingrzejszczak** [comment]
I don't get it but feel free to file a PR with your suggestion. Currently I think that having no tracing should be the way to go.

**Comment by marcingrzejszczak** [comment]
ping @TYsewyn
