### ISSUE TITLE
Application fails to start when implementing a ReactiveSessionRepository

### ISSUE THREAD

**Issue by Albertoimpl** [spring-cloud/spring-cloud-sleuth#2081]
**Describe the bug**
After upgrading to  Spring Cloud `2021.0.0` and Spring Boot `2.6.1` when enabling Sleuth in our Spring Cloud Gateway application we see the following exception:

> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastReactiveSessionRepository' defined in class path resource [io/pivotal/spring/cloud/gateway/session/SessionConfiguration$HazelcastReactiveSessionConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class io.pivotal.spring.cloud.gateway.session.HazelcastReactiveSessionRepository: Common causes of this problem include using a final class or a non-visible class; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.IllegalAccessError-->class io.pivotal.spring.cloud.gateway.session.HazelcastReactiveSessionRepository$$EnhancerBySpringCGLIB$$bd40a2dc cannot access its superclass io.pivotal.spring.cloud.gateway.session.HazelcastReactiveSessionRepository (io.pivotal.spring.cloud.gateway.session.HazelcastReactiveSessionRepository$$EnhancerBySpringCGLIB$$bd40a2dc is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @33e5ccce; io.pivotal.spring.cloud.gateway.session.HazelcastReactiveSessionRepository is in unnamed module of loader 'app')
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628) ~[spring-beans-5.3.13.jar:5.3.13]

Tried using the latest SNAPSHOT and the problem is still there:

```
	implementation 'org.springframework.cloud:spring-cloud-starter-sleuth:3.1.1-SNAPSHOT'
```

**Comment by marcingrzejszczak** [comment]
Do you have a small sample that replicates this problem? As a workaround you can disable sleuth TX support

**Comment by Albertoimpl** [comment]
Disabling the TX support worked and everything is running now.
I do not have a small sample but I will try to create one if that helps.  Thanks, @marcingrzejszczak!

**Comment by marcingrzejszczak** [comment]
ping @Albertoimpl

**Comment by Albertoimpl** [comment]
I tried to reproduce it with the same dependencies, similar configuration, in the same environment with a smaller application and I was unable to reproduce it. 

Going to assume it is a problem on our side and will re-open if we can figure it out.
