### ISSUE TITLE
spring-cloud-sleuth-instrumentation sql issue for spans

### ISSUE THREAD

**Issue by mschielmann** [spring-cloud/spring-cloud-sleuth#2083]
**Describe the bug**
Version: 3.1.0
The `TraceListenerStrategy` in `spring-cloud-sleuth-instrumentation` throws a `StringOutOfBoundsException` when the SQL consists of only one word, like: `BEGIN`. Such word, afaik, constitutes a valid SQL statement, and as such should be handled without throwing an exception.

The exception is thrown here:
https://github.com/spring-cloud/spring-cloud-sleuth/blob/main/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceListenerStrategy.java#L432
(in `spanName` method), as `indexOf(' ')` is -1.

I'd suggest handling this with returning the whole SQL as span name in such case. Another option would be to ignore such SQL.

**Sample**
N/A

**Comment by mschielmann** [comment]
@marcingrzejszczak answering your question, yes, that would be the case. I don't think any validation is possible though as to if that word can create a valid SQL statement by itself (for example 'BEGINN').

If you agree that this can be fixed by using the whole word - then I could create a MR for that.

**Comment by marcingrzejszczak** [comment]
Be my guest!

**Comment by mschielmann** [comment]
@marcingrzejszczak, waiting for your review.
https://github.com/spring-cloud/spring-cloud-sleuth/pull/2086

**Comment by gavlyukovskiy** [comment]
In my starter I didn't try to parse query to give span a name, so all of them were `query`, there are certainly a lot of edge cases when trying to parse user input, couple that comes to mind
- Not terminated by space: `select*from ...`. Can be solved by `query.split("[^a-zA-Z]", 2)[0]`
- Has a comment in the beginning: `/*some comment*/select ...`
- Not an edge case, but in certain queries first (non-comment) word does not identify the query: `with ... [select|insert|...]`

Not sure what would be the best way to handle those, what do you think about checking that first word is `select`/`insert`/`update`/`delete` and using it as a span name, but in all other cases use something generic (like `query`) as a span name.

**Comment by mschielmann** [comment]
@gavlyukovskiy sounds reasonable to me, I'm happy to make that change to PR if you think that would be a best way to go.

**Comment by marcingrzejszczak** [comment]
I like @gavlyukovskiy comment. Let's do it like he suggests.

**Comment by gavlyukovskiy** [comment]
@marcingrzejszczak @mschielmann great, let's do that then.

**Comment by mschielmann** [comment]
@gavlyukovskiy @marcingrzejszczak I've applied changes to my PR. Please let me know if you think that any changes are required.
Thank you for your input.

**Comment by mschielmann** [comment]
@gavlyukovskiy @marcingrzejszczak, 
my PR has been merged before I could apply changes based on your comments @gavlyukovskiy (busy time, holidays, sorry).

I've created another PR with some improvements 'based' on your comments. Please see if that works for you or let me know if you think something more could be added / changed. 

Thanks,
MS

**Comment by marcingrzejszczak** [comment]
Oh sorry, my bad. Thanks for the pr!

**Comment by mschielmann** [comment]
Come to think about it, we're now changing the behaviour a bit - if someone depended on spanName like 'alter' or 'create' then we'd break things for them. So I'd either go back to returning the first word whatever it may be (by slightly modifying the regexp I've used in the PR) or by extending the 'known span names' by alter/create/drop and any other that may come to our minds.

**Comment by gavlyukovskiy** [comment]
@marcingrzejszczak I think both ways are fine. In some cases first word will be useless, but the same can be said for `query`. Current regex completely fixes the bug, so let's not introduce any naming changes.

**Comment by mschielmann** [comment]
Ok, so let me then remove the "KNOWN_SPAN_NAMES" part and just leave the first word.

I'll add test cases for my use case that started the whole thing - BEGIN.

**Comment by mschielmann** [comment]
Changes done @marcingrzejszczak  @gavlyukovskiy

**Comment by mschielmann** [comment]
All steps passed now @marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
Thanks for your hard work @mschielmann ! Fixed via https://github.com/spring-cloud/spring-cloud-sleuth/commit/421c5e6476b57d52f6e1b2fa8d156143ca89f0d8

**Comment by mschielmann** [comment]
np @marcingrzejszczak, thank you for your support. BTW, is there any due date for 3.1.1 to be released? any estimation?

**Comment by marcingrzejszczak** [comment]
You can check the tentative release dates here https://github.com/spring-cloud/spring-cloud-release/milestones
