### ISSUE TITLE
BaggagePropagation do not work when using CUSTOM propagation type?

### ISSUE THREAD

**Issue by Melnicov** [spring-cloud/spring-cloud-sleuth#2088]
**Describe the bug**
Hi guys,

I faced such problem:

*Spring-Boot - 2.5.4
*Sleuth - 3.0.4

I am using CUSTOM propagation type, in application.properties defined it:
`spring.sleuth.propagation.type=CUSTOM`

Also I want to propagate X-Amzn-Trace-Id as well:
```
spring.sleuth.baggage.remote-fields=X-Amzn-Trace-Id
spring.sleuth.baggage.correlation-fields=X-Amzn-Trace-Id
```

And I want to set some value as traceId and spanId from this header, as well as propagate it as a baggage field:

```
@Component
public class SleuthCustomPropagator extends Propagation.Factory implements Propagation<String> {
  @Override
  public List<String> keys() {
    return List.of("X-Amzn-Trace-Id");
  }

  @Override
  public <R> Injector<R> injector(Setter<R, String> setter) {
    return (traceContext, request) -> {
      setter.put(request, "X-Amzn-Trace-Id", traceContext.traceIdString());
    };
  }

  @Override
  public <R> Extractor<R> extractor(Getter<R, String> getter) {

    return request ->
      TraceContextOrSamplingFlags.create(TraceContext.newBuilder()
        .traceId(HexCodec.lowerHexToUnsignedLong(getTraceIdHeader(getter, request)))
        .spanId(HexCodec.lowerHexToUnsignedLong(getTraceIdHeader(getter, request)))
        .build());
  }

  private <R> String getTraceIdHeader(Getter<R, String> getter, R request) {
    return getter.get(request, "X-Amzn-Trace-Id")
      //doing some manipulations to get just part of it
  }

  @Override
  public <K> Propagation<K> create(KeyFactory<K> keyFactory) {
    return StringPropagationAdapter.create(this, keyFactory);
  }
}
```

Also I have such logging pattern:
`logging.pattern.level=%5p {"app":"${spring.application.name:-}","traceId":"%X{traceId:-}","spanId":"%X{spanId:-}","X-Amzn-Trace-Id":"%X{X-Amzn-Trace-Id}"}`

And as I see `X-Amzn-Trace-Id` is always empty in the log as well as not presented as baggage/ header in the downstream service.

I spent some time debugging and figured out that `BaggagePropagationFactory` sets as default in case I do not define my own factory and then `BaggagePropagation` bean doing staff. But when I define my own Factory - BaggagePropagation just skipped.

So is it possible to define CUSTOM type of propagation and use baggage fields as well?

Best Regards.

**Comment by marcingrzejszczak** [comment]
No it's not. Typically in this case you leave the default b3 option and add a propagation field.
