### ISSUE TITLE
With Consul Config, schedule KV watcher is creating spans

### ISSUE THREAD

**Issue by dnathanson** [spring-cloud/spring-cloud-sleuth#209]
Spring Cloud Consul's config component schedules a watcher that checks is KV store in Consul has been updated.  Sleuth is automatically creating spans anything @Scheduled so in Zipkin there are lots of spans for Local Component: scheduled, Class: ConfigWatch, Method: watchConfigKeyValues.

There should be way to exclude scheduled classes from tracing via configuration.

**Comment by spencergibb** [comment]
Yeah, I thought we did that, but I can't find it on my phone. Maybe it was just a good intention that I can't find.

**Comment by marcingrzejszczak** [comment]
Warning :P The name of the skip pattern for `TraceFilter` has changed to `spring.sleuth.web.skipPattern`

**Comment by dnathanson** [comment]
Thanks for the heads up on the web skip pattern.
