### ISSUE TITLE
duplicate client span and missing remote servicename when use feign-httpclient 

### ISSUE THREAD

**Issue by yingziisme** [spring-cloud/spring-cloud-sleuth#2092]
use apache httpclient replace URLConnection

test three vision

Spring boot:2.3.9.RELEASE
Spring cloud: Hoxton.SR9

Spring boot: 2.1.15.RELEASE
Spring cloud: Greenwich.SR2

Spring boot: 2.0.9.RELEASE
Spring cloud: Finchley.SR2

`<dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-httpclient</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
        </dependency>`
`feign:
  httpclient:
    enabled: true`

use postman sent request to spring-consumer-demo , and spring-consumer-demo send request to spring-provider-demo by feignclient

there is two clien spans and both remoteEndpoint hasn't serviceName

 spans by spring-consumer-demo
`[{"traceId":"b796ef9370f8a90c","parentId":"1ce95adb53b073a3","id":"12613a5e1248dbad","kind":"CLIENT","name":"get","timestamp":1640838664371638,"duration":55154,"localEndpoint":{"serviceName":"spring-consumer-demo","ipv4":"192.168.255.10"},"remoteEndpoint":{"ipv4":"10.68.105.112","port":10002},"tags":{"http.method":"GET","http.path":"/echo/a"}},{"traceId":"b796ef9370f8a90c","parentId":"b796ef9370f8a90c","id":"1ce95adb53b073a3","kind":"CLIENT","name":"get","timestamp":1640838664368642,"duration":62108,"localEndpoint":{"serviceName":"spring-consumer-demo","ipv4":"192.168.255.10"},"tags":{"http.method":"GET","http.path":"/echo/a"}},{"traceId":"b796ef9370f8a90c","id":"b796ef9370f8a90c","kind":"SERVER","name":"get /echo-feign/{param}","timestamp":1640838664146966,"duration":292836,"localEndpoint":{"serviceName":"spring-consumer-demo","ipv4":"192.168.255.10"},"remoteEndpoint":{"ipv6":"::1","port":61662},"tags":{"http.method":"GET","http.path":"/echo-feign/a","mvc.controller.class":"DemoController","mvc.controller.method":"echoFeign"}}]`

**Comment by marcingrzejszczak** [comment]
Please upgrade to the latest maintained version e.g. 3.1.x or 3.0.x and try again.
