### ISSUE TITLE
Application fails to start after upgrading to Spring Boot 2.6 

### ISSUE THREAD

**Issue by Svinkel** [spring-cloud/spring-cloud-sleuth#2097]
**Describe the bug**
After upgrading to Spring Cloud `2021.0.0` and Spring Boot `2.6.2` our application fails to start/reach an healthy state without any error messages. Rolling back the Spring Cloud Version to `2020.0.5` fixes the issue, but it can also be fixed by removing the Spring Cloud Sleuth also solves the issue.

We have noticed that the current version of Sleuth defines the Kotlin version to `1.5.20` which does not match with Kotlin the version from Spring Boot 2.6.x (which is `1.6`).

Also for further information our project is using Kotlin, Coroutines and Webflux. Similar projects without Coroutines do not seem to run into this issue which is why we suspected the Kotlin version mismatch.

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/pom.xml#L92
