### ISSUE TITLE
Headers not always propagated to MDC (with sample)

### ISSUE THREAD

**Issue by anderius** [spring-cloud/spring-cloud-sleuth#2098]
I want to read header values, and have them available on MDC. One single request works, but not when a test does many requests after each other.

Complete project that reproduces the error every time (on my computer, Java 17). Most often after only 6-7 iterations:

https://github.com/anderius/spring-sleuth-problem-demo

Excerpt from the sample:

```kotlin
@RestController
@SpringBootApplication
class DemoApplication {

    @Bean
    fun sleuthHttpServerRequestParser() = HttpRequestParser { request, context, _ ->
        request.header("customHeader")
            ?.let { BaggageField.create("customField").updateValue(context, it) }
    }

    @Bean
    fun spanHandler(): SpanHandler = SpanHandler.NOOP

    @GetMapping("/mdc")
    fun getMdc(): Map<String, String> = MDC.getCopyOfContextMap()
}
```

This issue _might_ be related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/2064.

**Comment by marcingrzejszczak** [comment]
Can you please rewrite this to java?

**Comment by anderius** [comment]
Sure, tomorrow. :-) I use the Spring Start project to generate the project. Any preference for Maven/Gradle, or Java version?

**Comment by marcingrzejszczak** [comment]
Maven will be great!

**Comment by anderius** [comment]
@marcingrzejszczak Maven and Java is ready! :-)

Project is same place: https://github.com/anderius/spring-sleuth-problem-demo

The setup in java:

```java
@RestController
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Bean
    HttpRequestParser sleuthHttpServerRequestParser() {
        return (request, context, span) -> {
            String headerValue = request.header("customHeader");
            if (headerValue != null) {
                BaggageField.create("customField").updateValue(context, headerValue);
            }
        };
    }

    @Bean
    SpanHandler spanHandler() {
        return SpanHandler.NOOP;
    }

    @GetMapping("/mdc")
    Map<String, String> getMdc() {
        return MDC.getCopyOfContextMap();
    }
}
```

**Comment by marcingrzejszczak** [comment]
It took me a while but I understand why it's not working. So the default sampling strategy is rate based. You're sending requests to fast and after ~8 request sampling is noop so no baggage is set. The tests pass once you set `spring.sleuth.sampler.probability=1.0`. Then you sample all of them.

**Comment by anderius** [comment]
@marcingrzejszczak Thank you for looking into this!

That means Spring Cloud Sleuth should not be used for any headers other than the ones used for sampling/tracing, unless we sample everything.

**Comment by marcingrzejszczak** [comment]
That's how Brave works, I'd need to double check if OTel works in the same way.

**Comment by anderius** [comment]
It would be nice to be able to instrument/populate every request onto MDC, and still only send samples.

I will also have to check if this sampling affects propagated headers, as I was expecting that to happen every time as well.

**Comment by marcingrzejszczak** [comment]
Can you change your code and check if this helps. You can leave the sampling condition as it is but instead of

```java
 @Bean
    SpanHandler spanHandler() {
        return SpanHandler.NOOP;
    }
```

just create a new instance of a `SpanHandler` that does nothing (but don't call the `NOOP` reference).

**Comment by anderius** [comment]
Same result, I am afraid.

**Comment by marcingrzejszczak** [comment]
Meh. So it has to be sampled
