### ISSUE TITLE
There are trace reuse problems in Kafka consumption

### ISSUE THREAD

**Issue by FlyBookk** [spring-cloud/spring-cloud-sleuth#2103]
**Describe the bug**
When kafka consumption is performed, if there is no Trace information in the upstream, the consumer automatically creates a Trace. The Trace will not end after the call is completed, but will be reused along with the thread

![image](https://user-images.githubusercontent.com/31526393/151141260-43a294d2-12b5-49f5-ad2e-aa152ccd3cce.png)

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by FlyBookk** [comment]
use spring-boot version is 2.6.3 , sleuth  version is 3.1.0  ,kafka version is 2.8.2
#########provider (There is no trace for this project)############  
    @GetMapping("/test")
    public void test() {
        /*
        * No Trace is set in this Kafka message
        * */
        kafkaTemplate.send("test_sleuth_topic", "test......");
    }


##########consumer (this project has trace ) ###########
    @KafkaListener(topics = "test_sleuth_topic")
    public void listenDelete11(ConsumerRecord<?, ?> consumer, Acknowledgment ack) {
        try {
            log.info("consumer satrt .......");
        } finally {
            log.info("consumer end .....");
            ack.acknowledge();
        }
    }

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.
