### ISSUE TITLE
SpringBoot 3.0.0-M1 + SpringCloud 2022.0.0-M1 [ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-sleuth:jar is missing. 

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-sleuth#2110]
Hello Spring Cloud Sleuth Team,

Wanted to say thank you for this very cool project.
With the exciting releases of both SpringBoot 3.0.0-M1 and SpringCloud 2022.0.0-M1, I went ahead to bump the versions up.
https://spring.io/blog/2022/01/20/spring-boot-3-0-0-m1-is-now-available
https://spring.io/blog/2022/01/27/spring-cloud-2022-0-0-m1-codename-kilburn-has-been-released

While things worked perfectly fine on my SpringBoot 2.6.3 + Jubilee, the exact same code, with just the version change on the pom file to the new pair SpringBoot 3.0.0-M1 + SpringCloud 2022.0.0-M1, the following error is observed.

```
/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java -Dmaven.multiModuleProjectDirectory=abc -Dmaven.home=maven3 [...] -Didea.version=2021.3.1 clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-sleuth:jar is missing. @ line xx, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-sleuth-zipkin:jar is missing. @ line xx, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-contract-verifier:jar is missing. @ line xx, column 21
 @ 
```

I would like to report this issue, as I do would like to keep using Spring Cloud Sleuth, as it is a very important piece of the architecture.

Thank you

**Comment by marcingrzejszczak** [comment]
Sleuth is not part of the `2022.0` release train. You can check this README for more information https://github.com/spring-cloud/spring-cloud-sleuth/tree/main#spring-cloud-sleuth
