### ISSUE TITLE
Allow changing the format of the traceIDs so they are compatible with AWS X-Ray

### ISSUE THREAD

**Issue by trajano** [spring-cloud/spring-cloud-sleuth#2113]
**Is your feature request related to a problem? Please describe.**

At present when I copy and paste the trace IDs from the logs I have to add `1-` and `-` after the 8th character so I can use it in X-Ray.  

**Describe the solution you'd like**

Have a switch like `spring.cloud.sleuth.xray-trace-ids`  to change the default trace ID format being used in the logger to use the AWS X-Ray format

**Describe alternatives you've considered**

Manually doing it, or writing a small web app that takes the trace ID and reformats it

**Additional context**

**Comment by marcingrzejszczak** [comment]
If you're using brave which i assume you do after having read your comment here https://github.com/openzipkin/zipkin-aws/issues/58 you should add zipkin aws propagation to your classpath and read this section of the docs https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/howto.html#how-to-change-context-propagation

**Comment by trajano** [comment]
So I would do that in the `spring-cloud-gateway` config somewhere or do I need to do that everywhere I use Sleuth?

**Comment by marcingrzejszczak** [comment]
Add 

```
<groupId>io.zipkin.aws</groupId>
<artifactId>brave-propagation-aws</artifactId>
```

to your classpath and set the propagation mechanism to AWS

**Comment by trajano** [comment]
It does not appear to be part of the BOM https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-sleuth-dependencies/3.1.0 but I think I can figure it out.

**Comment by trajano** [comment]
Also where's the code for the documentation @marcingrzejszczak  I can try to create a PR to show what is needed for AWS X-Ray

**Comment by trajano** [comment]
But the dependency is required if you set type: AWS as per the docs right?

**Comment by trajano** [comment]
I may be doing it wrong, but I don't see the traceIDs changing in the logs, they still look like `620c3c56673e25dc42d8b04d6f1e426a`

**Comment by marcingrzejszczak** [comment]
You would have to debug https://github.com/openzipkin/zipkin-aws/blob/master/brave/propagation-aws/src/main/java/brave/propagation/aws/AWSPropagation.java and https://github.com/spring-cloud/spring-cloud-sleuth/blob/c795675cf93c666c3c13f9bbb9eadbde1f1aa775/spring-cloud-sleuth-brave/src/main/java/org/springframework/cloud/sleuth/brave/bridge/CompositePropagationFactorySupplier.java#L77 to see if Sleuth properly reads AWS propagation and whether that AWS propagation is working as you would expect it

**Comment by trajano** [comment]
Are you assuming the AWS trace ID is already available?  Because it's not available as of yet since the entry point is Traefik or Spring Cloud Gateway

**Comment by marcingrzejszczak** [comment]
I'm not assuming that, if you set the propagation type to AWS it should generate the AWS in your stead.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by trajano** [comment]
not working on this at the moment will reopen if I have new feedback
