### ISSUE TITLE
Reactor baggage propagation not work on some cases

### ISSUE THREAD

**Issue by deblockt** [spring-cloud/spring-cloud-sleuth#2115]
**Describe the bug**

On some case baggage (MDC on logs) are not propagated on threads using reactor. 

- spring-boot: 2.6.3
- r2dbc: 0.8.8.RELEASE
- spring-cloud: 2021.0.0
- spring-cloud-starter-sleuth: 3.1.0

I see that when on my controller I have an `@Transactional` annotation baggage propagation not work. I have the same issue using a reactive kafka event listener propagation propagation does not work at all.

**Sample**

You can use this project https://github.com/deblockt/spring-sleuth-log-bagage-propagation-issue to reproduce the issue. 
The controller can be found here https://github.com/deblockt/spring-sleuth-log-bagage-propagation-issue/blob/main/src/main/java/com/example/demo/DemoController.java the path `/non-transactional` work fine, and on `/transactional` path the baggage are not propagated.

**Comment by deblockt** [comment]
It seem that disabling `spring.sleuth.tx` fix a part of the issue.

**Comment by marcingrzejszczak** [comment]
Is this still a problem with Sleuth 3.1.0 and cloud 2021.0.1 ?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
