### ISSUE TITLE
Add trace context propagation for redis streams

### ISSUE THREAD

**Issue by lrozek** [spring-cloud/spring-cloud-sleuth#2117]
**Describe the solution you'd like**
There is a missing instrumentation for `redis streams` that would inject `tracing headers` into stream entry on producer side and on consumer side that would extract these headers or start a new trace context when missing

I created a sample project with two applications: one for a producer and one for a consumer which use `redis streams` for communication. I also outlined how a propagation could be achieved. Please refer to https://github.com/lrozek/redis-stream-trace-context-propagation

**Comment by marcingrzejszczak** [comment]
Spring Cloud Sleuth is feature complete, we will not be adding any new features. You can check this doc form more info https://github.com/spring-cloud/spring-cloud-sleuth/tree/main#spring-cloud-sleuth. You can file an issue to [lettuce](https://github.com/lettuce-io/lettuce-core/) I guess.

**Comment by lrozek** [comment]
@marcingrzejszczak I read https://github.com/spring-cloud/spring-cloud-sleuth/tree/main and I am not sure if I get it right. Is `Spring Cloud Sleuth` to be completely replaced by https://micrometer.io/ and there will be no further development, bug fixes etc of Sleuth? Is Sleuth reaching its end of life ?

I also disagree that `Spring Cloud Sleuth` is feature complete, otherwise I would not issue this request.

Should my project start transition from `Spring Cloud Sleuth` to `micrometer` than? I assume that ingress and egress instrumentation for `redis streams` is not present in micrometer yet, don't I ?

**Comment by marcingrzejszczak** [comment]
> @marcingrzejszczak I read https://github.com/spring-cloud/spring-cloud-sleuth/tree/main and I am not sure if I get it right. Is Spring Cloud Sleuth to be completely replaced by https://micrometer.io/ and there will be no further development, bug fixes etc of Sleuth? Is Sleuth reaching its end of life ?

Sleuth 3.1.x is the last version that we support for Sleuth. We will apply bug fixes to that version.

> I also disagree that Spring Cloud Sleuth is feature complete, otherwise I would not issue this request.

I understand, however from our perspective it is feature complete. That means we're not planning any features - it doesn't mean that we couldn't add any new features. We're not planning on releasing Sleuth 3.2.x nor 4.0.0

> Should my project start transition from Spring Cloud Sleuth to micrometer than? I assume that ingress and egress instrumentation for redis streams is not present in micrometer yet, is it ?

For the Spring Framework 6.0, Spring Boot 3.0 you will have to transition to Micrometer Tracing (the API is very similar to the Sleuth's one). We will not have instrumentations in Micrometer, the instrumentations will be there in given projects. For example in the Lettuce project that I have already pointed you to.
