### ISSUE TITLE
Baggage value not getting added to log4j 

### ISSUE THREAD

**Issue by JobinLitmus7** [spring-cloud/spring-cloud-sleuth#2120]
Iam using log4j2 and sleuth 3.0.3

Below is the confiugration I have used to add a baggage to sleuth

```
spring.sleuth.baggage.remote-fields=sessionId
spring.sleuth.baggage.correlation-fields=sessionId
```

I set the baggage field value from the controller of a request shown below.
```
BaggageField.getByName("sessionId").updateValue("value");
```

I am able to access the value from other points using  ```BaggageField.getByName("sessionId").getValue()``` and is being propagated to other services but it is not being acessible in the logs.

the log pattern is 
```
 <PatternLayout pattern="%d{HH:mm:ss.SSS} [%tid] [%t] [%X{sessionId},%X{traceId},%X{spanId}] %-5level %logger{36} - %msg%n"/>
```

Every time I try to print it only traceid and spanid is getting printed leaving session id empty as shown below.

```
[,e5bf8cd9dbf910dc,cb689f3c036b4260]
```

What could be the issue here?

**Comment by marcingrzejszczak** [comment]
Please do not cross post (https://stackoverflow.com/questions/71252366/baggage-value-not-getting-printed-in-log4j2-logs). 

Are you trying to retrieve the baggage just after you set it or later on in the flow? Can you show the code on how you're using the baggage?

**Comment by JobinLitmus7** [comment]
@marcingrzejszczak Sure will take down the other post.

**Comment by marcingrzejszczak** [comment]
I'm still waiting for you to show us some code. Could you please do it? Can you show the controller?

**Comment by JobinLitmus7** [comment]
The controller code is shown below.

```
    @PostMapping("/event")
    public ResponseEntity<String> collectAjaxEvents(@RequestBody JsonNode event, @RequestHeader(value=TENANT_ID) String tenantId) {

        String baggageKey = "sessionId";
        String baggageValue = event.get("rsc_identifiers").get("session_id").asText();
        BaggageField.getByName(baggageKey).updateValue(baggageValue);
        log.info("ajax event received");
        service.process(event,tenantId);
        log.info(" event delivered");
        return new ResponseEntity<>(HttpStatus.OK);
    }
```

**Comment by marcingrzejszczak** [comment]
OK Have you configured the baggage to automatically flush the Brave baggage keys?

**Comment by JobinLitmus7** [comment]
No,  how do we configure that?

**Comment by marcingrzejszczak** [comment]
Please read the docs https://docs.spring.io/spring-cloud-sleuth/docs/3.1.1/reference/htmlsingle/spring-cloud-sleuth.html#features-baggage

```java
// configuration
@Bean
BaggageField countryCodeField() {
    return BaggageField.create("country-code");
}

@Bean
ScopeDecorator mdcScopeDecorator() {
    return MDCScopeDecorator.newBuilder()
            .clear()
            .add(SingleCorrelationField.newBuilder(countryCodeField())
                    .flushOnUpdate()
                    .build())
            .build();
}

// service
@Autowired
BaggageField countryCodeField;

countryCodeField.updateValue("new-value");
```

**Comment by JobinLitmus7** [comment]
Works like a charms. Thanks
