### ISSUE TITLE
Sleuth doesn't propagate traceid and spanid with kafka

### ISSUE THREAD

**Issue by vishnu-chalil** [spring-cloud/spring-cloud-sleuth#2121]
I have following dependencies in my spring-boot application
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>
        <dependency>
            <groupId>io.zipkin.contrib.brave</groupId>
            <artifactId>brave-kafka-interceptor</artifactId>
            <version>0.5.5</version>
        </dependency>
```

as per the documentation of brave I added the following property in my kafka producer
```
        producerProperties.setProperty(ProducerConfig.INTERCEPTOR_CLASSES_CONFIG, TracingProducerInterceptor.class.getName());

```

I use log4j2 and the pattern is shown below.

```
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%tid] [%t] [%X{traceId},%X{spanId}] %-5level %logger{36} - %msg%n"/>
```

the sample log from producer is shown below.

```
15:20:00.302 [133] [kafka-producer-network-thread | producer-6] [,] INFO  KafkaProducer - event successfully send to kafka topic
```

You can see that the traceId and spanId is not being printed in the logs. Am I missing something here.

The kafka producer is shown below

```
@Component
@AllArgsConstructor
public class KafkaProducer {

    private static final Logger log = LogManager.getLogger(KafkaProducer.class);

    private final ProducerConfiguration producerConfiguration;

    public Future<RecordMetadata> produceEvents(GenericRecord genericRecord, String topic, String sessionId) {

        Producer<String, GenericRecord> producer = new KafkaProducer<>(producerConfiguration.getProducerProperties());
        ProducerRecord<String, GenericRecord> producerRecord = new ProducerRecord<>(
                topic, sessionId, genericRecord
        );

        Future<RecordMetadata> data = producer.send(producerRecord,
                (RecordMetadata metadata, Exception exception) ->{
                if (exception == null) {
                    log.info("event successfully send to kafka topic at time {}", System.currentTimeMillis());
                } else {
                    log.info(exception.getMessage());
                }
            }
        );

        producer.flush();
        producer.close();
        return data;
    }
}
```

The producer configuration is also shown below
```
@Component
@Getter
@Setter
public class ProducerConfiguration {

    private final Properties producerProperties;

    public ProducerConfiguration(Properties producerProperties){
        this.producerProperties = producerProperties;
    }

    @Bean
    private void setProperties(){
        this.producerProperties.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
        this.producerProperties.setProperty(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer .class.getName());
        this.producerProperties.setProperty(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, AvroSerializer .class.getName());       
        this.producerProperties.put(ProducerConfig.INTERCEPTOR_CLASSES_CONFIG, Collections.singletonList(TracingProducerInterceptor.class));

    }
}
```

**Comment by marcingrzejszczak** [comment]
Which version of Sleuth are you using? You can check our samples for Kafka 

- Kafka Consumer: https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples/tree/main/kafka-consumer
- Kafka Producer: https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples/tree/main/kafka-producer
- Kafka Reactive Consumer: https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples/tree/main/kafka-reactive-consumer
- Kafka Reactive Producer: https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples/tree/main/kafka-reactive-producer

**Comment by vishnu-chalil** [comment]
Im using sleuth 3.0.3

**Comment by vishnu-chalil** [comment]
@marcingrzejszczak Could the issue be because Kafka uses log4j1 and Im trying to use log4j2?

**Comment by marcingrzejszczak** [comment]
Yeah that might be the case

**Comment by vishnu-chalil** [comment]
@marcingrzejszczak I looked at the kafka message headers and spanId and traceId seems to be there, but just not logging it, do you have any idea on how to use log4j2 with kafka?

**Comment by marcingrzejszczak** [comment]
Have you checked the samples that I've shown you? Are you doing things in the same way and still you don't have the tracing info in the logs? 

Look at this https://github.com/openzipkin/brave/tree/master/context/log4j2 , you would have to add the `log4j2` dependency to your classpath and register the beans as in the snippet.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
