### ISSUE TITLE
spring-cloud-sleuth 3.1.1 send trace without content-type

### ISSUE THREAD

**Issue by shijie262** [spring-cloud/spring-cloud-sleuth#2127]
**Describe the bug**
Currently we upgrade spring-cloud-sleuth from 3.0.3 to 3.1.1, and we found that 3.1.1 are using webclientsender to sending trace by default even if we set "spring.sleuth.web.client.enabled" to false, according to the document, seem should use Restemplatesender if we set so.
and webclientsender got an error from server "Cannot parse Content-type: mime: no media type"

**Comment by marcingrzejszczak** [comment]
Argh, that's a bug. You can create such a bean yourself to go with the `resttemplate` one

```java
@Bean(ZipkinAutoConfiguration.SENDER_BEAN_NAME)
		Sender myRestTemplateSender(ZipkinProperties zipkin, ZipkinRestTemplateCustomizer zipkinRestTemplateCustomizer,
				ZipkinRestTemplateProvider zipkinRestTemplateProvider) {
			RestTemplate restTemplate = zipkinRestTemplateProvider.zipkinRestTemplate();
			restTemplate = zipkinRestTemplateCustomizer.customizeTemplate(restTemplate);
			return new RestTemplateSender(restTemplate, zipkin.getBaseUrl(), zipkin.getApiPath(), zipkin.getEncoder());
		}
```
