### ISSUE TITLE
Cannot configure CUSTOM with other propagations

### ISSUE THREAD

**Issue by ghost** [spring-cloud/spring-cloud-sleuth#2128]
**Describe the bug**
When setting `spring.sleuth.propagation.type=W3C,B3,CUSTOM` I would expect to be able to include my own propagation as the last item in the list of propagators.

However, in `CompositePropagationFactorySupplier` we create the `CUSTOM` propagator by using `beanFactory.getBeanProvider(PropagationFactorySupplier.class)`. It is not possible to provide a bean of type `PropagationFactorySupplier` without overriding the behaviour entirely.

```java
	@Bean
	@ConditionalOnMissingBean
	PropagationFactorySupplier compositePropagationFactorySupplier(BeanFactory beanFactory,
			SleuthBaggageProperties baggageProperties, SleuthPropagationProperties properties) {
		return new CompositePropagationFactorySupplier(beanFactory, baggageProperties.getLocalFields(),
				properties.getType());
	}
```

If I provide a `Propagation.Factory` then this completely removes Spring integration as `org.springframework.cloud.sleuth.autoconfig.brave.BraveBaggageConfiguration#sleuthPropagationWithB3Baggage` gets overridden.

**NB**
Using `CUSTOM` without providing a `PropagationFactorySupplier` results in `CompositePropagationFactorySupplier` injecting itself into itself.

**Sample**

https://github.com/borismorris-anaplan/sleuth-bug-recreate

I have added two profiles
- `propagation-factory` registers the `Propagation.Factory` as a bean
- `propagator-supplier` registers a `PropagationFactorySupplier` as a bean

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by ghost** [comment]
@marcingrzejszczak I believe I have done so.

**Comment by marcingrzejszczak** [comment]
I never thought that you can have both custom and other types really. I thought that you can have `B3,W3C` OR `Custom`. What's the use case really?

**Comment by ghost** [comment]
My use case is a graceful transition from custom propagation to standardised - so what I'd like is
 - when I receive standard headers, use those
 - otherwise fall back to custom propagation

Eventually we hope to phase out custom and just use the standard headers - having custom propagation at the end of the list allows a transparent transition.

And I would like to forward all headers downstream whilst we are transitioning for the same reason.

I have currently implemented this as a "decorator" pattern - with the custom propagation wrapping the Sleuth provided one (whichever is configured) and only applying its rules if that doesn't extract. This works, but I was hoping to move to the "idiomatic" solution - which from the docs I took to be adding `CUSTOM` as the last item in the propagation list.

**Comment by marcingrzejszczak** [comment]
> My use case is a graceful transition from custom propagation to standardised - so what I'd like is

I understand. That sounds like a valid use case.

> I have currently implemented this as a "decorator" pattern - with the custom propagation wrapping the Sleuth provided one (whichever is configured) and only applying its rules if that doesn't extract. This works, but I was hoping to move to the "idiomatic" solution - which from the docs I took to be adding CUSTOM as the last item in the propagation list.

That's what I would assume that should be done really

**Comment by marcingrzejszczak** [comment]
Can you present how you've applied the decorator pattern? I'm still on the fence whether just documenting how to achieve this wouldn't be enough (until now nobody else has been complaining about lack of this feature).

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by viacheslav-dobrynin** [comment]
Hello, @marcingrzejszczak!
Also faced the need to add b3 and custom propagations together.
Can you please support the ability to add custom propagation along with the existing in CompositePropagationFactorySupplier?

**Comment by marcingrzejszczak** [comment]
I would say that this is a missing feature and Sleuth is feature complete so currently we're not planning to add any new features.

**Comment by viacheslav-dobrynin** [comment]
Understood thanks!
