### ISSUE TITLE
Spans with Error should have tag error=true

### ISSUE THREAD

**Issue by oburgosm** [spring-cloud/spring-cloud-sleuth#2130]
All spans that have an error are labeled with _error_ tag, but sometimes this tag is the  boolean _true_, that it's correct according to [opentracing semantic conventions](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-and-log-errors), but other times is the error description.

Sleuth and brave in most of their instrumentation provide a string value for tag error. The full rationale of this can be found [here](https://github.com/openzipkin/brave/blob/master/brave/RATIONALE.md#error-handling), but a summary is that **the value of the "error" tag is less important than its existence**

**Comment by marcingrzejszczak** [comment]
I don't think Sleuth should be doing it. 

If you think that Brave should be doing it, you should file an issue in Brave. Sleuth always calls `Span.error` when an exception happens so it's there where it should be "fixed".

When Sleuth calls OTel via Spring Cloud Sleth Otel library then again it's up to the tracer library to do that work IMO.

**Comment by oburgosm** [comment]
Yes. I agree with you. It should be done by Brave. Sorry
