### ISSUE TITLE
trace id is not propagated to access logs properly using reactor

### ISSUE THREAD

**Issue by PH1P5** [spring-cloud/spring-cloud-sleuth#2132]
**Describe the bug**
Creating a Spring WebFlux app with project reactor we recognized, that using Flux publisher the trace id is not logged in the access logs (via mdc).

**Sample**

https://github.com/PH1P5/reactor-sleuth-sample

We provided this sample repository to reproduce the issue. Please see all the necessary information in the README and also, logback-spring.xml and SampleController for further details.

@marcingrzejszczak investigating this bug we saw that you often were involved in similar discussions like:
https://github.com/spring-cloud/spring-cloud-sleuth/issues/1748

We would really appreciate your help, thanks in advance

**Comment by PH1P5** [comment]
Could anyone please respond, we are currently working with a workaround which not fits our needs.

**Comment by marcingrzejszczak** [comment]
Let's start with the workaround. Please add the `io.projectreactor.netty:reactor-netty-http-brave` dependency and then set up the following configuration

```java
@Configuration(proxyBeanMethods = false)
class Config {

	@Bean
	NettyServerCustomizer traceNettyServerCustomizer(ObjectProvider<HttpTracing> tracing) {
		return server -> ReactorNettyHttpTracing.create(tracing.getObject()).decorateHttpServer(server);
	}
}
```

that should work. Since this is actually a new feature and we're not planning to add any new features to Sleuth most likely we'll just document this.
