### ISSUE TITLE
Possibility to set trace id for reactive stream

### ISSUE THREAD

**Issue by nefsir** [spring-cloud/spring-cloud-sleuth#2133]
Hello team,
I have a question whether its possible to set trace id using reactive streams (Webflux/Reactor Core).
We have a scenario when long processes are persisted in Redis database and processed (@Scheduled) in small batches. The thing is we'd like to correlate whole process under single trace id while initialization of process up to the Redis is propagated correctly with single trace id (as expected) but after scheduler pops batches the trace id is generated once again. I thought about extracting trace id and storing it along with batches but can't find a way to change trace id.
I'd be really grateful for some advise.

**Comment by marcingrzejszczak** [comment]
That sounds like a custom requirement. You would have to treat the Redis database as a source of context information. You would need to use a Propagator with Injector and Extractor to properly store the tracing context to redis and read from it.

**Comment by nefsir** [comment]
Thanks for the quick reply @marcingrzejszczak. The thing is I'm quite not sure if I understand the proposed solution. Could you please provide some snippet for this? Actually, I can store the current tracing id 'manually' (add it to Redis entity) but I have no idea how to set the tracing id after an entity is read from Redis.

**Comment by marcingrzejszczak** [comment]
[Here](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceMessageHandler.java#L152) you have an example of how we are regenerating a span from entries in the message headers. You would need to do sth similar but retrieve the entries from a Redis database.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
