### ISSUE TITLE
Zipkin reactive client does not set Content-Type

### ISSUE THREAD

**Issue by pavel-treutner** [spring-cloud/spring-cloud-sleuth#2139]
Class org.springframework.cloud.sleuth.zipkin2.WebClientSender does not set header Content-Type: application/json when posting JSON data. Jaeger collector then responds with 400 Bad Request, breaking the possibility to trace anything. Tested with jaegertracing/jaeger-collector:1.30.0.

**Comment by oguzhanonder91** [comment]
I got the same problem too when using spring cloud gateway. (version 3.1.1 )

**Comment by oguzhanonder91** [comment]
I solved this problem. I added default header when create  ZipkinWebClientBuilderProvider bean.
` @Bean
    ZipkinWebClientBuilderProvider gateWayWebClientBuilderProvider() {
        return () -> WebClient.builder().defaultHeader("Content-Type", MediaType.APPLICATION_JSON);
    }`
