### ISSUE TITLE
Kafka reactive consumer example issue with SpanAndScope class

### ISSUE THREAD

**Issue by daulet-sdn** [spring-cloud/spring-cloud-sleuth#2141]
Kafka reactive consumer example has SpanAndScope class, but in my app cannot resolve SpanAndScope class

my gradle
implementation 'org.springframework.cloud:spring-cloud-starter-sleuth:3.0.3'

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

Most likely you have a mismatch of versions. Please visit start.spring.io and generate a project using Sleuth and copy the setup to your project.
