### ISSUE TITLE
TraceId spreading between containers thread pools #2064

### ISSUE THREAD

**Issue by pankajchugh7** [spring-cloud/spring-cloud-sleuth#2142]
This issue is already fixed in 3.1.X
https://github.com/spring-cloud/spring-cloud-sleuth/issues/2064
Need the same on 3.0.X

as per the doc  https://spring.io/projects/spring-cloud-sleuth#support  3.0.x, end of support date is 2022-05-19. Can you pls check once.

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-sleuth/commit/6da18e9be24ba822fdc2c28d9e15e642ae737e41

**Comment by pankajchugh7** [comment]
Thank you so much for this fix.

Would be great if you could provide us the tentative date of 3.0.6 release.
