### ISSUE TITLE
AsyncFeign support

### ISSUE THREAD

**Issue by mwojtaczka** [spring-cloud/spring-cloud-sleuth#2153]
Hello,

Not sure if it should be labelled as bug or feature request but It looks like Sleuth doesn't support AsyncFeign#asyncBuilder

```
    @Bean
    Http2Client client() {
        return new Http2Client();
    }

    @Bean
    MyApi myApi(Http2Client client) {
        Feign feign = Feign.builder()
                .client(client)
                .build();
        AsyncFeign<Object> asyncFeign = AsyncFeign.asyncBuilder()
                .client(client)
                .build();

        return asyncFeign.newInstance(new Target.HardCodedTarget<>(MyApi.class, "http://localhost:8123"));
    }

    public interface MyApi {
        @RequestLine("GET /test")
        Response get();
    }
```
Above config works when sync feign is used but not when asyncFeign. 
What is currently the best option to instrument async feign client?

Thanks

**Comment by marcingrzejszczak** [comment]
We're not planning on adding any new features to Sleuth at his moment. We will try to tighten the integration of Feign with the new Observation API from Micrometer. You can read more about this here https://micrometer.io/docs/tracing . You can file an issue to Feign then or to Spring Cloud OpenFeign.
