### ISSUE TITLE
How to set a trace id to a string

### ISSUE THREAD

**Issue by sidharthnayyar** [spring-cloud/spring-cloud-sleuth#2159]
Hi,

I'm looking at setting the TraceId from a custom request header but it seems that it only takes a long. Is there a way to set it to custom string? Currently I'm getting the hashcode of the value provided in the header or if not provided then get a random hex and return the long value:

`@Override
    public List<String> keys() {
        return Arrays.asList(CORRELATION_ID, CORRELATION_SPAN_ID);
    }

    @Override
    public <R> TraceContext.Injector<R> injector(Setter<R, String> setter) {
        return (traceContext, request) -> {
            setter.put(request, CORRELATION_ID, traceContext.traceIdString());
            setter.put(request, CORRELATION_SPAN_ID, traceContext.spanIdString());
        };
    }

    @Override
    public <R> TraceContext.Extractor<R> extractor(Getter<R, String> getter) {
        return request -> TraceContextOrSamplingFlags.create(TraceContext.newBuilder()
                .traceId(getRequestValueLong(getter, request, CORRELATION_ID))
                .spanId(getRequestValueLong(getter, request, CORRELATION_SPAN_ID)).build());
    }

    @Override
    public <K> Propagation<K> create(KeyFactory<K> keyFactory) {
        return StringPropagationAdapter.create(this, keyFactory);
    }

    private <R> long getRequestValueLong(Getter<R, String> getter, R request, String key) {
        String value = getter.get(request, key);
        if (Strings.isBlank(value)) {
            return HexCodec.lowerHexToUnsignedLong(randomHexString(32));
        } else {
            return value.hashCode();
        }
    }`

Thanks
Sid

**Comment by marcingrzejszczak** [comment]
Have you seen this https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/howto.html#how-to-change-context-propagation ?

**Comment by sidharthnayyar** [comment]
Hi, yes the code is actually adapted from that page itself. It seems the TraceContext.newBuilder().traceId and spanId only allows long values. Is it not possible to supply string/text for trace and span ids? Or maybe I'm missing something obvious?

Thanks

**Comment by marcingrzejszczak** [comment]
There's no way to provide text.

**Comment by sidharthnayyar** [comment]
Thanks. A similar question - is that the same for Span then? I mean it seems as if I can set a name for a span:

```
Span newSpan = this.tracer.nextSpan().name(spanName);
try (Tracer.SpanInScope ws = this.tracer.withSpanInScope(newSpan.start())) {
    ...
} finally {
    newSpan.finish();
}
```

but it seems it still only displays the span id (hash/hex)... how do I get it to display the span name that I've set?

**Comment by marcingrzejszczak** [comment]
Where do you want to display this? In the logs? You would have to modify what's set in the MDC context. You can read more about this here https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/project-features.html#features-baggage if you want to use Baggage configuration. If you want to set the name then you would have to provide your own mechanism that adds the span name to MDC and then you would have to reference it in the logging format.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
