### ISSUE TITLE
Clean up dependencies before release

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#216]
Dependency hygiene needs a checkpoint before the first release. Problems I encountered today: 1) an app with `spring-cloud-starter-sleuth` and `spring-cloud-sleuth-zipkin` doesn't start (missing class in `zipkin.Endpoint`), 2) an app with just `spring-cloud-sleuth-stream` doesn't start because AspectJ is not available, 3) `zipkin-server` now has some nasty transitives (e.g. slf4j-log4j12 if kafka is used as a transport).

**Comment by adriancole** [comment]
ps zipkin-server's dependency on kafka is optional, and I guess any project
will have this issue as the transitive dep is from kafka itself..

ex the dep in spring-kafka has this, too, as kafka-clients depends on
slf4j-log4j12
https://github.com/spring-projects/spring-kafka/blob/master/build.gradle#L151

Regardless, will have a look.
https://github.com/openzipkin/zipkin-java/issues/99

**Comment by dsyer** [comment]
Thanks for fixing that in zipkin-java (at least partially). Probably zipkin-java should have it's own BOM for dependency management, but we can handle it here until it does if there's an issue with kafka transport. Need a test now.

**Comment by marcingrzejszczak** [comment]
I don't see any issues with this anymore.

**Comment by dsyer** [comment]
Re-opened for 1.0.0. I still see warnings and errors in the IDE about archaius (in core) and `io.zipkin.java:storage-jdbc` (in zipkin projects).

**Comment by marcingrzejszczak** [comment]
Checked against latest snapshots - don't see anything fishy
