### ISSUE TITLE
Caused by: java.lang.NoSuchFieldError: LIFTER

### ISSUE THREAD

**Issue by qianxifu** [spring-cloud/spring-cloud-sleuth#2161]
hi,

my project dependency spring-cloud:2020.0.5 and spring-cloud-starter-sleuth:3.0.5.

i got an error when i run my project.

 Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer' defined in class path resource [org/springframework/boot/autoconfigure/session/RedisSessionConfiguration$SpringBootRedisHttpSessionConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoSuchFieldError: LIFTER

Caused by: java.lang.NoSuchFieldError: LIFTER
at org.springframework.cloud.sleuth.instrument.reactor.ReactorHooksHelper.getLifterName(ReactorHooksHelper.java:170)

**Comment by marcingrzejszczak** [comment]
Please ensure that you're using the latest compatible Cloud, Sleuth and Boot versions. Most likely you have an old version of Boot that takes in an old version of Reactor.

**Comment by qianxifu** [comment]
thanks, i solved the problem

**Comment by oscarmtzg** [comment]
which was the solution?

**Comment by DHbee** [comment]
working for me when add below dependency

`<dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.4.16</version>
        </dependency>`

**Comment by claudsan** [comment]
@DHbee your solution also worked perfectly for me, thanks, saved my day!
