### ISSUE TITLE
WARN message at application startup using Sleuth and Spring Cloud Gateway

### ISSUE THREAD

**Issue by taxone** [spring-cloud/spring-cloud-sleuth#2166]
I noticed a WARN message generated by **SkipPatternConfiguration** at application start-up, if Sleuth and Cloud Gateway are used together. 
I need a HTTPTracing instance to be injected in order to customize the HTTPClient.
[Everything is described in this issue on StackOverflow](https://stackoverflow.com/questions/72292865/how-to-remove-warn-message-using-spring-cloud-sleuth-and-spring-cloud-gateway).

@marcingrzejszczak told me to add a bug issue for investigation.

Thanks in advance.

**Comment by marcingrzejszczak** [comment]
We will lower the error severity from `warn` to `debug`. We're already ignoring the exception so indeed there's no sense in actually printing this gigantic message where the user can't do much about it.
