### ISSUE TITLE
Use JSON for messages in stream

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#217]
For human readability and protection against schema changes, JSON is probably better than Java serialization. Also: never send data over the wire as Java object serialized.

**Comment by dsyer** [comment]
Assigned to RC1 because it will break existing apps if we change after 1.0.

**Comment by spencergibb** [comment]
:+1: should be the same for bus

**Comment by marcingrzejszczak** [comment]
Yeah, makes sense

**Comment by dsyer** [comment]
Bus (I hope) already uses JSON. Lets make sure it does.

**Comment by adriancole** [comment]
Can't tell if this is here or not, but one thing we ran into in zipkin was
that it can be more efficient to encode multiple spans into the same
message.

The cost of a extra [ ] when not sending multiple is pretty low, and at
least one use was able to move mountains of performance being able to
bundle spans.

Plus, this ends up the exact encoding of the HTTP transport. Food for
thought.
