### ISSUE TITLE
TraceableExecutorService#wrap may have memory leak

### ISSUE THREAD

**Issue by liuzzzz** [spring-cloud/spring-cloud-sleuth#2171]
**Describe the bug**
I found that ConcurrentHashMap is used when wrapping TraceableExecutorService, and Key is an instance of ExecutorService. When I need to dynamically create and release ExecutorService instances, the data in CACHE will not be released.
Do it need to clean up the CACHE when the shutdown or shutdownNow method is called?

**Sample**
None

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by liuzzzz** [comment]
spring-cloud-sleuth-instrumention:3.1.1

**Comment by marcingrzejszczak** [comment]
Yeah we could remove the entry from the cache after `shutdown` and `shutdownNow` takes place. Do you want to file a PR to the 3.0.x branch? I will then merge it forward to 3.1.x and main
