### ISSUE TITLE
Spring Cloud Gateway is not sending correct operation id

### ISSUE THREAD

**Issue by macsux** [spring-cloud/spring-cloud-sleuth#2179]
When using Spring Cloud Gateway with Sleuth, operation are named as HTTP method name without path. Expect it to be something like `get /api/search`, instead only getting `get` as operation name. See screenshot.

![image](https://user-images.githubusercontent.com/1102552/173923982-3a1be2b4-f46a-4177-b06a-63233fc703fd.png)

Sample in this repo: https://github.com/asaikali/vere-copia

**Comment by DaspawnW** [comment]
I see exactly the same behavior, it's a bit bad due to the fact that some applications rely on this Operation Name to define the name of a Trace. Jaeger for example does the same.

**Comment by marcingrzejszczak** [comment]
Please upgrade to [Micrometer Tracing](https://docs.micrometer.io/tracing/reference/). Spring Cloud Sleuth is feature complete and out of OSS support.
