### ISSUE TITLE
Auto-configured skip patterns is ignored by default

### ISSUE THREAD

**Issue by abgm** [spring-cloud/spring-cloud-sleuth#2180]
This is enabling it
https://github.com/spring-cloud/spring-cloud-sleuth/blob/3b5746a4202b87ca66dbd37a483746f1a339318d/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/web/SleuthWebProperties.java#L67-L70

But code is looking direct to properties and setting to "true"/disabled by default
https://github.com/spring-cloud/spring-cloud-sleuth/blob/3b5746a4202b87ca66dbd37a483746f1a339318d/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/web/SkipPatternConfiguration.java#L120-L121

**Comment by marcingrzejszczak** [comment]
Do you have a test that proves it? 

From what I see the current logic is ok

- `spring.sleuth.web.ignoreAutoConfiguredSkipPatterns` set to `true` - the configs in `SkipPatternConfiguration` will not be set (`havingValue = "false"` not met)
- `spring.sleuth.web.ignoreAutoConfiguredSkipPatterns` set to `false` - the configs in `SkipPatternConfiguration` will be set (`havingValue = "false"` met) 
- `spring.sleuth.web.ignoreAutoConfiguredSkipPatterns` not set explicitly - the configs in `SkipPatternConfiguration` will be set (`matchIfMissing = true` met) 
-

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
