### ISSUE TITLE
Allow WebFlux code to set the SERVER span name themselves

### ISSUE THREAD

**Issue by bbakerman** [spring-cloud/spring-cloud-sleuth#2181]
**Is your feature request related to a problem? Please describe.**

Today there is no easy way for an application to name its own SERVER spans and NOT have the Brave HttpHandler code overwrite that name.

We had code in the application runtime that worked out a good name for the current SERVER span and we can use `tracing.currentSpanCustomizer().name("my-nice-name")` to set it BUT when the Brave http handlers run it ALWAYS blats the current name with `HTTP method + path`.

**Describe the solution you'd like**
A way to tell WebFlux to preserve names before it "finishes" the SERVER span.

It's not possible to KNOW the best span name at http request time, only as you run the app code and work it out.  You can grab the `currentSpan` and change it however it will be overwritten.

It might be nice if we put hints in the WebFlux context so that it tells the Sleuth how to name the span but even then the Brave code always does its `method+path` naming and then finishes (and hence flushes) the span.

**Describe alternatives you've considered**

I ended up tricking the Brave code like this to make it skip the http name generation

```

/**
 * This allows us to intercept the WebFlux Sleuth output when a request hits the AGG
 */
@Primary
@Component
public class AggSleuthHttpClientHandler implements HttpServerHandler {

    private final BraveHttpServerHandler braveDelegate;

    public AggSleuthHttpClientHandler(HttpTracing httpTracing) {
        braveDelegate = new BraveHttpServerHandler(brave.http.HttpServerHandler.create(httpTracing));
    }

    @Override
    public Span handleReceive(HttpServerRequest request) {
        return braveDelegate.handleReceive(request);
    }

    @Override
    public void handleSend(HttpServerResponse response, Span span) {
        //
        // The default Brave http handler has an annoying side effect in that it ALWAYS sets the name of the
        // span based on the http method.  BUT if we make this null, it never sets the name.
        // We have other code that sets the span name to something better and hence this code returns
        // null for the method and this tricks the brave code into NOT setting a new name.
        //
        // This is fragile, I agree, but trust me when I say this is the only way for us in WebFlux to
        // name the SERVER span.  I have tried MANY ways to do this and this is the simplest.
        //
        HttpServerResponse wickedTricksyHobbit = new HttpServerResponse() {
            @Override
            public String method() {
                return null; // important side effect there
            }

            @Override
            public int statusCode() {
                return response.statusCode();
            }

            @Override
            public Collection<String> headerNames() {
                return response.headerNames();
            }

            @Override
            public Object unwrap() {
                return response.unwrap();
            }
        };
        braveDelegate.handleSend(wickedTricksyHobbit, span);
    }
}
```

**Additional context**

The code thats does the name setting is in `brave.http.HttpResponseParser.Default#parse`

```
    @Override public void parse(HttpResponse response, TraceContext context, SpanCustomizer span) {
      int statusCode = 0;
      if (response != null) {
        statusCode = response.statusCode();
        String nameFromRoute = spanNameFromRoute(response, statusCode);
        if (nameFromRoute != null) span.name(nameFromRoute);
        if (statusCode < 200 || statusCode > 299) { // not success code
          STATUS_CODE.tag(response, context, span);
        }
      }
      error(statusCode, response.error(), span);
    }
```

The trick above works because of `if (nameFromRoute != null) span.name(nameFromRoute);` ends up as null so it never overwrites the span.

**Comment by bbakerman** [comment]
ps.  After more investigation another way would be to write your own `brave.http.HttpResponseParser / org.springframework.cloud.sleuth.http.HttpResponseParser` however there is  a fair bit of logic in there (around error handling and so on - and this is a lot of cop and paste just to achieve the outcome of "keep my name I set thank you"

**Comment by marcingrzejszczak** [comment]
Since we are not planning to add ant new features to Sleuth we will need to go with the presented workarounds.
