### ISSUE TITLE
JDBC Sleuth instrumentation is not taking place

### ISSUE THREAD

**Issue by vspiliop** [spring-cloud/spring-cloud-sleuth#2185]
**Issue**

JDBC Sleuth instrumentation is not taking place

**Root Cause**

`Datasource` bean is created before the `p6SpyDataSourceDecorator` bean creation.

**Analysis**

Looks like when `TraceDataSourceDecoratorBeanPostProcessor.postProcessAfterInitialization()` is called

    Map<String, DataSourceDecorator> decorators = this.applicationContext
    		.getBeansOfType(DataSourceDecorator.class).entrySet().stream()
     .sorted(Entry.comparingByValue(AnnotationAwareOrderComparator.INSTANCE))

always return an empty map of `decorators`, when called on my `HikariDataSource`.

Also, in my case this was because the `HikariDataSource` was created before the `p6SpyDataSourceDecorator` was created. This had as a result the `decorators` to be empty and as a consequence the `HikariDataSource` not to be instrumented.

It seems Spring auto configuration has a bug. 

**Work Around**

My work around is the following and now I have proper instrumentation:

    @Primary
    @Bean
    @DependsOn("p6SpyDataSourceDecorator")
    @ConfigurationProperties(prefix = "spring.datasource.hikari")
    HikariDataSource dataSource(DataSourceProperties properties) {
        HikariDataSource dataSource = createDataSource(properties, HikariDataSource.class);
        if (StringUtils.hasText(properties.getName())) {
            dataSource.setPoolName(properties.getName());
        }
        return dataSource;
    }

**Issues with Work Around**

The downside is that I had to allow circular dependencies.

**Versions**

      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-sleuth</artifactId>
        <version>3.2.1</version>
      </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-zipkin</artifactId>
            <version>3.2.1</version>
        </dependency>

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by gavlyukovskiy** [comment]
> The downside is that I had to allow circular dependencies.

This probably means that you have something in the decoration flow that depends on `DataSource` being created early. Maybe some custom p6spy listeners?

**Comment by vspiliop** [comment]
@gavlyukovskiy I am looking into this. I do not have any custom p6spy listener. This is the circular dependency:

```
The dependencies of some of the beans in the application context form a cycle:

   webMvcMetricsFilter defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/web/servlet/WebMvcMetricsAutoConfiguration.class]
┌─────┐
|  simpleMeterRegistry defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/export/simple/SimpleMetricsExportAutoConfiguration.class]
↑     ↓
|  dataSourcePoolMetadataMeterBinder defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/jdbc/DataSourcePoolMetricsAutoConfiguration$DataSourcePoolMetadataMetricsConfiguration.class]
↑     ↓
|  p6SpyDataSourceDecorator defined in class path resource [org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/P6SpyConfiguration.class]
↑     ↓
|  traceJdbcEventListenerFactory defined in class path resource [org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/P6SpyConfiguration.class]
↑     ↓
|  tracingJdbcEventListener defined in class path resource [org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/P6SpyConfiguration.class]
↑     ↓
|  braveTracer defined in class path resource [org/springframework/cloud/sleuth/autoconfig/brave/BraveBridgeConfiguration.class]
↑     ↓
|  tracer defined in class path resource [org/springframework/cloud/sleuth/autoconfig/brave/BraveAutoConfiguration.class]
↑     ↓
|  tracing defined in class path resource [org/springframework/cloud/sleuth/autoconfig/brave/BraveAutoConfiguration.class]
↑     ↓
|  zipkinSpanHandler defined in class path resource [org/springframework/cloud/sleuth/autoconfig/zipkin2/ZipkinBraveConfiguration.class]
↑     ↓
|  zipkinReporter defined in class path resource [org/springframework/cloud/sleuth/autoconfig/zipkin2/ZipkinAutoConfiguration.class]
↑     ↓
|  sleuthMicrometerReporterMetrics defined in class path resource [org/springframework/cloud/sleuth/autoconfig/zipkin2/ZipkinAutoConfiguration$TraceMetricsMicrometerConfiguration$NoReporterMetricsBeanConfiguration.class]
└─────┘
```

Many thx for the help!

**Comment by marcingrzejszczak** [comment]
I'll break the cycle in Sleuth. In the meantime you can remove the cycle by creating such a bean (you will not have Zipkin metrics but you'll get rid of the cycle)

```java
@Bean ReporterMetrics mySleuthReporterMetrics() {
		return new InMemoryReporterMetrics();
	}
```

**Comment by marcingrzejszczak** [comment]
Can you check the latest `3.1.4-SNAPSHOT` of Sleuth (or `2021.0.4-SNAPSHOT` release train) to see if you still have the cycle?

**Comment by vspiliop** [comment]
Tried the workaround with 

```
@Bean ReporterMetrics mySleuthReporterMetrics() {
		return new InMemoryReporterMetrics();
	}
```

And the circular dependency went away. Trying snapshot dependencies in my workplace can be quite challenging, but I will give it a shot.

thanks once more!
