### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by sergey-morenets** [spring-cloud/spring-cloud-sleuth#2187]
**Describe the bug**

The current documentation (https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/project-features.html#project-features) contains incorrect or out-of-date code samples.

**Sample**

```
@Configuration(proxyBeanMethods = false)
    class MyConfig {
    @Bean ZipkinRestTemplateCustomizer myCustomizer() {
        return new ZipkinRestTemplateCustomizer() {
            @Override
            void customize(RestTemplate restTemplate) {
                // customize the RestTemplate
            }
        };
    }
}
```

It seems that this method was deprecated in 2.2.0 and removed in the next versions. New method was added instead:

```
	default RestTemplate customizeTemplate(RestTemplate restTemplate) {
		return restTemplate;
	}

```

**Comment by marcingrzejszczak** [comment]
Are you willing to help us out by updating the docs?

**Comment by sergey-morenets** [comment]
Hi @marcingrzejszczak 

I guess this is highly critical task that should be done only by project members

**Comment by marcingrzejszczak** [comment]
You're saying that updating the docs is a highly critical task that should be done by project members?
