### ISSUE TITLE
 Trace are not being injected in netty error logs

### ISSUE THREAD

**Issue by Jojoooo1** [spring-cloud/spring-cloud-sleuth#2189]
When an error in thrown the trace are not being injected in netty error logs.

![Screenshot from 2022-07-25 15-04-11](https://user-images.githubusercontent.com/17641873/180783972-023dc91d-3b7c-4be2-bd7c-2d2a6719cb28.png)

## Expected Behavior
Traces should be injected in error logs.

## Actual Behavior
Traces are not being injected.

## Your Environment
java: 17
spring-boot: 2.7.2
spring-boot-starter-webflux using reactor netty http 1.0.21
spring-cloud-starter-sleuth: 3.1.3

**Comment by samueldlightfoot** [comment]
I see the same behaviour if using DECORATE_QUEUES, but using DECORATE_ON_EACH as the Reactor Instrumentation type preserved the trace id.

**Comment by Jojoooo1** [comment]
@samueldlightfoot DECORATE_QUEUES seems to not pass the traces when using flatMap DECORATE_ON_EACH will. But it seems in any case that the trace are not passed to the error log of the webClient which make it very complicate to hunt down the error afterward.

**Comment by marcingrzejszczak** [comment]
I would suggest using `DECORATE_ON_EACH`. Of course it means a big performance drop but it should work most of the time. Sleuth and Reactor instrumentation works most of the time - most likely you found a problematic spot where it doesn't work well. Have you tried the latest snapshots of sleuth?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
