### ISSUE TITLE
Sleuth not sending trace data if the controller has @RefreshScope

### ISSUE THREAD

**Issue by PreetamMyneni** [spring-cloud/spring-cloud-sleuth#219]
I was printing sleuth trace to logs and feeding to Splunk. One interesting finding is if my rest controller has  @RefreshScope its not transmitting the trace to underlying services. I am using RestTemplate for the communication between the services. When i remove @RefreshScope i could see the trace id transmitting across the services.

**Comment by marcingrzejszczak** [comment]
Could you please provide a sample project so that we could check this out?

**Comment by marcingrzejszczak** [comment]
Hmm maybe we can close it then?

**Comment by PreetamMyneni** [comment]
Tested with Bricxton.RC1 working as expected
