### ISSUE TITLE
W3C baggage extraction fails when traceparent header not present 

### ISSUE THREAD

**Issue by jamesmoessis** [spring-cloud/spring-cloud-sleuth#2190]
**Describe the bug**
We need the `baggage` header to be extracted whether there is a `traceparent` header or not. 

**Sample**
I've written a branch here: https://github.com/jamesmoessis/spring-cloud-sleuth/tree/showcase-issue 

The sample sleuth application can be run and called by the `testing.http` file.

We are looking into possible solutions here since this is quite critical for us. We would appreciate some advice into how a solution might look for this. The problem is without a traceparent, there is no context to attach a baggage to. Is there a nice solution to this problem?

**Comment by marcingrzejszczak** [comment]
Why would the baggage be propagated if there's no tracing context in the first place?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by miruflin** [comment]
The [w3c baggage header](https://www.w3.org/TR/baggage/#overview) specification doesn't mention a tracing context specifically, but rather states that libraries should propagate the `baggage` header downstream. In our case we want to propagate tenancy information, which is completely unrelated to tracing.

I don't actually know whether Sleuth would be the right place to implement this logic, given the aim of the library is to handle distributed tracing. At the same time it seems somewhat fit to put the logic into it given it handles header propagation concerns already.

**Comment by marcingrzejszczak** [comment]
I think this is related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/2190 which is related to https://github.com/micrometer-metrics/tracing/pull/71/files .  I will close #2208

**Comment by jamesmoessis** [comment]
@marcingrzejszczak Can I suggest going forward the W3C trace context propagators and W3C baggage propagator should be two separate implementations of `Propagation`. They propagate independently of each other so there is no need to couple them together.  This is indeed how OpenTelemetry implements it [here](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java) and [here](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java), generally then tied together with a composite propagator.

**Comment by wangzlei** [comment]
From the w3c spec, my understanding is Baggage is independent with Trace Context, Trace Context contains traceparent and tracestate, which means using tracestate if user wants to propagate something when traceparent(trace id, span id, trace flags) must present, using Baggage if user wants to propagate something regardless tracing is enabled.
So, correct me if I am wrong, the implementation should support propagate Baggage propagation even traceparent not present.

**Comment by jamesmoessis** [comment]
@wangzlei in newer implementations (Micrometer Tracing + Otel) this works now. Sleuth is deprecated.

**Comment by marcingrzejszczak** [comment]
That's not how it works in Sleuth. It works like this only with Tracing and OTel as @jamesmoessis mentioned
