### ISSUE TITLE
how build span information that start from gateway service to other service. 

### ISSUE THREAD

**Issue by Layfolk-zcy** [spring-cloud/spring-cloud-sleuth#2193]
description :  In my a app case,  I can`t find the link result that  can`t include  gateway span client in feign calling. 

the link result:
`{
    "_index": "zipkin-span-2022-08-11",
    "_type": "_doc",
    "_id": "e9f58c98c96ee13e-612075090fc2043d9e4cad8b2b59bd0a",
    "_score": 1,
    "_source":
    {
        "traceId": "e9f58c98c96ee13e",
        "duration": 10812,
        "remoteEndpoint":
        {
            "ipv4": "127.0.0.1",
            "port": 13602
        },
        "localEndpoint":
        {
            "serviceName": "provider-consumer"
        },
        "timestamp_millis": 1660212239701,
        "kind": "SERVER",
        "id": "e9f58c98c96ee13e",
        "timestamp": 1660212239701055,
        "tags":
        {
            "ServerRequest": "Tag",
            "ServerResponseServlet": "200",
            "belApp": "",
            "belLogy": "",
            "belSer": "PROVIDER-CONSUMER",
            "consumer-Receive": "consumer-Receive",
            "consumerTwoServerRequestServlet": "GET",
            "consumerTwoServerResponse": "Tag",
            "localEndPointIp": "127.0.0.1",
            "localEndPointPort": "8090",
            "mvc.controller.class": "TestController",
            "mvc.controller.method": "consumerTest",
            "provider_consumer_two": "aop",
            "serverName": "PROVIDER-CONSUMER8090"
        }
    }
}`

`{
    "_index": "zipkin-span-2022-08-11",
    "_type": "_doc",
    "_id": "e9f58c98c96ee13e-5986ec009be5410c1a991c296a0cea71",
    "_score": 1,
    "_source":
    {
        "traceId": "e9f58c98c96ee13e",
        "duration": 7775,
        "localEndpoint":
        {
            "serviceName": "provider-consumer"
        },
        "timestamp_millis": 1660212239701,
        "kind": "CLIENT",
        "name": "get",
        "id": "695d43bad47ac4d7",
        "parentId": "e9f58c98c96ee13e",
        "timestamp": 1660212239701979,
        "tags":
        {
            "CONSUMERTWO-HttpClientRequestParser": "consumerTwo-HttpClientRequestParser",
            "CONSUMERTWO-HttpClientResponseParser": "consumerTwo-HttpClientResponseParser",
            "belApp": "",
            "belLogy": "",
            "belSer": "PROVIDER-CONSUMER",
            "consumerClientRequestFeign": "GET",
            "consumerClientResponseFeign": "200",
            "localEndPointIp": "127.0.0.1",
            "localEndPointPort": "8090",
            "serverName": "PROVIDER-CONSUMER8090"
        }
    }
}`

`{
    "_index": "zipkin-span-2022-08-11",
    "_type": "_doc",
    "_id": "e9f58c98c96ee13e-cd917ec9e6eb90cff37bdb1762296f62",
    "_score": 1,
    "_source":
    {
        "traceId": "e9f58c98c96ee13e",
        "duration": 6043,
        "remoteEndpoint":
        {
            "ipv4": "127.0.0.1",
            "port": 13603
        },
        "shared": true,
        "localEndpoint":
        {
            "serviceName": "providers"
        },
        "timestamp_millis": 1660212239703,
        "kind": "SERVER",
        "id": "695d43bad47ac4d7",
        "parentId": "e9f58c98c96ee13e",
        "timestamp": 1660212239703047,
        "tags":
        {
            "ServerRequest": "Tag",
            "ServerRequestServlet": "GET",
            "ServerResponseServlet": "200",
            "belApp": "",
            "belLogy": "",
            "belSer": "providers",
            "consumer-Receive": "consumer-Receive",
            "consumerServerResponse": "Tag",
            "localEndPointIp": "providers",
            "localEndPointPort": "8086",
            "mvc.controller.class": "ProviderController",
            "mvc.controller.method": "getPotValueProviderTwo",
            "serverName": "providers8086"
        }
    }
}`

`{
    "_index": "zipkin-span-2022-08-11",
    "_type": "_doc",
    "_id": "e9f58c98c96ee13e-6c763543cdeab3ace3646d20bdef3172",
    "_score": 1,
    "_source":
    {
        "traceId": "e9f58c98c96ee13e",
        "duration": 3847,
        "localEndpoint":
        {
            "serviceName": "providers"
        },
        "timestamp_millis": 1660212239703,
        "kind": "CLIENT",
        "name": "get",
        "id": "ef3bb59bab7ca4fb",
        "parentId": "695d43bad47ac4d7",
        "timestamp": 1660212239703714,
        "tags":
        {
            "belApp": "",
            "belLogy": "",
            "belSer": "providers",
            "localEndPointIp": "providers",
            "localEndPointPort": "8086",
            "providerTwo-ClientRequest": "providerTwo-Tag",
            "providerTwo-ClientRequestFeign": "GET",
            "providerTwo-ClientResponseFeign": "200",
            "providerTwo-ResponseParser": "providerTwo-ResponseParser",
            "serverName": "providers8086"
        }
    }
}`

`{
    "_index": "zipkin-span-2022-08-11",
    "_type": "_doc",
    "_id": "e9f58c98c96ee13e-c40dd50d438cf34f2ec659b256d93f98",
    "_score": 1,
    "_source":
    {
        "traceId": "e9f58c98c96ee13e",
        "duration": 1316,
        "remoteEndpoint":
        {
            "ipv4": "127.0.0.1",
            "port": 13600
        },
        "shared": true,
        "localEndpoint":
        {
            "serviceName": "provider-one"
        },
        "timestamp_millis": 1660212239706,
        "kind": "SERVER",
        "id": "ef3bb59bab7ca4fb",
        "parentId": "695d43bad47ac4d7",
        "timestamp": 1660212239706035,
        "tags":
        {
            "ServerRequest": "Tag",
            "ServerRequestServlet": "GET",
            "ServerResponse": "Tag",
            "ServerResponseServlet": "200",
            "mvc.controller.class": "ProviderController",
            "mvc.controller.method": "getPotValueProviderOne"
        }
    }
}` 

i wish to record the link of gateway service  when request  gateway service  by openFeign.

**Comment by jonatan-ivanov** [comment]
So is my understanding correct that you want to add a tag to your span when you call a gateway from a client that uses Spring Cloud Feign?

If so, here is the connected section of the docs: https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/htmlsingle/spring-cloud-sleuth.html#how-to-cutomize-http-client-spans
