### ISSUE TITLE
not surpport rocketmq？

### ISSUE THREAD

**Issue by fattyliu** [spring-cloud/spring-cloud-sleuth#2194]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fattyliu** [comment]
not need

**Comment by fattyliu** [comment]
need

**Comment by jonatan-ivanov** [comment]
It seems RocketMQ has support for Spring (https://github.com/apache/rocketmq-spring) so if they also instrument it or their integration works with a Spring component that is already instrumented (Spring Cloud Stream or Spring Integration), this should work. If not, I would open an issue in the https://github.com/apache/rocketmq-spring repo first.
