### ISSUE TITLE
[Kotlin Coroutines] why to end span while restoring thread context?

### ISSUE THREAD

**Issue by akrikheli** [spring-cloud/spring-cloud-sleuth#2197]
**Describe the bug**
Use Spring Cloud Sleuth 3.1.3

[KotlinContextElement.java](https://github.com/spring-cloud/spring-cloud-sleuth/blob/c795675cf93c666c3c13f9bbb9eadbde1f1aa775/spring-cloud-sleuth-instrumentation/src/main/kotlin/org/springframework/cloud/sleuth/instrument/kotlin/KotlinContextElement.java#L68)

The current behaviour confused me: the span is always closed while restoring thread context.

Example: 
```
  @Autowired
  private lateinit var tracer: Tracer

  @Test
  fun spanTest() = runBlocking<Unit> {
    val root = tracer.nextSpan().name("root")
    val rootSpanInScope = tracer.withSpan(root.start())
    try {
      rootSpanInScope.use {
        delay(100)
        withContext(tracer.asContextElement()) {
          delay(100)
        }
      }
    } finally {
      root.end()
    }
  }
```

Zipkin's visualization:

<img width="853" alt="Screenshot 2022-08-30 at 19 38 11" src="https://user-images.githubusercontent.com/23580186/187492545-8d0d54dc-02c8-4b01-b234-d473962a21d9.png">

Expected: duration of root's span more than 200ms

**Comment by marcingrzejszczak** [comment]
That doesn't sound good. I mean we should propagate the context and we should only close the scope after the code was executed.

**Comment by akrikheli** [comment]
May be we should close only scope, without closing a span?

**Comment by marcingrzejszczak** [comment]
yeah that's what seems we should be doing - are you willing to file a PR with a fix and a test?

**Comment by akrikheli** [comment]
May be at this weekend

**Comment by marcingrzejszczak** [comment]
Since today I guess we'll be doing a release I've fixed this
