### ISSUE TITLE
Trace Id not displaying in MDC config in logback

### ISSUE THREAD

**Issue by ManiyanKarthi** [spring-cloud/spring-cloud-sleuth#2200]
Trace Id not displaying in MDC for spring cloud version 2020.0.3 or 2021.0.3 and spring boot version 2.6.8

Config in log-back yaml

%d{HH:mm:ss.SSS} %-5level[%thread] %logger{0} - [%mdc] %msg %n

08:36:00.734 INFO [reactor-http-nio-3] **ClassName** - [] **log content**.

**Comment by marcingrzejszczak** [comment]
Can you create a sample that replicates the problem?

**Comment by ManiyanKarthi** [comment]
HI @marcingrzejszczak 
Create a repo for the same. 
https://github.com/ManiyanKarthi/mdclogissue.git

Able to see the MDC keyset available in filter when a request is coming.
Once it entered controller MDC Objects are empty

Sample log 

15:33:32.062 INFO [reactor-http-nio-3] TraceIdFilter - [traceId=3aa2bb1ec5c2c00a, spanId=3aa2bb1ec5c2c00a] Inside filter [traceId, spanId] 
15:33:32.127 INFO [reactor-http-nio-3] APIController - [] []

**Comment by marcingrzejszczak** [comment]
You didn't mention that you're using it in a WebFlux application. In order for that to work you would need to try to read the MDC values within the flux itself not at the controller level.

**Comment by ManiyanKarthi** [comment]
Hi @marcingrzejszczak 
I have also tried by logging and read the MDC values inside the flux.

https://github.com/ManiyanKarthi/mdclogissue.git

Since i am unable to see the traceid
Logs for the same .

11:44:19.937 INFO [reactor-http-nio-3] TraceIdFilter - [traceId=56111483cef5e369, spanId=56111483cef5e369] Inside filter [traceId, spanId] 
11:44:20.105 INFO [reactor-http-nio-3] APIController - [] TraceId null

**Comment by jonatan-ivanov** [comment]
Here are a few pointers to troubleshoot:
1. Could you please try not defining versions explicitly and use the Boot and the Cloud BOMs instead?
2. Could you please try not to override the pattern in the logback config (i.e.: delete that config file)?
3. Here is a webflux sample, could you please try if it works for you?
https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples/tree/main/webflux

**Comment by ManiyanKarthi** [comment]
Hi @jonatan-ivanov ,
Thanks for the info. Found out the issue is with  
  **org.springframework.cloud:spring-cloud-starter-gateway**
  
  When i removed this implementation able to see the traceid
  
  I can also see the below option solved the problem.
  spring.sleuth.reactor.instrumentation-type = DECORATE_QUEUES
  
Also recommends to 
Uses the new decorate queues feature from Project Reactor. Should allow the feature set of DECORATE_ON_EACH with the least impact on the performance.
  
 https://docs.spring.io/spring-cloud-sleuth/docs/3.1.3/reference/html/integrations.html#sleuth-reactor-integration

Refer:
https://github.com/spring-cloud/spring-cloud-sleuth/issues/1815

https://github.com/spring-cloud/spring-cloud-gateway/issues/2171

Which would be the best option?

**Comment by marcingrzejszczak** [comment]
If you have gateway on the classpath we automatically set the instrumentation type to MANUAL, this is why we you saw the change in behaviour.

**Comment by ManiyanKarthi** [comment]
okay Thanks @marcingrzejszczak
