### ISSUE TITLE
The name of the span has cardinality issue which creates multiple different operations for a single type of http request

### ISSUE THREAD

**Issue by ibu04** [spring-cloud/spring-cloud-sleuth#2201]
**Describe the bug**
The name of the span should appear as GET demo-request/1, but it should be like: GET demo-request/{path-variable}

**Sample**
If possible, please provide a test case or a minimal **Maven** sample written in **Java** that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by jonatan-ivanov** [comment]
Could you please give us more details about the issue?

**Comment by ibu04** [comment]
> Could you please give us more details about the issue?

actually the span name has the value of the path variable.

let suppose I create an API with URL: http://localhost:8080/demo/{id}
it shows the span name as http://localhost:8080/demo/1
http://localhost:8080/demo/2
http://localhost:8080/demo/3
basically it shows the value of the path variable {id}. This issue is fixed in 3.x +, but we want to use the existing 1.3.6

**Comment by marcingrzejszczak** [comment]
You're filing a request to fix Sleuth 1.3.x? That is not supported anymore.

**Comment by ibu04** [comment]
the issue is that we are using an old version of spring, less than 2.x and 3.x version of sleuth is not working properly with it, its having some dependency issues, thats why we opt to keep 1.3.6.
what do you suggest?

**Comment by marcingrzejszczak** [comment]
I suggest that you upgrade to 2.x or 3.x. We can't help you if you're working with an unsupported version. You can check this page https://spring.io/projects/spring-cloud-sleuth#support for support versions
