### ISSUE TITLE
Spring Sleuth with Jersey Rest API

### ISSUE THREAD

**Issue by anilkumarravi** [spring-cloud/spring-cloud-sleuth#2202]

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by anilkumarravi** [comment]
Thank  you Marc. 
This is not a bug, but i am looking for usage of sleuth with jersey rest api. I tried to google but did not get much help. 

My problem is: 
If you Observe the below log, the Trace id should come like [Test,92726764c6bf7cf3, spanid], but it is not coming as expected. 

2022-09-07 16:03:19.101  INFO [Test,,] 23108 --- [nio-9090-exec-1] : Service Invoked with Traceid:: 92726764c6bf7cf3

I am using Sleuth version - 3.0.2 with Jersey Rest API using Spring boot. 

But, same is working fine with Spring Rest using Spring boot. 

Please help me.

**Comment by jonatan-ivanov** [comment]
Sleuth 3.0.x is not supported anymore.

Do you use spring-boot-starter-jersey or you configure your servlet and endpoint manually? I'm not sure either of them are supported but I would try to use the boot starter ([see docs](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#web.servlet.jersey))
If it does not work, you either need to use it in a way that is supported or instrument it on your own.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
