### ISSUE TITLE
It is not possible to qet QueueCapacity from `LazyTraceThreadPoolTaskExecutor`

### ISSUE THREAD

**Issue by bhattacharyyasom** [spring-cloud/spring-cloud-sleuth#2203]
**Describe the bug**
It is not possible to qet QueueCapacity from `LazyTraceThreadPoolTaskExecutor`

**Sample**

The `LazyTraceThreadPoolTaskExecutor` class wraps a delegate of type `ThreadPoolTaskExecutor `
Following is the issue,
In [this piece of code](https://github.com/spring-cloud/spring-cloud-sleuth/blob/c795675cf93c666c3c13f9bbb9eadbde1f1aa775/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceThreadPoolTaskExecutor.java#L300) we set the capacity on the delegate.

But we do not have a method to `getQueueCapacity` from the delegate.
Also, there is no way to get the delegate like we do with the `getThreadPoolExecutor ` method. 

In the end we can set queue capacity on the `LazyTraceThreadPoolTaskExecutor` but not get the value from it.
I can do a PR if it helps but I think this is a miss.

**Comment by marcingrzejszczak** [comment]
Yeah we've forgotten about the delegation. Please be my guest to provide a PR with a proper fix.

**Comment by bhattacharyyasom** [comment]
@marcingrzejszczak Raised a request at https://github.com/spring-cloud/spring-cloud-sleuth/pull/2204 

Do let me know of any feedback as I am new to the process here. Thanks.

**Comment by marcingrzejszczak** [comment]
fixed by https://github.com/spring-cloud/spring-cloud-sleuth/pull/2204

**Comment by bhattacharyyasom** [comment]
@marcingrzejszczak I have a question. Is there a timeline when a snapshot build can be available for use ? I am working on something that needs this code.

**Comment by marcingrzejszczak** [comment]
Snapshots should already be available

**Comment by bhattacharyyasom** [comment]
@marcingrzejszczak  I am unable to locate the file in the snapshot jar. 
I see this when trying to import the snapshot. 
<img width="570" alt="Screenshot 2022-09-12 at 4 28 27 PM" src="https://user-images.githubusercontent.com/1084453/189637140-3bd6e888-3899-45b1-afe9-f6ebb3642db4.png">

**Comment by marcingrzejszczak** [comment]
You're using Sleuth 3.1.3 but only took in sleuth starter in version 3.1.5-SNAPSHOT. Please upgrade to a snaphost version of the release train BOM

**Comment by bhattacharyyasom** [comment]
Running into a `RefreshBootstrapRegistryInitializer has been compiled by a more recent version of the Java Runtime.(class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`
Using following versions :

- org.springframework.cloud:spring-cloud-starter-sleuth:3.1.5-SNAPSHOT
- spring cloud version : 2022.0.0-SNAPSHOT
- spring boot version : 2.7.2-SNAPSHOT
- Running Java 11 Temurin

**Comment by marcingrzejszczak** [comment]
The latest supported Cloud version with Sleuth is 2021.0.x. In your case you need to run `2021.0.5-SNAPSHOT `

**Comment by bhattacharyyasom** [comment]
Thank you very much. This worked ! Appreciate the advise.
