### ISSUE TITLE
when i do a feign request in rabbit consumer method, the feign request lost tracer info

### ISSUE THREAD

**Issue by sunset535** [spring-cloud/spring-cloud-sleuth#2207]
my sleuth version is 2.2.2.RELEASE.
i found if i use @RabbitListener annotation, feign request in consumer method will get the correct tracer info.
but when i use the custom annotation as the rabbit consumer method, the feign request will lost the tracer info.  
my custom rabbit consumer method just use a reflection, nothing else.
![image](https://user-images.githubusercontent.com/3860179/190999406-461f728c-021c-47b7-980e-ec67ef9d0ee3.png)
if i use RabbitTemplate's BeforePublishPostProcessors and SimpleMessageListenerContainer's AfterReceivePostProcessors , i could get the tracer info when my custom method get the message,  but i dont know how to use the MDC info througn inflection to the feign request, of course i had try if i specify the custom method run in LazyTraceAsyncTaskExecutor or LazyTraceExecutor, the both all still doesn't work.
 i want to consult, is there any special usage to my scene, or my usage is wrong, how could i fix it?

**Comment by marcingrzejszczak** [comment]
Please upgrade to the latest supported version and try again

**Comment by sunset535** [comment]
> 

my cloud version is Hoxton.SR3, it‘s match the sleuth version is 2.2.2.RELEASE.

**Comment by sunset535** [comment]
> 


my cloud version is Hoxton.SR3, it‘s match the sleuth version is 2.2.2.RELEASE.

**Comment by marcingrzejszczak** [comment]
You can check the support dates over here https://spring.io/projects/spring-cloud-sleuth#support , pick a version that is still supported

**Comment by sunset535** [comment]
> You can check the support dates over here https://spring.io/projects/spring-cloud-sleuth#support , pick a version that is still supported

i have take1 week to upgrade my cloud, but this problem still exist. 
![image](https://user-images.githubusercontent.com/3860179/192296258-e25a5264-68ab-4b81-86c4-80a50da143a2.png)

![image](https://user-images.githubusercontent.com/3860179/192296469-a8b42b63-450d-4869-bf69-3403f32643d8.png)

![image](https://user-images.githubusercontent.com/3860179/192296734-fbdadd5c-8a8d-44fa-8ee8-96519bf41b79.png)

![image](https://user-images.githubusercontent.com/3860179/192297172-cc524f81-2d09-46d5-a275-7ff42a5935e9.png)

**Comment by marcingrzejszczak** [comment]
You're using an unsupported version, please upgrade to the newest supported version and if the problem persists please open a new issue with a reproducer.

**Comment by sunset535** [comment]
> You're using an unsupported version, please upgrade to the newest supported version and if the problem persists please open a new issue with a reproducer.

my spring cloud version 2021.0.4, it's an unsupported version?

**Comment by jonatan-ivanov** [comment]
A few days ago you said:
>my cloud version is Hoxton.SR3, it‘s match the sleuth version is 2.2.2.RELEASE.

Which is unsupported.

**Comment by sunset535** [comment]
> 

i have upgraded to 2021.0.4, sleuth 3.1.4 , the problem still exist.

**Comment by sunset535** [comment]
> A few days ago you said:
> 
> > my cloud version is Hoxton.SR3, it‘s match the sleuth version is 2.2.2.RELEASE.
> 
> Which is unsupported.


i have upgraded to 2021.0.4, sleuth 3.1.4 , the problem still exist.

**Comment by marcingrzejszczak** [comment]
We will need a reproducer, feign does work correctly and rabbit also works correctly. Maybe you have some special use case that we don't understand

**Comment by sunset535** [comment]
> We will need a reproducer, feign does work correctly and rabbit also works correctly. Maybe you have some special use case that we don't understand

after debug tracing, i found the problem.

the normal request, the TraceContext is correct.
![image](https://user-images.githubusercontent.com/3860179/194796318-0b5427af-ec94-417c-8bde-37b5e0c618f9.png)

the feign request by custom mq consumer method,  the TraceContext is null.
![image](https://user-images.githubusercontent.com/3860179/194796399-7d77d329-40e8-4149-b436-264c661bb75e.png)

 i dont know how to resolve it.

> We will need a reproducer, feign does work correctly and rabbit also works correctly. Maybe you have some special use case that we don't understand
