### ISSUE TITLE
Baggage not propagated to Spring Cloud Stream (GCP Pub/Sub)

### ISSUE THREAD

**Issue by poznachowski** [spring-cloud/spring-cloud-sleuth#2211]
I'm trying to use baggage feature to propagate data along traceId. It does not get propagated into downstream messaging system.

Sample project reproducing the issues can be found here: https://github.com/poznachowski/tracing-baggage

Scenario is simple:
I call HTTP endpoint, which assigns the baggage field value and sends out a message with `StreamBridge`.
On the receiving end the baggage value is null.

Running test in the sample project is enough to reproduce it - it uses GCP Pub/Sub emulator (through Playtikka TestContainers)

SB: 2.7.4
SC: 2021.0.4

**Comment by marcingrzejszczak** [comment]
Please upgrade to [Micrometer Tracing](https://docs.micrometer.io/tracing/reference/). Spring Cloud Sleuth is feature complete and out of OSS support.
