### ISSUE TITLE
Gateway request can not collect to zipkin 

### ISSUE THREAD

**Issue by Layfolk-zcy** [spring-cloud/spring-cloud-sleuth#2213]
spring-boot-dependencies.version>2.6.3
spring-cloud-dependencies.version>2021.0.1
spring-cloud-alibaba-dependencies.version>2021.0.1.0

By gateway transit to other server, the gateway`s span can not show in the zipkin. But gateway api completely call, which span can collect to zipkin. 
![image](https://user-images.githubusercontent.com/59356890/194790385-13d8fe84-2756-4b9a-a26e-00e9392010b2.png)

demo git : 

- [ ] https://github.com/Layfolk-zcy/swagger-zipkin-validate.git

**Comment by marcingrzejszczak** [comment]
We have a sample for gateway and it works fine https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples/tree/main/gateway . Can you double check that you're doing things in a similar fashion?

**Comment by Layfolk-zcy** [comment]
> We have a sample for gateway and it works fine https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples/tree/main/gateway . Can you double check that you're doing things in a similar fashion?

Thank you! i browsed the sample.
The gateway project api call  that the span message can  record into kafka. But if gateway server transmit the request to other server when the gateway span messages will not be record into kafka, and just the span that other server`s span messages. So  i confused, i offer the demo project, gateway project can not be recored span into kafka.

**Comment by Layfolk-zcy** [comment]
I checked my code and found that the dependencies of spring-cloud-starter-sleuth and spring-cloud-sleuth-zipkin are located in other projects. My current project depends on the services that contain these two dependencies. After the project is started, sleuth cannot be recorded. The span information of my current service. But if my project directly introduces spring-cloud-starter-sleuth and spring-cloud-sleuth-zipkin dependencies, I can get the results I want to use in zipkin UI.

**Comment by marcingrzejszczak** [comment]
Great to hear that!

**Comment by Layfolk-zcy** [comment]
> Great to hear that!

but the span message can not show parent span in the gateway project, which the span is not relative in zipkin UI. when feign request call other server, the result just contain other server reporting span messages in the zipkin UI.
![image](https://user-images.githubusercontent.com/59356890/195243806-43a2bf2a-8bbb-4338-9060-982fa1eccc4c.png)

**Comment by marcingrzejszczak** [comment]
Please go to start.spring.io and create projects that replicate this issue. You have provided a gigantic setup to replicate this - let's try to isolate this as much as possible
