### ISSUE TITLE
Sleuth and Jaeger compete for single bean 'defaultSkipPatternBean' name 

### ISSUE THREAD

**Issue by demtnt** [spring-cloud/spring-cloud-sleuth#2214]
**Is your feature request related to a problem? Please describe.**
Having sleuth and jaeger dependencies together

```
plugins {
    id("org.springframework.boot") version "2.7.2"
    id("io.spring.dependency-management") version "1.0.12.RELEASE"
...
}

dependencies {
...
    implementation("io.opentracing.contrib:opentracing-spring-jaeger-web-starter:3.3.1")
    implementation("org.springframework.cloud:spring-cloud-starter-sleuth")
}

dependencyManagement {
    val springCloudVersion = "2021.0.3"
    imports {
        mavenBom("org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}")
    }
}
```

got exception 

> **************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> The bean 'defaultSkipPatternBean', defined in class path resource [org/springframework/cloud/sleuth/autoconfig/instrument/web/SkipPatternConfiguration$DefaultSkipPatternConfig.class], could not be registered. A bean with that name has already been defined in class path resource [io/opentracing/contrib/spring/web/starter/SkipPatternAutoConfiguration$DefaultSkipPatternConfig.class] and overriding is disabled.
> 
> Action:
> 
> Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
> 

**Describe the solution you'd like**
It would be nice if you could change name of this bean

**Describe alternatives you've considered**
I could use **spring.main.allow-bean-definition-overriding=true** but this can produce unexpected behavior in other bean definitions

**Additional context**
no

**Comment by marcingrzejszczak** [comment]
Have you asked in the opentracing space to rename the beans?

**Comment by marcingrzejszczak** [comment]
Since open tracing has been copying Sleuth code for years I think it's not a lot to ask to at least rename the beans when they're doing copy paste :) I'm closing this. You can file an issue in their repo to rename the beans

**Comment by demtnt** [comment]
> Since open tracing has been copying Sleuth code for years I think it's not a lot to ask to at least rename the beans when they're doing copy paste :) I'm closing this. You can file an issue in their repo to rename the beans

Thank You for your answer
