### ISSUE TITLE
BufferingSpanReporter memory leak on Spring Cloud Sleuth 3.1.4

### ISSUE THREAD

**Issue by tanisperez** [spring-cloud/spring-cloud-sleuth#2215]
**BufferingSpanReporter is memory leaking BraveFinishedSpan instances**

We are using **spring-cloud-sleuth-autoconfigure-3.1.4** and we are having some memory issues with our application. We have created a memory dump to analyze the application, the Eclipse Memory Analyzer reports that BufferingSpanReporter is a leak suspect.

![image](https://user-images.githubusercontent.com/2805369/195108395-c759d985-f110-4767-a130-5299a168e3bd.png)

Inspecting the values of the spans field inside the class **BufferingSpanReporter**, we have 9.954 instances of the class **BraveFinishedSpan**.

![image](https://user-images.githubusercontent.com/2805369/195108833-43e75590-5859-4493-aaa5-80efa22ab92b.png)

**Sample**
We are using **spring-boot 2.7.1** + **Java 8** with **spring-cloud-starter-sleuth 3.1.4** with default properties.

**Comment by marcingrzejszczak** [comment]
Yes and by default you can have 10 000. That value is configurable - you can lower it to whatever value you want. Why do you think that this is a memory leak?

**Comment by tanisperez** [comment]
Hi @marcingrzejszczak,

Thank you for your response, we didn't know this limit can be configurable, we think that 10.000 entries it is a bit excesive for us. Can you point me to the value configuration in the documentation?

Thank you in advance.

**Comment by marcingrzejszczak** [comment]
Sure, https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/project-features.html#features-traces-actuator

> The size of the queue where the spans are stored can be configured via the management.endpoint.traces.queue-size property.
