### ISSUE TITLE
Baggage field is not propagated in Spring Integration

### ISSUE THREAD

**Issue by mozzer39** [spring-cloud/spring-cloud-sleuth#2220]
I'm using Spring Sleuth with Spring Integration. I create a baggage field, which I want to be propagated.

```
@Configuration
public class SleuthConfig {
    @Bean
    BaggageField myBaggageField() {
        return BaggageField.create("myBaggageField");
    }

    @Bean
    public BaggagePropagationCustomizer baggagePropagationCustomizer(List<BaggageField> baggageFields) {
        return builder -> baggageFields.forEach(baggageField -> builder.add(BaggagePropagationConfig.SingleBaggageField.local(baggageField)));
    }
}
```

Then in the first step of my integration flow I set the value: `myBaggageField.updateValue(value)`

At this point, both traceId and spanId are equal. Later in my flow I try to get the value of the baggage: `myBaggageField.getValue()`

The result is null. At this point spanId is different from traceId. Why can't I access my baggage field? Why it isn't propagated and how to fix this?

As a workaround I disabled Spring Integration in Sleuth config: `spring.sleuth.integration.enabled: false`

**Comment by marcingrzejszczak** [comment]
Here you have an example of baggage producer https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples/tree/main/baggage-producer and baggage consumer https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples/tree/main/baggage-consumer projects with baggage set up. Can you ensure that you're using the baggage in a similar way?

**Comment by mozzer39** [comment]
Yes, I am using baggage in a similar way. Looking at your example of baggage producer: the problem is that when try-with-resource block is closed, `tracer.getAllBaggage()` returns empty list and my baggage fields are lost. Is it the expected behaviour?

I'm using Spring Integration. First step in my flow is setting baggage fields, which are used in next steps. Unfortunately I can't access them in next steps because of the reason above. Thank you.

**Comment by marcingrzejszczak** [comment]
Can you create a very simple sample that replicates this problem?

**Comment by mozzer39** [comment]
Sure thing. Here it is:
https://github.com/mozzer39/spring-integration-with-sleuth-sample/

**Comment by marcingrzejszczak** [comment]
Please upgrade to [Micrometer Tracing](https://docs.micrometer.io/tracing/reference/). Spring Cloud Sleuth is feature complete and out of OSS support.
