### ISSUE TITLE
Spring Cloud Gateway duplicate traceId 

### ISSUE THREAD

**Issue by lonmstalker** [spring-cloud/spring-cloud-sleuth#2221]
I'm using Spring Cloud Gateway 3.1.4 with Spring-cloud-starter-sleuth 3.1.4 and Kotlin 1.7.10
Enabled instrumentation type is DECORATE_QUEUES (if use MANUAL it'll generate trace id well but doesn't put in MDC) and Netty access log. When I locally debug api gateway, trace and span id generate okay but when gateway work in cluster where there are a lot of http and ws requests. trace id is ever same before reload application (but span id is ever different)
I tried to reproduce this situation locally but for my pc it's impossible, 40 threads in jmeter haven't given needed result
I use ReactorNettyHttpTracing customizer and Spring Security 2.6.3 based on ReactiveJwtDecoder(maybe it's important)

I can't send example because i'ts private company code, but we don't use something specific

**Comment by marcingrzejszczak** [comment]
Should be fixed by https://github.com/spring-cloud/spring-cloud-sleuth/commit/6a3612ce94e6f3b47e5a4b855b897c0c0581bbb9
