### ISSUE TITLE
Will Sleuth keep up to date?

### ISSUE THREAD

**Issue by MrXionGe** [spring-cloud/spring-cloud-sleuth#2222]
![image](https://user-images.githubusercontent.com/23261935/197981774-af954173-068e-43af-acf3-77f9d0918c7f.png)
Will Sleuth only be updated to version 3.1?
Are we going to use "micrometer-tracing"?

**Comment by marcingrzejszczak** [comment]
Yes, that's exactly what we wrote in the attached screenshot :)

**Comment by joshdcu** [comment]
Could you please explain if the Micrometer Tracing project will provide the same auto-configuration "magic" (😅)  as Spring Cloud Sleuth? Specifically, the [Sleuth docs](https://spring.io/projects/spring-cloud-sleuth#features) say:
> Sleuth configures everything you need to get started. This includes where trace data (spans) are reported to, how many traces to keep (sampling), if remote fields (baggage) are sent, and which libraries are traced.

But from the [Micrometer Tracing docs](https://micrometer.io/docs/tracing), it looks like we have to do the tracer configuration manually 😞

**Comment by MrXionGe** [comment]
> 

Sleuth is so excellent that we don't want to use micrometer at all.

**Comment by jonatan-ivanov** [comment]
@sereneshikari Micrometer Tracing does not depend on Spring so it will not give you auto-configuration, the auto-configuration will be provided by Spring Boot.

@MrXionGe Micrometer Tracing is Sleuth copied over and its package name changed.

**Comment by MrXionGe** [comment]
@jonatan-ivanov 
Will Sleuth not keep updated?
Or is there a 'starter' similar to Sleuth?

**Comment by joshdcu** [comment]
> @sereneshikari Micrometer Tracing does not depend on Spring so it will not give you auto-configuration, the auto-configuration will be provided by Spring Boot.

Thanks for the clarification @jonatan-ivanov! Would you happen to know if the auto-configuration by Spring Boot is a work in progress or ready for use?

 > Will Sleuth not keep updated? Or is there a 'starter' similar to Sleuth?

@MrXionGe, you need to move to Micrometer Tracing. Please read the documentation available [here](https://micrometer.io/docs/tracing) for how to do so

**Comment by marcingrzejszczak** [comment]
Please read this blog post https://spring.io/blog/2022/10/12/observability-with-spring-boot-3

**Comment by joshdcu** [comment]
Thanks a lot @marcingrzejszczak! I also saw this completed issue in the `spring-boot` repo: https://github.com/spring-projects/spring-boot/issues/30156.
