### ISSUE TITLE
Support of Jetty RequestLogHandler

### ISSUE THREAD

**Issue by usharik** [spring-cloud/spring-cloud-sleuth#2223]
I have a spring-boot application that uses Jetty as a server.

As I see at the moment, all the tracing parameters are not available at the Jetty handlers level and logging from RequestLogHandler looks like this
```
[INFO] 2022-10-27 15:25:28,115 [thrd01, e2a783480dfe0b5f, e2a783480dfe0b5f] some.application.Class - Some logs message with trace info
[INFO] 2022-10-27 15:25:28,158 [thrd01, , ] org.eclipse.jetty.server.RequestLog - [0:0:0:0:0:0:0:1] - - [27/Oct/2022:13:25:28 +0000] "GET /rest/path HTTP/1.1" 404 290 138
```
Is it possible to resolve this problem somehow?

**Comment by marcingrzejszczak** [comment]
Sleuth is feature complete. We are not planning to add any new features to it.

**Comment by usharik** [comment]
Just to summarize the issue. Problem is that the request logger from Jetty is called after the Sleath `TraceFilter` which is the closing scope and removes all parameters from `MDC`. Not sure if the issue is somehow resolvable because Jetty logging is implemented out of Servlet API architecture...
