### ISSUE TITLE
I'm a fresher can you tell how to add propagation key??

### ISSUE THREAD

**Issue by durga729** [spring-cloud/spring-cloud-sleuth#2225]

**Comment by marcingrzejszczak** [comment]
https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/project-features.html#features-baggage

**Comment by durga729** [comment]
Hii, I'm a fresher i saw your discussion in internet  regarding overriding
trace I'd for me also same problem.i don't know how to use propagation key
and insert it in  application.can you help me to overcome this problem.
