### ISSUE TITLE
the method contain @Scheduled that can collect  the span into zipkin.

### ISSUE THREAD

**Issue by Layfolk-zcy** [spring-cloud/spring-cloud-sleuth#2226]
Service A
`
@Component
public class ActuatorQueryTimer {

    @Autowired
    private RestTemplate restTemplate;
    @Scheduled(fixedDelay = 60 * 1000)
    public void updateSysSrcHis() {
            String forObject = restTemplate.getForObject("http://127.0.0.1:9091/provider/port", String.class)；
    }
}
`

Service B

`

@RestController
@RequestMapping("/provider")
public class ProviderController {

    @Value("${server.port}")
    private String port;

    @Autowired
    private ProviderFeign providerFeign;

    @GetMapping("/port")
    public String getProviderPort() {
        return port;
    }
}
`

![image](https://user-images.githubusercontent.com/59356890/199694661-d57439ce-d1b5-484f-9624-bd6a0794e672.png)

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.
