### ISSUE TITLE
Reactor Tracing Context alignment problem 

### ISSUE THREAD

**Issue by jfsanchez91** [spring-cloud/spring-cloud-sleuth#2228]
**Describe the bug**
Wrong Tracing Context for "same" Mono<Event> when the Mono is "merged" into a Flux.
Having this example:

```kotlin
@Component
class ReactorTest(
    private val tracer: Tracer,
) {
    companion object {
        private val logger = LoggerFactory.getLogger(ReactorTest::class.java)
    }

    data class Event(val id: Int)

    private fun receive(): Flux<Event> = Flux.fromIterable((0..20))
        .map { Event(id = it) }.flatMap { event ->
            ReactorSleuth.tracedMono(tracer, tracer.nextSpan(tracer.currentSpan())) {
                logger.info("Adding tracing information to Mono<Event>.")
                event.toMono()
            }
        }

    fun consume() = receive()
        .doOnNext { event ->
            logger.info("Fetched event: $event")
        }
        .filter { it.id % 2 == 0 }
        .groupBy { it.id % 4 }
        .flatMap(
            { group ->
                group.concatMap { event ->
                    logger.info("Processing event: $event")
                    Mono.just(event)
                        .delayElement(Duration.ofMillis(Random.nextLong(200, 500)))
                        .delaySubscription(Duration.ofMillis(Random.nextLong(200, 500)))
                        .map { Event(id = it.id * 2) }
                        .doOnNext { logger.info("Math is done $event") }
                        .onErrorReturn(event)
                        .doFinally {
                            logger.info("Processing done")
                        }
                }
            },
            4,
        )
        .doOnError { error ->
            logger.error("There was an unhandled error while processing the Event. $error")
        }
        .doFinally {
            logger.info("DONE")
        }
}
```
I would expect that every log statement related to the same Event should have always the same Tracing Context.
For instance, the `traceId` for the log `Fetched event: Event(id=8)` should be the same as in the log `Processing event: Event(id=8)` and the same `traceId` should also correlate the logs `Adding tracing information to Mono<Event>` and `Math is done Event(id=8)`.

**How can I align the tracing information the way that I can trace/correlate all logs related to one specific `Event`?**

**Sample**
https://github.com/jfsanchez91/sleuth-reactor-tracing-issue-example

**Comment by jonatan-ivanov** [comment]
Have you seen this?
https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/htmlsingle/spring-cloud-sleuth.html#sleuth-reactor-integration

There are multiple ways to propagate the context, if you are doing it manually, you can check the code snippet in the docs and you can also utilize `deferContextual`.
If you are using Reactor 3.5, there is a new operator there called `tap` (see Reactor docs).

**Comment by jfsanchez91** [comment]
Hi @jonatan-ivanov, 
what could be the purpose of using `deferContextual` within this example?
My issue is not actually to propagate the Context, but the mixing up of the Context between the `group.concatMap` operator and the initial `flatMap` where the `ReactorSleuth.tracedMono (contextWrite)` is used.
If you see the example repository I provided, I can't rely on the `traceId` to correlate log statements for the same `Event`.
Every log inside the `concatMap` operator, looks to have a different Context than the one in the original Flux.

Thank you very much for taking the time to check this.

**Comment by marcingrzejszczak** [comment]
Can you check the latest version of Sleuth? There were fixes done for Sleuth and Reactor that might be fixing this problem?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by j-lebek** [comment]
Thank you for the hint, @marcingrzejszczak. Please, can you provide more details on the respective fixes? Do you have a particular fix in mind that you could link here? Thank you.

**Comment by marcingrzejszczak** [comment]
E.g. this one https://github.com/spring-cloud/spring-cloud-sleuth/commit/6a3612ce94e6f3b47e5a4b855b897c0c0581bbb9

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
