### ISSUE TITLE
Spring Sleuth not woring for SOAP outgoing calls.

### ISSUE THREAD

**Issue by odiego-developer** [spring-cloud/spring-cloud-sleuth#2229]
Hi, guys! 

I'm trying to set up the following Spring Sleuth configuration to propagate remote fields (HTTP request headers) across the projects out-of-the-box:

```
  sleuth:
    baggage:
      remote-fields:
        - Caller-Id
```
 
For the outgoing Rest calls, it's working fine:

`Request headers: {Accept=[application/json; distances], Authorization=[Bearer ...], X-B3-TraceId=[3f3f61757851d371], X-B3-SpanId=[3f3f61757851d371], X-B3-Sampled=[1], **caller-id=[value]**}
`
However, it's not true for the SOAP outgoing calls:

`SOAP Headers - {Authorization=[Bearer...]}`

 We're using Feign as Rest client and jaxws-spring for SOAP.
 
```
         <dependency>
            <groupId>com.revinate</groupId>
            <artifactId>jaxws-spring</artifactId>
        </dependency>
```
        
Am I doing something wrong?

**Comment by jonatan-ivanov** [comment]
`com.revinate:jaxws-spring` is not instrumented by Sleuth. In order to make context propagation work somebody needs to instrument it, i.e.: set those headers. I guess this library belongs to your employer and the maintainers of this client should take care about instrumenting this.
Can you contact them to do it?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
