### ISSUE TITLE
Build fails within spring-cloud-sleuth-sample-zipkin

### ISSUE THREAD

**Issue by flytosky** [spring-cloud/spring-cloud-sleuth#223]
When I was running the application with command: 

mvn spring-boot:run 

I saw these ERROR messages:

[ERROR] No plugin found for prefix 'sprint-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/weiwang/.m2/repository), spring-snapshots (http://repo.spring.io/libs-snapshot-local), spring-milestones (http://repo.spring.io/libs-milestone-local), central (https://repo.maven.apache.org/maven2)] -> [Help 1]

Could someone help me figure out the issue? Thanks!

**Comment by adriancole** [comment]
sprint-boot (with a t) isn't in the project anywhere. Did you perhaps have
a typo?

I was able to execute mvn spring-boot:run from
spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin

**Comment by flytosky** [comment]
Thanks for your reply! The errors are like the following:

[ERROR] Failed to execute goal on project spring-cloud-sleuth-sample-zipkin: Could not resolve dependencies for project org.springframework.cloud:spring-cloud-sleuth-sample-zipkin:jar:1.0.0.BUILD-SNAPSHOT: Failure to find org.springframework.cloud:spring-cloud-sleuth-sample-test-core:jar:1.0.0.BUILD-SNAPSHOT in http://repo.spring.io/libs-snapshot-local was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by adriancole** [comment]
looks like your maven cache is stale? try

mvn -U clean spring-boot:run

**Comment by flytosky** [comment]
Hi, I have used mvn -U clean spring-boot:run or cleaned the maven cache, the errors remain same. I also asked my friends to try this project in his machine, the errors are the same.

**Comment by marcingrzejszczak** [comment]
Can you type in exactly what command are you running and from which level of the project directory structure?

**Comment by flytosky** [comment]
The path is: 

spring-cloud-sleuth/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin 

The command is:

mvn spring-boot:run

The errors are:

[ERROR] Failed to execute goal on project spring-cloud-sleuth-sample-zipkin: Could not resolve dependencies for project org.springframework.cloud:spring-cloud-sleuth-sample-zipkin:jar:1.0.0.BUILD-SNAPSHOT: Failure to find org.springframework.cloud:spring-cloud-sleuth-sample-test-core:jar:1.0.0.BUILD-SNAPSHOT in http://repo.spring.io/libs-snapshot-local was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced -> [Help 1]

Thanks!

**Comment by marcingrzejszczak** [comment]
Sth's wrong with your cache. I've just executed the same command as you have:

```
mvn spring-boot:run
```

and this is what I got:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building spring-cloud-sleuth-sample-zipkin 1.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.3.3.RELEASE:run (default-cli) > test-compile @ spring-cloud-sleuth-sample-zipkin >>>
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:check (validate) @ spring-cloud-sleuth-sample-zipkin ---
[INFO] Starting audit...
Audit done.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spring-cloud-sleuth-sample-zipkin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ spring-cloud-sleuth-sample-zipkin ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ spring-cloud-sleuth-sample-zipkin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/marcingrzejszczak/repo/spring-cloud-sleuth/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ spring-cloud-sleuth-sample-zipkin ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< spring-boot-maven-plugin:1.3.3.RELEASE:run (default-cli) < test-compile @ spring-cloud-sleuth-sample-zipkin <<<
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.3.3.RELEASE:run (default-cli) @ spring-cloud-sleuth-sample-zipkin ---

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.3.3.RELEASE)

2016-03-24 09:23:23.840  INFO [testsleuthzipkin,,,] 48256 --- [           main] 
...
```

Maybe first build and install the whole project 

`./mvnw clean install` 

and then re-run it? If that doesn't work then try removing any spring-cloud-sleuth related artifacts from your .m2 and re-run it.

**Comment by flytosky** [comment]
It works now after maven clean and install. Thanks very much!

**Comment by marcingrzejszczak** [comment]
No problem :)
