### ISSUE TITLE
Wrong autoconfig dependency in TraceAsyncCustomAutoConfiguration

### ISSUE THREAD

**Issue by bleipold** [spring-cloud/spring-cloud-sleuth#2230]
There seems to be a misconfiguration of autoconfiguration in the class ``org.springframework.cloud.sleuth.autoconfig.instrument.async.TraceAsyncCustomAutoConfiguration``.

``
@AutoConfigureAfter(
  name = {"org.springframework.cloud.sleuth.instrument.scheduling.TraceSchedulingAutoConfiguration"},
  value = {BraveAutoConfiguration.class}
)
``

I think it has to be ``org.springframework.cloud.sleuth.autoconfig.instrument.scheduling.TraceSchedulingAutoConfiguration`` rather than ``org.springframework.cloud.sleuth.instrument.scheduling.TraceSchedulingAutoConfiguration``.

**Comment by marcingrzejszczak** [comment]
Is there any error / exception that you're seeing? Which version of Sleuth are you referring to?

**Comment by bleipold** [comment]
No, there is no exception in the log. I just hit a breakpoint for IllegalStateException (in AutoConfigurationClass.getAnnotationMetadata line 237) while investigating another issue.  So it may affect autoconfiguration sorting.

I use Sleuth in version 3.1.5.

**Comment by marcingrzejszczak** [comment]
So you're saying that there's no such class? If that's the case are you willing to file a PR to fix this?

**Comment by bleipold** [comment]
There is such a class but in another package (see the initial post). But I don't know, whether it's wanted or just a typo.
