### ISSUE TITLE
Document tracing headers on responses

### ISSUE THREAD

**Issue by mwisnicki** [spring-cloud/spring-cloud-sleuth#2232]
There used to be a documentation about tracing headers on responses https://github.com/spring-cloud/spring-cloud-sleuth/commit/8437bef6a99840762b6087a3af7ca4a27495ddde but I wasn't able to locate anything like it in current docs: https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/integrations.html#sleuth-http-server-integration

Why was this documentation removed?
Can similar documentation be added back (ideally with [explanation](https://github.com/spring-cloud/spring-cloud-sleuth/issues/424#issuecomment-306274652) how it is a security risk)?

**Comment by marcingrzejszczak** [comment]
It's here https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/howto.html#how-to-add-headers-to-the-http-server-response
