### ISSUE TITLE
Deprecation warning for reactor-netty-http-brave

### ISSUE THREAD

**Issue by bergerst** [spring-cloud/spring-cloud-sleuth#2233]
The documentation currently contains correction steps to ensure that Logbook logs always contain spanIds and traceIds: https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/htmlsingle/spring-cloud-sleuth.html#sleuht-http-client-logbook-with-webclient

This is related to feature #1690

Without `reactorNettyHttpTracing.decorateHttpClient()` and `reactorNettyHttpTracing.decorateHttpServer()`, the "Incoming Response" and "Outgoing Response" logs will not contain any spanIds and traceIds.

The module reactor-netty-http-brave will be removed in the future: https://github.com/reactor/reactor-netty/tree/v1.1.0/reactor-netty-http-brave

The deprecation warnings contain hints on using micrometer-tracing instead of reactor-netty-http-brave, but I'm not sure on how to fix the issue of the missing spanIds and traceIds with micrometer.

After a solution was found, the documentation linked above should be updated with the micrometer-tracing way of ensuring spanIds and traceIds.

**Comment by bergerst** [comment]
#1690

**Comment by marcingrzejszczak** [comment]
I had a chat with @violetagg from Reactor Netty and we came to the following conclusions. We will close the issue here and can you please create one in Reactor Netty with a sample that Violeta can take out for a spin?

**Comment by bergerst** [comment]
The linked issue has the information you requested.

**Comment by bergerst** [comment]
Commenting for visibility:

spring-cloud-sleuth will be replaced with the Observability API in Spring Boot 3: https://spring.io/blog/2022/10/12/observability-with-spring-boot-3

The suggestion is to stay on reactor-netty 1.0.x while using Spring Boot 2.
