### ISSUE TITLE
Programmatic Sampler does not stop Zipkin Span reports

### ISSUE THREAD

**Issue by billybong** [spring-cloud/spring-cloud-sleuth#224]
I have a setup where I only want to trace incoming requests with a specific query parameter set (i.e. zipkin=true), which means that I've implemented my custom Sampler.
Now, even though the Sampler returns false, I still see requests to my Zipkin server (POST's to /v1/spans/) as my application creates outbound calls.

To me it seems that all Spans gets reported to Zipkin when originating from a RestTemplate, even though I've tried to disable them. Should I need to override the org.springframework.cloud.sleuth.instrument.web.TraceFilter as well as it seems like this filter is responsible for starting the spans?

My deps...

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-starter-parent:Brixton.M3"
        mavenBom 'org.springframework.cloud:spring-cloud-sleuth:1.0.0.M5'
    }
}

compile 'org.springframework.cloud:spring-cloud-sleuth-zipkin'
compile 'org.springframework.cloud:spring-cloud-starter-sleuth'

**Comment by billybong** [comment]
I have reproduced my issue in https://github.com/billybong/zipkin-issue-always-reports

**Comment by marcingrzejszczak** [comment]
Can you check against latest snapshot?

**Comment by billybong** [comment]
Still the same using:
compile('org.springframework.cloud:spring-cloud-starter-sleuth:1.0.0.BUILD-SNAPSHOT')
compile('org.springframework.cloud:spring-cloud-starter-zipkin:1.0.0.BUILD-SNAPSHOT')

Are they the correct ones? And am I correct that this is a bug, meaning that the intention is to never report if the Span says "no"?

**Comment by marcingrzejszczak** [comment]
If you use this one - `compile('org.springframework.cloud:spring-cloud-starter-zipkin:1.0.0.BUILD-SNAPSHOT')` then you don't need Sleuth.

The idea is that this particular span will not be sent to zipkin. However all the tracing information will get passed. We want you to for example be able to see for a particular trace-id all the logs in Kibana or sth like that.

**Comment by billybong** [comment]
So you're saying is that by design traces "always" gets reported to Zipkin irregardless of your Sampler decision?
This will generate quite a lot of unnecessary traffic and seems unintuitive.
Say that you're using the default percentage based Sampler. It will still send a lot of requests to your Zipkin server and is probably not what the user expects.

Is there any configuration you could use to shut off reporting completely? Theoretically I could do the same check in a custom zipkinreporter that wraps the default http one, but that seems both risky (say I've switched thread by now and dont have the RequestContext) and unnecessary since I want to make the decision as fast as possible.

**Comment by marcingrzejszczak** [comment]
No - it will not send them to Zipkin but it will propagate the headers between applications.

**Comment by billybong** [comment]
Ok, so then you consider the issue as a bug as the ZipkinSpanReporter actually gets called from ZipkinSpanListener.serverSend()?

Just to clarify, I'm seeing the behaviour that the traces do get reported to Zipkin even though my Sampler returns false.

**Comment by marcingrzejszczak** [comment]
So yeah most likely sth's wrong. I think we should call `ZipkinSpanReporter` only if the span has the `exportable` flag. CC @dsyer @adriancole

**Comment by billybong** [comment]
Ok, great. I'd guess that the problem is a missing check for isExportable() in ZipkinSpanListener.serverSend(...).

**Comment by marcingrzejszczak** [comment]
Yeah - my bad. https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-stream/src/main/java/org/springframework/cloud/sleuth/stream/StreamSpanReporter.java#L73 Here it's done properly. I'll file a fix in a second.
