### ISSUE TITLE
Trace info is not passed when ThreadPoolTaskExecutor.getThreadPoolExecutor() is used

### ISSUE THREAD

**Issue by Nazukin-Dmitry** [spring-cloud/spring-cloud-sleuth#2240]
**Describe the bug**
Spring Cloud Sleuth: 3.1.1

Underlying `ThreadPoolExecutor` from auto configured `ThreadPoolTaskExecutor` is not wrapped by sleuth, so when I use underlying executor then I lose initial trace id.

**Sample**
```
@Service
public class SomeService {

    @Autowired
    private ThreadPoolTaskExecutor taskExecutor;
    
    public void run() throws ExecutionException, InterruptedException {
        Future<?> helloWorld = taskExecutor.getThreadPoolExecutor().submit(() -> log.info("Hello world"));
        helloWorld.get();
    }
```

**Comment by marcingrzejszczak** [comment]
You can wrap the `taskExecutor.getThreadPoolExecutor()` result in a trace representation manually

**Comment by Nazukin-Dmitry** [comment]
@marcingrzejszczak Maybe `LazyTraceThreadPoolTaskExecutor.getThreadPoolExecutor()` could wrap executor service and return `TraceableExecutorService`?
https://gitter.im/spring-cloud/spring-cloud-sleuth?at=639f074b3daaa326ba8dc233

**Comment by marcingrzejszczak** [comment]
Care for a PR?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Nazukin-Dmitry** [comment]
@marcingrzejszczak I found that `ThreadPoolTaskExecutor.getThreadPoolExecutor` should to return instance of class `ThreadPoolExecutor`.
```
public ThreadPoolExecutor getThreadPoolExecutor() throws IllegalStateException
```
So idea to return `TraceableExecutorService` from `LazyTraceThreadPoolTaskExecutor.getThreadPoolExecutor()` didn't work, because `TraceableExecutorService` is not child of `ThreadPoolExecutor`.

**Comment by marcingrzejszczak** [comment]
Hmm so wrapping `taskExecutor.getThreadPoolExecutor()` in a trace representation won't work?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
