### ISSUE TITLE
cassandra instrumentation: spans for prepare method never ends

### ISSUE THREAD

**Issue by alex-kormukhin** [spring-cloud/spring-cloud-sleuth#2244]
**Describe the bug**
Sleuth 3.1.5.

In cassandra instrumentation spans for "execute*" method ends in [TraceRequestTracker](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/cassandra/TraceRequestTracker.java), but for ["prepare*"](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/cassandra/TraceCqlSessionInterceptor.java#L88-L99) method span never ends. TraceRequestTracker does not intercept results for prepare methods.

![image](https://user-images.githubusercontent.com/99888299/211634620-0864c1f6-d7fa-4c87-a15a-5dc9c0bb98de.png)

**Comment by marcingrzejszczak** [comment]
@mp911de do you recall this problem? Most likely we will have the same one in Spring Data Cassandra if it is here in Sleuth

**Comment by mp911de** [comment]
Good catch. That's fixed in Spring Data Cassandra already:

https://github.com/spring-projects/spring-data-cassandra/blob/f0f6895ebb1586ed2bd34bdfab8d793ea9829c5b/spring-data-cassandra/src/main/java/org/springframework/data/cassandra/observability/CqlSessionObservationInterceptor.java#L76-L96

**Comment by marcingrzejszczak** [comment]
Please upgrade to [Micrometer Tracing](https://docs.micrometer.io/tracing/reference/). Spring Cloud Sleuth is feature complete and out of OSS support.
