### ISSUE TITLE
Spring boot 2.6.6 + spring-cloud 2021.0.5 are not fully compatible with apache-kafka-client 3.0.1

### ISSUE THREAD

**Issue by mpashka** [spring-cloud/spring-cloud-sleuth#2248]
**Describe the bug**
**Spring cloud 2021.0.5** reports it is [compatible with spring boot 2.6.6|https://spring.io/projects/spring-cloud#adding-spring-cloud-to-an-existing-spring-boot-application].
**Spring boot 2.6.6** links to [apache-kafka-client 3.0.1|https://github.com/spring-projects/spring-boot/blob/v2.6.6/spring-boot-project/spring-boot-dependencies/build.gradle#L1019]
**Spring cloud 2021.0.5** links to [spring-cloud-sleuth version 3.1.5|https://github.com/spring-cloud/spring-cloud-release/blob/v2021.0.5/spring-cloud-dependencies/pom.xml#L31]
**Spring cloud sleuth 3.1.5** links to [zipkin.brave version 5.13.9|https://github.com/spring-cloud/spring-cloud-sleuth/blob/v3.1.5/spring-cloud-sleuth-dependencies/pom.xml#L45]
**Brave version 3.1.5** links to [zipkin-reporter-bom version 2.16.3|https://mvnrepository.com/artifact/io.zipkin.brave/brave-bom/5.13.9]
**Zipkin-reporter-bom version 2.16.3** links to [zipkin-sender-kafka version 2.16.3|https://mvnrepository.com/artifact/io.zipkin.reporter2/zipkin-reporter-bom/2.16.3]
**Zipkin-sender-kafka version 2.16.3** links to [apache-kafka-client 2.6.0|https://mvnrepository.com/artifact/io.zipkin.reporter2/zipkin-sender-kafka/2.16.3]

And **zipkin-sender-kafka version 2.16.3** is incompatible with **apache-kafka-client 3.0.1** that is used by spring boot 2.6.6 because originally zipkin-sender-kafka uses incompatible apache-kafka-client 2.6.0:
org.apache.kafka.clients.admin.Admin#close(long, java.util.concurrent.TimeUnit) method doesn't exist in 3.0.1 and is used in zipkin-sender-kafka:
[if (adminClient != null) adminClient.close(1, TimeUnit.SECONDS);|https://github.com/openzipkin/zipkin-reporter-java/blob/2.16.3/kafka/src/main/java/zipkin2/reporter/kafka/KafkaSender.java#L309]

Actually there is comment there in zipkin-sender-kafka source: 
[Intentionally using deprecated method to avoid pinning newer Kafka client|https://github.com/openzipkin/zipkin-reporter-java/blob/2.16.3/kafka/src/main/java/zipkin2/reporter/kafka/KafkaSender.java#L308]

That is not zipkin-sender-kafka bug - because zipkin-sender-kafka 2.16.3 uses kafka-client 2.6.0. This is not spring-boot but because spring boot doesn't have zipkin-sender-kafka dependency.

The problem is currently zipkin-sender-kafka doesn't have version compatible with apache-kafka-client 3.0.1.

**Sample**
Not sure if sample is needed here since it is dependency problem.

**Comment by marcingrzejszczak** [comment]
I think you should file this issue then in Zipkin so that they provide the compatible version?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
