### ISSUE TITLE
Response Time of capture  mongoDB  while do find operation not correct

### ISSUE THREAD

**Issue by desertTown** [spring-cloud/spring-cloud-sleuth#2249]
**Describe the bug**
while I do findAll operation with mongoTemplate, I found the total response time used a few hundred milliseconds, , but the response time of "findAll" always used less than 1 ms, even though I had already inserted 90000 records into MongoDB before

SpringBoot
2.6.9
SpringCloud
2021.0.0
![image](https://user-images.githubusercontent.com/17807898/212837870-3a1f63ee-012d-40e1-a913-e3eb1c8368f9.png)
![image](https://user-images.githubusercontent.com/17807898/212839144-4ed7844b-f268-4b5a-87dc-888592864d1d.png)

**Sample**

here is the sample project, and please read the README inside the project, it will show you how to reproduce the issue
[DBTracingTest.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/10432469/DBTracingTest.zip)

```
1. mvn compile
   mvn spring-boot:run
2. insert data
>    curl --location --request POST 'http://localhost:8081/mongodb/insertBatch'
3. findAll data
> curl --location --request GET 'http://localhost:8081/mongodb/findAll'
```

**Comment by marcingrzejszczak** [comment]
@mp911de do we have the same problem in Spring Data?

**Comment by marcingrzejszczak** [comment]
Please upgrade to [Micrometer Tracing](https://docs.micrometer.io/tracing/reference/). Spring Cloud Sleuth is feature complete and out of OSS support.
