### ISSUE TITLE
Support multiple `SpanTag`s

### ISSUE THREAD

**Issue by trung** [spring-cloud/spring-cloud-sleuth#2250]
Right now, there's only one `SpanTag` per argument. It would be great to have `SpanTags` which contains an array of `SpanTag`.

```java
@interface SpanTags {
  SpanTag[] values();
}
```

The main use case is that I'd like to tag subset of fields from an object being passed to the method. E.g.:

```java
public void methodA(@SpanTags(
values = {
  @SpanTag(key = "tag1", expression = "#{obj.field1}"),
  @SpanTag(key = "tag2", expression = "#{obj.field2}")
}) MyObject obj) {
...
}
```

**Comment by jonatan-ivanov** [comment]
This sounds somewhat complicated (and it really hurts readability) to me so I would recommend adding tags in the method instead: `span.tag("tag1", obj.field1);`

Btw Sleuth is feature complete and new features will be added to Micrometer Tracing, see the docs about this: https://spring.io/projects/spring-cloud-sleuth. Could you please open an issue in Micrometer Tracing instead?
