### ISSUE TITLE
Trace & Span ID are showing in local spring boot logs but not in AWS ECS Cloud Watch Logs.

### ISSUE THREAD

**Issue by jaganm2018** [spring-cloud/spring-cloud-sleuth#2252]
**Describe:** My application is spring-boot application. would like to add traceId to logs to my application. For that I added below sleuth 3.1.4 to pom.xml. Locally it was showing span & trace ID but not in AWS ECS clogs. 
1. spring-boot version: 2.6.6
2. Spring-cloud-sleuth: 3.1.4

When running spring boot application locally, it's showing traceID & SpanId in the logs. But same application deployed into AWS ECS, those traceId & SpanId are showing in the cloud watch logs. 

and same traceId should display in downstream applications also. 

Note: Tried lot of ways but not helpful. Please suggest/share any sample.

Please suggest and let me know if you need any more help.

Thanks in advance.

**Comment by jonatan-ivanov** [comment]
>Locally it was showing span & trace ID but not in AWS ECS clogs.

This means that Sleuth works, it is able to inject the tracing data to your logs, whatever happens after is out of control of Sleuth.

Here's what I think:
- Either you have different configuration in the environment where you use CloudWatch and Sleuth is not configured properly there -> Sync your config
- Or Sleuth is configured properly but something removes the tracing information (I guess this is unlikely) -> Contact AWS support

**Comment by jaganm2018** [comment]
shall i add this configuration spring.sleuth.propagation.type=aws. will it helps?

**Comment by jonatan-ivanov** [comment]
No, I don't think so but I tried to explain above what would help (check your config first, if identical, ask AWS support if they process logs in any way).

**Comment by jaganm2018** [comment]
ok sure. thanks let me check and get back to you

**Comment by jaganm2018** [comment]
My AWS team saying, don't know the reason why it's picking up. do you have any document about to configure the logs from cloud watch mainly this traceid logs.

**Comment by jaganm2018** [comment]
> spring.sleuth.propagation.type=aws

after added this, it's showing me traceId & spanId in the cloud watch logs. Thanks
