### ISSUE TITLE
Sleuth is not working out of box with spring webflux

### ISSUE THREAD

**Issue by MMahendravarman** [spring-cloud/spring-cloud-sleuth#2257]
Using spring cloud version 2021.0.5 .

**Comment by MMahendravarman** [comment]
[Uploading Sleuth_reactive.zip…]()

**Comment by marcingrzejszczak** [comment]
Please provide any details why is it not working and how we can reproduce the problem

**Comment by MMahendravarman** [comment]
Hi ,

Have uploaded the code . I added new fields but it is not enabled in the log

spring:
  application:
    name: my-app-api
  sleuth:
    baggage:
      correlation-enabled: true
      correlation-fields: correlationID
      remote-fields: correlationID    
log:
    slf4j:
      enabled: true
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:-}},%X{correlationID:-}]"
  level:
    org:
      springframework: info

**Comment by MMahendravarman** [comment]
> Uploading Sleuth_reactive.zip…

Please check the attached code

**Comment by marcingrzejszczak** [comment]
I'm on my mobile phone and can't read the project. Are you using boot 3?

**Comment by marcingrzejszczak** [comment]
Also your attached code actually redirects to  this issue. Please check the sleuth samples https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples for reference samples

**Comment by MMahendravarman** [comment]
Yes I am using boot 3 . Do you have any samples to use custom trace id ?Also if the custom trace id is not part of request header it needs to manually created and added for tracing.

**Comment by jonatan-ivanov** [comment]
If you are using Boot 3, you should use [Micrometer Tracing](https://micrometer.io/docs/tracing) instead of Sleuth, see the docs: https://spring.io/projects/spring-cloud-sleuth
