### ISSUE TITLE
TraceContext is null in rxjava3 and hence the traceability of the request across all the threads is lost 

### ISSUE THREAD

**Issue by Malika-Mindi** [spring-cloud/spring-cloud-sleuth#2258]
**Describe the bug**
springBootVersion = "2.7.5"
springCloudVersion = "2021.0.4"
rxJavaVersion = "3.0.7"

Is there a workaround on how we can fix this. Some suggestions were made to use RxJavaPlugins to propagate TraceContext across Threads . I could not find any code samples doing this . Any help will be much appreciated. 
Thank you

This issue does not exist in rxJavaVersion = "1.3.8"

**Sample**

**Comment by marcingrzejszczak** [comment]
we don't support rx java > 1
