### ISSUE TITLE
Spring Cloud Gateway fails to propagate server and client spans with same traceId

### ISSUE THREAD

**Issue by hugree** [spring-cloud/spring-cloud-sleuth#2259]
**Describe the bug**
I'm using a setup of several microservices running Spring Boot 2.7.5 with one of them being a Spring Cloud Gateway "ingress" service. I've hooked up OpenTelemetry with Open Telemetry Collector and Grafana Tempo consuming the traces.

The services are also running alongside Istio Service Mesh.

Regular Spring microservices are able to properly propagate traces and "inherit" traceIds. Most of them are using HTTP REST calls. 

The problem is with the first in line, which is using Spring Cloud Gateway to route traffic to other services.

After the upgrade to new Spring (2.7.5) and obviously excluding the old brave tracing we've lost the ability to "match" traces of Gateway (server span) and the following client calls. Obviously this also impacts our logging because we get several traceIds handling one call to the gateway in logback too.

```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
            <version>${spring-cloud-starter-sleuth.version}</version>
            <exclusions>
                <!-- Exclude Brave (the default) -->
                <exclusion>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-sleuth-brave</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

It seems that this configuration is not able to properly propagate traceId between handling the call within Spring Cloud Gateway and doing client calls to other services using the same trace context.

Right now we have one traceId for handling the server span and multiple traceIds for each of the downstream client calls.

<img width="1965" alt="image" src="https://user-images.githubusercontent.com/18511093/216758030-6fd097d5-9b0e-47f3-aca0-32d39019e7fa.png">

API Gateway service is running:
```
        <artifactId>spring-cloud-starter-gateway</artifactId>
```

Open Telemetry libraries:
```
        <spring.cloud-version>2021.0.4</spring.cloud-version>
        <spring-cloud-starter-sleuth.version>3.1.6</spring-cloud-starter-sleuth.version>
        <spring-cloud-sleuth-otel-autoconfigure.version>1.1.1</spring-cloud-sleuth-otel-autoconfigure.version>
        <opentelemetry-exporter-otlp-trace.version>1.14.0</opentelemetry-exporter-otlp-trace.version>
```

**Comment by marcingrzejszczak** [comment]
Please upgrade to the latest sleuth 3.1.6 release (it's out of the release train release)

**Comment by hugree** [comment]
@marcingrzejszczak which version do you mean exactly?
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/18511093/216763811-57a571d7-4adb-4500-a16a-9088d479234b.png">

I am using the latest it seems.

**Comment by marcingrzejszczak** [comment]
Turn on the decorate queues reactor wrapping and ensure that you're using the 3.1.6 version of sleuth
