### ISSUE TITLE
Disable Header Forwarding based on Header Name per Client

### ISSUE THREAD

**Issue by romulets** [spring-cloud/spring-cloud-sleuth#2271]
**The Problem:**
In a application with Sleuth enabled every request I create has the headers forwarded silently. 

That, can create silent issues such as the current one I'm facing: my application is forwarding a bad-formatted `Accept-Language` header. On this case, I can't just throw back a 400, I need to fallback to a language and finish my business process.

**Desired Solution**
A configuration to disabled header forwarding per `Header Name` and ideally only for specific clients

**Comment by marcingrzejszczak** [comment]
I don't understand the problem. Where do we forward all headers? Which component does it? Which version of Sleuth are you talking about?

**Comment by romulets** [comment]
So this might be my lack of knowledge on how sleuth works. I'll explain my use case:

we use a `org.springframework.web.reactive.function.client.WebClient` to perform requests to a downstream service.

This library, `spring-webflux` uses sleuth underneath, which in my understanding is what has the knowledge between what my service has gotten as request and requests I'm doing to down stream services.

I saw two StackOverflow questions with similar problems, and both also cited sleuth as the place where something should be configured. 
- [StackOverflow Question 1](https://stackoverflow.com/questions/69796963/spring-sleuth-feign-disable-header-propagation-on-specific-conditions)
- [StackOverflow Question 2](https://stackoverflow.com/questions/59201431/is-it-possible-to-disable-spring-cloud-sleuth-header-propagation-based-on-destin)

Both questions use different clients, but with commonality of sleuth. At the moment, either we have sleuth doing its work or not all, which is not what we want. We would like to control on specific cases if a header is forwarded or not.

But I can't tell you with certainty where this is being done on code level.

We use `org.springframework:spring-webflux:5.3.25`, which uses a bundle of sleuth libraries on version `3.1.7`

I know that we configure the baggage in the following way:

```yaml
  sleuth:
    baggage:
      remote-fields:
        - Accept-Language
        - X-RID
        - Experimentation-Beacon-Id
        - Encrypted-Customer-Id
        - Experiment-Subject-ID
```

That's what makes those fields being forwarded to downstream connections, right?

Is it possible to disable them on code level for specific client/requests?

**Comment by marcingrzejszczak** [comment]
Not on the Sleuth level. You would have to do a filter function on WebClient level to remove the headers

**Comment by romulets** [comment]
Ok, so it's in the interaction between the library and sleuth. Check.

Thank you for your time!
