### ISSUE TITLE
Duplicated spans for cassandra

### ISSUE THREAD

**Issue by maciej-gromul** [spring-cloud/spring-cloud-sleuth#2277]
**Describe the bug**
By default cassandra instrumentation attaches itself to cqlsesion. Because reactivesession wraps around sqlsession and it's being instrumented as well, we're getting spans for the same "requests" twice. Right now to fix that you can simply exclude TraceCassandraAutoConfiguration.class in @SpringBootApplication from autoloading, but it would be nice if those would detect which one should be loaded and when.

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem ? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

Can you also provide the Sleuth version?

**Comment by maciej-gromul** [comment]
Depending on setup it sometimes happens to inserts, sometimes to selects. In our services it happens to both. With this example it mostly occurs on inserts.

![image](https://user-images.githubusercontent.com/89904409/227302756-ba636473-0b1a-418d-86f4-8d40e2561294.png)

https://github.com/maciej-gromul/problems-with-cassandra-autoconfiguration

**Comment by marcingrzejszczak** [comment]
@mp911de do you recall these problems?

**Comment by maciej-gromul** [comment]
When i do breakpoints it registers both CqlSession and ReactiveSession tracing so the problem is most likely somewhere in that area.

**Comment by mp911de** [comment]
Thanks for having a look. There's indeed a risk that the instrumented `CqlSession` serves as underlying object for `ReactiveSession` and that is being used later in `ObservableReactiveSession`. In Spring Data Cassandra, we introduced a `ObservableCqlSessionFactoryBean` accepting `CqlSessionBuilder` to mitigate that risk.

**Comment by maciej-gromul** [comment]
It seems to be closed with issue 1366

**Comment by marcingrzejszczak** [comment]
Really this one https://github.com/spring-cloud/spring-cloud-sleuth/issues/1366 ? It doesn't seem to have anything to do with cassandra

**Comment by maciej-gromul** [comment]
Sorry issue from spring-data-cassandra, my bad https://github.com/spring-projects/spring-data-cassandra/issues/1366

**Comment by marcingrzejszczak** [comment]
Please upgrade to [Micrometer Tracing](https://docs.micrometer.io/tracing/reference/). Spring Cloud Sleuth is feature complete and out of OSS support.
