### ISSUE TITLE
 Shared traceId with skywalking

### ISSUE THREAD

**Issue by Toxa45** [spring-cloud/spring-cloud-sleuth#2279]
Добрый день. 
Подскажите возможно ли синхронизировать traceId со skywalking?
Или можно ли как то изменить traceId для Sleuth?
spring-cloud - 2021.0.5

**Comment by jonatan-ivanov** [comment]
Thank you for the issue, could you please express your thoughts in english?

**Comment by marcingrzejszczak** [comment]
Sleuth is feature complete, you can use Micrometer Observations with Skywalking https://skywalking.apache.org/docs/main/v9.4.0/en/setup/backend/micrometer-observations/

**Comment by Toxa45** [comment]
thanks, consider switching to Micrometer Observations

Can you advise here
https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/application-toolkit-micrometer-1.10/ 
how to connect apm-toolkit-micrometer-1.10, but I don't see it in
 https://mvnrepository.com/

**Comment by marcingrzejszczak** [comment]
Please ask these questions in the SkyWalking slack / stackoverflow / github

**Comment by Toxa45** [comment]
OK, thank you. If you switch to Micrometer Observations, will there be a single traceId with Skywalking? 
Skywalking always creates its own traceId, how it behaves Micrometer Observations?

**Comment by marcingrzejszczak** [comment]
Micrometer Observation uses SkyWalking's Tracer API to create spans and traces. So we are delegating work to Skywalking.

**Comment by Toxa45** [comment]
Thanks, to use Micrometer Observation , you need to go to Spring Boot 3? Version 2.7.5 or earlier not supported?

**Comment by marcingrzejszczak** [comment]
Correct
