### ISSUE TITLE
TraceContext lost in async thread when application shutdown

### ISSUE THREAD

**Issue by wapkch** [spring-cloud/spring-cloud-sleuth#2281]
**Describe the bug**

- Assuming that we have a thread pool Bean:

```
    @Bean
    public Executor customizedExecutor(BeanFactory beanFactory) {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(8);
        executor.setMaxPoolSize(16);
        executor.setAllowCoreThreadTimeOut(true);
        executor.setQueueCapacity(100);
        executor.setThreadNamePrefix("customizedExecutor-");
        executor.setRejectedExecutionHandler(new NewThreadPolicy("newExecutor-"));
        executor.setWaitForTasksToCompleteOnShutdown(true);
        executor.setAwaitTerminationSeconds(60);
        LazyTraceExecutor lazyTraceExecutor = new LazyTraceExecutor(beanFactory, executor);
        executor.initialize();
        return lazyTraceExecutor;
    }
```

- and an @Async method:
```
public void foo() {
  BaggageField field = BaggageField.getByName("xxx");
  field.updateValue("yyy");
  bar();
}
```
```
@Async("customizedExecutor")
public void bar() {
  BaggageField field = BaggageField.getByName("xxx");
  String value = field.getValue();
  // Use value to do something
}
```
So far, all good. 
But when the application shutdown, The baggage field value in method `bar` may not be found, and with the following log:
`Context [689fcd09] is either not refreshed or is closed` logged by `ContextUtil`.
The reason is that when `ContextClosedEvent` is published, ThreadPoolTaskExecutor is still running. But ContextUtil#isContextUnusable method will return true which result in TraceContext lost in async thread.

Is there a solution that can avoid the problem?

**Comment by marcingrzejszczak** [comment]
This feature was never asked for and is not supported and since Sleuth is feature complete we're not planning to add it.
