### ISSUE TITLE
Sleuth TraceId missing in Netty HttpClient WRITE event if same 'reactor-http-nio' thread is used

### ISSUE THREAD

**Issue by syedyusufh** [spring-cloud/spring-cloud-sleuth#2283]
Lately after **Spring Boot 2.7.6** (corresponding netty release), Sleuth TraceId is missing in the **WRITE** event of our custom `LoggingHandler` if same `reactor-http-nio` thread is used. First request using the new thread logs the traceId perfectly, subsequent request is missing the TraceId only for the **WRITE** event. **READ** event is fine.

We are currently on **Spring Boot 2.7.11** with latest Project Reactor and Sleuth dependencies.

```
HttpClient.create()
	.doOnRequest((request, connection) -> connection.addHandlerFirst(loggingHandler))
```

```
@Component
public class PayloadLogger extends LoggingHandler {

	@Autowired
	public PayloadLogger() {

		super(HttpClient.class, DEBUG, SIMPLE);
	}

  @Override
  protected String format(ChannelHandlerContext ctx, String event, Object arg) {

	if (arg instanceof ByteBufHolder byteBufHolder && StringUtils.equalsAny(event, WEBCLIENT_LOGGING_READ_EVENT, WEBCLIENT_LOGGING_WRITE_EVENT)) {

		var logMsg = byteBufHolder.content().toString(UTF_8);

		// WRITE
		if (WEBCLIENT_LOGGING_WRITE_EVENT.equals(event))
			return "Request Payload: " + logMsg;

		// READ
		if (WEBCLIENT_LOGGING_READ_EVENT.equals(event)) {
```

**Comment by marcingrzejszczak** [comment]
cc @OlegDokuka @violetagg does this ring any bell?

**Comment by violetagg** [comment]
This is not using Reactor Netty <-> Brave integration so I don't think it is related to Reactor Netty. It appears that this is not working after Spring Boot 2.7.6

**Comment by syedyusufh** [comment]
@marcingrzejszczak @violetagg  Sorry, it uses `ReactorClientHttpConnector` when the `WebClient` object is built

```
@Bean
public ReactorNettyHttpTracing reactorNettyHttpTracing() {
	return ReactorNettyHttpTracing.create(httpTracing);
}

public ReactorClientHttpConnector createReactorClientHttpConnector(final Integer timeout) {

	var httpClient = createHttpClient(timeout);
	return new ReactorClientHttpConnector(reactorNettyHttpTracing().decorateHttpClient(httpClient));
}
```

**Comment by violetagg** [comment]
@syedyusufh Can you provide a reproducible example?

**Comment by syedyusufh** [comment]
@violetagg I tried creating a sample project without the actual application functionality, however it worked fine in the sample project :(
I debugged further and found NoopSpan created in the real application (where the issue still exists) and RealSpan in the sample application. Could that be a reason? Both the applications match Sleuth dependency and configurations

Please suggest a way to debug this further.

**Comment by marcingrzejszczak** [comment]
Please upgrade to [Micrometer Tracing](https://docs.micrometer.io/tracing/reference/). Spring Cloud Sleuth is feature complete and out of OSS support.
