### ISSUE TITLE
Autoconfigurable correlationScopeDecorator doesn't use builder from Spring Context

### ISSUE THREAD

**Issue by akrikheli** [spring-cloud/spring-cloud-sleuth#2284]
The correlationScopeDecorator creates CorrelationScopeDecorator.Builder via **new** operator and fully ignores builder bean:

https://github.com/spring-cloud/spring-cloud-sleuth/blob/fc5f26a11fe3a1e4de3b542a3485cc13525132a7/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/brave/BraveBaggageConfiguration.java#L207

Looks like bug because there's conditional 
`@ConditionalOnBean(CorrelationScopeDecorator.Builder.class)`
over this bean.

Thus there's no way to customize builder for correlationScopeDecorator (for example if we want to add custom SingleCorrelationField with flushing on update).

I suggest to inject the builder as method parameter in java configuration of correlationScopeDecorator bean and use it.

**Comment by marcingrzejszczak** [comment]
fixed via https://github.com/spring-cloud/spring-cloud-sleuth/pull/2285
