### ISSUE TITLE
HandlerInterceptor section in document is outdated. `TraceHandlerInterceptor` disappeared.

### ISSUE THREAD

**Issue by hojongs** [spring-cloud/spring-cloud-sleuth#2287]
**Describe the bug**

https://github.com/spring-cloud/spring-cloud-sleuth/blob/a5eaa0ad6fabf94c60084eba44d7ba6a3401170f/docs/src/main/asciidoc/integrations.adoc#handlerinterceptor

In the document, `TraceHandlerInterceptor` is mentioned but it doesn't exist.

> Since we want the span names to be precise, we use a TraceHandlerInterceptor that either wraps an existing HandlerInterceptor or is added directly to the list of existing HandlerInterceptors. ...

**Comment by marcingrzejszczak** [comment]
Yikes! Are you willing to file a PR to remove this?

**Comment by hojongs** [comment]
Ok, let me make a PR. 😄
