### ISSUE TITLE
Clarification on Sleuth and Feign with Hystrix

### ISSUE THREAD

**Issue by nickcodefresh** [spring-cloud/spring-cloud-sleuth#229]
Does Sleuth support Feign with Hystrix? I've read some conflicting information, and just wanted to find a concise answer. 

At the moment I'm having to disable it with the following, otherwise I get an error in the Feign call.

```
feign:
    hystrix:
        enabled: false
```

**Comment by marcingrzejszczak** [comment]
Yes we do support Feign with Hystrix. http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_hystrix

**Comment by nickcodefresh** [comment]
How come I get an exception then? My feign interfaces are basic and don't have any hystrix annotations or objects in their specification.

**Comment by spencergibb** [comment]
@nickcodefresh it would be most helpful if you told us what exception you get.

**Comment by nickcodefresh** [comment]
Yes sorry, I wasn't at my computer. My bad. I'll upload one tomorrow
