### ISSUE TITLE
`TraceableExecutorService` does not terminate tests when wrapping the `ForkJoinPool.commonPool()`

### ISSUE THREAD

**Issue by TheBestPessimist** [spring-cloud/spring-cloud-sleuth#2291]
**Describe the bug**
When wrapping  `ForkJoinPool.commonPool()` and running tests, the tests do not finish because the pool does not shut down.

sample code:
```kotlin
@Configuration
class CaffeineExecutorFactory {
	@Bean("caffeineExecutor")
	fun caffeineExecutor(beanFactory: BeanFactory): ExecutorService {
		println("created")
        return TraceableExecutorService.wrap(beanFactory, ForkJoinPool.commonPool()) // ❌ when running the tests, the tests do not finish because the pull does not shut down
	}
}
```
It seems we're stuck inside `TraceableExecutorService.close`, because `ForkJoinPool.awaitTermination` always returns `false`.
![image](https://github.com/spring-cloud/spring-cloud-sleuth/assets/4482210/6472c2ce-9373-4d20-a150-38a76d3f6ab7)

**Sample**
[demo.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/11542739/demo.zip)

**Comment by marcingrzejszczak** [comment]
Are you sure that the executor's `shutdown` method is being called?

**Comment by TheBestPessimist** [comment]
i dont know that/don't remember. i decided the easiest sollution is to use another thread pool (cached thread pool) and not the common FJP one. I remember retrying the FJP again sometime in november and the bug was still there. 
I'm not working on this project anymore though.

**Comment by marcingrzejszczak** [comment]
Thanks for the update
