### ISSUE TITLE
Error release notes

### ISSUE THREAD

**Issue by Linda-pan** [spring-cloud/spring-cloud-sleuth#2294]
**Describe the bug**
The release notes for version 3.1.7 of the `spring-cloud-sleuth-instrumentation` module contain a bug where `ReflectionUtils` cannot access members of the `TraceSessionRepository` class, as reported in https://github.com/spring-cloud/spring-cloud-sleuth/issues/2267. However, this issue was fixed in version 3.1.8, despite the fact that it occurred in version 3.1.7.
![image](https://github.com/spring-cloud/spring-cloud-sleuth/assets/18511489/1fa44c2e-1d7a-4f38-a5dd-2392d93da158)

**Comment by marcingrzejszczak** [comment]
Fixed, thanks for the information
