### ISSUE TITLE
TraceContext will be lost when exiting @Transactional code

### ISSUE THREAD

**Issue by Kurok1** [spring-cloud/spring-cloud-sleuth#2296]
**Describe the bug**
I try to create a Span in my business code, such as:
```java
    @Transactional
    public void newTraceWithTransaction() {
        ScopedSpan scopedSpan = tracer.startScopedSpan("new-trace");
        logger.info("has create new trace : {}", scopedSpan.context().traceId());
        //other code...
    }
```
When these codes are executed, I try to get the `CurrentTraceContext` on the current thread. but get `null`
```java
     this.bizService.newTraceWithTransaction();
     //get current trace context
     CurrentTraceContext currentTraceContext = tracer.currentTraceContext();
     TraceContext context = null;
     if (currentTraceContext != null)
         context = currentTraceContext.context();
     if (context == null)
         logger.error("current trace not found ");
     else
         logger.info("current trace [id={}]", context.traceId());
```
the console output is 
```
2023-06-09 12:40:02.254  INFO [,c430caeb3e6280e3,66c3f500ffc2256a] 10615 --- [           main] com.example.sleuth.BizService            : has create new trace : c430caeb3e6280e3
2023-06-09 12:41:24.347 ERROR [,,] 10615 --- [           main] c.example.sleuth.SleuthDemoApplication   : current trace not found 
2023-06-09 12:41:38.570  WARN [,,] 10615 --- [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m24s892ms).
```
So I can't propagate the traceId I just generated to other components like `RestTemplate`

Spring Cloud Sleuth Version Information:
```
org.springframework.boot : spring-boot-starter-parent : 2.7.9
org.springframework.cloud : spring-cloud-starter-sleuth : 3.1.8
```

**Sample**
https://github.com/Kurok1/spring-sleuth-propagate-demo
You can run the `SleuthDemoApplication` directly (requires local mysql support)

**Comment by marcingrzejszczak** [comment]
> 2023-06-09 12:41:38.570  WARN [,,] 10615 --- [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m24s892ms).

no wonder - you have switched threads here. You would need to wrap the component that is responsible for switching threads.

Also you start a scoped span in a transaction and never finish it. You should create a span in main method, put it in scope, then create a child span in transactional method and close it when the method finishes. Instead your leaking thread local information.

**Comment by Kurok1** [comment]
This is a detection alert from Hikari and has nothing to do with my bug. My calls are all synchronous, there is no thread switching, so you can directly run the demo I provided

**Comment by Kurok1** [comment]
I I found the reason, because org.springframework.cloud.sleuth.instrument.tx.TracePlatformTransactionManager opened a Root Span when entering things, and closed it when exiting. So the span I created in the transaction was also closed together.
