### ISSUE TITLE
I want to propagate TraceId to all places where parallelStream() and CustomForkJoinPool is used.

### ISSUE THREAD

**Issue by petercheon** [spring-cloud/spring-cloud-sleuth#2297]
I would like to know how to propagate the TraceId within the Java Stream API in Spring Cloud Sleuth.

In the code below, the trace_id is not propagated, and each client ends up having an individual TraceId.

```java
TestForkJoinPool testForkJoinPool = new TestForkJoinPool(10);
Span span = tracer.nextSpan(tracer.currentSpan());

testForkJoinPool.submit(() -> {
    try (SpanInScope ignored = tracer.withSpan(span)) {
        IntStream.range(1, 20).parallel().forEach(idx -> {
            httpClient.get(1000L);
        });
    } finally {
        span.end();
    }
}).get();
```

However, if we modify the above code as shown below, the TraceId is propagated.

```java
TestForkJoinPool testForkJoinPool = new TestForkJoinPool(10);
Span span = tracer.nextSpan(tracer.currentSpan());

testForkJoinPool.submit(() -> {
    IntStream.range(1, 20).parallel().forEach(idx -> {
        try (SpanInScope ignored = tracer.withSpan(span)) {
            httpClient.get(1000L);
        } finally {
            span.end();
        }
    });
}).get();
```

Unfortunately, applying SpanInScope to all existing Stream API code as mentioned above has its limitations. Is there a way to inject SpanInScope with minimal modifications to the existing Stream API code?

Thank you.

**Comment by jonatan-ivanov** [comment]
Have you tried [`LazyTraceExecutor`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceExecutor.java)?

**Comment by petercheon** [comment]
@jonatan-ivanov 

Thank you for your feedback.
As you mentioned, I used LazyTraceExecutor as you suggested, but I still confirmed that the span is not propagated.
I have verified that the span is propagated correctly when not using parallel().

```java
    @Bean(name = "peterPool")
    @Lazy
    public Executor getCustomForkJoinPool(Tracer tracer) {
        final ForkJoinPool.ForkJoinWorkerThreadFactory factory = pool -> {
            final ForkJoinWorkerThread worker = ForkJoinPool.defaultForkJoinWorkerThreadFactory.newThread(pool);
            worker.setName("peterPool" + worker.getPoolIndex());
            return worker;
        };

        return new LazyTraceExecutor(beanFactory,
                new ForkJoinPool(Runtime.getRuntime().availableProcessors(), factory, null, true));
    }
```

```java

    private final Executor peterPool;

    @GetMapping("/test")
    public String test() throws ExecutionException, InterruptedException {
        peterPool.execute(() -> {
            IntStream.range(1, 20).parallel().map(idx -> {
                httpClient.get(1000L);
                return idx;
            }).sum();
        });

        return "test";
    }
```

Thank you

**Comment by jonatan-ivanov** [comment]
Your example does not use `LazyTraceExecutor`. You create a bean of it but the parallel stream does not use it. I checked a few things and I don't see the way using an executor/completion service in parallel streams. So I guess the solution is you need to instrument it on your own (basically what [LazyTraceExecutor](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceExecutor.java)) does.
