### ISSUE TITLE
Missing traceId when using spring-cloud-starter-stream-rabbit consumer listeners.

### ISSUE THREAD

**Issue by Toxa45** [spring-cloud/spring-cloud-sleuth#2300]
Good afternoon.
Missing traceId when using spring-cloud version 2021.0.5 when using spring-cloud-starter-stream-rabbit consumer listeners on errors like validation. spring-cloud-starter-sleuth version is pulling up 3.1.5

Вот пример сервиса https://github.com/Toxa45/Logging_Sleuth

If you send the following message to the "queue.test" queue
{
   "model":null
}

то в логах видим сообщение без traceId
![Log_Not_TraceId](https://github.com/spring-cloud/spring-cloud-sleuth/assets/57655161/b6b16767-2ad1-4bd4-abc4-fb86151b7390)

Tried earlier and later versions org.springframework.cloud:spring-cloud-starter-sleuth. Works only in version 2.2.8.RELEASE
![Log_TraceId](https://github.com/spring-cloud/spring-cloud-sleuth/assets/57655161/42644181-929b-4a10-8519-7d2b44fee0c6)

**Comment by Toxa45** [comment]
Can spring-cloud-starter-sleuth version 2.2.8.RELEASE be used with spring-cloud version 2021.0.5

**Comment by marcingrzejszczak** [comment]
You should not manually pick versions of cloud projects. You should use the release train. `2021.0.5` uses Sleuth 3.x.

**Comment by Toxa45** [comment]
Initially, I did not choose manually, but in that version traceId is not logged. I decided to test the work with other versions.
In versions of uses Sleuth 3.x. an error is observed.

**Comment by Toxa45** [comment]
And in version 2.2.8.RELEASE everything is logged correctly, so I asked if we can use it until the error is fixed.

**Comment by marcingrzejszczak** [comment]
Please upgrade to use [Micrometer Tracing](https://docs.micrometer.io/tracing/reference/). Spring Cloud Sleuth is feature complete and out of support.
