### ISSUE TITLE
Tracing support for Reactive Kafka (Using KafkaSender and KafkaReceiver)

### ISSUE THREAD

**Issue by rush1697** [spring-cloud/spring-cloud-sleuth#2301]
I don't find any implementation which support tracing using reactive kafka (`KafakaSender` and `KafkaReceiver`).

**Comment by rush1697** [comment]
is sleuth support reactive kafka implementation for tracing?

**Comment by marcingrzejszczak** [comment]
[Yes we do](https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/integrations.html#sleuth-kafka-integration)
