### ISSUE TITLE
investigate dependency graph issues

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#231]
I've heard from @joshlong and @marcingrzejszczak that sleuth'd traces aren't showing up in zipkin's UI dependency graph view.

The dependency graph view is special cased for zipkin "server" annotations. That's due to a number of reasons, including keeping the rules simple, the input data small and avoiding double-counting.

The following patterns will trigger nodes in the dependency tree.
* server span
  * A span has a SERVER_RECV("sr") annotation, but no CLIENT_ADDR("ca") 
* uninstrumented client+server span
  * A span has a CLIENT_ADDR("ca") binary annotation and a SERVER_RECV("sr") annotation
  * A span has both CLIENT_ADDR("ca") and SERVER_ADDR("sa") binary annotations
* client-only span
  * A span has a SERVER_ADDR("sa") binary annotation, but no SERVER_RECV("sr")

If sleuthed spans don't produce combinations like above, stop here, and try and figure out why or what's missing.

If sleuthed spans look right per above, yet no dependency graph is showing up in either mem or mysql storage... 

catch a trace via `http://zipkinhost:9411/api/v1/trace/your_trace_id` and ask about it in https://gitter.im/openzipkin/zipkin, preferably a pared down trace (vs one with a 100+ spans).

If you want details, there are a number of tests that account for behaviors, addressing specific instrumentation use cases.
https://github.com/openzipkin/zipkin-java/blob/master/zipkin/src/test/java/zipkin/internal/DependencyLinkSpanTest.java
https://github.com/openzipkin/zipkin-java/blob/master/zipkin/src/test/java/zipkin/internal/DependencyLinkerTest.java
https://github.com/openzipkin/zipkin-java/blob/master/zipkin/src/test/java/zipkin/DependenciesTest.java

**Comment by adriancole** [comment]
ps added this to try and find a good place to document this in a way that doesn't require familiarity with java https://github.com/openzipkin/openzipkin.github.io/issues/13

**Comment by marcingrzejszczak** [comment]
There are still issues in messaging and Zuul

**Comment by marcingrzejszczak** [comment]
Related to: https://github.com/openzipkin/zipkin-java/pull/144

**Comment by marcingrzejszczak** [comment]
Messaging fixed in https://github.com/spring-cloud/spring-cloud-sleuth/commit/caba82c740dbd8a4a0b7b1dcc25366c86d0f1516

Zuul fixed in https://github.com/spring-cloud/spring-cloud-sleuth/commit/b3c78c139dab25af6420d5ed43b5dc6c98221263
