### ISSUE TITLE
LazyTraceThreadPoolTaskExecutor.getQueueSize() does not call a delegate and always returns 0

### ISSUE THREAD

**Issue by vg2902** [spring-cloud/spring-cloud-sleuth#2315]
**Describe the bug**
When enabled, Sleuth instruments `ThreadPoolTaskExecutor` beans by wrapping them in [`LazyTraceThreadPoolTaskExecutor`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/v3.1.9/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceThreadPoolTaskExecutor.java) proxies.
Unlike the other `ThreadPoolTaskExecutor` methods, `LazyTraceThreadPoolTaskExecutor` for some reason does not 
override/delegate `getQueueSize()`, which is always returning 0.

**Sample**

[sleuth-instrumentation-thread-pool-bug.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/14073986/sleuth-instrumentation-thread-pool-bug.zip)

It is a simple Spring Boot application with an async method and custom `ThreadPoolTaskExecutor` for it. 
There is a test emulating a concurrent workload by submitting more tasks than the custom executor can process simultaneously.

The test runs twice, with Sleuth on and off respectively.

Just execute `mvn clean verify`

**Comment by marcingrzejszczak** [comment]
Hey thanks for filing the issue. Are you willing to file a pr with a fix and a test? 🙂

**Comment by vg2902** [comment]
> Hey thanks for filing the issue. Are you willing to file a pr with a fix and a test? 🙂

Sure, just raised one:

https://github.com/spring-cloud/spring-cloud-sleuth/pull/2316

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-sleuth/commit/20a9aa6342b3688e55d88f73dc0c6293c80a2856
