### ISSUE TITLE
Need documentation for collecting data using baggage.

### ISSUE THREAD

**Issue by Hari-Nikesh-R** [spring-cloud/spring-cloud-sleuth#2322]
How can I get the baggageField in sleuth 2.3.3.RELEASE for spring boot 2.3.4. 

Initially I used slueth version 1.3.3.RELEASE, where I had the method called span.getBaggage(key) and span.setBaggage(key, value). But in Sleuth 2.3.3 version. I was not able find the method and struggling to get the proper documentation to follow and get the baggage field. Please kindly help on this by providing the specific documentation for collecting data using baggage.

**Comment by jonatan-ivanov** [comment]
None of those versions are supported anymore, also Boot 2.x will go out of support in about a week: https://spring.io/projects/spring-boot#support, please try to upgrade.
