### ISSUE TITLE
TraceIds feature for a Request tarvelling across, doesn't seem working. TraceIds are different across a travelling request

### ISSUE THREAD

**Issue by harshithgandhamMS** [spring-cloud/spring-cloud-sleuth#2331]
We have updated springboot to version 2.7.14 and org.springframework.cloud:spring-cloud-dependencies to version 2021.0.3.

Post that, we noticed that the traceIds for a travelling request are different.

For example, if UI hits /a api of service-A and /a api of service-A hits /b api of service-B(using HttpClient or Webclient), then the traceIds for requests /a and /b are different.

we use spring sleuth to transfer traceIds between microservice calls and it seems to be broken.

We tried with all versions of spring-cloud-dependencies from 2021.0.3(sleuth version 3.1.3) to 2021.0.8(sleuth version 3.1.9) and couldn't see it working.

Can someone pls help on the same.

Here are the sample code snippets:
(pasting a sample code as pasting original Project src code is not allowed) 

Service-A: (runs on 8082)

 @GetMapping(value = "/sampleAsset")
        public ResponseEntity<Object> getSample() throws DataSetWorkflowException {
            WebClient.Builder webClientBuilder = WebClient.builder();
             webClientBuilder
                 .build().get().uri("http://localhost:8081/activity/acceptanceTestSync/pubSubGroupId")
                 .retrieve().bodyToMono(Object.class).block();
            return ResponseEntity.status(HttpStatus.OK).body("{}");
        }

It internally hits an api /pubSubGroupId of another Service-B running on 8081

When I hit, the api http://localhost.ms.com:8082/sampleAsset from postman,
Here are the logs in both Services:

Service-A:
2023-12-12 14:02:34.146 DEBUG [Service-A,423e8153db602879,423e8153db602879] [profile=test] 27192 --- [nio-8082-exec-1] o.s.w.f.CommonsRequestLoggingFilter      : Before request [GET /sampleAsset, client=127.0.0.1]
2023-12-12 14:02:34.492 DEBUG [Service-A,423e8153db602879,423e8153db602879] [profile=test] 27192 --- [nio-8082-exec-1] o.s.w.f.CommonsRequestLoggingFilter      : REQUEST DATA : GET /sampleAsset, client=127.0.0.1]

Service-B:
 [fdc_activities,e7ef8e8bb2225736,e7ef8e8bb2225736] 33232 --- [nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 3 ms
2023-12-12 14:02:34.368  INFO [Service-B,e7ef8e8bb2225736,e7ef8e8bb2225736] 33232 --- [nio-8081-exec-1] .AcceptanceTestSynchronizationController : Received request GET PubSubGroupId, which is set to: PubSubGroupId(id=sghjhg)

The traceIds which are supposed to be same, are different.
Can someone pls help me on this.

**Comment by marcingrzejszczak** [comment]
This project is out of OSS support (https://spring.io/projects/spring-cloud-sleuth#support). Please check https://tanzu.vmware.com/spring-runtime to get commercial support.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
