### ISSUE TITLE
Not able to set the traceId and spandId which was recieved at the subscriber end in web-socket with stomp message communication.

### ISSUE THREAD

**Issue by yatamraghu7** [spring-cloud/spring-cloud-sleuth#2346]
Hi,

Can someone please explain how I can set the trace-Id and span-Id to current spring cloud sleuth trace context which was received at the subscriber end when my micro-services are communicating with web socket using stomp.
I have tried using the below code snippet but most of the sub methods like newBuilder is deprecated.

Span span = this.tracer.nextSpan(TraceContextOrSamplingFlags.newBuilder()
				.traceIdContext(TraceIdContext.newBuilder()
						.traceId(123L)
						.build())
				.build()).name("foo").start();

Can someone tell me how can I achieve this.

Thanks,
Raghu

**Comment by jonatan-ivanov** [comment]
Sleuth reached the [end of its OSS support](https://spring.io/projects/spring-cloud-sleuth#support) timeline. We encourage to migrate to Micrometer Tracing.

You should not set traceId and spanId manually but you should instrument the server that receives them (check the Propagators in the codebase).
