### ISSUE TITLE
Sleuth - Not setting MDC with new span id when request is sent with WebClient

### ISSUE THREAD

**Issue by pratapjai143** [spring-cloud/spring-cloud-sleuth#2347]
Code to call backend and initialisation as shown below. The sample code is using the spring-cloud-version Hoxton.SR4 , 'org.springframework.boot' version '2.3.1.RELEASE'. Full sample at https://github.com/malika15/sleuth-resttemplate-webclient-comparison
`@EnableAutoConfiguration
@RestController
public class FrontendUsingWebClient {

    @Autowired
    WebClient webClient;
    private Logger log = LoggerFactory.getLogger("FrontendUsingWebClient");

    public static void main(String[] args) {
        SpringApplication.run(FrontendUsingWebClient.class,
            "--spring.application.name=FrontendUsingWebClient",
            "--server.port=8081");
    }

    @Bean
    WebClient webClient() {
        return WebClient.builder().exchangeStrategies(ExchangeStrategies.builder().codecs(c ->
            c.defaultCodecs().enableLoggingRequestDetails(true)).build()
        ).baseUrl("http://localhost:9000").build();
    }

    @RequestMapping("/")
    public Mono<String> callBackend() {
        log.info("Frontend WebClient::Begin");
        Mono<String> response = webClient.get().uri("/api").retrieve().bodyToMono(String.class)
            .doFirst(() -> log.info("Frontend WebClient ::doFirst"))
            .doOnSubscribe(subscription -> log.info("Frontend WebClient::doOnSubscribe"))
            .doOnRequest(value -> log.info("Frontend WebClient::doOnRequest"))
            .doOnSuccess(s -> log.info("Frontend WebClient::doOnSuccess"))
            .doOnEach(stringSignal -> log.info("Frontend WebClient::doOnEach"))
            .doOnNext(s -> log.info("Frontend WebClient::doOnNext"))
            .doAfterTerminate(() -> log.info("Frontend::doAfterTerminate"))
            .doFinally(signalType -> log.info("Frontend WebClient::doFinally"))
            .doOnCancel(() -> log.info("Frontend WebClient::doOnCancel"));
        log.info("Frontend WebClient::End");
        return response;
    }
}`
**Sample**
Is there any solution to this issue? https://github.com/spring-cloud/spring-cloud-sleuth/issues/1672

**Comment by jonatan-ivanov** [comment]
Sleuth reached the [end of its OSS support](https://spring.io/projects/spring-cloud-sleuth#support) timeline (as well as Boot 2.x). We encourage you to migrate to the latest Micrometer Tracing and the latest Boot 3.x.
