### ISSUE TITLE
TracingKafkaReceiver incorrectly sets traceId and spanId for all records in a batch

### ISSUE THREAD

**Issue by kartik-turtle** [spring-cloud/spring-cloud-sleuth#2353]
We are using TracingKafkaReceiver with the expectation that it sets up separate tracing contexts for each received record. However, when receiving a batch, the `traceId` and `spanId` of the first record are being applied to all other records in the batch.

sample - 
```
TracingKafkaReceiver.create(reactiveKafkaTracingPropagator, receiverOptions)
                .receive()
                .concatMap(receiverRecord -> Mono.deferContextual(ctx -> {
                    log.info("received record traceId: {}, spanId: {}", ctx.get(TraceContext.class).traceId(), 
                                  ctx.get(TraceContext.class).spanId());
                    return processRecord(receiverRecord);
                }));
```

Root Cause Analysis (RCA):

Upon investigation, we found that the issue lies within the `ReactiveKafkaTracingPropagator` implementation. Specifically, the ReactorSleuth closes the span and scope before the record processing is complete. This happens because `ReactiveKafkaTracingPropagator` uses `() -> Mono.just(consumerRecord)` as the supplier while calling `ReactorSleuth.tracedMono`. 
https://github.com/spring-cloud/spring-cloud-sleuth/blob/10eaf714c0024cbbec906fdb43d34977b2ef3a2a/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/kafka/ReactiveKafkaTracingPropagator.java#L58

using `KafkaReceiver` and modifying `propagateSpanContextToReactiveContext` method to include processing logic like this solved problem - 

```
KafkaReceiver.create(receiverOptions)
                .receive()
                .flatMap(this::propagateSpanAndProcessRecord)
                .flatMap(receiverRecord -> Mono.deferContextual(ctx -> {
                    log.info("received record traceId: {}, spanId: {}", ctx.get(TraceContext.class).traceId(), 
                    ctx.get(TraceContext.class).spanId());
                    return Mono.just(Success.SUCCESS);
                }));
```
                
```
    private <K, V, T extends ConsumerRecord<K, V>> Flux<Success> propagateSpanAndProcessRecord(Flux<T> publisher) {
        return publisher.concatMap(consumerRecord -> Mono.deferContextual((contextView) -> {

            Span newSpanWithParent = propagator.extract(consumerRecord, extractor).kind(Span.Kind.CONSUMER)
                    .name("kafka.consumer").tag("kafka.topic", consumerRecord.topic())
                    .tag("kafka.offset", Long.toString(consumerRecord.offset()))
                    .tag("kafka.partition", Integer.toString(consumerRecord.partition())).start();

            Mono<Success> successMono = Mono.just(consumerRecord)
                    .flatMap(receiverRecord -> this::processRecord)

            return ReactorSleuth.tracedMono(tracer, newSpanWithParent, () -> successMono);
        }));
    }
```

**Comment by marcingrzejszczak** [comment]
Spring Cloud Sleuth is [out of OSS support](https://spring.io/projects/spring-cloud-sleuth#support). If you're our customer you can reach out for enterprise support.

**Comment by marcingrzejszczak** [comment]
In the meantime please consider migrating to [Micrometer and Micrometer Tracing](https://github.com/micrometer-metrics/micrometer/wiki/Migrating-to-new-1.10.0-Observation-API)
