### ISSUE TITLE
Build and test for Linux/ARM64 

### ISSUE THREAD

**Issue by odidev** [spring-cloud/spring-cloud-sleuth#2354]
## Description  

For aarch64 platform, I have built "spring-cloud-sleuth" from source.  

 

## Steps   

Following "STEPS (https://github.com/spring-cloud/spring-cloud-sleuth?tab=readme-ov-file#building)" were used for building and installing spring-cloud-sleuth.  
```
wget https://github.com/spring-cloud/spring-cloud-sleuth/archive/refs/tags/v3.1.6.tar.gz 

cd spring-cloud-sleuth-3.1.6 

./mvnw install 
```
 

## Outcome  

To validate that the build was successful we ran version check. The version info returned matched the expected value(s). 

`./mvnw --version`
 

All this information was also added to Software Ecosystem Dashboard for Arm (https://www.arm.com/developer-hub/ecosystem-dashboard/).

**Comment by jonatan-ivanov** [comment]
Is there an actual issue you want to raise?
Fyi: Sleuth reached the [end of its OSS support](https://spring.io/projects/spring-cloud-sleuth#support) timeline. We encourage you to migrate to the latest version of Micrometer Tracing.
