### ISSUE TITLE
AsyncRestTemplate Interceptors with non blocking async client (apache http async client)

### ISSUE THREAD

**Issue by shivangshah** [spring-cloud/spring-cloud-sleuth#236]
A question came up while I was trying to using asyncresttemplate with async http client as per this example: http://vincentdevillers.blogspot.com/2013/10/a-best-spring-asyncresttemplate.html
Question is: Will sleuth continue to copy over the tracer contexts at the async http client level as well? Or will this be a different implementation altogether? Or will this not be supported out of the box?

**Comment by marcingrzejszczak** [comment]
We already support `AsyncRestTemplate` - https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebAsyncClientAutoConfiguration.java . Is it not working?

**Comment by shivangshah** [comment]
Ahhh .. thank you for that. I am going to give this a try and let you know how it goes! Appreciate your prompt reply!

**Comment by shivangshah** [comment]
I am going to close this for now. I will comment back once I have a trial project to let you know if it worked or not!

**Comment by shivangshah** [comment]
@marcingrzejszczak I am reopening this issue because I wasn't quite sure how custom async http client would work with the asyncwebclientautoconfiguration you mentioned above. So if you look at the example I mentioned above, you are setting up multiple properties for the async http client. Now from those client beans you make up the asynchttpclientfactory bean and so on and so forth. But if I do it manually, because of the `OnconditionalMissingBean` annotation in spring sleuth code, it will never really configure the way Sleuth expects those asyncclientfactories to be autoconfigured. We could potentially extend the Sleuth configuration, write our own. But is there any other way to do it out-the-box? Or any plans to support this in the future?

A more generic question here would be: There could be many different reasons of overriding the default configuration of restTemplate (or for that matter, asyncRestTemplate with (or without) async http client). Something directly autowiring these clients without configuring them might not work best for a given application. So, on one side, straight up using autowired restTemplates work fine out-the-box, custom configured autowired restTemplates will not work out-the-box, unless, somehow we know what to (and how to) override from Sleuth. 

If that's how it will be supported, it'd be nice to some kind of example/documentation on how we can write custom, overridden, configurations for these clients.
