### ISSUE TITLE
Do we need a RestTemplate bean?

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#239]
Currently `TraceWebClientAutoConfiguration` creates a `@Bean` of type `RestTemplate`. I'd prefer it if that was up to the user really, but I guess before I remove it I thought I'd better ask.

**Comment by marcingrzejszczak** [comment]
Yup makes sense to remove it if the user doesn't want it

**Comment by marcingrzejszczak** [comment]
...Then we shouldn't be adding it
