### ISSUE TITLE
Unclosed Span in ribbon client

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#240]
This one is hard to reproduce I think, but @joshlong had a sample where there were WARN logs about uncloseable spans from a Ribbon client that couldn't resolve its server. It was using Feign as well.

**Comment by marcingrzejszczak** [comment]
Josh can you provide these steps to reproduce it?

**Comment by dsyer** [comment]
I think I did it. If I use Feign and Ribbon/Hystrix and don't define a server list I can break the ribbon sample in Sleuth.

**Comment by dsyer** [comment]
Commit 84f4d37 adds a sample that fails (e.g. run it and curl localhost:3383/).

**Comment by dsyer** [comment]
I have a test that fails and I can fix it, but it won't run in a suite because of some stale state from one of the other tests. Needs more work.
