### ISSUE TITLE
spring.sleuth.log.json.enabled documentation?

### ISSUE THREAD

**Issue by magnusheino** [spring-cloud/spring-cloud-sleuth#245]
Hi.

I have a Brixton.RC1 app. A custom logback configuration, 

`
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<include resource="org/springframework/boot/logging/logback/defaults.xml" />
	<jmxConfigurator/>
	<appender name="JSON_CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
		<encoder class="net.logstash.logback.encoder.LogstashEncoder">
			<fieldNames>
				<level>[ignore]</level>
			</fieldNames>
		</encoder>
	</appender>
	<root level="INFO">
		<appender-ref ref="JSON_CONSOLE" />
	</root>
</configuration>
`

Log output from this config:

`
{"@timestamp":"2016-04-04T15:49:13.544+02:00","@version":1,"message":"Destroying Spring FrameworkServlet 'dispatcherServlet'","logger_name":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]","thread_name":"localhost-startStop-2","level_value":20000,"HOSTNAME":"daysleeper","caller_class_name":"org.apache.juli.logging.DirectJDKLog","caller_method_name":"log","caller_file_name":"DirectJDKLog.java","caller_line_number":180}
`

how can I embed sleuth data into this logentry? And what is spring.sleuth.log.json.enabled?

I have tried to goole, browse the code, but I dont understand how to do it... ?

I do get sleuth output in my logs if I remove my logback xml, but I want json/gelf output...

thanks!

**Comment by marcingrzejszczak** [comment]
As for `spring.sleuth.log.json.enabled` - https://github.com/spring-cloud/spring-cloud-sleuth/blob/v1.0.0.M4/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/SleuthLogAutoConfiguration.java#L52 we had such a thing some time ago. It was a component that used to log spans as jsons into the console.

We're using MDC to log sleuth related information. As I see in https://github.com/logstash/logstash-logback-encoder#loggingevent_mdc you should have this information already passed:

> By default, each entry in the Mapped Diagnostic Context (MDC) (org.slf4j.MDC) will appear as a field in the LoggingEvent.

it's enough for you to read the information with Logstash from the LogginEvent and parse it however you please. 

At the end of this section http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_purpose you'll see the grok pattern for Logstash - I guess you'll need a step before that will remap the LoggingEvent into those values.

Does it answer your question?

**Comment by magnusheino** [comment]
> As for spring.sleuth.log.json.enabled - https://github.com/spring-cloud/spring-cloud-sleuth/blob/v1.0.0.M4/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/SleuthLogAutoConfiguration.java#L52 we had such a thing some time ago. It was a component that used to log spans as jsons into the console.

Ok. I thought that was something that I should use since its still on http://cloud.spring.io/spring-cloud-sleuth/ listed as a feature.

I do get entries in my json log now, using the names defined in org.springframework.cloud.sleuth.Span

I was expecting empty entries for every row just like I get using the normal console log. I get entries for all keys that have values now. Makes sense.

> see the grok pattern for Logstash - I guess you'll need a step before that will remap the LoggingEvent into those values.

Nope, net.logstash.logback.encoder.LogstashEncoder takes care of that. If I run my app in eclipse, I get normal log output. I then package it in a docker container, and set a spring profile for json logging. Spring now logs everything in json to stdout, and I can stream it directly from docker to my graylog instance without any logstash process :-)

Thanks!

**Comment by marcingrzejszczak** [comment]
So everything is fine and we can close the issue? :D

Thanks for pointing out the doc thing. I'll fix it!

**Comment by magnusheino** [comment]
Yes.

**Comment by marcingrzejszczak** [comment]
Where did you see exactly this information about the JSON feature? I can't find it on the page.

**Comment by magnusheino** [comment]
![spring cloud sleuth - google chrome_051](https://cloud.githubusercontent.com/assets/494761/14275626/d8dac3a6-fb18-11e5-9072-5474242cf99f.png)

**Comment by marcingrzejszczak** [comment]
ok - thanks!

**Comment by marcingrzejszczak** [comment]
Fixed
