### ISSUE TITLE
Weird span duration

### ISSUE THREAD

**Issue by Koizumi85** [spring-cloud/spring-cloud-sleuth#247]
Hi all,

got some weird span durations with Sleuth (Requests over Zuul) and Zipkin.
As you can see on the screenshot below, the second span is longer than the first and longer than the request itself took according to my REST client app in the browser (was about 200ms for the whole request).
The Request-Flow is like the following:
- Browser
- Frontend-Service (TraceFilter creates Span 1)
- Frontend-Service (Zuul creates Span 2)
- Customer-Service (TraceFilter creates Span 3)

Because duration of Span 1 is okay (it is near on the duration shown by my REST client), I assume that there has to be some asynchronous action happening in the zuul stuff causing this issue.

Below I provided the screenshot of zipkin and a gist with the JSON of the trace.
If you need more informations, please feel free to ask here or on Gitter.

![spandurations](https://cloud.githubusercontent.com/assets/7482685/14384207/07847890-fd9a-11e5-9fd0-09d80ea8007e.png)

https://gist.github.com/Koizumi85/eefd9c85852bc8d313770303abb4e636

**Comment by marcingrzejszczak** [comment]
Hi! Can you please publish the sample app? It will be easier to reproduce the issue. I want to debug the Zuul part to ensure that we're sending Spans with proper durations. In that case the issue would be on the Zipkin side and we would fix it there. If not then it's our fault in Sleuth.
