### ISSUE TITLE
Support for Hystrix in Zuul proxy

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#25]
The Zuul proxy uses a custom Hystrix command, but isn't aware of the trace context, so unless `hystrix.execution.isolation.strategy=SEMAPHORE` it won't work right now.

**Comment by spencergibb** [comment]
This is a problem with `@HystrixCommand` as well.

**Comment by spencergibb** [comment]
I have a [branch](https://github.com/spring-cloud/spring-cloud-netflix/compare/zuul-httpclient) that abstracts the client zuul uses.  I think it can be used to wrap the ribbon command.

**Comment by spencergibb** [comment]
Looks like the default is `ExecutionIsolationStrategy.SEMAPHORE`

**Comment by dsyer** [comment]
That's a start. I think we still need to instrument the ribbon HTTP client?

**Comment by spencergibb** [comment]
to pass the headers, we do

**Comment by dsyer** [comment]
I think we have duplicate `ClientSentEvents` (one in the `TraceRestClientRibbonCommandFactory` and one in the `TracePreZuulFilter`). The filter shouldn't be sending events like that so we should remove it from there, but then the simple (non-ribbon) Zuul proxy will not send the `Client*Events`, so we need a new client factory for that as well I guess.

Also, should the `TraceRestClientRibbonCommandFactory` be conditional on ribbon being available?

**Comment by marcingrzejszczak** [comment]
I guess this is obsolete after doing https://github.com/spring-cloud/spring-cloud-sleuth/issues/75 ?

**Comment by dsyer** [comment]
I guess
