### ISSUE TITLE
Disable overriding logger pattern

### ISSUE THREAD

**Issue by jkubrynski** [spring-cloud/spring-cloud-sleuth#256]
It looks like currently Sleuth is always overriding my LOG_LEVEL_PATTERN

**Comment by dsyer** [comment]
It doesn't override anything that you set in application.yml (or higher priority). What is your use case exactly?

**Comment by jkubrynski** [comment]
You can override in application.yml using `logging.pattern.level` but when you use env property LOG_LEVEL_PATTERN it's being overridden

**Comment by dsyer** [comment]
That's just the way Spring Boot works. You could probably use `LOGGING_PATTERN_LEVEL` if it was an env var because of the way `SystemEnvironmentPropertySource` is implemented.
