### ISSUE TITLE
Posible loss of spans by StreamSpanReporter

### ISSUE THREAD

**Issue by jorgenota** [spring-cloud/spring-cloud-sleuth#259]
Hi,

I've been reading the code of StreamSpanReporter and I've seen that poll() and report() methods could have concurrency issues. At the moment just after copying the spans from the queue into the results and just before clearing the queue, a new span could be added to the queue... and that new span will be cleared from the queue without being sent in the payload of the message.

	@InboundChannelAdapter(value = SleuthSource.OUTPUT)
	public Spans poll() {
		List<Span> result = new ArrayList<>(this.queue);
		// At this point of execution report() method could be invoked
		// and the span just added to the queue wil be cleared and will not be sent to
		// the stream
		this.queue.clear();
		...
	}
	
	@Override
	public void report(Span span) {
		if (span.isExportable()) {
			this.queue.add(span);
		}
	}

Shouldn't some kind of sinchronization be done? Something like:

	@InboundChannelAdapter(value = SleuthSource.OUTPUT)
	public Spans poll() {
		List<Span> result = null;
		synchronized(this.queue){
			result = new ArrayList<>(this.queue);
			this.queue.clear();
		}
		...
	}
	
	@Override
	public void report(Span span) {
		if (span.isExportable()) {
			synchronized(this.queue){
				this.queue.add(span);
			}
		}
	}

**Comment by marcingrzejszczak** [comment]
Great catch @jorgenota ! Thanks a lot!

**Comment by jorgenota** [comment]
Great! And #262 uses a cleaner solution than my suggestion :)

By the way, I was going to suggest you using a ConcurrentLinkedQueue and just polling from it untill null is returned (ConcurrentLinkedQueue is thread-safe and there's no blocking involved), but I'm not sure if it really is more performant than using LinkedBlockingQueue and its drain method.

**Comment by marcingrzejszczak** [comment]
`LinkedBlockingQueue` is also thread safe - http://docs.oracle.com/javase/6/docs/api/java/util/concurrent/BlockingQueue.html :) I think we'll stay with this one for now. 

Once again thanks a lot for the feedback!
