### ISSUE TITLE
Sampler not used when parent is null inside DefaultTracer.createChild() method

### ISSUE THREAD

**Issue by jorgenota** [spring-cloud/spring-cloud-sleuth#271]
Reviewing the code of the createChild() method of DefaultTracer class, I've detected that when the parent is null a new span is always created as exportable.

I've got two questions about createChild() method:
- Is this method going to be invoked with parent being null? I mean, should we create a child without a parent? Maybe the method should assert that parent value is not null instead of creating a new span when the parent is null.
- In case we want to admit that createChild() receives a null parent, I think we should use the sampler to decide if the new span is going to be exportable, shouldn't we?

**Comment by marcingrzejszczak** [comment]
Hi!

Thanks for the debugging - good job :) 

Generally speaking you're right about this:

> In case we want to admit that createChild() receives a null parent, I think we should use the sampler to decide if the new span is going to be exportable, shouldn't we?

The thing is that I can't actually see a single case where the parent could be null in that method other than that somebody is extending the class and doing some bizarre stuff.

`createChild()` method is executed here:

```
@Override
	public Span createSpan(String name, Sampler sampler) {
		Span span;
		if (isTracing()) {
			span = createChild(getCurrentSpan(), name);
		}
...
```

and here

```
@Override
	public Span createSpan(String name, Span parent) {
		if (parent == null) {
			return createSpan(name);
		}
		return continueSpan(createChild(parent, name));
	}
```

Ad 1) To have a `null` parent in that method `getCurrentSpan()` would have to be `null`. That can't the case cause `isTracing()` checks for that:

```
/**
	 * Check if there is already a span in the current thread
	 */
	static boolean isTracing() {
		return CURRENT_SPAN.get() != null;
	}

```

Ad 2) if parent is `null` then that method is not even executed.

Can you tell us how you achieved a case, by using the public API, that you got a `null` in that parent?

**Comment by jorgenota** [comment]
Hi Marcin! I didn't achived the case, just read the code :) 

 I can't see either a single case where the parent is null when createChild() is invoked from any of the createSpan() methods. Just noticed that if you want to consider that case in createChild(), the block of code creating the span should use the sampler. The other option would be not considering that case and removing that "if" clause (probably asserting that parent is not null).

I'm glad I could help.
