### ISSUE TITLE
Wrong property name used in spring-cloud-sleuth-sample-zipkin

### ISSUE THREAD

**Issue by jorgenota** [spring-cloud/spring-cloud-sleuth#273]
The sample project spring-cloud-sleuth-sample-zipkin contains an application.yml with the property "sample.zipkin.enabled".

Shouldn't that property be "spring.zipkin.enabled" instead?

The file location is:
https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/main/resources/application.yml

**Comment by marcingrzejszczak** [comment]
Nope - it's related to this property - https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/main/java/sample/SampleZipkinApplication.java#L51 . To have a custom reporter in the sample.

**Comment by jorgenota** [comment]
Oooops! Thank you.
