### ISSUE TITLE
The maven central repository doesn't support 1.0.1.BUILD-SNAPSHOT or later

### ISSUE THREAD

**Issue by binlee1990** [spring-cloud/spring-cloud-sleuth#283]
When I pull the samples, I found that the maven central repository only has verison 1.0.0.RELEASE, but the samples now is version 1.0.1.BUILD-SNAPSHOT.

How can I convert to version 1.0.0.RELEASE and run the samples?

**Comment by marcingrzejszczak** [comment]
Just checkout the release tag - https://github.com/spring-cloud/spring-cloud-sleuth/tree/v1.0.0.RELEASE . Or just build the whole project with snapshots and then you'll be able to run the samples
