### ISSUE TITLE
Unclosed spans when using custom Feign client configuration

### ISSUE THREAD

**Issue by prademak** [spring-cloud/spring-cloud-sleuth#285]
When using a custom configuration for a @FeignClient (see
http://projects.spring.io/spring-cloud/spring-cloud.html#spring-cloud-feign-overriding-defaults)
spans are not closed anymore, resulting in the following warning messages:

`WARN Tried to detach trace span but it is not the current span: [...] You may have forgotten to close or detach [...] `

As far as I was able to investigate this is because the FeignBeanPostProcessor
will not be applied to Feign client custom @Configurations because in FeignClientFactoryBean these are loaded separately from the other @Configurations.

In a minute I will submit a pull request in which I've added 2 (currently failing) tests to reproduce the issue.

**Comment by marcingrzejszczak** [comment]
Fixed by https://github.com/spring-cloud/spring-cloud-sleuth/commit/358d0b16b5a5a061dfa9f13517fb8f2c0a3d6754
