### ISSUE TITLE
Possible race condition with MDC

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-sleuth#29]
From a conversation with @rwinch 

> DefaultTrace is using ApplicationEventPublisher to publish events which setup the MDC
> 
> This can be problematic in many production applications I have dealt with because lots of people provide an async `ApplicationEventMulticaster` by defining SimpleApplicationEventMulticaster in their application context
> 
> This means there is a race condition in terms of what logs get the MDC setup and cleaned up
> 
> Also....
> 
> The bigger problem is since MDC will be setup on another thread...the MDC is not actually properly setup
> 
> because it is tied to the current thread (which will not be the Thread of execution)
> 
> Of course the second issue means that there really is no race condition, but it would be the case if the MDC from the original thread were passed in)

**Comment by dsyer** [comment]
I think an async `ApplicationEventMulticaster` is buyer beware, and I don't think this is the only thing that will break if you do that. Whoever does that will have to make sure they pass the thread context down to the multicaster. Is it only MDC that is a problem here, or is it trace context thread state as well?

Copy @marcingrzejszczak for comment since they use this feature (I guess they don't use an async multicaster).

**Comment by dsyer** [comment]
I noticed a different problem with MDC which is that it isn't obviously always cleared so it remains set on the thread (in a pool presumably).

**Comment by rwinch** [comment]
@dsyer Even if they pass the context to the multicaster, it will still cause the race condition. Specifically you can't be sure that the MDC is populated or cleared before logging on the main thread occurs.

Also of note, I have noticed quite a few people do use custom `ApplicationEventMulticaster` so I wouldn't be surprised if this causes quite a bit of headaches for users.

**Comment by spencergibb** [comment]
In the beginning 4finance didn't use events at all: 9829ff99033a869dcaede89e3fa30f45e0efd1e4, so @marcingrzejszczak never had this problem.

**Comment by marcingrzejszczak** [comment]
Hi Guys! As @spencergibb says we weren't using events.

**Comment by marcingrzejszczak** [comment]
We're not using events anymore so won't have this problem
