### ISSUE TITLE
Feign external url span details missing

### ISSUE THREAD

**Issue by singram** [spring-cloud/spring-cloud-sleuth#290]
When using feign to call an external url.  eg.
```
@FeignClient(name = "swapi-service", url = "http://swapi.co/api/")
public interface SwapiService {
  @RequestMapping(method = RequestMethod.GET, value = "/people/{personId}")
  ResponseEntity<SwapiPerson> getPerson(@RequestHeader(value="User-Agent", defaultValue="curl/7.45.0") String userAgent, @PathVariable("personId") long personId);
}
```
Details such as 
-   http.host
-   http.method
-   http.path
-   http.url

Are not captured on the span and visible in Zipkin, as shown in other examples such as those found here. http://brewery-zipkin-server.cfapps.io/traces/38efdb9a8861a00a?serviceName=brewing

Using
- Spring-boot => 1.3.5.Release
- Spring-cloud => Brixton.Release

**Comment by marcingrzejszczak** [comment]
CC @adriancole - this is what we were discussing on Gitter. If we have both apps instrumented (client + server) then once the server side creates the span it adds the details. Whereas when we have a case where we call an external service then we lose those tag information.
