### ISSUE TITLE
TraceFeignRetryer overrides custom feign Retryer

### ISSUE THREAD

**Issue by dpalita** [spring-cloud/spring-cloud-sleuth#291]
I think there is a problem in TraceFeignRetryer which makes it always use the Retryer.Default implementation.

Shouldn't
```	
@Override
public Retryer clone() {
	return new TraceFeignRetryer(this.tracer);
}
```
be something like 
```	
@Override
public Retryer clone() {
	return new TraceFeignRetryer(this.tracer, this.delegate.clone());
}
```

As it is my custom retryer (that tries to not retry at all) is taken into account by the FeignBeanPostProcessor but is discarded at the first call to clone().

There may very well be (lots of) things I didn't understand, all I'm trying to do is to stop Feign from retrying automatically, especially when Ribbon is also trying to retry... I think retrying should be an opt-in behaviour, but this is another matter :-)

**Comment by marcingrzejszczak** [comment]
Thanks @dpalita for the great analysis!! You were obviously right - the issue is fixed.

**Comment by dpalita** [comment]
Thank you very much for taking this into account.
If I may add something, I think you should also be cloning the delegate in the clone method because the Retryer is not thread safe. 
If you to not clone you will also reuse the `int attempt;` and `long sleptForMillis;` of the Default implementation. I guess that after a short while the Retryer won't retry anymore because `attempt++ >= maxAttempts` will always be true.

**Comment by marcingrzejszczak** [comment]
Again you're right :) https://github.com/spring-cloud/spring-cloud-sleuth/commit/0a0d36053d7fd77247c2da9af12d81e5a465b9ba

**Comment by marcingrzejszczak** [comment]
@dpalita can you check against latest snapshots that everything is working as expected?

**Comment by dpalita** [comment]
Yes it does (as far as I can tell). Thanks a lot.
