### ISSUE TITLE
Integration with Spring AMQP (Remoting)

### ISSUE THREAD

**Issue by testark** [spring-cloud/spring-cloud-sleuth#295]
I made a quick test and I believe Spring Cloud Sleuth does not instrument comms made using Spring AMQP (Remoting). As we're using it to achieve RPC between microservices, I'd like to know whether this is in your roadmap.

**Comment by marcingrzejszczak** [comment]
If you can use Spring AMQP (Remoting) via Spring Integration then we already support it. If not then currently we do not have it in our roadmap. But if more people decide that it's an important feature to have then we consider taking it to the backlog.

**Comment by testark** [comment]
> If you can use Spring AMQP (Remoting) via Spring Integration
I'm using it directly. How do I go about using it via Integration?

**Comment by garyrussell** [comment]
Spring Remoting (using all technologies, including AQMP) uses a different paradigm to the other technologies used for message exchange.

Remoting implies tight coupling between client and server (at the API level).

You could replace it with Spring Integration by injecting a messaging gateway on the client side, where the gateway routes to an AmqpOutboundGateway; on the server side an AmqpInboundGateway routes to a ServiceActivator which invokes the POJO that's currently invoked by remoting.

**Comment by marcingrzejszczak** [comment]
Can we assume that this issue is closed?

**Comment by testark** [comment]
@garyrussell that should take care of the "request". What about a reply? How does a method that return a value gets its result delivered to the calling client?

**Comment by dsyer** [comment]
As a message body (e.g. see `MessageRequestReplyOperations` from Spring Framework for a nice abstraction).

**Comment by garyrussell** [comment]
>on the server side an AmqpInboundGateway routes to a ServiceActivator which invokes the POJO that's currently invoked by remoting.

The return value from the POJO method call will be routed back to the client caller via the gateways.

**Comment by garyrussell** [comment]
Or, as @dsyer says you can use the MRRO - (`GenericMessagingTemplate`).

One difference between remoting and messaging is remoting supports multiple parameters/arguments (which is what I implied by tight coupling of client/server APIs) messaging does not, there's one message payload.

If you are passing multiple arguments using remoting, using messaging you need a wrapper object for the message payload.

**Comment by marcingrzejszczak** [comment]
Can we close this @testark ?

**Comment by marcingrzejszczak** [comment]
One last ping @testark ?

**Comment by testark** [comment]
@marcingrzejszczak yes, sure 😊

**Comment by testark** [comment]
@dsyer @garyrussell @marcingrzejszczak many thanks again 😊
