### ISSUE TITLE
Server Support for Jersey (used in Spring Boot)

### ISSUE THREAD

**Issue by fritzrichter** [spring-cloud/spring-cloud-sleuth#298]
Hey together, typically we use a JSON/REST API exposed via Jersey in our Spring Boot Microservices on the server side. We use then Feign on the Client side. Where I was able to use sleuth together with Feign (trace information is attached as HTTP Headers), I now have to extract that information on the server side.

Is there anything I can reuse or do I have to write my own filters for jersey?

**Comment by marcingrzejszczak** [comment]
You can write sth similar to the `TraceFilter` - https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java . It uses `HttpServletRequestExtractor` - https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/HttpServletRequestExtractor.java and Injector - https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/HttpServletResponseInjector.java . You'd have to write sth similar.

**Comment by dsyer** [comment]
I don't think you need to do anything (except make sure the filters are ordered properly if you are using the Jersey filter). `TraceFilter`works with all handlers (not just Spring ones).

**Comment by fritzrichter** [comment]
ok thanks! It's basically working now. great stuff!

**Comment by axelgalicia** [comment]
Hello dsyer, how do you make sure the filters are ordered properly. In my case I am using Jersey in the server but how to check the correct order of the filters?

**Comment by shubham-chegg** [comment]
@dsyer @fritzrichter 
I believe the implementation has changed over the period of last 3 years, can you please provide an updated solution or way to implement this using sleuth 2.0.2.RELEASE

**Comment by juanmbellini** [comment]
Any news on this?

**Comment by dsyer** [comment]
No news because nothing has changed. It works and you shouldn’t have to do anything special.

**Comment by juanmbellini** [comment]
@dsyer Yes, but `spring-webmvc` must be included as a dependency. 
It would be great to be able to use sleuth without including `spring-webmvc` as muy application is jersey based.

**Comment by dsyer** [comment]
I would open a new issue specifically about that then. It’s not broken, just inconvenient. Not much point adding comments to an old, different issue.

**Comment by Klapsa2503** [comment]
@dsyer @marcingrzejszczak @juanmbellini any update on this after couple of years? I tried to follow previously attached links but those are inactive after that many years.

My issue is that we are using Jersey (client+server) in our microservices and I am looking an easy way to introduce tracing.

Could you share current recommended approach?

**Comment by mohsin36** [comment]
Below code worked for me. It uses TracingApplicationEventListener from [brave-instrumentation-jersey-server](https://github.com/openzipkin/brave/tree/master/instrumentation/jersey-server)

```java
Tracing tracing = Tracing.newBuilder().localServiceName("servicename")
				.sampler(Sampler.ALWAYS_SAMPLE).spanReporter(reporter).build();
Httptracing httpTracing = HttpTracing.newBuilder(tracing).build();
ApplicationEventListener jerseyTracingFilter = TracingApplicationEventListener
		.create(httpTracing);
environment.jersey().register(jerseyTracingFilter);
```

Reference [link](https://www.programcreek.com/java-api-examples/?code=jeqo%2Ftalk-kafka-zipkin%2Ftalk-kafka-zipkin-master%2Fhello-translation%2Fsrc%2Fmain%2Fjava%2Fio%2Fgithub%2Fjeqo%2Ftalk%2FTranslationService.java)

**Comment by marcingrzejszczak** [comment]
Sleuth is feature complete - we will not add new features to it.
