### ISSUE TITLE
Integration with gRPC

### ISSUE THREAD

**Issue by testark** [spring-cloud/spring-cloud-sleuth#305]
Is instrumentation for gRPC in your roadmap for anytime soon?

**Comment by marcingrzejszczak** [comment]
Nope - it's not ATM.

**Comment by mikkiweesenaar** [comment]
+1 for still implementing it :)

**Comment by sdavids** [comment]
Why is this closed?

**Comment by marcingrzejszczak** [comment]
Most likely by accident @sdavids

**Comment by thekalinga** [comment]
Is there a chance this would be fixed anytime soon?

`gRPC` is much more efficient as it uses HTTP 2.0, plus we can leverage new service mesh frameworks like (Enjoy)[https://www.envoyproxy.io/] that are far more superior & feature rich than `Hystrix` (netflix family ingeneral)

**Comment by adriancole** [comment]
https://github.com/spring-cloud/spring-cloud-sleuth/issues/711 will resolve this indirectly or directly as brave supports grpc

**Comment by adriancole** [comment]
Let's see about more out-of-box integration

you can see tests for client and server interceptors here
https://github.com/openzipkin/brave/blob/master/instrumentation/grpc/src/test/java/brave/grpc/ITTracingClientInterceptor.java
https://github.com/openzipkin/brave/blob/master/instrumentation/grpc/src/test/java/brave/grpc/ITTracingServerInterceptor.java

there are probably some example spring boot + grpc projects out there.. key is doing the interceptor add-on conditionally when building server or client channel

**Comment by tkvangorder** [comment]
Since brave has client and server side interceptors for gRpc (thanks for the pointer @adriancole ), It is actually pretty straighforward to instrument gRcp calls by combining Spring Cloud Sleuth 2.x with the third-party boot library grpc-spring-boot-starter. I have setup a small sample project that demonstrates how this can be done here: https://github.com/LogNet/grpc-spring-boot-starter

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by mikkiweesenaar** [comment]
Thanks for still implementing it!
