### ISSUE TITLE
Malformed X-B3 headers cause 500 error

### ISSUE THREAD

**Issue by efenderbosch** [spring-cloud/spring-cloud-sleuth#306]
If either X-B3-TraceId or X-B3-SpanId request header is malformed, Span throws a NumberFormatException.

It seems to me that this should fail gracefully, creating a new SpanId and/or TraceId instead of propagating the NFE and returning 500.

Maybe handle this in HttpServletRequestExtractor::joinTrace?

**Comment by adriancole** [comment]
noted in the commit, but I don't think sleuth should take any action on
malformed values, except possibly throw malformed (4xx range). Only custom
or pre-release instrumentation would send malformed data, and they should
be corrected vs burden the code base with several if statements

**Comment by marcingrzejszczak** [comment]
After having a chat with @adriancole we've decided to put more work on this. Actually malformed tracing headers can occur only in case of custom instrumentations or incidential requests. Obviously we shouldn't send 5xx codes back to the user but the 4xx exceptions would be acceptable. The user should fix the wrong impl (actually the tests should blow up with exceptions so such a malformed header sending impl shouldn't end up on production).
