### ISSUE TITLE
More precise duration

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#312]
Sleuth logs "local spans" for in-process activity (ex things like async methods that often complete in less than 2 milliseconds). I've found it difficult to debug sleuth itself on account of Span having only milliseconds precision. For example, some tasks end up as zero milliseconds, and others look longer than they should (ex 2 millis when it should be less than one). While we can use btrace or byteman to help diagnose local perf issues, seems we can kill 2 birds with one stone by changing some units to microseconds.

Durations of local spans are better made in smaller order (like microseconds), as you can more easily compare equivalent tasks. Moreover, we should avoid making end markers with calls to System.currentTimeMillis as it cannot show sub-millis differences and also has a risk of moving backwards.

Here's pseudocode of what we could do to alter the impl to use higher precision:

* when existing field Span.begin is initialized, also initialize startNanos with System.nanoTime
* at Span.stop() set endNanos = System.nanoTime
  * add new field or method: Span.duration() or durationMicros() =  (endNanos - startNanos) * 1000
  * direct existing method Span.getAccumulatedMillis to durationMicros() / 1000

Footnote on choosing micros instead of nanos for duration:

I'd suggest not advertising duration in nanoseconds because we cannot accurately measure at that granularity due to the [overhead and change frequency of System.nanoTime()](http://shipilev.net/blog/2014/nanotrusting-nanotime/#_backoff_measurements). For example, if calling nanoTime has to happen twice, and we should expect 30nanos overhead per call, we can't reliably report duration in orders of nanos. Moreover, eventhough unix can report time in microseconds using the presumably cheaper [gettimeofday](http://man7.org/linux/man-pages/man2/gettimeofday.2.html), it cannot in nanos. In short, micros ends up a pretty decent choice for various reasons even if we didn't consider zipkin which uses micros consistently for everything.

**Comment by dsyer** [comment]
Typo (Span.getAccumulatedMillis to durationMicros() / 1000)?

**Comment by marcingrzejszczak** [comment]
Actually Nanos to Millis is / 1 000 000 isn't it?

**Comment by dsyer** [comment]
The example was micros to millis.

**Comment by adriancole** [comment]
fixed the typo. thx @dsyer
