### ISSUE TITLE
Instrument zuul RibbonCommands in a generic way.

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-sleuth#313]
Currently instrumentation is specific to `RestClientRibbonCommand*` which is no longer [the default](https://github.com/spring-cloud/spring-cloud-netflix/commit/fd36a0cc7229d0205b4c4a7a3f7ced9bcb6eaf9a). There are [two other implementations](https://github.com/spring-cloud/spring-cloud-netflix/commit/7ac81f8fd5a2428d995a430903952125d9edc1db) that don't get zuul ribbon instrumentation.

**Comment by spencergibb** [comment]
Could be done with https://github.com/spencergibb/spring-cloud-netflix/tree/request-customizers.

Could implement `RibbonRequestCustomizer<>` for each http client type: jersey, apache and okhttp. Basically just need classes like https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/zuul/RequestBuilderContextInjector.java

**Comment by EstebanDugueperoux2** [comment]
Hello,

I'm using Spring Cloud Sleuth Core 2.2.3.RELEASE and I don't find anymore these RibbonRequestCustomizer and when calling one of my services through Spring Cloud Zuul without specifying "X-B3-TraceId" and other a get 2 traceIds in my Zipkin, one for Zuul and another for my service without link between them.
Is there a regression?

Best Regards.
