### ISSUE TITLE
hessian client injection

### ISSUE THREAD

**Issue by micheal-xudb** [spring-cloud/spring-cloud-sleuth#320]
I find restTemplateInterceptor and feignRequestInterceptor from spring-cloud-sleuth-core, but our project use hessian connect microservices, and I find that spring-cloud-sleuth can not inject to hessian client. Can anyone share the code how to use spring-cloud-sleuth with hessian? Thanks

**Comment by marcingrzejszczak** [comment]
Hello! We don not support Hessian. You would have to instrument it yourself using a `SpanExtractor` and `SpanInjector`. They provide a contract on how to pass spans into a carrier and how to get a span from the carrier. Examples of that you have for instance here:

- Injector - https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/HttpRequestInjector.java
- Extractor - https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/HttpServletRequestExtractor.java
- how they are used - https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java#L156-L165
