### ISSUE TITLE
Compatibility with Netty

### ISSUE THREAD

**Issue by mjallday** [spring-cloud/spring-cloud-sleuth#325]
I'm attempting to use this library with Netty and notice that in many places it's using a `ThreadLocal` which does not work with Netty. Netty has the concept of a `ChannelHandlerContext` which performs similarly (one channel per-request).

This results in some errors about attempting to close spans from requests which are incorrectly associated as soon as you begin handling concurrent requests.

The library currently does not make this change easy to implement but it would not be difficult, it looks like `TraceContextHolder` needs to be changed to an interface and provide implementations for `ThreadLocal` and `ChannelHandlerContext`/`AttributeMap`. 

I'm thinking here that the easiest way to begin this would be to change `TraceContextHolder` into an interface and then provide a default `ThreadLocalTraceContextHolder`. I should then be able to provide an alternate implementation of `DefaultTrace` in my own project which would be `NettyTrace` and there's no need to provide any Netty dependencies in this project.

Before I begin this work I want to understand if there's anything I'm missing here, is there more to this than an implementation like this?

**Comment by marcingrzejszczak** [comment]
@dsyer @smaldini isn't this related to Spring 5.0, Reactive approach etc ?

**Comment by smaldini** [comment]
This is an insightful and spot-on question, we are definitively thinking about it for our concerns regarding Reactor,  Spring 5 (and also reactor-netty which suffer exactly that same issue) /cc @rstoyanchev 

We have a tight schedule for the coming weeks until early August but we will be able to discuss in depth the topic very soon (thanks SpringOne 2016 💃). Be sure this is a top priority concern not only for tracing but also stuff like security or scopes which are using the same thread local trick.

**Comment by rstoyanchev** [comment]
So the idea is to store trace information as Netty channel attributes? Do you have access to the Netty channel from all the places where you need to access or update trace information?

**Comment by marcingrzejszczak** [comment]
I'm not a Netty expert to say the least. What we need to accomplish is that per-request we need to propagate some data between different contexts / libraries / threads etc. If we can accomplish that via channel attributes then most likely that's the way to go. In other words if `ChannelHandlerContext` is `ThreadLocal` for Netty then it seems like a good start.

On the other hand I guess we'll have to sit down and analyze it more since maybe we're trying to bend Netty's reactive approach to use the current Sleuth's implementation. Don't know - just asking.

**Comment by mjallday** [comment]
@marcingrzejszczak i was thinking that if you implemented something technology agnostic by allowing me to inject my own object that knows how to store information it would solve the issue e.g.

```java
@Component
public class TraceContextHolder {

  @Inject
  @Named("localTraceContext")
  private Local<Span> currentSpan;

  public Span getCurrentSpan() {
    return currentSpan.get();
  }

  public void setCurrentSpan(Span span) {
    currentSpan.set(span);
  }

  public void removeCurrentSpan() {
    currentSpan.remove();
  }

  public boolean isTracing() {
    return currentSpan.get() != null;
  }
}
```

and then provided a `Local` interface that can be injected then this would solve the issue.

```java
interface Local<T> {
  T get();
  void set(T value);
  void remove();
}
```

The spring-cloud-sleuth library can provide a Spring compatible implementation by default using `ThreadLocal` and then I can define my own bean which overrides this and uses something native to the framework that I'm using.

This isn't a perfect implementation, I'd still need to figure out how to pass a reference to the channel to the `get`, `set` and `remove` methods but I think it conveys the idea behind it.

**Comment by rstoyanchev** [comment]
A Channel is just an abstraction representing a connection. You can attach attributes like you can to a Servlet request. To get those attributes you need access to pass the Channel around. Hence my question how would the Channel be accessed from different contexts, libraries, etc. @mjallday ?

**Comment by rstoyanchev** [comment]
Oops, I should have hit Refresh before responding. At any rate I'd be interested to see the direction of this. As @smaldini mentioned this is an important topic for the Spring Framework 5 reactive efforts.

**Comment by marcingrzejszczak** [comment]
Related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/143 and https://github.com/spring-cloud/spring-cloud-sleuth/issues/344

**Comment by marcingrzejszczak** [comment]
We have introduced support for Project Reactor in latest `1.3.0.BUILD-SNAPSHOT` (`Edgware` release train) so this problem is fixed indirectly via the Reactor Context + custom subscribers. Would that work for now to solve this issue @mjallday ? If not then you can extend the `DefaultTracer` and provide your own implementation of what setting and getting a span should look like. WDYT ?

**Comment by marcingrzejszczak** [comment]
Ping @mjallday ?

**Comment by adriancole** [comment]
fyi, in another project doing raw netty http, attributes are used to carry
the trace context from here to there. This is the "spanInScope" commands
you see. https://github.com/openzipkin/brave/pull/441 This particular work
is waiting for others to be interested in it, but feel free to take ideas
here as there are similar concepts in sleuth for this stuff.

**Comment by marcingrzejszczak** [comment]
I'll put it to icebox until more people are interested and the Brave work has been done.

**Comment by goober** [comment]
@marcingrzejszczak what is the current status on this issue? I can see that the work on Brave has been implemented and released a couple of weeks ago.

**Comment by adriancole** [comment]
@goober last week we discussed that we'll start the major work soon (not that spring one platform is over). Can you describe the components you use and if you can beta test something even if it doesn't use the old sleuth span api? It will help us prioritize.

**Comment by goober** [comment]
Thanks for the update @adriancole. 
We are currently doing some test shots with Spring Boot 2 (2.0.0 M7) and spring-webflux running the Netty runtime to see if our dependencies are compatible. We are doing downstream requests to other services via [WebClient](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/function/client/WebClient.html). 

So our case is that we would like to have distributed tracing with spring-cloud-sleuth working with spring-webflux and the new WebClient from Spring Framework 5 (on a Netty runtime) as it currently works with the older synchronous spring-mvc and restTemplate on a tomcat runtime.

We can for sure beta test your findings during the process and can also help out with whatever you need!

**Comment by marcingrzejszczak** [comment]
> WebClient from Spring Framework 5 (on a Netty runtime)

Why would you say that it's not working with Netty runtime ATM? We have instrumented `WebClient` as such so that should work fine out of the box

**Comment by goober** [comment]
@marcingrzejszczak I can now confirm that WebClient works just fine with spring cloud sleuth. It was our mistake that we didn't create the WebClient or WebClient.Builder as a spring bean.

**Comment by marcingrzejszczak** [comment]
Great. So I'll close this issue for now.
