### ISSUE TITLE
Wrong service name in Spring Cloud vBrixton.SR1

### ISSUE THREAD

**Issue by arminbalalaie** [spring-cloud/spring-cloud-sleuth#330]
Using Spring Cloud vBrixton.SR1 (Spring Boot v1.3.5) the service name in logs is `bootstrap`. I think the problem is here https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceEnvironmentPostProcessor.java#L54. ${spring.application.name:} should be replaced by ${spring.application.name:-}. I fixed it by adding a property in my logback-spring.xml file. 
```
<property name="LOG_LEVEL_PATTERN" value="%clr(%5p) %clr([${spring.application.name:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow}"/>
```

As a side note, when using Spring Boot v1.3.2, and having a custom logback-spring.xml, Spring Boot does not initialize LOG_LEVEL_PATTERN with logging.pattern.level (Sleuth uses this to manipulate logs), and as a result, no tracing data appear in logs. I also fixed that by adding the following property to my logback-spring.xml file:
```
<property name="LOG_LEVEL_PATTERN" value="%clr(%5p) %clr([${spring.application.name:-},%X{X-Trace-Id:-},%X{X-Span-Id:-},%X{X-Span-Export:-}]){yellow}"/>
```

**Comment by marcingrzejszczak** [comment]
Hello! Yeah I think there's a typo there in the pattern. BTW can you put your sample app somewhere? I could play around with it to ensure that things are working fine.

**Comment by marcingrzejszczak** [comment]
Assuming that the logback config is

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/base.xml"/>
    <logger name="org.springframework.web" level="DEBUG"/>
</configuration>
```

Hmm if you set the `spring.application.name` in `bootstrap.yaml` then the name is present in the logs without doing the change. I've added the `-` but it didn't help much. I'll investigate it further on.

Also check out the docs, just above this section http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_adding_to_the_project we're showing how you can set your custom logback setup. We're also doing what you did on your side.

**Comment by marcingrzejszczak** [comment]
Ping @arminbalalaie ?

**Comment by arminbalalaie** [comment]
Yup. you're right. It worked fine with bootstrap.yml. But it should also work with application.yml. It shouldn't be important where one set the application name. If it matters, at least, it should be noted in the documentation.

How do you set spring.application.name variable for logback? I think the problem is that the variable is set too soon and before loading all of the property sources.

**Comment by marcingrzejszczak** [comment]
Actually I did similar to what you did. Check out the docs http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html 

Maybe @dsyer knows a better way to achieve this other than in logback configuration set a local variable

```
        <springProperty scope="context" name="springAppName" source="spring.application.name"/>
	<!-- Example for logging into the build folder of your project -->
	<property name="LOG_FILE" value="${BUILD_FOLDER:-build}/${springAppName}"/>​

	<property name="CONSOLE_LOG_PATTERN"
			  value="%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"/>
```

Cause it does sound bizarre that the `spring.application.name` without this approach ^^ gets ignored if set in `application.yml`.

**Comment by arminbalalaie** [comment]
I mean how does it know about spring.application.name when you don't set it in logback-spring.xml (the default situation)? As logback don't have access to spring properties, you should set it as a logback property or env variable. I am not sure if this is being done in spring-cloud-sleuth or spring-boot now. IMO, the problem lies there.

Another workaround could be injecting this property through MDC.

**Comment by marcingrzejszczak** [comment]
I do set it in `logback-spring.xml` - https://github.com/spring-cloud-samples/sleuth-documentation-apps/blob/master/service1/src/main/resources/logback-spring.xml this is an example.

In Sleuth we provide the default property for you via environment post processor - https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceEnvironmentPostProcessor.java#L53

**Comment by arminbalalaie** [comment]
I have no idea. Maybe logging auto configuration is different when a custom logback-spring.xml is present. But it's really odd! I think we should wait for @dsyer comment.

**Comment by marcingrzejszczak** [comment]
Yo! 

I had a chat with the one and only @dsyer and he suggested not to do that include `<include resource="org/springframework/boot/logging/logback/base.xml"/>` since it's there for backwards compatibility. 

If that doesn't help then let's assume that the aforementioned workaround is necessary and we should better document it.

**Comment by marcingrzejszczak** [comment]
ping @arminbalalaie

**Comment by arminbalalaie** [comment]
I needed to use spring-logback.xml becuase I wanted to configure a Sentry appender for logback. Also, I needed to log into console and file using either that base file or my own configurations. So, IMO, the problem is not that file, and in similar situations other ppl may want to use a custom spring-logback.xml file as well. 

If there isn't any other way for solving this problem (I think it's odd), I suggest that the documentation should be updated to highlight the aforementioned workaround.

**Comment by marcingrzejszczak** [comment]
Im just saying that maybe this line `<include resource="org/springframework/boot/logging/logback/base.xml"/>` is breaking things. And also it's not needed in the first place. If you confirmed that then it would be awesome. If not then we need to document that.

**Comment by marcingrzejszczak** [comment]
ok I've fixed the docs to reflect this - https://github.com/spring-cloud/spring-cloud-sleuth/issues/376
