### ISSUE TITLE
invokeAll and invokeAny calls within TraceableExecutorService are not wrapped in LocalComponentTraceCallable

### ISSUE THREAD

**Issue by PranayPS** [spring-cloud/spring-cloud-sleuth#333]
Is there a reason for this or is this simply a bug?

**Comment by PranayPS** [comment]
Proposed change: https://github.com/spring-cloud/spring-cloud-sleuth/compare/master...PranayPS:master

**Comment by marcingrzejszczak** [comment]
Argh! It's a bug... Good change, please file a PR :)

**Comment by marcingrzejszczak** [comment]
Thanks a lot @PranayPS for your help!
