### ISSUE TITLE
SleuthStreamReporter fails when multiple Pollers defined but no default Poller

### ISSUE THREAD

**Issue by steve-oakey** [spring-cloud/spring-cloud-sleuth#338]
When integrating Sleuth into existing applications, we had one Spring Integration application that had multiple `PollerMetadata` beans registered. We did not have a bean registered with a name of `PollerMetadata.DEFAULT_POLLER`. Since the `@InboundChannelAdapter` in `SleuthStreamReporter` relies on a default poller, the application would not start.

Would it make sense to provide a Poller (using `@Poller` within `@InboundChannelAdapter`)?

**Comment by garyrussell** [comment]
Yes, I agree - it's not really a good idea to rely on a default poller, in a component provided by a library - the default poller in the application might have completely inappropriate properties and, as @steve-oakey says, there might not be one present at all.

It would be better to provide an explicit `@Poller` in the component definition, perhaps with configurable properties (and some appropriate opinionated defaults).

**Comment by marcingrzejszczak** [comment]
Thanks @garyrussell ! @steve-oakey - care for another PR? :)

**Comment by steve-oakey** [comment]
Sure. Any preference on the poller configuration? Would providing a configurable fixed rate with 1 second as a default be sufficient?

**Comment by marcingrzejszczak** [comment]
Sure, sounds good

**Comment by mbogoevici** [comment]
Agree with @garyrussell. As background info Spring Cloud Stream provides some default poller metadata, but it's only activated when autoconfiguration is on. It's okay for an application, but not for a library.

**Comment by garyrussell** [comment]
I am not familiar with the application but if the time to accumulate the `Spans` can approach a second, you might want to use `fixed-delay` instead of `fixed-rate`.

Also, this doesn't look very efficient to me...

		List<Span> result = new ArrayList<>();
		this.queue.drainTo(result);
		for (Iterator<Span> iterator = result.iterator(); iterator.hasNext();) {
			Span span = iterator.next();
			if (span.getName() != null && span.getName().equals("message/" + SleuthSource.OUTPUT)) {
				iterator.remove();
			}
		}

If result is large, those remove operations might be expensive because the array has to be shifted down each time.

It would be much better to use a `LinkedList`.

**Comment by marcingrzejszczak** [comment]
Oh yeah - a very good point! Thanks @garyrussell
