### ISSUE TITLE
SA annotation endpoint servicename defaults for all use cases impacting external dependencies

### ISSUE THREAD

**Issue by singram** [spring-cloud/spring-cloud-sleuth#346]
The endpoint_service_name currently defaults to the current service for all annotation tags.

It is desirable when calling out to an external service to attach a 'SA' annotation to the span with the remote service name as the endpoint_service_name

A concrete example of the issue would be a zipkin aware service calling out to an external non-zipkin aware service.  For instance redis;

```
    Span newSpan = this.tracer.createSpan("redis");
    try {
      newSpan.tag("redis.op", "get");
      newSpan.tag("lc", "redis");
      newSpan.logEvent(Span.CLIENT_SEND);
      return (SomeObj) redisTemplate.opsForHash().get("MYHASH", someObjKey);
    } finally {
      newSpan.tag("sa", getRedisURI());
      newSpan.logEvent(Span.CLIENT_RECV);
      this.tracer.close(newSpan);
    }

```
This records the expected span but as all annotations are associated with the client service, there is nothing in the data store that would indicate that it is a call to an external service.  As such the external component is not apparent in the dependency view in zipkin.

Other libraries such as zipkin-tracer handle this scenario by creating the 'SA' annotation associated with the client span but associate it with a different 'endpoint_service_name' representing the external service.

It seems when creating a span there should be a way to indicate that it is for an external service and to tag it as such.  Thoughts?

**Comment by adriancole** [comment]
in brave, this is handled by special-casing the close..

ex.
```java
    brave.clientTracer()
        .setClientSent(redis.ipv4, redis.port, redis.serviceName);
```

We could do this by translating tags, for example [opentracing peer tags](https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/tag/Tags.java). Ex. translate "peer.X" to mean server, when a CLIENT_SEND is present.

```java
    Span newSpan = this.tracer.createSpan("redis");
    try {
      newSpan.tag("redis.op", "get");
      newSpan.tag("lc", "redis");
      newSpan.logEvent(Span.CLIENT_SEND);
      return (SomeObj) redisTemplate.opsForHash().get("MYHASH", someObjKey);
    } finally {
      newSpan.tag("peer.service", redisService);
      newSpan.tag("peer.ipv4", redisIpV4);
      newSpan.tag("peer.port", redisPort);
      newSpan.logEvent(Span.CLIENT_RECV);
      this.tracer.close(newSpan);
    }
```

**Comment by singram** [comment]
The tag conventions look great but presumably the close() would then remove the tags and manipulate the annotation entry (the translation you mentioned).  Feels somewhat confusing to add tags explicitly and then have the close() remove/translate them due to implied behavior/convention.

**Comment by marcingrzejszczak** [comment]
Actually I've taken another look at the code and we do support the `peer.service` tag. @singram can you try the code that @adriancole has suggested?

**Comment by marcingrzejszczak** [comment]
ping @singram

**Comment by singram** [comment]
@marcingrzejszczak Sorry for the slow response, I'll give this a whirl later today and report back.

**Comment by singram** [comment]
@marcingrzejszczak this worked great.  Only thing I'd stress in the document is not to manually add a 'sa' tag otherwise this fails.  Thanks!!

**Comment by marcingrzejszczak** [comment]
Awesome!! Care to file a PR to the docs? :D

**Comment by singram** [comment]
LOL, yeah NP, might not get to it today though :-)
