### ISSUE TITLE
Unresolved compilation - Lambda expression for Java in unit tests

### ISSUE THREAD

**Issue by daniellavoie** [spring-cloud/spring-cloud-sleuth#347]
Hello,

I tried to follow up the project build instruction but the project is being detected as Java 7 by m2e. I'm getting compilation errors from Eclipse and `mvnw` regarding lambda expressions from the unit tests. I am actually surprised to see some Unit Test making use of lambda expression. Did I miss something on the project set up ?

Many thanks.

Regards,
Daniel

**Comment by marcingrzejszczak** [comment]
You have to turn on in your IDE the Ide profile. It will turn on java8. Mind you that we use java8 only for tests

**Comment by daniellavoie** [comment]
thanks @marcingrzejszczak . Went too fast over the doc. Fixed my issue ;)

**Comment by marcingrzejszczak** [comment]
No problem :)
