### ISSUE TITLE
Support for tracing the WebService  via WebServiceTemplate

### ISSUE THREAD

**Issue by prateekvjain** [spring-cloud/spring-cloud-sleuth#348]
We have added support for RestTemplate, by having the filter injected.
Can we have the same thing done for the webservicetempalte. I have attached files , which we can plan to add to spring sleuth core, please let me know your thoughts.

[ZipkinContribution.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/377424/ZipkinContribution.zip)

**Comment by marcingrzejszczak** [comment]
Hi @prateekvjain . Thanks a lot for the issue. Can you file it as a PR instead of sending it in a zip file? :) That would help a lot!

**Comment by marcingrzejszczak** [comment]
Ping! @prateekvjain

**Comment by marcingrzejszczak** [comment]
Final Ping?

**Comment by rdramana85** [comment]
@marcingrzejszczak Not sure if this is the right place to ask this question - Does Spring cloud sleuth support Webservicetemplate automatically like Resttemplate? Or do I have to annotate with @NewSpan so that it is instrumented and sent to zipkin ?

**Comment by marcingrzejszczak** [comment]
I've answered your question on StackOverflow (https://stackoverflow.com/questions/44762961/spring-cloud-sleuth-with-webservicetemplate). Please don't cross post.

**Comment by jamesddube** [comment]
Is this something that will be considered in the future (adding Instrumentation to webservicetemplate) 
or we can do a PR? @marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
Nothing until now. If this gets more attention then we'll consider adding this feature.

**Comment by rummy123** [comment]
I am still looking for help with  webservicetemplate support  for sleuth?

**Comment by arefaydi** [comment]
webservicetemplate instrumentation support would be greate.
