### ISSUE TITLE
Sleuth is not able to close spans when not using hystrix in a FeignClient

### ISSUE THREAD

**Issue by thyzzv** [spring-cloud/spring-cloud-sleuth#350]
When disabling hystrix with feign.hystrix.enabled = false 
we still get o.s.cloud.sleuth.util.ExceptionUtils: "Tried to close span but it is not the current span" warnings.
In the end we have a lot of open traces in our application causing a OOM.

We don't use the feign integrated hystrix as we wrap the feign client's in a separated hystrix client.

Attached is a simple example project demonstrating the issue. It will log the warnings in the console.
unzip the test and run with mvn spring-boot:run
[sleuthspan-test.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/378251/sleuthspan-test.zip)

**Comment by marcingrzejszczak** [comment]
@thyzzv can you post that as a project on Github please?

**Comment by thyzzv** [comment]
[sleuthspan-test](https://github.com/thyzzv/sleuthspan-test)

**Comment by marcingrzejszczak** [comment]
Thanks I'll try to take a look ASAP

**Comment by marcingrzejszczak** [comment]
Fixed in Snapshots - you can check it out yourself but I've already checked it against your samples. Thanks a lot for providing the sample - it was really helpful.

**Comment by thyzzv** [comment]
Great! I've confirmed it in my small test, and I'am rolling it through our OTAP now.
