### ISSUE TITLE
When continuing a Span, Hystrix is not adding tags

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#352]
From what I see in the `SleuthHystrixConcurrencyStrategy` we've got this code

```
@Override
		public S call() throws Exception {
			Span span = this.parent;
			boolean created = false;
			if (span != null) {
				span = this.tracer.continueSpan(span);
			}
			else {
				span = this.tracer.createSpan(HYSTRIX_COMPONENT);
				this.tracer.addTag(Span.SPAN_LOCAL_COMPONENT_TAG_NAME, HYSTRIX_COMPONENT);
				this.tracer.addTag(
						this.traceKeys.getAsync().getPrefix()
								+ this.traceKeys.getAsync().getThreadNameKey(),
						Thread.currentThread().getName());
				created = true;
			}
			try {
				return this.callable.call();
			}
			finally {
				if (created) {
					this.tracer.close(span);
				}
				else {
					this.tracer.detach(span);
				}
			}
		}
```

so if we're using for example Javanica (`@HystrixCommand`) and we're continuing a SPan, then we're not setting tags from Hystrix. I think that it's wrong - regardless of the fact whether we're starting or continuing a Span we could add the tags - they can be helpful in debugging.

cc @adriancole

**Comment by adriancole** [comment]
is it possible for hystrix to re-enter a span it created? in that case, it might overwrite the thread name (which might be ok). Also, is it possible another thread added local component?

not saying I feel strongly about this, but this might be a place where we either say "last wins" or "set if unset"

**Comment by marcingrzejszczak** [comment]
I'd be consistent with the approach that if sth has been set then let's not override it.
