### ISSUE TITLE
Adding sleuth starter stops actuator endpoint customisations

### ISSUE THREAD

**Issue by darkmuse** [spring-cloud/spring-cloud-sleuth#365]
In my apps I move the info endpoint to /ping with this application.properties entry:
`endpoints.info.id=ping`
But if I add a dependency to sleuth this "redirect" stops working
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-sleuth</artifactId>
	<version>1.0.1.RELEASE</version>
</dependency>
```

**Comment by marcingrzejszczak** [comment]
Could you please try it with Sleuth starter 1.0.4.RELEASE ?

**Comment by darkmuse** [comment]
I had the same issue with 1.0.4.RELEASE
But I found that by updating to spring boot starter 1.3.7.RELEASE I could get this to work by setting 
`endpoints.info.path=/ping`
I think from the docs that the endpoints.{name}.id variable should also change the path?

Also, thank you for this sleuth project, it could be exactly what I am looking for after starting to implement something similar myself. Now I just have to make it work for non-jmsTemplate, camel jms routes to keep other team members happy!

**Comment by marcingrzejszczak** [comment]
I can see in the docs only this http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-customizing-endpoints - it seems that you have to pass `path`.

It's really awesome to hear such nice words :) 

Can you elaborate on `non-jmsTemplate` ? You're saying that `non-jmsTemplate` == `camel jms` routes? If you need to instrument Camel check this out - https://github.com/4finance/micro-infra-spring/blob/master/micro-infra-camel/src/main/java/com/ofg/infrastructure/camel/CorrelationIdOnCamelRouteConfiguration.java . as far as I see it's already integrated with Sleuth so just copy paste that :)

**Comment by darkmuse** [comment]
I have other work to complete first, but I'll check out that camel github as soon as I can. At a glance it does look to do what I need, thank you.

**Comment by marcingrzejszczak** [comment]
Np!
