### ISSUE TITLE
Documentation about UI Zipkin server is wrong

### ISSUE THREAD

**Issue by FrontierPsychiatrist** [spring-cloud/spring-cloud-sleuth#375]
[This line](https://github.com/spring-cloud/spring-cloud-sleuth/blame/master/docs/src/main/asciidoc/spring-cloud-sleuth.adoc#L297) states that the server will be an UI server, but the dependency to

    <groupId>io.zipkin.java</groupId>
    <artifactId>zipkin-autoconfigure-ui</artifactId>

has to be added to get the UI. Also the link to the repository leads to a 404.

**Comment by marcingrzejszczak** [comment]
Thanks a lot! :)
