### ISSUE TITLE
spring.application.name is not read from application.properties for custom logback-spring.xml

### ISSUE THREAD

**Issue by ashishkp** [spring-cloud/spring-cloud-sleuth#376]
It is found that spring.application.name is not read from application.properties for custom logback-spring.xml

We have to add bootstrap.yml with "spring.application.name".

**Comment by dsyer** [comment]
That's not really anything to do with Spring Cloud Sleuth. It's also in the category of "yes, but so what?" I guess we could document it in spring-cloud-context.
