### ISSUE TITLE
1.0.4 Modifications to HttpMessageConverters via WebMvcConfigurerAdapter are not realized when TraceFeignDecoder is invoked

### ISSUE THREAD

**Issue by bitsofinfo** [spring-cloud/spring-cloud-sleuth#377]
Using 1.0.4

I have a need to register a custom jackson `JsonDeserializer` for a particular class to handle certain responses from `@FeignClient` calls.

I took the approach below, using `WebMvcConfigurerAdapter` to just customize the `ObjectMapper` used in the default spring `MappingJackson2HttpMessageConverter` 

The problem I am facing is that my deserializer code below is never invoked and the instance of `MappingJackson2HttpMessageConverter` who's `ObjectMapper` I am customizing is completely different than the one which appears to be invoked by `TraceFeignDecoder`/`SpringDecoder` when my Feign client response is being processed.

Not sure if I am customizing the wrong `HttpMessageConverter` or the ones used by  `TraceFeignClientAutoConfiguration` are completely different.

A bit lost as to what I need to be doing or if this is a bug

```
@Configuration
@EnableWebMvc
public class MyConfig extends WebMvcConfigurerAdapter {

    @Override
	public void extendMessageConverters(List<HttpMessageConverter<?>> converters) {

		for (HttpMessageConverter<?> c : converters) {
			if (c instanceof MappingJackson2HttpMessageConverter) {
				MappingJackson2HttpMessageConverter toMod = (MappingJackson2HttpMessageConverter)c;
				
				SimpleModule module = new SimpleModule();
				 module.setDeserializerModifier(new BeanDeserializerModifier()
				    {
				      @Override public JsonDeserializer<?> modifyDeserializer(DeserializationConfig config, 
				    		  												  BeanDescription beanDesc, 
				    		  												  JsonDeserializer<?> deserializer) {
				        if (beanDesc.getBeanClass() == MyClass.class) {
				        	return new MySpecialDeserializer(deserializer);
				        }
				        return deserializer;
				      }
				    });
				 
				toMod.getObjectMapper().registerModule(module);
			}
		}
		
	}
```

**Comment by marcingrzejszczak** [comment]
Hi! Can you check that with snapshots cause there was some serious Frign refactoring that should simplify things

**Comment by marcingrzejszczak** [comment]
@bitsofinfo ping? We're on the verge of a release and I'd like to know if that's working or not :P

**Comment by bitsofinfo** [comment]
I just tried it, I don't see it being invoked unfortunately.

**Comment by marcingrzejszczak** [comment]
I think it's not the case of Sleuth anymore. Currently the only instrumentation in Sleuth that we do is that of `TraceFeignClient`. I think you should check out on Feign / Spring Cloud Gitter on how to `register a custom jackson JsonDeserializer for a particular class to handle certain responses from @FeignClient calls`.
