### ISSUE TITLE
Brixton.SR4 breaking the sleuth

### ISSUE THREAD

**Issue by PreetamMyneni** [spring-cloud/spring-cloud-sleuth#380]
We have a Spring Non-Blocking IO rest service wrapped around java.util.concurrent.Callable.
My Logs show that sleuth is adding a new TraceId and Span Id when reaching my controller.
When i rolled back to Brixton.RELEASE its working
At Filter log I am getting start Span and Trace.
But at controller i see different Trace and and span is not matching the new trace.

**Comment by marcingrzejszczak** [comment]
Can you post your sample somewhere?

**Comment by PreetamMyneni** [comment]
Here is it https://github.com/PreetamMyneni/sleuthNonBlockingIo
Hit http://localhost:8080/test
