### ISSUE TITLE
Zipkin Server & Marketplace.

### ISSUE THREAD

**Issue by hvandenb** [spring-cloud/spring-cloud-sleuth#381]
Is Zipkin as a CloudFoundry service for the marketplace is that on the roadmap?

**Comment by spencergibb** [comment]
This is not the correct forum for this question.

**Comment by hvandenb** [comment]
@spencergibb I assume this would be a question for Zipkin team. However, give that Sleuth can bind to Zipkin http or streaming would we not want the ability to simply bind to a Zipkin service?

**Comment by spencergibb** [comment]
@hvandenb I agree. @csterwa the spring cloud services integration with cloud foundry. Get in touch with him.
