### ISSUE TITLE
Missing http headers binary annotations in newer verstions

### ISSUE THREAD

**Issue by fabioranfi** [spring-cloud/spring-cloud-sleuth#383]
using Sleuth verstion 1.0.0.RELEASE everything works fine:

![screen shot 2016-08-12 at 15 30 24](https://cloud.githubusercontent.com/assets/19411029/17856697/0849fc78-687f-11e6-9166-fca7db8ccfbd.png)

while using Sleuth versions 1.0.1.RELEASE or 1.0.3.RELEASE the binary annotation that should contain those tags is empty and Zipkin looks like this:

![screen shot 2016-08-12 at 15 45 05](https://cloud.githubusercontent.com/assets/19411029/17856752/43f4a566-687f-11e6-8982-e70b1d3a6f69.png)

Zipkin's version is the same, the public image openzipkin/zipkin:1.6.0

**Comment by marcingrzejszczak** [comment]
This is deliberate - https://github.com/spring-cloud/spring-cloud-sleuth/pull/292 . Since all the tracing information is on the client side, we didn't want to duplicate this data on the server side.
