### ISSUE TITLE
Start adding error annotation

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#384]
With Zipkin 1.3 https://github.com/openzipkin/zipkin/releases/tag/1.3.0 and https://github.com/openzipkin/zipkin/issues/1140 `error` annotations can be resolved into a nice visualization in the UI.

**Comment by adriancole** [comment]
here's some hints here https://github.com/openzipkin/openzipkin.github.io/issues/52

main thing is that we shouldn't have a span dangling (ex only cr) as the span detail tab looks off.
