### ISSUE TITLE
`X-B3-*` headers are repeated when going through a Zuul Proxy

### ISSUE THREAD

**Issue by snussbaumer** [spring-cloud/spring-cloud-sleuth#385]
When a request goes through a Sleuth instrumented Zuul Proxy and this request is then routed through an other Sleuth instrumented spring microservice, the response will contain the set of `X-B3-*` headers twice.

For example : 
```
X-B3-Sampled: 1
X-B3-Sampled: 0
X-B3-SpanId: c3e720a1069666d3
X-B3-SpanId: 8fea2b0be533c5a6
X-B3-TraceId: c3e720a1069666d3
X-B3-TraceId: c3e720a1069666d3
```

This is a simple test to reproduce the problem. It fails on the `assertThat(result.getHeaders().get(Span.TRACE_ID_NAME)).hasSize(1);` line, because there are 2 `Span.TRACE_ID_NAME` headers :

```java
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = CheckHeadersTest.ZuulApplication.class)
@WebIntegrationTest
public class CheckHeadersTest {

    private static Logger log = LoggerFactory.getLogger(CheckHeadersTest.class);

    @Test
    public void verifyTraceHeadersPresentOnlyOnce() {
        RestTemplate restTemplate = new RestTemplate();
        ResponseEntity<String> result = restTemplate.exchange("http://localhost:8080/test", HttpMethod.GET, null,
                String.class);
        assertThat(result.getBody()).isEqualTo("OK");
        log.info("Headers : {}", result.getHeaders());
        assertThat(result.getHeaders().get(Span.TRACE_ID_NAME)).hasSize(1);
    }

    @EnableZuulProxy
    @SpringCloudApplication
    @RestController
    public static class ZuulApplication {

        private static Logger log = LoggerFactory.getLogger(ZuulApplication.class);

        @RequestMapping(method = RequestMethod.GET, path = "/real/test")
        public String test() {
            log.info("test is being called");
            return "OK";
        }

        public static void main(String... args) {
            SpringApplication.run(ZuulApplication.class, args);
        }

    }

}
```

this is the bootstrap.yml route that goes with it : 

```
zuul:
  ignoredServices: '*'
  routes:
    passthru:
      path: /test
      url: http://localhost:8080/real
      sensitiveHeaders:
      stripPrefix: false
```

The reproduction project is available here : https://github.com/snussbaumer/sleuth-zuul-issue-repro

Let me know if you have any question.

**Comment by marcingrzejszczak** [comment]
Hey @snussbaumer - can you check `Brixton.SR5` ? Cause we've removed returning any tracing information in the headers (that was a security issue). Now the test won't pass cause there are no headers in the response.

**Comment by snussbaumer** [comment]
Hello @marcingrzejszczak 

Thanks. I can see that. 
For debugging purposes it can be quite interesting to have the traceId  (curl + you just throw the traceId in Kibana to see what's going on) but I suppose it can be enabled/disabled upon a certain condition, no ?

I'll check that a bit more as soon as I find some time.

Thanks a lot !

**Comment by marcingrzejszczak** [comment]
Hmm you could create your own filter and add this information to the response yourself. That you could enable on a switch as you suggested.

**Comment by adriancole** [comment]
Also you can generate and pass a trace and span id yourself. This is what
the chrome plugin does though it would be neat if someone made a b3curl
wrapper to do this via shell (if noone hasnt yet)

**Comment by snussbaumer** [comment]
Oooh, I didn't know that. Thanks for all the hints guys, I really appreciate it.
