### ISSUE TITLE
sleuth+feign+zipkin request interceptor question

### ISSUE THREAD

**Issue by zhoffice** [spring-cloud/spring-cloud-sleuth#390]
I have sleuth+feign+zipkin run in my project, but TraceFeignRequestInterceptor does not work, I found bean "traceIdRequestInterceptor" first inital failed because Tracer not load. When traceWebFilter initalized, traceIdRequestInterceptor could normal load, but it does not in the feign.Feign.Builder.requestInterceptors list.
How to fix this?

**Comment by zhoffice** [comment]
Error is:
org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'sleuthTracer': Requested bean is currently in creation: Is there an unresolvable circular reference?
But why?

**Comment by zhoffice** [comment]
It is same as [https://github.com/spring-cloud/spring-cloud-sleuth/issues/307](url)

**Comment by zhoffice** [comment]
I think there still have a problem, if I remove AlwaysSampler, it works, but when I add AlwaysSampler back,  
the traceIdRequestInterceptor still no effect.

**Comment by marcingrzejszczak** [comment]
Can you post an example? Are you sure you're using Brixton.SR5 ?

**Comment by zhoffice** [comment]
https://github.com/zhoffice/spring-cloud-framework
relative projects:
demo-parent
demo-common
demo-eureka-server
demo-service
demo-service2

https://github.com/zhoffice/spring-cloud-framework/blob/master/demo-service/src/main/java/com/cnwidsom/Application.java

**Comment by marcingrzejszczak** [comment]
I've managed to start the demo-service without any problems.

Remember about the part that Dave mentioned:

> If you break up the config class a bit it will work. Probably if you just refrain from @Autowiring the (unused) feign client bean into the class that defines the sampler @Bean it will work (there's a cycle there).

**Comment by zhoffice** [comment]
It could startup, but traceIdRequestInterceptor does not work, can you reproduce this?

**Comment by marcingrzejszczak** [comment]
I don't understand your problem... I don't have this issue when I start the app:

```
org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'sleuthTracer': Requested bean is currently in creation: Is there an unresolvable circular reference?
```

Can you write step by step what to do to reproduce the error?

**Comment by zhoffice** [comment]
1.Startup demo-eureka-server,demo-service,demo-service2
2.Set breakpoint on TraceFeignRequestInterceptor.apply Method
3.visit http://localhost:8080/demo2
4.If no AlwaysSampler, it will break on the point, if add AlwaysSampler, the breakpoint will not trigger

**Comment by marcingrzejszczak** [comment]
Can you give me a bash script to run it or add a pom in the root folder that add some submodules? I mean I'd have to import 3 projects, run them somehow etc. Could you help me with that? Can you run a bash script that start all the necessary projects and then tell me in which project I'd have to set the breakpoint?

**Comment by zhoffice** [comment]
I have add a pom.xml under root folder.
1.Run "mvn clean install" under root folder
2.Run "mvn spring-boot:run"  in order demo-eureka-server,demo-service,demo-service2
3.Set Breakpoint on method void org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignRequestInterceptor.apply(RequestTemplate template) in spring-cloud-sleuth-core-1.0.6.RELEASE-sources.jar

**Comment by zhoffice** [comment]
Fixed. Add @Lazy annotation on proxy class, then it works.

**Comment by marcingrzejszczak** [comment]
:+1:
