### ISSUE TITLE
Trace/Span IDs get clobbered when using Jetty

### ISSUE THREAD

**Issue by shanman190** [spring-cloud/spring-cloud-sleuth#394]
When using the latest release version of Spring Sleuth 1.0.6.RELEASE and Spring Boot 1.3.7.RELEASE using the embedded Jetty runtime, the Trace ID and Span IDs are clobbered on an unsuccessful request. (eg: not 2xx response code). This causes some oddness where when observing the log messages, those filters appear to not be part of the trace, when in fact they are.

```
2016-09-06 16:32:54.708 DEBUG [app,cdd75af152f020e0,cdd75af152f020e0,false] 14960 --- [tp1935870377-24] o.s.w.f.CommonsRequestLoggingFilter      : Before request [uri=/hello]
2016-09-06 16:32:54.736 DEBUG [app,cdd75af152f020e0,cdd75af152f020e0,false] 14960 --- [tp1935870377-24] o.s.w.f.CommonsRequestLoggingFilter      : After request [uri=/hello]
2016-09-06 16:32:57.390 DEBUG [app,adc8c2ac62559daa,adc8c2ac62559daa,false] 14960 --- [tp1935870377-23] o.s.w.f.CommonsRequestLoggingFilter      : Before request [uri=/hello2]
2016-09-06 16:32:57.437 DEBUG [app,,,] 14960 --- [tp1935870377-23] o.s.w.f.CommonsRequestLoggingFilter      : After request [uri=/hello2]
```

This is just using a simple hello world spring boot application, where the first call in the log lines above is to the `/hello` endpoint, where the service response correctly with `Hello, world!` and a 200 status code. The second set is calling the `/hello2` endpoint, which does not exist and results in a 404 response code. As you can see though, the second call results in the trace being prematurely truncated.

This behaviour does not occur when using the Tomcat runtime.

**Comment by marcingrzejszczak** [comment]
That's interesting... Can you post a sample so that we can check this out?

**Comment by marcingrzejszczak** [comment]
It's highly probable that for some reason the Sleuth filter is executed after the `Commons...` one. We already had one issue like that and it was fixed. Maybe with Jetty sth's different

**Comment by shanman190** [comment]
Yeah, I can put a sample up here after a little bit. 

From the little bit of debugging that I was doing on the Jetty side, it seemed like there were two filter chains that the Trace filter was associated to. One was with just it and the servlet and the other with the Trace, Commons, and the servlet.

**Comment by marcingrzejszczak** [comment]
ah.. that might be the case. That's extremely interesting. Once you have it running ping me cause I'm curious to debug it too :)

**Comment by shanman190** [comment]
Alright. I've got a test project setup now. There are two branches configured. Jetty and Tomcat running the respective containers in each.

https://github.com/shanman190/sleuth-error-demo

**Comment by marcingrzejszczak** [comment]
Ok so it seems that for Jetty you have to manually provide the dispatch for your filter. If you write your config like this:

```
@Bean FilterRegistrationBean filterRegistrationBean() {
		FilterRegistrationBean bean = new FilterRegistrationBean();
		bean.setFilter(commonsRequestLoggingFilter());
		bean.setOrder(Ordered.LOWEST_PRECEDENCE);
		bean.setDispatcherTypes(DispatcherType.REQUEST, DispatcherType.ERROR, DispatcherType.ASYNC, DispatcherType.FORWARD, DispatcherType.INCLUDE);
		return bean;
	}

	public CommonsRequestLoggingFilter commonsRequestLoggingFilter() {
		CommonsRequestLoggingFilter filter = new CommonsRequestLoggingFilter();
		filter.setIncludeQueryString(true);
		filter.setIncludeClientInfo(true);
		return filter;
	}
```

it works fine.

**Comment by shanman190** [comment]
Is that FilterRegistrationBean mentioned somewhere in the Spring documentation being needed for Jetty usage? I'm guessing it's more a Spring Boot quirk when using the Jetty runtime, but probably something others will run into possibly with things like this.

**Comment by marcingrzejszczak** [comment]
Actually I haven't seen that. Let's ping @snicoll @philwebb about this? ^^

**Comment by philwebb** [comment]
Thanks. I've raised https://github.com/spring-projects/spring-boot/issues/6850 to try and dig into this a little more.
