### ISSUE TITLE
Add integration support for Google Stackdriver Trace

### ISSUE THREAD

**Issue by nyilmaz** [spring-cloud/spring-cloud-sleuth#395]
Referencing https://cloud.google.com/trace/api/?hl=en_US,

Would you consider adding pushing trace-span data to Google's Stackdriver trace? They have a Java API [here](https://github.com/GoogleCloudPlatform/cloud-trace-java), but as far as I experienced samples have dependency issues with grpc. Since spring have [oauth2](http://projects.spring.io/spring-security-oauth/docs/oauth2.html) support, REST API may be used as a beginning.

What do you think?

**Comment by adriancole** [comment]
@nyilmaz we're going to move our transport layer to https://github.com/openzipkin/zipkin-reporter-java in the near future. This will include a Sender component which by default will go to zipkin. A sender that does oauth etc will make sense when going to stackdriver, although a zipkin-> stackdriver proxy is also an option.

While you can pad out in the mean time, we need to address 128 bit trace ids (not span ids, just trace ids) for this to work well. Please upvote this change, which I'll be working on shortly.

**Comment by adriancole** [comment]
uhh this change: https://github.com/openzipkin/zipkin/issues/1262

**Comment by cemo** [comment]
@adriancole Is there any progress on this issue? I believe that this is a quick win for `zipkin`. Introducing `zipkin` features into a library without using a backend sounds really cool.

**Comment by mtwo** [comment]
Hey Cemo, I'm the PM for Stackdriver Trace @ Google! We're actually working on something that'll achieve this, which we'll be announcing soon. I'll reply back when we're able to show more to a broader audience.

**Comment by cemo** [comment]
Hey @mtwo! We will be looking forward your news. Thanks for the heads up.

**Comment by mtwo** [comment]
@cemo check [this](https://github.com/GoogleCloudPlatform/stackdriver-zipkin) out. It's a Zipkin collector implementation that forwards trace data to Stackdriver Trace. We'll be publishing the official announcement shortly, but feel free to try it out and let myself and @kevinmdavis and I know what you think.

**Comment by nyilmaz** [comment]
@mtwo now i'm trying `stackdriver-zipkin` adapter but i could not find how to set `ZipkinStackdriverStorageProperties#apiHost`.

**Comment by kevinmdavis** [comment]
Hi @nyilmaz! `ZipkinStackdriverStorageProperties#apiHost` configures the endpoint the collector will use to call the Stackdriver Trace API so the default value of "cloudtrace.googleapis.com" should work for most users. Setting `ZipkinStackdriverStorageProperties#projectId` and configuring the [Google Application Default Credentials](https://developers.google.com/identity/protocols/application-default-credentials) should be enough to setup the collector.

Feel free to open an issue in [GoogleCloudPlatform/stackdriver-zipkin](https://github.com/GoogleCloudPlatform/stackdriver-zipkin/) if you have any other questions.

**Comment by adriancole** [comment]
here's a full blog on the integration.
https://cloudplatform.googleblog.com/2016/12/Stackdriver-Trace-Zipkin-distributed-tracing-and-performance-analysis-for-everyone.html

As far as spring-cloud-sleuth goes, you use the normal `HttpZipkinSpanReporter` which is bundled in the spring-cloud-sleuth-zipkin dependency. There's no difference between using the normal zipkin server and the stackdriver connector. For any server config related concerns, best to use Kevin's advice.

If for some reason the connector isn't possible, and you need to have sleuth send spans directly to stackdriver, I'd suggest raising an issue in https://github.com/GoogleCloudPlatform/stackdriver-zipkin/ for a stackdriver "sender" which is the component that could relatively easily fit where the current http one does.
