### ISSUE TITLE
SPRING_SLEUTH_SAMPLER_PERCENTAGE is not a percentage

### ISSUE THREAD

**Issue by cer** [spring-cloud/spring-cloud-sleuth#397]
Isn't a percentage between 0 and 100%?

**Comment by marcingrzejszczak** [comment]
Since percents as their name suggests are values divided by 100 you can also represent them as a double ( 80% == 80/100 == 0.8). We've decided to go with the double representation :) 

But English is not my native language so maybe we've used a wrong name for the property. @adriancole WDYT?

**Comment by adriancole** [comment]
Maybe threshold is a better term for a 0-1 function?

**Comment by cer** [comment]
I think threshold means something else.
Mathematically speaking this value is a [probability](https://en.wikipedia.org/wiki/Probability), which is a number between 0 and 1

**Comment by adriancole** [comment]
SGTM! thanks, chris

On Mon, Sep 12, 2016 at 11:22 AM, Chris Richardson <notifications@github.com

**Comment by marcingrzejszczak** [comment]
This is a breaking change actually (which I don't like to do). We could allow people to provide entries greater > 0. You could then provide

`SPRING_SLEUTH_SAMPLER_PERCENTAGE=0.5`

or

`SPRING_SLEUTH_SAMPLER_PERCENTAGE=50` 

and that would be the same. I could also provide a new property for version 1.1 and deprecate the old one (but not remove it). I could remove it for 1.2 or sth like that. WDYT?

**Comment by marcingrzejszczak** [comment]
ping @cer ?

**Comment by cer** [comment]
SGTM

**Comment by dsyer** [comment]
What if you actually wanted 0.5% (not completely unlikely)? I think it might be better that we just live with it and document the mistake. Or else introduce a new notation with "%" in it or something (seems like overkill for such a simple thing).
