### ISSUE TITLE
Document how we (don't) support RxJava

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#398]
RxJava doesn't expose the API to do proper instrumentation. The current approach that we have Sleuth is not terrible and (but) it won't be better any time soon. We should describe that in more depth in the documentation together with rationale. Currently in RxJava >= 1.1.9 the Thread names of schedulers have changed and that was the only way we didn't wrap some things in spans. We should update the properties also in Sleuth to reflect that.

CC @smaldini @akarnokd @dsyer

**Comment by smaldini** [comment]
RxJava has introduced the same level of hooking than in reactor for Scheduler from 1.1.8 in RxJavaHooks and onwards so we should be able to apply the Action0 wrapping stuff + clean current dereferencing (outside scheduled action).

**Comment by marcingrzejszczak** [comment]
We've done a WIP for Reactor - https://github.com/spring-cloud/spring-cloud-sleuth/tree/issues_344_reactor_instrumentation . Maybe we could do sth similar for RxJava ?

**Comment by marcingrzejszczak** [comment]
I'll wait for the feedback on https://github.com/spring-cloud/spring-cloud-sleuth/pull/401 since almost identical logic we will be able to do with `RxJavaHooks`.

**Comment by marcingrzejszczak** [comment]
Added small info for `RxJava` that the suggested instrumentation is to use Reactor - https://github.com/spring-cloud/spring-cloud-sleuth/commit/0e50456ab0528c43067db62bf41a708914e11c6c#diff-4e928e7480d29e83ba298eac24ad0ce6R925
