### ISSUE TITLE
o.s.c.sleuth.instrument.zuul.TraceZuulHandlerMappingBeanPostProcessor should not override the provided ZuulHandlerMapping

### ISSUE THREAD

**Issue by strelok1** [spring-cloud/spring-cloud-sleuth#399]
I think this hurts extensibility and when Sleuth is enabled overrides potentially custom implementations of ZuulHandlerMapping with its own TestZuulHandlerMapping which is not accessible (or extensible).

The only reason this class exists (as far as I can see) is to call

`interceptors.add(new TraceHandlerInterceptor(this.beanFactory));`

in `extendInterceptors`.

Can this not be accomplished by just calling: org.springframework.web.servlet.handler.AbstractHandlerMapping#setInterceptors?

```
       @Override
	public Object postProcessBeforeInitialization(Object bean, String beanName)
			throws BeansException {
		if (bean instanceof ZuulHandlerMapping) {
			if (log.isDebugEnabled()) {
				log.debug("Attaching trace interceptor to bean [" + beanName + "] of type [" + bean.getClass().getSimpleName() + "]");
			}
			((ZuulHandlerMapping)bean).setInterceptors(new Object[]{new TraceHandlerInterceptor(this.beanFactory)}); // this will add the interceptor
		}
		return bean;
	}

```

**Comment by marcingrzejszczak** [comment]
Hi! Seems like a very good idea. I think that the reason was that I haven't checked properly what `setInterceptor` does.  You would think that it's setting the interceptors whereas it's adding them which makes a gigantic difference. Thanks!
