### ISSUE TITLE
Documentation: source of tracer instance

### ISSUE THREAD

**Issue by C-Otto** [spring-cloud/spring-cloud-sleuth#402]
The documentation at https://cloud.spring.io/spring-cloud-sleuth/ frequently references a `this.tracer` instance, but does not mention where this instance comes from. I'm struggling with this right now, and would expect at least a hint in the documentation.

**Comment by marcingrzejszczak** [comment]
Hi! There are two issues here.

1) You have found out that by some mistake we've removed the proper index.html content ;) It's been updated. The docs are here https://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html

2) The Tracer interface is described here - https://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_span_lifecycle

**Comment by marcingrzejszczak** [comment]
The code is here - https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Tracer.java

**Comment by C-Otto** [comment]
I found the interface already (it's not too hard to find), but that doesn't give me an instance of it. As a developer already having several own commands extending `HystrixCommand`, I just don't know where to get the tracer instance that is described in the documents (to create the `TraceCommand`).

I might not need this (there seems to be some automatic wrapper?), but I'm still investigating. Nevertheless, the documentation should at least hint at where the tracer is supposed to come from.

**Comment by marcingrzejszczak** [comment]
Spring gives you the instance. Just autowire it. Why would you like to instantiate it? Sure - I'll change the docs to give the FQN

**Comment by C-Otto** [comment]
I don't want to instantiate it, I just need an instance. Autowiring is fine, I did not try it. Seems trivial now. Thank you!
