### ISSUE TITLE
DNS lookup performance bottleneck when DiscoveryClient returns nonexistent host

### ISSUE THREAD

**Issue by s4s0l** [spring-cloud/spring-cloud-sleuth#403]
I was experiencing huge performance problems when using spring-cloud-consul-discovery + feign clients with seluth publising to zipkin. After some investigation I've narrowed it to DNS lookup made by org.springframework.cloud.sleuth.zipkin.DiscoveryClientEndpointLocator. In my case consul was running in docker, and my app was running on host. DiscoveryClient in getLocalServiceInstance is returning host as 'consul'. I believe it is hostname of docker container running consul. Then in DiscoveryClientEndpointLocator there is:

```
private int getIpAddress(ServiceInstance instance) {
        try {
            return InetUtils.getIpAddressAsInt(instance.getHost());
        }
        catch (Exception e) {
            return 0;
        }
    }
```

(see: https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/DiscoveryClientEndpointLocator.java)

This is called for EVERY span. When DNS is cached it's somewhat ok. If DNS lookup is performed, not so ok. If DNS timeouts/nonexistent host it has terrible impact on performance! In my case name 'consul' was not resolved... Another story is why consul-discovery is returning consul agent name as host, but i think it is irrelevant, this can always happen.

**Comment by marcingrzejszczak** [comment]
Thanks a lot for the feedback. I guess caching the result would enough to fix it, wouldn't it?

**Comment by s4s0l** [comment]
Actually it is cached, just figured it out...i think. In FallbackHavingEndpointLocator there is:
```
@Override
	public Endpoint local() {
		this.cachedEndpoint.compareAndSet(null, endpoint());
		return this.cachedEndpoint.get();
	}
```
But if i understand it correctly endpoint() method is called every time anyway?

Answering: I'ts hard for me to talk about it as i just started my adventure with zipkin, but first of all why zipkin needs an Ip address? Would it be possible to just leave hostname? 

If hostname will be cached wouldn't it mess with docker containers being migrated? Or what will happen when ip is changed? I would cache based on unconverted host name + port + serviceId - Until it changes I would leave cachedEndpoint alone....But then what if DNS resolution was only temporary unavailable during first resolution...ok i'm overcomplicating it.

**Comment by s4s0l** [comment]
It would be nice to make zipkinEndpointLocator bean 'conditional on missing bean', cause its hard to work it around:/ It may be usefull for someone hacking his own discovery...

**Comment by spencergibb** [comment]
@s4s0l if you create your bean with the same name you can override it now:
```java
@Bean
public EndpointLocator zipkinEndpointLocator() { /* ... */ }
```

**Comment by s4s0l** [comment]
didn't know that:)

**Comment by marcingrzejszczak** [comment]
@s4s0l how is it going? :>

**Comment by s4s0l** [comment]
Actually great. I'm on vacation. Till 20th November. Sorry but before I left I could not find a moment to finish it, and now all I have is a cell phone;/

**Comment by marcingrzejszczak** [comment]
Ping? :P
