### ISSUE TITLE
Make Span implement AutoCloseable

### ISSUE THREAD

**Issue by C-Otto** [spring-cloud/spring-cloud-sleuth#406]
As hinted at in #405, it is advisable to create and close Spans manually in certain situations. I'd like to use the "try-with-resources" of Java 7 to automatically close the span. However, the interface `AutoCloseable` needs to be implemented for that (and there might be the need to let the `tracer` do the work).

```
try (Span span = tracer.createSpan("x")) {
  doWork();
}
```

**Comment by marcingrzejszczak** [comment]
Yeah currently we don't want to make span autoclosable because as you can see in the `DefaultTracer` `close` method, there is some logic going on. We would have to move it to span and currently we decided not to do so.

**Comment by C-Otto** [comment]
OK, thanks for the awesome feedback :)

**Comment by marcingrzejszczak** [comment]
No problem :) We're help to answer all questions and doubts. If sth is unclear we will update the docs.

**Comment by xak2000** [comment]
*4 years later*: Do the same reasons to not doing this still apply (I can't find `DefaultTracer` class in the current sources)? Just asking.

I investigating spring-cloud-sleuth now and some APIs look very strange and inconvenient. I understand that flexibility of opening and closing a `span` at exact moment you want is important. But still, it's not 95% case. It's more like a 5% case, I think. The API convenience should be focused on 95% case, isn't it? And other 5% can be not very elegant - it's acceptable.

This is how API cloud look:

```
try (Tracer.SpanInScope span = tracer.newScopedSpan("calculateTax")) {
    span.tag("taxValue", taxValue);
    span.annotate("taxCalculated");
}
```

Isn't it much more convenient and clear, than example from the official docs?

```
Span newSpan = this.tracer.nextSpan().name("calculateTax");
try (Tracer.SpanInScope ws = this.tracer.withSpanInScope(newSpan.start())) {
    newSpan.tag("taxValue", taxValue);
    newSpan.annotate("taxCalculated");
}
finally {
    newSpan.finish();
}
```

Why do we need both `Span` and `Tracer.SpanInScope`? I think 95% of the time we don't. Maybe I don't understand something, but Sleuth docs is not helpful here too.

**Comment by marcingrzejszczak** [comment]
Wd have migrated to use the Brave api as the tracer. There's no more defaulttracer. If you gave any issues with that api please file an issue in their repo
