### ISSUE TITLE
HystrixStreamClass gather and send metrics bombarding RabbitMQ

### ISSUE THREAD

**Issue by deepank-sharma** [spring-cloud/spring-cloud-sleuth#414]
I have a microservice application in which I have the following dependencies : 
BOM: Brixton.SR5
spring-cloud-starter-hystrix
spring-cloud-netflix-hystrix-stream
spring-cloud-sleuth-stream
spring-cloud-starter-stream-rabbit

And I have a separate zipkin application which has the following dependencies:
spring-cloud-sleuth-zipkin-stream
spring-cloud-starter-stream-rabbit
zipkin-autoconfigure-ui

Now as soon as I start my µS I see these barrages of messages originating from HystrixStreamClass : 
{"host":{"serviceName":"my-service","address":"10.69.167.68000","port":8073},"spans":[{"begin":1474570413007,"end":1474570413017,"name":"send-metrics","traceId":-3218682980532928746,"spanId":-3218682980532928746,"exportable":true,"tags":{"method":"sendMetrics","class":"HystrixStreamTask","lc":"scheduled"},"logs":[],"durationMicros":9863},{"begin":1474570413007,"end":1474570413018,"name":"gather-metrics","traceId":6497711475647093742,"spanId":6497711475647093742,"exportable":true,"tags":{"method":"gatherMetrics","class":"HystrixStreamTask","lc":"scheduled"},"logs":[],"durationMicros":10818},{"begin":1474570413504,"end":1474570413504,"name":"gather-metrics","traceId":-2118921103880761568,"spanId":-2118921103880761568,"exportable":true,"tags":{"method":"gatherMetrics","class":"HystrixStreamTask","lc":"scheduled"},"logs":[],"durationMicros":88},{"begin":1474570413504,"end":1474570413506,"name":"send-metrics","traceId":8952112925817401868,"spanId":8952112925817401868,"exportable":true,"tags":{"method":"sendMetrics","class":"HystrixStreamTask","lc":"scheduled"},"logs":[],"durationMicros":2427}]}

Now I have tried adding the following 3 parameters to the startup configuration of my microservice as specified in Issue#49.
-Dspring.sleuth.log.slf4j.nameSkipPattern=^.*-metrics.*$
-Dspring.sleuth.integration.enabled=false
-Dspring.sleuth.schedule.enabled=false

I am using a rollingfileappender with JSON Encoder by creating my own logback-spring.xml.

After the skip pattern I could see that it reaches and returns from log method of Slf4jSpanLogger but I still the messages Span Messages in RabbitMQ
So after each step I tried to check if the messges dont reach MQ but I keep getting them there. Can someone help me identify if there is something I am not doing right.

**Comment by marcingrzejszczak** [comment]
Hello! I wonder if that thread is not somehow started by RxJava. If that's the case you can use this pattern  `spring.sleuth.rxjava.schedulers.ignoredthreads` from this class https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/rxjava/RxJavaAutoConfiguration.java to ignore that particular thread. And if not then we'll have to figure out sth else :/

**Comment by deepank-sharma** [comment]
@marcingrzejszczak please feel free to close this issue .
-Dspring.sleuth.schedule.enabled=false
this had to be
-Dspring.sleuth.scheduled.enabled=false
In some solutions it was the first one. Its fine now. Thanks !!

**Comment by marcingrzejszczak** [comment]
No problem! :D
