### ISSUE TITLE
CompletableFuture not showing correctly on Zipkin

### ISSUE THREAD

**Issue by deepank-sharma** [spring-cloud/spring-cloud-sleuth#423]
I have an API Gateway, where I call 3 different services and aggregate response in a helper function. When I use CompletableFuture to call these 3 methods asynchronously I see three different traces in zipkin as compared to one aggregated one. I am also creating a ThreadPooltaskExecutor and passing it to the supplyAsync calls.
Sample code : 

              CompletableFuture<Service1> service1 = CompletableFuture
				.supplyAsync(() -> getService1(), executor);

		CompletableFuture<Service2> service2 = CompletableFuture
				.supplyAsync(() -> getService2(), executor);

		CompletableFuture<Service3> service3 = CompletableFuture
				.supplyAsync(() -> getService3(), executor);

		CompletableFuture<AggregatedResponse> response = CompletableFuture.allOf(service1, service2, service3)
				.thenApply(ignoredVoid -> helper.aggregateResponse(service1.join(), service2.join(), service3.join()));

I am using the following BOM:
<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Brixton.SR5</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

**Comment by marcingrzejszczak** [comment]
Can you try it with latest snapshots cause we were fixing some executor stuff there

**Comment by marcingrzejszczak** [comment]
Ping @deepank-sharma

**Comment by marcingrzejszczak** [comment]
As I wrote in the commit message everything works fine. If you want to pass an executor that executor:

- must a bean
- if that's a custom executor then it will work OOB
- if that's a default taskExecutor you have to wrap it with `LazyTaskExecutor`
