### ISSUE TITLE
Zipkin annotations - cr(ClientReceive) before ss(ServerSend)

### ISSUE THREAD

**Issue by nklmish** [spring-cloud/spring-cloud-sleuth#431]
I have two services developed using spring cloud (tried both Camden.SR1 and Camden.RELEASE) and spring-cloud-starter-zipkin (plain vanilla - no hystrix, rxjava, **async** etc). I am running both services on a single machine, with zipkin **(1.13.1)** running inside a docker container and using and in memory database. 

Service A invokes Service B using `org.springframework.web.client.RestTemplate`. 

It seems that sometime **cr** (client receive) annotation is calculated before **ss**(server send). However, as per[ docs](http://zipkin.io/pages/instrumenting.html)
-  **cr** :  _the client has received the response from the server. This sets the end of the span_ 
- **ss**:  _that the server has completed processing and has sent the request back to the client_. 

A client should receive response only after it was sent by the server.  Below, you can see that for an identical request, I am receiving annotations in different order. 

You can also find the **minimal demo illustrating this problem**  [here](https://github.com/nklmish/issue-cr-ss)

![trace-overview](https://cloud.githubusercontent.com/assets/13149921/19765265/b144951c-9c47-11e6-890b-ac0aac529877.png)

<img width="1156" alt="screen shot 2016-10-27 at 02 56 34" src="https://cloud.githubusercontent.com/assets/13149921/19750644/2c44856a-9bf3-11e6-8a35-6b2b06fcb22a.png"> correct order
<img width="1157" alt="screen shot 2016-10-27 at 02 56 27" src="https://cloud.githubusercontent.com/assets/13149921/19750645/2c6dceca-9bf3-11e6-971d-bf43713f5b7c.png"> cr before ss
<img width="950" alt="screen shot 2016-10-27 at 02 50 37" src="https://cloud.githubusercontent.com/assets/13149921/19751280/60cc57e0-9bf8-11e6-86bb-860383cf851c.png"> cr before ss

[JsonForBadTrace.txt](https://github.com/spring-cloud/spring-cloud-sleuth/files/555532/JsonForBadTrace.txt)

**Comment by adriancole** [comment]
just guessing, but the cr before ss smells like the server-side of the span
is closing late, or it is being added only after the response is fully read
by the client.

**Comment by nklmish** [comment]
After debugging, It looks like a problem is on the side of spring cloud sleuth. I am summarising my findings below :

The spans produced in [ZipkinSpanListener#convert](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/ZipkinSpanListener.java) for a problematic trace looks like this:

trace:id : -8408355936149886654

spanId: 7465565014400962363
name:http/3
duration: 2009000
annotations: [
	name: cs , timestamp: **1477579900806000**
	name: cr,  timestamp: **1477579902815000**
]


spanId: -658298110749710215
name:create-catalog
duration: 155116705
annotations:[
	name: price.fetch , timestamp: 1477579900806000 
]

spanId: -8408355936149886654
name:http/3
duration: 701747627
annotations:[
	name: ss , timestamp: 1477580602530000
	name: sr,  timestamp: 1477579900804000
]

spanId: -3327993844976470951
name: calculate-cost
duration: 2003044
annotations: [
	name: cache.miss , timestamp: 1477579900811000
]


spanId: 7465565014400962363
name: http:/3
duration: 895051493
annotations: [
	name: sr , timestamp: **1477579900808000**
	name: ss,  timestamp: **1477580795832000**
]


OpenZipkin just takes those values (since I am running on the same machine so no clock skew or any other corrections were made). The code which is responsible for rendering simply convert those values via  [traceSummary#mkDurationStr](https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/component_ui/traceSummary.js). Below you can see how those values were calculated:

**cs** : mkDurationStr(**1477579900806000** - 1477579900804000) = 2ms
**sr**:  mkDurationStr(**1477579900808000** - 1477579900804000) = 4ms
**cr** : mkDurationStr(**1477579902815000** - 1477579900804000) = 2.011s
**ss** : mkDurationStr(**1477580795832000** - 1477579900804000) = 895.028s

<img width="903" alt="debug-report" src="https://cloud.githubusercontent.com/assets/13149921/19777400/5672828a-9c78-11e6-8ab2-48aeb8b76744.png">

**Comment by marcingrzejszczak** [comment]
Ping?

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-sleuth/commit/b996de50eafa26c9e5dd091a5ee0dadbb2018048

**Comment by adriancole** [comment]
thank you so much!

**Comment by marcingrzejszczak** [comment]
That was insane to fix :P
