### ISSUE TITLE
Can't override logging.pattern.level into the application.yml file

### ISSUE THREAD

**Issue by fanfansama** [spring-cloud/spring-cloud-sleuth#432]
I want remove the yellow color from the log pattern.  
I can't ovveride it into my application.yml file, only with system env

"logging.pattern.level",
"%clr(%5p) %clr([${spring.application.name:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow}");

**Comment by marcingrzejszczak** [comment]
Yes and it's described in the documentation how to change it. Please check http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html the `Logback setup` section.  Over there you have to provide a custom `logback-spring.xml` file and change it there.

**Comment by fanfansama** [comment]
I dit it also Sleuth inject again automatically his pattern ...

`[service1,,,] [service1,,]`

**Comment by marcingrzejszczak** [comment]
Can you post your sample somewhere?

**Comment by marcingrzejszczak** [comment]
Here you have an example - https://github.com/spring-cloud-samples/sleuth-documentation-apps/blob/master/service1/src/main/resources/logback-spring.xml

**Comment by fanfansama** [comment]
I can't post my code ...
It's an encoding file problem on Windows, not on Linux.
Thanks for your help

**Comment by marcingrzejszczak** [comment]
So can we close this?

**Comment by fanfansama** [comment]
yes you can
 thx
