### ISSUE TITLE
spring.sleuth.zuul.enabled set to false

### ISSUE THREAD

**Issue by altfatterz** [spring-cloud/spring-cloud-sleuth#434]
Using this configuration in the `foo-service`

```
spring:
  application:
    name: foo-service
  sleuth:
    sampler:
      # by default 10% of requests are sampled, here we say sample all requests
      percentage: 1.0
    zuul:
       enabled: false
```

with a zuul route to another `bar-service`

```
zuul:
  routes:
    proxy:
      url: http://localhost:8081
```

when accessing `/proxy` on the `foo-service` I see in the logs of `foo-service`:

```
2016-10-30 19:32:30.105 DEBUG [foo-service,d2e581ff150953ea,d2e581ff150953ea,true] 72489 --- [nio-8080-exec-4] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing GET request for [/proxy]
2016-10-30 19:32:30.105 DEBUG [foo-service,d2e581ff150953ea,d2e581ff150953ea,true] 72489 --- [nio-8080-exec-4] o.s.web.servlet.DispatcherServlet        : Last-Modified value for [/proxy] is: -1
2016-10-30 19:32:30.112 DEBUG [foo-service,d2e581ff150953ea,d2e581ff150953ea,true] 72489 --- [nio-8080-exec-4] o.s.web.servlet.DispatcherServlet        : Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2016-10-30 19:32:30.112 DEBUG [foo-service,d2e581ff150953ea,d2e581ff150953ea,true] 72489 --- [nio-8080-exec-4] o.s.web.servlet.DispatcherServlet        : Successfully completed request
```

Shouldn't be `false` everywhere meaning that is not exportable? 

And when I see RabbitMQ I see the adapted spans also withe `exportable` set to `true`, only tags are missing

```
"tags": {
        "http.path": "/proxy",
        "http.url": "/proxy",
        "http.status_code": "200",
        "http.method": "GET",
        "lc": "zuul"
      },
```

Is this the expected behaviour to disable the zuul support with `spring.sleuth.zuul.enabled` set to `false`?

**Comment by marcingrzejszczak** [comment]
So basically when you set

```
spring.sleuth:
    sampler:
      # by default 10% of requests are sampled, here we say sample all requests
      percentage: 1.0
```

then all your requests will be sampled thus you will have `true` - that the spans are exportable. When your span is sampled then you'll have the tags passed. I kind of don't get the last section of the issue. Can you please post a sample somewhere so I can take a closer look?

**Comment by altfatterz** [comment]
Thanks Marcin.

In my example I see that when the `percentage` is set to `1.0` and I disable zuul with `spring.sleuth.zuul.enabled=false`  then the tags are not passed.

Here is my example:

https://github.com/altfatterz/zuul-sleuth-demo

The `foo-service` creates a zuul proxy to `bar-service`. Initially the zuul proxy is enabled, everything works as [expected](https://github.com/altfatterz/zuul-sleuth-demo/blob/master/span1-zuul-enabled.json). The tags are there.

If you disable the zuul proxy and send a request again

```
curl http://localhost:8080/proxy
```

in rabbitmq in the `sleuth.sleuth` queue you can see the span does not have tag. https://github.com/altfatterz/zuul-sleuth-demo/blob/master/span4-zuul-disabled.json

Am I missing something here?

**Comment by marcingrzejszczak** [comment]
Btw which tags would you expect? You've disabled Zuul sleuth support so it's not working, right? Maybe I'm missing sth but can you describe what would be the desired state?

**Comment by altfatterz** [comment]
yes, zuul sleuth support is disabled with that flag, but you are right those tags which I am missing are related to the zuul component.

```
{
      "begin": 1478869360097,
      "end": 1478869360278,
      "name": "http:/proxy",
      "traceId": 7541390901139541147,
      "parents": [
        7541390901139541147
      ],
      "spanId": -4406636903463240345,
      "exportable": true,
      "tags": {
        "http.path": "/proxy",
        "http.url": "/proxy",
        "http.status_code": "200",
        "http.method": "GET",
        "lc": "zuul"
      },
      "logs": [
        {
          "timestamp": 1478869360097,
          "event": "cs"
        },
        {
          "timestamp": 1478869360278,
          "event": "cr"
        }
      ],
      "durationMicros": 181457
    },
``` 

became

```
{
      "begin": 1478869814434,
      "end": 1478869814434,
      "name": "http:/proxy",
      "traceId": 7454847378209770775,
      "parents": [
        7454847378209770775
      ],
      "spanId": -4634459219756515098,
      "exportable": true,
      "logs": [],
      "durationMicros": 116
    }
```

Which I guess is the correct behaviour, no issue here then, can be closed.

**Comment by marcingrzejszczak** [comment]
Yeah :) were on the same page then. Cool :)
