### ISSUE TITLE
Support for web tracing without Spring Web MVC

### ISSUE THREAD

**Issue by qerub** [spring-cloud/spring-cloud-sleuth#436]
Previous to Sleuth 1.0.3 it was possible to use web tracing for servlets without having Spring Web MVC on the classpath. Nowadays `TraceWebAutoConfiguration` `@Import`s `WebMvcConfigurerAdapter` via `TraceWebMvcConfigurer`. I use Sleuth in a couple of applications together with Apache CXF with no Web MVC controllers and would prefer to not have to drag in Web MVC or reimplement `TraceWebAutoConfiguration` to get tracing. Is this a setup you want to support? I could provide a patch that splits `TraceWebAutoConfiguration` into two.

**Comment by marcingrzejszczak** [comment]
Cool. Go ahead. Also please add info to javadocs about it so we don't forget and split it unnecessarily again

**Comment by qerub** [comment]
I've now created pull request #442 against `master`.

Is the comment good enough?

The same patch applies cleanly to `1.0.x` and `1.1.x` to. Should I open separate pull requests or will you handle that?

**Comment by marcingrzejszczak** [comment]
The comment is awesome, thanks a lot for the contribution.

Patched `1.0.x` in https://github.com/spring-cloud/spring-cloud-sleuth/commit/cd2b0fd0f4be38387cd53534dc9591b1917eb74c and `1.1.x` https://github.com/spring-cloud/spring-cloud-sleuth/commit/e0a20b205fc8499bf5924837b00817761587cab0
