### ISSUE TITLE
Retrieve Span class without any dependencies

### ISSUE THREAD

**Issue by alexandrenavarro** [spring-cloud/spring-cloud-sleuth#444]
Hi,

This is my use case. I have a jar with model classes for my Rest Api. I used the Span class in some of my model class for zipkin.
In my model lib, I don't want to have any dependencies except jackson annotation lib.
So as I added Span, I need to have a dependency to spring-cloud-sleuth-core and some dependencies of spring and Span class use some spring utils classes.

Is it possible to reduce the dependencies of Span class to minimum and generate a very basic dependencis.
If you are ok with this idea, I can propose a pull request with the modification I suggest you.
Tell me what do you think about it?

**Comment by marcingrzejszczak** [comment]
I think that what you're doing is wrong. Why do you have a tracing library dependency inside your model? That seems like a mistake (not to mention that sharing your model seems to be fishy but let's leave that aside). Your model should be completely framework agnostic.

**Comment by alexandrenavarro** [comment]
You are right, I thought there is a good reason to do it but it was just to go fast to develop it. Sorry for the issue.

**Comment by marcingrzejszczak** [comment]
No problem! We're here to help and have those sort of discussions :)
