### ISSUE TITLE
Spans are not closed in case of void return type in Feign

### ISSUE THREAD

**Issue by evredinka** [spring-cloud/spring-cloud-sleuth#448]
The scenario is: client calls service A, service A calls service B through Feign, expected 2 spans created.
When service A -> service B returns some entity (Method in Feign interface has returned type), two spans are created as expected
When service A -> service B returns no entity* (Method in Feign interface has void returned type), no spans are created. Warning is generated:
`o.s.cloud.sleuth.util.ExceptionUtils: Tried to close span but it is not the current span: [Trace: 4a56eb3befd096fa, Span: 4a56eb3befd096fa, exportable=false].  You may have forgotten to close or detach [Trace: 4a56eb3befd096fa, Span: 64775dd1b50b8be2, exportable=false]`

* no entity - Feign call actually returns Response status 200, but without response body

The reason seems to be is when Feign returns a Response - org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignDecoder is called and close a Span created during Feign call. But when there is no Response body, decoder is never called and Span is never closed.

test project to reproduce https://github.com/evredinka/sleuth-test
**sleuth version: 1.0.10.RELEASE**

**Comment by evredinka** [comment]
fixed by adding current version of spring-cloud-sleuth-core:
`<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-core</artifactId>
            <version>1.0.10.RELEASE</version>
</dependency>`

**Comment by marcingrzejszczak** [comment]
Good to know :) there was a major rewrite at some point that should have fixed most issues
