### ISSUE TITLE
SpanId, TraceId, ParentSpanId lose leading zeros

### ISSUE THREAD

**Issue by swetharepakula** [spring-cloud/spring-cloud-sleuth#449]
Hello,

When using the spring sleuth span library, we noticed that since the Ids are stored as a Long, we lose the leading zeros. In zipkin tracing since we expect a 64 bit Id, this can cause issues since the Id is randomly generated. Is there thoughts to add some toString, or toHexString which mandates the formatting of the Id?

Thanks,
@swetharepakula && @nino-k
CF Routing Team

**Comment by adriancole** [comment]
Hey there. Just to make sure we are fixing what you need fixed, are you seeing variable length in the B3 headers? or is it log entries? Most libraries encode as long and just format them as fixed length. I'm sure we can hunt this down if we know what we're hunting.

**Comment by swetharepakula** [comment]
We were using the Span library to get the spans from our headers. We did notice though some of our IDs were less than 16 characters and realized leading zeros were getting trimmed. Also https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java#L459 does not create fixed length strings from the Long, which is what we think the problem is. Thanks for the quick response!

**Comment by adriancole** [comment]
thanks, swetha.

easy to fix.

**Comment by adriancole** [comment]
https://github.com/spring-cloud/spring-cloud-sleuth/pull/450 < I can add this to all the release branches as it makes sense

**Comment by marcingrzejszczak** [comment]
Please do! Thanks a lot

**Comment by adriancole** [comment]
1.0.x backport https://github.com/spring-cloud/spring-cloud-sleuth/pull/451
