### ISSUE TITLE
Support for custom HTTP codes

### ISSUE THREAD

**Issue by FlorianLautenschlager** [spring-cloud/spring-cloud-sleuth#463]
Sleuth checks if the response is successful (successful or redirection, [see](https://github.com/spring-cloud/spring-cloud-sleuth/blob/v1.1.0.RELEASE/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java#L253)). The TraceFilter uses `HttpStatus.valueOf(response.getStatus());` that throws an exception on custom HTTP codes.

The actual exception:
`java.lang.IllegalArgumentException: No matching constant for [560] at org.springframework.http.HttpStatus.valueOf(HttpStatus.java:497) at org.springframework.cloud.sleuth.instrument.web.TraceFilter.httpStatusSuccessful(TraceFilter.java:253) at org.springframework.cloud.sleuth.instrument.web.TraceFilter.doFilter(TraceFilter.java:133)`

**Comment by RobWin** [comment]
This is related to https://jira.spring.io/browse/SPR-14205

**Comment by marcingrzejszczak** [comment]
@robwin so this will work without any change in Spring 4.2.5?

**Comment by RobWin** [comment]
No, but it provides an alternative which allows custom status codes.

**Comment by RobWin** [comment]
Sry I think there is only a fix for ResponseEntity.

**Comment by marcingrzejszczak** [comment]
@FlorianLautenschlager is it also fixed in 1.1 x and 1.0.x?

**Comment by FlorianLautenschlager** [comment]
Yes it is. The latest release contains the old code, that produces the exception.
