### ISSUE TITLE
Spring Sleuth Stream properties

### ISSUE THREAD

**Issue by deepank-sharma** [spring-cloud/spring-cloud-sleuth#464]
We have three different applications each with their own set of microservices.
We just have a single instance of rabbit MQ that we can use for sleuth stream.
Is there a way I can configure three different queues and from each application point the microservices to  their respective queues and have 3 different zipkin UI read those queues to collect data separately.
Right now as soon as I start a zipkin app it binds itself to sleuth.sleuth by default.
Is there a way I can point it to a specific destination, queue, or specify a routing key.

**Comment by Koizumi85** [comment]
Hi,
I don't know about the sleuth properties directly. But RabbitMQ has the possibility to create so called "vhosts". These are independent virtual hosts inside of RabbitMQ and in each of these hosts, you can create queues with the same name. So if you create a vhost for each of your applications, then you can set this vhost in your RabbitMQ connection settings and sleuth will create a sleuth.sleuth queue in each of these vhosts,

**Comment by marcingrzejszczak** [comment]
Theoretically you can do that...

Both in the span producer side and the collector size you can provide a different destination for the `org.springframework.cloud.sleuth.stream.SleuthSource`. So in the properties you can set `spring.cloud.stream.bindings.sleuth.destination=sthelse`. That way you'll start streaming the spans into different topics. But like I said - that's theory, if it will work fine - it's another question ;)

**Comment by deepank-sharma** [comment]
This worked, thanks for that !! I totally missed the cloud stream part.
