### ISSUE TITLE
Sleuth-Zipkin-Log-Reporter

### ISSUE THREAD

**Issue by FlorianLautenschlager** [spring-cloud/spring-cloud-sleuth#466]
Currently sleuth supports sending spans to a zipkin-server using HTTP. For this solution a connection from the instrumented application to the zipkin-server is necessary. It would be great to have a solution that writes sleuth traces converted to zipkin traces in a file (using standard logger, etc.). I have some code in my sandbox that solves this. Should i raise a PR for a sleuth-zipkin-starter-log module (or any other name).

**Comment by adriancole** [comment]
sleuth actually allows you to wire a functional interface `ZipkinSpanReporter` which can do whatever you want, right?

**Comment by adriancole** [comment]
I guess the point is that you should be able to make a log-based approach without changing any of sleuth. if others express interest, it could be considered for https://github.com/openzipkin/zipkin-reporter-java or here. I think I've heard some others ask about a logging approach in general, ex https://groups.google.com/forum/#!forum/zipkin-user

**Comment by FlorianLautenschlager** [comment]
The `ZipkinSpanReporter` is part of the `spring-cloud-sleuth-zipkin` module and handles zipkin spans while the interface `SpanReporter` handles sleuth spans. Therefore as you did in spring-cloud-sleuth one has to convert the spans. Then you can do whatever you want :-)
What about to handle the sleuth-span <-> zipkin-span conversion in a spring-cloud-sleuth-zipkin-utils module and provide ready to go modules for zipkin-server (via http), zipkin-log etc.?

I agree that it should be part of the zipkin-reporter-java project.

**Comment by adriancole** [comment]
> The ZipkinSpanReporter is part of the spring-cloud-sleuth-zipkin module and handles zipkin spans while the interface SpanReporter handles sleuth spans. Therefore as you did in spring-cloud-sleuth one has to convert the spans. Then you can do whatever you want :-)
> What about to handle the sleuth-span <-> zipkin-span conversion in a spring-cloud-sleuth-zipkin-utils module and provide ready to go modules for zipkin-server (via http), zipkin-log etc.?

I might be missing something, but why do we need another module for
this? If you implement ZipkinSpanReporter then it is already in zipkin
format (so no conversion needed). zipkin.reporter.Reporter can be
adapted easily to ZipkinSpanReporter. That or we expose the ability to
put a native zipkin.reporter.Sender. In any case, I can quite see yet
why we need a new util module. can you help me understand?

**Comment by FlorianLautenschlager** [comment]
> I might be missing something, but why do we need another module for this?  If you implement ZipkinSpanReporter then it is already in zipkin format ...

For the case that i want to write span to a log, currently i have to use the sleuth-zipkin that comes with all the HTTP connection handling for zipkin-server, that i never use.
A separate utility module makes it easier to implement new zipkin related modules without having all the classes around. Just a design proposal.

**Comment by adriancole** [comment]
Hmm.. it isn't that many classes relatively speaking, plus we have to consider having many modules could be confusing. The http client is a sensible default, doesn't depend on non-JDK impl and doesn't start any lifecycle stuff when not in use.. In that way, it doesn't seem harmful or bloated enough to warrant concern on its own.

That said.. there is some copy/paste sleuth conversion between the -zipkin and the -zipkin-stream.. I think there are some other zipkin + sleuth work, too (cc @mbogoevici). If extracting this seems helpful to multiple people, I'm not fussed about it.

@marcingrzejszczak any opinions?

**Comment by dsyer** [comment]
Currently `spring-cloud-sleuth-zipkin` has a mandatory dependency on `zipkin-reporter` which I guess is the HTTP client? Maybe that could be optional and the starter could bring it in to keep backwards compatibility for people using that. Anyone who wanted a log-only approach could exclude it, or just depend on `spring-cloud-sleuth-zipkin` directly? That way we don't need a new module (which would only have a few lines of code in it).

**Comment by adriancole** [comment]
I think for this one, @FlorianLautenschlager is talking about using the sender. the optional dep is zipkin-sender-urlconnection (12KiB)

**Comment by adriancole** [comment]
>2.5KiB of that is just pom and manifest stuff, incidentally

**Comment by adriancole** [comment]
anyway also true, we could make the whole reporter thing optional by playing with autoconfig.

**Comment by adriancole** [comment]
though.. I think that if it becomes effortful to use the default http reporter, to save a few dozen kb of jars, we've stepped backwards

**Comment by FlorianLautenschlager** [comment]
I agree - its not the total size of jars that matters. I think more of usability and how to slice modules. 

Lets get back to topic (if i should provide a solution to store zipkin traces). Currently i see the following points:
 - Reporter: Zipkin log reporter belongs to zipkin-reporter-java. Handles spans and reports them to log via. json or thrift. 
 - Sleuth-Integration:
   - As configuration by overriding the ZipkinSpanReporter bean. (a point in the documentation)
   - As a new starter module. (ease of use)

I am fine with every solution. :+1:

**Comment by adriancole** [comment]
cool. when thinking about the log reporter ping @schlosna who had done this in the past in brave https://github.com/openzipkin/brave/pull/226 we wouldn't merge code w/o multiple users anyway, so good to hook up in general

**Comment by marcingrzejszczak** [comment]
@FlorianLautenschlager any luck with moving the solution forward? :)

**Comment by marcingrzejszczak** [comment]
@FlorianLautenschlager ping?

**Comment by FlorianLautenschlager** [comment]
@marcingrzejszczak Sorry - i have a lot on my plate.  No progress at all. :-( Can work on this after the 10th of march.

**Comment by marcingrzejszczak** [comment]
No problem. Let me close this for now and feel free to reopen this once you have some stuff done :)

**Comment by jonatan-ivanov** [comment]
@FlorianLautenschlager Are you still interesting in it? I have a similar issue #575 which probably can solve this as well.
