### ISSUE TITLE
Zuul is not sending logs to Zipkin 

### ISSUE THREAD

**Issue by ajayaks** [spring-cloud/spring-cloud-sleuth#470]
Hi,

I have setup like below
 Zuul --> micro service

It was working fine when i am not using sleuth with zuul. 
Micro service is able to send logs to zipkin.

micro service to zipkin is fine 

Zuul --> Zipkin is not working 

When i m adding sleuth with zipkin , its not working. Means i am not able to see the result and getting below error.
2016-12-09 17:11:34.929  WARN [gateway-service,fe145b7b89120e25,e28d9e0575f254f,true] 48086 --- 

[nio-1113-exec-9] o.s.cloud.sleuth.util.ExceptionUtils     : Tried to close span but it is not the current span: [Trace: fe145b7b89120e25, Span: fe145b7b89120e25, Parent: null, exportable:true].  You may have forgotten to close or detach [Trace: fe145b7b89120e25, Span: e28d9e0575f254f, Parent: fe145b7b89120e25, exportable:true]

I have below settings.

spring:
  zipkin:
    baseUrl: http://192.168.99.100:9411/
  sleuth:
    sampler:
      percentage: 1.0

Please suggest.

**Comment by marcingrzejszczak** [comment]
This should work out of the box. Can you post your sample somewhere? Do you have some custom filters in your code? Can you also run this with debug level of sleuth logs and check the output?

**Comment by ajayaks** [comment]
Yes, i have defined one SimplePreFilter extending  ZuulFilter and below is the very basic implementation
 @Override
	  public Object run() {
	    RequestContext ctx = RequestContext.getCurrentContext();
	    HttpServletRequest request = ctx.getRequest();

	    log.info(String.format("#####Hello recevied %s request for %s #####", request.getMethod(), request.getRequestURL().toString()));
	    log.info(String.format("#####For Zipkin::  Hello recevied %s request for %s #####", request.getMethod(), request.getRequestURL().toString()));


	    return null;
	  }

**Comment by marcingrzejszczak** [comment]
We already have a filter registered in Zuul. Can you try to play with registration order so that our filter gets executed before yours (pre) and after yours (post)

**Comment by ajayaks** [comment]
I have upload the code https://github.com/ajayaks/gateway-service.

**Comment by ajayaks** [comment]
Even on commenting custom filter i am getting the same.

2016-12-10 01:29:03.442  WARN [gateway-service,c3343e9ec85466b5,e98ddbec636826e3,true] 48890 --- [nio-1113-exec-1] o.s.cloud.sleuth.util.ExceptionUtils     : Tried to close span but it is not the current span: [Trace: c3343e9ec85466b5, Span: c3343e9ec85466b5, Parent: null, exportable:true].  You may have forgotten to close or detach [Trace: c3343e9ec85466b5, Span: e98ddbec636826e3, Parent: c3343e9ec85466b5, exportable:true]

**Comment by ajayaks** [comment]
Its working now.

Issues got fixed,  when i added added Camden.SR3 bom.

Its working with custom filters also.
Thanks for your support.

**Comment by marcingrzejszczak** [comment]
No problem :)
