### ISSUE TITLE
Feign logger - no sleuth headers attached

### ISSUE THREAD

**Issue by tzebrowski** [spring-cloud/spring-cloud-sleuth#476]
Hi,

I provided own implementation of **feign.Logger** and set log level on **feign.Logger.Level.FULL** to make all data logged.
In the method **feign.Logger.logRequest** I read **feign.Request.headers** and don't see there sleuth headers like X-B3-,... .
I know for sure that **TraceFeignClient** is executed. When turn log level on DEBUG for org.springframework.cloud.sleuth.instrument.web.client.feign I see statements like
`o.s.c.s.i.w.c.feign.TraceFeignClient : The modified request equals POST`
with missing headers included.

/Tomek

**Comment by marcingrzejszczak** [comment]
Can you post a sample please?

**Comment by marcingrzejszczak** [comment]
Ping? @tzebrowski

**Comment by tzebrowski** [comment]
Have holidays right now :),will be back at the office begging of the new year. Then will attach some sample.

**Comment by marcingrzejszczak** [comment]
Great! Waiting to solve this until then :)

**Comment by tzebrowski** [comment]
Sample code bellow 
`
   @Slf4j
    @Configuration
    static class FeignLoggerAutoConfiguration {
        
        @Bean
        Level logLevel(){
            return Level.FULL;
        }
        
        @Bean
        Logger feignLogger(){
            return new Logger(){
                @Override
                protected void log(String configKey, String format, Object... args) {
                   
                    
                }
                @Override
                protected Response logAndRebufferResponse(String configKey, Level logLevel, Response response,
                        long elapsedTime) throws IOException {
             
                    return super.logAndRebufferResponse(configKey, logLevel, response, elapsedTime);
                }
                @Override
                protected void logRequest(String configKey, Level logLevel, Request request) {
                    log.info("------  " + request);
                    super.logRequest(configKey, logLevel, request);
                }
            };
        }   
    }
`

**Comment by marcingrzejszczak** [comment]
Thanks a lot! I'll check it out ASAP

**Comment by tzebrowski** [comment]
Great,

**Comment by marcingrzejszczak** [comment]
Ok only now I think I understood what you're saying... I thought that there are no entries in the logs, cause they are...

```
@Bean Logger feignLogger() {
		return new Logger() {
			@Override
			protected void log(String configKey, String format, Object... args) {
			}

			@Override
			protected Response logAndRebufferResponse(String configKey, Level logLevel,
					Response response, long elapsedTime) throws IOException {
				return super.logAndRebufferResponse(configKey, logLevel, response,
						elapsedTime);
			}

			@Override
			protected void logRequest(String configKey, Level logLevel, Request request) {
				log.info("------ BEFORE [" + request + "]");
				super.logRequest(configKey, logLevel, request);
				log.info("------ AFTER [" + request + "]");
			}
		};
	}
```

and the result is

```
2017-01-04 16:05:10.838 DEBUG [bootstrap,788ec26b79c8ca03,222cd6968ffd18ae,true] 57684 --- [strix-no-name-1] o.s.c.s.i.w.c.feign.TraceFeignClient     : Closing Feign span [Trace: 788ec26b79c8ca03, Span: 222cd6968ffd18ae, Parent: 788ec26b79c8ca03, exportable:true]
2017-01-04 16:05:11.349  INFO [bootstrap,788ec26b79c8ca03,788ec26b79c8ca03,true] 57684 --- [strix-no-name-1] o.s.c.s.i.w.c.f.i.issue476.Application   : ------ BEFORE [GET http://localhost:12345/name HTTP/1.1]
2017-01-04 16:05:11.349  INFO [bootstrap,788ec26b79c8ca03,788ec26b79c8ca03,true] 57684 --- [strix-no-name-1] o.s.c.s.i.w.c.f.i.issue476.Application   : ------ AFTER [GET http://localhost:12345/name HTTP/1.1]
```

I must buy better glasses cause now I understand that you've accessed the `Request` variable and you're saying that you can't find any tracing headers there, correct? Now wonder... That's because we are using `TraceFeignClient` to perform a request to which we're placing all headers AFTER the custom logger was executed. So you have no chances of seeing those headers there. Does it make sense?

**Comment by tzebrowski** [comment]
> I must buy better glasses cause now I understand that you've accessed the Request variable and you're saying that you can't find any tracing headers there, correct?

_correct_

> That's because we are using TraceFeignClient to perform a request to which we're placing all headers AFTER the custom logger was executed for request and it's executed BEFORE the response logger gets executed. So you have no chances of seeing those headers there. Does it make sense? 

_that is the issue_

**Comment by marcingrzejszczak** [comment]
I mean it's not an issue. Why do you want to access those headers?

**Comment by tzebrowski** [comment]
Have business requirement,

**Comment by marcingrzejszczak** [comment]
Do you're only chance is to try to extend tracefeignclient which is package scoped but that's a hack :/

**Comment by tzebrowski** [comment]
At the beginning I have in mind  to do some hacks, but decided  to ask an author about his opinion :)
I am not sure why your are cloning the headers in the TraceFeignClient and work on the copy?

**Comment by marcingrzejszczak** [comment]
Cause the request headers are immutable :)

**Comment by tzebrowski** [comment]
:), so no chance to get those  headers in the regular way,need to do some hacks,

**Comment by marcingrzejszczak** [comment]
Yeah it seems so :/

**Comment by vhrankina** [comment]
Hi, @tzebrowski. 

I have the exact same issue: could you please share your solution?
