### ISSUE TITLE
Misspeling in metrics configuration

### ISSUE THREAD

**Issue by gavlyukovskiy** [spring-cloud/spring-cloud-sleuth#477]
`TraceMetricsAutoConfiguration` enabled by using `spring.sleuth.metrics.enabled=true`, but the `SleuthMetricProperties` annotated by `@ConfigurationProperties("spring.sleuth.metric")`.

Difference in metric/metrics is confusing, I think they should have same prefix.

And also I'd like to move all such properties under `@ConfigurationProperties` classes or put them into `additional-spring-configuration-metadata.json`.

**Comment by marcingrzejszczak** [comment]
Let's split this into 2 issues. One will be for misspelling and the other for `@ConfigurationProperties`. It would be awesome if you could file a PR for the latter :D
