### ISSUE TITLE
Add parentSpanID to app logs

### ISSUE THREAD

**Issue by mgadiya** [spring-cloud/spring-cloud-sleuth#480]
Spring Cloud sleuth adds traceID and spanID to application logs. It would be great if it also supported adding parentSpanID. So if incoming request had a `traceId` and a `spanID` as `6b55de22492307e8`, `96e487b6bfd9ca76` then app logs would write `parentSpanID` in this format:

```
2016-09-09T11:12:34.19-0700 [APP/0]      OUT 2016-09-09 18:12:34.196DEBUG [,6b55de22492307e8,d1e467b6bfd8ca04,96e487b6bfd9ca76,true] 12 --- [nio-8080-exec-7] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing GET request for [/]
```

Here the app logs preserved traceID `6b55de22492307e8`, added spring boot's own spanID `d1e467b6bfd8ca04` and also preserved the incoming spanID and wrote it as `96e487b6bfd9ca76` right after the new spanID

This allows systems who ingest these logs to form a call stack of entire trace without needing any extra information.

**Comment by TheDarkKnight47** [comment]
I am in requirement of same thing. Can anyone guide if this is possible because when I added %X{parentSpanId :-} in log pattern it is always empty. but the parentSpanId is going as part of header request.
