### ISSUE TITLE
1.1.0.RELEASE missing from maven central

### ISSUE THREAD

**Issue by darkmuse** [spring-cloud/spring-cloud-sleuth#489]
It appears that org.springframework.cloud:spring-cloud-starter-sleuth:jar:1.1.0.RELEASE is missing from the main maven repos. 

The zipkin starter, and sleuth-core are all there at that version but my IDE cannot pull the starter!

**Comment by marcingrzejszczak** [comment]
No it's not - http://search.maven.org/#artifactdetails%7Corg.springframework.cloud%7Cspring-cloud-starter-sleuth%7C1.1.0.RELEASE%7Cjar and http://repo2.maven.org/maven2/org/springframework/cloud/spring-cloud-starter-sleuth/1.1.0.RELEASE/
