### ISSUE TITLE
TraceWebClientAutoConfiguration is dependent on a web application context

### ISSUE THREAD

**Issue by FrontierPsychiatrist** [spring-cloud/spring-cloud-sleuth#494]
I have a microservice that only acts as a web client (with a `RestTemplate`) that should create a trace id that is sent via HTTP header. This worked by having my `RestTemplate` as a bean and relying on the `TraceWebClientAutoConfiguration` that will create a `TraceRestTemplateInterceptor`.

Since commit 7a042af1777531b052649d9aae8f6a26e4a009f9 the `TraceWebClientAutoConfiguration` is dependent on the bean `HttpTraceKeysInjector` which is created in `TraceWebAutoConfiguration` which then has `@ConditionalOnWebApplication`. Since I don't have a web application I cannot rely on the client autoconfiguration anymore.

I think the client autoconfiguration should not depend on a web context (even transitive like now).

Workaround: Copy the bean method for the `HttpTraceKeysInjector` to my `@Configuration` and it works fine.

**Comment by marcingrzejszczak** [comment]
Have you checked the latest snapshots? I think it got fixed somewhere on the way

**Comment by FrontierPsychiatrist** [comment]
Ah, thanks! Yes, it seems the `HttpTraceKeysInjector` is now created in `TraceHttpAutoConfiguration` which is not dependent on a web context, so this is already resolved. Thanks!
