### ISSUE TITLE
TraceFilter's order should be configurable

### ISSUE THREAD

**Issue by seeksong** [spring-cloud/spring-cloud-sleuth#50]
In my app, I want to put TraceFilter before SecurityFilter. Currently the order for TraceFilter is hardcoded, I think it's better to provide a system property (and a default value) so that the order can be configured.

**Comment by qerub** [comment]
I think one workaround is to declare a custom `FilterRegistrationBean` for `TraceFilter` á la `TraceWebAutoConfiguration` that sets the required precedence using `setOrder`.

**Comment by qerub** [comment]
I was a bit surprised to find that `TraceFilter` has `@Order(Ordered.HIGHEST_PRECEDENCE + 5)` but is then shoved into a `FilterRegistrationBean` with default precedence. Is there any point to that annotation? (I'm not a Spring expert.)
