### ISSUE TITLE
TraceFeignClient doesn't support custom SSL certificate

### ISSUE THREAD

**Issue by jmirc** [spring-cloud/spring-cloud-sleuth#502]
Hi, 

We are using internal generated SSL certificate and I would like to know what is the best way to configure a `Feign.Client` with a specific `sslContextFactory` and `hostnameVerifier` objects.
Actually, because the TraceFeignClient is protected, I can't use the `TraceFeignClient(BeanFactory beanFactory, Client delegate)` constructor. To avoid this problem, I could add a custom Configuration class in the `org.springframework.cloud.sleuth.instrument.web.client.feign` package in my project but I don't like this approach.

Thanks for your thoughts.

**Comment by spencergibb** [comment]
Shouldn't the delegate be the one configured, since that is the one actually making calls?

**Comment by marcingrzejszczak** [comment]
I'm already working on that. It seems that I'm completely ignoring a delegate. That's the problem in this issue :/
