### ISSUE TITLE
Sleuth should log 'decoded-ansi' output to file appenders

### ISSUE THREAD

**Issue by mpalourdio** [spring-cloud/spring-cloud-sleuth#510]
Hello,

In my spring boot application, when using sleuth with the below `logback-spring.xml`, sleuth logs 'ansi-encoded' data to my log files.

```
2017-02-06 21:40:09.782 [32m INFO[0;39m [33m[myappname,,,][0;39m 7551 --- [Thread-7] com.netflix.discovery.DiscoveryClient    : Shutting down DiscoveryClient ...
```

Is there a way to have the logs sent to files 'ansi-decoded'. Am I missing something ? (I want to keep my console logs colored of course).

Thanks by advance.

Here is my logback.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/defaults.xml" />
    <include resource="org/springframework/boot/logging/logback/console-appender.xml" />

    <appender name="LOGFILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>logs/app.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>logs/app-%d{yyyy-MM-dd}.log</fileNamePattern>
        </rollingPolicy>
        <encoder>
            <pattern>${FILE_LOG_PATTERN}</pattern>
        </encoder>
    </appender>

    <root level="INFO">
        <appender-ref ref="CONSOLE" />
        <appender-ref ref="LOGFILE" />
    </root>

</configuration>
```

**Comment by gavlyukovskiy** [comment]
Seems like it is not allowed to have %clr inside log level, spring-boot uses it for both `logging.pattern.console` and `logging.pattern.file`, with %clr for console and without for file.

All you can do it is force set `logging.pattern.level` to `%5p [${spring.application.name:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]`, but in console it will have color equal to the severity level (yellow for warnings, red for errors).
Maybe it is not such a bad option to have it by default.

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-sleuth/commit/ce226ba334d07f16c7b03831e4e310dbcedfebcf

**Comment by mpalourdio** [comment]
Hello,

thanks @gavlyukovskiy for the suggestion. But I've just tried @marcingrzejszczak  fix, and it definitly fixes my issue !

Thanks a a lot to you both.
