### ISSUE TITLE
Sleuth and aspects erases type of config properties

### ISSUE THREAD

**Issue by kimsaabyepedersen** [spring-cloud/spring-cloud-sleuth#514]
Hi, 

From an application where I want to use Sleuth instead of a homegrown solution I have found this bug (or at least I believe it is a bug).

The essence of the story is:
If I have an aspect and put sleuth on the classpath my properties are being read as String instead of Integer and I get a:
_java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer_ 

I have this "production" code:
```java
package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MyApp {

    public static void main(String[] args) {
        SpringApplication.run(MyApp.class, args);
    }
}
```

```java
package com.example;

import org.aspectj.lang.JoinPoint;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Before;
import org.springframework.stereotype.Component;


@Component
@Aspect
class MyAspect {

    @Before("execution(public * *(..)) && within(com.example..*))")
    public void doSomethingHere(JoinPoint joinPoint) {
    }

}
```

```java
package com.example;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

import java.util.HashMap;
import java.util.Map;

@Component
@ConfigurationProperties(prefix = "my.props")
class MyProperties {

    private final Map<String, Integer> expiry = new HashMap<>();

    public Map<String, Integer> getExpiry() {
        return expiry;
    }

}
```

This application.properties:
```
my.props.expiry[a]=168
my.props.expiry[b]=48
```

This test:
```java
package com.example;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
public class MyAppTests {

	@Autowired
	private MyProperties myProperties;
	
	@Test
	public void contextLoads() {
                /* Without sleuth on the classpath this will print:
                 * class java.lang.Integer
                 * with sleuth this throws an exception
                 */
		System.out.println(myProperties.getExpiry().get("a").getClass());
	}

}
```

And finally this pom.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>demo</name>
    <description>Demo project for Spring Boot</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.1.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>

<!-- to get exception include this (and comment out the aop starter) -->

        <!--dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency-->
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Camden.SR5</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>1.4.1</version>
                <executions>
                    <execution>
                        <id>enforce</id>
                        <configuration>
                            <rules>
                                <dependencyConvergence/>
                            </rules>
                        </configuration>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>


```

**Comment by marcingrzejszczak** [comment]
Hi @kimsaabyepedersen . Thanks a lot for filing the issue.

Could you please post it as a sample on Github in exactly the way you're setting it up? It will be much easier to check what's wrong.

**Comment by kimsaabyepedersen** [comment]
Hi @marcingrzejszczak 

Sure, check this https://github.com/kimsaabyepedersen/slueth-bug. 

Run mvn clean install and it will fail (it has sleuth on the path). 

Then open the pom.xml and comment out sleuth. Run again and then it prints out as expected that the class is Integer.

**Comment by marcingrzejszczak** [comment]
@kimsaabyepedersen I've confirmed that it's not `sleuth` related but more `commons`related issue but let's keep it here for now until I find a real reason for this. You can change `sleuth` to `feign` and you'll get the same thing.

**Comment by kimsaabyepedersen** [comment]
Thanks @marcingrzejszczak. This is kind of a blocker if you use Spring AOP and want to use sleuth (or other cloud projects as you have found out). Let me know I if can help.

**Comment by marcingrzejszczak** [comment]
I've already managed to find the a place where it's happening. Now I'll try to understand why and how to fix it...

**Comment by marcingrzejszczak** [comment]
Moved to https://github.com/spring-cloud/spring-cloud-commons/issues/175

**Comment by marcingrzejszczak** [comment]
BTW @kimsaabyepedersen until we fix this I'd suggest not to create proxies over the configuration properties. Actually, why are you even doing that?

**Comment by kimsaabyepedersen** [comment]
Well @marcingrzejszczak I am not doing that in the real application I have extracted the code from. The code in the aspect looks more like this (at least the joinpoint :) ):
```java
@Before("execution(public * *(..)) && within(com.example..*) && @target(org.springframework.web.bind.annotation.RestController))")
```


https://github.com/kimsaabyepedersen/slueth-bug/blob/with-controller/src/main/java/com/example/MyAspect.java

So I an not proxying the configuration properties, and still it fails.

**Comment by marcingrzejszczak** [comment]
Yeah that's extremely interesting cause still the configuration property is a proxy!

**Comment by kimsaabyepedersen** [comment]
Yeah - I believe many use aspects like demoed to intercept calls and do cross cutting things like logging etc. Yes, the behavior is strange. Let me know if you need my help testing anything.

**Comment by marcingrzejszczak** [comment]
Actually when I changed the aspect a little bit to point to a precise class (`MyApp`) then it worked fine. For some reason IMO the aspect "catches" the `MyProperties` and makes it a proxy.

**Comment by marcingrzejszczak** [comment]
BTW if you change `@target` to `@annotation` it's working fine (which doesn't mean that the problem is gone...)

**Comment by kimsaabyepedersen** [comment]
Yeah but then the aspect does not work, which is in line with the documentation from here: https://docs.spring.io/spring/docs/current/spring-framework-reference/html/aop.html  - so that is not really a solution:

@target - limits matching to join points (the execution of methods when using Spring AOP) where the class of the executing object has an annotation of the given type

@annotation - limits matching to join points where the subject of the join point (method being executed in Spring AOP) has the given annotation

**Comment by marcingrzejszczak** [comment]
ah you're right... ok so I don't have a good workaround for now :(
