### ISSUE TITLE
When using MOCK web env and Zipkin starter exception is thrown

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#518]
It seems that in `WebEnvironment.MOCK` `server.port` property of an application is changed to -1 in spring test. It causes the following exception in zipkin: `java.lang.IllegalArgumentException: invalid port -1`

If zipkin is disabled in test class by using annotation: `@TestPropertySource(properties = { "spring.zipkin.enabled: false" })` everything goes fine.

project to replicate the issue https://github.com/vanarchi/SleuthZipkinPortProblem

**Comment by elgohr** [comment]
When will this be available?

**Comment by marcingrzejszczak** [comment]
This week hopefully. Next week at latest I think
