### ISSUE TITLE
Compatibility with logback-spring.xml

### ISSUE THREAD

**Issue by nickcodefresh** [spring-cloud/spring-cloud-sleuth#52]
With the latest version of Spring Boot you can use a logback-spring.xml file instead of added logging configuration in application.yml. I can't get get the trace or span IDs in to the logs though using the standard pattern elements:

```
	<appender name="console" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<pattern>%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] [%c] \(%t\) %msg%n
			</pattern>
			<charset>utf8</charset>
		</encoder>
	</appender>
```

Am I doing something wrong, or does Sleuth not support the logback-spring.xml file?

**Comment by dsyer** [comment]
Sleuth is independent of the logging system in Spring Boot so I don't see why that wouldn't work. Did you not see the `[trace=...]` part of your log format at all?

**Comment by vapp-project** [comment]
Try this, this will work.

<property name="CONSOLE_LOG_PATTERN"
              value="%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS}){faint} %clr(%level) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"/>

    <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>${CONSOLE_LOG_PATTERN}</pattern>
            <charset>utf8</charset>
        </encoder>
    </appender>
