### ISSUE TITLE
TraceChannelInterceptor makes Message NonSerializable

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-sleuth#520]
The code:
```
MessageHeaderAccessor headers = MessageHeaderAccessor.getMutableAccessor(message);
headers.copyHeaders(messageBuilder.build().getHeaders());
return new GenericMessage<Object>(message.getPayload(), headers.getMessageHeaders());
```
returns the `GenericMessage` with the `MutableMessageHeaders` which has a reference to the outer `MessageHeaderAccessor` instance which isn't `Serializable`.

Would be better to use `MessageHeaderAccessor.toMessageHeaders()`. At least for now.
Although it clashes with the fix for #276...

For more info: https://jira.spring.io/browse/SPR-15262

**Comment by artembilan** [comment]
Quoting @dsyer in the : https://jira.spring.io/browse/SPR-14791
> We found a workaround in Spring Sleuth https://github.com/spring-cloud/spring-cloud-sleuth/issues/276. I guess we can still consider this a valid improvement.

Since all those concerns have been addressed in SF since there, I think it would be better to retreat that workaround and come to the `MessageHeaderAccessor.toMessageHeaders()` therefore.

**Comment by marcingrzejszczak** [comment]
Dupcliated via #523
