### ISSUE TITLE
Investigate the memory usage of Sleuth applications

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#522]
It would be good to know how much more memory is used by Sleuth applications in comparison to normal boot apps.

**Comment by marcingrzejszczak** [comment]
Some work is done over here - https://github.com/marcingrzejszczak/sleuth-memory-benchmarks

**Comment by marcingrzejszczak** [comment]
## Introduction 

The tests from this repo https://github.com/marcingrzejszczak/sleuth-memory-benchmarks are doing the following

- start app without Sleuth
- curl requests to the app
- measure memory usage
- start app with Sleuth
- curl requests to the app
- measure memory usage

## Test results

### WITHOUT actuator

These are the results for application WITHOUT the actuator dependency:

```
For [100] requests...
99th percentile of memory usage for a non sleuth app is [21203.5]
99th percentile of memory usage for a sleuth app is [36477.7]
The Sleuth app is using [15274.2] more memory which means a increase by [72.00%]
GC time for non sleuth app [6.782]
GC time for sleuth app [7.966]
The Sleuth app needs [1.184] more time (in seconds) which means an increase by [17.400%]
```

```
For [500] requests...
99th percentile of memory usage for a non sleuth app is [21980.5]
99th percentile of memory usage for a sleuth app is [39391.1]
The Sleuth app is using [17410.6] more memory which means a increase by [79.00%]
GC time for non sleuth app [34.114]
GC time for sleuth app [40.840]
The Sleuth app needs [6.726] more time (in seconds) which means an increase by [19.700%]
```

```
For [2000] requests...
99th percentile of memory usage for a non sleuth app is [22013.0]
99th percentile of memory usage for a sleuth app is [39042.9]
The Sleuth app is using [17029.9] more memory which means a increase by [77.00%]
GC time for non sleuth app [147.288]
GC time for sleuth app [173.700]
The Sleuth app needs [26.412] more time (in seconds) which means an increase by [17.900%]
```

### WITH actuator

These are the results for application WITH the actuator dependency:

```
For [100] requests...
99th percentile of memory usage for a non sleuth app is [20869.7]
99th percentile of memory usage for a sleuth app is [46126.6]
The Sleuth app is using [25256.9] more memory which means a increase by [121.00%]
GC time for non sleuth app [6.874]
GC time for sleuth app [10.188]
The Sleuth app needs [3.314] more time (in seconds) which means an increase by [48.200%]
```

```
For [500] requests...
99th percentile of memory usage for a non sleuth app is [21935.7]
99th percentile of memory usage for a sleuth app is [51122.7]
The Sleuth app is using [29187.0] more memory which means a increase by [133.00%]
GC time for non sleuth app [34.286]
GC time for sleuth app [49.814]
The Sleuth app needs [15.528] more time (in seconds) which means an increase by [45.200%]
```

```
For [2000] requests...
99th percentile of memory usage for a non sleuth app is [21680.7]
99th percentile of memory usage for a sleuth app is [63588.3]
The Sleuth app is using [41907.6] more memory which means a increase by [193.00%]
GC time for non sleuth app [115.881]
GC time for sleuth app [201.294]
The Sleuth app needs [85.413] more time (in seconds) which means an increase by [73.700%]
```

## Conclusions 

### Cache for proxied objects

We can see that the without the actuator endpoint the increase in used memory is around 17-20 mbs. The GC time is stable with the increased number of requests. Why the increase in memory usage? That's because we're using quite a few aspects and a cache is used to cache the proxied object. So this growth is expected. In terms of `%` in a small application that has one endpoint and does nothing it can look drastic. But in a bigger application with more objects those 17-20 mbs are not sth that would look out of the ordinary.

### Trace actuator endpoint

With the actuator in place we can see a bigger memory usage. That's because we have the standard 17-20 mbs of cached proxied objects and there's an issue with TraceWebFilter https://github.com/spring-projects/spring-boot/issues/8322 that is responsible for a lot of memory growth.

```
20.5% - 35,904 bytes - 1,122 alloc. org.springframework.boot.actuate.trace.WebRequestTraceFilter.getRequestHeaders
8.2% - 14,400 bytes - 361 alloc. org.springframework.boot.actuate.trace.WebRequestTraceFilter.getResponseHeaders
```

Big kudos to @jkubrynski for his help on solving this mys(t)ery.

**Comment by wilkinsona** [comment]
Am I reading the numbers above correctly? `getRequestHeaders()` is responsible for 35.9KB of memory growth and `getResponseHeaders()` is responsible for 14.4KB? That seems negligible, particularly in the context of an extra 15-20MB of memory due to caching a proxied objects.

**Comment by jkubrynski** [comment]
@wilkinsona It means that actuator brings almost the same GC overhead than whole request/response processing. Due to operations on `Map` in the `TraceWebFilter` it allocates many objects.
