### ISSUE TITLE
make spring-cloud-sleuth-zipkin-stream a module

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#525]
In zipkin, we sometimes get support issues where people are creating custom zipkin servers as step 1. Just like monitoring users don't start by making a custom Prometheus server, we should find a way to stop encouraging this here. The end goal is to simplify the first tracing experience of sleuth users and lessen the support burden on OpenZipkin.

In short, custom builds are neither the fastest past to learning how to do tracing, nor a good way to leverage the OpenZipkin community. The fact that Zipkin is built with Spring Boot is only a convenience for server developers and extenders. It has never been a day 1 story.

### Why are people creating custom zipkin servers?

Zipkin server developers themselves and a handful of advanced users will need custom servers. Beginners do not need a custom server, but they are much more often the ones asking for help making one. Most of this comes from historical @joshlong videos, which start zipkin by making a custom one with start.spring.io. I spoke with josh about this, and hopefully new videos will stop suggesting that. The only other source of custom builds from beginners comes from spring-cloud-sleuth-zipkin-stream. Once we remove this here we stopped promoting custom builds as step 1 in spring videos, and stopped requiring custom builds here, we'd really have no problem anymore.

### But.. I like start.spring.io!

start.spring.io is good for sleuth, ex how do you get spring tracing in your app. On the other hand, it would be surprising to think beginners should need a custom Zipkin server. This has had numerous support impact including people asking for 1-1 sessions on how auto-configuration works, not getting their classpath or eclipse to work, etc. Our non-java developers know how to help with the supported means to configure zipkin, albeit from [a jar](https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md) or a [docker pov](https://github.com/openzipkin/docker-zipkin). Many people can help with commodity support. However, Spring Boot support is neither necessary, nor commodity in our channel. In many cases, this leads to people personally chatting with me only to later find out they had little idea what tracing even is, and were only making a custom server because of a video or more rarely the stream server. This ends up low value activity, which adds cognitive debt to the beginner as starves the OpenZipkin project of my time. Personal time aside, most people in the Zipkin channel are not java users. Pasting classpath dumps or eclipse problems is distracting there, especially when a custom server isn't needed.

### Ok.. I get helping zipkin would be nice, but what's in it for Sleuth?

Between the time we started in sleuth and now, a lot of progress has been made with collectors. By revisiting spring-cloud-sleuth-zipkin-stream, not only can Zipkin have less support burden, but also sleuth I think, too. For example, users who ask for things like Elasticsearch support wouldn't need special instructions. People wouldn't need to read or write blogs in order to get things to work. They wouldn't end up on Zipkin channel with few people able to help them with Eclipse. The first time experience with tracing will be easier and less confusing as the steps to get started would no longer include understanding how to build a custom telemetry server.

### Hmm.. ok, but what's next?

I'd like to use this issue to help track migrating scs-zipkin-stream to a "normal" 3rd party collector, such as we have with [zipkin-aws](https://github.com/openzipkin/zipkin-aws/tree/master/autoconfigure/collector-sqs) or [zipkin-azure](https://github.com/openzipkin/zipkin-azure#server-integration) (possibly stackdriver-zipkin will also use this process in the future).

This would result in scs-zipkin-stream being a "normal" collector, even if we still make an exec jar here for convenience.

**Comment by adriancole** [comment]
Here are some counter-points and alternatives to rebasing as a zipkin collector

## Is scs-zipkin-stream primarily covering for a lack of RabbitMQ support upstream?
At least in almost 4 years of issues and mailing lists, Zipkin has never had a request for RabbitMQ support. However, rabbit is often used in Josh's demos and maybe some Zipkin sites. I have seen [one other project](https://github.com/clearctvm/zipkin.net) use RabbitMQ. If there's an invisible need for RabbitMQ, we could bubble that up.

## scs-zipkin-stream features are tied to spring cloud releases (and implicitly spring boot)
Currently, scs-zipkin-stream looks and acts like a zipkin collector. However, it uses the sleuth model. While this model is relatively stable, it is tied to classes and change requests tied to spring cloud releases and those are also tied to specific spring boot releases. While the sleuth model is used, it could cause more complication to primarily tie to zipkin's spring boot, which isn't coordinated with spring cloud releases.

## scs-zipkin-stream is more about spring cloud stream and sleuth than zipkin.
While there is functional overlap with zipkin collector, understanding spring cloud stream is the primary thing to "get" with this vs a usual zipkin collector. For example, this bleeds into how messages are or aren't enveloped over transport etc, and what features are compatible with others. Keeping this primarily pinned to other spring cloud projects (vs an external one like zipkin), could help ensure that from a feature POV, things stay aligned across spring cloud stream and sleuth.

Final notes..

There are ways to reduce support burden and increase data store support besides re-using zipkin-aws or similar integration. For example, eventually new spring videos may stop suggesting start.spring.io for starting zipkin server (even better if zipkin server was removed). This would get most of the low-value troubleshooting out of the way. Also, we could do some things here to formalize or test more common back-ends, like Elasticsearch, so that users don't need blogs or 1-1 support to figure out how to do this. In other words, an alternate route could be of high value, and not require a major change.

**Comment by dsyer** [comment]
> Is scs-zipkin-stream primarily covering for a lack of RabbitMQ support upstream?

No. It is primarily to allow apps to quickly pivot away from any particular middleware (e.g. start with Rabbit and move to Kafka with just a change of classpath). This is a feature of Spring Cloud Stream, not really of Sleuth per se.

Note that Cloud Foundry does not have a native Kafka service, but it does have Rabbit. So that explains why we want Rabbit, but also would like to make it as transparent, and replaceable as possible.

I don't think users care what the format of the data is on the wire, so moving to a native Zipkin format would make perfect sense, as long as we retain interop with older clients (IIRC this wasn't possible when we started sleuth because Zipkin was still tied to Thrift). Equally, moving the whole thing to openzipkin wouldn't matter, as long as it can synchronize releases to support major Spring Cloud/Boot updates.

**Comment by adriancole** [comment]
Thanks for the insight, Dave. I'll chat with Marcin about this since seeing
him tomorrow as well.

Cheers!

**Comment by marcingrzejszczak** [comment]
The problem was fixed by keeping the module in Sleuth but we've removed the creation of Zipkin Http from initilizr so as not to make people confused.
