### ISSUE TITLE
current span is null

### ISSUE THREAD

**Issue by ddebaill** [spring-cloud/spring-cloud-sleuth#528]
Hi

Just created a fresh spring application from scratch. Only one dependency: spring-cloud-starter-sleuth, Dalston.BUILD-SNAPSHOT version.
According to the documentation, I guess I should get some trace and span id within my logs without any specific configuration.
Here's the code (pretty simple, uh)

```
@SpringBootApplication
public class TobedeletedApplication implements CommandLineRunner {

	private static final org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(TobedeletedApplication.class);

	@Autowired
	Tracer tracer;
	
	public static void main(String[] args) {
		SpringApplication.run(TobedeletedApplication.class, args);
	}

	@Override
	public void run(String... arg0) throws Exception {
		logger.info("dom was here "+tracer.getCurrentSpan());
		
	}
}
```

And here's the trace I get:
```
2017-02-23 09:38:54.949  INFO [tobedeleted,,,] 32424 --- [           main] f.i.r.common.TobedeletedApplication      : dom was here null
```

If I create a span myself, it works, but I expected a totally transparent behavior.

What did I miss ?

Thanks

**Comment by marcingrzejszczak** [comment]
I think you have completely misunderstood the idea behind tracing and tracing libraries. The idea is not to always create a span. 

In case of Sleuth a span is created when a request or a message comes in. Also when a `@Scheduled` method is called. These are the automatic scenarios in which we will start a span. In all other cases the span needs to be created by you. How should we know when you want a span or not? 

Please check out this sample https://github.com/openzipkin/sleuth-webmvc-example it shows in a very simple case how to applications talk to each other and that spans are created upon receival of a request.

**Comment by ddebaill** [comment]
OK thanks. 
I accept to be treated as a dumb but documentation should be clear about this; when I read "**Spring Cloud Sleuth instruments all your Spring application automatically, so you shouldn’t have to do anything to activate it.** " I understand that Spring Cloud Sleuth instruments all my Spring application automatically, so I shouldn’t have to do anything to activate it.  ;).

Would you plz provide a list of 'automatic scenarios in which you start a span'  ?

**Comment by marcingrzejszczak** [comment]
Just read the integrations part of the docs - http://cloud.spring.io/spring-cloud-sleuth/1.1.x/#_integrations .

It's activated OOB. You don't have to do anything. If your application receives a request / message it will automatically propagate it. If you send a request / message the span will be propagated. Why do you need a span when you start your application?

**Comment by ddebaill** [comment]
The sample was just a very simplified case in order to understand how Sleuth worked. 

The real problem I encountered was that I noticed a span was created in a @Schedule annotated method (now I understand why) but not, eg., for a @InboundChannelAdapter annotated one. Furthermore, I actually also used Sleuth stream and Trace and span id where indeed propagated to my kafka topic. So I could propagate the tracing context (great) but wasn't able to log it within my @InboundChannelAdapter annotated method. That was confusing.

**Comment by marcingrzejszczak** [comment]
That might be a bug actually (maybe we do sth too late or sth). We have our own `TraceChannelInterceptor` so maybe it's executed too late (or you do sth too early). Try creating a sample and file a new issue so that we can play around with this.

**Comment by ddebaill** [comment]
OK, thanks.

**Comment by ddebaill** [comment]
One checked, the bug applies to the Camden.SR5 version but the Dalston.BUILD-SNAPSHOT seems OK. _FYI, Had to upgrade kafka version from 0.10.0.1 to 0.10.1.1 to make Dalston.BUILD-SNAPSHOT version working._

**Comment by marcingrzejszczak** [comment]
Interesting... maybe it's fixed internally in Stream / Integration or sth. Glad that it's working! Ah yeah that is related to Stream being bumped. So the answer to all of this is to always use the latest versions possible :D

**Comment by ddebaill** [comment]
Arghhh, I claimed victory too quickly: with the very same code
- Camden.SR5: logging KO, propagation (stream mode w/kafka) OK
- Dalston.BUILD-SNAPSHOT,  logging KO, propagation (stream mode w/kafka) KO.  :(

I open a new issue and attach my sample.

Thx
