### ISSUE TITLE
No trace/span logging and stream propagation issues within @InboundChannelAdapter (spring-boot 1.5.1)

### ISSUE THREAD

**Issue by ddebaill** [spring-cloud/spring-cloud-sleuth#529]
Hi

See $Subject and attached projet. I added a `@Schedule` method in order to clearly show the difference:

```
2017-02-23 15:48:20 [task-scheduler-3] INFO  [tobedeleted] [trace=7fa37ee2c9eddae8] fr.ina.research.common.EventSource - @Scheduled: dom was here => trace logged
2017-02-23 15:48:29 [task-scheduler-5] INFO  [tobedeleted] [trace=] fr.ina.research.common.EventSource - @InboundChannelAdapter: dom was here => no trace logged but trace transmitted to kafka _(Camden only)_
2017-02-23 15:48:30 [task-scheduler-1] INFO  [tobedeleted] [trace=e5c0525d86eeafbf] fr.ina.research.common.EventSource - @Scheduled: dom was here => trace logged
2017-02-23 15:48:39 [task-scheduler-1] INFO  [tobedeleted] [trace=] fr.ina.research.common.EventSource - @InboundChannelAdapter: dom was here => no trace logged but trace transmitted to kafka
```

If I switch back to Camden.SR5, propagation works again but logging still doesn't.
Here's the kafka consumer trace:

```
?
 contentType"application/json"
                              X-B3-SpanId"0853d91951ef3dee"
                                                           X-B3-TraceId"0853d91951ef3dee"
                                                                                         X-B3-Sampled"0"{ 'someStuff' : 'someStuffIndeed'}
?
 contentType"application/json"
                              X-B3-SpanId"7fb1186d2897cb2f"
                                                           X-B3-TraceId"7fb1186d2897cb2f"
                                                                                         X-B3-Sampled"0"{ 'someStuff' : 'someStuffIndeed'}
?
 contentType"application/json"{ 'someStuff' : 'someStuffIndeed'}
?
 contentType"application/json"{ 'someStuff' : 'someStuffIndeed'}
```

The two first lines correspond to Camden.SR5, the latter to Dalston.BUILD-SNAPSHOT. Just updated the maven dependancies and relaunch.

Thx

[tobedeleted.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/796805/tobedeleted.zip)

**Comment by marcingrzejszczak** [comment]
BTW @ddebaill which Kafka should I start?

**Comment by marcingrzejszczak** [comment]
And please do not share this as a zip - please create a Github project

**Comment by ddebaill** [comment]
kafka 0.10.1.1 is OK, didn't try latter version.
OK, I create a Github project if it's easier for you.

**Comment by marcingrzejszczak** [comment]
One more thing can you update the description of this issue so that it's properly formatted? 

> The two first lines correspond to Camden.SR5, the latter to Dalston.BUILD-SNAPSHOT. Just updated the maven dependancies and relaunch.

What are those `?` in the description snippet?

**Comment by ddebaill** [comment]
first, the Github project, tell me if it's fine plz.
The ? are just outputs from a standard kafka consumer, you can ignore them; the important part here is that depending on the release (Camden.SR5 or Dalston.BUILD-SNAPSHOT), behavior changes.

**Comment by ddebaill** [comment]
github: ddebaill/Sleuth

**Comment by marcingrzejszczak** [comment]
You're missing 

`spring.sleuth.sampler.percentage=1.0` 

that's why you can't see any spans being sent to Kafka. When you change it you get for example

```
"text/plain"originalContentType "application/json;charset=UTF-8"{"host":{"serviceName":"tobedeleted","address":"192.168.1.40","port":8080},"spans":[{"begin":1487941048077,"end":1487941048416,"name":"test-trace-with-scheduled","traceId":-2343203870958027893,"spanId":-2343203870958027893,"exportable":true,"tags":{"method":"testTraceWithScheduled","class":"EventSource$$EnhancerBySpringCGLIB$$72e29903","lc":"scheduled"},"logs":[],"durationMicros":339439},{"begin":1487941048681,"end":1487941048700,"name":"message:output","traceId":3575887295491729388,"spanId":3575887295491729388,"exportable":true,"tags":{"spring.instance_id":"192.168.1.40:tobedeleted"},"logs":[{"timestamp":1487941048681,"event":"cs"},{"timestamp":1487941048700,"event":"cr"}],"durationMicros":19460}]}
```

**Comment by marcingrzejszczak** [comment]
As for the non logging thing I know a workaround... 

Provide your own custom task executor

```
@Bean TaskExecutor myTaskExecutor() {
...
	}
```

and reference it in the adapter.

```
@InboundChannelAdapter(value = Source.OUTPUT,
			poller = @Poller(fixedDelay = "10000", taskExecutor = "myTaskExecutor"))
	public String testTraceWithInboundChannelAdapter() throws IOException {
		logger.info("@InboundChannelAdapter: dom was here => no trace logged but trace transmitted to kafka"); 
		String jsonString = "{ 'someStuff' : 'someStuffIndeed'}";
		return jsonString;
	}
```

As far as I see the default executor (if one isn't provided) is not registered as a bean. That's why the logging is not present for Dalston.

But that means that sth has changed between Camden.SR5. I'll ping the one and only @garyrussell who knows everything about SI. @garyrussell for Dalston we use `spring integration 4.3.7` and if we don't provide a `taskExecutor` for `poller` then a non-bean is provided. That's why Sleuth's aspects don't work. Any idea other than explicitly providing a `taskExecutor` comes to your mind? Or are we doing sth wrong?

**Comment by ddebaill** [comment]
Hi 

Thank you for your quick answer. Will try the @TaskExecutor approach.

Regarding Stream propagation, I didn't mean sampler (sleuthtopic) but kafka headers within the business stream (trace propagation between microservices within mytopic). I guess I don't need to set `spring.sleuth.sampler.percentage` to activate it, right ? Furthermore, it works like a charm w/Camden.SR5 release.

**Comment by marcingrzejszczak** [comment]
As for the task executor - I didn't manage to make things work with Camden. It's always been like this so you need to use the TaskExecutor approach.

As for Stream propagation I think the case might be related to passing the headers. Spring Cloud Stream Kafka works like this that you have to pass the list of properties. I have no idea why it worked fine for Camden though. Check how we're doing things in Brewery - https://github.com/spring-cloud-samples/brewery/blob/master/brewing/src/main/resources/application-kafka.yaml#L16-L22 . Could you please apply those headers and see if things are working fine? If they do then I'll have to patch the docs. 

Pinging @mbogoevici @sobychacko on the Camden vs Dalston with Stream Kafka

**Comment by ddebaill** [comment]
Yep, I've seem some exchanges related to sleuth related kafka headers already. If this work, that's fine for me.
Will give a feedback once I find some time to test ;).

Thank you for your help.

**Comment by ddebaill** [comment]
Hi Marcin

Tried the header trick, it works, great. I guess I understood the difference between the two releases: Camden used ` X-B3-*` ids and Dalston uses `span*` ids; somewhere the X-B3-* headers are certainly hardcoded hence the behavior I noticed.

**Comment by marcingrzejszczak** [comment]
Camden uses both approaches. Dalston uses only the latter. But anyways I'll put it in the docs that with Kafka you have to add this info. Thanks for testing it out!

**Comment by ddebaill** [comment]
Yep, if I switch back to Camden, now I see both categories of headers (X-B3 AND span). So there's really a hard coded X-B3 header declaration somewhere in both release. Maybe if you just update this part you don't have to update the doc 😄 .

**Comment by ddebaill** [comment]
Somewhere here ?
```
public class Span implements SpanContext {

	public static final String SAMPLED_NAME = "X-B3-Sampled";
	public static final String PROCESS_ID_NAME = "X-Process-Id";
	public static final String PARENT_ID_NAME = "X-B3-ParentSpanId";
	public static final String TRACE_ID_NAME = "X-B3-TraceId";
	public static final String SPAN_NAME_NAME = "X-Span-Name";
	public static final String SPAN_ID_NAME = "X-B3-SpanId";
	public static final String SPAN_EXPORT_NAME = "X-Span-Export";
	public static final String SPAN_FLAGS = "X-B3-Flags";
	public static final String SPAN_BAGGAGE_HEADER_PREFIX = "baggage";
```

**Comment by marcingrzejszczak** [comment]
I think I got it. It's this thing https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-stream/src/main/java/org/springframework/cloud/sleuth/stream/StreamEnvironmentPostProcessor.java#L49 . I'll have to finish another thing in Sleuth and I'll fix this one. @ddebaill interested in testing that afterwards? :D

**Comment by ddebaill** [comment]
yep, the firstname is dominique (aka dom)

**Comment by ddebaill** [comment]
Regarding the taskExecutor, the workaround works.
Just added:
```
@Bean 
	TaskExecutor myTaskExecutor() {
		TaskExecutor taskExecutor= new ThreadPoolTaskExecutor();
		return taskExecutor;
	}
```
and updated the poller definition and now I get the traces within my @InboundChannelAdapter annotated method:
`2017-02-24 17:18:47 [myTaskExecutor-1] INFO  [tobedeleted] [trace=11421d270bbf1241] fr.ina.research.common.EventSource - @InboundChannelAdapter: dom was here `

Thx

**Comment by marcingrzejszczak** [comment]
I've fixed it I think @ddebaill :) Can you check if it's working? :P

**Comment by marcingrzejszczak** [comment]
It turned out that I completely messed up all the Camden releases in terms of Sleuth Stream :P This should fix it and Dalston too.

**Comment by ddebaill** [comment]
FYI, it works, both w/Camden and Dalston releases.
Just took some time to update my repo ;).

Thx

Dom
