### ISSUE TITLE
Big X-Span-Name headers can cause BAD-REQUEST

### ISSUE THREAD

**Issue by thyzzv** [spring-cloud/spring-cloud-sleuth#530]
We ran into a production issue while using Sleuth
We have a dynamic path variable that is a concatenation of list items. At some point the url used exceeds 5000 characters. Running the url in a browser executes just fine. But, using this is with Sleuth tracing enabled causes a the request header X-Span-Name to also contain these 5000+ characters which exceeds a certain threshold causing the receiving http server to block the request. returning a 400 BAD REQUEST

Given the following example project
https://github.com/thyzzv/sleuthspan-test

It shows the X-Span-Name. The project runs just fine, as there is no limit on the inbound Request Headers. But in our production environment we are running into a limit set by the apache (which we don't control).

**Comment by marcingrzejszczak** [comment]
We're truncating the name to 50 chars - that's the easiest solution and it should stop any name abuse

**Comment by thyzzv** [comment]
thnx
