### ISSUE TITLE
Sleuth on Camdem SR5 not compatible with Spring Boot 1.5.1

### ISSUE THREAD

**Issue by luizkowalski** [spring-cloud/spring-cloud-sleuth#531]
I have a Spring Boot (1.5.1) and just added Sleuth as follow:

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-sleuth</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-sleuth-zipkin</artifactId>
</dependency>
```

and updated my dep. management to Camdem SR5

```
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-dependencies</artifactId>
			<version>Camden.SR5</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
```

but when I start the app, I get 

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'zipkinSpanListener' defined in class path resource [org/springframework/cloud/sleuth/zipkin/ZipkinAutoConfiguration.class]: Unsatisfied dependency expressed through method 'zipkinSpanListener' parameter 2; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.core.env.Environment' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
```

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method envInfoContributor in org.springframework.boot.actuate.autoconfigure.InfoContributorAutoConfiguration required a bean of type 'org.springframework.core.env.ConfigurableEnvironment' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.core.env.ConfigurableEnvironment' in your configuration.
```

I worked fine with Spring Boot 1.4 and Camdem SR4

**Comment by marcingrzejszczak** [comment]
That's really surprising cause we're running quite a few tests in this combination. Could you please provide a sample? Also `Environment` bean has been there for ages. Most likely you have some other problem that leads to this but without a sample it's really difficult to tell what that problem is

**Comment by luizkowalski** [comment]
yes, sure @marcingrzejszczak 
I have this project for some time that I use for test new SB and Cloud functionalities: https://github.com/inkdrop/chathub-backend
on branch develop

**Comment by marcingrzejszczak** [comment]
@luizkowalski could you please provide a version of the branch that doesn't require the db? Some spring profile with which everything starts with in mem support?

**Comment by luizkowalski** [comment]
ok, so I created the branch https://github.com/inkdrop/chathub-backend/tree/bug/sleuth
where I'm using H2 embedded db, that should do it. You may see an error related to Firebase but can be safely ignored for this purpose

**Comment by dsyer** [comment]
There's a bean in `ReactorConfigurator` in that app called `environment`.
If you change that to `reactorEnvironment` does the error go away?

**Comment by luizkowalski** [comment]
yes, OF COURSE it the error goes away. 
I cannot believe I missed something so stupid! Thanks @dsyer
