### ISSUE TITLE
Trace id length - setting

### ISSUE THREAD

**Issue by tomaszglinski** [spring-cloud/spring-cloud-sleuth#535]
Hi, AFAICS there is no setting for length of ids. Is there a good reason to set it to 64 bits and not to change it (sure, such constant helps in many ways, but why not to allow to change it "only if you are really sure"?)

**Comment by marcingrzejszczak** [comment]
You can use either 128bit or 64bit number and that is configurable. We want to be Zipkin compatible that's why we're preparing those kind of numbers. With the newest release of Sleuth you'll be able to tweak it by registering a couple of beans. However we do suggest that you reconsider this and stay with the suggested defaults. 

What kind of a problem are you trying to fix by changing the length of the ids ?

**Comment by tomaszglinski** [comment]
Thanks for super fast answer. It is not about a serious problem, rather willingness to make it shorter, if I know the risk of collisions is low (because of amount of requests for example). It could also help on local dev envs, if you use logs a lot, to minimize the "boring" part of the log line (sure, it can be changed in other ways too).

Since it is addressed in incoming version, im closing the issue, thanks.

**Comment by marcingrzejszczak** [comment]
You can also change the logging pattern for devs and trim the id.

**Comment by jasonkoo** [comment]
Hi, I have two questions about id length and log format.
1. In your previous comment, you said it is possible to tweak the id length by registering a couple of beans. How to achieve that? I didn't find any information in the doc. Could you provide more detailed description?
2. Currently, the default log format produced by Sleuth is "[application_name, traice_id, span_id, is_exported]". Is it possible to change this format? For example, I want the format to be space separated without square brackets like "application_name trace_id span_id is exported".
Thank you!

**Comment by marcingrzejszczak** [comment]
Ad. 1)

By default we generate the 64 bit value of the id. You can change it to 128 here https://github.com/spring-cloud/spring-cloud-sleuth/blob/24f6827a4a968440bf286228edb085be9d00dfe5/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/SleuthProperties.java#L31 . Maybe you could elaborate more on what you're trying to achieve?

Ad. 2)

You have to change the `logging.pattern.level`. The default is set to https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceEnvironmentPostProcessor.java#L56

**Comment by jasonkoo** [comment]
Thank you for the quick response. This is very helpful.
