### ISSUE TITLE
E2E tracing From a non-spring application to a spring/sleuth one: Need some validation

### ISSUE THREAD

**Issue by ddebaill** [spring-cloud/spring-cloud-sleuth#537]
Hi

I have a non spring application (an ESB indeed) which has its own trace mechanism (w/traceid and spanid ;) ).
This application writes to a kafka topic consumed by a regular spring stream/sleuth microservice. I added simili sleuth headers to this topic (spanTraceId=myTraceId, spanId=myTopicId, aso ...) in order to get E2E tracing mechanism and leverage sleuth implementation where it's available.

This seems to work, sleuth recognize my headers and create new spans attached to my own trace.
Question is, do you think this approach is a good one or should I use another mechanism ?

Thank you for your help.

**Comment by marcingrzejszczak** [comment]
Yeah it seems like a good idea. If you create on this topic messages that Sleuth Stream understands then it's perfectly fine

**Comment by ddebaill** [comment]
Hi Marcin

Great. Thank you. No specific format to respect anyway ?

**Comment by marcingrzejszczak** [comment]
These are the headers we expect in terms of passing of tracing information in messages - https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceMessageHeaders.java#L29-L35 .

This is how a Span message should look like if you want to send it to a Sleuth Stream Collector - https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-stream/src/main/java/org/springframework/cloud/sleuth/stream/Spans.java

**Comment by ddebaill** [comment]
Perfect, will keep same formats then.
Thx

**Comment by ashwgupt** [comment]
If one is using a languages that has http://opentracing.io supported libraries, should not one use that instead?

**Comment by marcingrzejszczak** [comment]
You can check out this issue https://github.com/spring-cloud/spring-cloud-sleuth/issues/253 for more info about this. We've initially decided to pick a different transport format for sending spans via messaging and currently the plan to change it is low in terms of priority. You can always run our collector and store spans to the same DB as other collectors.

**Comment by ddebaill** [comment]
Hi 

@ashwgupt: not in our use case: we already use Sleuth tracing mechanism within our Spring Cloud applications but upstream and downstream we use components that don't rely on Spring (WSO2 ESB e.g.).
 In order to get E2E tracing, we had to find a bi-directional solution which propagates Sleuth headers from and to these components.

**Comment by marcingrzejszczak** [comment]
BTW let's differentiate 2 things here - one is tracing headers in messages and the other format of spans. Tracing headers in messaging can't be zipkin compatible since they are invalid for JMS (you can't have hyphens in header names).
