### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-sleuth#54]
- General background on tracing
- specifics on howto use sleuth (with or without zipkin)

what else @dsyer @adriancole @marcingrzejszczak

**Comment by dsyer** [comment]
I guess we need to look at all the configuration options

**Comment by marcingrzejszczak** [comment]
@dsyer - good idea, in micro-infra-spring we had a problem with actually finding all the options. Maybe we could think of automating that a little bit? I'm not saying that we should do it right now. It could be worth to generate a page with all the configuration options and maybe as a description pass the javadoc or sth. Just an idea...

Until then maybe it would be worth to create manually a table with current params, their defaults and some short description?

**Comment by dsyer** [comment]
@snicoll has some tools to automate configuration docs. We should invest some time in them and get an appendix into Spring Cloud docs.

**Comment by snicoll** [comment]
There's a few things [here](https://github.com/snicoll-scratches/spring-boot-config) in particular [AppendixGenerator](https://github.com/snicoll-scratches/spring-boot-config/blob/master/spring-boot-config-diff/src/main/java/net/nicoll/boot/config/diff/AppendixGenerator.java)

It's very _raw_ but does the job for the checks I am applying between each release. Spring Boot does not  generate the doc automatically yet but looking at this is good enough to spot inconsistencies (wrong/conflicting namespaces, etc).

Please ping me if you need more info

**Comment by marcingrzejszczak** [comment]
Done in http://cloud.spring.io/spring-cloud-static/spring-cloud.html
