### ISSUE TITLE
TraceFeignClient has static logger, but was it mean to be dinamic ?

### ISSUE THREAD

**Issue by dquintela** [spring-cloud/spring-cloud-sleuth#540]
```
class TraceFeignClient implements Client {
	private static final Log log = LogFactory.getLog(MethodHandles.lookup().lookupClass());
```
Seems to be creating a logger that is sensitive to caller, but is static.

Shouldn't it be created on demand on the execute method instead ?

**Comment by marcingrzejszczak** [comment]
Nope. I was too lazy to each time pass in the class name so I used a static method to resolve the name.
