### ISSUE TITLE
Exceptions thrown in controllers don't get span/trace IDs

### ISSUE THREAD

**Issue by sixcorners** [spring-cloud/spring-cloud-sleuth#542]
It looks like when an exception is thrown from a rest controller the filter removes the span from the MDC and when it's eventually logged in [StandardWrapperValve](https://github.com/apache/tomcat/blob/trunk/java/org/apache/catalina/core/StandardWrapperValve.java) that information isn't available.

If there were a TraceValve instead of a TraceFilter I think the span would get added to the log messages produced by uncaught exceptions.

**Comment by sixcorners** [comment]
Log output:
https://github.com/sixcorners/tests/commit/49cac50bec8ab7ba1d28f9b14c0658cbe21c63f6
Sample:
https://gist.github.com/sixcorners/82200bf723c9fd8fbc3bf7f161187edb

**Comment by marcingrzejszczak** [comment]
Thanks! I'll try to check this out ASAP

**Comment by sixcorners** [comment]
I'm not sure if this is a bug. Is it supposed to add the span ID to default logged exceptions? The examples I have seen always involve doing to logging yourself. We have been working around it by making `@ExceptionHandler` methods and logging them ourselves. It would just be nice if the logging tomcat does had the span on it.

**Comment by marcingrzejszczak** [comment]
I can't yet tell if it's a bug but that would be very valuable to have the span info over there. I'll try to see if it's a bug or a feature request :)

**Comment by marcingrzejszczak** [comment]
@sixcorners I was thinking about this and actually I think that this is not a bug. The problem is that `Valve` comes from Catalina and we don't want to be Tomcat specific on this. That's why we have the `ExceptionHandlers`. I don't think that this is a workaround - quite the contrary - it's a good practice. Does it make any sense what I'm saying? :P

**Comment by marcingrzejszczak** [comment]
Ping @sixcorners ?

**Comment by marcingrzejszczak** [comment]
Closing the issue due to inactivity
