### ISSUE TITLE
Support adding baggage before newly created span is logged.

### ISSUE THREAD

**Issue by aknrdureegaesr** [spring-cloud/spring-cloud-sleuth#547]
I'm using `tracer.createSpan` and want to add baggage to the newly created span.

I want that baggage to be available when the newly created span is handed over to my subclass of `Slf4jSpanLogger` for logging.

This is not well supported with the present API (we use 1.2.0M1). You get the new span only after it already has been logged. There seems to be no way to seed baggage.

**Comment by marcingrzejszczak** [comment]
What exactly are you trying to achieve? The logger logs when span is started (there's no baggage then), continued (you might have baggage) or closed (you will have baggage).

**Comment by aknrdureegaesr** [comment]
The logger logs when the span is started. That logger is my own subclass of `Slf4jSpanLogger`. That logger needs the baggage for complete log output. But it doesn't find it, because the baggage is only added afterwards. That's the problem I have.

As an ugly hack, I log again from where I generate the span.

I need a way to pre-seed the baggage into the tracer.

**Comment by marcingrzejszczak** [comment]
That's currently not possible. We have no idea when you'll add baggage so it's actually up to you to control what you're logging and where. I don't think what you're doing is an ugly hack. You could override the `logger.setBaggageItem` to log the baggage.

**Comment by aknrdureegaesr** [comment]
> That's currently not possible.

A good summary of the problem I have, yes.

> We have no idea when you'll add baggage

In the case relevant for this ticket, I want to add the baggage right away, as I'm creating the span.

> so it's actually up to you to control what you're logging and where.

Well... It's not my code that calls the logger, but the code of the tracer. Which would be just perfect for my case. If only the tracer's API would give me a way to add my initial baggage _before_ it calls the logger.

> You could override the `logger.setBaggageItem` to log the baggage.

 Where's that method? Didn't find it in `Slf4jSpanLogger` aka https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jSpanLogger.java .

**Comment by marcingrzejszczak** [comment]
Sorry my bad, I've forgotten that we add baggage on a span not from tracer. Disregard what I suggested about the `logger.setBaggageItem`.

So the logger is active on three events

1) Span started
2) Span continued
3) Span closed

There is no way you can customize it other than rewriting the `Tracer` implementation. But if your idea is to print in the MDC the baggage you can use the following workaround. In your custom logger you can add/remove the MDC entry for baggage and you can call the span creation like this:

```
Span s = tracer.createSpan("foo");
s.setBaggageItem("key", "value");
tracer.continueSpan(s);
```

That way the last line will call the logger with all the proper baggage stuff. That's the best workaround we can provide for now. We were not planning on adding hacks to change the way logging events can be customized.

**Comment by marcingrzejszczak** [comment]
Ping @aknrdureegaesr ?

**Comment by aknrdureegaesr** [comment]
What can I say? You suggest I should hack.

The `createSpan()` already calls my logger, but without the information it needs. So I don't like your suggestion.

I would much prefer you provide an option to hand in a `Function<Span, Span>` into `tracer.createSpan()` that gives me control over the `Span` right after creation, before it is actually used for anything.

**Comment by marcingrzejszczak** [comment]
I say that what you want to do is a hack. That's why the solution looks like what you want to do ;)

So currently we can't offer you such a solution. If there are more people interested in this feature then we can come back to it and think of some additional approaches. Until then I'm closing the issue.

**Comment by aknrdureegaesr** [comment]
My analysis:

The baggage feature opens up sleuth. By that feature, it can be used in environments where what the logging should look like cannot be governed by what spring cloud sleuth offers. You need to do two things: 

* Add baggage to the spans, containing the information your environment demands of you.
* Implement your own loggers, that take advantage of that information.

So far the theory. That describes how it should be. In practice, however, as this discussion and my experience shows: If you seriously want to use the baggage feature, you have no problem with implementing your own logger subclasses.

But an interface to add baggage before your special-purpose loggers are called - does not exist.

I thought I'm using the baggage feature exactly as it was intended to be used. I fail to see why using baggage and my own subclasses of `Slf4jSpanLogger` is hacky. I would like to receive your advice on that, @marcingrzejszczak .

For the time being, as I have not yet received such advice, my understanding is that using the baggage feature leads you straight into hacking. In other words, the baggage feature is not well-supported.

**Comment by marcingrzejszczak** [comment]
I completely disagree with you. The idea is extremely simple. You set a baggage item in one service and then in another service you can retrieve that baggage item via a key. I really don't understand what else you want to achieve. 

> But an interface to add baggage before your special-purpose loggers are called (are called by sleuth code, mind you!) - does not exist.

We're logging only 3 events. I don't understand really why you have focused so much on logging a baggage item to MDC before the span is created.  It doesn't exist cause there was no need for that.

> I thought I'm using the baggage feature exactly as it was intended to be used

You're not cause we weren't expecting anyone to break the "contract" on the events in Sleuth.

>For the time being, as I have not yet received such advice, my understanding is that using the baggage feature leads you straight into hacking. In other words, the baggage feature is not well-supported.

I disagree. What you want to achieve is a misusage of Sleuth thus you need to do some workarounds.

**Comment by aknrdureegaesr** [comment]
I'm not concerned with the part where you shove baggage from one service through a remote call to another service. That stuff works for me.

I have custom code that retrieves the baggage from the incoming request and tries to generate a new span with that baggage. Log records written with that span active contain my baggage - all of them. With notable exceptions: Initial logging, done from sleuth code at span initialisation time, should (in my firmly held conviction) contain the baggage information, but don't.

(For the record: I'm in a non-Zipkin situation.)

> I don't understand really why you have focused so much on logging a baggage item to MDC before the span is created.

I never said I want to log _before_ the span is created.

I don't particularly care about logging when the span is created. But logging when the span is created is something that sleuth code does. Fine with me, makes sense, it may do so.

But I do want log records being written to be correct. I do not want to have records in my log output, that, from the logic of things, should contain my additional baggage information, but then I find they don't. This is simply a small bug, a glitch.

Sleuth lacks an opportunity to set up baggage information at span creation. I can set baggage afterwards, but at that point the newly created span has already been used for logging. It has already generated a log record. I strongly feel that log record should have the information from the baggage, the information that is the sole reason why the span is created in the first place. But the log record is missing that information.

> What you want to achieve is a misusage of Sleuth

I keep re-iterating the question: Which of the two is that misuse?

* Is it a misuse to organize additional information you want to see in your logs as span baggage?
* Is it a misuse to put baggage information into the log records being written out by overriding the logger?

Or what else is a misuse?

**Comment by aknrdureegaesr** [comment]
Let me put it this way:

* If I create a span with certain baggage information
* and I overwrite the logger to write that baggage information into the log
* but than I see records in the log that were logged by that logger, with that span active, but do not contain the baggage information

- that's a bug.

**Comment by marcingrzejszczak** [comment]
Can you create a sample that proves this? It would be much more helpful to really understand what you want to achieve and replicate the issue

**Comment by aknrdureegaesr** [comment]
I can try to come up with some JUnit test or something that condenses this. Sure. Give me a few days.

**Comment by marcingrzejszczak** [comment]
Any luck @aknrdureegaesr ?

**Comment by aknrdureegaesr** [comment]
Didn't find the time yet to create a test. We have span-generating code that looks about like this, if that helps any:

```
    public Span startNewSpanWithFooBar(String spanName) {
        String bar = ...;
        Span parent = tracer.getCurrentSpan();
        // This already registers the span with Slf4j, creating a log entry without baggage:
        Span newSpan = tracer.createSpan(Preconditions.checkNotNull(spanName));
        // Only now we get a chance to add the bar baggage with the foo key to that span:
        newSpan.setBaggageItem("foo", bar);
        return newSpan;
    }
```

**Comment by adriancole** [comment]
I was thinking about this problem in a different context. If the baggage is
independent (ex doesnt require user apis to decide what it is) a pre-hook
or custom log context synchronizer is the easiest way out.

Otherwise, each time baggage is added that state needs to be resynchronized
with whatever is in scope (slf4j etc). The latter makes the api for the log
context synchronizer more complex as the state model is different.. ex an
update command which apllies independent of span lifecycle or
inject/extract.

Whatever is done here one or not one thing is clear that we understand what
works and what doesnt better. At least javadoc might be needed to capture
this.

**Comment by marcingrzejszczak** [comment]
I'm sorry I completely don't understand this issue. 

I tried to focus on this:

> Let me put it this way:
> If I create a span with certain baggage information
> and I overwrite the logger to write that baggage information into the log
> but than I see records in the log that were logged by that logger, with that span active, but do not > contain the baggage information
> - that's a bug.

So I created a test where I created a custom span logger. And I'm sorry to say this but I can't replicate your issue @aknrdureegaesr . My logger gets called, the baggage is there on the parent and it's on the child. Maybe I'm doing sth wrong here to replicate this. If you don't provide a sample I'll have to close this issue for now...

```
public class CustomLoggerTests {

	CustomSpanLogger spanLogger = new CustomSpanLogger();
	Tracer tracer = new DefaultTracer(new AlwaysSampler(), new Random(),
			new DefaultSpanNamer(), this.spanLogger, new NoOpSpanReporter(), new TraceKeys());

	@Test
	public void should_pass_baggage_to_custom_span_logger() {
		Span parent = Span.builder().spanId(1).traceId(2).baggage("foo", "bar").build();

		Span child = this.tracer.createSpan("child", parent);

		then(child).hasBaggageItem("foo", "bar");
		then(this.spanLogger.called.get()).isTrue();
	}
}

class CustomSpanLogger extends Slf4jSpanLogger {

	private static final Log log = LogFactory.getLog(MethodHandles.lookup().lookupClass());

	final AtomicBoolean called = new AtomicBoolean();

	public CustomSpanLogger() {
		super("");
	}

	@Override public void logStartedSpan(Span parent, Span span) {
		super.logStartedSpan(parent, span);
		called.set(true);
		then(parent).hasBaggageItem("foo", "bar");
		then(span).hasBaggageItem("foo", "bar");
		log.info("Baggage item foo=>bar found");
		log.info("Parent's baggage: " + parent.getBaggage());
		log.info("Child's baggage: " + span.getBaggage());
	}
}
```

and the logs are

```
2017-04-11 14:48:40.528  INFO   --- [           main] o.s.cloud.sleuth.trace.CustomSpanLogger  : Baggage item foo=>bar found
2017-04-11 14:48:40.531  INFO   --- [           main] o.s.cloud.sleuth.trace.CustomSpanLogger  : Parent's baggage: {foo=bar}
2017-04-11 14:48:40.532  INFO   --- [           main] o.s.cloud.sleuth.trace.CustomSpanLogger  : Child's baggage: {foo=bar}
```

**Comment by aknrdureegaesr** [comment]
I can give you the call path...

* I'm calling `Tracer.createSpan()` as above.
* The implementation that's used is `org.springframework.cloud.sleuth.trace.DefaultTracer`.
* That delegates to its own message `Span createSpan(String name, Sampler sampler)`
* That contains a line of code `this.spanLogger.logStartedSpan(null, span);`
* That delegates to my own subclass of `Slf4jSpanLogger` that I provided (via Spring dependency injection)
* That subclass expects the baggage. It is not there yet, it cannot be there yet, as the original call to `Tracer.createSpan()` has not yet returned the span for me to add any baggage to it.

**Comment by marcingrzejszczak** [comment]
In Sleuth first you have to create a span to add baggage to it. These are 2 separate things. If you want to create a custom span yourself you can use the builder as I have in the test. There is no other way ATM and we're not thinking of providing any other way.

So what you can do is...

```
// create span manually
Span span = Span.builder().spanId(1).traceId(2).baggage("foo", "bar").build();
// continue that span
tracer.continueSpan(span);
// your custom logger will see the baggage
```

Is this answer satisfactory?

**Comment by aknrdureegaesr** [comment]
Yes! I have to test it, but it rather looks like that functionally solves my problem.

So the only thing we might now still consider is how to improve the documentation so the next person trying to do what I tried to do will find the right method to call.

> Creates a new Span with a specific parent. The parent might be in another process or thread.

That scared me away from simply pulling the parent span out of blue sky. I didn't think it safe to simply invent a parent span that is not connected with anything. I thought the `spanName` thing is what one should use in my situation.

**Comment by marcingrzejszczak** [comment]
> So the only thing we might now still consider is how to improve the documentation so the next person trying to do what I tried to do will find the right method to call.

You're the first person to ask about this. If more people ask about the same problem for sure I'll patch the docs.

> That scared me away from simply pulling the parent span out of blue sky. I didn't think it safe to simply invent a parent span that is not connected with anything. I thought the spanName thing is what one should use in my situation.

So if you use the `Tracer` API we build the span for you. It's not a typical situation where you have to build the span manually. I'd say that a typical situation is that you only append tags / logs / baggage to the span. If you need to do some custom manuall stuff then that's the way to go. Of course remember about closing that span....

```
// create span manually
Span previousSpan = tracer.getCurrentSpan();
// pseudocode
Span span = Span.builder().parent(previousSpan.getSpanId()).spanId(new Random().nextLong()).traceId(previousSpan.getTraceId()).baggage("foo", "bar").build();
// continue that span
tracer.continueSpan(span);
// your custom logger will see the baggage
try {
 // do some stuff
} finally {
  tracer.close(span);
}
// here you're again continuing the parent span
```

**Comment by marcingrzejszczak** [comment]
Closing the issue since the workaround satisfies the requirements.
