### ISSUE TITLE
TraceAsyncAspect#traceExecutor is not compatible with spring-security DelegatingSecurityContextExecutor

### ISSUE THREAD

**Issue by nbruno** [spring-cloud/spring-cloud-sleuth#550]
When using a [`DelegatingSecurityContextExecutor`](https://github.com/spring-projects/spring-security/blob/master/core/src/main/java/org/springframework/security/concurrent/DelegatingSecurityContextExecutor.java) from [`spring-security`](https://github.com/spring-projects/spring-security), the `traceExecutor` point cut is applied. However, this bean can't be proxied through AOP since it declares a final field. As is, if the `traceExecutor` point cut is applied, the `delegate` field within `DelegatingSecurityContextExecutor` becomes `null`, which will cause later failures when trying to use this bean.

**Comment by marcingrzejszczak** [comment]
Fixed! You can check out the latest snapshots and it should work :)

**Comment by kaweston** [comment]
I'm seeing the same behaviour (if not same root cause) of the delegate set to null with spring-security-core:5.1.4-RELEASE (as a dependency of spring-boot-starter-security:2.1.3.RELEASE) and spring-cloud-sleuth-core:2.1.0.RELEASE (as a dependency of spring-cloud-starter-sleuth:2.1.0.RELEASE).

**Comment by marcingrzejszczak** [comment]
Ok, can you check that the latest snapshots fix your problem?
