### ISSUE TITLE
LazyTraceThreadPoolTaskExecutor - Tried to detach trace span but it is not the current span

### ISSUE THREAD

**Issue by aj070** [spring-cloud/spring-cloud-sleuth#552]
Spring Boot version 1.4.5.RELEASE
Spring Cloud Dependencies Camden.RELEASE

I have a background job running on each request, which will take the thread from a LazyTraceThreadPoolTaskExecutor. But on running the trace I'm getting the following warning.
Is it ok to go ahead to the prod by ignoring this warning? Or will it cause memory leaks?

WARN [app-name, 5c964a40ec5ad420,5c964a40ec5ad420,false] 26660 --- [bgJob-1] o.s.cloud.sleuth.util.ExceptionUtils     : Tried to detach trace span but it is not the current span: [Trace: 5c964a40ec5ad420, Span: 5c964a40ec5ad420, Parent: null, exportable:false]. You may have forgotten to close or detach null

**Comment by marcingrzejszczak** [comment]
It shouldn't cause any memory leaks. But that means that we're trying to close or detach a span that was already closed. We'll need to fix this situation

**Comment by aj070** [comment]
Thanks marcingrzejszczak. I think similar issue existed in #257, #447, #198

**Comment by marcingrzejszczak** [comment]
Always when there's a problem with closing spans we log this message. That's why you're seeing this. The fix should be easy cause we shouldn't detach a detached span.
