### ISSUE TITLE
Rethink Spring Cloud Stream Zipkin integration

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#555]
Spring Cloud Sleuth Stream Zipkin is very different than the rest of sleuth code as it is a custom server. I think it would be best to pull this into a separate repo which includes at least the collector side, if not also the sender side. This would be similar to zipkin-aws where SQS a custom transport can be plugged into a vanilla zipkin server (and any tracer for that matter)

https://github.com/openzipkin/zipkin-aws/tree/master/autoconfigure/collector-sqs#running

Most zipkin integrations do not require a custom build, rather custom assembly. For example, zipkin-aws and zipkin-azure layer autoconfiguration on top of the base server. This allows people to mix and match things, for example using a kafka collector, but a google cloud storage. Importantly, this allows people to compose servers in their tool of choice, albeit docker, puppet, chef or doit.sh without a custom build.

There's only one catch to this, which is that the maven setting (module) used there has been removed in spring boot 1.5 (openzipkin/zipkin-aws#32). Across all projects we would need a similar remedy to that.

cc @dsyer

**Comment by marcingrzejszczak** [comment]
It was rethought in a very brutal way :P https://github.com/spring-cloud/spring-cloud-sleuth/issues/727
