### ISSUE TITLE
Smarter sampling and forcing tracing for certain requests

### ISSUE THREAD

**Issue by swehner** [spring-cloud/spring-cloud-sleuth#56]
I have a question regarding how the tracing is turned on for requests:

I understand that on one hand there's the Sampler which allows for a service to basically turn on tracing for a random sample of requests (seems like the info part is not implemented yet in any way, correct?).
Then there is also the "X-Not-Sampled" header, which if set disables tracing for the call.
So basically sleuth allows for turning on tracing for a certain percentage of requests at any point, or disallowing the tracing of a call setting the X-Not-Sampled header.

Is there any way to force the tracing of a call setting a header e.g. if you want to debug a certain call?
In our experience logging all calls often creates too much information and using sampling proves most valuable at the most external entrypoints (so that we always get a full trace, instead of partial traces if some random sampler activates tracing somewhere downstream).
But it'd still be very useful to be able to turn on tracing to debug certain calls - so maybe having the same behavior of the X-B3-Sampled header in brave?
Also being able to trace certain calls, e.g. by rest method name with a different percentage would be very useful. I guess that the info part of the sampler is supposed to be used for this, but I can't see how this is going to work in the current implementation

I'm probably missing something on how this is working - if you have any more documentation/info on how these headers are being used please let me know!
Thanks in advance for your help!

**Comment by marcingrzejszczak** [comment]
In Zipkin there is the `debug` flag that can be used to enforce sampling. We don't support that but ATM you can try to use a custom sampler (like this one https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/sampler/PercentageBasedSampler.java). If you need to pass some values to that sampler you can add some logs or tags on Span and then profit from that in a Sampler.

**Comment by marcingrzejszczak** [comment]
Ping?

**Comment by marcingrzejszczak** [comment]
Closing due to lack of feedback
