### ISSUE TITLE
Custom ThreadPoolExecutor

### ISSUE THREAD

**Issue by felipelino** [spring-cloud/spring-cloud-sleuth#565]
In my company we use a custom ThreadPoolTaskExecutor.

To still use our Executor with Sleuth we did:
```
    @Autowired
    private BeanFactory beanFactory;

    @Override
    public Executor getAsyncExecutor() {
        YourCustomThreadPoolTaskExecutor executor = new YourCustomThreadPoolTaskExecutor();
        //CUSTOMIZE HERE
        executor.setCorePoolSize(100);
        executor.setMaxPoolSize(150);
        executor.setThreadNamePrefix("my-prefix");
        executor.setQueueCapacity(50);
        executor.setKeepAliveSeconds(30);
        executor.initialize();

        LazyTraceExecutor lazyTraceExecutor = new LazyTraceExecutor(beanFactory, executor);
        return lazyTraceExecutor;
    }
```

This could be helpfull to others and be included in docs: https://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_executor_executorservice_and_scheduledexecutorservice

**Comment by marcingrzejszczak** [comment]
Are you using a `AsyncConfigurer` bean to generate that? Cause if you do then we're already wrapping that object via `AsyncCustomAutoConfiguration` bean.

**Comment by felipelino** [comment]
No. My class extends org
.springframework.scheduling.annotation.AsyncConfigurerSupport:

@Configuration
@EnableAsync
public class AsyncAppConfig extends AsyncConfigurerSupport



2017-04-18 9:14 GMT-03:00 Marcin Grzejszczak <notifications@github.com>:

**Comment by marcingrzejszczak** [comment]
Yeah but `AsyncConfigurerSupport` is an instance of `AsyncConfigurer`. Do you have a sample that I can check? You could put a breakpoint in `AsyncCustomAutoConfiguration` in this method

```java
@Override
	public Object postProcessAfterInitialization(Object bean, String beanName)
			throws BeansException {
		if (bean instanceof AsyncConfigurer) {
			AsyncConfigurer configurer = (AsyncConfigurer) bean;
			return new LazyTraceAsyncCustomizer(this.beanFactory, configurer);
		}
		return bean;
	}
```

**Comment by felipelino** [comment]
My complete class is:

import com.b2winc.corpserv.async.setting.AsyncSetting;
import org.springframework.aop.interceptor.AsyncUncaughtExceptionHandler;
import org.springframework.beans.factory.BeanFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;
import org.springframework.scheduling.annotation.AsyncConfigurerSupport;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;

import java.lang.reflect.Method;
import java.util.concurrent.Executor;

@Configuration
@EnableAsync
public class AsyncAppConfig extends AsyncConfigurerSupport {

    @Autowired
    private AsyncSetting asyncSetting;

    @Autowired
    private BeanFactory beanFactory;

    @Override
    public Executor getAsyncExecutor() {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(500);
        executor.setMaxPoolSize(1000);
        executor.setThreadNamePrefix("msg-receiver");
        executor.setQueueCapacity(100);
        executor.setKeepAliveSeconds(10);
        executor.initialize();
        return executor;
    }

    @Override
    public AsyncUncaughtExceptionHandler getAsyncUncaughtExceptionHandler() {
        return new AsyncUncaughtExceptionHandler() {
            @Override
            public void handleUncaughtException(Throwable throwable,
Method method, Object... objects) {

            }
        };
    }
}


Even when I changed to implement AsyncConfigurer instead of extends
AsyncConfigurerSupport the breakpoint inside the '*if (bean instanceof
AsyncConfigurer)*' never was reach.

When I @Autowired AsyncConfigurer in a variable in other class my instance
was there as expected.

[image: Imagem inline 1]

2017-04-18 9:42 GMT-03:00 Marcin Grzejszczak <notifications@github.com>:

**Comment by marcingrzejszczak** [comment]
Is there an option for you to attach logs from application startup? I'd like to see if there's anything written about excluding `AsyncAppConfig` from bean post processing.

**Comment by felipelino** [comment]
Yes,

I changed for DEBUG is attached.

Abraços,
Felipe Lino

2017-04-18 10:15 GMT-03:00 Marcin Grzejszczak <notifications@github.com>:

**Comment by marcingrzejszczak** [comment]
I don't see anything...

**Comment by marcingrzejszczak** [comment]
Done here https://github.com/spring-cloud/spring-cloud-sleuth/commit/3d7b15f62c67c257eea1b4f9b7a1075d76bde6de
