### ISSUE TITLE
How to inject gtid(from api gateway) as trace id in spring sleuth

### ISSUE THREAD

**Issue by b-rajesh** [spring-cloud/spring-cloud-sleuth#574]
Hi,

I am looking around  to override trace id in spring by getting global transaction which was set by API Gateway. I would like to use the gateway gtid as trace id, instead of spring to generate one for me. Have any one done that ?

**Comment by marcingrzejszczak** [comment]
You can do one of two things. 

You can register your own bean of `Random` type that will generate a long of your choosing for you. Check https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java#L55-L59 and https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/trace/DefaultTracer.java#L225-L227 .

And second way. If you can use the latest snapshots you can profit from `SpanAdjuster` and basically fully change whichever part of your span sent to Zipkin - http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_customization_of_reported_spans . But you'll have a mismatch between logs and Zipkin.

I'd go with the first option if I were you.

**Comment by marcingrzejszczak** [comment]
Ping @b-rajesh ?

**Comment by b-rajesh** [comment]
Hi, I don't want to generate another id for trace. but i want to reuse the GTID from request which is already supplied in the request header.

**Comment by marcingrzejszczak** [comment]
So your option to do that is to use the new feature from Dalston.RELEASE - http://cloud.spring.io/spring-cloud-static/Dalston.RELEASE/#_customizations . You can register a `HttpSpanInjector` and `HttpSpanExtractor` like presented in this section of the docs and provide different headers from which you'd like to pick the IDs.

**Comment by b-rajesh** [comment]
ok will give it a try. it looks promising.
