### ISSUE TITLE
Attaching the Exception/Throwable to the Span

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-cloud/spring-cloud-sleuth#576]
I wanted to report the `Span`s to logs instead of Zipkin, see: #575.
I would like to report more details about the Exception than the [current error message in the tags](
https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/Span.java#L95).

For this, it would be great if the `Span` could contain the Exception/Throwable, not just the error message as a tag.

**Comment by marcingrzejszczak** [comment]
I think that we shouldn't mix the two - Zipkin and logging. I think that the purpose of Zipkin is to see latency issues mainly. We're trying our best not to store too much data in Zipkin since that way grouping by tags is definitely less efficient. WDYT @adriancole ?

**Comment by jonatan-ivanov** [comment]
Sorry for the misunderstanding, I don't want to mix them, I'm not talking about Zipkin here at all. By `Span`, I meant the sleuth span (`org.springframework.cloud.sleuth.Span`), not the Zipkin span (`zipkin.Span`).

So putting a reference to the Exception in the sleuth span (`org.springframework.cloud.sleuth.Span`) should not have any effect on the Zipkin span (`zipkin.Span`), the Zipkin reporting or what Zipkin stores.

I'm only saying here that if you want to use the sleuth span (`org.springframework.cloud.sleuth.Span`) for any reasons,  having the exception in it is very useful.

Personally I would be very happy to have this small feature and I don't really know how can I work this around without ugly hacking.

**Comment by adriancole** [comment]
I don't think adding a field is problematic as much as no-one using it, then being curious why it is there. To do exception handling with span holding a reference would be quite a wave of change I think, right? So even if it were desired, it would be a lot of work or otherwise a "tease" or otherwise not yet used functionality.

**Comment by marcingrzejszczak** [comment]
> Personally I would be very happy to have this small feature and I don't really know how can I work this around without ugly hacking

Use normal logging? I mean whenever an exception is thrown in different instrumentations that we have, there we add the tag and continue normally. So that means that if you don't swallow exceptions anywhere you'll see them in your logs.

**Comment by jonatan-ivanov** [comment]
@adriancole

If my understanding is correct only 7 files adds the error tag (`Span.SPAN_ERROR_TAG_NAME`) to the `Span`: [see search](https://github.com/spring-cloud/spring-cloud-sleuth/search?p=2&q=SPAN_ERROR_TAG_NAME&type=&utf8=%E2%9C%93)

These are the files where the `Exception` should be added to the `Span`, right? So in these files we need a one-liner change (if we don't want to optimize the error message tag based on this) + the changes in the `Span` + tests.

To me this does not seem to much change, or am I missing something?

**Comment by jonatan-ivanov** [comment]
@marcingrzejszczak

I have "normal" logging. :) What I would like to have is a little bit more than that.
The original problem here that I want to solve is having a trace/perf/transaction log (see: #575) so that I can easily build dashboards about latency, success rate, error distribution, etc. I don't need anything else to build these dashboards and I can tell the cause of any issue(s) just by checking the dashboard, I don't need to check the stacktrace (it is in the normal log just for sure).

Here is a formatted example with the fields that I want to log out in just one log entry (/line):
```
2017-04-26 12:34:56.789
span="authenticate"
traceId="e5c8ceeb215bffca"
spanId="751414412ae52107"
parent="e5c8ceeb215bffca"
duration="1000"
exportable="true"
success="false"
eventName="AUTH_SVC_ERROR"
eventId="12345"
classification="TECHNICAL"
errorClass="...ExternalException"
errorMessage="Hulk sad..."
rootCauseClass="...SocketTimeOutException"
rootCauseMessage="request timed out"
userName="testUser"
customfield01="customvalue02"
```

At the moment I can get most of the info from the span, and I can attach custom fields to the baggage but I would like to have more information about the Exception, e.g.: the root cause and my custom fields in my custom exception: eventName, eventId, classification, etc.

**Comment by adriancole** [comment]
Adding exception to all instrumentation sites, adding tests for each,  some
sort of default formatter for "error" tag, and documenting how to use it is
all part of work like this. If you are keen to bear this responsibility we
can chat about next steps. Otherwise it is a burden as incomplete feature.
Sound fair?

**Comment by jonatan-ivanov** [comment]
@adriancole I am; deal. :)

**Comment by adriancole** [comment]
I was thinking about allowing an error tag parser to be configured and passed with the span.

Then, users can do `span.addError(Throwable e)` or similar. This would invoke default logic like what's in TraceChannelInterceptor file, but the function would be customizable.

Ex. `TagError.tag(Span, Throwable)` which by default does a safe variant of adding the message or simple class name on null message.

**Comment by adriancole** [comment]
Note: it could also be `String ErrorTagParser.parse(Throwable t)`. this might be easier as it is a single-param function and is easy to understand that this is associated with the "error" tag.

For your custom format, sleuth's first goal isn't to facilitate custom data formats, but I think existence of a hook to format the error will give you an option you don't have now in order to do your custom stuff.

**Comment by marcingrzejszczak** [comment]
I had a chat with @adriancole and we'll go down the Brave way and introduce sth similar. I'll try to propose some option for discussion today

**Comment by marcingrzejszczak** [comment]
Ok a PR is ready - fire away your comments https://github.com/spring-cloud/spring-cloud-sleuth/pull/590 @adriancole @jonatan-ivanov  :)
