### ISSUE TITLE
sleuth in stream cant trace

### ISSUE THREAD

**Issue by mindyue** [spring-cloud/spring-cloud-sleuth#582]
consumer and producer **in the same project** 

```
 public interface BaseHandlerProcessor {
	@Input(BaseProcessor.BASE_CHANNEL)
	SubscribableChannel input();
 }

```

```
public interface BaseProcessor {
	static final String BASE_CHANNEL = "MBaseChannel";
	@Output(BaseProcessor.BASE_CHANNEL)
	MessageChannel output();
}
```

message can send to producer ,but sleuth taceid is new one .
like ,in consumer is  

2017-05-02 17:04:08.380 INFO[80ed001d5294a232,80ed001d5294a232,true] c.u.m.p.d.w.v.TestProvider.smssend :1 thread id=46

in producer is 
[microservices-demo]2017-05-02 17:04:08.489 INFO[029405ce43af7d2f,029405ce43af7d2f,true] c.u.m.p.d.s.h.EventHandler.handler :3 thread id=37

i think the output channel interceptor isnt working .but why ,thanks...

**Comment by marcingrzejszczak** [comment]
Can you please post a sample on Github?

**Comment by marcingrzejszczak** [comment]
Ping?

**Comment by mindyue** [comment]
i know the reason,cause i send message to message channel without rabbitmq . they are in same thread .and now i separate the input and output channel in different name . it`s working now ...thx very much . : )

**Comment by marcingrzejszczak** [comment]
No problem!
