### ISSUE TITLE
Reconsider to remove `spring.aop.proxyTargetClass` from the TraceEnvironmentPostProcessor 

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-sleuth#584]
Since Spring Boot 2.0 the `spring.aop.proxyTargetClass` is `true` by default: https://github.com/spring-projects/spring-boot/issues/8786. Therefore we don't need to specify such a property explicitly.

On the other hand having that unconditional in the `TraceEnvironmentPostProcessor` code makes it impossible to override via `application.properties`.

Shouldn't we wrap it into `if` at least:
```
if (environment.containsProperty(spring.aop.proxyTargetClass) {
    map.put("spring.aop.proxyTargetClass", "true");
}
```
?

**Comment by marcingrzejszczak** [comment]
Already filed in https://github.com/spring-cloud/spring-cloud-sleuth/issues/583 . Will remove #583

**Comment by marcingrzejszczak** [comment]
I think we should fix the reason why we had to force it. Cause without this some features were broken. Obviously I don't remember those right now but will take a look into it.

**Comment by artembilan** [comment]
>  Cause without this some features were broken. 

Well, I think that is why Spring Boot reconsider that to have `true` by default.
In the presence that looks like we should reconsider otherwise - fix those who are not compatible wit CGLib. Like we have just done in Spring Integration https://jira.spring.io/browse/INT-4270.

My main point here that we can't override it to `false` if we use Sleuth.
Of course, for Boot 2.0-based branch there is just enough to remove it altogether.

And yes, would be better from the day first just recommend those guys with Websocket issue to switch on `spring.aop.proxyTargetClass` in their `application.properties` instead of doing such an unconditional decision...

**Comment by marcingrzejszczak** [comment]
Yeah - so the best option would be to remove this line from Sleuth at all and fix Websockets.

**Comment by artembilan** [comment]
Let's forget those Websockets for now!

There might be other cases (TX?) which require CGLib and they even may not know about our `spring.aop.proxyTargetClass = true`, because it comes with Sleuth as out-of-the-box.

You have an unconditional option there which can't be reset. That must be fixed via condition.
Since this option is there for a while already: https://github.com/spring-cloud/spring-cloud-sleuth/commit/4bd484fb214f65736efd6e8903cfb308e700ec88, we can't just remove it from the maintenance versions. That must be as `true` by default, but provide an ability for end-user to override it would be great solution.

We can remove it altogether only from the branch based on the Boot `2.0`. Because only from there it will be `true` from the top. But there we can override it already now.

As a flexible fix we might consider conditional auto-config similar to the `EnableTransactionManagementConfiguration`. This way we remove that explicit option from the `TraceEnvironmentPostProcessor` and will rely on the overriding via application properties.
