### ISSUE TITLE
[1.2.x] Duplicate Trace Header Propagation for Zuul Proxy Applications

### ISSUE THREAD

**Issue by tmack8001** [spring-cloud/spring-cloud-sleuth#586]
I'm seeing within the 1.2.0-RELEASE version that there are duplicate trace headers being added to my Zuul RequestContext requestHeaders Map. I have traced where this is happening and noticed that indeed Spans are being injected/customized into the outgoing requests to backends due to `TracePreZuulFilter` internally using the `spanInjector` to inject the span into the RequestContext (ala the requestHeaders Map contained within. Then when the request is being made which ever HttpClient one is using (okhttp, ribbon-httpclient, or apache) will also add additional tracing headers via the included SpanInjectingRibbonRequestCustomizer (example for ribbon-httpclient) or OkHttpClientRibbonRequestCustomizer (example for okhttp powered ribbon) or ApacheHttpClientRibbonRequestCustomizer (example for apache powered ribbon).

Here are some screenshots from my example debug session:

first place spans are being injected (ZipkinHttpSpanInjector via TracePreFilter)
![image](https://cloud.githubusercontent.com/assets/2158627/25775630/8be60ed8-325e-11e7-9b19-3a7b1bf5067f.png)

second place spans are being injected (first two scrubbed of sensitive data)
![image](https://cloud.githubusercontent.com/assets/2158627/25775645/dd001e6c-325e-11e7-9da8-88fb21846ca1.png)
![image](https://cloud.githubusercontent.com/assets/2158627/25775649/ea47fea0-325e-11e7-92e4-cfd82cbbb4bd.png)

this is from a test I added to echo back all the headers to test this case that 2 sets of B3 headers are being propagated to the underlying service (first is before SpanInjectingRibbonRequestCustomizer.inject method execution)
![image](https://cloud.githubusercontent.com/assets/2158627/25775663/3137b364-325f-11e7-99c8-9dff6b0c41f3.png)

showing the duplicated headers in the requestHeaders context carrier (after SpanInjectingRibbonRequestCustomizer.inject method execution)
![image](https://cloud.githubusercontent.com/assets/2158627/25775678/90803bb6-325f-11e7-84e6-b8af50c552e3.png)

Looking at the classes mentioned in the issue I have determined that this creeped in under my upgrade to use 1.2.0-RELEASE due to the newly added (in 1.2.x) of [ZipkinHttpSpanInjector.java](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/ZipkinHttpSpanInjector.java).

Couple of approaches to fix this:
1) check for presence of a trace header before adding a new one
2) replace the current value (if there is one) of any existing trace headers
3) mark the context as already containing a trace and check that a trace has been propagated before adding a trace to the header map
4) remove duplicate code that is injecting propagation trace headers

This is an issue for us because the receiving service throws an exception when attempting to propagate the span:
```
java.lang.NumberFormatException: 19206a2c3675d783,19206a2c3675d783 should be a 1 to 32 character lower-hex string with no prefix at 
com.github.kristofa.brave.IdConversion.isntLowerHexLong(IdConversion.java:68) at 
com.github.kristofa.brave.IdConversion.convertToLong(IdConversion.java:39) at 
com.github.kristofa.brave.http.HttpServerRequestAdapter.getSpanId(HttpServerRequestAdapter.java:61) at 
com.github.kristofa.brave.http.HttpServerRequestAdapter.getTraceData(HttpServerRequestAdapter.java:35) at 
com.github.kristofa.brave.ServerRequestInterceptor.handle(ServerRequestInterceptor.java:34) at 
```

**Comment by marcingrzejszczak** [comment]
Should be fixed with latest snapshots. If that's the case then as a workaround it's enough for you to register your own version of the injectors as presented in the https://github.com/spring-cloud/spring-cloud-sleuth/commit/419ec7232aea6863390819fa5acaeef352f6f883 commit  until new version of Sleuth gets released.

**Comment by tmack8001** [comment]
I failed at following up on this fix due to a number of things, but upon reattempting to upgrade (to 1.2.4.RELEASE to get this fix the same two places are adding these into the contextMap. The issue I see is that the linked commit changed the behavior of HeaderBasedMessagingInjector.java to only add headers if not already present and this is the first place executed in the code path for adding Span headers so that didn't change anything, a good thing to have regardless but doesn't solve this problem. This is because the second place the current Span is being added into headers is within the SpanInjectingRibbonRequestCustomizer.java which then doesn't check for presence before adding the header and thus creating the duplicated headers.

I think this code needs to add protections to find if the current span was already injected into the context headers.

```
@Override
public void inject(Span span, SpanTextMap carrier) {
	if (span == null) {
		carrier.put(Span.SAMPLED_NAME, Span.SPAN_NOT_SAMPLED);
		return;
	}
	carrier.put(Span.SAMPLED_NAME, span.isExportable() ?
			Span.SPAN_SAMPLED : Span.SPAN_NOT_SAMPLED);
	carrier.put(Span.TRACE_ID_NAME, span.traceIdString());
	carrier.put(Span.SPAN_ID_NAME, Span.idToHex(span.getSpanId()));
	carrier.put(Span.SPAN_NAME_NAME, span.getName());
	if (getParentId(span) != null) {
		carrier.put(Span.PARENT_ID_NAME, Span.idToHex(getParentId(span)));
	}
	carrier.put(Span.PROCESS_ID_NAME, span.getProcessId());
}
```

**Comment by tmack8001** [comment]
Guess from what the context of SpanInjectingRibbonRequestCustomizer is intended for would this !.contains(header) be responsible for all extensions of the abstract class SpanTextMap?

For our specific use this one would need to check for presence of the header before adding it to the request context.

```
class ApacheHttpClientRibbonRequestCustomizer extends SpanInjectingRibbonRequestCustomizer<RequestBuilder> {

      public void put(String key, String value) {
            context.addHeader(key, value);
      }
```
