### ISSUE TITLE
add javadoc for org.springframework.cloud.sleuth.SpanAccessor#isTracing

### ISSUE THREAD

**Issue by dddjoe** [spring-cloud/spring-cloud-sleuth#587]
It should not require to go through implementation classes and usages to find out what question does this method answer.

**Comment by marcingrzejszczak** [comment]
Care for a PR? :) you can start with a PR to 1.1.x branch

**Comment by dddjoe** [comment]
I can create on, but I'm not sure if I have the right answer.

**Comment by marcingrzejszczak** [comment]
When this method returns true then it means that a span is set in the context.

**Comment by dddjoe** [comment]
I get this part, but it would also be good to know what does it mean when a span is attached or not.
E.g. this method is called on Runnable wrappers that should have a span attached - it looks like this is just a safety guard, but I might be missing a point there.

**Comment by marcingrzejszczak** [comment]
If you execute this on a trace runnable wrapper then it will return true. That's because either we create a new Span if there was no previous one, or we continue a span that was initiated in the parent thread.
