### ISSUE TITLE
Custom AsyncConfigurer not getting processed by AsyncCustomAutoConfiguration's BeanPostProcessor

### ISSUE THREAD

**Issue by ssherwood** [spring-cloud/spring-cloud-sleuth#59]
I'm attempting to provide a custom AsyncConfigurer in my Boot application like this:

```java
@Bean
    public AsyncConfigurer asyncConfigurer() {
        return new AsyncConfigurer() {
            @Override public Executor getAsyncExecutor() {
                ThreadPoolTaskExecutor taskExecutor = new ThreadPoolTaskExecutor();
                taskExecutor.setCorePoolSize(5);
                taskExecutor.setMaxPoolSize(10);
                taskExecutor.setQueueCapacity(25);
                taskExecutor.setThreadNamePrefix("ThreadPoolTaskExecutor-");
                taskExecutor.initialize();
                return taskExecutor;
            }

            @Override public AsyncUncaughtExceptionHandler getAsyncUncaughtExceptionHandler() {
                return new SimpleAsyncUncaughtExceptionHandler();
            }
        };
    }
```

As I read the AsyncCustomAutoConfiguration class, this should be detected and wrapped by the LazyTraceAsyncCustomizer.  However, my bean is never post processed.  In the logs, I've noticed this:

```
2015-11-25 15:48:18.128 [trace=,span=]  INFO 68413 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'demoSleuthApplication' of type [class com.example.DemoSleuthApplication$$EnhancerBySpringCGLIB$$fa790465] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-11-25 15:48:18.149 [trace=,span=]  INFO 68413 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'asyncConfigurer' of type [class com.example.DemoSleuthApplication$1] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2
```

I've made various attempts to get this working including moving this Bean to its own Configuration class and nothing seems to work.  Am I making invalid assumptions about the AsyncCustomAutoConfiguration class or is there something specific that I'm missing in getting this custom Bean to take over?

**Comment by marcingrzejszczak** [comment]
Hello - do you have some demo app that we can work on?

**Comment by ssherwood** [comment]
https://github.com/ssherwood/demo-sleuth

I'm using Zipkin via this docker project:  https://github.com/openzipkin/docker-zipkin

You can see that I'm experimenting with Hystrix and Async to see how Sleuth will handle the trace/span context by hitting one of the 3 end points.  Let me know if this works for you.

**Comment by marcingrzejszczak** [comment]
you can check this project: https://github.com/spring-cloud-samples/brewery where we check the following combinations:

- Sleuth with Zipkin
- Sleuth Stream with Zipkin

In tracing approach we're checking the following integrations:

- WebAsyncTask returning Controller's methods
- Explicit TraceCommand calls
- AsyncRestTemplate with @LoadBalanced RestTemplate
- @Async annotated methods
- CompletableFuture.supplyAsync(...) with TraceableExecutorService
- Controllers with Callable returning methods
- Javanica (@HystrixCommand annotated methods)

**Comment by ssherwood** [comment]
Thanks, I'll take a look.

However, at first glance, I don't see where the sample is actually using @HystrixCommand nor do I see anything related to this specific issue when attempting to create a custom AsyncConfigurer (i.e. my original expectation that AsyncCustomAutoConfiguration should have been able to detect my custom ThreadPoolTaskExecutor and wrapped it).

**Comment by marcingrzejszczak** [comment]
Here is the example of @HystrixCommand - https://github.com/spring-cloud-samples/brewery/blob/master/brewing/src/main/java/io/spring/cloud/samples/brewery/bottling/BottlerService.java#L42.

The sample that I'm showing you is just BTW and is an answer to this:

> You can see that I'm experimenting with Hystrix and Async to see how Sleuth will handle the trace/span context by hitting one of the 3 end points. Let me know if this works for you.

I'll try to take a look at your sample ASAP and answer you issue.

**Comment by marcingrzejszczak** [comment]
hi!

I think I solved this... there are CGLIB beans created over the configuration classes:

```
2015-11-25 15:48:18.128 [trace=,span=]  INFO 68413 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'demoSleuthApplication' of type [class com.example.DemoSleuthApplication$$EnhancerBySpringCGLIB$$fa790465] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-11-25 15:48:18.149 [trace=,span=]  INFO 68413 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'asyncConfigurer' of type [class com.example.DemoSleuthApplication$1] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

The @EnableAsync by default uses JDK proxies and needs to autowire those `AsyncConfigurer` here https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/scheduling/annotation/AbstractAsyncConfiguration.java#L63 .  Actualy with the JDK approach this line `this.beanFactory.getBeanPostProcessorCount() < this.beanPostProcessorTargetCount` is true . When you explicitly state that you want to use the AspectJ proxy then the number of post processor changes and then the bean becomes eligible for proxying. 

That way you have proper ordering, first we're wrapping the `AsyncConfigurer` and after that the `AbstractAsyncConfiguration` has them injected.

You can check out this commit: https://github.com/marcingrzejszczak/demo-sleuth/commit/22ddbec0b8634ddfa8b350504caef472e6002015

If that's the typical situation for the async approach then we must define it in Javadocs / documentation cc @dsyer , @spencergibb .

@dsyer , @spencergibb  - the question is also applicable if `AbstractAsyncConfiguration` should just autowire stuff like that (https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/scheduling/annotation/AbstractAsyncConfiguration.java#L63) or should use `BeanFactory` so as not to change the ordering.

PS. It's a little bit similar to:
- https://gist.github.com/dsyer/ebeb25d5afbdd9242cd5
- http://stackoverflow.com/questions/1201726/tracking-down-cause-of-springs-not-eligible-for-auto-proxying/19688634#19688634

**Comment by dsyer** [comment]
Using `AdviceMode.ASPECTJ` is a bit off the beaten track and definitely shouldn't be necessary, hence I don't think the documentation needs changing yet. I'll have a play with that app once I update it to Brixton snapshots.

**Comment by dsyer** [comment]
I'm getting this in the revised version of the app with Brixton snapshots:

```
2016-01-29 16:53:31.081  WARN [demo-sleuth,9c9b0ac82190eb69,85701ecc74746c11,true] 26673 --- [nio-9090-exec-3] o.s.cloud.sleuth.util.ExceptionUtils     : Warn during joining trace: thread http-nio-9090-exec-3 tried to start a new Span with parent Span(begin=1454086411080, end=0, name=http/hi2, traceId=-7162118927729759383, parents=[-7162118927729759383], spanId=-483526207662941185, remote=true, exportable=true, tags={}, processId=null, logs=[], savedSpan=null), but there is already a currentSpan Span(begin=1454086411018, end=0, name=http/hi3, traceId=-7162118927729759383, parents=[-483526207662941185], spanId=-8831525005797594095, remote=false, exportable=true, tags={http/url=http://localhost:9090/hi3, http/host=localhost, http/path=/hi3, http/method=GET, callAsync-sleep-millis=10}, processId=null, logs=[], savedSpan=null)
```

So there's a probably somewhere with context clean up. But the hystrix and async stuff is working up to a point (i.e. I get a new span id for each thread).

**Comment by dsyer** [comment]
The original problem (`AsyncConfigurer` not working on a `@Bean`) might still be there, but I can't see it. I think we should close this issue and concentrate on #136 and #137).

**Comment by marcingrzejszczak** [comment]
So is this an issue or not? :P

**Comment by dsyer** [comment]
I can't see any issue with sleuth snapshots. Unless someone can give a crisp description of what exactly is wrong we should close this issue.

**Comment by marcingrzejszczak** [comment]
The only thing that is wrong is that only with the approach taken in my commit will tracing work with custom `AsyncConfigurer`. 

If we have the code presented by @ssherwood then this feature is not working

**Comment by ssherwood** [comment]
To add a little more clarity:

From the code that I submitted, the custom ThreadPoolTaskExecutor that is configured via the AsyncConfigurer does not properly get reported in Zipkin (see the third span).  It does not have the service name or the annotation attached to it that the code supplied.

I believe this is because the custom AsyncConfigurer is not processed so the trace/span/annotation are not properly associated to the thread that is used from the pool.

![zipkin](https://cloud.githubusercontent.com/assets/957282/12689210/50f753b2-c6a9-11e5-800b-a60abc55c6e5.png)

**Comment by marcingrzejszczak** [comment]
@ssherwood and have you tried that with the changes that I've suggested in my commit - https://github.com/marcingrzejszczak/demo-sleuth/commit/22ddbec0b8634ddfa8b350504caef472e6002015 ?

**Comment by ssherwood** [comment]
Yes, just tried it.  The warning in the logs goes away, but I don't see a different behavior in the zipkin view of the trace (no name and the annotation is missing).  I put a debug stop on line 51 in the AsyncCustomAutoConfiguration class and it did not stop there, so I'm guessing something else is getting in the way.  I will try experimenting with it more later.  I'll also try to use the Brixton snaphosts that Dave was using to see if I get a different result.

**Comment by dsyer** [comment]
The Zipkin UI is not a reliable witness, so we can't rely on it for evidence of a bug in anything except itself. The Zipkin query API reflects the span store quite well so more data from that might help, or (even better) just look at the trace and span ids in the logs from sleuth. Warnings are definitely a sign of a bug, but that's what I extracted into #136 and #137, so there's no sign of a problem here as far as I can tell.

BTW (nothing to do with this project): to report a problem with the Zipkin UI it is really helpful if there is a JSON view of the trace (and you can get that with `/api/v1/trace/{traceIdInHex}` (the trace id is in the url for the UI screenshot that you just posted).
