### ISSUE TITLE
Potential ClassNotFoundException in TraceHandlerInterceptor after Spring Boot 2.0

### ISSUE THREAD

**Issue by rockotseng** [spring-cloud/spring-cloud-sleuth#592]
Since Spring Boot 2.0 restructures `org.springframework.boot.autoconfigure.web`, there will be a class not found error about `ErrorController ` in `TraceHandlerInterceptor`.

Please see [gh-8616](https://github.com/spring-projects/spring-boot/issues/8616) for details.

**Comment by spencergibb** [comment]
No need to open issues against boot 2.0 yet, it's still early.
