### ISSUE TITLE
FeignBeanPostProcessorConfiguration is not eligible for getting processed by all BeanPostProcessors

### ISSUE THREAD

**Issue by arielsegura** [spring-cloud/spring-cloud-sleuth#594]
I can't get sleuth forwarding traceIds and I guess it's because of the following warning
`
Bean 'org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignClientAutoConfiguration$FeignBeanPostProcessorConfiguration' of type [class org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignClientAutoConfiguration$FeignBeanPostProcessorConfiguration$$EnhancerBySpringCGLIB$$8403515e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
`
Any ideas what could be going on?
Thanks in advance

**Comment by marcingrzejszczak** [comment]
I actually doubt that it's because of this. Can you elaborate more on the matter?  Which headers are not forwarded? When you're doing what exactly? It would be the best if you published your sample project somewhere cause without this it will be hard to help you.

**Comment by arielsegura** [comment]
I was referring to the headers like `X-B3-TraceId`. Basically, I was creating a FeignClient with a custom builder for RxJava: 
```java
 public class RxJavaFeign {
    public static Feign.Builder builder() {
        return new RxJavaFeign.Builder();
    }

    public static final class Builder extends Feign.Builder {


        private Contract contract = new Contract.Default();

        @Override
        public Builder contract(Contract contract) {
            this.contract = contract;
            return this;
        }

        @Override
        public Feign build() {
            super.invocationHandlerFactory(RxJavaInvocationHandler::new);
            super.contract(new RXJavaDelegatingContract(contract));
            return super.build();
        }
    }

 }
```

And using it like this
```java
static MyClient connect(String baseUrl, Integer connectTimeout, Integer readTimeout){
        return RxJavaFeign.builder()
                .options(new Request.Options(connectTimeout, readTimeout))
                .decoder(SuperSmartDecoderBuilder.newInstance().withJsonDecoder(new JacksonDecoder()).withInputStreamDecoder(new InputStreamDecoder()).build())
                .encoder(new JacksonEncoder())
                .logLevel(feign.Logger.Level.FULL)
                .logger(new Slf4jLogger(MyClient.class))
                .target(MyClient.class, baseUrl);
    }
```
Then, in my spring-boot application `A` (which has sleuth 1.1.4 in the classpath) I create a bean (because the client is in a separated module spring agnostic):
```java
@Bean
    public MyClient myClient() {
        return MyClient.connect(url, 500, 500);
    }
```
After the creation of that bean, I expected spring to apply that BPP, but it didn't. In fact, it was only applied to some other `FeignClient` that appeared elsewhere (may be a FeignClient created within spring-cloud). 
So I moved forward and after checking that application `A` contains `X-B3-TraceId` (I also see it in the logs), I expected sleuth to inject the headers in the request that go to application `B`. Of course that didn't happen because the BPP didn't wrapped my client in the `TraceFeignClient`. 

The workaround I found for this after posting this issue was basically creating a OkHttpClient bean
```java
@Bean
    public OkHttpClient okHttpClient() {
        return new OkHttpClient();
    }
```
and passing it to `MyClient`:
```java
static MyClient connect(String baseUrl, Integer connectTimeout, Integer readTimeout, Client client){
        return RxJavaFeign.builder()
                .client(client)
                .options(new Request.Options(connectTimeout, readTimeout))
                .decoder(SuperSmartDecoderBuilder.newInstance().withJsonDecoder(new JacksonDecoder()).withInputStreamDecoder(new InputStreamDecoder()).build())
                .encoder(new JacksonEncoder())
                .logLevel(feign.Logger.Level.FULL)
                .logger(new Slf4jLogger(MyClient.class))
                .target(MyClient.class, baseUrl);
    }
```
This is working right now because of `OkHttpFeignClientBeanPostProcessor`, but I still wonder why `MyClient`, without `OkHttpClient`, didn't apply for that BPP. May be it's related to my custom builder?
Thanks and sorry for the lack of details before.

**Comment by marcingrzejszczak** [comment]
Any object that you're creating in that builder needs to be wrapped in its trace representation. What you call a workaround is a good practice cause registering the `Client` as a bean makes it possible for the framework to wrap your `Client` in a trace representation. Since you were doing that via `new` then Sleuth couldn't do anything about it.
