### ISSUE TITLE
HttpTraceKeysInjector injecting wrong values

### ISSUE THREAD

**Issue by szetheli** [spring-cloud/spring-cloud-sleuth#597]
https://github.com/spring-cloud/spring-cloud-sleuth/blob/ae06079bdc621906e5b94e303f49d78e39ec62ba/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/HttpTraceKeysInjector.java#L74

The above is trying to put the http headers into tags on the current span, but instead of matching header name in the traceKeys.getHttp().getHeaders() to a header in the request, its writing multiple times so that only the last header's value gets stored into the tags for each configured key.

Expected: http header tags to match actual header value.
Actual: 
http.accept=http:/, http.user-agent=http:/, http.path=/, http.url=http://localhost:8080/, http.method=GET, http.host=localhost

**Comment by marcingrzejszczak** [comment]
Can you write an example of a request with expected tags? I can see you wrote some actual values but I don't know how the request looks like and what exactly should the tags look like. Also which version of sleuth are you using?

**Comment by szetheli** [comment]
[spring-sleuth-sample.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/1036591/spring-sleuth-sample.zip)
Attached is a sample project that makes a request and logs the tags.
1.2.1.RELEASE

**Comment by marcingrzejszczak** [comment]
Thanks. Could you please upload it as a github project?

Also could you please describe what is the expected outcome in your opinion?

**Comment by szetheli** [comment]
Here's the project sample
https://github.com/szetheli/spring-sleuth-http-tags

Here's a pull request of the fix and a test case demonstrating expected outcomes.
https://github.com/spring-cloud/spring-cloud-sleuth/pull/598

Working on the Contributor License Agreement

**Comment by szetheli** [comment]
Sorry for not being clear before.  I chose standard HTTP Headers "Accept" and "User-Agent" because I figured the "incorrect" values would be obvious.  

In the case of my sample the expected outcome would be:
**http.accept='text/plain','text/xml' http.user-agent=Test,** http.path=/, http.url=http://localhost:8080/, http.method=GET, http.host=localhost

The actual outcome (pre fix) is:
**http.accept=http:/, http.user-agent=http:/,** http.path=/, http.url=http://localhost:8080/, http.method=GET, http.host=localhost

This is because all the entries of traceKeys.http.headers end up being assigned the value of the last header, whatever that may be, after being assigned the value of each header (the inner for loop).  In this case the last header was 'X-Span-Name'

PR updated

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-sleuth/pull/598

Thanks a lot for your contribution!!
