### ISSUE TITLE
2 Feign.Builder Beans on the classpath if FeignClientConfiguration and TraceFeignClientAutoConfigruation are loaded.

### ISSUE THREAD

**Issue by FlorianLautenschlager** [spring-cloud/spring-cloud-sleuth#601]
If  the `FeignCliensConfiguration.java` and the `TraceFeignClientAutoConfiguration.java` configuration are loaded Spring Boot holds two Beans of the Feign.Builder. 

```
Parameter 1 of constructor in com.bad.demo.DemoApplication$FooController required a single bean, but 2 were found:
	- feignBuilder: defined by method 'feignBuilder' in org.springframework.cloud.netflix.feign.FeignClientsConfiguration
	- feignHystrixBuilder: defined by method 'feignHystrixBuilder' in class path resource [org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignClientAutoConfiguration.class]

```

Reproducer: https://github.com/FlorianLautenschlager/spring.sleuth

**Comment by marcingrzejszczak** [comment]
@FlorianLautenschlager why are you importing that configuration explicitly? You don't have to do that cause it comes with `FeignContext` - https://github.com/spring-cloud/spring-cloud-netflix/blob/758ff920fc71d9a2aaf41d1250d3cc5ddd46b870/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignContext.java#L31 . Is there a specific usecase that requires you to use that import?

**Comment by FlorianLautenschlager** [comment]
@marcingrzejszczak we have to build URLs at run-time and therefore we use the `Feign.Builder `with the beans defined in `FeignCliensConfiguration`. Our current solution is, that we provide the required beans from `FeignCliensConfiguration` except the Feign.Builder bean that is only created if sleuth is disabled. 

I think we can close the issue for now.

**Comment by marcingrzejszczak** [comment]
Thanks for the info!
