### ISSUE TITLE
Need to change the Kafka topic name

### ISSUE THREAD

**Issue by jprateekvmware** [spring-cloud/spring-cloud-sleuth#606]
Hi ,
Can i change the kafka topic name from "sleuth" .
I already have kafka binder used as part of spring cloud data flow and have topic name specified for output/input channel.
I am looking at having it explicity specified for trace data, which means I am having two output.

spring.application.name=sleuth-test-app
spring.cloud.stream.kafka.binder.zkNodes=broker
spring.cloud.stream.kafka.binder.brokers=broker
spring.cloud.stream.default.contentType=application/json
spring.cloud.stream.bindings.output.destination=topic.name

Thanks
Prateek

**Comment by marcingrzejszczak** [comment]
Just write `spring.cloud.stream.bindings.sleuth.destination=topic.name` and you'll change the topic name where the spans are sent for collection
