### ISSUE TITLE
monitor service is not enough

### ISSUE THREAD

**Issue by linking12** [spring-cloud/spring-cloud-sleuth#607]
I think monitor micro service is not enough
like:
A  service  call B service
B  service  call  distributed cache, and then query from database.

I think distributed cache、database must be monitored too, like sql execute time, cache expire time， all of some third middleware are monitored, the trace will be complete.

can sleuth provide common SDK to support this integration?

**Comment by adriancole** [comment]
I think this would be broken down into specific libraries. For example, sleuth could instrument JDBC or access through a cache api. Knowing which apis are used would focus efforts.

**Comment by linking12** [comment]
@adriancole  api is difficulty to judge，I think this decision is maked by user, sleuth provide SPI to support integrate every middleware. 
For example:
some one think spring rabbit is best api for rabbit, but some one like to use rabbitmq-java-client to operate rabbit.

and it is difficulty to judge

**Comment by adriancole** [comment]
@linking12 so this is getting to the main point. you are the user! What specific apis did you want and found missing? We don't have the resources or culture to implement every api that might possibly be used. Knowing which apis users want helps direct effort.

**Comment by linking12** [comment]
@adriancole my point is sleuth provide convenient api to support integration，user can quickly integrate with api by sleuth's spi.
now, sleuth is unsuitable for integrate, and heavy depend on spring, like rabbitmq-java-client, I donot want to depend on spring, and want to integrate in my project, not in sleuth.
because i want to upgrade sleuth follow community‘s version

**Comment by linking12** [comment]
@adriancole  
https://github.com/naver/pinpoint 
like pinpoint plugin, i want  the integration is simple and quickly.

**Comment by marcingrzejszczak** [comment]
So you can already wrap a call in a span with proper SA tag - http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_custom_sa_tag_in_zipkin . That way you'll monitor a call to an external service. I don't understand the problem ATM.
