### ISSUE TITLE
PercentageBasedSampler.java line-42 ,it seems that the condition is not right

### ISSUE THREAD

**Issue by karelpan** [spring-cloud/spring-cloud-sleuth#608]
It seems that in PercentageBasedSampler.java's line 42, which like this
`
...
} else if (this.configuration.getPercentage() == 100) {
...
`

but i see the getPercentage is  from  0.01f to 1.0f ,  is this can be right like this ?
`
} else if (this.configuration.getPercentage() == 1.0f) {
`

**Comment by marcingrzejszczak** [comment]
Yup - thanks!
