### ISSUE TITLE
Doubt for close() method of TraceScope class

### ISSUE THREAD

**Issue by gauravrmazra** [spring-cloud/spring-cloud-sleuth#61]
I was seeing close() method of TraceScope class. In this method, current thread's span is replaced with other span(savedSpan). See line number 108. Why is this done this way?

**Comment by dsyer** [comment]
Why do you think it's a problem?

**Comment by gauravrmazra** [comment]
In TraceCallable and TraceRunnable, first span is started and we get TraceScope reference and run the delegated Thread(Runnable or Callable) and when it is done. We call close() of that particular scope, which does as mentioned in above question. 
My concern is related to Executors. If one executor is shared to do some process and multiple requests are coming which is catered by some service using executors(It is just a use case). Then in worker threads of executors, the above code is creating problem and lead to Htrace error message when space is started. This is the reason I asking for this way. Isn't it if Worker thread is done its processing then it should clear its ThreadLocal context as well.

I will write some sample app with code which is able to reproduce this problem and with possible solution.

**Comment by dsyer** [comment]
I'm not sure I see the problem yet, but a sample project will certainly help. BTW I'm in the middle of a big refactor of all the core APIs so the names and locations of things might change soon.

**Comment by gauravrmazra** [comment]
I have created the sampleapp
https://github.com/gauravrmazra/spring-cloud-sleuth-executor-sampleapp

If multiple request are send from UI, it throws weird Htrace error (runtime exception)

The solution is simple. Just remove the current span from ThreadLocal context of the worker thread within TraceCallable and TraceRunnable
