### ISSUE TITLE
cannot find error msg in zipkin

### ISSUE THREAD

**Issue by zuochangan** [spring-cloud/spring-cloud-sleuth#615]
According the documents 

> Zipkin allows you to visualize errors in your trace. When an exception was thrown and wasn’t 

> caught then we’re setting proper tags on the span which Zipkin can properly colorize.

I didn't see this happen in my zipkin and I also wonder how does it works. Would you please show me the code

**Comment by marcingrzejszczak** [comment]
https://github.com/spring-cloud/spring-cloud-sleuth/blob/v1.2.1.RELEASE/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRestTemplateInterceptor.java#L64

**Comment by zuochangan** [comment]
@marcingrzejszczak   Thanks for your reply.

**Comment by marcingrzejszczak** [comment]
No problem!
