### ISSUE TITLE
Adding sa tag in current span should be a bug

### ISSUE THREAD

**Issue by zuochangan** [spring-cloud/spring-cloud-sleuth#619]
code in ZipkinSpanListener.java

> 	private void ensureServerAddr(Span span, zipkin.Span.Builder zipkinSpan, Endpoint localEndpoint) {
		if (span.tags().containsKey(Span.SPAN_PEER_SERVICE_TAG_NAME)) {
			zipkinSpan.addBinaryAnnotation(BinaryAnnotation.address(Constants.SERVER_ADDR,
					localEndpoint.toBuilder().serviceName(
							span.tags().get(Span.SPAN_PEER_SERVICE_TAG_NAME)).build()));
		}
	}

I think this function is wrong because the _localEndpoint_ just point to current server address. here only replace the serviceName should not be right!

And as the document said 

> IMPORTANT
Remember not to add both peer.service tag and the SA tag! You have to add only peer.service.

is this function just break the law?

**Comment by marcingrzejszczak** [comment]
I'm sorry but I don't really understand what you mean. Can you please write how in your opinion it should work?

**Comment by marcingrzejszczak** [comment]
Ping?

**Comment by zuochangan** [comment]
Sorry for late reply!

**Comment by zuochangan** [comment]
@marcingrzejszczak 

Sorry for late reply!
for example. 
we have two services, which are A and B. 
so if we send one request from A to B. should we just set peer.service with B and set SERVER_ADDR with address where B is deployed?

> if (span.tags().containsKey(Span.SPAN_PEER_SERVICE_TAG_NAME)) {
        zipkinSpan.addBinaryAnnotation(BinaryAnnotation.address(Constants.SERVER_ADDR,
          localEndpoint.toBuilder().serviceName(
        span.tags().get(Span.SPAN_PEER_SERVICE_TAG_NAME)).build()));
}

well, as the code show. we just set the SERVER_ADDR with localEndpoint which should be incorrect.

I hope I made myself clear. Sorry for late reply again!

**Comment by adriancole** [comment]
localEndpoint is incorrect for server_addr. If an ip/port info is added to server_addr, it should be of the remote side. It is valid to not send ip/port info if you have nothing except the service name.

**Comment by zuochangan** [comment]
@adriancole 
Should we changed the code as follow.  so the user can set server_addr info correctly!

```
private void ensureServerAddr(Span span, zipkin.Span.Builder zipkinSpan, Endpoint localEndpoint) {
		if (span.tags().containsKey(Span.SPAN_PEER_SERVICE_TAG_NAME)) {

			int peerAddress=localEndpoint.ipv4;
			if (span.tags().containsKey("peer.host")){

				peerAddress=  InetUtils.getIpAddressAsInt(span.tags().get("peer.host"));
			}

			int peerPort=localEndpoint.port;
			
			if (span.tags().containsKey("peer.port")){

				peerPort=Integer.parseInt(span.tags().get("peer.port"));
			}
			
			Endpoint peerEndPoint=Endpoint.create(span.tags().get(Span.SPAN_PEER_SERVICE_TAG_NAME),peerAddress,peerPort);
			
			zipkinSpan.addBinaryAnnotation(BinaryAnnotation.address(Constants.SERVER_ADDR, peerEndPoint));
		}
	}

```
