### ISSUE TITLE
TraceHandlerInterceptor should override span name set by TraceFilter

### ISSUE THREAD

**Issue by dhay** [spring-cloud/spring-cloud-sleuth#623]
I'm noticing that when I have a `TraceHandlerInterceptor` and a `TraceFilter` (normal setup for Spring Boot), that the span name is the original incoming URI, not the name provided by the `HandlerMethod` (i.e. the name of the method).  

I'm thinking there should be an option to allow the `TraceHandlerInterceptor` to override the span name.

Often URIs have unique IDs in them, espeically REST endpoints. (e.g. GET /user/12345), If we were to use the name provided by the `HandlerMethod` in the `TraceHandlerInterceptor`, the number of unique span names would be reduced (e.g. get-by-id)

**Comment by marcingrzejszczak** [comment]
We don't want to change the name of the span. It's strictly related to the URL. What you can do is to use the `SpanAdjuster` and modify the span name upon reporting to Zipkin - http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_customization_of_reported_spans

**Comment by marcingrzejszczak** [comment]
Ping?

**Comment by dhay** [comment]
I wasn't aware of the `SpanAdjuster`. That sounds like what I'm loo king for. 

Thanks!
