### ISSUE TITLE
spanTraceId is not propagated in messageHeaders 

### ISSUE THREAD

**Issue by srini78** [spring-cloud/spring-cloud-sleuth#631]
Hello

The spanTraceId and spanID are not retained when the message is flowing across multiple boot applications that are listening to kafka stream. I haven't used EnableAutoConfiguration, but I can see Sleuth working and creating the Ids during the runtime. Is there any flag or configuration I am missing?

**Comment by srini78** [comment]
I have a Global channel interceptor and I can see the Ids in ChannelInterceptor postSend - but as soon as the message comes to ChannelInterceptor preSend of other application, the messageHeaders - spanTraceId and spanId disappear. I checked Sleuth's TraceChannelInterceptor and dont see any code to remove these headers. What am I missing here? please let me know.

**Comment by marcingrzejszczak** [comment]
You have to use auto configuration to automatically register the channel interceptor. Spring cloud is built on top of spring boot. If you're disabling boots autoconfiguration mechanisms then almost nothing will work

**Comment by srini78** [comment]
Thank you, enabling autoconfiguration will affect other boot applications, can I manually include the Sleuth configuration?

**Comment by srini78** [comment]
Also, spring doc says  -  As long as Spring Cloud Sleuth is on the classpath any Spring Boot application will generate trace data. I see the trace data being generated without any configuration, its just not being propagated. I tried with "@Import({SleuthLogAutoConfiguration.class, SleuthAnnotationAutoConfiguration.class}) " - but headers are not propagated still.  My next step is try these - 
@EnableAsync,  @IntegrationComponentScan

**Comment by marcingrzejszczak** [comment]
Yes it's written like this cause it assumes that you have a boot app with boot context. 

As for the manual context setup you have to import all autoconfigurations and configurations manually. Please check the code to pick the proper ones. Definitely it's not the suggested way to go so I'll close the issue for now.
