### ISSUE TITLE
TraceAsyncRestTemplate missing Span.continue?

### ISSUE THREAD

**Issue by dhay** [spring-cloud/spring-cloud-sleuth#636]
I was looking at the TraceAsyncRestTemplate as an example of how to do something similar in some async code we were working on and I think there may be a bug in the way the parent Span is handled.

The code in question is the `doExecute` method, shown here:

```
	@Override
	protected <T> ListenableFuture<T> doExecute(URI url, HttpMethod method,
			AsyncRequestCallback requestCallback, ResponseExtractor<T> responseExtractor)
			throws RestClientException {
		final ListenableFuture<T> future = super.doExecute(url, method, requestCallback, responseExtractor);
		final Span span = this.tracer.getCurrentSpan();
		future.addCallback(new TraceListenableFutureCallback<>(this.tracer, span,
				this.errorParser));
		// potential race can happen here
		if (span != null && span.equals(this.tracer.getCurrentSpan())) {
			this.tracer.detach(span);
		}
```

After returning from the super.doExecute, the current span should be the new child span, containing the "client send" event.  The final "if" block makes sure to detach this child span from the current request thread to avoid having two threads stomping on the same span.  However, it doesn't restore the parent span.  Shouldn't the body of the final "if" block look something like this?

```
		if (span != null && span.equals(this.tracer.getCurrentSpan())) {
			Span parent = this.tracer.detach(span);
                        if (parent != null) this.tracer.continueSpan(parent);
		}
```

We're not currently using the AsyncRestTemplate, so it's not affecting us, but it might impact others.

Thanks!

**Comment by marcingrzejszczak** [comment]
Thanks a lot for the feedback. I agree that we should continue the parent span.
