### ISSUE TITLE
ServiceName still shown in logs when sleuth is disabled.?

### ISSUE THREAD

**Issue by bsridhar123** [spring-cloud/spring-cloud-sleuth#638]
When sleuth is enabled for the application, I am able to see the traces in the log.

Now, I want the option to enable/disable sleuth at startup (or anytime at runtime too)  after the required dependencies are added to pom.xml.

When I add ,
`spring.sleuth.enabled=false`
I see the the traces( traceId, spanId and export to zipkin(true/false) ) are disabled ( not shown in the logs ).

But, I see the service name still showed in the logs.

`2017-07-13 17:31:24.519  INFO [integration-service,,,] 440 --- [  XNIO-2 task-2] c.a.b.s.i.IntegrationServiceApplication  : sending request to demo-service
`
I am forced to  change the logging pattern level as below,
`logging.pattern.level='%5p'`

 Whenever I want sleuth to disable generating traces and also the service name to also be not shown in the logs.

I feel whenever sleuth is disabled the logging pattern should revert to whatever was earlier.

Is there a better way to handle this.

**Comment by marcingrzejszczak** [comment]
Yeah - that's because we're registering an environment post processor that acts before verifying any other properties. We would have to add the verification in the env post processor ourselves - which is a fair thing to do. So until then the answer is that there's no better way to do it. The other question is why do you need Sleuth on the classpath if you don't want to use it.

**Comment by bsridhar123** [comment]
@marcingrzejszczak  Thanks for your responding. But, I am not clear with environment post processor registering. 

On your question on why sleuth is on the classpath.

We want the option to toggle on/off generating traces at startup time, without having the need to rebuild the service.

Not sure if we can also do it at run-time, but  at least we should be able to toggle it at startup time .

This is because in some environments we do not want tracing and we want the flexibility to control tracing.

**Comment by marcingrzejszczak** [comment]
Yeah of course - that is understandable. I'll try to look into it. Currently the traces are not created for you, only the logging format is changed so that's not a blocker kind of a problem
