### ISSUE TITLE
Servlet 3.0 dependency issues on Servlet 2.5 container even when using spring-boot-legacy

### ISSUE THREAD

**Issue by kevinhooke** [spring-cloud/spring-cloud-sleuth#639]
After adding spring-cloud-sleuth to an existing Spring Boot service that is deployed to Weblogic 10.3.6 (Servlet api 2.5), we're getting this exception that looks like it's failing because of dependencies on Servlet 3.0 api:

```
Caused By: java.lang.NoClassDefFoundError: javax/servlet/DispatcherType
	at org.springframework.boot.web.servlet.AbstractFilterRegistrationBean.<clinit>(AbstractFilterRegistrationBean.java:52)
	at org.springframework.cloud.sleuth.instrument.web.TraceWebAutoConfiguration.traceWebFilter(TraceWebAutoConfiguration.java:89)
	at org.springframework.cloud.sleuth.instrument.web.TraceWebAutoConfiguration$$EnhancerBySpringCGLIB$$76dec89.CGLIB$traceWebFilter$3(<generated>)
	at org.springframework.cloud.sleuth.instrument.web.TraceWebAutoConfiguration$$EnhancerBySpringCGLIB$$76dec89$$FastClassBySpringCGLIB$$15f54e13.invoke(<generated>)
```

The app deploys and runs successfully to Weblogic 10.3.6 before adding spring-cloud-sleuth, since we've also added spring-boot-legacy (1.0.2.RELEASE. although same error with 1.1.0.RELEASE too).

Is it possible to use spring-cloud-sleuth with Servlet api 2.5?

**Comment by marcingrzejszczak** [comment]
The long answer is that maybe it would be possible to achieve that (by excluding the `TraceWebAutoConfiguration` and by trying to work this around with some manual work (I haven't tried it so I can't even confirm that it would be working fine).  So I guess the short answer will be that it's not possible to do so :/ @dsyer do you have some ideas about this?

**Comment by marcingrzejszczak** [comment]
I had a chat with @dsyer  and in theory maybe that could be possible but it would require a lot of work. You'd have to ignore our `TraceFilter` and write your own. If you manage to write sth like this and it will be working we can help you with a review or sth but I don't think we will put it in Sleuth core though.

**Comment by kevinhooke** [comment]
Thanks for the info. I doubt we'll be writing our own TraceFilter, but this gives us one more reason why we need to upgrade from Weblogic 10.3.6.
