### ISSUE TITLE
HTTPZipkinSpanReporter RestTemplate Ribbon or loadbalanced

### ISSUE THREAD

**Issue by jprateekvmware** [spring-cloud/spring-cloud-sleuth#640]
Hi currently we have got the zipkin service registered with Eureka and its not getting loadbalanced as  in ZipkinAutoConfiguration class its not loadbalanced.

Can we have RestTemplate customized for Ribbon based loadbalancer based on one of the sleuth properties
 
	@Bean
	@ConditionalOnMissingBean
	public ZipkinSpanReporter reporter(SpanMetricReporter spanMetricReporter, ZipkinProperties zipkin,
			ZipkinRestTemplateCustomizer zipkinRestTemplateCustomizer) {
		RestTemplate restTemplate = new RestTemplate();
		zipkinRestTemplateCustomizer.customize(restTemplate);
		return new HttpZipkinSpanReporter(restTemplate, zipkin.getBaseUrl(), zipkin.getFlushInterval(),
				spanMetricReporter);
	}

 
zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
    baseUrl: http://zipkin-service/

**Comment by marcingrzejszczak** [comment]
Done via the fabulous `WIP` commit - https://github.com/spring-cloud/spring-cloud-sleuth/commit/8c98386c1429bd2bd57a77ddd28db49996d9e77e ... I've forgotten to add `--squash` option to the merge command

**Comment by marcingrzejszczak** [comment]
Updated here - https://github.com/spring-cloud/spring-cloud-sleuth/issues/642

**Comment by marcingrzejszczak** [comment]
@jprateekvmware can you create a new issue for this?

**Comment by jprateekvmware** [comment]
Done
https://github.com/spring-cloud/spring-cloud-sleuth/issues/734

**Comment by consult-kk** [comment]
Hi,
Can you considering back-porting this to Spring cloud 1.2.5 .specifically Spring-cloud-slueth-zipkin-1.1.2-RELEASE.
Not everyone can afford to upgrade to newer Spring cloud versions all the time

**Comment by marcingrzejszczak** [comment]
Nope, we don't consider adding that feature to Dalston. Dalston is a very old release and we don't plan on adding any features to it.

**Comment by jprateekvmware** [comment]
@consult-kk  you should upgrade your version every 6 months.
