### ISSUE TITLE
SpanContextHolder::close looks suspicious

### ISSUE THREAD

**Issue by alesj** [spring-cloud/spring-cloud-sleuth#645]
https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/trace/SpanContextHolder.java#L73

Is this really OK?
As current span never gets the function applied,
since in line L77 you already change current to its parent.

**Comment by marcingrzejszczak** [comment]
Everything is ok since look at the `DefaultTracer` - we've already applied the `logStoppedSpan` on the current span there

**Comment by alesj** [comment]
OK.
Imo, it would be nicer if logStoppedSpan would be all handled via function and SpanContextHolder::close, but that's minor detail, so np.

**Comment by marcingrzejszczak** [comment]
Thanks for reading the code and your comments. That's really great to have someone double check your work :)
