### ISSUE TITLE
Locate zipkin via Eureka Service Registry.

### ISSUE THREAD

**Issue by jbaurchn** [spring-cloud/spring-cloud-sleuth#647]
I have registered Zipkin as a Eureka client in Eureka Service Registry.

I have also added the below config in all my service clients,
spring.zipkin.locator.discovery.enabled=true

But, I see a exception stack trace in all my service logs that connection failed when trying to connect to localhost:9411 for sending the spans.

Is there anything else we need to do to locate Zipkin via Eureka service registry.

**Comment by marcingrzejszczak** [comment]
Please read this part of the docs http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_sending_spans_to_zipkin and use the latest `1.3.0` snapshots from `Edgware` release train
