### ISSUE TITLE
wrong documentation link

### ISSUE THREAD

**Issue by jorgheymans** [spring-cloud/spring-cloud-sleuth#657]
https://cloud.spring.io/spring-cloud-sleuth/ has the wrong link for version 1.2.2 , it says 1.2.32

![image](https://user-images.githubusercontent.com/193792/28611516-52dd6a78-71ec-11e7-9c2e-6a8771d5b1c0.png)

**Comment by marcingrzejszczak** [comment]
Fixed! Thanks!
