### ISSUE TITLE
SleuthAdvisorConfig implements IntroductionAdvisor but doesn't really have any of its features

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#659]
`SleuthAdvisorConfig` isn't really an `IntroductionAdvisor` (all the relevant methods are empty). Probably better if it wasn't declared to implement that interface.

**Comment by marcingrzejszczak** [comment]
Done in https://github.com/spring-cloud/spring-cloud-sleuth/commit/b60620239c43549a13e8a9e55902d1ef1ef0e9ed
