### ISSUE TITLE
The SleuthBenchmarkingSpringApp doesn't wrap its ExecutorService

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#661]
The aspect creates a new `Span` but then it just returns `pjp.proceed()` (which would be a `Future` typically). It doesn't have a way to wrap the callable that was submitted to a thread pool to create the future. The thread pool should do that.

**Comment by marcingrzejszczak** [comment]
The thread pool is also instrumented (https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/LazyTraceThreadPoolTaskExecutor.java). We're just creating a new span to show that this is an asynchronous operation that will be done by a certain class / method.

**Comment by dsyer** [comment]
Right, I think I was confused because I'm looking at the benchmark app and it doesn't wrap its executor.

I also realized that the aspect is only there to *create* a new span for async processing. For some use cases (most?), users might not want that anyway. They can speed up app start up by disabling the aspect.

**Comment by marcingrzejszczak** [comment]
Come to think of it I wonder if this span should even be created or shouldn't it just continue the existing one if it's present and add the tags to it. But still, we would need the aspect.

**Comment by dsyer** [comment]
We wouldn't need the aspect if the parent span can just be continued, right?

**Comment by marcingrzejszczak** [comment]
Yeah but we want to add tags and create a span if there's no parent

**Comment by marcingrzejszczak** [comment]
So do we need to do sth about this @dsyer ?

**Comment by dsyer** [comment]
I think we should document it clearly at least (the switch to disable the aspect, and explain why it might be a sensible choice). Maybe change the default in 2.0?

**Comment by marcingrzejszczak** [comment]
Hmm but actually I don't think that it's a wrong thing that this aspect is applied. I only wonder if it should create a new span each time. It could continue an existing one and create one if it's missing. IMO it's very helpful that it's adding the tags related to the class and methods.

**Comment by marcingrzejszczak** [comment]
Fixed by https://github.com/spring-cloud/spring-cloud-sleuth/commit/a44bb543545187dbac7f35eeb8a6bff0f7d40c5a
