### ISSUE TITLE
Failure to find org.springframework.cloud:spring-cloud-sleuth-samples:pom:1.3.0.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by xinhaiye** [spring-cloud/spring-cloud-sleuth#663]
I have trouble to run mvn spring-boot:run in spring-cloud-sleuth-sample-zipkin directory.
Same spring-boot runs file in spring-cloud-sleuth-sample.

>spring-cloud-sleuth-sample-zipkin $ mvn package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building spring-cloud-sleuth-sample-zipkin 1.3.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.768 s
[INFO] Finished at: 2017-07-28T09:20:18-07:00
[INFO] Final Memory: 21M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project spring-cloud-sleuth-sample-zipkin: Could not resolve dependencies for project org.springframework.cloud:spring-cloud-sleuth-sample-zipkin:jar:1.3.0.BUILD-SNAPSHOT: Failed to collect dependencies at org.springframework.cloud:spring-cloud-sleuth-sample-test-core:jar:1.3.0.BUILD-SNAPSHOT: Failed to read artifact descriptor for org.springframework.cloud:spring-cloud-sleuth-sample-test-core:jar:1.3.0.BUILD-SNAPSHOT: Failure to find org.springframework.cloud:spring-cloud-sleuth-samples:pom:1.3.0.BUILD-SNAPSHOT in https://repo.spring.io/libs-snapshot-local was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by marcingrzejszczak** [comment]
Fixed by https://github.com/spring-cloud/spring-cloud-sleuth/commit/4d5156bca7e8abac4d386026a1126f5b1dd98675
