### ISSUE TITLE
TraceFilter skipPattern and extra span when X-B3-Flags header is present

### ISSUE THREAD

**Issue by dhay** [spring-cloud/spring-cloud-sleuth#665]
I've noticed two issues related to the handling of the `X-B3-Flags` header in the `TraceFilter` and it's interaction with the `ZipkinHttpSpanExtractor`.

`TraceFilter.createSpan` appears to have logic that creates a new span based on the `X-B3-Flags` header and also honors the skipPattern (skip parameter).
```
if (skip) {
	spanFromRequest = this.tracer.createSpan(name, NeverSampler.INSTANCE);
}
else {
	String header = request.getHeader(Span.SPAN_FLAGS);
	if (Span.SPAN_SAMPLED.equals(header)) {
		spanFromRequest = this.tracer.createSpan(name, new AlwaysSampler());
	} else {
		spanFromRequest = this.tracer.createSpan(name);
	}
}
```

However, this logic is only invoked if there isn't a parent span created by the SpanExtractor.  The `ZipkinHttpSpanExtractor.joinTrace` method creates a parent span based on the presence of the `X-B3-Flags`.  So the logic in `TraceFilter` is never invoked.

```
boolean debug = Span.SPAN_SAMPLED.equals(carrier.get(Span.SPAN_FLAGS));
if (debug) {
	// we're only generating Trace ID since if there's no Span ID will assume
	// that it's equal to Trace ID
	generateIdIfMissing(carrier, Span.TRACE_ID_NAME);
```

The way the `ZipkinHttpSpanExtractor` is currently implemented, the X-B3-Flags header results in the creation of an extra span and the "skipPattern" setting is completely ignored.  This makes it hard, for example, to use a browser plugin to always set the X-B3-Flags header and only trace the main requests.  It also makes the traces a bit more difficult to read, since they're not exactly the same as if, say, sampling was set to 100%.

Is this behavior expected? If not, I would like to see the removal of the X-B3-Flags header logic from the SpanExtractor so that the Filter can handle it as written.

**Comment by adriancole** [comment]
The fundamental issue here is that a trace sampling decision in the (B3)
trace context is trace scoped (all operations) not span scoped (one
operation).

What you'd like to do is trim a trace vs an all or nothing decision. For
example a trace from service A -> B will include spans except the ones you
want to exclude, like favicon. The issue here is the client on service A
may have already created a span for the undesirable resource. Is that the
case with your code? Ex even if this were skipped here, wouldnt you have a
client span for the resource?

Or are you just controlling trace ID? For example you are not reporting
anything to zipkin before hitting this service. In that case, leaving out
the sampling header is the standard way to accomplish this. Ex in absence
of a X-B3-Sampled header, a top level decision is made here (which can
include skipping the trace).


Hope these notes help.

**Comment by dhay** [comment]
In my particular situation, I'm making requests to our web application (edge node) from my browser using a plugin that sets the following HTTP header on all requests:

X-B3-Flags: 1

When I go to look at the trace in the Zipkin collector, I see two spans:

```
http:/parent/path/to/something.js
+-- http://path/to/something.js
```
I've set the `spring.sleuth.web.skipPattern` to include ".*\.js" and I've verified that my pattern is matching the URI.  The presence of the `X-B3-Flags: 1` header forces the `ZipkinHttpSpanExtractor` to create an artificial parent span that I feel is unnecessary in this scenario.  It also ignores the skip pattern and reduces the usefulness of having a browser plugin for myself or our QA staff.

I can see how things get a bit murkier in the downstream services.  But my perspective is that if A calls B and B says that certain URLs are not interesting, then we should abide by that decision, regardless of the X-B3-Sampled or X-B3-Flags header.

**Comment by adriancole** [comment]
Thanks for the scenario. Yeah it isn't usual for a client to propagate
sampled 1 on a resource it doesn't care about, but I can see how the
browser wildcard makes sense.

> I can see how things get a bit murkier in the downstream services. But my
> perspective is that if A calls B and B says that certain URLs are not
> interesting, then we should abide by that decision, regardless of the
> X-B3-Sampled or X-B3-Flags header.
>
This is fair, but it is changing the nature of that parameter. Basically
you are talking about instrumentation policy, not sampling policy. For
example, probably this needs to be a filter which disables all trace
functionality on a particular expression (instrumentation) vs trying to
decide if a trace should be created or not (sampling).

So, I think you are asking to bump this up a notch as far as scope. This
might be possible already (via normal filtering expressions)

**Comment by adriancole** [comment]
another way of discussing the same thing, is probably you also don't
care about metrics on /favicon :) The scope is you don't care at all
about tracking a resource, but notably not adding it to a span.

**Comment by dhay** [comment]
Putting aside the skip pattern discussion. It seems weird to me that simply adding `X-B3-Flags: 1` to my HTTP request results in a `http://parent/something` span in addition to the main `http://something` span.

My understanding is that `X-B3-Flags: 1` means "always sample this request, regardless of what the Sampler would normally say". So I would advocate for removing the debug logic from the ZipkinHttpSpanExtractor and let the Filter handle that logic.

**Comment by adriancole** [comment]
Flags 1 (debug) implies sampled. Sending only this header is valid practice
and means start a new trace and make sure it is kept.

**Comment by dhay** [comment]
Are you saying that the artificial parent span is expected/desired behavior?

**Comment by marcingrzejszczak** [comment]
Yes, it is. It's not done by accident ;) The debug flag just implies that no sampling decision will be made / calculated. It will be assumed to be sampled.

**Comment by dhay** [comment]
Hmmm...I get the bit about the debug flag implying that sampling will be assumed.  I guess I'm missing the rationale for creating the "http://parent/whatever" span.

**Comment by marcingrzejszczak** [comment]
So the rationale is that when you have a request that was/must be traced (you've passed the Trace and Span ids in the headers OR you've set the debug flag)  BUT it didn't have the parent span header passed then we need to fix this abnormal situation. We're creating an additional span that simulates the parent span. Does it make sense now?

**Comment by dhay** [comment]
That helps, but I see these as two, unrelated, scenarios.
- When the Trace and Span Ids are passed, but no parent span header, I can see the rationale for creating the parent span. It's an indication of a malformed request and there's a need to try and recover.
- When the the debug flag is passed, we are saying that the Sampler should be ignored and the request traced. That is, the span we create for the request is the root span of the trace...it has no parent. Creating an artificial parent span doesn't make sense.

**Comment by marcingrzejszczak** [comment]
The second scenario is related to the first one. If you put the debug flag we just generate an id if that was missing. Or do you see that it's not acting like this?

**Comment by dhay** [comment]
I guess I don't see how the second scenario is related to the first.  

What I'm seeing is that if I make a request with the debug flag set (and no other Zipkin headers) that initial request generates 2 spans: a strange parent span and then the span I'd expect.

I've worked around it for now by creating a custom HttpSpanExtractor that mimics the ZipkinHttpSpanExtractor, but removes all handling of the X-B3-Flags header. This results in the HttpSpanExtractor returning `null`, which triggers the TraceFilter to fall into the "parent == null" else condition in `createSpan` and create the span I would expect for the initial request of a trace.

**Comment by marcingrzejszczak** [comment]
I guess I can't explain it any better. I'm glad though that you have your workaround. I'll close this issue then.

**Comment by dhay** [comment]
Um...I still consider this an issue if I have to work around it.  Not sure why it's being closed.

**Comment by marcingrzejszczak** [comment]
It's closed cause I don't think that this is an issue and I tried to explain it but you don't accept my explanation.

**Comment by dhay** [comment]
I've been reading and re-reading through the explanations on this thread but I still feel like I'm missing something.  

- If I make a call to an HTTP endpoint with sampling set to 100% (no special headers), I get one span reported.  
- If I make a call to the same HTTP endpoint with sampling set to 0%, but the X-B3-Flags header present, I get 2 spans reported. 

I'm having a hard time understanding how these two scenarios are different.

**Comment by marcingrzejszczak** [comment]
I'll reopen this issue. 

I have already a couple of unit tests that test this situation https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java#L385-L449 and either I don't understand your problem or there is no problem or the tests are wrong.

 Can you please provide a sample that depicts your case? A unit test would be the best option.

**Comment by dhay** [comment]
Here's a unit test that shows the issue.  There seems to be an interaction between the TraceFilter and the TraceHandlerInterceptor that causes the problem I've been attempting to describe.  I also think that the TraceFilterTests.beanFactory() should be using the `spanReporter` field instead of a NoOpSpanReporter.

```
	@Test
	public void samplesASpanDebugFlagWithInterceptor() throws Exception {
		this.request = builder()
				.header(Span.SPAN_FLAGS, 1)
				.buildRequest(new MockServletContext());
		this.sampler = new NeverSampler();
		BDDMockito.given(beanFactory.getBean(Tracer.class)).willReturn(this.tracer);
		BDDMockito.given(beanFactory.getBean(TraceKeys.class)).willReturn(this.traceKeys);
		BDDMockito.given(beanFactory.getBean(HttpSpanExtractor.class)).willReturn(this.spanExtractor);
		BDDMockito.given(beanFactory.getBean(SpanReporter.class)).willReturn(this.spanReporter);
		BDDMockito.given(beanFactory.getBean(HttpTraceKeysInjector.class)).willReturn(this.httpTraceKeysInjector);
		BDDMockito.given(beanFactory.getBean(ErrorParser.class)).willReturn(new ExceptionMessageErrorParser());
		TraceFilter filter = new TraceFilter(beanFactory);

		filter.doFilter(this.request, this.response, (req, res) -> {
			// Simulate the TraceHandlerInterceptor
			req.setAttribute(TraceRequestAttributes.HANDLED_SPAN_REQUEST_ATTR, span);
			this.filterChain.doFilter(req, res);
		});

		then(new ListOfSpans(this.spanReporter.getSpans()))
				.doesNotHaveASpanWithName("http:/parent/")
				.hasASpanWithName("http:/")
				.hasSize(1)
				.allSpansAreExportable();
		then(TestSpanContextHolder.getCurrentSpan()).isNull();
		then(ExceptionUtils.getLastException()).isNull();
	}
```

**Comment by marcingrzejszczak** [comment]
@dhay thanks for filing the test. Only after reading it did I get what you mean. I guess I should have asked you for the test earlier and we wouldn't have this long conversation. Anyways I guess now everything should be fine. Again, thanks for the feedback and writing the test!!

**Comment by dhay** [comment]
Thanks!  Sorry for all the confusion.  Lesson learned on my end...I should have submitted the test in the first place.  There's nothing like code to disambiguate a situation, eh?

**Comment by marcingrzejszczak** [comment]
Exactly - nothing better than a failing test to show that something is not working :)
