### ISSUE TITLE
Trace Ids as String

### ISSUE THREAD

**Issue by ahmednasir91** [spring-cloud/spring-cloud-sleuth#674]
We would like to use Amazon ALB trace Ids, but at the moment we can only provide the implementation of `Random` bean to modify the trace id, also the Ids are of type `long`. 
```
    private long createId() {
        return this.random.nextLong();
    }
```

Is there a workaround to use Amazon Trace Ids, following are some sample trace ids
`X-Amzn-Trace-Id: Root=1-67891233-abcdef012345678912345678`

http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html

One of the advantage of using ALB Trace ID - that its available in the access logs.

**Comment by marcingrzejszczak** [comment]
I had a chat with @adriancole and this is what we came up with.

The traceid in a string format is not sth that we took into consideration but there is a workaround that we can think of. 

However, the Amazon Trace ID consists of 2 parts. Some version-timestamp and a number. You can create a custom extractor (http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_http) that will take out a trace id in the Amazon form from a certain header, then split it into two pieces. Then one piece will become the traceid and the other will become a baggage entry that will get propagated. Of course, you'll need to also create your custom injector too as presented in the documentation if you want to inject entries from the span to the headers in a required way.

If you need to generate an id you will do the same - you will generate the trace if via `random` and you can attach a baggage item yourself. 

As for the logs you can override the `Slf4jSpanLogger` to combine the entries from the baggage and the traceid to the format understandable by any log harvester or any other Amazon tooling. Just convert it and put it into MDC context in any way you need. If you want to change the logging format remember that you need to also change the logging pattern in the properties.

@adriancole do you have anything to add to it?

**Comment by adriancole** [comment]
@marcingrzejszczak in theory this is what I would do. There might be some snags and feel free to reply back if you run into one.

**Comment by ahmednasir91** [comment]
@marcingrzejszczak @adriancole Thanks - i'll try this out and will surely ask here if I hit some wall.

**Comment by ahmednasir91** [comment]
I'm able to add trace ids to logs
https://github.com/ahmednasir91/spring-slueth-amazon-alb-trace/commit/a00ea1033a7cf37985844999b862f010387d088e

@marcingrzejszczak @adriancole Thanks for the help. Let me know if you guys have some feedback

**Comment by ahmednasir91** [comment]
This worked for us, Thanks for the help.
