### ISSUE TITLE
SleuthHystrixConcurrencyStrategy startup order problem

### ISSUE THREAD

**Issue by dhay** [spring-cloud/spring-cloud-sleuth#678]
We are seeing an issue with the startup order of the `SleuthHystrixConcurrencyStrategy` and the use of Hystrix libraries...specifically with the `HystrixCodaHaleMetricsPublisherThreadPool`.

The scenario is that, during application context initialization, one of our Spring beans makes a call through a Hystrix command, which initializes all the plugins and the metrics publisher specifically. (i.e. `HystrixCodaHaleMetricsPublisherThreadPool.initialize()` is invoked).  This operations happens to occur before the `SleuthHystrixConcurrencyStrategy` is created.  Once the Sleuth class is instantiated, it calls `HystrixPlugins.reset()`, which wipes out the internal static cache in `HystrixMetricsPublisherFactory`.  The next time our original Hystrix command is run, we get the error below. The problem is that the `HystrixPlugins.reset()` method doesn't un-register the metrics added to the `MetricRegistry`, so the second initialization of Hystrix causes the error.

```
ERROR [http-nio-11088-exec-1] --- MyClass: A metric named MyCommandName.isCircuitBreakerOpen already exists
        java.lang.IllegalArgumentException: A metric named MyCommandName.isCircuitBreakerOpen already exists
            at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91) ~[metrics-core-3.1.4.jar:3.1.4]
            at com.netflix.hystrix.contrib.codahalemetricspublisher.HystrixCodaHaleMetricsPublisherCommand.initialize(HystrixCodaHaleMetricsPublisherCommand.java:54) ~[hystrix-codahale-metrics-publisher-1.4.10.jar:1.4.10]
            at com.netflix.hystrix.strategy.metrics.HystrixMetricsPublisherFactory.getPublisherForCommand(HystrixMetricsPublisherFactory.java:115) ~[hystrix-core-1.4.21.jar:1.4.21]
            at com.netflix.hystrix.strategy.metrics.HystrixMetricsPublisherFactory.createOrRetrievePublisherForCommand(HystrixMetricsPublisherFactory.java:83) ~[hystrix-core-1.4.21.jar:1.4.21]
            at com.netflix.hystrix.AbstractCommand.<init>(AbstractCommand.java:228) ~[hystrix-core-1.4.21.jar:1.4.21]
            at com.netflix.hystrix.HystrixCommand.<init>(HystrixCommand.java:142) ~[hystrix-core-1.4.21.jar:1.4.21]
            at com.netflix.hystrix.HystrixCommand.<init>(HystrixCommand.java:128) ~[hystrix-core-1.4.21.jar:1.4.21]
...
```

I realize this isn't necessarily a Spring Sleuth problem per-se, but I'm wondering if there's a way to work around the issue in some way, perhaps forcing the startup ordering in some way?

**Comment by marcingrzejszczak** [comment]
That's an interesting problem... Is `HystrixCodaHaleMetricsPublisherThreadPool` set up by some Spring Boot Autoconfiguration? I'm asking cause theoretically what you could do is to create an additional autoconfigration and set sth like this:

```java
@Configuration
@AutoConfigureBefore(AutoConfigurationWhere HystrixCodaHaleMetricsPublisherThreadPoolIsSet.class)
@AutoConfigureAfter(SleuthHystrixAutoConfiguration.class)
public class YourCustomAutoConfig {

}
```

and add to `spring.factories`

```properties
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
com.example.YourCustomAutoConfig
```

That way you might force the order. If that works fine then we can try to merge it back to Sleuth somehow. WDYT?

**Comment by dhay** [comment]
Setting up autoconfiguration like that would certainly be one way to work around the problem.  I've been suggesting to our team that adding a Spring application lifecycle listener which execute after the context has been initialized is another way.

I'm not really sure there are any good solutions here, with the way Hystrix is written.  Hopefully Hystrix 2.0 will be better in this regard.

**Comment by marcingrzejszczak** [comment]
So maybe until then let's close this issue and once you prove that there's a workaround for this we'll paste it here?

**Comment by dhay** [comment]
Sounds reasonable...mainly wanted to point it out in case you had some trick up your sleeve to work around the issue on the Spring Sleuth side of things

**Comment by marcingrzejszczak** [comment]
No tricks this time ;) If you want to see tricks you can check this out https://github.com/spring-cloud/spring-cloud-sleuth/issues/680 . Maybe you have a better idea how to solve it :)

**Comment by icehockeystar** [comment]
I faced the same issue with the `SleuthHystrixConcurrencyStrategy` and `new HystrixCodaHaleMetricsPublisher(this.metricRegistry)`. In my project I use just Feign w/ hystrix support. Is there some way to disable creation of `SleuthHystrixConcurrencyStrategy` ?

**Comment by marcingrzejszczak** [comment]
Have you read the documentation?  http://cloud.spring.io/spring-cloud-static/Dalston.SR4/multi/multi__integrations.html#_custom_concurrency_strategy

**Comment by icehockeystar** [comment]
Nope, but thanks. I don't know what exactly I'll miss with the turning off but it would be at least a workaround for the problem.
