### ISSUE TITLE
zuul's traceid not pass to oauth-server

### ISSUE THREAD

**Issue by junneyang** [spring-cloud/spring-cloud-sleuth#681]
1. zuul-server
security.oauth2.resource.userInfoUri = http://${AUTH_SERVER_HOST}:${AUTH_SERVER_PORT}/uaa/user

```
@SpringBootApplication
@EnableZuulProxy
@EnableDiscoveryClient
@EnableResourceServer
public class Application {

	private static final Logger LOGGER = LoggerFactory.getLogger(Application.class);
	
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		//SpringApplication.run(Application.class, args);
		new SpringApplicationBuilder(Application.class).web(true).run(args);
	}
```

2. picture
![xxx](https://user-images.githubusercontent.com/6802322/29453747-4f3b53ae-843d-11e7-8aa8-93fe660f88f5.png)

zuul---->auth-server is missing, why?
thanks very much for your help !

**Comment by marcingrzejszczak** [comment]
Is AuthServer using Sleuth too ?

**Comment by junneyang** [comment]
@marcingrzejszczak 
yes

pom.xml
`<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-sleuth-zipkin-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-stream-rabbit</artifactId>
		</dependency>

`

conf:
`spring.rabbitmq.host = ${RABBITMQ_SERVER_HOST}
spring.rabbitmq.port = ${RABBITMQ_PORT}
spring.rabbitmq.username = ${RABBITMQ_USER}
spring.rabbitmq.password = ${RABBITMQ_PASSWORD}`


and the data in mysql:
![yyy](https://user-images.githubusercontent.com/6802322/29453923-f07396f0-843d-11e7-8551-3249f07e8a8a.png)


but the traceid is new , not pass from zuul

**Comment by marcingrzejszczak** [comment]
You have the wrong dependency...

Change `spring-cloud-sleuth-zipkin-stream` to `spring-cloud-sleuth-stream`. I understand that you are sending spans via messaging? The first one is the Zipkin collector and you want to send spans to Zipkin. If you send spans via HTTP change `spring-cloud-sleuth-zipkin-stream` to `spring-cloud-starter-zipkin`.

**Comment by junneyang** [comment]
@marcingrzejszczak 
you mean the zipkin-server use: spring-cloud-sleuth-zipkin-stream
but the client use: spring-cloud-sleuth-stream ?

**Comment by marcingrzejszczak** [comment]
Yes, as described in the documentation. 

http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_sleuth_with_zipkin_via_spring_cloud_stream - client
http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_spring_cloud_sleuth_stream_zipkin_collector - server

**Comment by junneyang** [comment]
thanks, i have try the above solution, but it not works yet, seems not this reason.
because:

zuul-server log:   traceId: 11c0211bcd23189c
![zuul](https://user-images.githubusercontent.com/6802322/29463125-30ce890a-8464-11e7-845f-67b7e0d9b960.png)


then, the auth-server log:
![auth](https://user-images.githubusercontent.com/6802322/29463087-037282cc-8464-11e7-958b-9106df72d54f.png)


doesn't search the traceId
the auth-server create new traceId ,not pass from the zuul-server

and the auth-server could send message to zipkin-server normal:
![zipkin](https://user-images.githubusercontent.com/6802322/29463173-5bd95404-8464-11e7-98e7-45419423973d.png)

**Comment by marcingrzejszczak** [comment]
Could you please start pasting the logs instead of screenshots? Could you also upload your sample applications somewhere? It will be difficult for me to analyze the problem without the real apps

**Comment by junneyang** [comment]
@marcingrzejszczak 
code: https://github.com/junneyang/xxproject

auth-server zuul-server and zipkin-server all in:
xxproject/support/  fold

thnaks

**Comment by marcingrzejszczak** [comment]
Ok, one more question. Could you please run the sample again but turn on the Sleuth's logs to DEBUG in Auth server. Then please upload it here as a file. I'd like to see if the headers are there.

Also can you please try it out with the latest Dalston snapshots? I have a hunch that it's related to OAuth2 template that we have only fixed in the latest snapshots.

**Comment by junneyang** [comment]
ok, thanks, i will feedback tomorrow,time to sleep,^_^

**Comment by junneyang** [comment]
a low-level question, how to find the latest  Dalston  snapshots? thanks

**Comment by marcingrzejszczak** [comment]
Just pick the Dalston.BUILD-SNAPSHOT version here  http://projects.spring.io/spring-cloud/ and copy it to your project

**Comment by junneyang** [comment]
[app.log.txt](https://github.com/spring-cloud/spring-cloud-sleuth/files/1236129/app.log.txt)

@marcingrzejszczak 
the auth-server log

**Comment by junneyang** [comment]
you mean the Finchley M1?

![vv2](https://user-images.githubusercontent.com/6802322/29484351-468d7842-84ef-11e7-8900-ba377d3cac58.png)

**Comment by marcingrzejszczak** [comment]
No, I mean a snapshot version. Any snapshot version.

**Comment by junneyang** [comment]
still not work
the snapshot auth-server log:
[snapshot-app.log.txt](https://github.com/spring-cloud/spring-cloud-sleuth/files/1236147/snapshot-app.log.txt)

**Comment by marcingrzejszczak** [comment]
Did you put snapshot versions in all applications? Can you post the logs or the client app too?

**Comment by junneyang** [comment]
1. Code: https://github.com/junneyang/xxproject
2. auth-server zuul-server product-api-service's sleuth log level: DEBUG
3. Test Step:

- source bootstrap.rc
- docker-compose up -d
- access http://localhost:9999/uaa/oauth/authorize?response_type=code&client_id=acme&redirect_uri=http://example.com&scope=webshop&state=97536 to get the code, ret: http://example.com/?code=W72AJ4&state=97536 
- CODE=W72AJ4
- access curl acme:acmesecret@localhost:9999/uaa/oauth/token -d grant_type=authorization_code -d client_id=acme -d redirect_uri=http://example.com -d code=$CODE -s | jq . to get token
- TOKEN=323535b0-3e85-4119-b408-0fdd69e79e51
- access curl 'http://localhost:5555/api/product-api-service/product-api-composite' -H  "Authorization: Bearer $TOKEN" -s | jq . 
- result ok:
![aaa](https://user-images.githubusercontent.com/6802322/29486148-05a11f14-8512-11e7-82ee-dabcc660ca85.png)

4. all logs:
[log.tar.gz](https://github.com/spring-cloud/spring-cloud-sleuth/files/1236291/log.tar.gz)


thanks for your help

**Comment by marcingrzejszczak** [comment]
I'm trying to go through this sample but it's so gigantic that it's difficult to work with. Is there an option to prepare just 2 applications. Zuul and Authentication server and a simple script how to run these things together? I'd like to debug how Zuul is sending a request to the Authentication server. Cause it seems that it's not passing the tracing information for some reason. Thanks!

**Comment by junneyang** [comment]
@marcingrzejszczak 

mvn package

1. source bootstrap.rc && java -jar support/config-server/target/config-server-1.0.0-RELEASE.jar
2. source bootstrap.rc && java -jar support/auth-server/target/auth-server-1.0.0-RELEASE.jar
3. source bootstrap.rc && SPRING_CLOUD_CONFIG_PROFILE=${EUREKA_SERVER01} java -jar support/eureka-server/target/eureka-server-1.0.0-RELEASE.jar
4. source bootstrap.rc && SPRING_CLOUD_CONFIG_PROFILE=${EUREKA_SERVER02} java -jar support/eureka-server/target/eureka-server-1.0.0-RELEASE.jar
5. source bootstrap.rc && java -jar support/zuul-server/target/zuul-server-1.0.0-RELEASE.jar

**Comment by junneyang** [comment]
@marcingrzejszczak 
when i refer this issue: https://github.com/spring-cloud/spring-cloud-sleuth/issues/581

add this 
`
@Bean
    public UserInfoRestTemplateCustomizer userInfoRestTemplateCustomizer(
            TraceRestTemplateInterceptor traceRestTemplateInterceptor) {
        return restTemplate -> {
            List<ClientHttpRequestInterceptor> interceptors = new ArrayList<>(
                    restTemplate.getInterceptors());
            interceptors.add(traceRestTemplateInterceptor);
            restTemplate.setInterceptors(interceptors);
        };
    }
`

to zuul, product-api-service it works!

![aaa](https://user-images.githubusercontent.com/6802322/29607236-32094f2c-8823-11e7-8471-6e5ef701aa6a.png)

**Comment by marcingrzejszczak** [comment]
Yeah so the thing is that it should work out of the box... :| Can you ensure that you're using latest snapshots, and check if this line https://github.com/spring-cloud/spring-cloud-sleuth/blob/253b34b1cf5627c61e8e4cb8e75fcc00d22e5664/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientAutoConfiguration.java#L117 is executed?

**Comment by marcingrzejszczak** [comment]
Ha! Actually I know why it's not working. I've created a Bean Post Processor and I'm wrapping a UserInfoRestTemplateCustomizer with a trace representation. But what if there's not a single one defined? Then nothing happens. That's why if there's no `UserInfoRestTemplateCustomizer` defined then one should be applied. I'll add a fix in a second

**Comment by marcingrzejszczak** [comment]
Ok it's fixed. Can you check against latest snapshots? And ensure that you don't have the manual `UserInfoRestTemplateCustomizer` set

**Comment by marcingrzejszczak** [comment]
I'm sorry, I tried to run the sample locally but I didn't manage to do it. With the latest changes things should work fine so I'll close the issue and if you find out that there are still some problems just feel free to reopen it.

fixed by https://github.com/spring-cloud/spring-cloud-sleuth/commit/6d25738ec41aab2d2ebe3c152be7271a3dc57649
