### ISSUE TITLE
spring-cloud-sleuth-dependencies:1.2.3.RELEASE refers to SNAPSHOT parent

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-sleuth#683]
POM of `spring-cloud-sleuth-dependencies:1.2.3.RELEASE` contains the following (unexpected) parent declaration:

```
<parent>
  <artifactId>spring-cloud-dependencies-parent</artifactId>
  <groupId>org.springframework.cloud</groupId>
  <version>1.3.3.BUILD-SNAPSHOT</version>
  <relativePath/>
</parent>
```

**Comment by marcingrzejszczak** [comment]
Yeah, we had a small glitch ;) check this version https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-sleuth-dependencies/1.2.4.RELEASE/spring-cloud-sleuth-dependencies-1.2.4.RELEASE.pom

**Comment by brenuart** [comment]
Oh great! 
Sorry, did not notice version 1.2.4.RELEASE already exists :(

**Comment by marcingrzejszczak** [comment]
No problem, thanks for keeping your eyes on these things :)
