### ISSUE TITLE
Implement Sleuth interceptor for Apache HttpClient

### ISSUE THREAD

**Issue by metacubed** [spring-cloud/spring-cloud-sleuth#685]
Would it be possible to add an interceptor which instruments outgoing calls from an Apache HttpClient? It would follow the same pattern as the other interceptors in [org.springframework.cloud.sleuth.instrument.web.client](https://github.com/spring-cloud/spring-cloud-sleuth/tree/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client).

This interceptor would implement `org.apache.http.HttpRequestInterceptor`, and can be used as follows:

```java
@Autowired
private TraceHttpClientInterceptor tracingInterceptor; // New class

...

org.apache.http.client.HttpClient httpClient =
    HttpClientBuilder.create()
                     .addInterceptorFirst(tracingInterceptor)
                     .build();
```

**Comment by marcingrzejszczak** [comment]
How about a contribution? :) You have almost everything sorted out so it would be great if you continued the work and wrote the missing implementation and wrote some tests to it. We will gladly accept such a contribution :)

**Comment by metacubed** [comment]
@marcingrzejszczak, for sure, I'll be happy to contribute. I just wanted to be sure that it fits into the overall project before starting.

**Comment by marcingrzejszczak** [comment]
With the #711 done, it's enough to wrap your builder with Brave components (https://github.com/openzipkin/brave/tree/master/instrumentation/httpclient). Just add the `io.zipkin.brave:brave-instrumentation-httpclient` dependency.

> To enable tracing, create your client using TracingHttpClientBuilder.
```
httpclient = TracingHttpClientBuilder.create(tracing).build();
```

> You can also use TracingCachingHttpClientBuilder if you depend on org.apache.httpcomponents:httpclient-cache

**Comment by marcingrzejszczak** [comment]
Where `tracing` would be the `HttpTracing` bean.

```java
@Autowired HttpTracing tracing;

httpclient = TracingHttpClientBuilder.create(tracing).build();
```

**Comment by metacubed** [comment]
Yes, I saw the announcement just this week (I think). That and open-tracing compatibility are great news!

Once I got into implementation, I found that you couldn't really configure all available `HttpClientBuilder`s in a post-process step (like the `RestTemplate`), since they become immutable. So I dropped the idea and just configured the `HttpClient`s individually.

This solution bypasses that by asking you to use a custom builder. Your code still has to change at all points-of-use, but it is all neatly encapsulated.

**Comment by mukulb82** [comment]
@marcingrzejszczak please share the complete example. it will really help to see the implementation. is the project on github? i have the same problem statement to use apache HTTP client for tracing in spring boot microservice and export traces to zipkin

**Comment by marcingrzejszczak** [comment]
@mukulb82 wherever you're using an `HttpClient` you have to use in the way I've presented above. You can read more about this here https://github.com/openzipkin/brave/tree/master/instrumentation/httpclient and here you have a test for that https://github.com/openzipkin/brave/blob/master/instrumentation/httpclient/src/test/java/brave/httpclient/ITTracingHttpClientBuilder.java#L44-L55

**Comment by mukulb82** [comment]
okay. let me take a look. thanks

**Comment by mukulb82** [comment]
i have a question, in the java class - https://github.com/openzipkin/brave/blob/master/instrumentation/httpclient/src/test/java/brave/httpclient/ITTracingHttpClientBuilder.java how are you creating httpTracing ?

**Comment by marcingrzejszczak** [comment]
You can autowire it. `Tracer` and `HttpTracing` are available as beans.

**Comment by mukulb82** [comment]
@marcingrzejszczak i have a question, in the java class - https://github.com/openzipkin/brave/blob/master/instrumentation/httpclient/src/test/java/brave/httpclient/ITTracingHttpClientBuilder.java how are you creating httpTracing ?

**Comment by mukulb82** [comment]
ok, while autowiring these are not available. i tried doing the autowiring and i am being told

No qualifying bean of type 'brave.Tracing' available: expected at least 1 bean which qualifies as autowire candidate

**Comment by mukulb82** [comment]
i am using - spring-beans-4.3.9.RELEASE.jar

**Comment by marcingrzejszczak** [comment]
I have no idea what you're doing. If you generate a project via start.spring.io then it will work (https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java#L76). If you have questions about Brave, please go to Brave's GitHub project and ask for questions there or on Brave's Gitter channel.

**Comment by adriancole** [comment]
on gitter, both brave alone and also later sleuth were mentioned. I have no idea specifically what's of interest but if I create a diff for using httpclient I'll post it here.

**Comment by adriancole** [comment]
https://github.com/openzipkin/sleuth-webmvc-example#apache-http-client-tracing shows what we were talking about

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave-webmvc-example/compare/add-apachehc-tracing for brave standalone (just because I said I would :P )
