### ISSUE TITLE
High instrumentation overhead compared to Jaeger tracer

### ISSUE THREAD

**Issue by sweatybridge** [spring-cloud/spring-cloud-sleuth#686]
Hello,

As part of my research at Imperial College London, I designed and ran a few end-to-end latency benchmarks for various instrumentation libraries, including Sleuth, Jaeger, and our own tracer (Minke). Our result shows **8x higher** instrumentation overhead for Sleuth than both Jaeger and Minke (about 4ms per request with 10 spans). What do you think could be the cause of such high overhead?

Details of our experiment setup are described in my [presentation slides](https://www.slideshare.net/QiaoHan1/benchmarking-distributed-tracers). Please feel free to shoot me any questions you may have. I would be happy to help Sleuth improve.

Cheers,
Han Qiao

**Comment by adriancole** [comment]
@sweatybridge best path forward for things like this is to use JMH benchmark, as instrumentation overhead is usually not related to network activity. It is also useful to ensure things are apples/apples comparison. You up to doing that?

**Comment by adriancole** [comment]
as a tip, you can copy something like this if what you are tracing is spring web communication https://github.com/openzipkin/brave/tree/master/instrumentation/benchmarks/src/main/java/brave/spring

**Comment by sweatybridge** [comment]
While micro benchmark has its merits in profiling very specific sections of code, they do not represent realistic workloads. An end-to-end latency benchmark like wrk2 is extremely useful to the end user because it measures the overall impact of tracing, including instrumentation, buffering, and reporting. Components on the critical path tend to matter more because they affect latency directly but we cannot neglect background activities like asynchronous reporting because those are what's running on production systems.

In order to represent more realistic workloads, we decided to compare the full stack (both instruementation library and the server that collects traces). We allowed wrk2 to run for 2 minutes at a constant throughput (80 requests per second) for each run of the benchmark. Despite having extra layers in the stack like docker containers and networking, we are able to obtain very consistent results across multiple runs of the benchmark. The extreme outliers (less than 0.1% of all requests) vary quite a bit from run to run but the mean response time was very consistent.

Yes, it is going to be difficult trying to pinpoint which component is causing the extra latency (could be instrumentation, propagation between threads or between services, or trace collection). One possible way is to turn off reporting in the tracer so that traces are not collected to the server but you need to be careful not to affect buffering behaviour of the collector. I've made the benchmark source code available so feel free to customise it. If you would like to reproduce the result, it should be as straightforward as pointing wrk2 to the dedicated server running the benchmark application in a docker swarm described in readme.

**Comment by adriancole** [comment]
you conjecture is that there is "High instrumentation overhead" and that's something easy to track down, for whoever is interested in doing that. I'd encourage a PR with benchmarks that can live in this project to ensure whatever instrumentation overhead present is indeed removed. Until then, thanks for noticing, but I'm closing the issue as it has way too many variables for anyone to progress in an objective way.

**Comment by dsyer** [comment]
N.B. this project already has JMH benchmarks (https://github.com/spring-cloud/spring-cloud-sleuth/tree/master/benchmarks) and we have concluded from them that there is little or no instrumentation overhead. So you should probably redirect your investigation into how your full stack tests differ between sleuth and non-sleuth.

**Comment by adriancole** [comment]
If you must use a "real" tracing backend per experiment, try to use
the same one, as obviously any change to sleuth would need to affect
what it can control (which isn't the tracing system!). For example,
you could use COLLECTOR_SAMPLE_RATE=0.0 in zipkin to obviate the
in-memory storage limitations.

The in-memory zipkin setup is highly synchronized to make it
predictable (ex not OOM and not overlap writes) at the cost of
performance. Most defaults setup for ease as opposed to performance,
especially projects that cater towards beginners. An assumption that
defaults are the fastest is actually not usual.

https://github.com/openzipkin/zipkin/issues/1317#issuecomment-250730378
