### ISSUE TITLE
Support for native AspectJ load time weaving

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#688]
Spring might be able to improve here, but as things stand AspectJ LTW is much faster on startup (at runtime there isn't much difference, but it might be measurable). We could make it an option via config flags, so that the user can add an AspectJ agent if they know what they are doing.

**Comment by marcingrzejszczak** [comment]
Please upgrade to [Micrometer Tracing](https://docs.micrometer.io/tracing/reference/). Spring Cloud Sleuth is feature complete and out of OSS support.
