### ISSUE TITLE
A suggestion to make the span name more understandable

### ISSUE THREAD

**Issue by yanglifan** [spring-cloud/spring-cloud-sleuth#690]
When use `NewSpan` annotation, if the code looks like following:

```
@Repository
public interface UserRepository extends CrudRepository<User, Long> {
    @NewSpan
    User findByName(@SpanTag("username") String name);
}
```

You can find a span in ZipKin UI named "find-by-name". By this name, the span can be identified as a Java method easily. But if there is too many spans, only named by methods will not easy to locate a span in the code.

So may be `NewSpan` annotation can add a parameter called `namingPattern`, the value can be like CLASS_AND_METHOD, ONLY_METHOD and so on. Let user to define the strategy to generate the Zipkin span name.

Another way is to create a tag automatically to info the class name.

**Comment by marcingrzejszczak** [comment]
I think we initially discussed sth else in our Gitter conversation. We were talking about an option to add the class name into the tags. So before we do that by default (first let's ask @adriancole for his opinion on this), you can already set it yourself. Just read this part of the documentation http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.2.4.RELEASE/#_resolving_expressions_for_value  and then you can try to use a spell expression to retrieve the class name

**Comment by yanglifan** [comment]
Yes, add a tag to info the class name will be better to avoid the span name too long.

**Comment by marcingrzejszczak** [comment]
Also as a workaround you can create your own implementation of the `SpanCreator` interface. Over there you have already got everything you need to retrieve the class name and put it into tags
