### ISSUE TITLE
Add JDBC instrumentation

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#693]

**Comment by yanglifan** [comment]
Other than add JDBC instrumentation, may be can intercept Spring Data Repositories and Templates.

**Comment by marcingrzejszczak** [comment]
You can already use the Spring Data Repositories together with Sleuth's annotations.

**Comment by yanglifan** [comment]
But cannot add annotations on methods like `save()`, `findOne()`

**Comment by marcingrzejszczak** [comment]
Why? You can inherit a method in your interface and annotate it

**Comment by yanglifan** [comment]
Yes, but a little ugly.

**Comment by gavlyukovskiy** [comment]
I have created a library that is proxying your DataSource with one of the jdbc instrumentation libraries such as [p6spy](https://github.com/p6spy/p6spy). 
It as well integrates with sleuth and registers listener that is very similar to the one from [brave-instrumentation-p6spy](https://github.com/openzipkin/brave/tree/f419332ac0532ed6a2996140397e16457dd58e5c/instrumentation/p6spy), but mine is also creating span for each connection taken from the DataSource and query span includes time to close ResultSet if query returns it.

In zipkin it looks great:
![zipkin](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/raw/master/images/zipkin.png)
You can find more screenshots and try it on [library page](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator).

**Comment by marcingrzejszczak** [comment]
That looks awesome @gavlyukovskiy . Let's do it like this. Everyone who is interested in this feature please try the https://github.com/gavlyukovskiy/spring-boot-data-source-decorator library. Once we get more parties involved and happy with the library we'll think of putting it in the core of Sleuth.

**Comment by marcingrzejszczak** [comment]
Closing this in favour of Brave's p6spy instrumentaiton - https://github.com/openzipkin/brave/tree/master/instrumentation/p6spy#brave-instrumentation-p6spy
