### ISSUE TITLE
Latest sleuth 2.0 milestone is broken wrt latest spring boot 2.0 milestone

### ISSUE THREAD

**Issue by eric239** [spring-cloud/spring-cloud-sleuth#700]
sleuth `2.0.0.M2` (as well as prior 2.0 milestones) is broken after upgrade to spring boot `2.0.0.M4`

`TraceHandlerInterceptor` refers to `ErrorController` which has (finally) been moved to the new package. This was raised several month ago in #592 and has finally fired.

**Comment by marcingrzejszczak** [comment]
Yup we know and we fixed it AFAIR but some other issues occurred and the build is broken currently

**Comment by eric239** [comment]
@marcingrzejszczak thanks for the quick response, I'll wait for the new milestone build
