### ISSUE TITLE
 Dropped 1 spans due to ConnectException

### ISSUE THREAD

**Issue by jidianxiake** [spring-cloud/spring-cloud-sleuth#702]

**Comment by marcingrzejszczak** [comment]
Have you opened this issue by accident?

**Comment by jidianxiake** [comment]
I use feign. Always show unknow, the interface can not display dependency graphs

**Comment by marcingrzejszczak** [comment]
You know that you haven't provided any information? No Sleuth version, no stacktrace, nothing. You use Feign? That's great but I think it's completely irrelevant cause you have `ConnectException` when trying to send spans to Zipkin. So most likely you've provided a wrong URL, port or sth to Zipkin

**Comment by jidianxiake** [comment]
thanks.I have solve this problem
