### ISSUE TITLE
zipkin shows unkown serviceName ,and all traces services are unkown

### ISSUE THREAD

**Issue by 358235737** [spring-cloud/spring-cloud-sleuth#704]
[
  [
    {
      "traceId": "408c144293bc27ea",
      "id": "408c144293bc27ea",
      "name": "http:/test",
      "timestamp": 1505963560002000,
      "duration": 26839,
      "annotations": [
        {
          "timestamp": 1505963560002000,
          "value": "sr",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "timestamp": 1505963560028000,
          "value": "ss",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ],
      "binaryAnnotations": [
        {
          "key": "spring.instance_id",
          "value": "cnsz141760:openapi-netway-front:35004",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ]
    },
    {
      "traceId": "408c144293bc27ea",
      "id": "d62b9197bd400626",
      "name": "http:/openapiapp/test",
      "parentId": "408c144293bc27ea",
      "timestamp": 1505963560005000,
      "duration": 15000,
      "annotations": [
        {
          "timestamp": 1505963560005000,
          "value": "cs",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "timestamp": 1505963560020000,
          "value": "cr",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ],
      "binaryAnnotations": [
        {
          "key": "http.host",
          "value": "SQSZ-L1150",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "http.method",
          "value": "GET",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "http.path",
          "value": "/OpenAPIApp/test",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "http.url",
          "value": "http://SQSZ-L1150:8083/OpenAPIApp/test",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "spring.instance_id",
          "value": "cnsz141760:openapi-netway-front:35004",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ]
    },
    {
      "traceId": "408c144293bc27ea",
      "id": "8a4d9a2eb66a646f",
      "name": "http:/test",
      "parentId": "408c144293bc27ea",
      "timestamp": 1505963560029000,
      "duration": 70,
      "binaryAnnotations": [
        {
          "key": "lc",
          "value": "unknown",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ]
    }
  ],
  [
    {
      "traceId": "01e1ac7a2e6a428e",
      "id": "01e1ac7a2e6a428e",
      "name": "http:/test",
      "timestamp": 1505963509734000,
      "duration": 84127,
      "annotations": [
        {
          "timestamp": 1505963509734000,
          "value": "sr",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "timestamp": 1505963509817000,
          "value": "ss",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ],
      "binaryAnnotations": [
        {
          "key": "spring.instance_id",
          "value": "cnsz141760:openapi-netway-front:35004",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ]
    },
    {
      "traceId": "01e1ac7a2e6a428e",
      "id": "30bb80af5eefeb3c",
      "name": "http:/openapiapp/test",
      "parentId": "01e1ac7a2e6a428e",
      "timestamp": 1505963509737000,
      "duration": 73000,
      "annotations": [
        {
          "timestamp": 1505963509738000,
          "value": "cs",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "timestamp": 1505963509811000,
          "value": "cr",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ],
      "binaryAnnotations": [
        {
          "key": "http.host",
          "value": "SQSZ-L1150",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "http.method",
          "value": "GET",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "http.path",
          "value": "/OpenAPIApp/test",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "http.url",
          "value": "http://SQSZ-L1150:8082/OpenAPIApp/test",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "spring.instance_id",
          "value": "cnsz141760:openapi-netway-front:35004",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ]
    },
    {
      "traceId": "01e1ac7a2e6a428e",
      "id": "4a0397665fcd0231",
      "name": "http:/test",
      "parentId": "01e1ac7a2e6a428e",
      "timestamp": 1505963509818000,
      "duration": 73,
      "binaryAnnotations": [
        {
          "key": "lc",
          "value": "unknown",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ]
    }
  ],
  [
    {
      "traceId": "c790060deb526788",
      "id": "c790060deb526788",
      "name": "http:/test",
      "timestamp": 1505963509133000,
      "duration": 187227,
      "annotations": [
        {
          "timestamp": 1505963509133000,
          "value": "sr",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "timestamp": 1505963509319000,
          "value": "ss",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ],
      "binaryAnnotations": [
        {
          "key": "spring.instance_id",
          "value": "cnsz141760:openapi-netway-front:35004",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ]
    },
    {
      "traceId": "c790060deb526788",
      "id": "3cc14e75ebf4bcf2",
      "name": "http:/openapiapp/test",
      "parentId": "c790060deb526788",
      "timestamp": 1505963509136000,
      "duration": 115000,
      "annotations": [
        {
          "timestamp": 1505963509136000,
          "value": "cs",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "timestamp": 1505963509251000,
          "value": "cr",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ],
      "binaryAnnotations": [
        {
          "key": "http.host",
          "value": "SQSZ-L1150",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "http.method",
          "value": "GET",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "http.path",
          "value": "/OpenAPIApp/test",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "http.url",
          "value": "http://SQSZ-L1150:8083/OpenAPIApp/test",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "spring.instance_id",
          "value": "cnsz141760:openapi-netway-front:35004",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ]
    },
    {
      "traceId": "c790060deb526788",
      "id": "0460a6718be1522c",
      "name": "http:/test",
      "parentId": "c790060deb526788",
      "timestamp": 1505963509319000,
      "duration": 65,
      "binaryAnnotations": [
        {
          "key": "lc",
          "value": "unknown",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ]
    }
  ],
  [
    {
      "traceId": "83049d2b57926528",
      "id": "83049d2b57926528",
      "name": "refresh-dubbo-enabler-cache",
      "timestamp": 1505963446413000,
      "duration": 8372519,
      "binaryAnnotations": [
        {
          "key": "class",
          "value": "DubboEnablerLocalCacheRefresh",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.243.245.139",
            "port": 35004
          }
        },
        {
          "key": "lc",
          "value": "scheduled",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.243.245.139",
            "port": 35004
          }
        },
        {
          "key": "method",
          "value": "refreshDubboEnablerCache",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.243.245.139",
            "port": 35004
          }
        }
      ]
    }
  ],
  [
    {
      "traceId": "ec47dff903a797ec",
      "id": "ec47dff903a797ec",
      "name": "refresh-dubbo-enabler-cache",
      "timestamp": 1505963316520000,
      "duration": 8168933,
      "binaryAnnotations": [
        {
          "key": "class",
          "value": "DubboEnablerLocalCacheRefresh",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.243.245.139",
            "port": 35004
          }
        },
        {
          "key": "lc",
          "value": "scheduled",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.243.245.139",
            "port": 35004
          }
        },
        {
          "key": "method",
          "value": "refreshDubboEnablerCache",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.243.245.139",
            "port": 35004
          }
        }
      ]
    }
  ],
  [
    {
      "traceId": "bd574565fd672329",
      "id": "bd574565fd672329",
      "name": "refresh-dubbo-enabler-cache",
      "timestamp": 1505963291112000,
      "duration": 3895,
      "binaryAnnotations": [
        {
          "key": "class",
          "value": "DubboEnablerLocalCacheRefresh",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "lc",
          "value": "scheduled",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "method",
          "value": "refreshDubboEnablerCache",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ]
    }
  ],
  [
    {
      "traceId": "27b19dee9dcbc292",
      "id": "27b19dee9dcbc292",
      "name": "refresh-dubbo-enabler-cache",
      "timestamp": 1505963171066000,
      "duration": 41045,
      "binaryAnnotations": [
        {
          "key": "class",
          "value": "DubboEnablerLocalCacheRefresh",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "lc",
          "value": "scheduled",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "method",
          "value": "refreshDubboEnablerCache",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ]
    }
  ],
  [
    {
      "traceId": "3102200d11a1009b",
      "id": "3102200d11a1009b",
      "name": "refresh-dubbo-enabler-cache",
      "timestamp": 1505962796663000,
      "duration": 12746,
      "binaryAnnotations": [
        {
          "key": "class",
          "value": "DubboEnablerLocalCacheRefresh",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "lc",
          "value": "scheduled",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        },
        {
          "key": "method",
          "value": "refreshDubboEnablerCache",
          "endpoint": {
            "serviceName": "unknown",
            "ipv4": "10.25.174.28",
            "port": 35004
          }
        }
      ]
    }
  ]
]

**Comment by 358235737** [comment]
information：
org.springframework.cloud:spring-cloud-dependencies:Dalston.SR3
springBootVersion = '1.5.3.RELEASE'
compile 'org.springframework.cloud:spring-cloud-starter-zipkin'

**Comment by marcingrzejszczak** [comment]
Can you please upload your project somewhere on Github? Also could you please read this doc on how to format the code ? https://help.github.com/articles/creating-and-highlighting-code-blocks/

Are you sure you have the `spring.application.name` set ? Cause we set it as `uknown` only if it doesn't have a value. Please also try to move it to `bootstrap.yml` and try again

**Comment by marcingrzejszczak** [comment]
Ping @358235737 ?

**Comment by jidianxiake** [comment]
I tried, or did not work

**Comment by jidianxiake** [comment]
I found that it has not read the spring application name in the configuration file, but using zookeeper as the registry, it has successfully registered up, and the sping application name is configured in our configuration file. Do not know why this happens The

**Comment by jidianxiake** [comment]
@marcingrzejszczak can you give me some ideas

**Comment by marcingrzejszczak** [comment]
If you don't upload your project as a sample it will be difficult to help you

**Comment by marcingrzejszczak** [comment]
I'm closing this one. I've changed this in Edgware so that the name gets resolved at runtime.
