### ISSUE TITLE
spring-cloud-sleuth surpressing information

### ISSUE THREAD

**Issue by jidianxiake** [spring-cloud/spring-cloud-sleuth#705]
my spring-cloud-sleuth service uses the built-in tomcat boot, my consumer, with the provider using the external tomcat boot, zipkin-server suppresses the display when collecting information always show java.net.ConnectException: Connection refused: connect,how can i do

**Comment by spencergibb** [comment]
Please provide more information. Versions, steps to reproduce or a project that replicates the problem.

**Comment by jidianxiake** [comment]
spring-cloud-dependencies-Camden.SR6    spring-boot-starter-parent-1.5.2.RELEASE,zipkin-server is a jar,but cousumer is war and provider is war .

**Comment by spencergibb** [comment]
Please provide steps to reproduce or a project that replicates the problem.

**Comment by jidianxiake** [comment]
I first start zipkin-server this application through the springboot way, after the success of a time I started through the tomcat provider, and then start the consumer. Then let the consumer out of the user but in the zipkin interface all show unknow call link diagram. Did not show application name. Are unknow in the form of display

**Comment by adriancole** [comment]
I'd recommend starting zipkin the supported way, first. Once you do that successfully, then you can try something custom. Regardless, this isn't the forum for zipkin server support. https://gitter.im/openzipkin/zipkin

https://github.com/openzipkin/zipkin#quick-start
