### ISSUE TITLE
TraceFilter creates two Spans when calling non-Spring Controllers

### ISSUE THREAD

**Issue by dhay** [spring-cloud/spring-cloud-sleuth#708]
It appears that the TraceFilter will end up creating two spans if the final destination in the web application is not a Spring Controller that has been wrapped with the `TraceHandlerInterceptor` (e.g. a plain old `Servlet`).  

This seems to be related to the implementation of `TraceFilter.createSpanIfRequestNotHandled`, which looks for the presence of the `TraceRequestAttributes.HANDLED_SPAN_REQUEST_ATTR` request attribute.  As far as I can tell, the `TraceHandlerInterceptor` is the only thing that sets this attribute. I'm not really sure what it means for a Span to be considered "handled". 

Here is an updated set of tests for `TraceFilterTests` that demonstrates the problem. I updated the `startsNewTrace` test and added a second test that simulates what happens when the `TraceHandlerInterceptor` is invoked.

```
@Test
public void startsNewTrace() throws Exception {
	TraceFilter filter = new TraceFilter(beanFactory());
	filter.doFilter(this.request, this.response, this.filterChain);


	then(TestSpanContextHolder.getCurrentSpan()).isNull();
	then(new ListOfSpans(this.spanReporter.getSpans()))
			.hasSize(1) // <---- Fails on this assertion. Returns 2 instead of the expected 1
			.hasASpanWithTagEqualTo("http.url", "http://localhost/?foo=bar")
			.hasASpanWithTagEqualTo("http.host", "localhost")
			.hasASpanWithTagEqualTo("http.path", "/")
			.hasASpanWithTagEqualTo("http.method", HttpMethod.GET.toString())
			.hasASpanWithTagEqualTo("http.status_code", HttpStatus.OK.toString())
			.allSpansAreExportable();
}

@Test
public void startsNewTraceWithTraceHandlerInterceptor() throws Exception {
	final BeanFactory beanFactory = beanFactory();
	TraceFilter filter = new TraceFilter(beanFactory);
	filter.doFilter(this.request, this.response, (req, resp) -> {
		this.filterChain.doFilter(req, resp);
		// Simulate execution of the TraceHandlerInterceptor
		request.setAttribute(TraceRequestAttributes.HANDLED_SPAN_REQUEST_ATTR, tracer.getCurrentSpan());
	});


	then(TestSpanContextHolder.getCurrentSpan()).isNull();
	then(new ListOfSpans(this.spanReporter.getSpans()))
			.hasSize(1)
			.hasASpanWithTagEqualTo("http.url", "http://localhost/?foo=bar")
			.hasASpanWithTagEqualTo("http.host", "localhost")
			.hasASpanWithTagEqualTo("http.path", "/")
			.hasASpanWithTagEqualTo("http.method", HttpMethod.GET.toString())
			.hasASpanWithTagEqualTo("http.status_code", HttpStatus.OK.toString())
			.allSpansAreExportable();
}
```

**Comment by marcingrzejszczak** [comment]
It's a well-known issue (I guess I must document it). Thanks for creating an issue though with a test case. I might use in the docs. 

> TraceHandlerInterceptor is the only thing that sets this attribute. I'm not really sure what it means for a Span to be considered "handled".

It means that a Spring related component has managed to create an additional child span. If that's not the case then without that additional span, you will have the Zipkin graph broken, as the debug message says:

```
"The request with uri [" + request.getRequestURI() + "] hasn't been handled by any of Sleuth's components. "
						+ "That means that most likely you're using custom HandlerMappings and didn't add Sleuth's TraceHandlerInterceptor. "
						+ "Sleuth will create a span to ensure that the graph of calls remains valid in Zipkin
```

Does it make sense?

**Comment by dhay** [comment]
I guess I'm confused.  

First, the `TraceHandlerInterceptor` doesn't create a new span, it continues the original span created by the Trace filter (unless there isn't one for some odd reason).  Second, what's broken in the Zipkin graph if we don't create the second span? Isn't a trace with a single span a valid trace?

**Comment by marcingrzejszczak** [comment]
> First, the TraceHandlerInterceptor doesn't create a new span, it continues the original span created by the Trace filter (unless there isn't one for some odd reason)

Yeah and I was talking about these odd reasons. In Sleuth we're trying to always continue spans but sometimes that's not possible.

> Second, what's broken in the Zipkin graph if we don't create the second span? Isn't a trace with a single span a valid trace?

As far as I remember you wouldn't see the bar in the service that processes the request. So let's say that A is calling B and in B we don't add this "additional span", then AFAIR in Zipkin you will not see the bar corresponding to B. But maybe something has changed in Zipkin and that's no longer valid. You can try it out by putting an additional filter that just sets the value of the attribute. If you do that, and the graph is correct then it means that Zipkin got fixed and this workaround is not necessary

**Comment by dhay** [comment]
That's exactly the work-around we've made to work around the issue. The spans in Zipkin appear to look correct from what I can tell.

**Comment by marcingrzejszczak** [comment]
Ok then, good to know. Most likely they fixed it. I'll update the code for Edgware than. (I think that @devinsba had the same case. Can you double check @devinsba that if you add the filter entry then things still work fine for you?)

**Comment by devinsba** [comment]
@dhay great write up. I was missing the entire context when I reported it. I'll close my issue since this one is much better.

**Comment by marcingrzejszczak** [comment]
I wrote a pretty long note in the commit message. I'll rewrite it here:

> without this change we created a "fallback span" in the case where a Spring component didn't handle the span. By handling it means that it got processed by anyway (a tag, log was added etc.). Why did we do that? That's because if no component was involved in creation of additional spans then in the Zipkin UI the service that had only the span that has the SR, SS logs wouldn't show up. In other words, if service A called service B and service B had only a single span, then service B wouldn't show up in the UI (there would be no blue bar). All the data would show up however in the client side of that span.
>
> with this change we're removing this behaviour. That's because it introduces confusion for our users, that use non Spring related components. Also it seems that the Zipkin UI got fixed and this error no longer is present. If however it turns out that it's still there, it clearly seems that the place to fix this error should be Zipkin and not Sleuth.
