### ISSUE TITLE
Add support for Dubbo

### ISSUE THREAD

**Issue by liangGTY** [spring-cloud/spring-cloud-sleuth#710]

**Comment by spencergibb** [comment]
Dubbo? Please provide more information and reopen

**Comment by marcingrzejszczak** [comment]
From what I understand you mean this - http://dubbo.io/ ? I'm not faimilar with @liangGTY so if you know more about this maybe you can describe how it works and maybe help us with a PR ?

**Comment by liangGTY** [comment]
yes ! I mean that's it - [https://github.com/alibaba/dubbo](https://github.com/alibaba/dubbo) I also want PR， but i lack of ability ,so i ask...

**Comment by adriancole** [comment]
depending on how we address #711 we could consider doing dubbo here or via brave https://github.com/openzipkin/brave/issues/504

**Comment by adriancole** [comment]
I'm pretty sure https://github.com/openzipkin/brave/pull/623 will allow you to plug in by default, as long as you choose the filter named "tracing"

**Comment by marcingrzejszczak** [comment]
The Dubbo support got merged to Brave - https://github.com/openzipkin/brave/pull/623/files

**Comment by adriancole** [comment]
ps if comes time to automatically configure "tracing" where the user isn't already doing this, it would likely be via the hook  com.alibaba.dubbo.config.AbstractConfig#appendAnnotation

**Comment by wujun8** [comment]
@adriancole May I ask about this support of Dubbo, is it only a feature for sleuth tracing?
We can say that Spring Cloud Sleuth supports Dubbo, but Spring Cloud is still using Rest rather than RPC like Dubbo. Is that correct?

**Comment by adriancole** [comment]
sleuth doesnt change how you communicate, it just traces what you use to
communicate. so if you use spring webmvc sleuth traces this. supporting
dunno does not remove support for web.
