### ISSUE TITLE
I encountered a problem that is the use of springcloudsleuth I was using external tomcat to load my application But I found zipkin query interface on the serviceName has become unknown, is not he did not load my configuration file in the spring.application.name what should i do?

### ISSUE THREAD

**Issue by jidianxiake** [spring-cloud/spring-cloud-sleuth#712]

**Comment by marcingrzejszczak** [comment]
@jidianxiake can you please read this article - https://wiredcraft.com/blog/how-we-write-our-github-issues/ on how to write Github issues? You have put a gigantic title, without even presenting the context behind your problem. We have no idea what the version of Sleuth is. Your title contains no valuable content to help you. I will close this issue, please read the article and when you're ready please file a new one.
