### ISSUE TITLE
Need to expire traces based on in-memory storage component in zipkin

### ISSUE THREAD

**Issue by hellouserchn** [spring-cloud/spring-cloud-sleuth#713]
When I use the open source version of Zipkin I am able to set the max number of spans and expire them accordingly as below.

I am using the latest version of Zipkin for  which this in-memory storage component was added from Zipkin 1.28.

java -Dzipkin.storage.mem.max-spans=5 -jar  zipkin-server-2.0.1-exec.jar

But, when I add the below dependencies and create/build a Spring Boot based zipkin service as below.
```
<dependencies>
	<dependency>
			<groupId>io.zipkin.java</groupId>
			<artifactId>zipkin-server</artifactId>
		</dependency>
		<dependency>
			<groupId>io.zipkin.java</groupId>
			<artifactId>zipkin-autoconfigure-ui</artifactId>
			<scope>runtime</scope>
		</dependency>
</dependencies>

<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Dalston.SR1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

 I do not see the spans expiring accordingly.

I have added the property -D**zipkin.storage.mem.max-spans=5** while starting the service.

I even tried adding **zipkin.storage.mem.max-spans=5** application configuration application.yml.

What version of Zipkin are the maven dependencies are based. 

Should I need to do add anything other than those.

**Comment by marcingrzejszczak** [comment]
I think you should file this issue in the https://github.com/openzipkin/zipkin project.

**Comment by hellouserchn** [comment]
I do not understand. The open source version of Zipkin works fine. I only want to know why it does not work with spring cloud.  If I use spring cloud sleuth and zipkin dependencies and create my own Zipkin service it does not work. So, how would the issue be with openzipkin?

**Comment by adriancole** [comment]
I would do mvn dependency:tree and make sure you are running the same
zipkin.jar version as you think you are! Declare explicit dependency if
needed.

**Comment by dpoddar** [comment]
Did you find any solution to this issue? If yes could you please post the solution/

**Comment by dpoddar** [comment]
With Spring boot **Dalston.SR3** (which uses open zipkin 1.28) you can achieve this by setting property **zipkin.storage.mem.max-spans=xxxx** This will limit the number of spans and discard old ones.
