### ISSUE TITLE
Setting spring.sleuth.rxjava.schedulers.hook.enabled doesn't work

### ISSUE THREAD

**Issue by kutzi** [spring-cloud/spring-cloud-sleuth#718]
When trying to set spring.sleuth.rxjava.schedulers.hook.enabled as documented here 
http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.2.4.RELEASE/#_rxjava
I get an expection:

> 2017-09-29 14:58:48,017 ERROR [main] o.s.boot.SpringApplication: Application startup failed  
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sleuthRxJavaSchedulersHook' defined in class path resource [org/springframework/cloud/sleuth/instrument/rxjava/RxJavaAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sleuthRxJavaSchedulersHook' parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.sleuth.rxjava.schedulers-org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties': Could not bind properties to SleuthRxJavaSchedulersProperties (prefix=spring.sleuth.rxjava.schedulers, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.beans.NullValueInNestedPathException: Invalid property 'hook' of bean class [org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties]: Could not instantiate property type [org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties$Hook] to auto-grow nested property path; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties$Hook]: Is the constructor accessible?; nested exception is java.lang.IllegalAccessException: Class org.springframework.beans.BeanUtils can not access a member of class org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties$Hook with modifiers "private"
> 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
> 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
> 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
> 	at com.tipp24.cara.Application.main(Application.java:92)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
> 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.sleuth.rxjava.schedulers-org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties': Could not bind properties to SleuthRxJavaSchedulersProperties (prefix=spring.sleuth.rxjava.schedulers, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.beans.NullValueInNestedPathException: Invalid property 'hook' of bean class [org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties]: Could not instantiate property type [org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties$Hook] to auto-grow nested property path; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties$Hook]: Is the constructor accessible?; nested exception is java.lang.IllegalAccessException: Class org.springframework.beans.BeanUtils can not access a member of class org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties$Hook with modifiers "private"
> 	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:334)
> 	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:291)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
> 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
> 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
> 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
> 	... 25 common frames omitted
> Caused by: org.springframework.beans.NullValueInNestedPathException: Invalid property 'hook' of bean class [org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties]: Could not instantiate property type [org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties$Hook] to auto-grow nested property path; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties$Hook]: Is the constructor accessible?; nested exception is java.lang.IllegalAccessException: Class org.springframework.beans.BeanUtils can not access a member of class org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties$Hook with modifiers "private"
> 	at org.springframework.beans.AbstractNestablePropertyAccessor.newValue(AbstractNestablePropertyAccessor.java:933)
> 	at org.springframework.beans.AbstractNestablePropertyAccessor.createDefaultPropertyValue(AbstractNestablePropertyAccessor.java:901)
> 	at org.springframework.beans.AbstractNestablePropertyAccessor.setDefaultValue(AbstractNestablePropertyAccessor.java:889)
> 	at org.springframework.beans.AbstractNestablePropertyAccessor.getNestedPropertyAccessor(AbstractNestablePropertyAccessor.java:853)
> 	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyAccessorForPropertyPath(AbstractNestablePropertyAccessor.java:827)
> 	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:270)
> 	at org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanWrapper.setPropertyValue(RelaxedDataBinder.java:699)
> 	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:95)
> 	at org.springframework.validation.DataBinder.applyPropertyValues(DataBinder.java:859)
> 	at org.springframework.validation.DataBinder.doBind(DataBinder.java:755)
> 	at org.springframework.boot.bind.RelaxedDataBinder.doBind(RelaxedDataBinder.java:128)
> 	at org.springframework.validation.DataBinder.bind(DataBinder.java:740)
> 	at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:272)
> 	at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:240)
> 	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:329)
> 	... 39 common frames omitted
> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties$Hook]: Is the constructor accessible?; nested exception is java.lang.IllegalAccessException: Class org.springframework.beans.BeanUtils can not access a member of class org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties$Hook with modifiers "private"
> 	at org.springframework.beans.BeanUtils.instantiate(BeanUtils.java:83)
> 	at org.springframework.beans.AbstractNestablePropertyAccessor.newValue(AbstractNestablePropertyAccessor.java:928)
> 	... 53 common frames omitted
> Caused by: java.lang.IllegalAccessException: Class org.springframework.beans.BeanUtils can not access a member of class org.springframework.cloud.sleuth.instrument.rxjava.SleuthRxJavaSchedulersProperties$Hook with modifiers "private"
> 	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
> 	at java.lang.Class.newInstance(Class.java:436)
> 	at org.springframework.beans.BeanUtils.instantiate(BeanUtils.java:77)
> 	... 54 common frames omitted

**Comment by kutzi** [comment]
Thanks for the quick fix.
One question: as far as I can see, the property isn't accessed anywhere in spring-cloud-sleuth code currently. Is this correct and so it doesn't matter if I set the property or not, right?

**Comment by marcingrzejszczak** [comment]
It's used here - https://github.com/spring-cloud/spring-cloud-sleuth/blob/24f6827a4a968440bf286228edb085be9d00dfe5/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/rxjava/RxJavaAutoConfiguration.java#L29

**Comment by kutzi** [comment]
Ah, yeah. Thanks
