### ISSUE TITLE
Using autowired ThreadPoolTaskExecutor

### ISSUE THREAD

**Issue by tdawe** [spring-cloud/spring-cloud-sleuth#722]
When using sleuth, my autowired ThreadPoolTaskExecutor is not being instantiated correctly.

Output with sleuth dependency in my pom.xml: Core pool size = 1

Output with sleuth dependency **not** in my pom.xml: Core pool size = 2

Class:

```
@SpringBootApplication()
@Configuration
@ImportResource("classpath:config.xml")
public class SampleApplication {

    @Autowired
    ThreadPoolTaskExecutor executor;

    public static void main(String[] args) {
        SpringApplication.run(SampleApplication.class, args);
    }

    @PostConstruct
    public void test() {
        System.out.println("Core pool size = " + executor.getCorePoolSize());
    }

}
```

config.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

	<bean id="taskExecutor"
		class="org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor">
		<property name="corePoolSize" value="2" />
		<property name="maxPoolSize" value="5" />
		<property name="waitForTasksToCompleteOnShutdown" value="true" />
	</bean>
		
</beans>
```

**Comment by devinsba** [comment]
Sleuth wraps your `ThreadPoolTaskExecutor` in a `LazyTraceThreadPoolTaskExecutor` so that it can track traces through async operations. Looks like the `getCorePoolSize()` method is not passed to the backing Executor but all the normal execution related operations will be sent to the executor you create.

**Comment by roberthafner** [comment]
We are running into this issue in our environment as well. Are there plans to release another 1.2.x release containing this fix soon?
