### ISSUE TITLE
Truncate span names at 255 characters

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#723]
Zipkin tracers usually default span names to the http method or RPC name as things like URLs can include variables that have two effects:
* can be really long
* can repeat, making them a poor choice for grouping

The current naming convention doesn't prevent these situations from occurring. We should at least limit (truncate) the length to 255 characters as multiple systems only index that much. The full url can still exist as a tag and be searchable by that.

_From @pennstatephil on September 29, 2017 15:27_

Currently, "name" in the database is limited to 255 characters. We have some REALLY long URLs (I know it's not ideal) and this causes a SQL exception:

`[ZipkinMySQLStorage-1] zipkin.server.ZipkinHttpCollector        : Cannot store spans [bc4e3b8f7025cbde.aff2ed227e2cea87<:bc4e3b8f7025cbde, bc4e3b8f7025cbde.aff2ed227e2cea87<:bc4e3b8f7025cbde, 4bad878142e4c587.069ffdef649e62c4<:c603f78125156b83, 4bad878142e4c587.c603f78125156b83<:4bad878142e4c587] due to DataAccessException(SQL [null]; Data truncation: Data too long for column 'name' at row 1)`

Trying to increase the field ourselves causes a key length error:

`17:07:35	alter table zipkin.zipkin_spans modify column name varchar(400)	Error Code: 1071. Specified key was too long; max key length is 767 bytes	0.00033 sec`

Is there any way to get a longer name supported? If not, is there a recommended practice we can follow to work around the issue?

_Copied from original issue: openzipkin/zipkin#1751_

**Comment by adriancole** [comment]
URLs tend to be a bad choice for span names as they end up with variable
names in them (which explodes the cardinality). Do you have very long span
names that don't have variables encoded? In general, we default to method
name, or where supported the associated RPC name (ex method name)

**Comment by adriancole** [comment]
meant "RPC name (ex function name)"

**Comment by adriancole** [comment]
_From @pennstatephil on October 3, 2017 16:0_

On further inspection, this is an issue with the way Spring Cloud Sleuth picks span names:

TraceFilter.java line 136:
`String name = HTTP_COMPONENT + ":" + uri;`

When "uri" is really long, we start seeing these issues. I can migrate this issue over to that project... Or, is there an easy way to override the span name?

edited to add: looks like it's been reported here: https://github.com/spring-cloud/spring-cloud-sleuth/issues/500

**Comment by adriancole** [comment]
revised description

**Comment by marcingrzejszczak** [comment]
We're truncating already at 50 chars according to https://github.com/spring-cloud/spring-cloud-sleuth/issues/530 . Do you want to extend this value to 255 ?

**Comment by marcingrzejszczak** [comment]
Maybe an older version of sleuth was used?

**Comment by adriancole** [comment]
is something else shortening this then? https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java#L160

**Comment by adriancole** [comment]
yep https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/trace/DefaultTracer.java#L93

must be old version you are right

**Comment by marcingrzejszczak** [comment]
You can check if your DefaultTracer contains the line of code that truncates the name. If it doesn't then you have to upgrade (btw camden is ancient) if it does then we have a bug
