### ISSUE TITLE
zipkin server discovery could not work with consul

### ISSUE THREAD

**Issue by LittleShrimp1987** [spring-cloud/spring-cloud-sleuth#731]
I use consul as register server,  yaml config as follows:
spring:
  zipkin:
    enabled: true
    baseUrl: http://zipkin-http-server/

zipkin-http-server is the zipkin server's name registered in consul, but the error message shows that zipkin-http-server is UnknownHost.

**Comment by marcingrzejszczak** [comment]
Which version of sleuth are you using? Check if you're using the version that supports this feature

**Comment by LittleShrimp1987** [comment]
thanks. ok, I will check that. 
springcloud version: Camden.SR7
sleuth version: 1.1.4.REALEASE

**Comment by marcingrzejszczak** [comment]
The feature is not supported in Camden

**Comment by LittleShrimp1987** [comment]
all right, thank you very much, I will try newer version that support this feature.

**Comment by LittleShrimp1987** [comment]
I have tried Dalston.SR4, still not works.

**Comment by marcingrzejszczak** [comment]
It's working with Edgware - http://cloud.spring.io/spring-cloud-sleuth/single/spring-cloud-sleuth.html#_sending_spans_to_zipkin

Issues:

- #640
- #642

**Comment by LittleShrimp1987** [comment]
Edgware works. Thanks.
