### ISSUE TITLE
Enable zipkin trace server location via discovery client (e.g. consul)

### ISSUE THREAD

**Issue by bashnesnos** [spring-cloud/spring-cloud-sleuth#732]
It's a bit sad to supply zipkin url via baseUrl when we are using consul for dicovering and checking services. It would be a really nice feature to enable service discovery for the zipking http collector.

I've done some hacking to achieve this, since current HttpZipkinSpanReporter is protected from this kind of modification. 

Basically, to achieve the thing I wanted I've created a configuration like this

    @Configuration
    public class ZipkinConsulConfiguration {
        @Value("${cloud.trace.service.name}")
        private String cloudTraceServiceName;

        @Bean
        public ZipkinSpanReporter reporter(ConsulDiscoveryClient discoveryClient, SpanMetricReporter spanMetricReporter, ZipkinProperties zipkin, ZipkinRestTemplateCustomizer zipkinRestTemplateCustomizer) {
            RestTemplate restTemplate = new RestTemplate();
            zipkinRestTemplateCustomizer.customize(restTemplate);
            return new ConsulHttpZipkinSpanReporter(restTemplate, cloudTraceServiceName, discoveryClient, zipkin.getFlushInterval(), spanMetricReporter);
        }
    }

And then copy-pasted HttpZipkinSpanReporter into a [ConsulHttpZipkinSpanReporter](https://gist.github.com/bashnesnos/ba43b643397239c48763184b89d07965), where I just swapped the RestTemplateSender with the consul-aware [ConsulRestTemplateSender](https://gist.github.com/bashnesnos/e7cc4afee368173e14a3d34963569e5e)

My happiness could be even bigger, if a similar solution was provided from the Spring libraries, you know.

What do you guys think of merging it into one of the next releases?

**Comment by marcingrzejszczak** [comment]
It's already working with Edgware - http://cloud.spring.io/spring-cloud-sleuth/single/spring-cloud-sleuth.html#_sending_spans_to_zipkin

Issues: 
- https://github.com/spring-cloud/spring-cloud-sleuth/issues/640
- https://github.com/spring-cloud/spring-cloud-sleuth/issues/642

**Comment by bashnesnos** [comment]
Cool, thanks. I'll check Edgware's snapshot and await the release then.
