### ISSUE TITLE
Zipkin Eureka Discovery Client Zone affinity

### ISSUE THREAD

**Issue by jprateekvmware** [spring-cloud/spring-cloud-sleuth#734]
Can it be ribbon based ? We have eureka server setup across zone in peer and we have setting done which will hop over to host in another zone if the service in the current zone are down.

Current configuration directly fetches from the eureka registry and do roundrobin over it. Ideally it should be zone aware.  We can make it ribbon based.

pcf-sample,19:36:26.275 [http-nio-8080-exec-1] INFO [aab461f7cd697f2b,aab461f7cd697f2b,true] c.n.l.DynamicServerListLoadBalancer - DynamicServerListLoadBalancer for client gateway initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=gateway,current list of Servers=[1.1.1.1],Load balancer stats=Zone stats: =[Zone:; Instance count:1; Active connections count: 0; Circuit breaker tripped count: 0; Active connections per server: 0.0;]

**Comment by marcingrzejszczak** [comment]
@jprateekvmware - WDYT https://github.com/spring-cloud/spring-cloud-sleuth/pull/743/files ?
