### ISSUE TITLE
Is it possible to create a new span with multiple parents?

### ISSUE THREAD

**Issue by storni** [spring-cloud/spring-cloud-sleuth#739]
The scenario as follows:

Several requests are buffered and processed in background issuing a single remote call. That is, source spans should be merged into a single one and continue tracing as usual. 

Is there any way to represent this model with Sleuth?

**Comment by adriancole** [comment]
Not at the moment.. joins like this are a bit complex as you end up having
a virtual trace representing the join/buffer. One easy middle ground is to
tag the correlation identifier of the batch. There may be a time that this
is modelable otherwise but not now.
