### ISSUE TITLE
spring.application.name / Logback - need bootstrap or logback config changes

### ISSUE THREAD

**Issue by identigral** [spring-cloud/spring-cloud-sleuth#741]
This is another run at #330 

Issue: if the application name is set in application.yml/.properties via spring.application.name and there's no bootstrap.yml, the app name doesn't show up in the logs. A documented solution via #330 is to mess with Logback config or use bootstrap. While that works, I don't think it's a good solution. For one, the doc recommends bootstrap as an alternative to _custom logback-spring.xml_  . The recommended, idiomatic approach of using Logback with Spring Boot is to roll your own logback-spring.xml and import org/springframework/boot/logging/logback/base.xml. Technically that is _custom_ but it's virtually out of the box config.

Furthermore, the documented solution doesn't work for me with 1.2.5 and Boot 1.5.7.  Defining springProperty in logback-spring doesn't help, I still see 'boostrap' in the logs. Defining spring.application.name in bootstrap.yml does work.

**Comment by marcingrzejszczak** [comment]
The presented solution (https://github.com/spring-cloud/spring-cloud-sleuth/issues/330) is only in case you have a custom `logback-spring.xml` AFAIR. 

I'll update the docs that it's clearly understandable that the `spring.application.name` needs to e in `bootstrap.yml`.
