### ISSUE TITLE
parallelStream() creates new trace for each element in stream

### ISSUE THREAD

**Issue by Panthro** [spring-cloud/spring-cloud-sleuth#744]
Hi there
I don't know if this is desired behaviour or a bug, so I'm opening this issue to double check.

Check the code below with the following information:

- Assume `getAccountWithMovements` send a request using `restTemplate` to another service.
- Only 1 trace is generated, and 1 span for each service call which is OK.

```java
    public ResponseEntity<List<AccountWithMovements>> getAccountsWithMovements() {
        log.info("Request to get accounts with movements");
        return ResponseEntity.ok(accounts.stream()
                .map(this::getAccountWithMovements)
                .collect(Collectors.toList()));
    }
```

Now, if I change the code to use parallelStream instead:
```java
    public ResponseEntity<List<AccountWithMovements>> getAccountsWithMovements() {
        log.info("Request to get accounts with movements");
        return ResponseEntity.ok(accounts.parallelStream()
                .map(this::getAccountWithMovements)
                .collect(Collectors.toList()));

    }
```

4 traces are generated and they are not related

**Comment by marcingrzejszczak** [comment]
Maybe I should update the docs but it's currently (or at the time I wrote the instrumentation) close to impossible to instrument `parallelStream` cause we don't have access to the internal `ExecutorService` AFAIR.

In Brewery I've shown how you can work around this issue:

https://github.com/spring-cloud-samples/brewery/blob/8fc5bdbd6a65306bc3c4d088d20f5d14edbf3af2/brewing/src/main/java/io/spring/cloud/samples/brewery/aggregating/IngredientsAggregator.java#L51-L66

**Comment by Panthro** [comment]
No problem at all, the thing is that I was looking for it and couldn't find anywhere that this was it.

I believe it should be stated somewhere in the README or in the docs just so people are aware of it, I understand that it might be way too complicated or near impossible to instrument it.
