### ISSUE TITLE
Feign + Hystrix don't pass Spans properly

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#75]
## Description

When using Sleuth with Feign the Span information is lost. 

## How to reproduce?

It's enough to run the e2e brewery for SLEUTH and add `Feign` in this line https://github.com/spring-cloud-samples/brewery/blob/master/acceptance-tests/src/test/groovy/io/spring/cloud/samples/brewery/acceptance/SleuthBreweryAcceptanceSpec.groovy#L40

**Comment by marcingrzejszczak** [comment]
This class seems to be where we should plug in `TraceCommand`

```
final class HystrixInvocationHandler implements InvocationHandler {

  private final Target target;
  private final Map<Method, MethodHandler> dispatch;

  HystrixInvocationHandler(Target target, Map<Method, MethodHandler> dispatch) {
    this.target = checkNotNull(target, "target");
    this.dispatch = checkNotNull(dispatch, "dispatch");
  }

  @Override
  public Object invoke(final Object proxy, final Method method, final Object[] args) throws Throwable {
    String groupKey = this.target.name();
    String commandKey = method.getName();
    HystrixCommand.Setter setter = HystrixCommand.Setter
        .withGroupKey(HystrixCommandGroupKey.Factory.asKey(groupKey))
        .andCommandKey(HystrixCommandKey.Factory.asKey(commandKey));

    HystrixCommand<Object> hystrixCommand = new HystrixCommand<Object>(setter) {
      @Override
      protected Object run() throws Exception {
        try {
          return HystrixInvocationHandler.this.dispatch.get(method).invoke(args);
        } catch (Exception e) {
          throw e;
        } catch (Throwable t) {
          throw (Error)t;
        }
      }
    };

    if (HystrixCommand.class.isAssignableFrom(method.getReturnType())) {
      return hystrixCommand;
    }
    return hystrixCommand.execute();
  }

  static final class Factory implements InvocationHandlerFactory {

    @Override
    public InvocationHandler create(Target target, Map<Method, MethodHandler> dispatch) {
      return new HystrixInvocationHandler(target, dispatch);
    }
  }
}
```

The problem is that the class is final ;)

**Comment by adriancole** [comment]
well, I'd not say final is a problem as it is considered good hygiene by
many to limit visibility and prefer composition over inheritance. Moreover,
it encourages engagement on features, while at the same time allowing the
most amount of change to not break public api.

trolling aside..

Why don't we figure out what implementation is actually needed, then decide
if it is a different enough beast to be its own invocation handler or not.

There's some unfinished business in the class you mentioned anyway,
particularly around naming the group and command keys.

here are some notes which might be distracting or helpful..

https://github.com/Netflix/feign/issues/189

**Comment by marcingrzejszczak** [comment]
> well, I'd not say final is a problem as it is considered good hygiene by many to limit visibility and prefer composition over inheritance. Moreover, it encourages engagement on features, while at the same time allowing the most amount of change to not break public api.

:D

>  Why don't we figure out what implementation is actually needed, then decide if it is a different enough beast to be its own invocation handler or not.

From Sleuth's perspective, wherever we're calling `HystrixCommand`, we should in fact call `TraceCommand` to pass the current span and set it in the new, Hystrix thread. This is the first place that I found out that would need it.

So as not to change Feign too much (I don't know what is the release cycle of Feign) we could create a custom `feign.Feign.Builder` - don't know how yet and if that's even possible. From what I see most of things are not extensible / package scoped so we would end up with copy pasting which sucks.

**Comment by marcingrzejszczak** [comment]
@adriancole , @dsyer , @spencergibb - https://github.com/spring-cloud/spring-cloud-sleuth/commit/eea9cce1d2cc8c7ce1b9d0af03c491986acd7e34 this commit is working properly. I don't know if that's the most beautiful of the solutions but it's working ;) 

Tested against: https://github.com/spring-cloud-samples/brewery/commit/e0df6accf79adae0527cce15e6a2547bc3d8bb5b

**Comment by spencergibb** [comment]
That looks like a decent solution. Any changes to `HystrixInvocationHandler` would only buy you a few lines of code saved.

**Comment by marcingrzejszczak** [comment]
The thing that sucks is that `TraceCommandDelegatingContract` is a copy `HystrixDelegatingContract`

**Comment by spencergibb** [comment]
So if `HystrixDelegatingContract` wasn't package private we could use that. I think that sounds like a decent enhancement for feign.

**Comment by marcingrzejszczak** [comment]
+1 - @adriancole WDYT?

**Comment by adriancole** [comment]
SGTM I can cut this immediately https://github.com/Netflix/feign/pull/305

**Comment by adriancole** [comment]
nice work!

**Comment by spencergibb** [comment]
thanks @adriancole!
