### ISSUE TITLE
Wrong span adjustment in ZipkinSpanListener

### ISSUE THREAD

**Issue by tomasz-werminski** [spring-cloud/spring-cloud-sleuth#750]
When there are many instances of SpanAdjuster method "convert" in ZipkinSpanListener calls each one with original Span reference. So all changes on Span made by previous SpanAdjuster are overwritten by current SpanAdjuster call.

To cut a long story short, now is:
```
Span convertedSpan = span;
for (SpanAdjuster adjuster : this.spanAdjusters) {
	convertedSpan = adjuster.adjust(span);
}
```
should be:
```
Span convertedSpan = span;
for (SpanAdjuster adjuster : this.spanAdjusters) {
	convertedSpan = adjuster.adjust(convertedSpan);
}
```

**Comment by marcingrzejszczak** [comment]
Great catch! 

Care for a PR? It's a perfect casd for a fast contribution. If you're interested please apply your pr to 1.2.x branch
