### ISSUE TITLE
Sleuth tracing seems to make assumptions about the type of WebHandler in play

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-sleuth#752]
this results in a ClassCastException. 

you can confirm the issue by looking at the `reservation-service` in https://github.com/joshlong/bootiful-reactive-microservices 

Start `config-service`, `eureka-service` and `zipkin-service` first, of course.

**Comment by marcingrzejszczak** [comment]
Done in https://github.com/spring-cloud/spring-cloud-sleuth/commit/91a2c799de686e44721d0a64a9295c1e6f5a2b51
