### ISSUE TITLE
spring.sleuth.enabled=false causes all related dependencies to fail 

### ISSUE THREAD

**Issue by golonzovsky** [spring-cloud/spring-cloud-sleuth#757]
Beans `TraceRestTemplateInterceptor`, `Tracer` etc are not created when `spring.sleuth.enabled=false`

Therefore all code which Autowire them is failing on startup.

Workaround is to mark them as optional and check for nulls on all invocations which adds lots of boilerplate:
```java
if (traceRestTemplateInterceptor != null) {
	restTemplateBuilder.additionalInterceptors(traceRestTemplateInterceptor);
}
```

```java
private Span createSpan(String spanName) {
	if (tracer == null) {
		return null;
	}
	return tracer.createSpan(spanName);
}
```

```java
} finally {
	if (tracer != null) {
		tracer.close(span);
	}
}
```

and so on.. Maybe cleaner solution would be in case of `spring.sleuth.enabled=false` to create `noop` implementations.

**Comment by marcingrzejszczak** [comment]
The cleanest solution would be that in case of `spring.sleuth.enabled=false` no autoconfiguration that is requiring Sleuth will even be executed (I thought I found them all). Can you provide the configuration classes that got processed even though they shouldn't have? Which version of Sleuth are you using?

**Comment by golonzovsky** [comment]
Uh, sorry, maybe I was not clear in my description. I meant that when I use `Tracer` and `TraceRestTemplateInterceptor` in my code and then pass `spring.sleuth.enabled=false`, than my app is failing during startup.
Maybe its worth mentioning in docs that code dependencies to these classes will fail on this param set to false. Other possible option is to provide `noop` implementations, so application code will not need to wrap all tracing APIs to null-checking wrappers in order to be able to disable Sleuth during startup.

**Comment by marcingrzejszczak** [comment]
If you use `Tracer` in your code and you disable sleuth then no wonder things don't work. I don't agree that any noops should be defaults. Why should they be? All Sleuth related injection will fail if you disable Sleuth.

**Comment by marcingrzejszczak** [comment]
Ping @golonzovsky ?

**Comment by mgroma** [comment]
@marcingrzejszczak,  not sure if my question applies to this discussion but what if i wanted to use the same code that includes `Tracer`and deploy it to two different environments: one that allows tracing (with zipkin collector available) and one that doesn't? if using `spring.sleuth.enabled=false` is not an option then use something like `spring.sleuth.sampler.percentage=0` instead?

**Comment by marcingrzejszczak** [comment]
Exactly. You would use `spring.sleuth.sampler.percentage=0`. I'm closing this issue since @golonzovsky didn't reply

**Comment by golonzovsky** [comment]
Yes, this makes sense. I had wrong impression that I would be able to disable sleuth with `spring.sleuth.enabled=false` even with `Tracer` usage. 

My motivation for noop was to have cleaner code without null-checks and optional dependencies. But this scenario (extensive use of `Tracer` and requirement to disable sleuth with program arg) seems not to be a common use case. 

We can close this one from my side, thanks for feedback.

**Comment by golonzovsky** [comment]
@mgroma maybe you can consider `spring.zipkin.enabled=false` for your case, as with only `spring.sleuth.sampler.percentage=0` user can still initiane export with `X-B3-Flags=1` which will fail if env doesent have zipkin deployed.
