### ISSUE TITLE
We know that zipkin defaults to storing the data into memory, that is, cassandra, and I want to know when he will go to clear the data.

### ISSUE THREAD

**Issue by jidianxiake** [spring-cloud/spring-cloud-sleuth#763]

**Comment by marcingrzejszczak** [comment]
Before you file another issue please read this article about how to file a good issue:

https://wiredcraft.com/blog/how-we-write-our-github-issues/

Another thing is that this is the `spring-cloud-sleuth` project. You're asking about Zipkin. This is the Zipkin repository:

https://github.com/openzipkin/zipkin

You can also try to ask this question either on Stackoverflow or Gitter (https://gitter.im/openzipkin/zipkin)
