### ISSUE TITLE
An invalid span id discards a valid trace id as well

### ISSUE THREAD

**Issue by szerhusenBC** [spring-cloud/spring-cloud-sleuth#768]
Hi,

we've tested Sleuth's behavior for different combinations for given trace and span ids. We found out that a valid trace id will be discarded and newly generated when the given span id is invalid.

Is the intentional behavior? Isn't it better to keep a valid trace id and only generate a new span id?

**Comment by marcingrzejszczak** [comment]
Can you elaborate more on this issue? What combinations have you tested? Which version of sleuth? What does it mean that it will be discarded? Please provide more information, or even better, write a test to show what you mean

**Comment by szerhusenBC** [comment]
Ah OK, sry for the spare informations. We wrote a JUnit test where we're using the RestTestTemplate to request our app. In the request header we're sending the following fields:

"X-B3-TraceId" : "5678"
"X-B3-SpanId" : "invalid"

After that we check the context data in the log event for the tracing fields. In this case we found out that not only the span id was newly generated but also the tracing id. We would expect to keep the trace id because it is valid.

We're using Spring Boot 1.5.8 with "spring-cloud-starter-sleuth".

I can't provide the test because it contains code from my customer. If this information isn't enough, I can write a small test project for that, but I can't say when I find time for **that.**

**Comment by marcingrzejszczak** [comment]
Ok I understand. That's actually a valid behaviour. So the thing is that if you have an invalid id, then an exception is thrown and we swallow it. 

```
public Span joinTrace(SpanTextMap textMap) {
		Map<String, String> carrier = SPAN_CARRIER_MAPPER.convert(textMap);

		boolean debug = Span.SPAN_SAMPLED.equals(carrier.get(Span.SPAN_FLAGS));
		boolean idToBeGenerated = debug && onlySpanIdIsPresent(carrier);
		// we're only generating Trace ID since if there's no Span ID will assume
		// that it's equal to Trace ID - we're trying to fix a malformed request
		if (!idToBeGenerated && traceIdIsMissing(carrier)) {
			// can't build a Span without trace id
			return null;
		}
		try {
			return buildParentSpan(carrier, idToBeGenerated);
		} catch (Exception e) {
			log.error("Exception occurred while trying to extract span from carrier", e);
			return null;
		}
	}
```

That means that we couldn't extract the id from a header. By returning `null` we simulate the case in which there was no tracing information and we generate a new one. That's by design. 

You must prepare a request that has valid tracing information. For both the traceid and the spanid.

**Comment by szerhusenBC** [comment]
OK, I understand. But isn't the design wrong in this case? The most important part is the tracing id to identify the call to a functional process. The span id is only important to get the call stack / chain. By this design you're loosing the whole information. Just asking ...

**Comment by marcingrzejszczak** [comment]
Initially, we would throw an exception when your tracing headers are wrong. Only after some people decided to send arbitrary text in the headers which broke the apps completely, did we decide to swallow the exception and create a new span. We actually didn't want to do that but it seems that some developers do YOLO driven development and push apps to production without testing them first ;) 

If we have a contract on how the tracing headers should look like then we assume that all parties will agree to this contract.

If you don't like the design then you can create your own implementation of the `HttpSpanExtractor`. Just extend the `ZipkinHttpSpanExtractor` and before you call `super`, verify if `spanId` in the headers is correct, if not just overwrite it there.

**Comment by szerhusenBC** [comment]
Ah OK. Thanks for the hint with the ZipkinHttpSpanExtractor.

I like this term 'YOLO-driven development' :D But I have a similar experience in a lot of projects: Deploy to PROD and then test! Luckily I have a better project right now ;)
