### ISSUE TITLE
Zipkin dependency fails to load when upgrading to edgware rc1 version

### ISSUE THREAD

**Issue by reshmik** [spring-cloud/spring-cloud-sleuth#769]
The docs mentioned below states use the spring-cloud-sleuth-starter-zipkin2 which is missing from edgware rc1, name needs to be changed to map to correct starter
http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.3.0.RC1/single/spring-cloud-sleuth.html#_sleuth_with_zipkin_via_rabbitmq_or_kafka

**Comment by marcingrzejszczak** [comment]
Fixed by https://github.com/spring-cloud/spring-cloud-sleuth/commit/b96ca210c393f5121094920697380a61232320b6
