### ISSUE TITLE
Configure Sleuth without SpringBoot

### ISSUE THREAD

**Issue by hth** [spring-cloud/spring-cloud-sleuth#771]
Is there an example without SpringBoot that shows how to configure Sleuth?

**Comment by marcingrzejszczak** [comment]
I have no knowledge of such an example. Maybe theoretically it's possible but until now we've been saying that it would take a lot of time to do it (you'd have to stimulate the auto configuration mechanism yourself). 

Maybe consider using Brave in the meantime?

**Comment by hth** [comment]
Will try Brave. 

On a side note, its rare to use spring boot in production environment. For mass adoptability it would be nice to have different ways of configuring. Startup like us, rarely have time to experiment on things beyond a certain scope other than their own product.

**Comment by spencergibb** [comment]
> its rare to use spring boot in production environment

That's not what we observe.

**Comment by hth** [comment]
@spencergibb Our references are different, but I get your point
