### ISSUE TITLE
@NewSpan annotation on class level is ignored

### ISSUE THREAD

**Issue by golonzovsky** [spring-cloud/spring-cloud-sleuth#772]
Using `@NewSpan` on a class level seems cleaner than marking each method 

Test project provided: https://github.com/golonzovsky/sleuth-zipkin-span-class-issue

See related service code:
https://github.com/golonzovsky/sleuth-zipkin-span-class-issue/blob/master/src/main/java/sleuth/spantest/SpantestApplication.java#L38-L55

ZipkinUI:
![screenshot from 2017-11-06 18-45-13](https://user-images.githubusercontent.com/2477950/32455469-ad154a60-c322-11e7-8b3a-92ab950610f4.png)

JaegerUI:
![screenshot from 2017-11-06 18-41-45](https://user-images.githubusercontent.com/2477950/32455316-302dde9a-c322-11e7-8ee9-122e50b466d0.png)

**Comment by adriancole** [comment]
My suggestion is to consider how web tracing works. We don't annotation
NewSpan on every method, rather there's some policy around it instrumented
in such a way that it is in the background, not the foreground of the app.
So for example, webmvc code doesn't have to be redecorated for tracing to
work or for policy around it to change.

It seems like you are making use of Service annotations, and for lack of a
policy or choice using NewSpan to instrument them. That may be fine, but
you could also consider alternatives if you feel placing annotations on
methods isn't the best vs decoupling that policy. For example, some use
aspectj even others write their own annotations (emplying aspectj to
provide policy for them).

At any rate, I do understand, just want to make sure options are being
considered.

**Comment by marcingrzejszczak** [comment]
For now, I've removed the class target. You can only annotate methods

**Comment by fdirlikli** [comment]
@marcingrzejszczak @adriancole Maybe you should update the documentation as well as it is still mentioning classes and interfaces as valid targets.
