### ISSUE TITLE
TraceAsyncAspect method delegation misbehaves

### ISSUE THREAD

**Issue by golonzovsky** [spring-cloud/spring-cloud-sleuth#774]
TraceAsyncAspect seems to return values from other proxies rather than target executor

Probably [this method](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceAsyncAspect.java#L75-L80) may need a review
 
![image](https://user-images.githubusercontent.com/2477950/32489895-9f32384c-c3b1-11e7-9f69-b370be3e0d06.png)

So Sleuth wrapped task executor is returning [default value](https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/scheduling/concurrent/ThreadPoolTaskExecutor.java#L79) which seems to be value from another proxy. 

Maybe somethig [like this](https://github.com/spring-projects/spring-framework/blob/master/spring-aop/src/main/java/org/springframework/aop/interceptor/AsyncExecutionInterceptor.java#L104-L105) would help

**Comment by marcingrzejszczak** [comment]
That's a perfect suggestion and a great catch! Care for a PR? :) if you're interested please apply it towards 1.2.x branch

**Comment by golonzovsky** [comment]
Yes, I will give it a try, thx

**Comment by marcingrzejszczak** [comment]
@golonzovsky I can't actually replicate this... Have you checked this against the latest Sleuth release? On 10/10 I've added the missing methods to `LazyTraceThreadPoolTaskExecutor`, one of which was `getMaxPoolSize()`...

**Comment by golonzovsky** [comment]
I'm having troubles to reproduce this in isolated test on `1.2.x` as well. 
Trying to find out what is the source for this misbehaving proxy.. 

We are using `v1.2.5.RELEASE`, I will try to use latest `1.2.x` snapshot to check if its still a case

**Comment by golonzovsky** [comment]
Can reproduce with `1.2.6.BUILD-SNAPSHOT`. Will try to create isolated test from original project by chopping other parts..

**Comment by golonzovsky** [comment]
tried with latest snapshot 
```gradle
imports {
   mavenBom 'org.springframework.cloud:spring-cloud-sleuth:1.2.6.BUILD-SNAPSHOT'
}
```
and issue is no longer reproduced with my initial test, thanks! seems #722 fix was a cure.

**Comment by marcingrzejszczak** [comment]
Great! Thanks for the great analysis and help with checking that things work fine
