### ISSUE TITLE
Consider renaming / removing Zipkin starters in Edgware / Finchley

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#785]
The default for Edgware is to use Zipkin 2 - then the default starter should use `zipkin2` and should be called `starter-zipkin`. 

The legacy Zipkin 1 should be called `zipkin1` - since it's not the default.

In Finchley I guess we should remove `zipkin1` support - that's a perfect occasion to do such a change.

cc @snicoll @adriancole @dsyer

**Comment by adriancole** [comment]
if we rename, then we are breaking folks even if mildly. The main reason to name the new version zipkin2 was to just not conflict with the old name. Given a choice, we'd only have one zipkin (easier for start.spring.io, too)

my 2p

**Comment by adriancole** [comment]
you can call old one zipkin-legacy (which will work until 2 years from now when zipkin2 is legacy :P)
