### ISSUE TITLE
Spring cloud sleuth doesn't play nicely with spring security

### ISSUE THREAD

**Issue by will08rien** [spring-cloud/spring-cloud-sleuth#786]
Sample app here: https://github.com/will08rien/sleuth-webflux-security

The log message prints without the span and trace info. Removing the Filter and security library causes these to be added to the context as normal.

**Comment by marcingrzejszczak** [comment]
Thanks for the sample app! Can you pass some logs to this issue anyways?

**Comment by will08rien** [comment]
Logs with security enabled, e.g.

`2017-11-20 09:35:57.872  INFO [-,,,] 29344 --- [     parallel-2] will08rien.sleuth.Controller      
       : Demo log msg                                                                             
`
If security lib and filter removed, logs e.g.
`2017-11-20 09:37:42.135  INFO [-,6651a54788fd2776,6651a54788fd2776,false] 29398 --- [ctor-http-nio-
2] will08rien.sleuth.Controller             : Demo log msg                                        
`                                                                       
Checked in no-sec version of branch of sample repo.
