### ISSUE TITLE
How can I traced rabbitMQ Message

### ISSUE THREAD

**Issue by liangxp** [spring-cloud/spring-cloud-sleuth#792]
How can I traced rabbitMQ Message,2 applications communicate with rabbitMQ,How should I expand?

**Comment by adriancole** [comment]
@liangxp can you comment here? https://github.com/openzipkin/brave/issues/508

in not too long, we'll be rebasing sleuth over the brave api, inheriting anything compatible with it such as RabbitMQ tracing

**Comment by shakuzen** [comment]
If you're using Spring Integration or Spring Cloud Stream to communicate with RabbitMQ, it should already be traced by Sleuth as documented:
http://cloud.spring.io/spring-cloud-sleuth/1.0.x/#_messaging

**Comment by liangxp** [comment]
@shakuzen  Thank you！I will  try it.
