### ISSUE TITLE
Spring Integration - joining existing trace using HTTP between 2 microservices

### ISSUE THREAD

**Issue by alansegar** [spring-cloud/spring-cloud-sleuth#793]
For 2 Spring Boot microservices (Service1 and Service2) which both use Spring Integration to communicate via a HTTP call, I'm finding that when Service1 makes a HTTP call to Service 2, it puts headers on the request in `HeaderBasedMessagingInjector` which use names from `TraceMessageHeaders `e.g. "spanName". When Service 2 receives the request, it uses `ZipkinHttpSpanExtractor `to decide whether to join an existing trace or start a new one. This class makes the decision based on header names from the `Span `class e.g. `Span.SPAN_NAME_NAME = "X-Span-Name"`. As these names are different, it doesn't find the existing trace and starts a new one.
I was expecting Service 1 and Service 2 to automatically form a combined trace but I've had to add a custom HTTP span extractor in order to achieve this (as described at https://cloud.spring.io/spring-cloud-sleuth/multi/multi__customizations.html). Is this the correct way to use Spring Cloud Sleuth with Spring Integration or is there some other way to achieve this without having to write a custom HTTP span extractor?

Service 1 has a gateway which triggers a HTTP call to Service 2 when a method is called on an interface. The `request-channel` on that method is linked to an HTTP `outbound-gateway` which makes a GET request.

```
import org.springframework.cloud.sleuth.Span;
import org.springframework.cloud.sleuth.SpanTextMap;
import org.springframework.cloud.sleuth.instrument.messaging.TraceMessageHeaders;
import org.springframework.cloud.sleuth.instrument.web.HttpSpanExtractor;
import org.springframework.cloud.sleuth.util.TextMapUtil;

import java.util.Map;

public class CustomHttpSpanExtractor implements HttpSpanExtractor {

	@Override public Span joinTrace(SpanTextMap carrier) {
                Map<String, String> map = TextMapUtil.asMap(carrier);
                long traceId = Span.hexToId(map.get(TraceMessageHeaders.TRACE_ID_NAME));
                long spanId = Span.hexToId(map.get(TraceMessageHeaders.SPAN_ID_NAME));
                long parent = Span.hexToId(map.get(TraceMessageHeaders.PARENT_ID_NAME));
                String processIdName = map.get(TraceMessageHeaders.PROCESS_ID_NAME);
                // TODO Find out if there are other fields that are also required
                Span.SpanBuilder builder = Span.builder()
				.traceId(traceId)
				.spanId(spanId)
				.parent(parent)
				.processId(processIdName);

		// build rest of the Span
		return builder.build();
	}
}
```

**Comment by marcingrzejszczak** [comment]
Can you present the integration configuration? Also can you define from your observation which classes are called when `HeaderBasedMessagingInjector`, `HeaderBasedMessagingExtractor`, `ZipkinHttpSpanExtractor`, `ZipkinHttpSpanInjector` ? 

In general, the name doesn't matter. Span id and Trace id matters

**Comment by alansegar** [comment]
This is the integration configuration on the Service 1 side. What I've referred to as Service 2 above is servicethree in this config:
```
    <int:channel id="servicethree.retrieveByIdChannel" />

    <int:gateway id="sevicethree.client"
                 service-interface="com.example.servicethree.client.ServiceThree">
        <int:method name="retrieveById" request-channel="servicethree.retrieveByIdChannel" />
    </int:gateway>

    <int-http:outbound-gateway url="http://localhost:8083/service-three/retreivebyid/{id}"
                               request-channel="servicethree.retrieveByIdChannel"
                               http-method="GET"
                               expected-response-type="java.lang.String">
        <int-http:uri-variable name="id" expression="payload" />
    </int-http:outbound-gateway>
```
and the config on the Service 2 side (again called servicethree in this config rather than Service 2):
```
    <bean id="serviceThree" class="com.example.servicethree.ServiceThreeImpl" />

    <int:channel id="retreiveByIdChannel" />

    <int-http:inbound-gateway id="retreiveByIdGateway"
            request-channel="retreiveByIdChannel"
            path="/retreivebyid/{id}"
            payload-expression="#pathVariables.id"
            supported-methods="GET" />

    <int:service-activator input-channel="retreiveByIdChannel"
                           ref="serviceThree"
                           method="retrieveById" />
    
    <bean id="customHttpSpanExtractor" class="com.example.servicethree.CustomHttpSpanExtractor" />
    
```

**Comment by marcingrzejszczak** [comment]
Ah I think I know why. You have to pass a rest template bean to the http outbound gateway. Otherwise a new rest template instance will be created that is not instrumented

**Comment by alansegar** [comment]
@marcingrzejszczak Thanks for the very quick response. I'll give that a try now.

**Comment by marcingrzejszczak** [comment]
Ok! Once you've confirmed it just ping me back so that I can (hopefully) close this

**Comment by alansegar** [comment]
@marcingrzejszczak Thanks again for solving this. I've confirmed that adding the following to Service 1 means that I no longer need to use `CustomHttpSpanExtractor`:

`<bean id="restTemplate" class="org.springframework.web.client.RestTemplate" />`

**Comment by marcingrzejszczak** [comment]
Great to hear that!
