### ISSUE TITLE
Where there are examples or APIS for Spring Cloud Sleuth integrates with Spring Integration

### ISSUE THREAD

**Issue by liangxp** [spring-cloud/spring-cloud-sleuth#796]
I want to traced rabbitMQ by Spring Cloud Sleuth ,by there [url](http://cloud.spring.io/spring-cloud-sleuth/1.0.x/#_messaging) I don't know how to do it，Do you have a more detailed description that can help me，Thanks！

**Comment by marcingrzejszczak** [comment]
You can read the code.

Here are the message headers we're using - https://github.com/spring-cloud/spring-cloud-sleuth/blob/v1.3.0.RELEASE/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceMessageHeaders.java 

This is how we create a span from a message - https://github.com/spring-cloud/spring-cloud-sleuth/blob/v1.3.0.RELEASE/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/HeaderBasedMessagingExtractor.java

This is how we fill out a message from a span - https://github.com/spring-cloud/spring-cloud-sleuth/blob/v1.3.0.RELEASE/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/HeaderBasedMessagingInjector.java
