### ISSUE TITLE
How can I get messages sent to Kafka by Zipkin？

### ISSUE THREAD

**Issue by liangxp** [spring-cloud/spring-cloud-sleuth#798]
I wanted to analyze the log data, but I didn't find the code to receive the Zipkin message, and the message sent the spring-cloud-sleuth-zipkin-stream I used.If you can provide the code that receives sleuth to receive Kafka, or tell me how to receive the message and convert it to the right object, I'll be very grateful to you

**Comment by marcingrzejszczak** [comment]
Which version of Sleuth are you referring to? 

If you're talking about the `sleuth-stream` support then this is how the spans look like - https://github.com/spring-cloud/spring-cloud-sleuth/blob/v1.3.0.RELEASE/spring-cloud-sleuth-stream/src/main/java/org/springframework/cloud/sleuth/stream/Spans.java . The messages are sent to the `sleuth` topic in Kafka so you'd have to search for the messages there.

However, with Edgware this approach is deprecated and we suggest that you use the Zipkin 2, native Kafka approach (e.g. https://github.com/openzipkin/zipkin/tree/master/zipkin-collector/kafka)

**Comment by liangxp** [comment]
The version of the Zipkin I used is 1.28.0
The version of the sleuth I used is 1.2.4
code like this:
`@KafkaListener(topics = "topic_zipkin_sleuth",group = "fdsfdsfd")
	public void test(Message<?> message){
		System.out.println(new String((byte[]) message.getPayload()));
	//result like this �contentType   N"application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans"spanId   "60fb3bc41c406981"spanTraceId   "60fb3bc41c406981"spanSampled   "0" org.springframework.cloud.sleuth.stream.Hos�172.16.16.9��Vmicro-zuul-web-servic�java.util.LinkedLis�org.springframework.cloud.sleuth.Spa�java.util.concurrent.ConcurrentHashMa� ���ʄX�����ʄXjava.util.concurrent.ConcurrentLinkedQueu�org.springframework.cloud.sleuth.Lo�c����ʄXc��ʄXhttp:/gateway/gateway/gateway/apiGroup/listByLeve�java.util.ArrayLis��������¹   ���ʄX�����ʄXs����ʄXs��ʄX    �������¹귈����spring.instance_i�node90:micro-zuul-web-service:555��������¹ ���٪���p�������http.status_cod�20�l�zuu�node90:micro-zuul-web-service:555�http.pat�/apiGroup/listByLeve�http.ur�"http.metho�POS��������¹ 
	}`
spring kafka config 
`spring.kafka.bootstrap-servers=172.16.16.212:9092
spring.kafka.consumer.group-id=fdsfdsfd
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.consumer.auto-offset-reset=earliest
`
