### ISSUE TITLE
A question rather than an issue

### ISSUE THREAD

**Issue by larry13767** [spring-cloud/spring-cloud-sleuth#8]
I was wondering what the roadmap on this is.  I am interested in using this to solve an architectural condition that I have in my system

**Comment by dsyer** [comment]
Things are moving fast. The goal is to get a milestone out early September. If Zipkin stabilizes we could be releasing something no too long after that. All help (especially kicking the tyres and giving feedback) greatly appreciated. There's a gitter room for spring-cloud if you want to chew the fat (https://gitter.im/spring-cloud/spring-cloud).
