### ISSUE TITLE
Trace tags are not accounting for parameterized URLs

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#802]
https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-spring-legacy/src/main/java/io/micrometer/spring/web/servlet/WebMvcTags.java#L68

**Comment by jkschneider** [comment]
@marcingrzejszczak [Here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/servlet/WebMvcTags.java).

**Comment by marcingrzejszczak** [comment]
related to https://github.com/openzipkin/brave/pull/602

**Comment by marcingrzejszczak** [comment]
Done through https://github.com/spring-cloud/spring-cloud-sleuth/pull/878
