### ISSUE TITLE
How can I get messages sent to Kafka by sleuth ？

### ISSUE THREAD

**Issue by liangxp** [spring-cloud/spring-cloud-sleuth#804]
The version of the Zipkin I used is 1.28.0
The version of the sleuth I used is 1.2.4
code like this:
`@KafkaListener(topics = "topic_zipkin_sleuth",group = "fdsfdsfd")
	public void test(Message<?> message){
		System.out.println(new String((byte[]) message.getPayload()));
	}`

result like this 
�contentType   N"application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans"spanId   "60fb3bc41c406981"spanTraceId   "60fb3bc41c406981"spanSampled   "0" org.springframework.cloud.sleuth.stream.Hos�172.16.16.9��Vmicro-zuul-web-servic�java.util.LinkedLis�org.springframework.cloud.sleuth.Spa�java.util.concurrent.ConcurrentHashMa� ���ʄX�����ʄXjava.util.concurrent.ConcurrentLinkedQueu�org.springframework.cloud.sleuth.Lo�c����ʄXc��ʄXhttp:/gateway/gateway/gateway/apiGroup/listByLeve�java.util.ArrayLis��������¹   ���ʄX�����ʄXs����ʄXs��ʄX    �������¹귈����spring.instance_i�node90:micro-zuul-web-service:555��������¹ ���٪���p�������http.status_cod�20�l�zuu�node90:micro-zuul-web-service:555�http.pat�/apiGroup/listByLeve�http.ur�"http.metho�POS��������¹ 

spring kafka config 

`spring.kafka.bootstrap-servers=172.16.16.212:9092
spring.kafka.consumer.group-id=fdsfdsfd
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.consumer.auto-offset-reset=earliest

**Comment by adriancole** [comment]
are you able to upgrade to latest sleuth v1.3.0.RELEASE? We now support
zipkin-compatible kafka

**Comment by liangxp** [comment]
@adriancole  yes ,I can upgrade to latest sleuth v1.3.0.RELEASE,Can you give me an example of 3 or a document！

**Comment by liangxp** [comment]
@adriancole I upgrade to 1.3.0,also like this `�contentType   N"application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans"spanId   `

**Comment by marcingrzejszczak** [comment]
@liangxp what Adrian has mentioned is that you upgrade the whole application to use Sleuth in version 1.3.0. If you read the documentation (http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.3.0.RELEASE/single/spring-cloud-sleuth.html#_sleuth_with_zipkin_via_rabbitmq_or_kafka) it should be enough to understand how to use the Zipkin compatible kafka client.
