### ISSUE TITLE
Instrumentation of Spring Cloud Gateway

### ISSUE THREAD

**Issue by tine2k** [spring-cloud/spring-cloud-sleuth#806]
As [Spring Cloud Gateway](http://cloud.spring.io/spring-cloud-gateway/) is set to replace [Zuul](https://github.com/Netflix/zuul), Sleuth should integrate with it as it does with Zuul.

**Comment by marcingrzejszczak** [comment]
Doesn't it work with Gateway at all?

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-gateway/issues/20

**Comment by tine2k** [comment]
No, no support at all.
