### ISSUE TITLE
How to Custom RabbitMQ or Kafka Topic

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-sleuth#817]
I use Spring Cloud Edgware, and I want to use sleuth with zipkin.
I follow the doc here: <http://cloud.spring.io/spring-cloud-static/Edgware.RELEASE/single/spring-cloud.html#_sleuth_with_zipkin_via_rabbitmq_or_kafka> .
And then It works.

The default topic is `zipkin` ,I wonder how to custom it.
What's more over, How to change the MQ address?
Could you help me?

@royclarkson @marcingrzejszczak @adriancole

**Comment by marcingrzejszczak** [comment]
On the client side 

- we respect all the default RabbitMq (https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-messaging.html#boot-features-rabbitmq) / Kafka (https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-messaging.html#boot-features-kafka) properties.
- to change the Rabbit topic use `spring.zipkin.rabbitmq.queue`
- to change the Kafka topic use `spring.zipkin.kafka.topic`

On the Zipkin server side:

- here is how you can tweak stuff for Rabbit https://github.com/openzipkin/zipkin/tree/master/zipkin-collector/rabbitmq#configuration
- here is how you can tweak stuff for Kafka https://github.com/openzipkin/zipkin/tree/master/zipkin-autoconfigure/collector-kafka10#configuration

**Comment by eacdy** [comment]
@marcingrzejszczak I see. Thanks a lot!
