### ISSUE TITLE
sometimes one uri but two traces 

### ISSUE THREAD

**Issue by Jaware** [spring-cloud/spring-cloud-sleuth#820]
[Bug report]
 sleuth version is  **1.2.4**, most of the times the result is one span ,but in some cases there were two spans,very confusing.
![image](https://user-images.githubusercontent.com/3970304/34475480-76d1bed0-efc7-11e7-841b-85e2c38c8f91.png)

**Comment by marcingrzejszczak** [comment]
Please upgrade to `1.2.6` check if the problem still is there. If it's there please provide sample code to show what exactly you're doing
