### ISSUE TITLE
Tracing is not working with spring-cloud/spring-cloud-stream defined @input channels

### ISSUE THREAD

**Issue by lchayoun** [spring-cloud/spring-cloud-sleuth#821]
Spring Cloud Sleuth is using TraceChannelInterceptor in order to continue the spans through the messaging system.
TraceChannelInterceptor is using the ExecutorChannelInterceptor#beforeHandle method.
If the channel is not an ExecutorSubscribableChannel tracing is not possible along with other capabilities regarding the parsing of incoming messages headers.

Currently the only way to handle messages before the method annotated with "@streamlistener" is called is on PollableChannels with the "postReceive" method.
When using SubscribableChannel this is possible only using the ExecutorChannelInterceptor#beforeHandle method.
But ExecutorSubscribableChannel is not supported by the "@input" annotation factory,

spring-cloud/spring-cloud-stream#1173

**Comment by artembilan** [comment]
I think the situation is like `TraceChannelInterceptor` doesn't support `AbstractMessageChannel` from Spring Integration. I guess the simplest test would be don't worry about SCSt but just try to apply `TraceChannelInterceptor` to the `DirectChannel` and verify afterward.

There is a `ThreadStatePropagationChannelInterceptor` abstraction in Spring Integration to consider for this situation.

The other problem that this interceptor doesn't support `PollableChannel` as well...

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/572 will fix all of this or die trying
