### ISSUE TITLE
RestTemplate: register Trace interceptor *first* in the chain

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-sleuth#822]
It would be nice if the `TraceRestTemplateInterceptor` appears first in the list of registered interceptors. This way any log statement generated by other interceptors in the chain would benefit from the trace/span ids in the logs.

It seems this could easily be done by using a `RestTemplateCustomizer` instead of current the `BeanPostProcessor` approach. The former seems to take into account the ordering specified by `@Order` annotations or `Ordered` interface implemented by the interceptor.

What you think ?

**Comment by marcingrzejszczak** [comment]
I don't mind. 

The BPP is used for the `RestTemplateBuilder` only. So that when you build the `RestTemplate` it already has the customizer. 

What we could do to fix the problem with existing `RestTemplate`s is this

```java
@Configuration
		protected static class TraceInterceptorConfiguration {

			@Autowired(required = false)
			private Collection<RestTemplate> restTemplates;

			@Autowired
			private TraceRestTemplateInterceptor traceRestTemplateInterceptor;

			@PostConstruct
			public void init() {
				if (this.restTemplates != null) {
					for (RestTemplate restTemplate : this.restTemplates) {
						List<ClientHttpRequestInterceptor> interceptors = new ArrayList<ClientHttpRequestInterceptor>(
								restTemplate.getInterceptors());
						interceptors.add(this.traceRestTemplateInterceptor);
						restTemplate.setInterceptors(interceptors);
					}
				}
			}
		}
```

we could set the `TRTInterceptor` as the first in that list. WDYT?

**Comment by brenuart** [comment]
I propose to have it first in the list, correct.

Regarding the use of BPP vs. RestTemplateCustomizer - I don't see why the BPP is preferred. Other things are available only when the RestTemplate is obtained from the builder. This seems to be the recommended way of construction a RestTemplate in SpringBoot - am I wrong ?

I wouldn't go for the approach illustrated in your code snipped above. It requires that the RestTemplate instance is available in the context. What if I create one locally from a builder and don't register in in the context? IMHO the current and/or customizer approaches are better.

**Comment by marcingrzejszczak** [comment]
> Regarding the use of BPP vs. RestTemplateCustomizer - I don't see why the BPP is preferred. Other things are available only when the RestTemplate is obtained from the builder. This seems to be the recommended way of construction a RestTemplate in SpringBoot - am I wrong ?

Yeah, maybe you're right. I'll give it a second thought.

> I wouldn't go for the approach illustrated in your code snipped above. It requires that the RestTemplate instance is available in the context. What if I create one locally from a builder and don't register in in the context? IMHO the current and/or customizer approaches are better.

This approach is already there since forever.

**Comment by brenuart** [comment]
> This approach is already there since forever.

Damn - I stopped reading at `TraceRestTemplateBuilderBPP` :(
But wait - what if RestTemplates found in the context were created by a RestTemplateBuilder you already instrumented? Is that possible at all?

**Comment by marcingrzejszczak** [comment]
> But wait - what if RestTemplates found in the context were created by a RestTemplateBuilder you already instrumented? Is that possible at all? (just asking here...)

No, cause you have to call `build`. You typically inject a builder via constructor and then call `build`.

**Comment by brenuart** [comment]
True.
Regarding `TraceInterceptorConfiguration` - you should then make sure your BPP is invoked last, otherwise other interceptors registered with another BPP may come after. No?

**Comment by marcingrzejszczak** [comment]
I'll have to think about this. Currently, I'm doing #711 so I can't fully focus on this.

**Comment by brenuart** [comment]
No worries. Thanks for your - quick - support ;-)

**Comment by marcingrzejszczak** [comment]
BTW why would you want to add tracing interceptors to `TestRestTemplate` ? That sounds insane :P

**Comment by brenuart** [comment]
Hmm... I wanted during test cases but switched to standard RestTemplate instead. I needed to verify our error handling mechanism and wanted to assert that the error response had a reference to the current trace...
I recon this is an edge case and I’m happy with the current solution.

**Comment by marcingrzejszczak** [comment]
Great to hear that! :)
