### ISSUE TITLE
where i can get spring-cloud-sleuth-zipkin-stream project code?

### ISSUE THREAD

**Issue by pickmonster** [spring-cloud/spring-cloud-sleuth#826]
i want use spring-cloud-sleuth-zipkin-stream project code, so where i can get it? Thanks!!!

**Comment by marcingrzejszczak** [comment]
It's in the `1.3.x` branch (https://github.com/spring-cloud/spring-cloud-sleuth/tree/1.3.x/spring-cloud-sleuth-zipkin-stream) and we write about it in the documentation
