### ISSUE TITLE
Sleuth and Zookeeper ServiceID understanding

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#83]
When running e2e tests it turned out that when using the https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/DiscoveryClientEndpointLocator.java#L48 - the `serviceId` for Zookeeper is a UUID. Not the application name. That's why the e2e tests fail because they're expecting a name like "presenting" and not ID.

**Comment by adriancole** [comment]
I suppose the most important question that can steer us is.. Is
ServiceInstance.serviceId in spring-cloud-zookeeper being a UUID a bug
or a feature?

If a feature, I suppose the action to take would be to find a field
that is a better label... maybe ServiceInstance.host? or maybe a
.metadata entry? If a feature, we should also clarify javadoc of
ServiceInstance.serviceId (in spring-cloud-commons) something like:

"<p> This is not necessarily a friendly name for the service. Ex in
some implementations, this could be a UUID. Use {@link #foo} for a
human-readable label of the service."

If it is a bug to have a non-friendly serviceId, then we'd open an
issue in https://github.com/spring-cloud/spring-cloud-zookeeper to
change it to a label.

Thoughts?

**Comment by marcingrzejszczak** [comment]
As we talked on Gitter I agree that we'll end up with some sort of policies that can be tweaked

**Comment by marcingrzejszczak** [comment]
It turned out that the issue was in Zookeeper - https://github.com/spring-cloud/spring-cloud-zookeeper/commit/de25a0973d08d1555ed06a1ee3e974e2db4b69eb
