### ISSUE TITLE
How to configure @FeignCient with an HTTPS url (non-Eureka)?

### ISSUE THREAD

**Issue by yngwietiger** [spring-cloud/spring-cloud-sleuth#837]
Hi,

I have a feign client defined like:

`@FeignClient(name = "authserverTokenService", path="/authserver", url="${authserver.server}", configuration = AuthServerTokenServiceConfig.class)`

The authserver service is not registered with Eureka. We specify the url in a properties file.

If I put in my properties file:

`authserver.server=localhost:8087`

it resolves correctly to http://localhost:8087 (looks like FeignClientsRegistrar adds the protocol?).

But beyond my local dev box, it needs to hit an HTTPS service.

If I try:

`authserver.server=https://localhost:8087 `

it gives me an error, because the final host/url is: http://https://localhost:8087

I've tried putting the URL into the name attribute (per some other threads that I saw), but then I get:

```
0:31:54.651 [RMI TCP Connection(2)-127.0.0.1] ERROR [fweb,,,] o.s.boot.SpringApplication - Application startup failed (SpringApplication.java:771) 
java.lang.IllegalStateException: Service id not legal hostname (${authserver.listOfServers})
	at org.springframework.util.Assert.state(Assert.java:70)
	at org.springframework.cloud.netflix.feign.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:238)
	at org.springframework.cloud.netflix.feign.FeignClientsRegistrar.registerFeignClient(FeignClientsRegistrar.java:181)
```

i.e. it doesn't seem to like properties in the name attribute.

**What is the correct way to configure an @FeignClient with a property-based HTTPS url?**

Thanks in advance,

yngwietiger

**Comment by marcingrzejszczak** [comment]
Please file this issue in https://github.com/spring-cloud/spring-cloud-netflix . It has nothing to do with Sleuth

**Comment by yngwietiger** [comment]
Ooops, sorry. Will do.
