### ISSUE TITLE
Trace id is lost when using dynamically bound destinations

### ISSUE THREAD

**Issue by erdemedeiros** [spring-cloud/spring-cloud-sleuth#838]
The current trace id is maintained in the consumer when the producer uses statically bound destination. e.g. `output.send(message)`. However, a new trace id is generated for the consumer when the producer uses dynamically bound destinations. e.g. `resolver.resolveDestination(channelName).send(message)`

*Spring cloud version:* Finchley.M5

**How to reproduce**: use this [sample application](https://github.com/erdemedeiros/trace-id-issue-reproducer).

It might be related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/821.

**Comment by Salaboy** [comment]
This is blocking us to have correct traces when we use dynamically resolved destinations.

**Comment by marcingrzejszczak** [comment]
Issue for `2.0.x` will be fixed in Spring Cloud Stream
