### ISSUE TITLE
Use a BeanPostProcessor in TraceInterceptorConfiguration to register the interceptor in RestTemplate beans

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-sleuth#846]
`TraceInterceptorConfiguration` is responsible to add instrumentation to RestTemplate instances found in the application context (see code [here](https://github.com/spring-cloud/spring-cloud-sleuth/blob/1.3.x/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientAutoConfiguration.java#L71-L100)). That inner config class holds an @Autowired collection of RestTemplates and process them on @PostConstruct.

With this strategy, other beans may already have their RestTemplate dependency injected when the instrumentation occurs - hence "altering" the instance behind the scenes. 
This may have strange results on those that took some decisions after inspection or early use of the RestTemplate they received. 
For instance, I have seen cases where people grab the `RequestFactory` from the RestTemplate just after properties are set and got caught later because another was set later by a mechanism similar to the one used here by Sleuth.

Although I was "against" in [gh822](https://github.com/spring-cloud/spring-cloud-sleuth/issues/822), I recon using a `BeanPostProcessor` in this case is probably a better solution: RestTemplates would be fully instrumented at the time they are injected into @Autowired fields...

What do you think ?

**Comment by marcingrzejszczak** [comment]
Can you present a test sample that can replicate the problem?

**Comment by brenuart** [comment]
Sample test project: [gh846.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/1691783/gh846.zip)

Attached is a sample Initialzr project with a simple test case illustrating the issue.
A simple `mvn test` is enough.

The test case contains a bean with a `@Autowired` RestTemplate. It compares the number of interceptor registered in the RestTemplate at `@PostConstruct` and after the app is fully initialized. It fails if the two counts are not the same - which illustrates the issue described in this case.
