### ISSUE TITLE
Add some Samplers

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#85]
We need at least a configurable fixed percentage-based sampler, and some docs on how to use it to control span data collection. It could be used  with `@RefreshScope` for instance to drive dynamic sampling based on traffic rates.

Also probably useful would be a way to force export of span data by adding a special header. That could even be the default sampler.

**Comment by dsyer** [comment]
See also #56

**Comment by adriancole** [comment]
Some context on zipkin and how it deals with the second part of this issue:

A sampled boolean propagation field is commonly used. This is often set
after a sampling policy applies, and propagates in HTTP as a header (to
avoid next hop on sampled=false mistakingly creating a new root span)

That's different than a debug flag, at least in zipkin, where it is a hint
made at the instrumentation point (ex the tracing api) to say make sure
this always passes. This lives in the span as opposed to propagation
context, so processed at collection time.

I think this topic came up in open tracing, too. I will update my comment
with links later.

**Comment by adriancole** [comment]
On the first part (sampling algo), the dapper paper has a commonly
implemented approach, which is to hash the trace id as a part of the
collection-side sampling function. This allows us to ensure we drop an
entire trace vs parts of it (as partial traces are misleading and can be
worse than no traces).

http://research.google.com/pubs/archive/36356.pdf

IIRC, sleuth ids are UUIDs encoded as a string. We can either hash the
string or retain the 128bits behind it and use that as an input to get the
same effect. For example, htrace split the 128bits into two accessors
(upper and lower). This would allow a numeric function to be applied (note
afaik htrace don't have a collection-side sampler, which may explain why
they don't use the span id as an input to their sampling implementations)

https://github.com/apache/incubator-htrace/blob/master/htrace-core4/src/main/java/org/apache/htrace/core/SpanId.java

The zipkin-java project is closer to dapper where the trace ids are 64bit
numbers. I will add a compatible impl there, soon.

**Comment by adriancole** [comment]
I took a look at how sampler was used (which is a little more complex than necessary due to #86).

Unless I'm mistaken, the sampling function applies regardless of whether a span is a parent or child. This implies that a sampler impl should take some care to avoid sparse traces. For example, we should either document or attempt to avoid losing a part of a trace because the sampler of the parent had a different answer than the child.

**Comment by gauravrmazra** [comment]
htrace has CountSampler (every N calls) and ProbabilitySampler (some request based on threshold) for instance. Is it a good add-on?

**Comment by adriancole** [comment]
Good suggestion to look at other projects :)

We have actually looked at these approaches.. count-based has some issues
and probability isn't idempotent. Marcin has work in progress on a solution
here #90, it is borrowing an algorithm from an existing sampler and
extending it to 128 bits. Much of the context about the various sampling
approaches be found here.

https://groups.google.com/d/msg/distributed-tracing/E0yh_3fept0/DQiRgVqXCAAJ
