### ISSUE TITLE
No traces/spans when logs executed within flatMap 

### ISSUE THREAD

**Issue by jmilkiewicz** [spring-cloud/spring-cloud-sleuth#850]
Hey

This is a little based on https://github.com/spring-cloud/spring-cloud-sleuth/issues/811
Seems like the fix works but not fully :(
I created a sample app [https://github.com/jmilkiewicz/sleuth-issue](https://github.com/jmilkiewicz/sleuth-issue) that shows **lack of  trace/spans** in logs when logging statements are located _within_

`Mono#flatMap `
or 
`Flux#flatMap`

The example i prepared is pretty simply. It has 2 endpoints:

- /noFlatMap which merges 3 Mono into flux and simply return it
- /withFlatMap which first merges 3 Mono into flux to then flatMap it

For the first endpoint logs have span/traces, which is expected and works perfect.

For the second endpoint logs have traces/spans **till** 'flatMap'. Any logs executed **within** 'flatMap' miss both trace/span Ids

**Comment by sbueringer** [comment]
#813
