### ISSUE TITLE
SleuthWebProperties.DEFAULT_SKIP_PATTERN ignores "management.context-path"

### ISSUE THREAD

**Issue by lchayoun** [spring-cloud/spring-cloud-sleuth#851]
when setting `management.context-path`, the skip patterns doesn't take that into account

```java
	public static final String DEFAULT_SKIP_PATTERN =
			"/api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/trace|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream";
```

**Comment by marcingrzejszczak** [comment]
It does

https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java#L57-L89

**Comment by lchayoun** [comment]
Thanks! hadn't noticed that, I am using the `Edgware.SR2` Release train and I see that `TraceHttpAutoConfiguration#httpSpanExtractor` is not using the `SkipPatternProvider`:

https://github.com/spring-cloud/spring-cloud-sleuth/blob/1.3.x/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceHttpAutoConfiguration.java#L49-L53

any reason for it?

**Comment by marcingrzejszczak** [comment]
Yeah, most likely the reason is that I'm blind. 🤦‍♂️ I'll double check what's going on there
