### ISSUE TITLE
`TraceWebClientAutoConfiguration` needs to remove injection of RestTemplates and @PostConstruct init `method`

### ISSUE THREAD

**Issue by ezraroi** [spring-cloud/spring-cloud-sleuth#852]
The new code in 1.3.2 is using the `Customizer` pattern but the code that injects all rest templates and adds the interceptor was not deleted.

This is making that applications will not be able to create `RestTemplate` bean using the `RestTemplateBuilder` as a circular dependency is now created:
![image](https://user-images.githubusercontent.com/5808368/36072414-fd826144-0f27-11e8-93bb-dc4e04e72659.png)

`CloudRestTemplateAutoConfigure:`
```java
@Configuration
public class CloudRestTemplateAutoConfigure {

    @LoadBalanced
    @Bean
    public RestTemplate loadBalanced(RestTemplateBuilder restTemplateBuilder) {
        return restTemplateBuilder.build();
    }

    @Bean
    @Primary
    public RestTemplate restTemplate(RestTemplateBuilder restTemplateBuilder) {
        return restTemplateBuilder.build();
    }
}
```

Also looks like the `RestTemplateCustomizer traceRestTemplateCustomizer() ` needs to have `LOWEST_PRECEDENCE` and not `HIGHEST_PRECEDENCE` as you want to make sure you add it as the first customizer and no other customizer is adding to the start of the list after your code

**Comment by ezraroi** [comment]
You can find a simple project that was generated with start,spring.io with Slueth and Web only and reproduces it.

https://github.com/ezraroi/SpringSluethRestTemplateIssue

**Comment by marcingrzejszczak** [comment]
🤦‍♂️

**Comment by ezraroi** [comment]
Looks like the code that adds the interceptors to a RestTemplate created with `new` will stop working... as RestTamplate should be created with the `RestTemplateBuilder`. 

Tried to fix the code in my fork and looks like you have tests that tests that tracing is working with RestTemplate not created by the builder

**Comment by marcingrzejszczak** [comment]
I guess, I've fixed it. Also I've updated a test to prove that it works with 2 RestTemplates at a time, one created via builder and one via `new`. https://github.com/spring-cloud/spring-cloud-sleuth/commit/d62756e3b116fa8dc818a6388043c46c773c8e69

**Comment by brenuart** [comment]
Any idea of when `1.3.3.RELEASE` is gona happen ?

**Comment by marcingrzejszczak** [comment]
Hopefully soon... until then just disable `spring.sleuth.web.client.enabled: false`

**Comment by brenuart** [comment]
We'll wait until then... maintaining workarounds is too expensive (unless it takes months to get the new release ;-)

**Comment by marcingrzejszczak** [comment]
hehehe, no, I think this one will be much sooner ;)

**Comment by brenuart** [comment]
Will it be part of an `Edgware.SR3` or an independent release of "Sleuth only" ?

**Comment by marcingrzejszczak** [comment]
part of `Edgware.SR3`

**Comment by brenuart** [comment]
Damn! You guys are going too fast...

**Comment by brenuart** [comment]
Any ETA update for `Edgware.SR3` ?

**Comment by marcingrzejszczak** [comment]
https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-sleuth-core/ it's there. We will announce it today I guess.

**Comment by brenuart** [comment]
Cool. Can’t wait for it… 😉
