### ISSUE TITLE
Spring cloud function + sleuth

### ISSUE THREAD

**Issue by solidgains** [spring-cloud/spring-cloud-sleuth#853]
I did a search for spring cloud function in here, nothing popped up.

Currently my team is facing an issue, our architecture consist of spring integration apps, aws lambdas, and spring boot mvc apps in ecs.

Our goal is to trace everything, through lambdas, etc... I have tried adding spring cloud sleuth to my spring cloud function app, but spans aren't being populated, but the app name is. 

Is spring cloud sleuth supposed to work out of the box with spring cloud function?

**Comment by marcingrzejszczak** [comment]
We haven't yet invested our time in integration with Spring Cloud Function. Can you create a sample of your function and describe how you work with it?

**Comment by solidgains** [comment]
Well, so far, Ive been playing with simple hello world world type of function. Similar to one of the existing function demo’s then I tried adding sleuth to see if it worked. 

In practice, I would primarly deploy the function to aws lambda, and have it run locally. Some lambdas would be event driven and others, rest web services. Let me kmow if this answers your question.
