### ISSUE TITLE
New SPAN created for handling on `/error` when request does not have span header

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-sleuth#859]
Uncaught exceptions are catched by Tomcat and forwarded to `/error` for handling by Spring's default `BasicErrorController`.

It appears the span logged from within the `BasicErrorHandler` (and anywhere in the handling chain after the TraceFilter) *may* not refer to the same span as from within the handler that threw the uncaught exception. It actually depends on whether the original request had span headers on it or not:
- if span headers are present and the request is parent of an ongoing trace, span stays the same in `/error`
- if no span header is present, everything appears as if two spans were created: one first the original attempt at invoking the handler, a second for the forward to `/error`.

This behaviour is observed with SpringCloud `Edgware.SR2`.
Things are different however with `Finchley.M6`: the same span is reported in both cases.

I have attached two sample applications to illustrate the case. They are built from Spring Initializr with Web and Sleuth features only. Both are the same except one is built on `Edgware.SR2` and the other on `Finchley.SR6`.
The application contains a simple RestController that logs a small message and throws a RuntimeException whenever it receives a request (mapped on `/**`).
The context also contains a custom DefaultErrorAttributes with the same behaviour as the original except it logs a message when the `errorAttributes()` method is invoked. This method is invoked after Tomcat has forwarded the request to the ErrorDispatcher after reception of an _uncaught_ exception.
The application starts on port 8080 by default.

**Scenario 1**
Invoke the service - an uncaught RuntimeException is thrown
```
curl -v http://localhost:8080
```

Application logs:

```
 INFO [-,e7f50e4c43a76f7c,e7f50e4c43a76f7c,false] 41701 --- [nio-8080-exec-2] com.example.demo.RestService             : Request received - about to throw an exception
ERROR [-,e7f50e4c43a76f7c,e7f50e4c43a76f7c,false] 41701 --- [nio-8080-exec-2] o.s.c.sleuth.instrument.web.TraceFilter  : Uncaught exception thrown

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.RuntimeException: boom
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
....
ERROR [-,,,] 41701 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: boom] with root cause

java.lang.RuntimeException: boom
	at com.example.demo.RestService.custom(RestService.java:30) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
....
 INFO [-,045aa25bab393b07,045aa25bab393b07,false] 41701 --- [nio-8080-exec-2] com.example.demo.RestService             : getErrorAttributes() invoked for /error
```

The first two lines are caused by the request hitting the RestController handler. They both refer to the same Span (`e7f50e4c43a76f7c`).
The third line is logged by Tomcat because of the _uncaught_ exception - it does not contain any Span (as expected, see #714).
The last line is caused by the handling on `/error`.
**--> Logs generated by `/error` refer to a DIFFERENT span than when the request originally hit the rest controller.**

**Scenario 2**
Invoke the service with Span headers:
```
curl -v -H "X-B3-TraceId: 97952cdf1b39993f" -H"X-B3-SpanId: 97952cdf1b39993f" http://localhost:8080
```

Application logs:
Note: exception logged by Tomcat is omitted for brevity.
```
 INFO [-,97952cdf1b39993f,97952cdf1b39993f,true] 41701 --- [nio-8080-exec-3] com.example.demo.RestService             : Request received - about to throw an exception
ERROR [-,97952cdf1b39993f,97952cdf1b39993f,true] 41701 --- [nio-8080-exec-3] o.s.c.sleuth.instrument.web.TraceFilter  : Uncaught exception thrown

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.RuntimeException: boom
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
....
 INFO [-,97952cdf1b39993f,97952cdf1b39993f,true] 41701 --- [nio-8080-exec-3] com.example.demo.RestService             : getErrorAttributes() invoked for /error
```
**--> All logs now refer to the SAME span, including those generated by `/error`.**

**Comment by marcingrzejszczak** [comment]
Is it for `2.0.0.M6` - if that's the case then it's a known issue that I haven't filed. Thanks for doing that for me ;)

**Comment by brenuart** [comment]
[sample-projects.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/1724572/sample-projects.zip)

**Comment by brenuart** [comment]
Well... according to me, everything is fine in `2.0.0`... but `1.3.x` behaviour is odd (and annoying).

**Comment by marcingrzejszczak** [comment]
Seriously? Interesting, I'll double check that then. Thanks for the sample!

**Comment by brenuart** [comment]
I suspect a new span is actually created for `/error` in both cases but they reused the ids embedded in the request - so they _look_ the same. However, we may have two _server received_ events and it will look as if the server received two consecutive requests: one for the original URI, the second for /error.

**Comment by marcingrzejszczak** [comment]
I think that the problem might be present in both cases but Brave & Zipkin combination is handled in a more intelligent way.

**Comment by brenuart** [comment]
To give you some background: we have a custom handler behind `/error` that includes the span ids in the error response. For us it is important they are the same as from within the rest handler.

**Comment by brenuart** [comment]
I wonder if the difference in behaviour comes from the following changes in `TraceWebAspect`: 
- `2.0.x`: [L147-149](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAspect.java#L147-L149)
- `1.3.x`: [L150-159](https://github.com/spring-cloud/spring-cloud-sleuth/blob/1.3.x/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAspect.java#L150-L159)

`1.3.x` marks the span for close after the HandlerExceptionResolver is invoked, `2.0.x` does not (afaik). Why should it be closed anyway? The handler may not have handled the exception and it will bubble up to Tomcat...

What's the purpose of instrumenting the HandlerExceptionResolver by the way - besides maybe capturing details about the exception... ?

**Comment by marcingrzejszczak** [comment]
In `2.0.x` the problem was already fixed in `TraceFilter`. I've forgotten to backport it to `1.3.x`. 

The problem wasn't with the aspect, it was in `TraceFilter`. I haven't checked if there's an error controller present when an exception was thrown. Cause if there is one then it means that it will be called and it will execute the logic of closing the span. In `2.0.x` there's a problem with multiple tags, but I guess that's another problem to solve

**Comment by brenuart** [comment]
Nice - I'm gonna test latest SNAPSHOT asap. I'll keep you informed.

Your comment let me think the TraceFilter expects Tomcat to forward the request to `/error` in case of uncaught exception. Correct?
As already mentioned, this is not always the case. For instance, Tomcat silently ignore uncaught  `org.apache.catalina.connector.ClientAbortException` (subtype of `IOException`) exceptions: they are not logged and not forwarded to the ErrorDispatcher. Is this causing issues to the `TraceFilter`?

**Comment by marcingrzejszczak** [comment]
> Your comment let me think the TraceFilter expects Tomcat to forward the request to /error in case of uncaught exception. Correct?

Correct

> As already mentioned, this is not always the case. For instance, Tomcat silently ignore uncaught org.apache.catalina.connector.ClientAbortException (subtype of IOException) exceptions: they are not logged and not forwarded to the ErrorDispatcher. Is this causing issues to the TraceFilter?

I haven't tested that at all so we can actually give it a go and check it out.
