### ISSUE TITLE
Parameter in Sampler - use it or lose it

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#86]
Sampler is parameterised with a mythical "context" type which is never used. It looks awkward and so should be removed unless we can work it into the API in a sensible way.

**Comment by dsyer** [comment]
See also #56

**Comment by marcingrzejszczak** [comment]
So I guess that everybody agrees to the fact that there should be no parameter there? :) @dsyer @adriancole @spencergibb ?

**Comment by adriancole** [comment]
I made some notes in #91. the only user of the type could have been `TraceManager.startSpan(name, sampler, info)`. My vote is axe the param and its caller.
