### ISSUE TITLE
Sending trace to zipkin over http even when kafka/rabbit is on classpath - missing docs

### ISSUE THREAD

**Issue by odedia** [spring-cloud/spring-cloud-sleuth#862]
I couldn't find a way to force sending events to zipkin via http.
I have an application that uses cloud stream for messaging.
I still want sleuth to track events in zipkin using http, since it seems to be the default solution of openzipkin.

I tried using the old zipkin-server from 1.4.7 (seems unsupported starting with 1.5.0), but my new microservices are sending events to the "zipkin" topic while zipkin-server appears to be listening on "sleuth" topic.

I believe zipkin events should be allowed via http, even if kafka/rabbitmq is on the classpath.

Thanks.

**Comment by marcingrzejszczak** [comment]
> Bug report

Please provide details of the problem, including the version of Spring Cloud that you
are using. If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

Could you please provide the Spring Cloud version that you're using? 

Just set 

`spring.zipkin.sender.type` 

to either

`web`, `kafka` or `rabbit` to force it.

**Comment by odedia** [comment]
Thank you, that indeed worked.
Please note that I could not find this in the documentation: https://cloud.spring.io/spring-cloud-sleuth/single/spring-cloud-sleuth.html

I will upload a sample project showing the problem soon.
Thanks.

**Comment by marcingrzejszczak** [comment]
Ok so, I need to update the docs

**Comment by odedia** [comment]
A demo is available here:

https://github.com/odedia/spring-cloud-meetup-demo

Spring Cloud Stream 1.5+ sends zipkin events to the "zipkin" channel while Spring Zipkin Stream 1.4.7 is listening for events on the "sleuth" channel. Tried to change the output destination in properties but it didn't work.

Requires local default rabbitmq (localhost:5672)

**Comment by marcingrzejszczak** [comment]
you should have both servers running. The new one (openzipkin-zipkin) and the old one (zipkin-stream) at the same time. Apps using legacy sleuth-stream will send spans to the old one, apps using the new approach will send spans to the new one. As simple as that. Once you've migrated all old to new, you just kill the old zipkin server.

**Comment by odedia** [comment]
Thank you, it's beginning to make sense to me.

The demo app doesn't have any legacy requirements, I just wanted to be able to send events to zipkin for demo purposes.

The demo app uses latest 1.5.10 release. By default it sends events to the "zipkin" channel.

I tried to use the legacy zipkin server because I thought that was the only way to get events from streams, since the official documentation on http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.3.2.RELEASE/single/spring-cloud-sleuth.html doesn't mention openzipkin. But 1.4.7 was listening on another channel called "sleuth".

Looking deeper into openzipkin server documentation I can see there are variables for RABBIT_ADDRESSES and KAFKA_ZOOKEEPER. I guess this replaces the standard spring properties config. 

Perhaps these environment properties should be mentioned in the sleuth documentation as well.

Thanks for the great framework, it helps me a lot!
