### ISSUE TITLE
Add an option to provide additional sleuth skip patterns through configuration

### ISSUE THREAD

**Issue by lchayoun** [spring-cloud/spring-cloud-sleuth#865]
The only available property is `spring.sleuth.web.skipPattern` which has default value:
```java
	public static final String DEFAULT_SKIP_PATTERN =
			"/api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/trace|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream";
```
So in order to keep the default skip pattern and add to it the whole pattern need to be given in this property.

I suggest adding another property `spring.sleuth.web.additionalSkipPattern` which will be concatenated to the `spring.sleuth.web.skipPattern` value.

Another option is to add a property `spring.sleuth.web.appendDefaultSkipPattern=<true|false>` which will append the default to the given value of `spring.sleuth.web.skipPattern`.

**Comment by lchayoun** [comment]
@marcingrzejszczak Thanks for the quick response!
Any chance this change will be ported to 1.3.x?

**Comment by marcingrzejszczak** [comment]
It's a new feature and I prefer not to add any new features to the `1.3.x` branch.
