### ISSUE TITLE
Spring cloud sleuth starter breaks Reactor kafka

### ISSUE THREAD

**Issue by jntakpe** [spring-cloud/spring-cloud-sleuth#866]
When Spring Sleuth is enabled it's no longer possible to send messages to topic.
The error is : `Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@67043092 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7da2f73[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]`
You can reproduce the issue using this project : https://github.com/jntakpe/sleuth-kafka

**Comment by jntakpe** [comment]
@marcingrzejszczak do you have a workaround till M8 is released ?

**Comment by spencergibb** [comment]
M8 happens today

**Comment by jntakpe** [comment]
@spencergibb great news :)
