### ISSUE TITLE
Ensure that the messaging spans result in showing the app in dependency view in Zipkin

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#867]

**Comment by macarlet** [comment]
Hi there, it seems that sleuth zipkin won't send tracing message to zipkin collector using spring boot 2(release) isn't it? Thanks

**Comment by adriancole** [comment]
technically messaging spans need to have the remote service name set to the
broker's name to pop up on the dependency view

**Comment by marcingrzejszczak** [comment]
Fixed in new version of Brave

**Comment by marcingrzejszczak** [comment]
Still doesn't work
