### ISSUE TITLE
Missing icons for callouts in reference guide

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#876]
E.g. http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/2.0.0.M7/single/spring-cloud-sleuth.html#_sleuth_with_zipkin_via_http

**Comment by marcingrzejszczak** [comment]
That should go to sc-build I guess...

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-build/issues/70
