### ISSUE TITLE
Ensure that the Sleuth Reactor instrumentation is not breaking other projects

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#881]
- [x] Reactor Kafka
- [x] Josh's apps
- [ ] Spring Secutiry

**Comment by jntakpe** [comment]
@marcingrzejszczak sometimes it's also breaks reactor subscriber context but I'm in trouble to reproduce the issue

**Comment by marcingrzejszczak** [comment]
have you tested that against latest snapshots?

**Comment by jntakpe** [comment]
I tested with M8

**Comment by marcingrzejszczak** [comment]
Please test against latest snapshots

**Comment by jntakpe** [comment]
I keep you in touch when I have tested with the latest snasphot

**Comment by jntakpe** [comment]
Yes the issue is still here I will try to setup a project where you will be able to reproduce the problem. In my main project to reproduce, I run tests with WithMockUserDetails in the service layer and the subscriber context is empty when sleuth is enabled. But tests using subscriber context in controller layer works.

**Comment by marcingrzejszczak** [comment]
:( a sample will be very useful, thanks!

**Comment by marcingrzejszczak** [comment]
Maybe related https://github.com/spring-projects/spring-security/issues/4888 ?

**Comment by tjormola** [comment]
I think I encountered this issue. Here's a small sample project: https://github.com/tjormola/zipkin-reactive-problem
With Finchley.M8 exception
```
java.lang.ClassCastException: reactor.core.publisher.FluxLift cannot be cast to reactor.core.publisher.ConnectableFlux
```
is thrown. With Finchley.BUILD-SNAPSHOT the app will boot, but didn't check if Zipkin stuff really works.

**Comment by marcingrzejszczak** [comment]
@tjormola so that problem got fixed with snapshots. I'm still waiting for @jntakpe to show a sample cause I had a chat with @rwinch and we're not sure what the problem might be. We'll need a sample to replicate the issue

**Comment by marcingrzejszczak** [comment]
@jntakpe any chance for a sample? ;)

**Comment by jntakpe** [comment]
@marcingrzejszczak I hope I will be able to upload a sample this week end

**Comment by jntakpe** [comment]
@marcingrzejszczak I've uploaded the sample project [here](https://github.com/jntakpe/sleuth-reactor-issue)

**Comment by rwinch** [comment]
@jntakpe Thanks for the report. This is a duplicate of https://github.com/spring-projects/spring-security/issues/4888

**Comment by marcingrzejszczak** [comment]
So I'll close or here cause automatically once security is fixed sleuth will work fine

**Comment by jntakpe** [comment]
@rwinch But it works fine when Sleuth is disabled.

**Comment by jntakpe** [comment]
I've updated the sample project without using WithUserDetails but only Reactor's subscriberContext and I've the same issue ([link to failing tests](https://github.com/jntakpe/sleuth-reactor-issue/blob/master/src/test/java/com/github/jntakpe/sleuthreactorissue/IssueServiceTest.java)). If the sleuth is disabled it's working and when I enable Sleuth I'm not able to retrieve Reactor context.

**Comment by marcingrzejszczak** [comment]
great - I'll definitely take a look at it today

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-sleuth/issues/897

**Comment by marcingrzejszczak** [comment]
@jntakpe thanks to your sample I was able to see that we were overwriting the security (or any other) context with an empty one. Now it's fixed and the problem should be gone!

**Comment by jntakpe** [comment]
Great news. Thanks
