### ISSUE TITLE
Puzzles about images shown in "Terminology" section in README.adoc

### ISSUE THREAD

**Issue by silencehe09** [spring-cloud/spring-cloud-sleuth#884]
Dear authors,
I have some questions about the images used to explain the terminology.
Q1.  In the image "The following image shows how Span and Trace look in a system"， are "Span Id=C“,"Span Id=E“ and "Span Id=G“ all physical spans ? Would they be reported to zipkin ?
In my opinion，"Span Id=C" is equivalent to part of “Span Id=B” (Server Received and Server Sent in Span Id=B)， the same as  "Span Id=E" and “"Span Id=G”。And in the following explaination of "Why is there a difference between the seven and four spans in this case"， it seems that "Span Id=C“,"Span Id=E“ and "Span Id=G“ are referred to "Server Received (sr) and Server Sent (ss) events took place on the service2/3/4 side 。

Q2. In the image "The following image shows how parent-child relationships of spans look",  it shows that the "Span Id=C“ is a physical span and the parent span of “Span Id=D” and "Span Id=F”, is that corresponding to the database storage of zipkin ( that's the datatable of  zipkin_spans in zipkinv2  ) ?
 I have tried out a demo to show the trace info just like the live demo in PCF, but the trace data stored in zipkin_spans  seems that  the parent span of “Span Id=D” and "Span Id=F” is "Span Id=B“.  Does that mean "Span Id=C“ doesn't exist in the implementation ?

 Maybe I misunderstand some concepts. Look forwar to your reply.

**Comment by marcingrzejszczak** [comment]
> are "Span Id=C“,"Span Id=E“ and "Span Id=G“ all physical spans ? Would they be reported to zipkin ?

yes

> n my opinion，"Span Id=C" is equivalent to part of “Span Id=B” (Server Received and Server Sent in Span Id=B)， the same as "Span Id=E" and “"Span Id=G”

Ok, but that's not the case. We've simulated that someone has created a new span by themselves (maybe I need to update the docs to emphasise that).

> Q2. In the image "The following image shows how parent-child relationships of spans look", it shows that the "Span Id=C“ is a physical span and the parent span of “Span Id=D” and "Span Id=F”, is that corresponding to the database storage of zipkin ( that's the datatable of zipkin_spans in zipkinv2 ) ?
I have tried out a demo to show the trace info just like the live demo in PCF, but the trace data stored in zipkin_spans seems that the parent span of “Span Id=D” and "Span Id=F” is "Span Id=B“. Does that mean "Span Id=C“ doesn't exist in the implementation ?

I don't understand the problem. The parent-child relationship is pretty straightforward. How it's stored in the Zipkin's DB is an impl detail I guess. If you're interested you can ask that question in the Zipkin repo.
