### ISSUE TITLE
Allow custom HttpClientParser and HttpServerParser

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-sleuth#886]
Working on https://github.com/spring-cloud/spring-cloud-gcp/pull/438 to provide auto-configuration to propagate trace data to Stackdriver Trace.

Sleuth 2.0.0.M6+ is now using Brave. The default configuration doesn't provide the same information as Sleuth 1.x.  A couple of tags are missing and would be beneficial to Stackdriver Trace.  Namely, `http/host` and `http/url`.

Upon inspecting the Sleuth legacy implementation, we may also want to not use it but use custom parsers to produce spans with name and tags that's better suited for Stackdriver Trace.

However, there is currently no way to produce `HttpTracing` bean to override the Sleuth auto-configuration, because several `SkipPatternProvider`, `SleuthHttpClientParser`, `SleuthHttpServerParser`, and `SleuthHttpSampler` are all package protected.  Even if we produce the `HttpClientParser` and `HttpServerParser`, there is still no way to create `SleuthHttpSampler` nor injecting existing `SkipPatternProvider`.

After discussing w/ @marcingrzejszczak, it would be beneficial to be able to take custom `HttpClientParser` and `HttpServerParser` beans and adding/appending them to the existing auto-configured `HttpTracing` configuration.

**Comment by adriancole** [comment]
sounds fine. just if someone overrides all of HttpTracing, they'll also override these parsers, which is probably fine (more a documentation thing). FWIW exactly the same issue for x-ray
