### ISSUE TITLE
1.2.6 still have trace id conflict problem

### ISSUE THREAD

**Issue by Jaware** [spring-cloud/spring-cloud-sleuth#887]
I remember the traceid random confict problem have been fixed in some release version,but when i use 1.2.6，i find the problem still existsO__O "…
![image](https://user-images.githubusercontent.com/3970304/37072287-8fdc4358-21fb-11e8-84c0-6000209caadd.png)

**Comment by marcingrzejszczak** [comment]
Please upgrade to `1.3.x` release.  The problem was fixed in `1.3.2` https://github.com/spring-cloud/spring-cloud-sleuth/issues/728

**Comment by Jaware** [comment]
ok,thanks
