### ISSUE TITLE
Migrate integration tests from brewery to sleuth

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#89]
we could from maven start for example Zipkin docker container and run some tests against it

**Comment by adriancole** [comment]
Yep. Also the zipkin-java server should be something we can make a junit
rule out of. This is something I think can solve the classpath concerns,
too, as I probably wouldn't involve spring framework code in a junit rule.

**Comment by marcingrzejszczak** [comment]
Done - https://github.com/spring-cloud/spring-cloud-sleuth/commit/4efa4c3f27cc74ad115134554c5c3d476191361f
