### ISSUE TITLE
Make sure layered http server instrumentation doesn't make spans

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#892]
Layers over servlet, like web mvc have important data to add to a span, but shouldn't create new spans or finish spans started at the servlet layer. Such an approach keeps latency coherent and also helps make sure we have less chance of lifecycle bugs (like double-reporting)

At the very least, these "tagging interceptors or filters" set the servlet request attribute "http.route" with the best matching route as well any tags like the controller method. Since it is only adding tags, it doesn't need reference to a tracer, rather "span customizer".

This is a thing we can align here until brave 4.18 is out which will be more formal about this in general per https://github.com/openzipkin/brave/pull/635

**Comment by marcingrzejszczak** [comment]
fixed via 171daaf
