### ISSUE TITLE
Different versions of Spring Cloud with the same code show different effects on zipkin

### ISSUE THREAD

**Issue by jumkey** [spring-cloud/spring-cloud-sleuth#898]
When i use **Spring Boot 2.0.0.RELEASE**&**Spring Cloud Finchley.M8** zipkin show like this
![20180310232818](https://user-images.githubusercontent.com/1449530/37243848-102626de-24bb-11e8-8cf5-763a9b7668d9.png)

but change to **Spring Cloud Edgware.SR2**&**Spring Boot 1.5.10.RELEASE** or use Rest Template don't have the last demo2
![20180310232953](https://user-images.githubusercontent.com/1449530/37243849-10575132-24bb-11e8-9535-ea70f36875fa.png)

I think it might be a bug

**Comment by marcingrzejszczak** [comment]
Can you 
- explain where do you think that there's a bug
- try latest finchley snapshots
- show the code (I have no idea what and how exactly you're doing things)

**Comment by jumkey** [comment]
This is demo2 code
``` java
@RestController
public class Demo2Controller {
    @Autowired
    private UserClient userClient;
    @Autowired
    private RestTemplate restTemplate;

    @RequestMapping(value = "login",method = RequestMethod.GET)
    public void login(){
        restTemplate.getForEntity("http://localhost:8080/s",Boolean.class).getBody();

        userClient.isLogin();//FeignClient http://localhost:8080/s
    }
}
```
http://localhost:8080/s is just return true

use FeignClient has more span

because of poor network  i have not try latest snapshots

**Comment by marcingrzejszczak** [comment]
To help you, you'll have to upload the whole sample. I don't understand what you're trying to achieve, I still don't understand where the "bug" is.

**Comment by jumkey** [comment]
demo code
``` java
@RestController
public class UserResource implements UserClient {

    @Override
    public Boolean isLogin() {
        return true;
    }
}
```
demo didn't call demo2
but zipkin show

>demo-->demo2

**Comment by marcingrzejszczak** [comment]
Please upload your whole project to github. Until you do so I'm closing this issue cause i can't really guess what you're doing.
