### ISSUE TITLE
Configuration startup issue

### ISSUE THREAD

**Issue by jntakpe** [spring-cloud/spring-cloud-sleuth#905]
On application startup the message : 

> Cannot enhance @Configuration bean definition 'org.springframework.cloud.sleuth.instrument.reactor.TraceReactorAutoConfiguration$TraceReactorConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.

is logged and the application freeze

**Comment by marcingrzejszczak** [comment]
In the comment that you deleted when you create an issue we ask the users to 

> Please provide details of the problem, including the version of Spring Cloud that you
are using. If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

Could you please provide this information? Also can you test if the problem is still there when you use SNAPSHOT versions?

**Comment by marcingrzejszczak** [comment]
Just in case I've pushed a change to make that bean static, hopefully it fixes things for you.

**Comment by jntakpe** [comment]
The problem was occuring on the last BUILD-SNAPSHOT version. I'm not sure I'll be able to provide an application sample. I'll say if the issue is fixed

**Comment by jntakpe** [comment]
Ok the message is not present anymore but the application is still frozen on startup. I'll try to provide a sample application

**Comment by jntakpe** [comment]
It seems the application is looping on a bean called tracing. Below the startup log lines :

>o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'spring.sleuth-org.springframework.cloud.sleuth.autoconfi
o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'tracing' via factory method to bean named 'sleuthPropagation'     
o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'tracing' via factory method to bean named 'slf4jSpanLogger'       
o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'tracing' via factory method to bean named 'noOpSpanReporter'      
o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'tracing' via factory method to bean named 'sleuthTraceSampler'    
o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'tracing' via factory method to bean named 'spring.sleuth-org.sprin
o.s.b.f.s.DefaultListableBeanFactory     : Eagerly caching bean 'tracing' to allow for resolving potential circular references                  
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'org.springframework.cache.config.internalCacheAdvisor'  
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'methodSecurityInterceptor'                              
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'sleuthAdvisorConfig'                                    
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'org.springframework.retry.annotation.RetryConfiguration'
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'org.springframework.cache.config.internalCacheAdvisor'  
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'methodSecurityInterceptor'                              
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'sleuthAdvisorConfig'                                    
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'org.springframework.retry.annotation.RetryConfiguration'
o.s.b.f.s.DefaultListableBeanFactory     : Finished creating instance of bean 'tracing'                                                         
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'tracing'                                                
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'tracing'                                                
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'tracing'                                                
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'tracing'                                                
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'tracing'                                                
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'tracing'                                                
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'tracing'                                                
o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'tracing'

**Comment by marcingrzejszczak** [comment]
With the sample it will be much easier. Also can you paste the logs in a normal format? The whole logs please.

**Comment by jntakpe** [comment]
Ok I've managed to reproduce but failed to understand whats going on.
I've setup a sample project https://github.com/jntakpe/sleuth-mongodb.
When using previous Spring cloud sleuth version it's working : https://github.com/jntakpe/sleuth-mongodb/blob/1b210d1e8030f45c33d77f03bf35d1dec66cd737/build.gradle#L49.
It's also working when you remove actuator dependency : https://github.com/jntakpe/sleuth-mongodb/blob/1ae52f3fe30bf2cc7ef8bc56ddff1596f0577b6c/build.gradle#L60
You can make it work too by removing the indexed annotation on User document : https://github.com/jntakpe/sleuth-mongodb/blob/905996b5b02a68768850f46a6d431e713c4fee1b/src/main/kotlin/com/github/jntakpe/sleuthmongodb/SleuthMongodbApplication.kt#L27

**Comment by marcingrzejszczak** [comment]
The `SpanSubscriptionProvider` didn't cache the calls for the `Tracing` bean. For some reason, Spring didn't like it and just hang. So what I did was, what I should have done from the very beginning, store the `Tracing` bean as a field and reference it once it was retrieved. That helped to solve the issue and the application successfully started.
