### ISSUE TITLE
slueth with rxjava2 creating multiple traces

### ISSUE THREAD

**Issue by banank1989** [spring-cloud/spring-cloud-sleuth#909]
I am using spring cloud slueth with zipkin in spring boot to trace the services calls.

My spring cloud version is Edgware.RELEASE

Now I when I tried to trace my facade layer which uses rxjava, it creates 12 traces for a single request?

What should I do ? I mean i want just 1 trace should be generated for 1 request of facade layer(facade layer do parallel calls using rxjava).

I am using slueth with http and have not change any property if properties file

I have added these 2 dependency

 <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zipkin</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>

this i have added in properties file

spring.zipkin.baseUrl: http://172.16.3.197:9411/
spring.slueth.enabled: true
spring.sleuth.sampler.percentage: 1

**Comment by marcingrzejszczak** [comment]
Yeah, so RxJava support in Sleuth is very basic. Starting from Sleuth 2.0.0 we recommend to fully use project Reactor to do reactive programming

![image](https://user-images.githubusercontent.com/3297437/37761691-b085ff20-2dba-11e8-8dc6-cd9f634e3b5b.png)

**Comment by adriancole** [comment]
opened https://github.com/openzipkin/brave/issues/664 for a "continue-only" scheduler hook for rxjava2. This would not trace rxjava2, but it could prevent broken traces.
