### ISSUE TITLE
Inserting custom fields in the console logs

### ISSUE THREAD

**Issue by ppsanyal1** [spring-cloud/spring-cloud-sleuth#911]
Hello,
I am using 1.3.2.RELEASE of spring sleuth. I would like to customize the console logging from
[MyApplication_Name,03d6160eb8f3bccb,7106ef5dc7bdee7a,false]
to
[MyApplication_Name,**myCorrelationId**,7106ef5dc7bdee7a,false]

Can you please share code examples of how this could be done? I haven't found any concrete example anywhere. **myCorrelationId** is actually a session-id.

Thanks,
Partha

**Comment by shakuzen** [comment]
This is similar to the request in https://github.com/spring-cloud/spring-cloud-sleuth/issues/864

You would need to make your own implementation of `CurrentTraceContext` similar to https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jCurrentTraceContext.java
which adds your correlation ID to the MDC, and then update your logging pattern to use the MDC key added.

**Comment by marcingrzejszczak** [comment]
Thanks, @shakuzen for the great response! As for older versions of Sleuth you would have to create your own implementation of `SpanLogger` and register it as a bean. The way we create https://github.com/spring-cloud/spring-cloud-sleuth/blob/1.3.x/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jSpanLogger.java
