### ISSUE TITLE
Is there a reason why spanExportable is not exposed for log4j2?

### ISSUE THREAD

**Issue by thekalinga** [spring-cloud/spring-cloud-sleuth#918]
Question

Currently I dont see the following variable `spanExportable` exposed via `ThreadContext` when using `log4j2`. I'm referring to `ThreadContextCurrentTraceContext`

However, this variable is exposed when it comes to `slf4j` inside `Slf4jCurrentTraceContext`

Is that intentional/a mistake?

**Comment by marcingrzejszczak** [comment]
Yes, that's intentional. That's an implementational detail of Sleuth. To remain backward compatible we've added that field in the Slf4j implementation.

**Comment by thekalinga** [comment]
Instead of just exporting `X-Span-Export` for making it backward compatible, why did you export `spanExportable` aswell if you wanted `spanExportable` to be deprecated?

**Comment by marcingrzejszczak** [comment]
I'm sorry but I don't understand what you're talking about. If you look at https://github.com/openzipkin/brave/blob/master/context/slf4j/src/main/java/brave/context/slf4j/MDCCurrentTraceContext.java#L36 you'll see that Brave uses a different notation. So I've added the same one in Slf4j `spanExportable`. Also to remain backward compatible I've added `X-Span-Export`. I don't understand your problem, sorry.

**Comment by thekalinga** [comment]
My bad, I should given the code reference,

I am referring to this code inside (I see that this gets executed during the auto configuration phase)

https://github.com/spring-cloud/spring-cloud-sleuth/blob/eedff746d658eab73d9efcd0d3d5d3e83e49e0f1/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jCurrentTraceContext.java#L90-L92

**Comment by thekalinga** [comment]
Dint knew that there were two different places where MDC is being applied. What's the difference between these two?
