### ISSUE TITLE
Add a property to enable / disable Zipkin Discovery Client support

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#919]

**Comment by doernbrackandre** [comment]
Hey,

I've spend some minutes in thinking of this..

maybe it would be nice to have some kind of "ConfigurationBasedZipkinLoadBalancer" where spring.zipkin.baseUrl can be a comma separated list of FQDNs 

Cheers,
A

**Comment by marcingrzejszczak** [comment]
When we're using `LoadBalancerClient` for Zipkin, it follows all the standard setup of load balancing that we have in Spring Cloud. That means that if you have Ribbon on the classpath, `LoadBalancerClient` will delegate work to Ribbon, meaning that you can use the standard Ribbon configuration to provide the list of URLs. We don't want to invest too much effort in some additional customization of Zipkin LoadBalancer, since the mechanism to tweak that communication is already there. WDYT?

**Comment by doernbrackandre** [comment]
you mean something like:

```yaml
zipkin:
  ribbon:
    ListOfServers: host1,host2
```
sure, works for me. But this should be well documented because I would not expect to have this configured at a completely different place, you know?

**Comment by marcingrzejszczak** [comment]
@doernbrackandre, wait a couple of minutes for the snapshots to be built and you can check if things are working fine for you. I've also updated the docs.

**Comment by doernbrackandre** [comment]
looks good to me 👍
