### ISSUE TITLE
spring-cloud-stream channel instrumentation with ExtraFieldPropagation

### ISSUE THREAD

**Issue by dhoffi** [spring-cloud/spring-cloud-sleuth#927]
Hi,

I want to add ExtraFieldPropagation which also should be logged via spring-cloud-stream with Rabbit binders. Now (almost) everything works fine out of the box.
I defined the MDC Data in application.yml logging.pattern.level
I provide my own `CustomSlf4jCurrentTraceContext extends CurrentTraceContext` which puts my custom Baggage into MDC in its `newScope()` method and it gets propagated to my downlink µservices.

Only thing left is, that my source is called by a spring scheduler and activated/called by spring-cloud-stream:

```
    @SendTo(SourceChannels.OUTPUT)
    public void timerMessageSource() {
        ExtraFieldPropagation.set(sleuthTracer.currentSpan().context(), CustomSlf4jCurrentTraceContext.CUSTOM_SLEUTH_BAGGAGE_BUSINESS_PROCESS_NAME, "myCustomBpName");
        ExtraFieldPropagation.set(sleuthTracer.currentSpan().context(), CustomSlf4jCurrentTraceContext.CUSTOM_SLEUTH_BAGGAGE_BUSINESS_PROCESS_SUCC, "sink1;somethingElse");

        MessageDTO messageDTO = new MessageDTO();
        messageDTO.datetime = new Date().toString();
        messageDTO.message = "fromSource";
        log.info("[{}]Produced: '{}'", instanceIndex, messageDTO);
        sourceOutputMessageChannel.send(MessageBuilder.withPayload(messageDTO).build());
    }
```

now at the time I insert my custom baggage, the initial Span has already been started by spring-cloud-stream message instrumentation (or sleuth scheduler support?), and at the point I add my ExtraFieldPropagation it will not get into the currentSpan's MDC, as the span is already started and my `CustomSlf4jCurrentTraceContext` has already finished being called by the instrumentation.

Hence propagation is working fine, but my `log.info()` inside the sender does not contain/log my extra baggage.

Is there a simple way to achieve this?

How about an Annotation which I can put on my spring-cloud-stream `@SendTo(SourceChannels.OUTPUT)` and `@StreamListener(Tier1Channels.INPUT)` methods with key/value pairs that are then accessible in its `currentTraceContext` so that I can do with them anything I want to do, e.g. inside my `CustomSlf4jCurrentTraceContext` putting them into the MDC so that already spring-cloud-stream adapter log messages for my scheduled method contain the MDC log data I want to be in there.

This way I could act on my custom baggage and alter it for logging at the point in time where spring-cloud-stream does create the new span for me and not afterwards when my business code has to try to fiddle it in backward. Plus on the receiving side, it could alter the custom baggage to be logged with the altered custom values of the receiver already on receiving by spring-cloud-stream.

thanx for feedback.

**Comment by marcingrzejszczak** [comment]
Hi!

That's a really interesting problem, thanks for raising it up!

My first impression is that we never intended to make the two - baggage and logging to somehow work together exactly at the same time out of the box. That's cause noone has asked about this, until now. However, since you're raising it up, let's try to find a best solution.

Wouldn't it be the easiest to actually rewrite this:

```java
    @SendTo(SourceChannels.OUTPUT)
    public void timerMessageSource() {
        ExtraFieldPropagation.set(sleuthTracer.currentSpan().context(), CustomSlf4jCurrentTraceContext.CUSTOM_SLEUTH_BAGGAGE_BUSINESS_PROCESS_NAME, "myCustomBpName");
        ExtraFieldPropagation.set(sleuthTracer.currentSpan().context(), CustomSlf4jCurrentTraceContext.CUSTOM_SLEUTH_BAGGAGE_BUSINESS_PROCESS_SUCC, "sink1;somethingElse");

        MessageDTO messageDTO = new MessageDTO();
        messageDTO.datetime = new Date().toString();
        messageDTO.message = "fromSource";
        log.info("[{}]Produced: '{}'", instanceIndex, messageDTO);
        sourceOutputMessageChannel.send(MessageBuilder.withPayload(messageDTO).build());
    }
```

to 

```java
    @SendTo(SourceChannels.OUTPUT)
    public void timerMessageSource() {
        ExtraFieldPropagation.set(sleuthTracer.currentSpan().context(), CustomSlf4jCurrentTraceContext.CUSTOM_SLEUTH_BAGGAGE_BUSINESS_PROCESS_NAME, "myCustomBpName");
        ExtraFieldPropagation.set(sleuthTracer.currentSpan().context(), CustomSlf4jCurrentTraceContext.CUSTOM_SLEUTH_BAGGAGE_BUSINESS_PROCESS_SUCC, "sink1;somethingElse");

        try (Tracer.SpanInScope ws = this.sleuthTracer.withSpanInScope(sleuthTracer.currentSpan())) {
            MessageDTO messageDTO = new MessageDTO();
            messageDTO.datetime = new Date().toString();
            messageDTO.message = "fromSource";
            log.info("[{}]Produced: '{}'", instanceIndex, messageDTO);
            sourceOutputMessageChannel.send(MessageBuilder.withPayload(messageDTO).build());
        }
    }
```

I think that if you do that, a new scope will be created and the baggage should be visible in MDC. Can you confirm that?

BTW Could you provide a sample we could fiddle with?

**Comment by dhoffi** [comment]
well, when I finally arrive in the busuiness method, it is even enough to just put the MDC data in (as at this point I am in the right thread anyway):

        @SendTo(SourceChannels.OUTPUT)
        public void timerMessageSource() {
            MDC.put(BUSINESS_PROCESS_NAME, ...);
            ExtraFieldPropagation.set(sleuthTracer.currentSpan().context(), BUSINESS_PROCESS_NAME, ...);
        }

But this does not solve the problem of an error that might happen inside the binder implementation.
Let's say there is a network outage or a problem with rabbit binder sending or receiving.
This then would throw Exceptions and also most probably log something.
But these log messages wouldn't have my custom Baggage information in them as my business code never was reached.
So if I do a logsearch for my custom baggage values I _never_ will get the log messages that are the most interesting to me, as they tell me about what went wrong, but won't have my custom baggage inside MDC

**Comment by olegz** [comment]
FWIW and not related to this discussion, but the above configuration won't work
What I mean is this is the wrong signature
```
@SendTo(SourceChannels.OUTPUT)
 public void timerMessageSource() {..}
```
You can't have `SendTo` on the `void` operation. You'll get 
```
java.lang.IllegalArgumentException: An output channel cannot be specified for a method that does not return a value
	at org.springframework.util.Assert.isTrue(Assert.java:116) ~[spring-core-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor$DefaultStreamListener...
```
What you should so instead of `sourceOutputMessageChannel.send(MessageBuilder.withPayload(messageDTO).build());` is to simply return a Message
```
@SendTo(SourceChannels.OUTPUT)
public Message<?> timerMessageSource() {
    . . .
    return MessageBuilder.withPayload(messageDTO).build();
}
```
. . . and the message will be sent to `SourceChannels.OUTPUT`

**Comment by dhoffi** [comment]
@olegz really a bit off-topic
but I can explain.
For Demo purposes I want to wrap my `@SendTo` with a `@HystrixCommand`
If I depend on `spring-cloud-stream` to send my message, it will be sent in another thread and my `@HystrixCommand` will never be activated ... solution was to directly inject the messageChannel of the Channel:

```
    @Autowired
    @Qualifier(SourceChannels.OUTPUT)
    private MessageChannel sourceOutputMessageChannel;
    
    @HystrixCommand(fallbackMethod = "fallbackTimerMessageSource")
    @SendTo(SourceChannels.OUTPUT)
    public void timerMessageSource() {
        if (springEnv.acceptsProfiles("sleuth")) {
            CustomBaggage.addFixedCustomBaggage(sleuthTracer, "myCustomBpName");
            CustomBaggage.addOrModifyVariableCustomBaggage(sleuthTracer, "sink1;somethingElse");
        }
        MessageDTO messageDTO = new MessageDTO();
        messageDTO.datetime = Instant.now().toString();
        messageDTO.message = "fromSource";
        log.info("[{}]Produced: '{}'", instanceIndex, messageDTO);
        sourceOutputMessageChannel.send(MessageBuilder.withPayload(messageDTO).build());
    }

    public void fallbackTimerMessageSource(Throwable t) {
    ...
    }

```

**Comment by olegz** [comment]
@dhoffi that is fine and perfectly acceptable. In fact it's a documented feature (the fact that you can operate directly on the binding and/or individual channel). My main point is that for your case remove the `@SendTo` otherwise your app fail during the startup.

**Comment by dhoffi** [comment]
well, funny enough it starts and behaves perfectly nice.
Thought the `@SendTo` would still be needed for `spring-cloud-stream` to do some kind of instrumentation maybe ...

**Comment by olegz** [comment]
funny indeed. What version of stream you're using?

The instrumentation you're describing will happen during the `@EnableBinding` and `@StreamListener`. Come to think of it I don't see `@StreamListener` which explains why it doesn't burf in your case. 
Anyway, just remove it since it is confusing.

**Comment by adriancole** [comment]
>
> So if I do a logsearch for my custom baggage values I *never* will get
> the log messages that are the most interesting to me, as they tell me about
> what went wrong, but won't have my custom baggage inside MDC
>
if your only message was an error, sure, but the primary focus of sleuth is
tracing. Wouldn't you get an error span? If you'd like to make some tests
cases, you can, but right now there's simply no resources to implement
CorrelationContext, which wouldn't use ExtraFieldPropagation anyway.

If you are highly reliant on MDC, you should use indeed use MDC apis, like
you suggest. You can also make your own wrapper, if you generically want
every thing set in ExtraFieldPropagation to immediately go to MDC. This
probably not a bad idea anyway because CorrelationContext will have similar
semantics, but be a different api (because  not everything you set will
always go downstream)

**Comment by adriancole** [comment]
While a best solution might not make it for 2.0, we *might* be able
special case ExtraFieldsPropagation meanwhile and achieve the same
https://github.com/openzipkin/brave/issues/682

**Comment by dhoffi** [comment]
thanks guys ... I know you do your best!

**Comment by dhoffi** [comment]
thinking about it further ...

kind of the same "problem" arises when tagging a spring-cloud-stream `@SendTo(...)` or `@StreamListener(...)`

even if I set a tag on the currentSpan as the first thing in my business code...

        @StreamListener(...)
        public void transform(...) {
                SpanCustomizer spanCustomizer = sleuthTracer.currentSpanCustomizer();
                spanCustomizer.tag("some", "tag");

 the tag will only be propagated to zipkin if something will be sent to zipkin afterwards (as my span I am in already has started)

Again what I want, would be that the span spring-cloud-stream is starting already is tagged with whatever tag(s) I want.

    @SleuthSpanTag("key:value")
    @SleuthSpanName("myMessageReceiving")
    @StreamListener(...)
    public void myMessageReiving(...) {
         ...
    }

so that I see the tag in zipkin attached to the receiving span (`handle`)
and that the span has some name I can associate with my method and not a kind of anonymous `handle` which is the same name in all my `@StreamListener`s

But I think this is not _that_ important as the logging MDC above, as I always could just start a `nextSpan` as soon as I am in my business method.
(Again, this is just to have something I as a dev can decide to be the name/tag of the receiving/sending span, which is handled for me by spring instrumentation magic.)

hope it still makes sense what I am saying :)

**Comment by dhoffi** [comment]
any infos or feedback you need from me on this? as this is still marked with question and waiting for feedback ...

**Comment by marcingrzejszczak** [comment]
Sorry I've forgotten to disable the label. We're still chatting about this with @adriancole

**Comment by adriancole** [comment]
@dhoffi I might be confused, but your last comment seems to be about tags (like ending up in zipkin json) not extra fields (like ending in headers), is that right? If so, mind moving this to a new issue as it makes my brain hurt otherwise :)

**Comment by adriancole** [comment]
there are a few interrellated iasuws including this one.  Marcin and I luckily have some face to face time in a couple weeks. We will rope some time on this issue. I dont think there has been progress on the w3c side of things and also census isnt much farther along either. However, I do think we can at least get some focus time at our F2F and topics like this do meed focus to do the right thing with. until then, hang tigj or feel free to add feedback.

**Comment by matthewjmason** [comment]
Adding to this issue from #1003 

The request in 1003 encompasses a lot of the work @dhoffi did in creating his own custom CustomSlf4jCurrentTraceContext. However, rather than relying on each client to create their own custom implementation, the existing CustomSlf4jCurrentTraceContext  is augmented to allow for automated adding of some baggage fields from the span into MDC. My client has an existing traceability library that mimics a subset of sleuth's behavior by storing the "spans" in threadlocal and logging them via MDC fields. I was hoping to leverage the reactor decoration performed by sleuth to pass the context around since ThreadLocal is not available with reactor. My hope is to add the client's current traceability fields to sleuth via tags or baggage fields and then have them added to MDC in the same fashion as the standard spanId and traceId.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by marcingrzejszczak** [comment]
We've added a feature to automatically add entries to MDC from baggage (https://github.com/spring-cloud/spring-cloud-sleuth/issues/1071) and this is the recommended way to go. With @adriancole we've talked through that we don't want to currently support other means of automatic insertion of entries to MDC.

Of course, Sleuth is extremely extensible so if you want to, you can extend it in any way you want to.

**Comment by adriancole** [comment]
Added here https://github.com/spring-cloud/spring-cloud-sleuth/wiki/Spring-Cloud-Sleuth-3.0-Migration-Guide
