### ISSUE TITLE
could not be found the annotation of 'EnableZipkinStreamServer' 

### ISSUE THREAD

**Issue by godpit** [spring-cloud/spring-cloud-sleuth#935]
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-zipkin-stream</artifactId>
 </dependency>

The dependency could not be found in the spring cloud 2.0.0.M9, however, the 'EnableZipkinStreamServer'  could not be found in the package of 'org.springframework.cloud.sleuth.zipkin.stream.EnableZipkinStreamServer'.
How i can  get it?

**Comment by marcingrzejszczak** [comment]
You can't. Please read the documentation where we describe exactly what you should do. https://cloud.spring.io/spring-cloud-sleuth/single/spring-cloud-sleuth.html#_zipkin_stream_span_consumer

**Comment by godpit** [comment]
I know that it is deprecated, but are there available alternatives?

**Comment by marcingrzejszczak** [comment]
Yes. Use the zipkin rabbit / kafka support. It's described in the documentation. Please read the docs

**Comment by godpit** [comment]
thanks a lot!

**Comment by godpit** [comment]
1. We recommend that you add the dependency management through the Spring BOM so that you need not manage versions yourself.

  2.Add the dependency to spring-cloud-starter-zipkin. That way, all nested dependencies get downloaded.

  3.To automatically configure RabbitMQ, add the spring-rabbit dependency.

I just find these, i think it is so simple description.

@SpringBootApplication
@EnableDiscoveryClient

@EnableZipkinStreamServer
public class ZipkinApplication {
    public static void main(String[] args) {
        SpringApplication.run(ZipkinApplication.class, args);
    }

}

This is my previous code，however, i use the '@EnableRabbit' to replace ‘@EnableZipkinStreamServer’. is it ok?

**Comment by marcingrzejszczak** [comment]
You are mixing the consumer side (`spring-cloud-sleuth-stream`) with the Zipkin server. Here (http://cloud.spring.io/spring-cloud-static/Edgware.SR3/single/spring-cloud.html#_zipkin_consumer) we write that:

> spring-cloud-sleuth-zipkin-stream is deprecated and should no longer be used. Please use the OpenZipkin’s Zipkin server and set the environment variables as presented here for rabbit (Zipkin 2.4.6) or here for kafka (Zipkin 2.4.6)

If you read through the Zipkin documentation you can find this entry for rabbit

https://github.com/openzipkin/zipkin/tree/2.4.6/zipkin-server#rabbitmq-collector

and this for kafka 

https://github.com/openzipkin/zipkin/tree/2.4.6/zipkin-server#kafka-collector

There's also a similar old issue here https://github.com/spring-cloud/spring-cloud-sleuth/issues/736


All in all, you should stop using the legacy `sleuth-stream` dependency, you should follow the docs to migrate to new way of sending spans via messaging and your zipkin server should also get migrated as described in the zipkin docs.
