### ISSUE TITLE
Spring Cloud Sleuth 2.x with SLF4J+Log4j2

### ISSUE THREAD

**Issue by nnanda2016** [spring-cloud/spring-cloud-sleuth#938]
Requesting for a sample to show Sleuth with Spring Boot 2.0 WebFlux apps which use Slf4J + Log4J2 for logging.

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud-samples/sleuth-documentation-apps/commit/06209c0529d9f73be369edf5d1b5bb22ce818310

I haven't done the logging cause I guess you'd have to just add the bridge (https://www.slf4j.org/legacy.html#log4j-over-slf4j). If you're able to provide a sample somewhere we can check it out.
