### ISSUE TITLE
TraceID not carried with Spring Integration and task Executor

### ISSUE THREAD

**Issue by Anand0583** [spring-cloud/spring-cloud-sleuth#943]
When I am using Spring Integration and having a task Executor inside it then a new trace id is getting generated and the main traceId is lost. It is mentioned that when using any task executor the traceId will be maintained and the span id will be newly generated. Not sure what I am missing but this is critical for us because we want to co-relate the spans and measure the performance of each thread.

Can you please let us know your what we are doing wrong it will be very helpful.

Attached is the sample project.

[HelloWorldSpringIntegration.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/1911670/HelloWorldSpringIntegration.zip)

To Execute the Sample : mvn spring-boot:run & invoke the http://localhost:8081/getHelloWorldMessage

Log Message:

```
[HelloSpringIntegrationConfiguration,,,] 14184 --- [nio-8081-exec-3] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 96 ms
[HelloSpringIntegrationConfiguration,15d8d0f1fbb7a1ba,15d8d0f1fbb7a1ba,false] 14184 --- [nio-8081-exec-3] c.e.s.HelloWorldRestController           : Inside getHelloWorldMessage
[HelloSpringIntegrationConfiguration,15d8d0f1fbb7a1ba,b0a515855c893d36,false] 14184 --- [nio-8081-exec-3] c.e.springintegration.HelloWorldImpl     :  Inside splitMessage [Ljava.lang.String;@1cf0b80f
[HelloSpringIntegrationConfiguration,16b318d800c8d709,16b318d800c8d709,false] 14184 --- [questExecutor-2] c.e.springintegration.HelloWorldImpl     :  input message Hellow World Message 1
[HelloSpringIntegrationConfiguration,debd51b328528d2f,debd51b328528d2f,false] 14184 --- [questExecutor-6] c.e.springintegration.HelloWorldImpl     :  input message Hellow World Message 2
[HelloSpringIntegrationConfiguration,5af4a81a92315a85,5af4a81a92315a85,false] 14184 --- [questExecutor-3] c.e.springintegration.HelloWorldImpl     :  input message Hellow World Message 3
[HelloSpringIntegrationConfiguration,16b318d800c8d709,16b318d800c8d709,false] 14184 --- [questExecutor-2] c.e.springintegration.HelloWorldImpl     :  After the Sleep Hellow World Message 1
[HelloSpringIntegrationConfiguration,5af4a81a92315a85,5af4a81a92315a85,false] 14184 --- [questExecutor-3] c.e.springintegration.HelloWorldImpl     :  After the Sleep Hellow World Message 3
[HelloSpringIntegrationConfiguration,debd51b328528d2f,debd51b328528d2f,false] 14184 --- [questExecutor-6] c.e.springintegration.HelloWorldImpl     :  After the Sleep Hellow World Message 2
```

**Comment by marcingrzejszczak** [comment]
We applied a fix for branch `1.3.x`, the functionality works fine for `2.0.x` already without any changes to the code.

**Comment by Anand0583** [comment]
I tried to upgrading the version of Spring Boot 2.0.0 and Finchley.M9 version and I get an error 'java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication'.

[HelloWorldSpringIntegration_Uploaded.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/1915943/HelloWorldSpringIntegration_Uploaded.zip)

Not sure what I am doing wrong.

**Comment by Anand0583** [comment]
And also when you mention to migrate the version. I updated the Spring Cloud Boot Starter to Edgware.SR3 which uses Spring Boot Slueth version 1.3.3 version and still see the issue. Thats the reason i tried to migrate to the Spring 2.0.0 version. But getting the ClassNotFoundException.

**Comment by marcingrzejszczak** [comment]
For edgware and finchly use latest snapshots.

**Comment by Anand0583** [comment]
When i change to Edgware.BUILD-SNAPSHOT.. another issue..

Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.springframework.cloud:spring-cloud-dependencies:pom:Edgware.BUILD-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:434)
        ... 27 more
[ERROR]     'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-sleuth:jar is missing. @ line 40, column 15
[ERROR]
[ERROR]

[pom.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/1919176/pom.zip)

**Comment by marcingrzejszczak** [comment]
It's clearly written what the problem is:

```
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.springframework.cloud:spring-cloud-dependencies:pom:Edgware.BUILD-SNAPSHOT
```

It can't find the artifact. Have you added the snapshot repository to your pom? Please generate a snapshot project here https://start.spring.io/ and see how the setup looks like.

**Comment by marcingrzejszczak** [comment]
Maybe, we don't have a date yet. You can check this page to find release dates https://github.com/spring-cloud/spring-cloud-release/milestones

**Comment by Anand0583** [comment]
Thanks alot with the fix. TraceId and SpanId issue is resolved. Thanks alot for your support.

2018-04-17 06:21:30.505  INFO [HelloSpringIntegrationConfiguration,60e1766c2b3b9d49,60e1766c2b3b9d49,false] 16940 --- [nio-8081-exec-3]
2018-04-17 06:21:30.540  INFO [HelloSpringIntegrationConfiguration,60e1766c2b3b9d49,3fc2c73a8131a37b,false] 16940 --- [nio-8081-exec-3]
2018-04-17 06:21:30.549  INFO [HelloSpringIntegrationConfiguration,60e1766c2b3b9d49,3fc2c73a8131a37b,false] 16940 --- [questExecutor-5]
2018-04-17 06:21:30.556  INFO [HelloSpringIntegrationConfiguration,60e1766c2b3b9d49,3fc2c73a8131a37b,false] 16940 --- [questExecutor-4]
2018-04-17 06:21:30.786  INFO [HelloSpringIntegrationConfiguration,60e1766c2b3b9d49,3fc2c73a8131a37b,false] 16940 --- [questExecutor-1]
2018-04-17 06:21:30.793  INFO [HelloSpringIntegrationConfiguration,60e1766c2b3b9d49,60e1766c2b3b9d49,false] 16940 --- [nio-8081-exec-3]

**Comment by marcingrzejszczak** [comment]
No problem. I'm happy that it's working fine
