### ISSUE TITLE
Sleuth corrupts Error message in Spring integration

### ISSUE THREAD

**Issue by juandesalas** [spring-cloud/spring-cloud-sleuth#946]
This problem is related with the issue 761 of garyrussell.
I have a application with rabbit and spring integration, i read a message call a service and send a response. When the service work fine i have no problem but if the service throw an exception the response message is not released.
I obtain the message: Reply message received but the receiving thread has exited due to an exception while sending the request message:GenericMessage
If i put the propertie spring.sleuth.integration.enabled=false my application works fine in all cases.

Thanks.

**Comment by marcingrzejszczak** [comment]
Which version of Sleuth are you using?

**Comment by marcingrzejszczak** [comment]
Also can you provide an example?

**Comment by juandesalas** [comment]
version is 2.0.0.M9

**Comment by juandesalas** [comment]
Hello, i have in local spring-cloud-sleuth 2.0.0.BUILD-SNAPSHOT branch master.
If in the class TracingChannelInterceptor in the line:
295 MessageHeaderAccessor headers = MessageHeaderAccessor.getMutableAccessor(getMessage(message));
change for MessageHeaderAccessor headers = MessageHeaderAccessor.getMutableAccessor(message);
works fine, the method 
private Message<?> getMessage(Message<?> message) {
		Object payload = message.getPayload();
		if (payload instanceof MessagingException) {
			MessagingException e = (MessagingException) payload;
			return e.getFailedMessage();
		}
		return message;
	}
change the HEADERS.

**Comment by juandesalas** [comment]
If i build an interceptor and copy message headers into messagingexception header works too.
	@Override
	public Message<?> preSend(Message<?> message, MessageChannel channel) {
		if (!(message instanceof ErrorMessage)) {
			return message;
		}
		MessagingException payload = (MessagingException) message.getPayload();
		Message<?> failedMessage = payload.getFailedMessage();
		failedMessage = MessageBuilder.fromMessage(failedMessage).copyHeaders(message.getHeaders()).build();
		return new ErrorMessage(new MessagingException(failedMessage, payload), message.getHeaders());
	}
