### ISSUE TITLE
will a javaagent version be developed?

### ISSUE THREAD

**Issue by Jaware** [spring-cloud/spring-cloud-sleuth#951]
will a javaagent version be developed?  sleuth on spring boot has a lot of shortcomings, our team want to use javaagent to replace sleuth,so i want to rewriten sleuth to support javaagent. maybe i can contribute some bit.

**Comment by marcingrzejszczak** [comment]
> sleuth on spring boot has a lot of shortcomings

what exactly do you mean?

**Comment by adriancole** [comment]
this isn't the best place to discuss a generic agent. you are basically asking where to find alternatives to sleuth, right. a more appropriate place is to look at zipkin proper where some work has been discussed in the past https://github.com/openzipkin/openzipkin.github.io/issues/62

**Comment by marcingrzejszczak** [comment]
Similar issue - https://github.com/spring-cloud/spring-cloud-sleuth/issues/688
