### ISSUE TITLE
http.status_code  and error tags not set for RestTemplate call

### ISSUE THREAD

**Issue by sabtharishi** [spring-cloud/spring-cloud-sleuth#952]
From Spring boot application, we are making calls to other services (nodejs). Nodejs does not implement any tracing mechanism yet so it just ignores trace headers. But when the nodejs app return 500 error, my Spring boot app does not add http.status_code or error tags to the Span. We are currently using RestTemplate to call nodejs service from Spring boot app.
In this case, I am seeing below tags with Span though
`
[ http.path=/v2/books ]
[ http.url=http://localhost/v2/books ]
[ http.method=PUT ]
[ http.host=localhost ]
`

**Comment by adriancole** [comment]
hmm we have tests that cover error status being added when not ok.

https://github.com/openzipkin/brave/blob/master/instrumentation/http-tests/src/main/java/brave/test/http/ITHttpClient.java#L227

Also, I routinely do this example which uses resttemplate with the other server down, which adds the error tag https://github.com/openzipkin/sleuth-webmvc-example

Did you add your own `HttpClientParser` by chance?

**Comment by marcingrzejszczak** [comment]
Yeah, a sample of what you're doing would be useful cause maybe I broke sth in Sleuth.

**Comment by Sabtharishi** [comment]
Thanks for getting back to me @adriancole and @marcingrzejszczak 
Actually,yesterday I tried  the same thing on the Spring boot application v1.5.9 Release having both calling & exposing apps and same behavior seen. I will upload the Spring boot version apps and share it with you once I have access to my other laptop.

**Comment by marcingrzejszczak** [comment]
Yeah, maybe let's start with the question that pops up when you file an issue. Which version of Sleuth are you using?

**Comment by sabtharishi** [comment]
Please refer these sample apps both implemented in Spring boot (Springboot - 1.5.10.RELEASE and Spring cloud - Edgware.SR3) 
1. https://github.com/sabtharishi/springboot-tracing app implements Sleuth and this app calls the other web service which will throw runtime exception. Please refer the doc for more info
2. https://github.com/sabtharishi/springboot-web - Does not implement Sleuth and throw runtime exception when #1 calls this service endpoint. 

Hope this would help. I also tested in 1.5.12.RELEASE and same result found

**Comment by marcingrzejszczak** [comment]
Sleuth in `1.3` never registered error status code AFAIR https://github.com/spring-cloud/spring-cloud-sleuth/blob/1.3.x/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java#L96 . That's because we didn't want to duplicate the logs. The errors were set on the Filter side - https://github.com/spring-cloud/spring-cloud-sleuth/blob/1.3.x/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilter.java#L435-L448 

How is it done in Zipkin now @adriancole ? Do you take care of duplicates? If the filter sets those (info about errors) values and the client interceptor also sets them?

**Comment by adriancole** [comment]
ah so in brave we would have no idea if a server would register an error or
not. moreover the client could error without the server and visa versa.
hence error handling is done at both sides regardless of status code or
exception.

**Comment by marcingrzejszczak** [comment]
Ok, so this is more of an enhancement than a bug. I think that the suggested solution is to upgrade to the `Finchley` release train where the Brave instrumentation takes a different approach.

**Comment by sabtharishi** [comment]
@adriancole @marcingrzejszczak just a question, is this applicable only to RestTemplate or even to Feign,  zuul etc as well? I am not sure if these are using RestTemplate internally. And what about http status code, do we add it when we are getting 4xx/5xx response from the service?
