### ISSUE TITLE
Feature: customize span name and tags for stream listeners

### ISSUE THREAD

**Issue by dhoffi** [spring-cloud/spring-cloud-sleuth#956]
similar to the "problem" on with ExtraFieldPropagation and logging on instrumented parts of spring-cloud-stream discussed in https://github.com/spring-cloud/spring-cloud-sleuth/issues/927#issuecomment-383880872

 when tagging a spring-cloud-stream `@SendTo(...)` or `@StreamListener(...)`

even if I set a tag on the currentSpan as the first thing in my business code...

        @StreamListener(...)
        public void transform(...) {
                SpanCustomizer spanCustomizer = sleuthTracer.currentSpanCustomizer();
                spanCustomizer.tag("some", "tag");

 the tag will only be propagated to zipkin if something will be sent to zipkin afterwards (as my span I am in already has started)

It would be nice to be able to tell the instrumented part (which starts the trace) that it should take custom values for the created Trace/Span, e.g. Tag Names, Span Name, Baggage Values.

    @SleuthSpanTag("key:value")
    @SleuthSpanName("myMessageReceiving")
    @StreamListener(...)
    public void myMessageReiving(...) {
         ...
    }

These values would be picked up and used by the instrumentation parts of e.g. spring-cloud-stream/integration, so that I see the tag in zipkin attached to the receiving span (`handle`)
and that the span has some name I can associate with my method and not a kind of anonymous `handle` which is the same name in all my `@StreamListener`s

(Again, this is just to have something I as a dev can decide to be the name/tag of the receiving/sending span, which is handled for me by spring instrumentation magic.)

hope it still makes sense what I am saying :)

**Comment by adriancole** [comment]
is this about tags or baggage (extra fields)? Looks like it is about tags (the code is very different depending on your answer)

**Comment by dhoffi** [comment]
it is all about: if the trace is started by an instrumentation or instrumentation will "add" a span to the trace (as this might be the case for e.g. spring-cloud-stream `@StreamListener` or `@SendTo`) I want my metadata in the current trace right from the beginning of the trace.
a) having my extra Baggage in the ExtraFieldPropagation right from the start of the trace (also to see it in log messages of the initiating instrumentation code)
b) being able to set tags and the name of the Trace/Span which the instrumentation code will use

So if I add e.g. annotations like suggested above, these would be picked up by the instrumentation code which will use the values on creation of the Trace/Span (name it, Tag it) and also being able to tell the instrumentation to put ExtraFieldPropagation values in the context and also in MDC

**Comment by adriancole** [comment]
ok can you rename this issue to customize span name for stream listeners?
The issue title confused me. we might need to reword the description a bit
and then elaborate how to accomplish this.

**Comment by marcingrzejszczak** [comment]
Related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/1062

**Comment by marcingrzejszczak** [comment]
`StreamListener` is deprecated so I'm closing this issue.
