### ISSUE TITLE
Sleuth once request can't have the same trace_id?

### ISSUE THREAD

**Issue by xuked325** [spring-cloud/spring-cloud-sleuth#959]
hello, i am sorry 。
I have a question to consult you
when i use 1.3.3 sleuth, I have two micro services a and b, 
like: the a port is 11016
```
@RequestMapping("/sservicea")
	public String sservicea() {
		LOG.log(Level.INFO, "calling trace service-b");
		return restTemplate.getForObject("http://localhost:11017/sserviceb", String.class);
	}
```
b:

```
@RequestMapping("/sserviceb")
	public String sserviceb() {
		LOG.log(Level.INFO, "calling trace service-c");
		return "OK";
	}
```

but i call http://localhost:11017/sservicea 
i see the logs . there are two trace_id.
so zipkin can't draw the dependence Graph
sorry my enlisgh is bad.

**Comment by marcingrzejszczak** [comment]
You have a working example here - https://github.com/openzipkin/sleuth-webmvc-example. Just build your solution around what's explained there.

**Comment by xuked325** [comment]
sorry you mistake me . the demo is working well use 1.3.0,but use 1.3.3 work  bad. once request but hava two trace_id

**Comment by marcingrzejszczak** [comment]
If you think that this is not working, please provide a sample that replicates the issue.

**Comment by xuked325** [comment]
my demo is 3 parts
1 part:
main java 
@EnableZipkinServer
@SpringBootApplication
public class ZipKinServerApplication {

	public static void main(String[] args) {
		SpringApplication.run(ZipKinServerApplication.class, args);
	}
}
pom:
<spring-boot.version>1.5.10.RELEASE</spring-boot.version>
<spring-cloud.version>Edgware.SR3</spring-cloud.version>
<dependencys>
spring-boot-starter
spring-boot-starter-web
zipkin-autoconfigure-ui
zipkin-server
zipkin-autoconfigure-storage-mysql
spring-boot-starter-jdbc
mysql-connector-java
zipkin-autoconfigure-collector-rabbitmq
</dependencys>
yml:
server:
  port: 11011
zipkin: 
  collector:
    rabbitmq:
      addresses: localhost:5672
      password: guest
      username: guest
      queue: zipkin
  storage: 
    type: mysql
spring:
  application:
    name: zipkinserver
  sleuth: 
    enabled: false
  datasource:
    name: zipkin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    schema: classpath:/zipkin.sql
    initialize: true
    continue-on-error: true

2 part  mircoserve A
main java 
@RestController
@SpringBootApplication
public class SampleFeignApplication {
	private static final Logger LOG = Logger.getLogger(SampleFeignApplication.class.getName());

	@Autowired
	private RestTemplate restTemplate;

	@Bean
	public RestTemplate getRestTemplate() {
		return new RestTemplate();
	}

	@Bean
	public AlwaysSampler defaultSampler() {
		return new AlwaysSampler();
	}

	public static void main(String[] args) {
		SpringApplication.run(SampleFeignApplication.class, args);
	}

	@RequestMapping("/sservicea")
	public String sservicea() {
		LOG.log(Level.INFO, "calling trace service-b");
		return restTemplate.getForObject("http://localhost:11017/sserviceb", String.class);
	}
}
pom：
<spring-boot.version>1.5.10.RELEASE</spring-boot.version>
<spring-cloud.version>Edgware.SR3</spring-cloud.version>
spring-boot-starter
spring-cloud-starter-zipkin
spring-rabbit
yml：
server:
  port: 11016
spring: 
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin: 
    rabbitmq: 
      queue: zipkin 
  application:
    name: sera
2 part  mircoserve B like A
just the functon has diff
@RequestMapping("/sserviceb")
	public String sservicea() {
		LOG.log(Level.INFO, "calling trace service-b");
		return "ok";
	}

**Comment by marcingrzejszczak** [comment]
No, please don't put the unformatted code in the issue. How am I supposed to even read it? Can you read what you pasted?

Upload your sample to Github. Also don't use the `@enablezipkinserver`. Have you read the documentation? This is deprecated. Please read the documentation, understand what you're doing. Read the sample that I've shown you and then I'm more than certain that everything will work for you. 
 Here you have another example https://github.com/spring-cloud-samples/sleuth-documentation-apps/tree/edgware . 

I'm locking this issue. If you're unable to solve this problem please ask on Stackoverflow cause there's no issue with Sleuth here but with your setup.
