### ISSUE TITLE
Too many Span Name for RESTful uri 

### ISSUE THREAD

**Issue by meifans** [spring-cloud/spring-cloud-sleuth#965]
Question:
When I used zipkin with spring mvc and feign，zipkin reported Span Name like this:

/v1/resources/afdfdsfdsafdsf
/v1/resources/fdsfdsfdsfdsfs
... or
/v1/resources/fdsfsdfsdfsdaf/start
/v1/resources/ffdsfsdfsdffds/start

Because every resource has unique id ,the Span Name drop-down list in the main UI will be quite long and might cause performance issues.

![wechatimg1](https://user-images.githubusercontent.com/12523371/39463096-868f3634-4d48-11e8-8b65-b7ad7f811e8b.jpeg)

Any help or suggestion will be appreciated. 🙂

🥇 By the way , SpanAdjuster doesn't have any information about method which spring mvc mapped . How can I adjust span name to class+method？

**Comment by marcingrzejszczak** [comment]
I think you should upgrade to Sleuth 2.0 and make the URI parametrized. With Brave we do discern those and you would have `/api/1/in/vehicle/{id}`

**Comment by meifans** [comment]
@marcingrzejszczak thanks
