### ISSUE TITLE
When Sleuth Zipkin wiil support Spring Cloud Gateway ？

### ISSUE THREAD

**Issue by wxiaoqi** [spring-cloud/spring-cloud-sleuth#969]
# Question
When Slueth Zipkin wiil support Spring Cloud Gateway ？
Today when I test the sleuth and Zipkin ，I found that Zipkin trace does not record the gateway‘s trace, but the sleuth log has written ! 

# Detail
Could u give me some ideas to support the Gateway and I will pr the code for this project. If u are trying to support it, please tell me when.

Thank you!

**Comment by marcingrzejszczak** [comment]
Sleuth in version 2.0 supports Spring Cloud Gateway out of the box

**Comment by wxiaoqi** [comment]
Could u show me how to use Sleuth Zipkin in Spring Cloud Gateway?

**Comment by bjlhx15** [comment]
> Could u show me how to use Sleuth Zipkin in Spring Cloud Gateway?
hello ,
How are you using now?I also met。Please give ideas。

**Comment by bjlhx15** [comment]
> Sleuth in version 2.0 supports Spring Cloud Gateway out of the box

hello ,
How are you using now?I also met。Please give ideas。
version
        <spring-cloud.version>Finchley.SR1</spring-cloud.version>
        <spring-boot.version>2.0.4.RELEASE</spring-boot.version>
pom
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zipkin</artifactId>
        </dependency>
I visit restapi by the gateway, Zipkin trace does not record the gateway‘s trace, Zipkin trace does not record the service‘s trace .but Direct access to the service is recordable。
