### ISSUE TITLE
Web skip patterns don't consider server.servlet.context-path

### ISSUE THREAD

**Issue by shakuzen** [spring-cloud/spring-cloud-sleuth#971]
The `SkipPatternProvider` made in auto-configuration considers when `management.server.servlet.context-path` is set, but it does not consider when just `server.sevlet.context-path` is set.

https://github.com/spring-cloud/spring-cloud-sleuth/blob/434e06c3ce4c6471cb77e88ee317390dfc22c4bf/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java#L49-L96

The following test demonstrates this issue and will fail with current snapshots:

```java
@RunWith(SpringRunner.class)
@SpringBootTest(classes = DemoSleuthSkipApplicationTests.Config.class,
		webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
		properties = {"spring.sleuth.sampler.probability:1",
				"management.endpoints.web.exposure.include:*",
				"server.servlet.context-path:/context-path"})
public class DemoSleuthSkipApplicationTests {

	@Autowired
	ArrayListSpanReporter accumulator;

	@LocalServerPort
	int port;

	@Test
	public void should_not_sample_skipped_endpoint_with_context_path() {
		new RestTemplate().getForObject("http://localhost:" + port + "/context-path/actuator/health", String.class);
		then(Tracing.current().tracer().currentSpan()).isNull();
		then(this.accumulator.getSpans()).hasSize(0); // this fails
	}

	@EnableAutoConfiguration
	@Configuration
	public static class Config {

		@Bean ArrayListSpanReporter reporter() {
			return new ArrayListSpanReporter();
		}
	}
}
```

**Comment by shakuzen** [comment]
@marcingrzejszczak the fix for this doesn't look right to me. It looks like it will skip sampling for ALL endpoints including user-defined, non-actuator ones when a Servlet context path is set (whereas before it would never skip any endpoints). I was expecting one of the following would be done:

- the servlet context path would be (effectively) prepended to each of the OR `|` concatenated skip patterns
- alternatively, the context path would be subtracted from the path when matching the patterns (in `SleuthHttpSampler`, perhaps?)

The former makes for a more complicated regex pattern construction. For example, context path `/bla` without a separate management context would perhaps be `/bla(/foo.*|/bar.*)` if the skip pattern is set to `/foo.*|/bar.*`.
The later requires the HttpSampler to be context-path aware.

A test with an endpoint that should be sampled (in other words, not match the skip pattern) should show the current issue and test its resolution.

For example, assuming the context path is set to `/bla` and there is a user-defined endpoint at `/hello`, then a GET request for it would be to `/bla/hello` and it should not be skipped by the default pattern.

```java
then(pattern.matcher("/bla/hello").matches()).isFalse();
```
The above fails with the current implementation.
A request to an Actuator endpoint like `/bla/actuator/health` should be skipped.

```java
then(pattern.matcher("/bla/actuator/health").matches()).isTrue();
```

**Comment by marcingrzejszczak** [comment]
Yeah you're right. I hastened with this. I'll revert it and consider adding it for 2.1

**Comment by shakuzen** [comment]
Looks like there is still a problem with the fix. Now I'm seeing *all* endpoints get skipped when a `server.servlet.context-path` is set (because it is appended to the end of the pattern like `|context-path.*`). Below is a patch for the integration test that demonstrates the issue.

```diff
Index: spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/issues/issue971/DemoSleuthSkipApplicationTests.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/issues/issue971/DemoSleuthSkipApplicationTests.java	(revision 26417a27079bf353cacdfd25eed8e29b741d1893)
+++ spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/issues/issue971/DemoSleuthSkipApplicationTests.java	(date 1543217273000)
@@ -30,6 +30,8 @@
 import org.springframework.context.annotation.Bean;
 import org.springframework.context.annotation.Configuration;
 import org.springframework.test.context.junit4.SpringRunner;
+import org.springframework.web.bind.annotation.GetMapping;
+import org.springframework.web.bind.annotation.RestController;
 import org.springframework.web.client.RestTemplate;
 
 import static org.assertj.core.api.BDDAssertions.then;
@@ -60,11 +62,26 @@
 		then(this.accumulator.getSpans()).hasSize(0);
 	}
 
+	@Test
+	public void should_sample_non_actuator_endpoint_with_context_path() {
+		new RestTemplate().getForObject(
+				"http://localhost:" + this.port + "/context-path/something",
+				String.class);
+
+		then(this.tracer.currentSpan()).isNull();
+		then(this.accumulator.getSpans()).hasSize(1);
+	}
+
 	@EnableAutoConfiguration(exclude = RabbitAutoConfiguration.class)
 	@Configuration
 	@DisableSecurity
+	@RestController
 	public static class Config {
 
+		@GetMapping("something")
+		void doNothing() {
+		}
+
 		@Bean
 		ArrayListSpanReporter reporter() {
 			return new ArrayListSpanReporter();
```

**Comment by melloware** [comment]
+1. I am using Greenwich.M3 and spent all day on this bug too.  Everything works fine without a server.servlet.context-path.  As soon as I add it all of my Zipkin traces stop being sent.    Is there some workaround we can apply to make it work with server.servlet-context-path?

**Comment by melloware** [comment]
I opened a new issue: https://github.com/spring-cloud/spring-cloud-sleuth/issues/1146

In there I posted my "hack" workaround.
