### ISSUE TITLE
Span informations missing when logging with DispatcherHandler starting from Sleuth 2.0.0.M8

### ISSUE THREAD

**Issue by jhaeyaert** [spring-cloud/spring-cloud-sleuth#973]
Hi,

Here are the versions I use :

- Spring Framework version : 5.0.4.RELEASE
- Spring Boot version : 2.0.1.RELEASE
- Spring Cloud Sleuth : 2.0.0.RC1 (via Finchley.RC1 release train)

Using the latest version of spring cloud Sleuth, logging handled requests using o.s.web.reactive.DispatcherHandler (ie : Webflux equivalent to MVC o.s.web.servlet.DispatcherServlet) does not display span informations.

`2018-05-04 15:06:06.109 DEBUG [myapp,,,] 73025 --- [        http-54] o.s.web.reactive.DispatcherHandler       : Processing GET request for [http://localhost:8080/test]
`

If I switch back to Sleuth 2.0.0.M7 and Spring Boot 2.0.0.RELEASE, things are working as expected (the problem seems starting from Sleuth 2.0.0.M8 with both Spring Boot 2.0.1.RELEASE and 2.0.0.RELEASE) :

`2018-05-04 15:09:12.449 DEBUG [myapp,394cf756c1f3a695,394cf756c1f3a695,false] 73218 --- [        http-52] o.s.web.reactive.DispatcherHandler       : Processing GET request for [http://localhost:8080/test]
`

This strange behavior has impacts on log correlation.
Does someone have any idea about this problem (is it spring boot or spring cloud sleuth ?) ?

Thank you.

**Comment by marcingrzejszczak** [comment]
Is the problem there when you use snapshots? Does it affect your WebFluxes?

**Comment by marcingrzejszczak** [comment]
Also is it the case each time or only for the first request?

**Comment by marcingrzejszczak** [comment]
That would be great!

**Comment by jhaeyaert** [comment]
Hi again,

You can find a simple spring boot project (I used spring initializr for convenience) here : [https://github.com/jhaeyaert/issue-sleuth-logging](https://github.com/jhaeyaert/issue-sleuth-logging)

Follow these steps to reproduce the problem :
```bash
git clone https://github.com/jhaeyaert/issue-sleuth-logging
./mvnw clean package spring-boot:run
```

The server will start and if you make a curl on localhost:8080 you will have a 404 with expected working logs (ie : with span id). Ex: 

```
2018-05-05 00:09:28.227 DEBUG [issue-sleuth-logging,283e076baa0d291b,283e076baa0d291b,false] 81648 --- [ctor-http-nio-2] o.s.web.reactive.DispatcherHandler       : Processing GET request for [http://localhost:8080/]
2018-05-05 00:09:28.314  WARN [issue-sleuth-logging,283e076baa0d291b,283e076baa0d291b,false] 81648 --- [ctor-http-nio-2] .a.w.r.e.DefaultErrorWebExceptionHandler : Failed to handle request [GET http://localhost:8080/]: Response status 404
```

Now if you update pom.xml and change `<spring-cloud.version>Finchley.M8</spring-cloud.version>` to `<spring-cloud.version>Finchley.M9</spring-cloud.version>` then restart the server you will now have DispatcherHandler log without span id. Ex : 

```
2018-05-05 00:17:52.828 DEBUG [issue-sleuth-logging,,,] 81781 --- [ctor-http-nio-2] o.s.web.reactive.DispatcherHandler       : Processing GET request for [http://localhost:8080/]
2018-05-05 00:17:52.873  WARN [issue-sleuth-logging,72307898ff15112a,72307898ff15112a,false] 81781 --- [ctor-http-nio-2] .a.w.r.e.DefaultErrorWebExceptionHandler : Failed to handle request [GET http://localhost:8080/]: Response status 404
```

Note : I take a long time to make it work until I discover that whatever the version of Sleuth, If I remove the spring-boot-starter-actuator dependency then span id will never be logged by the DispatcherHandler. If the spring-boot-starter-actuator is added It works only with version <= Finchley.M8 (--> sleuth 2.0.0.M7)

I hope this will help you to figure out the problem.

**Comment by marcingrzejszczak** [comment]
I'll check it out. But actually, does it really matter if that particular line has the context passed or not? If doesn't influence your code that you write in the controllers right? So this is not a blocker, it's more of an inconvenience?

**Comment by marcingrzejszczak** [comment]
This is the stacktrace of the "working" (reactor 3.1.5, Boot 2.0.0, Sleuth 2.0.0.M8) version:

```
handle:149, DispatcherHandler (org.springframework.web.reactive)
lambda$filter$0:79, DefaultWebFilterChain (org.springframework.web.server.handler)
get:-1, 1073781602 (org.springframework.web.server.handler.DefaultWebFilterChain$$Lambda$447)
subscribe:44, MonoDefer (reactor.core.publisher)
subscribe:46, MonoLift (reactor.core.publisher)
subscribe:61, MonoPeekTerminal (reactor.core.publisher)
subscribe:46, MonoLift (reactor.core.publisher)
onNext:150, MonoFlatMap$FlatMapMain (reactor.core.publisher)
onNext:81, ScopePassingSpanSubscriber (org.springframework.cloud.sleuth.instrument.reactor) [2]
complete:1069, Operators$MonoSubscriber (reactor.core.publisher)
signal:241, MonoZip$ZipCoordinator (reactor.core.publisher)
onNext:323, MonoZip$ZipInner (reactor.core.publisher)
onNext:81, ScopePassingSpanSubscriber (org.springframework.cloud.sleuth.instrument.reactor) [1]
request:1626, Operators$ScalarSubscription (reactor.core.publisher)
request:69, ScopePassingSpanSubscriber (org.springframework.cloud.sleuth.instrument.reactor)
onSubscribe:312, MonoZip$ZipInner (reactor.core.publisher)
onSubscribe:63, ScopePassingSpanSubscriber (org.springframework.cloud.sleuth.instrument.reactor)
subscribe:54, MonoJust (reactor.core.publisher)
...
```

Notice that the `ScopePassingSpanSubscriber` gets called and it's responsible for setting the tracing data in the scope.

This is the stacktrace of the "not working" (reactor 3.1.6, Boot 2.0.1, Sleuth 2.0.0.RC1) version:

```
handle:149, DispatcherHandler (org.springframework.web.reactive)
lambda$filter$0:79, DefaultWebFilterChain (org.springframework.web.server.handler)
get:-1, 604987166 (org.springframework.web.server.handler.DefaultWebFilterChain$$Lambda$496)
subscribe:44, MonoDefer (reactor.core.publisher)
subscribe:61, MonoPeekTerminal (reactor.core.publisher)
subscribe:46, MonoLift (reactor.core.publisher)
onNext:150, MonoFlatMap$FlatMapMain (reactor.core.publisher)
complete:1073, Operators$MonoSubscriber (reactor.core.publisher)
signal:241, MonoZip$ZipCoordinator (reactor.core.publisher)
onNext:323, MonoZip$ZipInner (reactor.core.publisher)
request:1630, Operators$ScalarSubscription (reactor.core.publisher)
onSubscribe:312, MonoZip$ZipInner (reactor.core.publisher)
subscribe:54, MonoJust (reactor.core.publisher)
...
```

For some reason the `ScopePassingSpanSubscriber` is ignored, even though, it's constructed 

```
2018-05-04 22:59:14.809 TRACE [issue-sleuth-logging,,,] 81337 --- [ctor-http-nio-2] o.s.c.s.i.r.ScopePassingSpanSubscriber   : Root span [NoopSpan{context=bd51d8c284b04ece/bd51d8c284b04ece}], context [Context1{class brave.Span=NoopSpan{context=bd51d8c284b04ece/bd51d8c284b04ece}}]
```

So what changed in the code of Sleuth?

**OLD VERSION**

```java
private static final Predicate<Scannable> POINTCUT_FILTER =
			s ->  !(s instanceof Fuseable.ScalarCallable);
      
public static <T> Function<? super Publisher<T>, ? extends Publisher<T>> scopePassingSpanOperator(
			Tracing tracing) {
		return Operators.lift(POINTCUT_FILTER, ((scannable, sub) -> {
			//do not trace fused flows
			if(scannable instanceof Fuseable && sub instanceof Fuseable.QueueSubscription){
				return sub;
			}
			return new ScopePassingSpanSubscriber<>(
					sub,
					sub != null ? sub.currentContext() : Context.empty(),
					tracing);
		}));
	}
```

**NEW VERSION**

```java
private static final Predicate<Scannable> POINTCUT_FILTER =
			s ->  !(s instanceof ConnectableFlux) && !(s instanceof Fuseable.ScalarCallable) && s.isScanAvailable();


public static <T> Function<? super Publisher<T>, ? extends Publisher<T>> scopePassingSpanOperator(
			BeanFactory beanFactory) {
		return Operators.lift(POINTCUT_FILTER, ((scannable, sub) -> {
			//do not trace fused flows
			if(scannable instanceof Fuseable && sub instanceof Fuseable.QueueSubscription){
				return sub;
			}
			if (contextRefreshed(beanFactory)) {
				if (log.isTraceEnabled()) {
					log.trace("Spring Context already refreshed. Creating a scope "
							+ "passing span subscriber with Reactor Context "
							+ "[" + sub.currentContext() + "] and name [" + scannable.name() + "]");
				}
				return scopePassingSpanSubscription(beanFactory, scannable, sub).get();
			}
			if (log.isTraceEnabled()) {
				log.trace("Spring Context is not yet refreshed, falling back to lazy span subscriber. "
						+ "Reactor Context is [" + sub.currentContext() + "] and name is [" + scannable.name() + "]");
			}
			return new LazySpanSubscriber<T>(
					scopePassingSpanSubscription(beanFactory, scannable, sub)
			);
		}));
	}
```
	private static <T> SpanSubscriptionProvider scopePassingSpanSubscription(
			BeanFactory beanFactory, Scannable scannable, CoreSubscriber<? super T> sub) {
		return new SpanSubscriptionProvider(
				beanFactory,
				sub,
				sub.currentContext(),
				scannable.name()) {
			@Override SpanSubscription newCoreSubscriber(Tracing tracing) {
				return new ScopePassingSpanSubscriber<T>(
						sub,
						sub != null ? sub.currentContext() : Context.empty(),
						tracing);
			}
		};
	}
```

There's obvioulsy more logic, but the concept is the same. In all the logs we can see that the context got refereshed so actually no lazy span creation happens. It's eager, in the same way as it used to be. The one thing that differes is `s ->  !(s instanceof ConnectableFlux) ` in the new version. I needed to add that for some reasons, but maybe that's the reason for the lack of scope in the dispatcher?

I guess I'll need help from @simonbasle or @smaldini . Fortunately this is not a blocker, it's just an inconvinience, since the scope gets set just after the dispatcher is called.

**Comment by jhaeyaert** [comment]
Hi,

Thank you for your feedback on this issue. Indeed this is not a blocker but when I discovered this problem I asked myself if this could occur somewhere else or have any other side effects.

The only problem I have is for log correlation. Enabled logging over Dispatcher allows to have at least one log with span informations for each http invocation. I suppose this can be compensated using Zipkin or something else. I hope this issue does not affect the way spans are reported to Zipkin cause I remember I had some troubles with that too, spans were never send to Zipkin until I play with maven dependencies and downgrade some dependencies, then it started to work. I will take some time to double check and open another issue if the problem is proven.

Thx

**Comment by simonbasle** [comment]
Root cause is that `Operators.lift` is very limited in 3.1.x (see reactor/reactor-core#1105).

Here it is the adding of `s.isScanAvailable()` that causes the issue, because in reactor 3.1.x a lot of operators are not implementing `Scannable`. The `Operators.lift` still tries to convert them to `Scannable` to expose them to user code (here the sleuth logic), but that hides the actual instances behind a constant `UNAVAILABLE_SCAN`, which never passes this test.

On the other hand, if the test is removed, the later check for `instanceof Fuseable` will sometimes fail to detect `Fuseable` operators, for the same reason (some `Fuseable` operators are not implementing `Scannable` and the lift function exposes them as a `UNAVAILABLE_SCAN`, making the test fail to discover a fuseable that Sleuth cannot replace).

The workaround is to write a Sleuth-specific `Function<Publisher, Publisher>` that will perform all the checks directly on the source `Publisher` then delegate to the `Operators.lift()` for the decoration.

This function should look like this (to be refined):

```java
public static <T> Function<? super Publisher<T>, ? extends Publisher<T>> scopePassingSpanOperator(
			BeanFactory beanFactory) {
        return sourcePub -> {
            //do the checks directly on actual original Publisher
            if (sourcePub instanceof Fuseable //Sleuth can't handle that
                || sourcePub instanceof Fuseable.ScalarCallable //IIRC Sleuth can't handle that
                || sourcePub instanceof ConnectableFlux //Operators.lift can't handle that
                || sourcePub instanceof GroupedFlux  //Operators.lift can't handle that
            ) {
                return sourcePub;
            }                
		    return Operators.lift((scannable, sub) -> { //no more POINTCUT_FILTER since mecanism is broken
			//hopefully with the Fuseable rejection, QueueSubscription shouldn't happen
              //rest of the logic unchanged...
              //if (contextRefreshed(beanFactory)) {
				//...
            });
		};
	}
```

**Comment by marcingrzejszczak** [comment]
Related issue - https://github.com/reactor/reactor-core/issues/1105

**Comment by marcingrzejszczak** [comment]
@jhaeyaert can you double check, once the snapshots are built, that everything is ok?

**Comment by jhaeyaert** [comment]
Yes no problem I will test that tomorrow.
