### ISSUE TITLE
Feign.Builder from FeignClientsConfiguration overrides SleuthFeignBuilder

### ISSUE THREAD

**Issue by dmarkhas** [spring-cloud/spring-cloud-sleuth#977]
I am trying to get Sleuth to work correctly with feign clients constructed with Feign.builder. Based on previous posts here and looking at the code, I understand that I can rely on `SleuthFeignBuilder` to return a builder that wraps the client in the Trace functionality.

However, I'm not able to inject the correct builder in my Spring application - it seems that the default builder, from `org.springframework.cloud.netflix.feign.FeignClientsConfiguration` overrides the Sleuth builder from `org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignClientAutoConfiguration` since they are both marked as `ConditionalOnMissingBean` and the `FeignClientsConfiguration` class gets loaded first.

This is the builder in `FeignClientsConfiguration`:

```
	@Bean
	@Scope("prototype")
	@ConditionalOnMissingBean
	public Feign.Builder feignBuilder(Retryer retryer) {
		return Feign.builder().retryer(retryer);
	}
```

And this is the builder in `TraceFeignClientAutoConfiguration`:

```
	@Bean
	@ConditionalOnMissingBean
	@Scope("prototype")
	@ConditionalOnProperty(name = "feign.hystrix.enabled", havingValue = "false", matchIfMissing = true)
	Feign.Builder feignBuilder(BeanFactory beanFactory) {
		return SleuthFeignBuilder.builder(beanFactory);
	}
```

How can I get the 2nd one, and not the first?

**Comment by marcingrzejszczak** [comment]
Are you able to setup a sample that replicates this? Also, you haven't mentioned which version you are using?

**Comment by dmarkhas** [comment]
I am using spring-cloud-sleuth-core 1.3.3.RELEASE and spring-cloud-netflix-core 1.4.4.RELEASE.
I will try to setup a sample but can you please confirm if I am even going down the right path here? I am using Spring Cloud Discovery and building Feign clients with the builder, so what I really need is to get an instance of TraceLoadBalancerClient, which seems that only the builder in TraceFeignClientAutoConfiguration knows how to return, right ?

**Comment by marcingrzejszczak** [comment]
I don't really know if you are because you're the first one to say that something is not working fine and the feature is out there since a long time.

**Comment by ezraroi** [comment]
@marcingrzejszczak which of the builders do you expect us to get when we inject `@Feign.Builder`?

Looks like there is no order between the, their auto configuration files

**Comment by marcingrzejszczak** [comment]
The `TraceFeignClientAutoConfiguration` is an autoconfiguration. `FeignClientsConfiguration` is not an autoconfiguration. It's part of the `FeignContext`. `FeignContext` is setup in `FeignAutoConfiguration`. We do have `@AutoConfigureBefore(FeignAutoConfiguration.class)`.

**Comment by dmarkhas** [comment]
@marcingrzejszczak your last comment helped me pinpoint the issue - there was an explicit Import of FeignClientsConfiguration in a different place in the code that caused this conflict, after removing it everything works fine!
