### ISSUE TITLE
spring-cloud-sleuth removes the id and timestamp headers set by spring-integration

### ISSUE THREAD

**Issue by karel1980** [spring-cloud/spring-cloud-sleuth#978]
I have a spring integration flow which looks like this:

  ```
       return IntegrationFlows.from("inboundChannel")
                .wireTap(flow -> flow.handle(msg -> System.out.println("Timestamp" + msg.getHeaders().get(MessageHeaders.TIMESTAMP))))
            ... .get();
```

Before adding the org.springframework.cloud:spring-cloud-starter-sleuth dependency this would print out the timestamp as expected.
After adding the dependency this is showing a null value for the timestamp. (same goes for the id header).

(This breaks e.g. TimeoutCountSequenceSizeReleaseStrategy because it will throw an NPE when auto-unboxing the timeout to a primitive long).

I'm using Spring Integration 5.0.4.RELEASE and org.springframework.cloud:spring-cloud-starter-sleuth:2.0.0.RC1

**Comment by marcingrzejszczak** [comment]
That's highly unfortunate. Do you have a sample we could play with?

**Comment by karel1980** [comment]
I'll provide you a smallish example. I can't send you the whole project ;)

**Comment by marcingrzejszczak** [comment]
Smallish sounds perfect :)

**Comment by karel1980** [comment]
[demo.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2001308/demo.zip)
Here you go. I hope this is fine. If you run the test you'll see that it writes a message with timestamp 'null' to stdout. If you remove the sleuth starter dependency and run the test again, you'll get the  correct timestamp.

**Comment by marcingrzejszczak** [comment]
I've checked against your sample and seems to be ok. Can you wait for the snapshots to be built and double check if I haven't made any mistakes?

**Comment by karel1980** [comment]
I'll give it a go.
