### ISSUE TITLE
SpanInjector migration guide

### ISSUE THREAD

**Issue by marco-primiceri** [spring-cloud/spring-cloud-sleuth#981]
Hi There,

It seems that the `SpanInjector` has been removed in [M6](https://github.com/spring-cloud/spring-cloud-sleuth/pull/829) although I could not find anything in the [migration guide](https://github.com/spring-cloud/spring-cloud-sleuth/wiki/Spring-Cloud-Sleuth-2.0-Migration-Guide) about how  to migrate to a new implementation (if any) or whether the feature has been removed entirely (hence it is now using Brave instead).

Also, do you mind updating the docs which still say:
> Sleuth includes default logic to join a trace across HTTP or messaging boundaries. For example, HTTP propagation works over Zipkin-compatible request headers. This propagation logic is defined and customized through SpanInjector and SpanExtractor implementations.

Thanks!
Marco

**Comment by marcingrzejszczak** [comment]
Great suggestions!

migration updated - https://github.com/spring-cloud/spring-cloud-sleuth/wiki/Spring-Cloud-Sleuth-2.0-Migration-Guide#spaninjector--spanextractor
docs fixed - https://github.com/spring-cloud/spring-cloud-sleuth/commit/03763da653bba5dc2070c481b42b41f9b214d160

**Comment by marco-primiceri** [comment]
Thanks for that Marcin, much appreciated!

**Comment by marcingrzejszczak** [comment]
No problem, great catch! I haven't noticed that this piece is missing.
