### ISSUE TITLE
How and where to see the trace  UI ?

### ISSUE THREAD

**Issue by ExtremeYu** [spring-cloud/spring-cloud-sleuth#987]
like this 
![dependencies](https://user-images.githubusercontent.com/16620268/40358568-3547425c-5df2-11e8-8daf-6e9c09a91414.png)

**Comment by ExtremeYu** [comment]
the stream server is deprecated,where to open the UI page?

**Comment by marcingrzejszczak** [comment]
If you use the standard openzipkin zipkin server instead of the deprecated one then you get it out of the box. In case of further questions please ping the Zipkin repo

**Comment by ExtremeYu** [comment]
i dont understand what you mean. but the reference shown the ui page .

**Comment by marcingrzejszczak** [comment]
If you check it out https://github.com/openzipkin/zipkin/blob/master/README.md#quick-start you'll see how to run the zipkin server and you get the view out of the box
