### ISSUE TITLE
Basic health metrics

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#99]
Arising from some discussions, it seems the most basic primitives we need to assess the health of the tracing system are spans accepted vs dropped.

If we have these metrics on the producer side (ex boot apps) and the consumer side (stream listener), we can get at least a basic signal of health.

This topic was discussed in brave, but I can add more context and opinions here, if it could help.

FWIW, here is the callback brave provides to address this issue. Note that the consuming callback would be quite similar. In any case, this sort of callback is easy to bind to any number of metrics systems.

```java
public interface SpanCollectorMetricsHandler {

    /**
     * Called when spans are submitted to SpanCollector for processing.
     *
     * @param quantity the number of spans accepted.
     */
    void incrementAcceptedSpans(int quantity);

    /**
     * Called when spans become lost for any reason and won't be delivered to the target collector.
     *
     * @param quantity the number of spans dropped.
     */
    void incrementDroppedSpans(int quantity);

}
```

See https://github.com/openzipkin/brave/pull/101

**Comment by marcingrzejszczak** [comment]
We can somehow connect this with Codehale metrics and add this to health endpoint

**Comment by marcingrzejszczak** [comment]
In progress - https://github.com/spring-cloud/spring-cloud-sleuth/pull/123/files
