### ISSUE TITLE
trace mysql use "brave-instrumentation-mysql" is not using 

### ISSUE THREAD

**Issue by guangmingchen** [spring-cloud/spring-cloud-sleuth#991]
<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-sleuth</artifactId>
				<version>2.0.0.RC1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

                       <dependency>
			<groupId>io.zipkin.brave</groupId>
			<artifactId>brave-instrumentation-mysql</artifactId>
			<version>4.13.1</version>
		</dependency

**Comment by adriancole** [comment]
if you want us to help you have to stop re-opening issues and use gitter instead ok? 
https://gitter.im/spring-cloud/spring-cloud-sleuth

re-opening issues can cause some annoyance. you were asked to not open an issue and did it again. Moreover you opened an issue after already creating this one.. please don't behave like this as we want to help but it is hard when annoyed ok?

https://github.com/openzipkin/sleuth-webmvc-example/issues/13

**Comment by guangmingchen** [comment]
This problem has not been dealt with completely, you close, this behavior is too responsible, the first use of this, can not be more patient?

**Comment by guangmingchen** [comment]
I'm trying to make my point. How do you feel so impatient

**Comment by guangmingchen** [comment]
Your attitude of forcing closure without solving the problem is really disappointing

**Comment by guangmingchen** [comment]
![image](https://user-images.githubusercontent.com/38786800/40528317-354ca3c2-6023-11e8-8851-93426289df2a.png)

**Comment by adriancole** [comment]
We've asked you to use gitter. that's how we support things. This needs to be investigated as a problem before using an issue. As mentioned in the issue template, issues are used for changes to the codebase. I don't think a change will occur here in this repository. Please don't make us block you.

**Comment by marcingrzejszczak** [comment]
I also asked you multiple times to provide your full codebase and instructions on how to replicate the issue. Also, I've asked you if you followed the guidelines in the brave-mysql instrumentation repo. You have provided no feedback and kept ignoring my questions.

**Comment by guangmingchen** [comment]
I didn't even come and provide the full code, so you shut down the problem

**Comment by guangmingchen** [comment]
![image](https://user-images.githubusercontent.com/38786800/40529133-16872680-6026-11e8-8231-6a90ab7f43b6.png)

**Comment by adriancole** [comment]
you posted the issue twice.. here after posting here less than a day ago
https://github.com/openzipkin/sleuth-webmvc-example/issues/13

why are you not joining gitter like asked? do you feel that doing the
opposite will make things better for either you or us, or the hundred
people who are alerted when you post issues like this?

The request on the issue is to please try the example, and if report back
on gitter what happens. please do that and stop pasting things at us. it is
easier and we can be friends as opposed to being frustrated ok?
