### ISSUE TITLE
Setting up a springCloud App to send span to Zipkin via Kafka

### ISSUE THREAD

**Issue by danielsouza85** [spring-cloud/spring-cloud-sleuth#992]
I´m new with zipkin and sleuth, but I´m trying to setup a test aplication that report the messages to a Zipkin server via kafka.
Everything seams to work, but at the Zipkin UI page, any traces are shown.

At the microservice sprong boot, I´ve set the dependencies in the pom.xml as bellow:
           <spring-cloud.version>Dalston.SR5</spring-cloud.version>

	    <dependency>
	       <groupId>org.springframework.cloud</groupId>
	       <artifactId>spring-cloud-starter-zipkin</artifactId>
	   </dependency>
	   <dependency>
	       <groupId>org.springframework.kafka</groupId>
	       <artifactId>spring-kafka</artifactId>
	   </dependency>
	   <dependency>
	       <groupId>org.springframework.cloud</groupId>
	       <artifactId>spring-cloud-sleuth-zipkin-stream</artifactId>
	   </dependency>
	   <dependency>
	       <groupId>org.springframework.cloud</groupId>
	       <artifactId>spring-cloud-stream-binder-kafka</artifactId>
	   </dependency>

In aplication.properties, I have the following:
	   server.port = 9081
	   spring.application.name = zipkin-server1
	   spring.zipkin.sender.type = kafka
	   spring.zipkin.enabled=false
	   spring.sleuth.enabled=true
	   spring.cloud.stream.kafka.binder.brokers = xxx.xxx.xxx.xx:9092
	   spring.cloud.stream.kafka.binder.zkNodes = xxx.xxx.xxx.xx:2181
	   spring.cloud.stream.default.contentType = application/json
	   spring.cloud.stream.bindings.output.destination=sleuth

When start the 2 microservides, I can see the parameters at startup and a warning log:

2018-05-29 00:43:32.725  INFO [zipkin-server2,,,] 15710 --- [           main] o.a.k.clients.producer.ProducerConfig    : ProducerConfig values:
        acks = 1
        batch.size = 16384
        block.on.buffer.full = false
        bootstrap.servers = [10.102.35.99:9092]
        buffer.memory = 33554432
        client.id = producer-1
        compression.type = none
        connections.max.idle.ms = 540000
        interceptor.classes = null
        key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
        linger.ms = 0
        max.block.ms = 60000
        max.in.flight.requests.per.connection = 5
        max.request.size = 1048576
        metadata.fetch.timeout.ms = 60000
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.sample.window.ms = 30000
        partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
        receive.buffer.bytes = 32768
        reconnect.backoff.ms = 50
        request.timeout.ms = 30000
        retries = 0
        retry.backoff.ms = 100
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        send.buffer.bytes = 131072
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        timeout.ms = 30000
        value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer

2018-05-29 00:43:32.757  WARN [zipkin-server2,,,] 15710 --- [           main] o.a.k.clients.producer.ProducerConfig    : The configuration 'key.deserializer' was supplied but isn't a known config.
2018-05-29 00:43:32.757  WARN [zipkin-server2,,,] 15710 --- [           main] o.a.k.clients.producer.ProducerConfig    : The configuration 'value.deserializer' was supplied but isn't a known config.

And after a test call, I get a 2 messages at the configured kafka topic:

 contentTypeN"application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans"spanId"0ec6bc354a704e6a"
                                                                                                                   spanTraceId"0ec6bc354a704e6a"
                                                                                                                                                spanSampled"0"org.springframework.cloud.sleuth.stream.Hos▒10.102.35.9▒▒zipkin-server▒java.util.LinkedLis▒org.springframework.cloud.sleuth.Spa▒java.util.concurrent.ConcurrentHashMa▒Ȅ▒▒▒X▒▒▒ӥ▒▒Xjava.util.concurrent.ConcurrentLinkedQueu▒org.springframework.cloud.sleuth.Lo▒c▒Ȅ▒▒▒Xc▒ӥ▒▒Xhttp:/zipkin▒java.util.ArrayLis▒▒ɓ▒▒▒▒▒▒▒▒▒▒X▒▒▒▒ӥ▒▒Xs򢄥▒▒Xs▒ӥ▒▒Xhttp:/zipkin▒▒ɓ▒▒▒▒▒▒▒í▒▒
mvc.controller.clas▒ZipkinControlle▒ReqI▒29051800431▒mvc.controller.metho▒zipkinService▒spring.instance_i▒cldnp00604d.internalenv.corp:zipkin-server1:908▒▒ɓ▒▒▒▒▒▒▒▒▒▒▒▒
            ▒▒▒խ▒▒
http.pat▒/zipkin▒http.ur▒http://localhost:9082/zipkin▒http.metho▒GE▒http.hos▒localhos▒ cldnp00604d.internalenv.corp:zipkin-server1:908▒▒ɓ▒▒▒▒▒
PuTTYPuTTYPuTTYPuTTYPuTTY▒
                          contentTypeN"application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans"spanId"784fcd2ed7dfd2ea"
                                                                                                                                            spanTraceId"784fcd2ed7dfd2ea"
             spanSampled"0"org.springframework.cloud.sleuth.stream.Hos▒10.102.35.9▒▒zipkin-server▒java.util.LinkedLis▒org.springframework.cloud.sleuth.Spa▒java.util.concurrent.ConcurrentHashMa▒Ԅ▒▒▒X▒▒▒▒ӥ▒▒Xjava.util.concurrent.ConcurrentLinkedQueu▒org.springframework.cloud.sleuth.Lo▒s▒Ԅ▒▒▒Xs▒ӥ▒▒Xhttp:/zipkin▒java.util.ArrayLis▒▒ɓ▒▒▒▒▒▒▒▒▒▒▒▒
                               ▒▒▒ۭ▒▒
mvc.controller.clas▒ZipkinControlle▒mvc.controller.metho▒zipkinService▒spring.instance_i▒cldnp00604d.internalenv.corp:zipkin-server2:908▒▒ɓ▒▒▒▒▒

Next, I´ve tarted the Zipkin server with the command: 
           java -Dloader.path='kafka10.jar,kafka10.jar!/lib' -Dspring.profiles.active=kafka -Dzipkin.collector.kafka.bootstrap-servers=127.0.0.1:9092 -Dzipkin.collector.kafka.topic=sleuth -Dzipkin.collector.kafka.group-id=zipkin -cp zipkin.jar -Dlogging.level.zipkin=DEBUG org.springframework.boot.loader.PropertiesLauncher

The consumer config values are:
2018-05-29 01:16:02.762  INFO 16133 --- [           main] o.a.k.c.c.ConsumerConfig                 : ConsumerConfig values:
        auto.commit.interval.ms = 5000
        auto.offset.reset = earliest
        bootstrap.servers = [127.0.0.1:9092]
        check.crcs = true
        client.id =
        connections.max.idle.ms = 540000
        enable.auto.commit = true
        exclude.internal.topics = true
        fetch.max.bytes = 52428800
        fetch.max.wait.ms = 500
        fetch.min.bytes = 1
        group.id = zipkin
        heartbeat.interval.ms = 3000
        interceptor.classes = []
        internal.leave.group.on.close = true
        isolation.level = read_uncommitted
        key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
        max.partition.fetch.bytes = 1048576
        max.poll.interval.ms = 300000
        max.poll.records = 500
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.recording.level = INFO
        metrics.sample.window.ms = 30000
        partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
        receive.buffer.bytes = 65536
        reconnect.backoff.max.ms = 1000
        reconnect.backoff.ms = 50
        request.timeout.ms = 305000
        retry.backoff.ms = 100
        sasl.jaas.config = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        send.buffer.bytes = 131072
        session.timeout.ms = 10000
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer

I can see the Kafka consummer working with the debug logs:

2018-05-29 01:18:01.271 DEBUG 16133 --- [pool-2-thread-1] z.c.k.KafkaCollectorWorker               : Kafka polling returned batch of 0 messages.
2018-05-29 01:18:01.296 DEBUG 16133 --- [pool-2-thread-1] z.c.k.KafkaCollectorWorker               : Kafka polling returned batch of 1 messages.
2018-05-29 01:18:01.656 DEBUG 16133 --- [pool-2-thread-1] z.c.k.KafkaCollectorWorker               : Kafka polling returned batch of 1 messages.
2018-05-29 01:18:02.657 DEBUG 16133 --- [pool-2-thread-1] z.c.k.KafkaCollectorWorker               : Kafka polling returned batch of 0 messages.

But at the zipkin UI page, there are any traces...
![image](https://user-images.githubusercontent.com/8404180/40633472-4ed9e14c-62c6-11e8-99c0-67c78b819485.png)

Do someone have any idea of what am I doing wrong?

**Comment by marcingrzejszczak** [comment]
Yes. There is a number of wrong things here.

- You're using Dalston release train - it's ancient, please use Edgware.SR3.
- https://cloud.spring.io/spring-cloud-static/Edgware.SR3/single/spring-cloud.html#_features_2 - if you go through this document you'll see info that you shouldn't create a server by yourself
> If you depend on spring-rabbit or spring-kafka your app will send traces to a broker instead of http.
> Note: spring-cloud-sleuth-stream is deprecated and should no longer be used.
- Here you have an instruction on how to set things up properly - https://cloud.spring.io/spring-cloud-static/Edgware.SR3/single/spring-cloud.html#_sleuth_with_zipkin_via_rabbitmq_or_kafka on the client side
- On the server side here you have info on how to set things up for Kafka https://github.com/openzipkin/zipkin/tree/master/zipkin-autoconfigure/collector-kafka10 nad rabbit https://github.com/openzipkin/zipkin/tree/master/zipkin-collector/rabbitmq

Please follow those documents and you'll see how easy it is to reuse native features of Sleuth and Zipkin to send spans over a message broker

**Comment by danielsouza85** [comment]
@marcingrzejszczak thanks for helping.
I´ve changed the release train as you said, and the dependencies as show at the links you´ve sent.
Now it´s like this:
	    <dependency>
	       <groupId>org.springframework.cloud</groupId>
	       <artifactId>spring-cloud-starter-zipkin</artifactId>
	   </dependency>
	   <dependency>
	       <groupId>org.springframework.kafka</groupId>
	       <artifactId>spring-kafka</artifactId>
	   </dependency>
	   <dependency>
	       <groupId>org.springframework.cloud</groupId>
	       <artifactId>spring-cloud-sleuth-zipkin</artifactId>
	   </dependency>
	   <dependency>
	       <groupId>org.springframework.cloud</groupId>
	       <artifactId>spring-cloud-starter-stream-kafka</artifactId>
	   </dependency>
	   
	   	<properties>
	   		<spring-cloud.version>Edgware.SR3</spring-cloud.version>
		</properties>

With that, nothin happens. The aplication isn´t posting anything at the topic.

Is there some properties I have to set at aplication .properties?
Do you have a example project to make things clear?

**Comment by marcingrzejszczak** [comment]
I'm pretty sure you that you can see that the issue is improperly formatted. Can you please fix it? Have you set up the percentage sampling rate to 1.0 ?

**Comment by danielsouza85** [comment]
That finally worked. But after chances from Dalsin to Edgware, the traceId between the microservicos begins to change at this example, the comunicativo between microservices are made with rest calls.

**Comment by danielsouza85** [comment]
That finally worked. But after chances from Dalsin to Edgware, the traceId between the microservicos begins to change at this example, the comunicativo between microservices are made with rest calls.
